Pure Node.js? Node.js without frameworks? An overview
section-engineering-education/engineering-education pull request #1226
Opened 2021-01-08 13:18 UTC by kimkimani

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-12 04:53 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-21 03:15 UTC, cyberShaw requested changes
Great article, @kimkimani!

But I noticed that this article needs a lot of attention to grammar and readability. Please use a grammar checker to check grammar and make the changes that I've suggested in the comments.

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +A package is somebody else code. It is developed to help the community solve day-to-day problems easily and quickly without writing many code setups, especially for a large app.
```suggestion
A package is code written by someone else. It is developed to help the community solve day-to-day problems easily and quickly without re-writing code, especially for a large application.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +Open-source codes, frameworks, external libraries, and packages are available for most programming languages. Therefore, you only need basic skills to write your application logic. However, one thing
```suggestion
Open-source frameworks, external libraries, and packages are available for most programming languages. Therefore, you only need basic skills to write your application logic. However, one thing makes Node.js unique. It exposes you to running the core Node.js barebones. With vanilla Node.js, you can learn and build apps from scratch with no external frameworks.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +Let's take the example of building a Node.js server. In this case, you would use packages such as [Express.js](https://expressjs.com/) to create a server route and manage your HTTP server. Using such
```suggestion
Let's take the example of building a Node.js server. In this case, you would use packages such as [Express.js](https://expressjs.com/) to create server routes and manage your HTTP server. Using such a framework is terrific. It makes your server easy to set up, scalable, and easy to manage.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +Libraries make your work efficient by obstructing redundant functionalities concepts. Nevertheless, there is what goes on behind the scenes of these packages. They are developed using pure Node.js. T
```suggestion
Libraries make your work easier and more efficient by reducing redundant code. Behind the scenes, these libraries are developed using pure Node.js. This way, as you implement your HTTP server, the low-level Node.js logic is hidden from you. In such circumstances, your server logic does not directly interact with vanilla Node.js.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +They are reliable but shrink your learning exposure. Of course, you can't learn everything, but it is important to understand how your system works. Moreover, with that, you start asking yourself the
```suggestion
They are reliable but shrink your learning exposure. Of course, you can't learn everything, but it is important to understand how your system works. Therefore, it is a good experience for a developer to learn vanilla Node.js
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +When learning Node.js, you will typically use packages. As you level up, the urge to learn more might increase, you will realize that you can build APIs and Serves using raw Node.js. No packages or a
```suggestion
While learning Node.js, you will typically use packages. As you level up, the urge to learn more might increase, you will realize that you can build APIs and servers using vanilla Node.js, without the use of packages or third-party frameworks. This way, you utilize core Node.js runtime code.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +As developers, it's hard to imagine a day without using NPM. A package manager helps you install these packages and use them in your project as if they were build-in. Nevertheless, the NPM ecosystem
```suggestion
As developers, it's hard to imagine a day without using NPM (Node Package Manager). A package manager helps you install packages and use them in your project. Nevertheless, the NPM ecosystem drives you away and makes it tough to learn the pure Node.js functionalities.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +With packages, every project becomes scalable, fast to build, and easy to manage. This makes it challenging for professionals to dig deeper. Your application development life cycle is reduced to pack
```suggestion
With packages, every project becomes scalable, fast to build, and easy to manage. This makes it challenging for professionals to dig deeper. Your application development life cycle is reduced to package names. You call a package function and a set of parameters, and boom, you are done, very easy indeed.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +Packages are open-source, and frequently there will be issues with the packages, such as bugs. With the knowledge of pure Node.js, you stand in a position to address an issue to solve a bug or improv
```suggestion
Packages are open-source, and frequently there will be issues with the packages, such as bugs. With the knowledge of pure Node.js, you stand in a position to address an issue to solve a bug or improve a package. Package code is hosted in GitHub. You can create an issue or a pull request to post your improvement. With that, you become a package contributor, helping the community utilize your skills of using pure Node.js. As a contributor, you understand what happened behind the scene of Node.js packages.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +We mentioned packages having bugs, so if you develop an app with raw Node.js, How would you run into a bug contributed by a package. Packages have compatibility issues with certain projects due to pa
```suggestion
We mentioned packages having bugs, so if you develop an app with vanilla Node.js, How would you run into a bug contributed by a package. Packages have compatibility issues with certain projects due to package versioning specified in the NPM module dependencies. A no package app will not worry about version compatibility. You are the sole manager of your project's functions lifecycle.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +To put the raw Node.js knowledge, I have demonstrated how to create a simple web server. No frameworks, no Node package manager (NPM). Thus no `package.json` file as you have no dependency management
```suggestion
To put the raw Node.js knowledge, I have demonstrated how to create a simple web server. No frameworks, no Node package manager (NPM). Thus no `package.json` file as you have no dependency management — just a text editor and command line and using the functionalities that are core provided by Node.js itself.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +- Create an HTTP serve.
```suggestion
- Create an HTTP server.
```

2021-01-21 03:15 UTC, cyberShaw commented on articles/pure-node-js-no-frameworks-or-packages/index.md
> +Use the `createServer()` method to create a server instance. It takes a callback function as its second argument. The callback takes arguments, response, and request.
```suggestion
Use the `createServer()` method to create a server instance. It takes a callback function as its second argument. The callback takes the arguments: response, and request.
```

2021-01-22 09:59 UTC, kimkimani commented
@cyberShaw can you check this?

2021-01-22 22:47 UTC, hectorkambow commented
plagiarism check done

2021-01-27 09:06 UTC, cyberShaw commented
> @cyberShaw can you check this?

Yep, I'll review the changes today

2021-01-30 13:44 UTC, cyberShaw commented
Thank you for making the changes, @kimkimani!

2021-02-02 20:28 UTC, hectorkambow commented
@cyberShaw  Is this ready for a final ? Just wanted to double check. 👍

2021-02-03 19:42 UTC, cyberShaw commented
> @cyberShaw Is this ready for a final ? Just wanted to double check. 👍

It's ready for a final review, but it would be great if you could check readability once. That's why I haven't added the final review label 😅

2021-02-04 01:48 UTC, hectorkambow commented
@kimkimani  Im noticing that the article is a bit choppy and difficult to read. The 1st sentence alone. 

Please be sure to go over the grammar throughly - to avoid either a tiered payout or PR closure. 

Again, an article like this would really benefit from [a professional revision](https://www.fiverr.com/johnbatsoniii/proofread-and-edit-your-writing-for-publication?context_referrer=user_page&ref_ctx_id=9caf75ed-ce79-4880-b2fc-5b09e92e23d6&pckg_id=1&pos=1) - which we have listed a couple options in our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) with some rather economical prices.

Unfortunately, we can not provide revision services in our program and have to close articles that may take up too much time to polish up. 

🚀  

Thank you

2021-02-05 07:32 UTC, kimkimani commented
@hectorkambow Did some extensive grammar and flow checks. It should be good now.

2021-02-05 15:58 UTC, cyberShaw commented
> @hectorkambow Did some extensive grammar and flow checks. It should be good now.

I'll do another check

2021-02-11 17:50 UTC, cyberShaw commented
Added some edits for readability, in addition to the changes made by the author. Check this article, it's ready for final review. @hectorkambow

2021-02-11 18:17 UTC, merged