MongoDB vs. MySQL
section-engineering-education/engineering-education pull request #1257
Opened 2021-01-10 03:12 UTC by Pius1991

This fixes #1112

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-15 09:52 UTC, lalith1403 requested changes
When a person reads your article, expect them to know nothing in the beginning and know everything in your topic towards the end. You explain concepts well but don't go in-depth. Add some more additional material and let me know. 

Any statement that you make, base it on facts and reasoning.

2021-01-15 09:52 UTC, lalith1403 commented on articles/mongodb-vs-mysql/index.md
> +
Can you take a practical point of view? Compare the two with respect to two projects that you may have worked on. Giving a real-world example helps the reader understand the pros and cons better. The pros and cons that you mention are good. But, I wouldn't be interested in them until I know their applications.

2021-01-15 09:52 UTC, lalith1403 commented on articles/mongodb-vs-mysql/index.md
> +| Website | Mysql.com | Mongodb.com |
I think this feature is too generic.

2021-01-15 09:52 UTC, lalith1403 commented on articles/mongodb-vs-mysql/index.md
> +| Website | Mysql.com | Mongodb.com |
and redundant.

2021-01-15 09:52 UTC, lalith1403 commented on articles/mongodb-vs-mysql/index.md
> +| Command speed | MySQL is slower than MongoDB in executing the same commands like select, update, and insert. | MongoDB is faster in the execution of commands than MySQL. |
Saying A is greater than B, and B is lesser than A is the same thing. Avoid redundant comparisons. I want to know which aspect of c++ makes it slower than MongoDB? 

In the above table, avoid such redundancies. Wherever applicable, remove it or base the arguments with facts.

2021-01-20 02:36 UTC, hectorkambow commented
plagiarism check done

2021-01-25 16:00 UTC, hectorkambow commented
@Pius1991  

Please take notes on the suggestions made by the peer reviewer - this article is a great article topic - but the information Im coming across seems very basic and lacking substance. 

The conclusion seemed to barely wrap any thing up. 

I found myself reworking and rewording sentences to try and add some substance.

2021-01-25 16:17 UTC, hectorkambow commented
Please consider adding some more substantial information or examples to add some more value to the article and the community as a whole. 

The article was a bit rough around the edges - and it seemed like most information could be easily found elsewhere - we want to make sure we are putting together articles that solve major pain points with substance.

2021-01-25 17:43 UTC, Pius1991 commented
@hectorkambow  it's well noted, please re-open so that I can work on it.

2021-02-08 15:18 UTC, hectorkambow commented
@Pius1991 I'll be closing this PR just to make room in the queue. 

You can re-submit the "revised and improved" article in a new PR (by transferring the files over) and link this to it for us to know 👍 
Thank you.

2021-02-08 15:18 UTC, closed without merging