SQL-user-defined-functions
section-engineering-education/engineering-education pull request #1288
Opened 2021-01-11 20:04 UTC by rahulbanerjee26

First Draft of SQL-user-defined-functions

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-11 20:04 UTC, rahulbanerjee26 commented
This solves Issue #1284

2021-01-12 04:51 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-20 02:59 UTC, hectorkambow commented
plagiarism check done

2021-01-21 15:08 UTC, cyberShaw commented
@rahulbanerjee26, could you please re-upload the Hero Image with a 600 x 400 dimension? Also, make sure the hero image is in `jpg` format.

2021-01-21 15:43 UTC, cyberShaw requested changes
Good article, @rahulbanerjee26! I've suggested some changes to improve the readability of the article. Please implement them and we can move on to the next round of review.

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +- We use the **Create Function** command to define Functions. It is followed by the name of the function. In the above example, the name of the function is **scalar_func**.
Please include function names within backticks.

```suggestion
- We use the **Create Function** command to define Functions. It is followed by the name of the function. In the above example, the name of the function is `scalar_func`.
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +   In our above example, we have defined two Integer parameters **a** and **b**.
Please include param names also in backticks.

```suggestion
In our above example, we have defined two Integer parameters `a` and `b`.
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    END
```suggestion
    END;
```

It is a good practice to include a semi-colon at the end of an SQL statement. (Although it isn't compulsory in SQL Server)

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    )
```suggestion
    );
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    (4,5)
```suggestion
	    (4,5);
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +	    FROM TEST
```suggestion
	    FROM TEST;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +	    FROM TEST
```suggestion
		    FROM TEST;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    DROP FUNCTION dbo.scalar_func
```suggestion
    DROP FUNCTION dbo.scalar_func;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    DROP FUNCTION dbo.table_valued_func
```suggestion
    DROP FUNCTION dbo.table_valued_func;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    DECLARE @result AS INT
```suggestion
    DECLARE @result AS INT;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    SET @result = @a + @b
```suggestion
    SET @result = @a + @b;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    END
```suggestion
    END;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    DECLARE @num AS INT
```suggestion
    DECLARE @num AS INT;
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    CREATE FUNCTION is_even(@num AS INT)
Please add semi-colons at the appropriate places.

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +The **Alter** Keyword is used to update the function.
```suggestion
The **Alter** keyword is used to update the function.
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +The **DECLARE** Keyword is used to create a variable and the **SET** Keyword is used to initialize a variable.
```suggestion
The **DECLARE** keyword is used to create a variable and the **SET** keyword is used to initialize a variable.
```

The 'k' in keyword has to be in lowercase.

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +When you are dealing mith multiple if statements, it is better to use case statements. They make your code easier to read. Below is the general syntax for Case Statements
```suggestion
When you are dealing with multiple if statements, it is better to use case statements. They make your code easier to read. Below is the general syntax for Case Statements
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +The concept of Functions in SQL is like that in any other programming language like Python. The major difference being the way they are implemented. There are two main types of user-defined functions
```suggestion
The concept of functions in SQL is similar to other programming languages like Python. The major difference being the way they are implemented. There are two main types of user-defined functions in SQL based on the data they return:
```

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +- [SQL Server Management Studio](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15) to connect to your database.
```suggestion
- [SQL Server Management Studio](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15) to connect to your database
```

It is good practice to use periods `.` consistently.

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +Below is the definition of a simple Function. It takes in two numbers and returns their sum. Since this function returns a number, it is a scalar function.
> Below is the definition of a simple Function. 

Please change the **f** in Function to lowercase in all instances

2021-01-21 15:43 UTC, cyberShaw commented on articles/sql-user-defined-functions/index.md
> +    CREATE FUNCTION scalar_func
It would be beneficial to beginners if you could add code comments for all the code that you've used in this article.

2021-01-24 22:44 UTC, rahulbanerjee26 commented
Hi @cyberShaw! Thanks for the review! I have made the suggested changes.

2021-01-25 18:18 UTC, cyberShaw commented
Great job on the changes, @rahulbanerjee26! This article is ready for final review.

2021-01-25 19:50 UTC, rahulbanerjee26 commented
Thanks! @cyberShaw

2021-02-02 02:41 UTC, hectorkambow commented
@rahulbanerjee26  please be sure to go over the edits I made to the flow and the formatting for future reference. 
Great work. 👍  

Also one thing to note lets be sure to create PRs with Final drafts - I noticed you mentioned First Draft (when submitted) - in an effort to keep the queue clear and up to date - lets keep any and all drafts in our forked repos - we can make all the need commits there and push a PR with the final drafts 🚀 

cc @cyberShaw

2021-02-02 02:41 UTC, merged

2021-02-02 02:42 UTC, rahulbanerjee26 commented
@hectorkambow sounds good, I will keep that in mind moving forward