Merge pull request #2 from section-io/master
section-engineering-education/engineering-education pull request #1292
Opened 2021-01-12 05:06 UTC by Inyrkz

update branch

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-12 06:48 UTC, lalith1403 commented
Change the title of the pr to title of the article. Also, check the boxes in the checklist whichever is applicable.

2021-01-12 14:25 UTC, Inyrkz commented
Added a folder image-classifier-keras.
Wrote an article about how to build an Image Classifier using Keras with a TensorFlow backend.
There are images of code output in the folder along with memes to aid explanation. 
Some images are original while others are from the internet, the sources have been provided.

2021-01-12 14:31 UTC, lalith1403 commented
Can you add a hero image?

2021-01-12 20:02 UTC, Inyrkz commented
This fixes #1072

2021-01-26 00:00 UTC, hectorkambow commented
plagiarism check done

2021-01-27 12:48 UTC, lalith1403 requested changes
Well written article. Implement the changes and we can move onto the final round of review.

2021-01-27 12:48 UTC, lalith1403 commented on articles/image-classifier-keras/index.md
> +### Importing libraries and exploring the dataset
Before you begin with the tutorial, ensure you insert a link to your Colab file with the outputs. This way, a person who wants to check your project can do so without having to go through the entire article,

2021-01-27 12:48 UTC, lalith1403 commented on articles/image-classifier-keras/index.md
> +model.add(Dropout(0.5))
My experience says a dropout of 0.2-0.25 is ideal. Anything above that leads to loss of data and bad training. 0.5 is huge,

2021-01-27 12:49 UTC, lalith1403 commented
Also, we will need a short bio and a headshot pic of you. Look at the authors folder for more information.

2021-01-27 12:54 UTC, lalith1403 commented on articles/image-classifier-keras/index.md
> +We will use a batch size of 32, and the class mode is either *binary* or *categorical*. *Binary* is for two output classes, while categorical is for more than two classes. Since we are working with o
Don't use future tense. Instead, write it as: We use a batch size of 32... I observed it throughout your article. Needs to be changed at all occurrences.

2021-02-01 14:58 UTC, lalith1403 commented
Are the changes done? Notify us after all the changes are made.

2021-02-06 08:23 UTC, Inyrkz commented
All the changes have been made.

2021-02-06 08:23 UTC, Inyrkz commented
All the changes have been made.

2021-02-08 16:23 UTC, merged