connect B4A-PHP Init
section-engineering-education/engineering-education pull request #1293
Opened 2021-01-12 05:16 UTC by tambastar

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-13 14:53 UTC, tambastar commented
this fixes #1251

2021-01-26 15:46 UTC, hectorkambow commented
@Tsanguu  will be reviewing this article -  🚀

2021-01-26 15:51 UTC, hectorkambow commented
plagiarism check done @Tsanguu

2021-01-26 15:55 UTC, Tsanguu commented
Working on it @hectorkambow

2021-01-28 07:19 UTC, Tsanguu reviewed
@tambastar Great tutorial. The content is well detailed. There are a few issues I have pointed on that can improve this tutorial. Check the recommendations. Work on them so that we can move to the next step.

2021-01-30 10:05 UTC, tambastar commented
Thank you @Tsanguu. all changes suggested have been worked on accordingly

Regards

2021-02-01 02:21 UTC, tambastar commented
@Tsanguu  sorted

2021-02-02 06:50 UTC, Tsanguu requested changes
There are some areas I suggest you work on to improve the tutorial.

The B4A code provided is running. There is an issue; the B4A app cannot connect to the server. To make it work, you have to edit the manifest file. Find the solution to this issue on the [B4A forum](https://www.b4x.com/android/forum/threads/android-usescleartexttraffic-true-need-help.106915/.
).

Once the server's connection is made, the app gives positive feedback, yet no data is inserted in the database.
I suggest that you verify that the code or the final product is working as expected.

2021-02-04 04:03 UTC, tambastar commented on Connect-Basic4Android-BAndroid-development-too- to-MySQL-Database-Using-PHP/index.md
> +* Kindly follow this [Tutorial](https://www.section.io/introduction-to-android-app-development-basic4android-b4a-part1).
this link is invalid. Kindly check on it.
i have renamed to one that is redirecting correctly

2021-02-04 04:04 UTC, tambastar commented on Connect-Basic4Android-BAndroid-development-too- to-MySQL-Database-Using-PHP/index.md
> +* Click next for the below windows.
done

2021-02-04 05:09 UTC, tambastar commented
I have done the changes requested.
Kindly put right URL for the app to communicate
@Tsanguu

2021-02-04 19:35 UTC, Tsanguu approved these changes

2021-02-04 19:41 UTC, Tsanguu commented
@hectorkambow This article is ready for final review.

2021-02-09 05:39 UTC, WanjaMIKE commented
@Tsanguu I added for you the ready for final review label

2021-02-09 17:13 UTC, hectorkambow commented
@tambastar  

Please take note of the changes made during the final review - there were some changes to the intro and I found some place a bit tough to go through in the article as well. 

cc @Tsanguu  Please also take keen note of my changes to better improve any future revisions 🚀

2021-02-09 17:13 UTC, merged