Introduction To Network Scanning Using Nmap
section-engineering-education/engineering-education pull request #1295
Opened 2021-01-12 08:44 UTC by jumamiller

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [*] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [*]  Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [*]  Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [*]  Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [*]  Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
-[*]  Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [*]  Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [*]  Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [*]  In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [*]  Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [*]  Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [*]  Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [*]  Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1263

2021-01-27 13:01 UTC, lalith1403 requested changes
Well written article. Congratulations! Make the few requested changes and we can proceed to the next round of review,

2021-01-27 13:01 UTC, lalith1403 commented on articles/nmap-network-scanner/index.md
> +#### Step 2: Install Network Mapper(Nmap)
Ensure spaces before parentheses. Install Network Mapper (Nmap). I observed it throughout your article. Change it wherever applicable.

2021-01-27 13:01 UTC, lalith1403 commented on articles/nmap-network-scanner/index.md
> +From that point, you can send a reset packet(RST); consequently, the server assumes that an error occurred while establishing a connection while the open port remains open and ready/vulnerable to exp
space after reset packet.

2021-01-27 13:01 UTC, lalith1403 commented on articles/nmap-network-scanner/index.md
> +The client may send several SYN packets to the server, consuming a lot of resources. This way, legitimate requests cannot be handled. This is one-way of how DOS(Denial of service is achieved).
space after DOS.

2021-01-27 13:34 UTC, jumamiller commented
@lalith1403, done!

2021-01-27 13:36 UTC, lalith1403 approved these changes

2021-02-02 16:31 UTC, hectorkambow commented
plagiarism check done

2021-02-02 16:32 UTC, hectorkambow commented
just an FYI @jumamiller  The 3rd plagiarism check had a few red flags but I believe most of them were needed dependancies in the code. 
But just an FYI.

2021-02-02 16:47 UTC, jumamiller commented
@hectorkambow noted with thanks!

2021-02-02 17:24 UTC, merged