Simclr: A simple framework for contrastive learning of visual represe…
section-engineering-education/engineering-education pull request #1296
Opened 2021-01-12 09:29 UTC by Bayler

…ntations

This fixes #1224

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-27 13:20 UTC, lalith1403 requested changes
Very well explained. Can we come up with code to implement SimCLR framework? That would be amazing (in another article). In this article, there are a few places where more information and links are required. Add them wherever you feel more information is necessary. I have highlighted a few such places.

2021-01-27 13:20 UTC, lalith1403 commented on articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/index.md
> +Contrastive learning is a very active area in machine learning research. It is a self-supervised method used in machine learning to put together the task of finding similar and dissimilar things. By
An introduction to self-supervised learning is required.

2021-01-27 13:20 UTC, lalith1403 commented on articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/index.md
> +SimCLR is a framework developed by Google which demonstrated the implications of contrastive learning. It is a high-impact work that eliminates specialized architectures and memory banks, usually use
Insert links to data augmentation, Resnet-50.

2021-01-27 13:35 UTC, Bayler commented
> 
> 
> Very well explained. Can we come up with code to implement SimCLR framework? That would be amazing (in another article). In this article, there are a few places where more information and links are required. Add them wherever you feel more information is necessary. I have highlighted a few such places.

@lalith1403  Sure. That would be amazing. I'll do that in my next article as a follow-up. Let me work on the few revisions

2021-01-28 18:12 UTC, hectorkambow commented
Plagiarism check done

2021-01-31 15:06 UTC, Bayler commented
@lalith1403 finished with the revisions

2021-02-02 18:40 UTC, merged