Hashtable implementation using CRC32 algorithm
section-engineering-education/engineering-education pull request #1313
Opened 2021-01-13 10:48 UTC by jerimkaura

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1289

2021-02-08 12:26 UTC, lalith1403 requested changes
It is not clear which are class methods and which are actual functions. Also, you need to create an object of the class and run it. It would help if you explain every single step in detail. I see each section is disconnected from each other. 

Also, paste the expected output from the terminal. Not the _passed the tests_ output, but something that explains the concept.

2021-02-08 12:26 UTC, lalith1403 commented on articles/hashtables-implementation-using-CRC32-algorithm/index.md
> +We have successfully created the data members. We now proceed to write our dunder methods for overwriting some of the Python built-in function behaviors. This implementation is based on the following
Explicitly mention double under methods are also known as dunder methods.

2021-02-08 12:26 UTC, lalith1403 commented on articles/hashtables-implementation-using-CRC32-algorithm/index.md
> +def __len__(self) -> int:
Check the indentation. I think a tab should right indent this.

2021-02-08 12:26 UTC, lalith1403 commented on articles/hashtables-implementation-using-CRC32-algorithm/index.md
> +        self.table: List[(T, T)] = [None] * self.table_size
The variable T is not defined. Can you check the entire code once? I am getting errors
1. Indentation errors
2. Name Errors. 

Add a repl link which will ensure that we know the code is working. For example:

Run this code [here](https://repl.it/@lalithNarayan/SuperiorDeficientType).

2021-02-08 12:26 UTC, lalith1403 commented on articles/hashtables-implementation-using-CRC32-algorithm/index.md
> +        (à la Python's dict's {key1: value1, key2: value2, ..., keyN: valueN})
What is this? **à la** in à la Python's dict's?

2021-02-10 20:00 UTC, hectorkambow commented
plagiarism check done

2021-02-13 00:27 UTC, merged