Top Node.js Monitoring Tools
section-engineering-education/engineering-education pull request #1315
Opened 2021-01-13 11:17 UTC by EKahuha

this fixes #1065

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-20 18:56 UTC, LinusMuema requested changes
Hi @EKahuha 
This is a great article. However, your language is quite complex and it would be better to simplify it by using simpler words apart from the technical ones. 
Just check the one suggestion and I have, otherwise, everything else checks out :+1:

2021-01-20 18:56 UTC, LinusMuema commented on articles/top-node.js-monitoring-tools/index.md
> +When applications don't work as efficiently as they should, the responsibility of carrying out preventive and curative maintenance solely lies on your shoulders as a developer. Customers using your a
This first statement is a bit long. You could find a way to rephrase it and shorten it.
Same as other few statements in the article. You can use Hemingway to help you

2021-01-27 13:48 UTC, EKahuha commented
@LinusMuema, I have updated this article.

2021-02-01 07:28 UTC, LinusMuema commented
Hi @hectorkambow
You could give this article a plag check and final review.

2021-02-01 15:05 UTC, hectorkambow commented
plagiarism check done

2021-02-01 15:05 UTC, hectorkambow commented
Please be sure to go over some of minor edits I made for flow @EKahuha  
cc @LinusMuema  🚀

2021-02-01 15:06 UTC, merged