Understanding the Software Development Life Cycle (SDLC)
section-engineering-education/engineering-education pull request #1318
Opened 2021-01-13 14:09 UTC by mbaabuones

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1269 .

2021-01-20 03:07 UTC, hectorkambow commented
plagiarism check done

2021-01-25 20:40 UTC, adrianmurage requested changes
@mbaabuones 
Great article. I left a few notes, kindly make the necessary changes

2021-01-26 13:00 UTC, mbaabuones commented on articles/understanding-software-development-life-cycle/index.md
> +In the current digital era, many software applications are being developed to solve various real-life problems. If you are a new developer, you would probably want to know the steps that can be taken
Noted. Thank you.

2021-01-26 13:01 UTC, mbaabuones commented on articles/understanding-software-development-life-cycle/index.md
> +This article takes you through the software development life cycle, which consists of the main stages of software development. It also provides an overview of the model processes in software developm
Done.

2021-01-26 13:01 UTC, mbaabuones commented on articles/understanding-software-development-life-cycle/index.md
> +A software development life cycle (SDLC) refers to the process followed by software developers to develop a high-quality software product. It can also be termed as a software development process. SDL
Done.

2021-01-26 13:01 UTC, mbaabuones commented on articles/understanding-software-development-life-cycle/index.md
> +SDLC can be used by various people in the organization such as software engineers, developers, and cross-function teams. Developers and software engineers use it to create effective plans and designs
Done.

2021-01-26 13:01 UTC, mbaabuones commented on articles/understanding-software-development-life-cycle/index.md
> +This is the implementation stage that involves developing the software. Here, the design of the product is transformed into reality by creating some source codes. The design document specification pr
Done.

2021-01-26 13:03 UTC, mbaabuones commented on articles/understanding-software-development-life-cycle/index.md
> +After ensuring that all the customer requirements have been met, the developers deploy the software for use. Before actual deployment is done, the software should be documented for future reference.
I have revised this section to provide a deeper understanding of the statement.

2021-01-26 13:03 UTC, mbaabuones commented
@adrianmurage I have finished working on the changes.

2021-01-27 13:04 UTC, adrianmurage commented
@mbaabuones 
Kindly add a hero image

2021-01-27 15:05 UTC, mbaabuones commented
> 
> 
> @mbaabuones
> Kindly add a hero image

@adrianmurage I have added a hero image.

2021-01-27 18:41 UTC, adrianmurage commented
@mbaabuones 
As always, great job with this. Keep at it!
@hectorkambow this article is ready for final review.

2021-02-03 21:08 UTC, merged