Problem Framing in Machine Learning
section-engineering-education/engineering-education pull request #1326
Opened 2021-01-13 19:08 UTC by collins-a

Article as index.md
Hero image as hero.jpg

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-13 19:09 UTC, collins-a commented
This fixes #1183

2021-02-08 13:04 UTC, lalith1403 requested changes
Well written. I feel more information is required under a few sections. The content is a bit generic and can benefit from being more targeted and unique. Add more information wherever you feel appropriate to improve the article.

2021-02-08 13:04 UTC, lalith1403 commented on articles/problem-framing/index.md
> +Problem framing is a key step in the machine learning workflow. Since it’s arguably less technical than other stages in a machine learning workflow, it might be inaccurately perceived as an easy step
You mention problem framing and then data analysis. So does data collection and understanding sources of data come under problem framing as well? Can you elaborate on some of the issues under data collection?

2021-02-08 13:05 UTC, lalith1403 requested changes
Well written. I feel more information is required under a few sections. The content is a bit generic and can benefit from being more targeted and unique. Add more information wherever you feel appropriate to improve the article.

2021-02-10 20:06 UTC, hectorkambow commented
plagiarism check done

2021-02-14 13:31 UTC, collins-a commented
@lalith1403 thank you, as usual. I struggled to get in-depth with this topic because a great number of the sources I found were barebones. 

Still, I have added some content to various sections of the best practices. I hope it suffices. Cheers!

2021-02-17 15:48 UTC, lalith1403 approved these changes

2021-02-18 19:58 UTC, merged