An Overview of Compiler Design
section-engineering-education/engineering-education pull request #1339
Opened 2021-01-14 14:33 UTC by mbaabuones

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1272 .

2021-01-15 10:00 UTC, cyberShaw requested changes
Great article, @mbaabuones! I've suggested some minor changes. Please implement them and we can move on to final review.

2021-01-19 14:20 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +Computers are important elements in our lives because they run applications that solve many real-life problems. Computer programmers play the role of writing codes (using programming languages) for c
Done.

2021-01-19 14:20 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +In this article, we learn about the fundamental aspects of compiler design. Some of the aspects covered include language processing systems, compiler design architecture, and phases of a compiler. Th
Done.

2021-01-19 14:21 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +A compiler is a computer program that transforms a source language (high-level language (HLL)) into a machine language (low-level language (LLL)) without changing the program meaning. It is simply an
Done.

2021-01-19 14:21 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +
Done.

2021-01-19 14:21 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +* **Assembler:** This tool uses the output of the compiler as its input. In this tool, the assembly code is transformed into a machine code. The output produced by the assembler can be referred to as
Done.

2021-01-19 14:21 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +* **Linker:** This tool transforms the output of the assembler into an executable machine code. Here, all the program parts are linked to enhance execution.
Done.

2021-01-19 14:22 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +[Image Source: Tutorials Point](https://www.tutorialspoint.com/compiler_design/images/language_processing_system.jpg)
Done.

2021-01-19 14:22 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +An internal representation (IR) of the program is generated and analyzed before it is sent to the synthesis phase. The analysis part of the architecture consists of phases such as preprocessing, lexi
Yes it is. Thank you for the correction.

2021-01-19 14:23 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +* **Semantic analysis:** This phase checks whether the language rules in the parse tree have been followed. Semantic information is added to the parse trees produced in the syntax analysis. The seman
Done.

2021-01-19 14:23 UTC, mbaabuones commented on articles/an-overview-of-compiler-design/index.md
> +* **Intermediate code generation:** This phase involves generating an intermediate code that can be translated into the final machine code.
Done.

2021-01-19 14:24 UTC, mbaabuones commented
@cyberShaw I have finished working on the changes.

2021-01-23 22:35 UTC, cyberShaw commented
@mbaabuones Please add a hero image to this.

2021-01-24 21:13 UTC, hectorkambow commented
plagiarism check done

2021-01-25 14:56 UTC, mbaabuones commented
> 
> 
> @mbaabuones Please add a hero image to this.

@cyberShaw Done.

2021-01-25 17:51 UTC, cyberShaw approved these changes

2021-01-25 17:51 UTC, cyberShaw commented
@mbaabuones Hero image should be in JPG. I've converted it and uploaded properly in jpg in commit: 466feec. Please ensure that you do it properly next time.

2021-01-26 06:30 UTC, mbaabuones commented
> 
> 
> @mbaabuones Hero image should be in JPG. I've converted it and uploaded properly in jpg in commit: [466feec](https://github.com/section-io/engineering-education/commit/466feec5489c46fbb8682dd239a1a761fc9e4427). Please ensure that you do it properly next time.

@cyberShaw Noted. Thank you for the correction.

2021-02-04 13:29 UTC, hectorkambow commented
> > @mbaabuones Hero image should be in JPG. I've converted it and uploaded properly in jpg in commit: [466feec](https://github.com/section-io/engineering-education/commit/466feec5489c46fbb8682dd239a1a761fc9e4427). Please ensure that you do it properly next time.
> 
> @cyberShaw Noted. Thank you for the correction.

jpg is best but PNG also works as well. 

@mbaabuones  cc @cyberShaw  👍

2021-02-04 13:29 UTC, merged

2021-02-04 13:48 UTC, cyberShaw commented
> > > @mbaabuones Hero image should be in JPG. I've converted it and uploaded properly in jpg in commit: [466feec](https://github.com/section-io/engineering-education/commit/466feec5489c46fbb8682dd239a1a761fc9e4427). Please ensure that you do it properly next time.
> > 
> > 
> > @cyberShaw Noted. Thank you for the correction.
> 
> jpg is best but PNG also works as well.
> 
> @mbaabuones cc @cyberShaw 👍

Understood 👍🏼