Node.js CLI Input
section-engineering-education/engineering-education pull request #1342
Opened 2021-01-14 15:31 UTC by zolomohan

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1306

2021-01-20 12:45 UTC, adrianmurage commented
@hectorkambow 
kindly run a plagiarism check

2021-01-23 17:51 UTC, hectorkambow commented
[Node.js CLI Input #1342.pdf](https://github.com/section-io/engineering-education/files/5860672/Node.js.CLI.Input.1342.pdf)

Plagiairism check done - @zolomohan  The % is a bit higher than usual - please review and make sure to add any needed sources and or edit 🚀

2021-01-24 17:19 UTC, zolomohan commented
@hectorkambow @adrianmurage I edited some lines to avoid plagiarism.

2021-01-26 09:38 UTC, adrianmurage requested changes
Great article @zolomohan 
I've left you a few changes to make.
Ping me when you're done.

2021-01-26 09:38 UTC, adrianmurage commented on articles/nodejs-cli-input/index.md
> +In this tutorial, we will learn how to get a user input in a Node.js CLI application. To do this, you'll need to listen to `STDIN` (Standard Input), which Node.js exposes as `process.stdin`, a readab
```suggestion
In this tutorial, we will learn how to get user input in a Node.js CLI application. To do this, you'll need to listen to `STDIN` (Standard Input), which Node.js exposes as `process.stdin`, a readable stream.
```

2021-01-26 09:38 UTC, adrianmurage commented on articles/nodejs-cli-input/index.md
> +- You should have a basic understanding of the JavaScript language.
```suggestion
- You should have an understanding of the JavaScript language.
```
Using the term "basic" might discourage someone who is struggling to understand the concepts you've written about.

2021-01-26 09:40 UTC, zolomohan commented
@adrianmurage I've applied those suggestions.

2021-01-26 09:43 UTC, adrianmurage approved these changes

2021-01-26 09:43 UTC, adrianmurage commented
@hectorkambow 
This article is ready for final review

2021-02-04 15:18 UTC, merged