Python static typing
section-engineering-education/engineering-education pull request #1364
Opened 2021-01-15 12:44 UTC by jerimkaura

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1316

2021-02-02 07:16 UTC, lalith1403 commented
I think you have uploaded the earlier article on hash tables. Can you check and upload the correct article.

2021-02-05 06:54 UTC, jerimkaura commented
I have uploaded the right files

2021-02-12 16:21 UTC, lalith1403 requested changes
Make the changes requested, and we can move to the final round of review. This is a very informative article.  Well done :)

2021-02-12 16:21 UTC, lalith1403 commented on articles/python-static-typing/index.md
> +**4.2. List**
Use H4 and beyond for further subheadings. 

```suggestion
#### 4.2 List
```

2021-02-12 16:21 UTC, lalith1403 commented on articles/python-static-typing/index.md
> +Type annotations is a new feature added by [PEP 484](https://www.python.org/dev/peps/pep-0484/) to python version 3.5 and above. They give a code reader a hint on what type a variable or a function r
```suggestion
Type annotations is a new feature added by [PEP 484](https://www.python.org/dev/peps/pep-0484/) to python version 3.5 and above. They give the code reader hints on the return type of variable or function. Type annotations can be performed on variables and functions as well.
```

2021-02-12 16:21 UTC, lalith1403 commented on articles/python-static-typing/index.md
> +```
Mention the output of the code as well.

2021-02-12 16:21 UTC, lalith1403 commented on articles/python-static-typing/index.md
> +```
Mention the output of the code as well. Do it for all code snippets in the article.

2021-02-14 05:09 UTC, jerimkaura commented
I have done the changes requested.

2021-02-18 18:29 UTC, jerimkaura commented
Fixed merge conflict on PR #1562

2021-02-19 01:19 UTC, hectorkambow commented
Merge conflict

2021-02-19 01:19 UTC, closed without merging