Deconstructing Shared Nothing and Shared Disk Clustering Architectures
section-engineering-education/engineering-education pull request #1365
Opened 2021-01-15 14:32 UTC by EKahuha

this fixes #1195

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-02-02 07:33 UTC, lalith1403 commented on articles/deconstructing-shared-nothing-and-shared-disk-clustering-architectures/index.md
> +
Add a table summarizing the features of the 2 types of clustering. That makes this article crisp and clear.

2021-02-02 07:34 UTC, lalith1403 requested changes
Very well written article. A table indicating the differences would ensure the reader is left with a clean way to consume the information present.

2021-02-04 13:17 UTC, EKahuha commented
@lalith1403, I have updated this article.

2021-02-04 16:18 UTC, hectorkambow commented
plagiarism check done

2021-02-04 18:38 UTC, hectorkambow commented
@EKahuha  
Great overall article - seems really informative. Just found myself stumbling or having to re-read certain parts in the 
Please take keen notes on the changes I made to the intro (upper half) . 

To "save" time I did most of the edits - but otherwise I would have asked for more revisions. 

The bottom half was actually well done. 

cc: @lalith1403  please go through the edits as well for future reference. 🚀

2021-02-04 18:38 UTC, merged