Python projects for beginners part 1
section-engineering-education/engineering-education pull request #1371
Opened 2021-01-15 17:55 UTC by Anitaachu

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-15 18:01 UTC, Anitaachu commented
This fixes 1371

2021-01-15 18:25 UTC, lalith1403 commented
Mention the issue number. You seem to have mentioned the PR number.

2021-01-15 18:33 UTC, Anitaachu commented
Sorry for the mistake, changes made. Thank you.

2021-02-02 08:13 UTC, lalith1403 requested changes
Make the requested changes and we can move on the next round of review.

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +At this point, I believe you've learned the basic concept of Python theoretically? *Great*! Now we will be testing these new skills you have learned by building a simple project to aid your understan
Why a ? after theoretically?

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +      print("\nFor easy, you have 6 chances to guess a number between 1-10. \nFor meduim, you have 4 chances to guess a number between 1-20. \nFor hard, you have 4 chances to guess a number between 1
Instead of using newline character, use three print statements to improve readability

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +![guessing game](Guessinggame.png)
```suggestion
![guessing game](/engineering-education/python-projects-for-beginners/Guessinggame.png)
```

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +![guessing game](Guessinggame.png)
Make the changes for all image paths.

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +Now let's move to something a bit more complex, building a *guessing game* with different levels where users will be able to choose the desired level and given limited chances to guess.
Add a heading to indicate that this is the second project. Use headers and sub headers suitably.

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +Notice, in this simple game, we have used a few methods in Python, such as *random, function, input, conditional statements.* I hope you properly understand how these concepts work in Python.
After the first project, add a repl link where the reader can directly go and run the code. 
For example: 

You can run the code [here](https://repl.it/@lalithNarayan/SoreMediumblueMemory#main.cs)

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +The ***randint*** method returns an integer from a random range. Notice the indentations? In Python, indentation is important, and improper indentation will cause an error, or the codes may not run a
After the second project, add a repl link where the reader can directly go and run the code. 
For example: 

You can run the code [here](https://repl.it/@lalithNarayan/SoreMediumblueMemory#main.cs)

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +In further tutorials, we'll work on a more complex project and use more Python methods and tools. I hope you followed along.
Add a conclusion section.

2021-02-02 08:13 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +If this is your first Python project, there are tons of code editors you could use, [Visual studio code](https://code.visualstudio.com/download), [pycharm](https://www.jetbrains.com/pycharm/download/
there are tons of -> there are several editors

2021-02-02 08:17 UTC, lalith1403 commented on articles/python-projects-for-beginners/index.md
> +## Introduction
Also, we use headers H3 and beyond in all the articles. Therefore, update all the headers.

2021-02-09 23:14 UTC, Anitaachu commented
All changes have been made. Thank you.

2021-02-10 20:23 UTC, hectorkambow commented
plagiarism check done

2021-02-12 16:25 UTC, lalith1403 approved these changes

2021-02-13 19:38 UTC, merged