Introduction To Wireless Networking
section-engineering-education/engineering-education pull request #1377
Opened 2021-01-15 19:58 UTC by jumamiller

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1303

2021-02-10 20:32 UTC, hectorkambow commented
plagiarism check done

2021-02-12 16:50 UTC, lalith1403 requested changes
This article needs significant editing. Go through the articles published already, and you will get a feel for the flavor of writing that is acceptable. I have highlighted significant issues. Make changes throughout the article. I have highlighted a type of error only once. There are multiple occurrences of the errors mentioned. Be sure to rectify all such occurrences of the error.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +Wireless networks have exploded the world currently, all the same, we all hate wires all over, or don't we? Or perhaps not!
Change the introductory sentence. Make it a bit more formal.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +Nowadays, the laptop price is affordable, or isn't it?
This sentence does not make sense.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +
Pay attention to the formatting.

![image](https://user-images.githubusercontent.com/26842636/107795096-43754d80-6d7e-11eb-83e2-ddcfe6ba2d95.png)

It looks odd if each sentence occupies a line each.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +
Make the change throughout the article.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +You ought to have also learned that computer networks have five components.
```suggestion
Computer networks have five components.
- message
- sender
- receiver
- protocol
- transmission medium
```

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +They include  ***message, sender, receiver, protocol, and Transmission media***.
```suggestion

```

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +They include  ***message, sender, receiver, protocol, and Transmission media***.
do you mean transmission medium?

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +Obviously, in wireless, we don't use cables but radio waves instead.
```suggestion
In wireless networks, we use radio waves instead of cables.
```

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +But do you remember **Carrier-sense multiple access with collision detection (CSMA/CD)** used in half-duplex networks?
Assume the reader has no knowledge of CSMA and CSMA/CD. You need to explain these.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +The main reason why wireless is half-duplex is because of sending and receiving on a single frequency.
```suggestion
The reason why wireless is half-duplex is that sending and receiving happens on the same frequency. 
```

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +### How does a wireless network works?
How does a wireless network work?

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +While learning about computer networks, you might have come across radio frequency technology.
Don't come across as expecting the reader to know everything in the article. Using phrases such as you might have come across, it is obvious, etc., sounds discouraging. Instead, use encouraging phrases. I have observed this throughout the article.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +Radio Frequency (RF) refers to the electromagnetic signals sent wirelessly to allow for communication.
Use a proper definition here for RF.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +These signals are unique and, therefore, cannot interfere with each other.
What do you mean the signals are unique?

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +>This technology is beyond the scope of this article. Therefore we won't discuss it in-depth, but you're free to find good books on the topic.
Why is this under a quote section?

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +>This technology is beyond the scope of this article. Therefore we won't discuss it in-depth, but you're free to find good books on the topic.
Suggest resources.

2021-02-12 16:50 UTC, lalith1403 commented on articles/introduction-to-wireless-networking/index.md
> +How it works is that wireless networks create a two-way data communication channel.
Don't begin a sentence with how, why, what, etc.,

2021-02-12 17:02 UTC, hectorkambow commented
@jumamiller  Be sure to go through our resources page to help improve all future articles. 

https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md

2021-02-12 17:44 UTC, jumamiller commented
@lalith1403, this is my first article(no codes), was quite challenging to write. Thanks for the suggestions! working on them ASAP!

2021-02-15 15:59 UTC, jumamiller commented
@lalith1403, I've made major changes to this article, check it out!

2021-02-23 12:38 UTC, WanjaMIKE commented
@jumamiller I also noted similar mistakes as @lalith1403 . The suggestions we make are aimed at helping deliver better articles rather than discouraging you.

2021-02-23 19:58 UTC, hectorkambow commented
@lalith1403  

Just wanted to get a status on this PR 👍

2021-02-24 19:06 UTC, lalith1403 commented
Will update by EOD (Indian time)

2021-02-25 16:59 UTC, merged