Implementing Bottom Sheet Dialogs Using Android Studio
section-engineering-education/engineering-education pull request #1383
Opened 2021-01-16 09:37 UTC by kimkimani

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
Fixes #1230

2021-02-12 07:57 UTC, WanjaMIKE commented on articles/bottom-sheet-dialogs-using-android-studio/index.md
> +Go ahead and add a button in your `main_activity.xml` file.
do you mean `activity_main.xml`. This is what I see in your github repo `https://github.com/kimkimani/ModalBottomSheet/tree/master/app/src/main/res/layout`

2021-02-12 08:19 UTC, WanjaMIKE commented on articles/bottom-sheet-dialogs-using-android-studio/index.md
> +Run the app to test if the sheet is working. Clicking the button will trigger the dialog to slide from the bottom to the top.
You can say Bottom Sheet to avoid confusion.

2021-02-12 08:47 UTC, WanjaMIKE commented on articles/bottom-sheet-dialogs-using-android-studio/index.md
> +Add a button in the activity XML, declare it, and set `OnClick` Listener as we explained when using `BottomsheetDialog`.
activity_main.xml

2021-02-12 08:50 UTC, WanjaMIKE commented on articles/bottom-sheet-dialogs-using-android-studio/index.md
> +#### Laying out the bottom sheet design
Could you replace instances of `bottom sheet` with `Bottom Sheet`

2021-02-12 08:52 UTC, WanjaMIKE requested changes
Kindly, review the above minor suggestions. Thanks

2021-02-12 09:34 UTC, kimkimani commented
Made some updates @WanjaMIKE

2021-02-17 19:01 UTC, WanjaMIKE approved these changes

2021-02-19 01:26 UTC, hectorkambow commented
plagiarism check done

2021-02-19 18:02 UTC, merged