Cookie Vs Token-based authentication
section-engineering-education/engineering-education pull request #1402
Opened 2021-01-17 13:39 UTC by ReactifyStudio

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-17 13:41 UTC, ReactifyStudio commented
This fixes #1078

2021-01-17 13:41 UTC, ReactifyStudio commented
@zolomohan , check my new PR

2021-02-02 12:34 UTC, ReactifyStudio commented
@zolomohan this PR is ready. @hectorkambow PayPal fixed.

2021-02-02 17:35 UTC, zolomohan commented
@hectorkambow kindly run a plagiarism check.

2021-02-02 17:36 UTC, hectorkambow commented
@ReactifyStudio  please only have one of your articles open at a time. 👍

2021-02-06 16:46 UTC, hectorkambow commented
plagiarism check done @zolomohan

2021-02-06 18:49 UTC, zolomohan requested changes
@ReactifyStudio Please go through these minor revisions and ping me when you are done.

2021-02-06 18:49 UTC, zolomohan commented on articles/cookie-token-auth/index.md
> +The anatomy of a JWT token comprises three parts separated by dots(.). The three parts include the JWT header, the JWT payload, and its signature, respectively (`header.payload.signature`).
Please provide an example of a JWT token. Also, instruct that readers can use the jwt.io to parse the information before moving on to the examples.

2021-02-06 18:49 UTC, zolomohan commented on articles/cookie-token-auth/index.md
> +The JWT Payload contains claims that are the statements about the user and additional data. Claims include registered, public or private.
This line is a bit unclear. Please explain in a better way.

2021-02-06 18:49 UTC, zolomohan commented on articles/cookie-token-auth/index.md
> +This will create a using the `HMAC SHA256` algorithm. This is the signature to verify that the token is not changed when the secret key is applied on the backend.
This will create a ?

2021-02-06 19:33 UTC, ReactifyStudio commented
@zolomohan changes implemented.

2021-02-07 17:56 UTC, zolomohan approved these changes

2021-02-07 17:57 UTC, ReactifyStudio commented
@zolomohan check the approch

2021-02-07 17:58 UTC, ReactifyStudio commented
@zolomohan check the approches spelling 🙏

2021-02-07 18:02 UTC, zolomohan commented
@ReactifyStudio Good catch. Fixed it.

2021-02-07 18:45 UTC, merged