Introduction to javascript Modules
section-engineering-education/engineering-education pull request #1432
Opened 2021-01-19 14:07 UTC by jumamiller

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1396

2021-01-21 21:10 UTC, botahamec requested changes
Hello @jumamiller. I'm requesting some changes to this.

2021-01-23 18:29 UTC, hectorkambow commented
plagiarism check done

2021-01-24 17:09 UTC, jumamiller commented
@botahamec  changes requested done!

2021-01-24 18:13 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +import { addTwoNumbers } from './modules/add.js';
I still don't see anything indicating this. Correct me if I'm wrong

2021-01-24 18:15 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +    <script type="module" src="results.js"></script>
I don't think this was fixed. Again, correct me if I'm wrong though

2021-01-24 18:16 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +    <button onClick="addTwoNumbers(1,2);">
This doesn't seem to have been fixed either.

2021-01-24 18:20 UTC, jumamiller commented
lemme push, will ping you,seems i didn't commit changes

On Sun, Jan 24, 2021 at 9:16 PM Mike White <notifications@github.com> wrote:

> *@botahamec* commented on this pull request.
> ------------------------------
>
> In articles/introduction-to-javascript-modules/index.md
> <https://github.com/section-io/engineering-education/pull/1432#discussion_r563329271>
> :
>
> > +    <script type="text/javascript" src="myScript.js"></script>
> +</head>
> +
> +```
> +Well, this is slightly different when working with modules, you need a few modifications as we will see soon.
> +
> +The first and the most important part is to add a ``` type``` as ```module```, that is, ```type=" module" ``` in the script element.
> +This ensures that the script is defined or declared as a module.
> +
> +Now to import ```results.js``` we would do something like:-
> +```html
> +<head>
> +    <script type="module" src="results.js"></script>
> +</head>
> +<body>
> +    <button onClick="addTwoNumbers(1,2);">
>
> This doesn't seem to have been fixed either.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-io/engineering-education/pull/1432#discussion_r563329271>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL6XOYCL6ECX5LIQKRJPMSTS3RPXPANCNFSM4WI2IGOQ>
> .
>

2021-01-24 18:21 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +In the above code, we have a method named ```studentDetails()```  which is being passed several parameters and, a variable named ```studentName```.
The comma goes before the word "and".

Mentioning the parameters of the function seems irrelevant.

```suggestion
In the above code, we have a method named ```studentDetails()```, and a variable named ```studentName```.

2021-01-24 18:21 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +     +" .I'm in year"+ yearOfStudy;
I'm unresolving this comment to remind you that there should be a space after the word, "year"

2021-01-24 18:22 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +NOTE:- The Javascript module could also be embedded directly into the HTML file as follows:-
One dash has been removed but the other dash is still there.

2021-01-24 18:23 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +The first and the most important part is to add a ``` type``` as ```module```, that is, ```type=" module" ``` in the script element.
The spacing has changed, but the sentence itself hasn't

2021-01-24 18:24 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +Once these items are imported into the file, in this case, ```results.js```, they are readily available for using a smart IDE will even suggest for you the methods and properties when you start typin
I don't understand the change you made at all. You replaced "using" with "use", but you also replace "a" with "of"? And it's still a run-on sentence.

2021-01-24 18:26 UTC, botahamec commented on articles/introduction-to-javascript-modules/index.md
> +     +" .I'm in year"+ yearOfStudy;
The space before the period is fixed, but a space after "year" is still needed.

2021-01-24 18:28 UTC, botahamec requested changes
@jumamiller A lot of the comments you've marked as resolved are not actually resolved. Please fix those.

In addition, I have a new comment to a change you made, and also should help with shortening the sentence down.

2021-01-24 18:30 UTC, jumamiller commented
@botahamec kindly lemme push changes, I'll let you know. Thanks

2021-01-24 18:37 UTC, botahamec commented
Oh I see your other comment now

2021-01-25 07:51 UTC, jumamiller commented
@botahamec, all the 'changes' you requested have been made. I have personally made sure every single line of my article is edited on both Grammarly and Hemingway Editor.
Mr. @botahamec, each script has been run on both Firefox and chrome, they are working. Kindly take your time, run each script on your machine following the tutorial. In case of any issue, rather than having all these chats on the PR, ping me on the slack.
Thanks.

2021-01-26 21:36 UTC, botahamec approved these changes
@jumamiller You did a great job of editing this article.

@hectorkambow This is ready

2021-02-07 00:54 UTC, merged