Android Nested RecyclerView
section-engineering-education/engineering-education pull request #1453
Opened 2021-01-20 10:39 UTC by kimkimani

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

Android Nested RecyclerView #1411

2021-01-20 20:50 UTC, hectorkambow commented
@paulodhiambo is looking to review this article.

2021-01-21 01:30 UTC, paulodhiambo commented on articles/android-nested-recycler-view/index.md
> +We have designed the parent View and the items that belong to it, including the child RecyclerView. We need to add the items to the child RecyclerView. These are the items that will be scrollable hor
Consider changing the statement "... RecyclerView widgets that we add" to "... RecyclerView widget that we add."

2021-01-21 09:38 UTC, paulodhiambo requested changes
@kimkimani amazing tutorial. I have mentioned a few suggestions, review those whenever you get a chance. I found a few grammatical errors. Use Grammarly to ensure minimal errors. That way, the article gets reviewed faster.

2021-01-21 09:38 UTC, paulodhiambo commented on articles/android-nested-recycler-view/index.md
> +Let populate this data into the respective views. We will have two view adapters for each of the RecyclerView widgets. Create the two adapters.
Consider changing "Let populate this data into the respective views." to "Let us populate this data into the respective views."

2021-01-21 09:38 UTC, paulodhiambo commented on articles/android-nested-recycler-view/index.md
> +- Invoke the layout fixed size. This tells the layout not to move around the screen. It stabilizes the layout screen movements.
This statement is not clear, consider explaining.

2021-01-21 09:38 UTC, paulodhiambo commented on articles/android-nested-recycler-view/index.md
> +Let set the necessary categories to display the movies to the main RecyclerView layout.
Consider rewriting "Let set the necessary ..." to "Let us set the necessary ..."

2021-01-21 09:41 UTC, paulodhiambo commented
@hectorkambow this article needs plagiarism check.

2021-01-21 18:25 UTC, paulodhiambo approved these changes

2021-01-22 17:20 UTC, paulodhiambo commented
@hectorkambow technical review done. ready for final review

2021-02-09 18:15 UTC, merged