How to Detect and Correct Multicollinearity in Regression Models
section-engineering-education/engineering-education pull request #1460
Opened 2021-01-20 16:02 UTC by collins-a

Article as index.md and hero image as hero.jpg

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-20 16:03 UTC, collins-a commented
This fixes #1330

2021-02-10 20:56 UTC, hectorkambow commented
plagiarism check done

2021-02-23 20:04 UTC, hectorkambow commented
can we get a status on this PR ? @lalith1403

2021-02-24 19:08 UTC, lalith1403 commented
The technical portions covered in this article are very good. Will update by EOD.

2021-02-24 19:15 UTC, lalith1403 requested changes
A top notch article on multicollinearity. A few additions and this should be a very good article ready to be published.

2021-02-24 19:15 UTC, lalith1403 commented on articles/multicollinearity/index.md
> +**Partial least squares regression (PLS) or principal component analysis (PCA).** A takeaway from this paper on [partial least squares regression](http://www.ijastnet.com/journals/Vol_4_No_1_January_
The heading needs to changed... Are you suggesting that PLS and PCA are the same? It needs to be made clear that PLS is similar to PCA... The heading is misleading.

2021-02-24 19:15 UTC, lalith1403 commented on articles/multicollinearity/index.md
> +To learn the severity of multicollinearity, there are a few tests that may be carried out. We focus on the use of the variance inflation factor (VIF). The variance inflation factor represents the quo
Can you explain the definition a bit more detailed manner. The definition is accurate for VIF, but I feel it needs more explanation in simpler words or through the help of an example.

2021-02-24 19:15 UTC, lalith1403 commented on articles/multicollinearity/index.md
> +**Centering the variables.** Centering is defined as subtracting a constant from the value of every variable. It redefines the zero point for a given predictor to become the value we subtracted. Here
How does this impact multicollinearity?

2021-02-26 12:03 UTC, collins-a commented
@lalith1403 thanks, sir. Added a few lines to address the changes. Let me know if they are sufficient. Cheers.

2021-02-27 12:49 UTC, lalith1403 approved these changes

2021-03-01 17:15 UTC, hectorkambow commented
👋  Fantastic article @collins-a  - really learned a lot about Multicollinearity - think the community will find it useful. 
I'll be sure to revisit it again. 

Just wanted to give you an FYI that there were a few parts that I found a bit difficult to great through - the intro and a few other sentences. (as such I will be placing a tiered label for payouts)

I changed what I could to help the article flow. Please go through my changes to make sure I omitted nothing important.  
Also to see apply any applicable changes moving forward to future articles (or revisions). 

cc @lalith1403  please do the same to improve future revisions 👍  

Overall fantastic job! 
Thank you gentlemen 🚀

2021-03-01 17:17 UTC, merged