Working with Forms in PHP
section-engineering-education/engineering-education pull request #1464
Opened 2021-01-20 19:57 UTC by JudyNduati

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-20 19:59 UTC, JudyNduati commented
This fixes #1273

2021-01-28 12:45 UTC, WanjaMIKE commented on articles/working-with-forms-in-php/index.md
> +Creating a form on a web application is achieved using HTML. PHP connects the web application with the server (My SQL). It takes data from a webpage and sends it to the server. PHP handles data in th
It's `MySQL` rather `My SQL`.

2021-01-28 12:46 UTC, WanjaMIKE commented on articles/working-with-forms-in-php/index.md
> +A [form](https://www.tutorialspoint.com/php/php_form_introduction.htm) is a document with blank spaces for a user to insert or select data. The user's data is stored or saved in the database and retr
`blank fields` feels better than `blank spaces`.

2021-01-28 12:49 UTC, WanjaMIKE commented on articles/working-with-forms-in-php/index.md
> +The Form is presented to the user. The user inserts data and submits the form using the submit button. Then the data is saved and processed by the server. Data is processed based on the method mentio
What about the `PUT` method? talk more about it since it is related to forms

2021-01-28 12:50 UTC, WanjaMIKE commented on articles/working-with-forms-in-php/index.md
> +Forms in PHP are similar to forms built using HTML besides the syntax used. The form contains `Html` tags with [Graphical User Interface (GUI)](https://www.computerhope.com/jargon/g/gui.htm) such as
Just say we create forms using html tags rather than comparing the two.

2021-01-28 12:52 UTC, WanjaMIKE commented on articles/working-with-forms-in-php/index.md
> +Forms are written inside form tags `<form>` and `<\form>;.` The `form` tag surrounds all the inputs. Also, it gives instructions about how and where to submit the form. `POST` and `GET` methods decla
Instead of `Forms are written inside form tags `<form>` and `<\form>;``
Say
`Forms are defined by the <form></form> tags.`

2021-01-28 13:18 UTC, WanjaMIKE commented on articles/working-with-forms-in-php/index.md
> +Both methods send data to the server. The difference between the two methods is how data is submitted to the server. The POST method sends data from the browser (client) to the HTTP request in the me
does the `get` method send data or collect/retrieve data from server?

2021-02-03 09:17 UTC, JudyNduati commented
@WanjaMIKE,  I made changes you suggested

2021-02-13 09:49 UTC, WanjaMIKE commented
@JudyNduati Nice article. However, I feel you have not addressed forms adequately. Specifically how to store (CRUD) data in a MySQL database.

2021-02-13 09:50 UTC, WanjaMIKE requested changes
revision needed

2021-02-23 20:07 UTC, hectorkambow commented
author pinged via slack 👍

2021-02-27 09:55 UTC, JudyNduati commented
@WanjaMIKE I made the changes you requested. Please have a review

2021-03-02 22:33 UTC, JudyNduati commented
@WanjaMIKE  i made changes

2021-03-07 16:48 UTC, WanjaMIKE approved these changes
Just finished the review. Nice job. FYI: `Comments in PHP are written with // or /*   */ rather than #`.

2021-03-08 18:23 UTC, hectorkambow commented
plagiairism check done

2021-03-08 18:33 UTC, merged

2021-03-08 20:04 UTC, JudyNduati commented
Hi @hectorkambow, thank you. I am a little bit confused about the tiered payout. I did all the reviews once. Actually, the reviewer went ahead and suggested that I add some content on "CRUD functionalities", which I did despite that being not part of my takeaways and out of my topic. I think you can reconsider this. Thanks. Also regarding PR #1581 the reviewer also commented "Major changes" yet there were minimal changes. I felt that the tired payout was not fair.

I hope I am not biased. Maybe we can have a more transparent guideline on what amounts to a tiered payout.