added article on Spring security
section-engineering-education/engineering-education pull request #1467
Opened 2021-01-21 01:24 UTC by john-amiscaray

This fixes #1244
### Article Checklist
**NOTE: (1st-time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-26 07:20 UTC, paulodhiambo commented
@hectorkambow I wish to review this article.
Regards.

2021-01-27 14:05 UTC, paulodhiambo requested changes
@john-amiscaray amazing tutorial on Spring security. I have mentioned a few suggestions, review those whenever you get a chance and ping me when done.

2021-01-27 15:53 UTC, john-amiscaray commented on articles/an-all-in-one-spring-security-crash-course-for-java-developers/index.md
> +Before we begin coding, let’s go over some theory. The main features we will cover are different tactics for authentication and authorization. Authorization is the process of verifying we allow the u
The reason I referred to it as theory and not Spring security fundamentals is that that content is more so about general web security concepts that can be applied outside of Spring so I don't believe I want to make that change.

2021-01-27 16:06 UTC, john-amiscaray commented on articles/an-all-in-one-spring-security-crash-course-for-java-developers/index.md
> +Whenever we build an application, security isn’t exactly the first thing we think about. Yet, it is one of the most important features that needs your attention. In this article, we will cover some k
@paulodhiambo Okay I have just committed that change. Thank you.

2021-01-27 16:16 UTC, paulodhiambo approved these changes

2021-01-27 16:17 UTC, paulodhiambo commented
@john-amiscaray I am proceeding to tech review.

2021-01-29 18:36 UTC, paulodhiambo commented
@john-amiscaray amazing article on Spring security.

2021-01-29 19:25 UTC, john-amiscaray commented
> 
> 
> @john-amiscaray amazing article on Spring security.

Thank you for taking the time to review this.

2021-02-09 03:08 UTC, hectorkambow commented
plagiarism check done

2021-02-09 21:49 UTC, merged