AJAX request in Django (Using Axios)
section-engineering-education/engineering-education pull request #1472
Opened 2021-01-22 14:17 UTC by atoyegbe

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-22 19:44 UTC, hectorkambow commented
@geoffrey45  will be reviewing this PR 👍

2021-01-22 20:15 UTC, hectorkambow commented
plagiarism check done @geoffrey45

2021-01-25 12:10 UTC, geoffrey45 requested changes
Great article @atoyegbe. Just a few minor issues. Please fix them and ping me when you are done.

2021-01-25 12:10 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
There are some missing words. Edit removing 'exactly' to look like this: 'Your `home.html` should look like this.'

2021-01-25 22:07 UTC, atoyegbe commented
@geoffrey45 I'm done.

2021-01-26 19:42 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
@atoyegbe Replace the words 'and above' with 'or newer'.

2021-01-26 19:43 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
Start these list sentences with a capital letter

2021-01-26 19:53 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
@atoyegbe  Change this to read: '... the CDN script tag below `</div>` closing tag'

2021-01-26 20:25 UTC, atoyegbe commented
@geoffrey45 done.

2021-01-27 11:40 UTC, geoffrey45 requested changes
@atoyegbe Make these changes and ping me when done.

2021-01-27 11:40 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
Put file directories into code blocks .eg. \`views.py`

2021-01-27 11:40 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
Move this explanation somewhere before the code work. Create a sub-heading with the name "What is Axios" and put the explanation in it.  Also, provide relevant links for Fetch API and XMLHttpRequests.

2021-01-27 12:26 UTC, atoyegbe commented
@geoffrey45 done.

2021-01-27 12:35 UTC, geoffrey45 commented on articles/ajax-request-in-django-using-axios/index.md
> +
@atoyegbe Break down this into two smaller sentences. Also, edit to look like this: '... directory by running `cd notes` and run the command below.'

2021-01-27 12:36 UTC, geoffrey45 approved these changes

2021-01-27 12:37 UTC, geoffrey45 commented
@hectorkambow tech review done. Ready for final review.

2021-02-10 19:21 UTC, merged