Introduction to C++ namespace
section-engineering-education/engineering-education pull request #1477
Opened 2021-01-23 15:00 UTC by Dawe-7

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1415

2021-01-25 18:49 UTC, cyberShaw commented
@Dawe-7 Amazing article! Code indentation was missing in the code snippets that you've given. Since the changes were minor, I fixed it myself. There is a lack of code comments in the snippets. Please add them and we can move on to final review.

2021-01-25 18:51 UTC, cyberShaw requested changes

2021-01-25 18:51 UTC, cyberShaw commented on articles/introduction-to-c++-namespace/index.md
> +namespace no1 {
The below code snippet needs helpful code comments

2021-01-25 18:51 UTC, cyberShaw commented on articles/introduction-to-c++-namespace/index.md
> +#include <iostream>
Code comments here too, please :D

2021-01-25 18:51 UTC, cyberShaw commented on articles/introduction-to-c++-namespace/index.md
> +      int sample1 = sample;
Comments needed here too

2021-01-26 08:42 UTC, Dawe-7 commented
Hi @cyberShaw, I've added a few comments in the code snippets that the user can use to follow the program. I hope it's good to go, Kindly review.
Thanks.

2021-01-26 08:44 UTC, cyberShaw commented
> Hi @cyberShaw, I've added a few comments in the code snippets that the user can use to follow the program. I hope it's good to go, Kindly review.
> Thanks.

I just saw the comments, they are really helpful! Thank you for making the changes. This article is ready for final review.

2021-01-26 09:11 UTC, Dawe-7 commented
> > Hi @cyberShaw, I've added a few comments in the code snippets that the user can use to follow the program. I hope it's good to go, Kindly review.
> > Thanks.
> 
> I just saw the comments, they are really helpful! Thank you for making the changes. This article is ready for final review.

Okay, thanks so much.

2021-01-26 09:34 UTC, cyberShaw approved these changes

2021-02-11 21:14 UTC, hectorkambow commented
plagiarism check done

2021-02-14 19:06 UTC, hectorkambow commented
@Dawe-7 
Just made some changes for flow during final review. 

cc @cyberShaw  🚀  

Please do review to make sure no meaning was changed and to see the changes themselves

2021-02-14 19:06 UTC, merged