How To Build A Music Player Using Django
section-engineering-education/engineering-education pull request #1493
Opened 2021-01-26 22:35 UTC by Chukslord1

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-26 22:47 UTC, Chukslord1 commented
This fixes #1328

2021-02-02 17:47 UTC, hectorkambow commented
plagiarism check done @zolomohan

2021-02-02 17:48 UTC, zolomohan commented
thank you @hectorkambow

2021-02-02 18:15 UTC, zolomohan commented
Hi @Chukslord1, Please don't use `#` and `##` for headings. You should only use `###` and up.

2021-02-06 14:12 UTC, zolomohan reviewed
Hi @Chukslord1, The CSS file you've included is very long. I'd suggest you create a gist in [Github Gist](https://gist.github.com/) and add a link instead.

2021-02-06 15:45 UTC, Chukslord1 commented
@zolomohan I have added a Github gist link instead, thanks for the corrections.

2021-02-06 15:58 UTC, zolomohan commented
Does any of the images that you've included in the article require sources?

2021-02-06 16:03 UTC, Chukslord1 commented
Yes , I have only one image that was from a source which I added in the resources section .

2021-02-06 16:36 UTC, zolomohan commented
@Chukslord1 Add the image source right below the image. 

Like this: [Image Source](https://www.javatpoint.com/django-mvt)

2021-02-06 16:50 UTC, Chukslord1 commented
@zolomohan I have added the image source

2021-02-09 18:10 UTC, Chukslord1 commented
This fixed #1294

2021-02-12 13:07 UTC, zolomohan requested changes

2021-02-12 13:41 UTC, Chukslord1 commented
@zolomohan i have made the changes requested

2021-02-12 14:34 UTC, zolomohan requested changes
@Chukslord1 Please remove the `$` sign in all the bash commands.

2021-02-12 14:34 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +```
Please explain this code snippet.

2021-02-12 14:34 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +```
Also mention you are using an external library.

```HTML
<script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js">
```

2021-02-12 14:34 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +In the code above we created the HTML attributes for our music player and made use of jinja; a python web templates engine to render our query set object in our **"page_obj"** context which we define
At this point in the article, we aren't setting any **"page_obj"** in the *views.py* file before this step. Please check.

2021-02-12 14:34 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +
Since you are not explaining every piece of code, please add the required skill level of the reader to go through this article.

2021-02-12 15:18 UTC, Chukslord1 commented
@zolomohan this article focusses on the use of django as a backend to develop the music player. Readers are meant to copy the JavaScript and html/bootstrap code which I would just summarize the general use of the frontend but focus on explaining the backend.

2021-02-12 15:50 UTC, Chukslord1 commented
@zolomohan I have made some changes..please review

2021-02-13 06:01 UTC, zolomohan commented
> @zolomohan this article focusses on the use of django as a backend to develop the music player. Readers are meant to copy the JavaScript and html/bootstrap code which I would just summarize the general use of the frontend but focus on explaining the backend.

Even though that's the case, The JS code is still a crucial part for the app to work. Thus, you should explain about it too.

2021-02-13 11:21 UTC, Chukslord1 commented
@zolomohan i have explained the js code please review

2021-02-14 18:36 UTC, zolomohan requested changes
@Chukslord1 Please mention that you are using `MediaElemet.js` and briefly explain what the library is used for.

Also, please go through the suggestions below.

2021-02-14 18:36 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +Install python and enable `pip`. Then run the following to install the required packages:
Provide a link to the Python download page. Isn't pip enabled by default? If that's not the case, please add instructions on how to enable it.

2021-02-14 18:36 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +pip install pillow
Briefly explain about the `pillow` package and how you are going to use it in this project.

2021-02-14 18:36 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +In this case, the `audioHeight` attribute which is the default volume is set to 40, the `features` attribute which carries all the allowed controls for the audio file is defined, the `alwaysShowContt
Break this down as points.

2021-02-14 18:36 UTC, zolomohan commented on articles/how-to-build-a-music-player-using-django/index.md
> +In the code above we used Bootstrap which we imported using the CDN link (as seen in the head tag) to create the HTML attributes for our music player and made use of jinja; a python web templates eng
Add a link to Bootstrap's homepage.

2021-02-15 01:20 UTC, Chukslord1 commented
@zolomohan I have made changes. Please review.

2021-02-15 15:04 UTC, zolomohan approved these changes

2021-02-15 20:59 UTC, hectorkambow commented
Please go over the changes made during final review to implement any improvements to next articles.  
@Chukslord1 

cc @zolomohan  please do the same to improve future revisions.

2021-02-15 21:00 UTC, merged