How to Choose Levels of Logging
section-engineering-education/engineering-education pull request #1513
Opened 2021-02-01 16:44 UTC by EKahuha

this fixes #1438

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-02-03 21:20 UTC, geoffrey45 requested changes
@EKahuha Great article. Just some tiny issues. Please make the changes attached below.

2021-02-03 21:20 UTC, geoffrey45 commented on articles/how-to-choose-levels-of-logging/index.md
> +
Please rewrite this last sentence using simpler and commonly used terms. Ie. In "merely the unification" and "whole lot of loggings will be logged".

2021-02-12 01:17 UTC, hectorkambow commented
plagiarism check done

2021-02-22 06:58 UTC, geoffrey45 reviewed
@EKahuha Almost done with the review. Just some minor suggestions. Please look at the comments below.

2021-02-22 06:58 UTC, geoffrey45 commented on articles/how-to-choose-levels-of-logging/index.md
> +Eric Allman developed the Sendmail project that eventually needed a logging solution. This is where the System Logging Protocol ([Syslog](https://www.paessler.com/it-explained/syslog#)) was introduce
You have some repetition here. The line: `Eric Allman developed the Sendmail project that eventually needed a logging solution.` repeats line 13.

Also, provide the Syslog link and full form of the word in the first appearance of the word.

2021-02-22 06:58 UTC, geoffrey45 commented on articles/how-to-choose-levels-of-logging/index.md
> +
Looks like the log levels are ordered. Consider turning them into an ordered list. Also, state how they are ordered. ie. according to what criteria and in what order.

2021-03-02 17:33 UTC, hectorkambow commented
@geoffrey45  
just wanted to get a status update on this article

2021-03-02 19:59 UTC, hectorkambow commented
> @hectorkambow I'm checking the article for the last time before I submit it for final review. I had suggested some minor changes from the author which came through almost 2 hours ago.

Understood - thank you. 
Wasn't sure when the author changes came in - no worries or rush. 
Thank you v much 🚀

2021-03-02 20:46 UTC, hectorkambow commented
@EKahuha  Great work Gentlemen 

Very minor edits on my end 👍 

cc @geoffrey45  🚀

2021-03-02 20:47 UTC, merged