Python Boto3 and Amazon DynamoDB Programming Tutorial
section-engineering-education/engineering-education pull request #1528
Opened 2021-02-06 12:43 UTC by Tsanguu

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-02-06 12:44 UTC, Tsanguu commented
This solves #929

2021-02-11 21:02 UTC, hectorkambow commented
@paulodhiambo  

I see that you have assigned this article for review - if you are working on another one - could @rahulbanerjee26  

do a test review on this one - he is interested in becoming a peer reviewer. 

If you could please guide @rahulbanerjee26  if he has any questions along the way. 

Do not hesitate to ping me for anything 🚀  
Thank you

2021-02-12 01:14 UTC, rahulbanerjee26 requested changes
Thanks, @hectorkambow, and @paulodhiambo. 

Hi @Tsanguu, as Hector mentioned, I am a new peer reviewer so please feel free to ignore some of my suggestions.

It is a well-written article and easy to understand. I have made a few suggestions to improve readability. You should also consider adding more comments to your code. It will make it easier for readers to understand.

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +Below is the expected output. The response item is similar to the item we created previously. Using the specific primary key, we can retrieve a particular item.
```suggestion
Below is the expected output. You can confirm that the response item is the item we created previously. Using the specific primary key, we can retrieve a particular item.
```

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +The update modifies an existing item by updating the values of current attributes, removing attributes, or adding new attributes. In this tutorial, we will update the values of existing attributes. B
```suggestion
Update refers to modifying a previously created item by updating the values of existing attributes, removing attributes, or adding new attributes. In this tutorial, we will update the values of existing attributes. Below is the original item and the updated item.
```

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +We will use the method `update_item`, as shown in the code below. Create a script named update_item.py `update_item.py` and add the code below.
```suggestion
We will use the `update_item` method, as shown in the code below. Create a script named  `update_item.py` and add the code below.
```

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +To delete an item, we use the method `delete_item`. We can specify the primary key for the item to delete or provide a `ConditionExpression`. If we use a `ConditionExpression`, the item will not be d
```suggestion
To delete an item, we use the `delete_item` method. We can specify the primary key for the item to delete or provide a `ConditionExpression`. If we use a `ConditionExpression`, the item will not be deleted unless the condition is evaluated to True. In this example, we will provide a primary key for the item to be deleted and provide a `ConditionExpression`. The item will be deleted if the `ConditionExpression` is met. In this example, the condition is:
```

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +The item will be deleted if the value of `info_timestamp` is greater than or equal to the value provided. Create a script named `info_timestamp` and paste the code below.
```suggestion
The item will be deleted if the value of `info_timestamp` is greater than or equal to the value provided. Create a script named `info_timestamp.py` and paste the code below.
```

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +Scan operation reads and returns all the items in the table. The method `DynamoDB.Table.scan()` is used to scan. Using a `filter_expression`, we can filter the items to be returned. However, the whol
```suggestion
Scan operation reads and returns all the items in the table. The method `DynamoDB.Table.scan()` is used to scan a table. Using a `filter_expression`, we can filter the items to be returned. However, the whole table will be scanned, and items not matching the `filter_expression` will be thrown away. Create a script named `scan.py` and paste the code below. To learn more about DynamoDB scans, refer to the [developer guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html).
```

2021-02-12 01:14 UTC, rahulbanerjee26 commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +The script above scans through the table `Devices` with no `filter_expression`. Run the command below to execute the script scan.py. The output will be all the items in the `Devices` table.
```suggestion
The script above scans the `Devices` table with no `filter_expression`. Run the command below to execute the script scan.py. The output will be all the items in the `Devices` table.
```

2021-02-12 12:37 UTC, rahulbanerjee26 commented
@Tsanguu I will review your new changes and move on to the tech review on Sunday.

2021-02-16 02:00 UTC, rahulbanerjee26 requested changes
@Tsanguu  Preliminary and Tech Review are completed. I have addressed a minor issue I found during the tech review. Please address that and we can move on to the next steps in the review process.

2021-02-16 13:19 UTC, Tsanguu commented on articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
> +        if er.response1['Error']['Code'] == "ConditionalCheckFailedException":
@rahulbanerjee26 I have taken note of the issues and resolved the code error.

2021-02-16 14:00 UTC, rahulbanerjee26 commented
@hectorkambow The preliminary review and tech review for this article are completed. It requires a plagiarism check and is ready for the final review.

2021-02-16 14:01 UTC, rahulbanerjee26 approved these changes

2021-02-16 16:51 UTC, hectorkambow commented
plagiarism check done

2021-02-22 02:30 UTC, hectorkambow commented
Great work gentlemen

@Tsanguu  

cc @rahulbanerjee26  🚀

2021-02-22 02:30 UTC, merged