vuejs 2-crud-with-localstorage
section-engineering-education/engineering-education pull request #1561
Opened 2021-02-18 08:03 UTC by EspiraMarvin

### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-02-18 08:03 UTC, EspiraMarvin commented
@geoffrey45 done

2021-02-18 08:09 UTC, geoffrey45 commented
@EspiraMarvin You have an author folder in your article directory. Please delete this folder ans commit again.

2021-02-22 09:33 UTC, EspiraMarvin commented
Link to my issue #1220

2021-02-22 16:35 UTC, hectorkambow commented
plagiarism check done

2021-02-26 10:19 UTC, geoffrey45 requested changes
@EspiraMarvin Great article. Teaches us how to use local storage in Vuejs in a simple and straightforward manner. Just a few issues. Please fix these issues and ping me when you are done.

2021-02-26 10:19 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +The Watch method comes in handy again, to help us watch for any changes in the editBook data, we set ```deep:true``` property to let the Vue instance continuously watch for changes, so while editing
This sentence is too long. Consider breaking it into simpler sentences.

2021-02-26 10:19 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +Go back to the App.vue file, after editing a title an event ```edit-book-event``` is sent to App.vue file we assign the event to a method in order to save the changes to localStorage. Update the code
This sentence is too long. Consider breaking it into simpler sentences.

2021-02-26 10:19 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +
This sentence is too long. Consider breaking it into simpler sentences.

2021-02-26 10:19 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +
This sentence is too long. Consider breaking it into simpler sentences.

2021-02-26 10:19 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +
This sentence is too long. Consider breaking it into simpler sentences.

2021-03-01 20:55 UTC, geoffrey45 requested changes
@EspiraMarvin almost through with the tech review. Please fix the minor issues below. Please let me know when you are through

2021-03-01 20:55 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +}
Looks like you are using the wrong block of code here. Please replace this with the correct books code.

2021-03-01 20:55 UTC, geoffrey45 commented on articles/vue2-crud-app-with-localstorage/index.md
> +```
Please replace `v-on:edit-todo-item` with the correct piece of code

2021-03-03 16:46 UTC, merged

2021-03-05 20:27 UTC, hectorkambow commented
As an FYI we'll be adding a tiered payout label due to the level of revisions and reviews.

2021-03-05 22:23 UTC, EspiraMarvin commented
@hectorkambow I was inquiring is this not a tech tutorial?