JWT Authentications in Angular 11
section-engineering-education/engineering-education pull request #1699
Opened 2021-03-16 04:32 UTC by jumamiller

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you placed your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1691

2021-03-16 07:50 UTC, geoffrey45 commented
Hello @jumamiller. The title of this article conflicts with that of another already published article. See https://www.section.io/engineering-education/getting-started-with-jwt-using-angular8-and-nodejs/. The article talks about jwt in angular 11 using a node.js server. 

Looking at your article, seems like there's some PHP used. Just a suggestion, maybe you could update the title to include PHP, to differentiate it from the other article.

2021-03-17 19:21 UTC, paulodhiambo requested changes
@jumamiller  an amazing article. Check on the suggested changes and ping me when done.

2021-03-17 19:21 UTC, paulodhiambo commented on articles/jwt-auth-angular/index.md
> +You learned how to use JWT authentication in your Angular 11 framework in this tutorial.
Consider changing "You learned how to use JWT authentication in your Angular 11 framework in this tutorial." to "You have learned how to use JWT authentication in your Angular 11 application in this tutorial. Implement other authentication strategies such as token authentication in your Angular app."

2021-03-17 19:36 UTC, jumamiller commented
@paulodhiambo, done!

2021-03-17 19:54 UTC, paulodhiambo commented
@jumamiller an amazing article on Angular 11 authentication. @hectorkambow  this article is ready for final review.

2021-03-17 21:15 UTC, hectorkambow commented
@jumamiller  👋 Good afternoon - Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on [plagiarism](https://www.scribbr.com/category/plagiarism/) and what is considered as such.

🤔 

[Angular 11 - JWT Authentication Example & Tutorial With PHP #1699.pdf](https://github.com/section-engineering-education/engineering-education/files/6159747/Angular.11.-.JWT.Authentication.Example.Tutorial.With.PHP.1699.pdf)

2021-03-18 14:54 UTC, jumamiller commented
@hectorkambow, I've updated most of the boilerplate codes, you can recheck! 
cc @paulodhiambo

2021-03-19 18:28 UTC, merged