How to render HTML pages as an HTTP server response Using Node.js
section-engineering-education/engineering-education pull request #1742
Opened 2021-03-17 05:50 UTC by mosesreigns

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you placed your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-17 06:22 UTC, lalith1403 requested changes
Welcome to the program. This is a great article on rendering HTML pages using Node.js. I would like to point out a couple of points. 
1. While writing technical articles, we tend to stick to deliver the message from a third person's point of view. Usage of I, you, etc should be avoided. 
2. Maintain consistency in the usage of technical terms. GET, POST, Node.js, Express.js. Avoid mixing it up with get, Get, etc.

The outputs are great! The code works as mentioned. Make these changes and we can move on to the final round fo review.

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +- Rend the pages directly from the server - when the browser tries to access a route specified in your server, the server will load these HTML pages upon users' requests.
Break this into 2-3 simpler sentences.

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +- Create a Node.js project/directory. Initialize the project within the directory you have created. Use `npm init -y` to automatically initialize this Node.js project or check this [guide](/engineeri
Mention installation of npm in the setting up section.

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +![](server-rendered-html-elements.jpg)
Make sure to add text related to the content of the image. Also, modify all the image URLs to the following.
```![alt text](/engineering-education//rendering-html-pages-as-a-http-server-response-using-node-js/server-rendered-html-elements.jpg)```

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +However, this did not load the CSS styling. `app.css` is a static file. To [static server files](https://expressjs.com/en/starter/static-files.html) included in the `index.html` use `express.static`
I think the second sentence is incomplete. Check that. It should be, to load static server files?

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +To render an HTML file into the server using Express, we use `res.sendFile()`. This read and render the data that you include in your HTML files. This transfers the file over to the browser whenever
```suggestion
To render an HTML file into the server using Express, we use `res.sendFile()`. This reads and renders the data included in one's HTML files. This transfers the file to the browser upon a [GET request](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods) to the server. The server submits a response status with HTML rendered web content as the message body.
```

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +`app.css`
```suggestion
**File name**: _app.css_
```

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +`app.css`
Make the exact change everywhere file names are mentioned.

2021-03-17 06:22 UTC, lalith1403 commented on articles/rendering-html-pages-as-a-http-server-response-using-node-js/index.md
> +The server is running. It is now returning HTML form as a response to the client (browser). Whenever you access this server's route, the `Get` request will be executed from the browser. However, what
Maintain consistency while mentioning commands such as GET, POST, etc.

2021-03-17 06:26 UTC, lalith1403 commented
@mosesreigns We will need a headshot pic and a short bio for the author's page. Refer to the contributing guidelines for more information. You may also refer to the authors folder in the main repository for more information.

2021-03-17 06:28 UTC, lalith1403 commented
@mosesreigns Add a hero image from Unsplash.com. Let me know if you have any doubts. Before modifying the files, make sure to pull the changes made to avoid merge conflicts.

2021-03-17 08:55 UTC, mosesreigns commented
I have updated the article @lalith1403

2021-03-17 09:04 UTC, lalith1403 commented
What about author pic and bio?

2021-03-17 10:06 UTC, mosesreigns commented
Adde that too @lalith1403

2021-03-17 16:21 UTC, lalith1403 commented
> Welcome to the program. This is a great article on rendering HTML pages using Node.js. I would like to point out a couple of points.
> 
> 1. While writing technical articles, we tend to stick to deliver the message from a third person's point of view. Usage of I, you, etc. should be avoided.
> 2. Maintain consistency in the usage of technical terms. GET, POST, Node.js, Express.js. Avoid mixing it up with get, Get, etc.
> 
> The outputs are great! The code works as mentioned. Make these changes and we can move on to the final round fo review.

I still see a lot of _you_ mentioned in the article. A third-person narrative suits technical writing better.

2021-03-18 09:30 UTC, mosesreigns commented
> I still see a lot of _you_ mentioned in the article. A third-person narrative suits technical writing better.

Worked on most of the "you", Check the update @lalith1403

2021-03-22 18:49 UTC, hectorkambow commented
plagiairsm check done

2021-03-22 19:38 UTC, hectorkambow commented
@mosesreigns  👋  Welcome and great job submitting you 1st article to the EngEd program. 

We're happy to have you join the community - please take keen notes on any changes made by your peer reviewer or myself to apply those to future articles. 🚀  

Be sure to go over our resources page if you haven't already for more information and helpful links. 

cc @lalith1403

2021-03-22 19:39 UTC, hectorkambow commented
@lalith1403  Please see the changes I made to the front matter 👍  

main thing is the list - the front matter does not need to be in list form.

2021-03-22 19:41 UTC, merged