Speech Command Recognition With Tensorflow.js and React.js
section-engineering-education/engineering-education pull request #1745
Opened 2021-03-17 06:42 UTC by Worawat101

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

This fixes #1693 

#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you placed your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-22 12:48 UTC, cyberShaw requested changes
Great article, @Worawat101 !
Really good work. I have some minor suggestions. Please make them so we can move to the final round of review.

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +There are many AI-powered computer systems nowadays that can use speech-based communication to communicate with humans. The main logic that is used in these types of systems is the ability to recogni
```suggestion
There are many AI-powered computer systems nowadays that can use speech-based communication to communicate with humans. The main logic that is used in these types of systems is the ability to recognize speech and perform tasks accordingly. In this tutorial, we are going to explore the basics of speech/command recognition using a speech-command recognizer model provided by TensorFlow in a React app ecosystem. The tutorial also demonstrates the use of a system microphone for speech audio input and listen to the audio to make probabilistic predictions.
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +In this tutorial, we will learn how to perform speech command recognition in real-time and demonstrate the result of predictions. Then, we are going to load the speech-commands model provided by Tens
```suggestion
In this tutorial, we will learn how to perform speech command recognition in real-time and demonstrate the result of predictions. Then, we are going to load the speech-commands model provided by TensorFlow.org. Feeding the audio data to the model neural network, we are going to listen to the audio and make the predictions. Lastly, we are also going to improve the accuracy of recognition by applying the argmax function to our model.
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +- To precise, the speech commands using the pre-trained speech-commands model from TensorFlow.
```suggestion
- To be precise, the speech commands using the pre-trained speech-commands model from TensorFlow.
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +```jsx
```suggestion
```bash
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +Then, we need to open the project in our code editor IDE (VScode) as shown in the screenshot below:
```suggestion
Then, we need to open the project in our code editor IDE (VSCode) as shown in the screenshot below:
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +Now, we can execute the command  `yarn start` or `npm start` to run the project on the port 3000 of our [localhost](http://localhost):
```suggestion
Now, we can execute the command  `yarn start` or `npm start` to run the project on the port 3000 of our [localhost](http://localhost:3000):
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +Now, we are going to install the main TensorFlow.JS package along with the speech commands recognition package provided by TensorFlow.org. for installation package, we need to execute the following c
```suggestion
Now, we are going to install the main TensorFlow.js package along with the speech commands recognition package provided by TensorFlow.org. For installing the package, we need to execute the following command in our project command line or terminal:
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +- @tensorflow-models/speech-commands: It is a Tensorflow models that enables us to perform recognition of spoken commands.
```suggestion
- @tensorflow-models/speech-commands: It is a Tensorflow model that enables us to perform recognition of spoken commands.
```

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +Then, we need to define the state variable for model, action, and labels using the `useState` hook as shown in the code snippet below:
Please briefly explain how the useState hook works. This might be useful for a beginner

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +```jsx
Please add code comments, this would make the code more readable.

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +Here, we are going to create a function called `loadModel` that loads the Speech Recognizer model into our app. First, a `recognizer` is initialized using the `create` method provided by the `speech`
Please also briefly explain how the useEffect hook works

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +  };
Please add code comments here too

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +The function uses `map` logic along with `reduce` method to improve the overall probability of detection. Hence, it is a Map-Reduce algorithm.
Please explain how `map` and `reduce` works in two lines.

2021-03-22 12:48 UTC, cyberShaw commented on articles/speech-command-recognition-with-tensorflow-and-react/index.md
> +```
Please add code comments

2021-03-24 06:15 UTC, Worawat101 commented
@cyberShaw I already fixed all your comment

2021-03-24 06:16 UTC, cyberShaw commented
> @cyberShaw I already fixed all your comment

Great work, I'll do a review.

2021-03-25 23:58 UTC, Worawat101 commented
@cyberShaw hi I wundering if your help me win this week with complete this task

2021-03-26 05:34 UTC, cyberShaw commented
Thank you for making the changes, @Worawat101!
This article is ready for final review.

2021-03-26 16:09 UTC, hectorkambow commented
plagiarism check done

2021-03-26 16:10 UTC, merged