Connecting library application to SQL Server using Windows forms
section-engineering-education/engineering-education pull request #1767
Opened 2021-03-17 17:56 UTC by mohamedgh16

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1621

2021-03-19 16:52 UTC, srishilesh requested changes
Hey @mohamedgh16,

Thanks for the PR.

Great article! I have suggested few changes, please let me know when the changes are done. We can then move on to the tech review.

A few suggestions:
- The article lacked punctuations, and had unnecessary capitalizations of words.
- If you're using a variable or unique name, add them within ` `` `, to highlight.
- Format your code snippets neat.

Thank you.

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +In this tutorial, we will use a windows forms project and work on it, we will add new forms that will add edit & delete books from the library, we will also manage the authors, the stores & the publi
```suggestion
Windows forms are one of the best tools used in making applications. With windows forms, you can make a variety of applications, from a mini calculator to a library application that uses a database.

In this tutorial, we will connect a library application to a SQL database server using Windows forms. We will use a windows forms project to add new forms, edit or delete from the library. Also, we will manage the authors, the stores & the publishers in the database, and display the information of each attribute & refresh it each time, a change accrues.

```

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +In this tutorial, we will use a windows forms project and work on it, we will add new forms that will add edit & delete books from the library, we will also manage the authors, the stores & the publi
Please explain what a `Windows form` is. Add them in the first para. Give a 1 -2 line intro.

If possible, add a link.

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +If you don’t have Visual Studio installed on your computer, you can check this article on how to set up the C# environment in Visual Studio [here](https://www.geeksforgeeks.org/setting-environment-c-
```suggestion
#### Installation guide
- To install Visual Studio and setup the work environment, refer [this](https://www.geeksforgeeks.org/setting-environment-c-sharp/) article on how to set up the C# environment in Visual Studio.
- To install SQL Server, you can download it from [here](https://www.microsoft.com/en-us/sql-server/sql-server-downloads).
- If you are new to Windows forms, you can check [this](/engineering-education/getting-started-with-windows-forms-using-c-sharp/) tutorial which would help you understand the basic concepts.
```

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +If you don’t have Visual Studio installed on your computer, you can check this article on how to set up the C# environment in Visual Studio [here](https://www.geeksforgeeks.org/setting-environment-c-
Do not clutter too many information as a paragraph. Instead, list them out as points.

Also, while referring any other Section article, you need not type out the full URL. You can use `/engineering-education/getting-started-with-windows-forms-using-c-sharp/`

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +- A basic understanding of C# programming language.
```suggestion
- A basic understanding of the C# programming language.

```

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +
Could you be more specific on what "pubs" mean? And, also add why you need to create it

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +After copying the database paste it in a new Query and execute it, you should be able to see the name of the database "pubs" to the left of your screen.
If "pubs" is some sort of variable or unique name, you can put them into ` `` ` like `Pubs`. Also, capitalize the first letter if needed.

I believe "Pubs" is the short hand form of "Publishers". Please correct me, if I'm wrong.

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +After copying the database paste it in a new Query and execute it, you should be able to see the name of the database "pubs" to the left of your screen.
`After copying the database`.

Did you mean `database query`?

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +Add a refresh button and 3 more tabs next to the Title tab to use later, then add 4 more columns to the datagridview to show the data of the library.
`datagridview`.

What is "datagridview"? Does it come as one single word? If not, split them out

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +Adding a new book will require the title id title name title type publisher id publisher date & the price of the book.
Add these variables within ` `` `

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +Adding a new book will require the title id title name title type publisher id publisher date & the price of the book.
```suggestion
Adding a new book will require the `titleID`, `titleName`, `titletype`, `pubid`, `pubdate`, and `price` of the book.

```

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +Adding a new book will require the title id title name title type publisher id publisher date & the price of the book.
Make these kind of changes throughout the article

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +```
Format the code snippet neatly.

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +            {dataGridView3.Rows.Add(dr["authorcount"]);}
Format the code.

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +```
Format the code

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +
Explain your objective about what you're going to build

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +
Add a `Table of contents` section.

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +            }
Format the code

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +        }
Add inline code comments

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +        }
Add inline code comments

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +            }
Add inline code comments

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +            MessageBox.Show("Information inserted!");}
Add inline code comments

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +```
Add inline code comments

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +```c#
Add comments for all the code snippets

2021-03-19 16:52 UTC, srishilesh commented on articles/connecting-library-application-to-sql-server-using-windows-forms/index.md
> +In this tutorial we have learned how to connect an application to a database and convert any string to a Query that can be understood by the SQL server, we have also learned how to add edit & delete
Add a `Further reading` section and reference few links which would help the reader gain more knowledge about this topic

2021-03-22 20:21 UTC, mohamedgh16 commented
hello, @srishilesh 
Thanks for the suggestions!
I have done the changes, hope you like it.

2021-03-24 16:45 UTC, srishilesh approved these changes
Hey @mohamedgh16,

Thank you for making the changes.

You had missed out to resolve a few suggestions as a part of my previous review. I have resolved them now. Make sure you go through my commits and suggestions to improve on your future articles.

Moving this to the final review.

Thank you.

2021-03-24 23:53 UTC, hectorkambow commented
plagiarism check done

2021-03-25 00:13 UTC, hectorkambow commented
@mohamedgh16  Please take keen notice on the changes made by your peer reviewer or myself in the final review - to provide (any applicable changes) to future articles. 

Be sure to check out our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) as well for more helpful tips and links.

2021-03-25 00:14 UTC, merged