Building web server with vlang
section-engineering-education/engineering-education pull request #1771
Opened 2021-03-18 00:09 UTC by Umoren

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-21 04:42 UTC, Umoren commented
The fixes https://github.com/section-engineering-education/engineering-education/pull/1771/commits/2704dfa3d35175d1720c31c20a78c6f2808a3a00

2021-03-21 22:50 UTC, geoffrey45 commented
@Umoren  Thank you for submitting your first article. 

For the author details, please create a new folder at the `authors` folder with the following files:
1. `index.md` -- this file carries your bio
2. `avatar.jpg` -- this is your avatar

Feel free to look at other students' folders to get the overview. You can also duplicate one of the author folders and edit it accordingly.

2021-03-21 22:58 UTC, geoffrey45 reviewed
> The fixes [2704dfa](https://github.com/section-engineering-education/engineering-education/commit/2704dfa3d35175d1720c31c20a78c6f2808a3a00)

Please add this line to the pull request header (the part with the checkboxes).  To link an issue, this should look like this: `This fixes #...` (note the #)

2021-03-22 11:39 UTC, geoffrey45 requested changes

2021-03-22 11:39 UTC, geoffrey45 commented on articles/building-your-web-server-with-vlang/index.md
> +
Please format your image to look like this: 
```markdown
![vlang server](/engineering-education/building-your-web-server-with-vlang/v-server.png)
```
Please format all your images as shown above.

2021-03-24 11:20 UTC, Umoren commented on articles/building-your-web-server-with-vlang/index.md
> +
Okay, so there's no formal definition for the term "safe program". I was trying to explain why i think V is safe in the language policies. 
Anyway, i rewrote the sentences: `V is very strict with writing secure, fast and memory-safe programs. Some strict policies of the language are`

Is this okay?

2021-03-24 11:26 UTC, Umoren commented
This fixes #1771

2021-03-24 11:29 UTC, Umoren commented
@geoffrey45 I've made the requested changes

2021-03-25 16:03 UTC, Umoren commented
@hectorkambow i've made the requested changes

2021-03-26 21:09 UTC, geoffrey45 requested changes
@Umoren Please make the changes below and ping me when you are done. 

We tend to avoid using product logos as hero images. Please replace your `v-logo.png` with a 600 x 400 image from [Unsplash.com](https://unsplash.com), named `hero.png`  or `hero.jpg`. You can choose the download size when downloading. Feel free to create a custom hero image. 

Your images are not legible. Please replace your images with HD images. If not, you can omit them entirely and replace them with code output.

2021-03-26 21:09 UTC, geoffrey45 commented on articles/building-your-web-server-with-vlang/index.md
> +Finally, to create routes in V, you can either specify the path as an attribute like this `["/"]` or auto-mapping of function names like this `index()` .
Explain what `fn run<T>(port int)` is. Provide examples showing creating different routes using the methods above.

2021-03-29 12:33 UTC, Umoren commented
The fixes #https://github.com/section-engineering-education/engineering-education/pull/1771

2021-03-29 12:34 UTC, Umoren commented
@geoffrey45 
I've made the requested changes.

2021-03-29 12:38 UTC, geoffrey45 commented on articles/building-your-web-server-with-vlang/index.md
> +}
@Umoren This one

2021-03-29 12:42 UTC, geoffrey45 commented
@Umoren Your article's image shoub be named `hero.jpg`. Please rename the image as such.

2021-03-29 14:03 UTC, Umoren commented
Oh this doesn't have an output. It's a helper function.
The code snippet below shows the output

```c++
fn main() {
	repo := Repo{
		users: [User{1, 'Andrew'}, User{2, 'Bob'}, User{10, 'Charles'}]
	}
	user := repo.find_user_by_id(10) or { // Option types must be handled by `or` blocks
		return
	}

  user := repo.find_user_by_id(7) or {
    println(err) // "User 7 not found"
    return
  }

	println(user.id) // "10"
	println(user.name) // "Charles"
}

```
`

2021-03-29 14:05 UTC, Umoren commented
@geoffrey45 I've renamed the article image.
Thanks

2021-03-29 16:09 UTC, hectorkambow commented
plagiarism check done

2021-04-05 08:29 UTC, geoffrey45 approved these changes

2021-04-05 10:39 UTC, Umoren commented
Hi @geoffrey45 
To avert issues with payment, I have changed my Paypal link to this: 
[https://paypal.me/DanielWildegger](https://paypal.me/DanielWildegger)
Thanks.

2021-04-05 10:44 UTC, geoffrey45 commented
> Hi @geoffrey45 
> To avert issues with payment, I have changed my Paypal link to this: 
> [https://paypal.me/DanielWildegger](https://paypal.me/DanielWildegger)
> Thanks.

@hectorkambow

2021-04-05 15:50 UTC, merged