Understanding c++ templates
section-engineering-education/engineering-education pull request #1777
Opened 2021-03-18 13:12 UTC by Dawe-7

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1632

2021-03-28 11:45 UTC, adrianmurage requested changes
@Dawe-7 

I left a few sentence structure suggestions. 
I also noticed that you were using H4 headings. According to the pre-review checklist, the preferred headings are H3, H2, and H1.

Aside from that this was a great read!
Once you've made the suggested changes @ me and I'll mark the article as ready for final review.

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +This will bloat the code base and will be difficult to manage because of a change in one class that will need change on all classes/functions. But, class templates allow you to reuse the same code fo
```suggestion
The declaration of separate classes that do the same thing for different data types will bloat the code base and make it difficult to manage. Any changes made in one class will need to be reflected in all the similar classes. 

Class templates allow you to reuse the same code for all data types. Like normal arguments, we can transfer more than one type of data to templates as arguments if we need to.
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +#### Variadic function template
```suggestion
### Variadic function template
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +### Introduction
```suggestion
## Introduction
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +### Prerequisites
```suggestion
## Prerequisites
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +### How do templates work?
```suggestion
## How do templates work?
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +### Class templates
```suggestion
## Class templates
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +#### Declaration of a class template
```suggestion
### Declaration of a class template
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +#### How to create a class template object?
```suggestion
### How to create a class template object?
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +#### Advantages of class templates
```suggestion
### Advantages of class templates
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +### Function templates
```suggestion
## Function templates
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +#### Declaration of a function template?
```suggestion
### Declaration of a function template?
```

2021-03-28 11:45 UTC, adrianmurage commented on articles/understanding-c++-templates/index.md
> +### Conclusion
```suggestion
## Conclusion 
```

2021-03-28 18:20 UTC, Dawe-7 commented
Hello, @adrianmurage I've made the requested changes. I hope its good to go, thanks.

2021-03-29 07:31 UTC, adrianmurage commented
> Hello, @adrianmurage I've made the requested changes. I hope its good to go, thanks.

Yup it is @Dawe-7 
Great article 👍🏽 

@hectorkambow this article is ready for final review

2021-03-31 01:03 UTC, hectorkambow commented
great work gentlemen - be sure to go over any final edits 👍  @Dawe-7 

cc @adrianmurage

2021-03-31 01:03 UTC, merged