How to upload files to AWS S3 using Django Rest Framework
section-engineering-education/engineering-education pull request #1795
Opened 2021-03-19 09:07 UTC by Damephena

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-21 00:10 UTC, paulodhiambo commented on articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/index.md
> +Object storage is a type of storage where items processed as a data object. Contrary to the traditional method of storing files in the file system hierarchy.
Consider changing "...items processed as a data object" to "...items are processed as a data object"

2021-03-21 00:13 UTC, paulodhiambo commented on articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/index.md
> +In traditional file system, the basic unit of storage is a "file". In AWS S3, the basic unit of storage called a "bucket".
Consider changing "In traditional file system" to "In the traditional file system" and "...storage called a "bucket"." to "...storage is called a "bucket"."

2021-03-21 00:21 UTC, paulodhiambo commented on articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/index.md
> +![media_folder_included_vs_code](../how-to-upload-files-to-aws-s3-using-django-rest-framework/media_included_structure.png)
Consider changing all the image paths by appending `/engineering-education/how-to-upload-files-to-aws-s3-using-django-rest-framework/` before every the image name. For example, in this above image change `![media_folder_included_vs_code](../how-to-upload-files-to-aws-s3-using-django-rest-framework/media_included_structure.png)` to `![media_folder_included_vs_code](engineering-education/how-to-upload-files-to-aws-s3-using-django-rest-framework/media_included_structure.png)`

2021-03-21 00:21 UTC, paulodhiambo requested changes
@Damephena an amazing article. Check out the changes requested changes and ping me when done.

2021-03-21 07:46 UTC, Damephena commented
Hello @paulodhiambo, thank you for reviewing. I have made the requested changes.

2021-03-22 14:05 UTC, paulodhiambo commented
Hello @Damephena I am seeing three index.md files and I do not understand the reason why they are three.

2021-03-22 18:14 UTC, Damephena commented
Hi @paulodhiambo, there's only one index.md file. Perhaps you are mistaking the commits as extra index file.

2021-03-22 18:18 UTC, paulodhiambo commented
Check on the files changed tab, you will see there are some index.md files grom other PRs

2021-03-22 18:24 UTC, Damephena commented
I just did. 
I had re-ran the `git fetch section`. `git pull --rebase section master` commands I when updated the requested changes in order to be in sync with section's branch.
Perhaps, the reason for seeing the included files from other people's article.

2021-03-23 06:54 UTC, paulodhiambo commented
@Damephena always make sure you create a new branch every time you're writing a new article. You shouldn't be working on the master branch.

2021-03-23 06:55 UTC, Damephena commented
Noted. Thanks @paulodhiambo

2021-03-29 11:10 UTC, paulodhiambo commented
@Damephena amazing article. @hectorkambow you can give this article a final review.

2021-03-29 17:48 UTC, hectorkambow commented
@Damephena 👀  Im noticing this PR has multiple files attached to it - please fix this - as it may cause merging issues. 

see our [FAQ ](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md)for more info. 

best option would be to create a new PR with only the needed files attached to it. 

Be sure to do a git pull on your forked repo to get the latest changes. All articles should be their own separate branch on your forked repo to avoid these issues moving forward 👍 

cc @paulodhiambo

2021-03-30 21:17 UTC, Damephena commented
Hello @hectorkambow, I will close this PR and open a new one with a different branch. Thanks. 
Would use new branches moving forward.

2021-03-30 21:17 UTC, closed without merging