First commit
section-engineering-education/engineering-education pull request #1804
Opened 2021-03-20 11:57 UTC by Anitaachu

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-20 12:02 UTC, Anitaachu commented
This fixes #1760

2021-03-20 12:06 UTC, jumamiller commented
@Anitaachu, I'll review this article
cc @hectorkambow

2021-03-21 11:32 UTC, jumamiller commented on articles/converting-html-content-to-pdf-with-pdfkit-for-python/index.md
> +
I think the links 're not correctly used, for example, readers would want to click on terms/words they don't understand, to get more information. You don't have to go to the end of the sentence to get the link. My suggestion, have something like this ****We will be using [wkhtmltopdf](https://wkhtmltopdf.org) alongside..........*****.
Make use of this format where applicable throughout your article.

2021-03-21 11:34 UTC, jumamiller commented on articles/converting-html-content-to-pdf-with-pdfkit-for-python/index.md
> +![pdfkit-installation](/engineering-education/python-projects-for-beginners/pdfkit.png)
What does this image do, tell the user...., for instance, you can say .."as shown in the image below to explain your concept further..."

2021-03-21 11:36 UTC, jumamiller requested changes
@Anitaachu, I've suggested a few changes which I realized are repeated severally throughout your article. Kindly work on them.

2021-03-21 14:04 UTC, Anitaachu commented
@jumamiller changes have been made, thank you!

2021-03-22 14:45 UTC, jumamiller commented
Hi @Anitaachu, I've gone thro' the changes you made. I noticed you only made a single change for each requested change while they are repetitive in different sections of the article. I only pointed a few of the many occurrences in the article. Kindly go thro' the whole article.

2021-03-23 06:41 UTC, Anitaachu commented
I have gone through the article and made requested changes @jumamiller

2021-03-25 15:37 UTC, jumamiller commented
@hectorkambow, ready for final review on successful plagiarism checks!

2021-03-30 05:05 UTC, jumamiller commented
@adrianmurage, you could as well add the 'ready for final review' label...

2021-03-30 09:03 UTC, adrianmurage commented
@jumamiller I will 
But the main reason I add them from time to time is that they are needed.
As a reviewer, you should have the permissions to add and remove labels.
If you don't have the necessary permissions you should consult @hectorkambow on Slack preferably.

2021-03-30 19:00 UTC, hectorkambow commented
@Anitaachu  👋  good afternoon
Upon doing a final review - I found myself rewording and reworking some of the sentences. 
Some of the paragraphs were a bit difficult to get through - and I believe some sections repeat. 

If you could please revisit this article - be sure to go through, our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and helpful links on how to improve overall technical writing. 

cc: @jumamiller

2021-03-30 19:00 UTC, closed without merging