Key Design of HDFS Architecture
section-engineering-education/engineering-education pull request #1805
Opened 2021-03-20 12:14 UTC by RuthAMare

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-22 14:34 UTC, srishilesh requested changes
Hey @RuthAMare,

Thanks for the PR.

This article looks amazing. I have requested a few changes. Please let me know when it's done, we can then move on to the tech review.

As a general suggestion, make use of [hemingwayapp](hemingwayapp.com) to write short and meaningful sentences.

Make sure go through each comment, and resolve them before requesting for the review.

Thank you.

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +HDFS (Hadoop Distributed File System) is a big data distributed file system storage by Apache that is implemented within the hadoop framework and that needs to have several features of design impleme
```suggestion
HDFS (Hadoop Distributed File System) is a big data distributed file system storage by Apache. It is implemented within the Hadoop framework and that needs to have several features of design implemented to work effectively in processing, distributing, and storing big data.
```

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +HDFS (Hadoop Distributed File System) is a big data distributed file system storage by Apache that is implemented within the hadoop framework and that needs to have several features of design impleme
Please make use of [hemingwayapp](hemingwayapp.com) to write shorter and meaningful sentences.

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +- [ntroduction to Big Data Framework](#Introduction-to-Big-Data-framework)
```suggestion
- [Introduction to Big Data Framework](#Introduction-to-Big-Data-framework)
```

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +- [Colocation and its benefits in HDFS](#Colocation-and-its-benefits-in-HDFS)
On the markdown headers part, you must write everything is lower case. Something like this:

`- [Introduction to Big Data Framework](#introduction-to-big-data-framework)`

Make the changes for the remaining headings.

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +### 1) Introduction to Big Data Framework
Please remove the numbering.

If you put them here, them in the `Table of content` you have to make the changes accordingly like `#1-introduction-to-big-data-framework`

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +Big data framework is characterized by 4Vs namely; Variety (data is of various forms and types), Velocity (data processing speed is high), Value (low data value density), and Volume (massive amount o
Instead of writing the `4Vs` sequentially, write them as numbered lists.

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +***Robustness:*** HDFS stores data reliably even when failures occur. Its robustness takes into account the 3 common types of failures: DataNode failure, NameNode failure, and network failures.
Convert the `3 types` to numbered lists

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +***Data storage policy:*** HDFS supports 6 storage policies namely;
```suggestion
***Data storage policy:*** HDFS supports 6 storage policies namely:
```

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +### 3) Configuring HDFS data storage policies
Remove `3)`

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> ++ *Layered storage*
Instead of italicizing this, you can make this as another subheading with `####` as the header

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +Store key data in highly reliable node groups because the DataNode cluster uses heterogeneous servers.
Do the same here too

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> ++	Enhances easy and quick access to data.
For bulleted points, use `-` instead of `+`

2021-03-22 14:34 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +***Metadata persistence:*** The HDFS NameNode stores the namespace. The NameNode consistently records every change that occurs in file system metadata in a transaction log file called the EditLog. Wh
For `EditLog`, you could enclose them within ` `` `. Similarly, for any unique name or variable, you must enclose them within ` `` `.

Make this change wherever needed

2021-03-22 15:46 UTC, RuthAMare commented
> Hey @RuthAMare,
> 
> Thanks for the PR.
> 
> This article looks amazing. I have requested a few changes. Please let me know when it's done, we can then move on to the tech review.
> 
> As a general suggestion, make use of [hemingwayapp](hemingwayapp.com) to write short and meaningful sentences.
> 
> Make sure go through each comment, and resolve them before requesting for the review.
> 
> Thank you.

@srishilesh I've done the changes requested.
Thank you

2021-03-23 17:24 UTC, srishilesh requested changes
Hey @RuthAMare,

Thank you for making the requested changes.

I have added 1 minor suggestion. Please resolve it before we move for the final review.

Thank you.

2021-03-23 17:24 UTC, srishilesh commented on articles/key-design-of-hdfs-architecture/index.md
> +Data can still be accessed normally even when a failure occurs on the DataNode or NameNode.
Could you please explain what a `DataNode` and `NameNode` is?

2021-03-24 08:36 UTC, RuthAMare commented
> Hey @RuthAMare,
> 
> Thank you for making the requested changes.
> 
> I have added 1 minor suggestion. Please resolve it before we move for the final review.
> 
> Thank you.

Thank you for the suggestion, i just added it.

2021-03-24 14:25 UTC, srishilesh approved these changes
Hey @RuthAMare,

Thank you for making the change.

Moving this to the final review.

Thank you.

2021-03-30 01:05 UTC, hectorkambow commented
programs check done

2021-03-31 14:39 UTC, hectorkambow commented
👋  @RuthAMare  
Overall a nice article - it seems to cover some good topics. 
Please go through my final edits - as I changed a couple things around - and I want to make sure we did not change the meaning of the sentences. 

I found the last sentence confusing as I felt new topics were being discussed. 

cc @srishilesh

2021-03-31 14:40 UTC, merged