added quasar framework tutorial
section-engineering-education/engineering-education pull request #1808
Opened 2021-03-20 16:59 UTC by EspiraMarvin

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-23 14:32 UTC, geoffrey45 requested changes
@EspiraMarvin Great article. I have suggested some minor changes for overall improvements. Most of them are suggestions which you can commit as a batch.

2021-03-23 14:32 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +Now navigate to the `src` folder, then  `pages` folder and open the Index.vue file,
```suggestion
Now navigate to the `src/pages` folder and open Index.vue.
```

2021-03-23 14:32 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +    <img alt="Quasar logo" src="~assets/quasar-logo-full.svg">
```suggestion
<img alt="Quasar logo" src="~assets/quasar-logo-full.svg">
```

2021-03-23 14:32 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +You can delete the whole image tag, looks like this below.
```suggestion
You can delete the whole image tag that looks like this.
```

2021-03-23 14:32 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +We are intend to display name of a countryin the root page. In the script add the following code,
```suggestion
We are intending to display the name of a country in the root page. In the script, add the following code:
```

2021-03-23 14:32 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +1. Support for multiple platforms
Please write these as h4 headings.
```suggestion
#### 1. Support for multiple platforms
```

2021-03-26 16:38 UTC, geoffrey45 requested changes
@EspiraMarvin please make the suggested changes before I move on to the final round of review.

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +
Outline some of the best practices that you are referring to here.

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +4. Npm 5.10 or newer / yarn 1.2 or newer
Please explain why you excempt Node.js 13 and 15.

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +
In the prerequisites section, you outline the things the reader needs prior to going through your tutorial. The reader does not need Quasar CLI at this point. This is why you are guiding the installation deeper in your tutorial.
```suggestion
To follow along with this tutorial, you need:
1. Some knowledge of Vue js
2. Node.js 10.x or newer excluding 13 and 15.
3. Npm 5.10 or newer / yarn 1.2 or newer.

```

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +
Please use consistent capitalization of words like 'Quasar', etc. Review your document correcting this.

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +Navigate to the `src` folder, open App.vue you'll see a div with and id of q-app
Write inline file and folder names and code excerpts as inline code blocks. eg . `App.vue`. Revise your document fixing similar issues.

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +
```suggestion
Now navigate to the `src/pages` folder and open `Index.vue`. You can delete the whole image tag that looks like this.

```

2021-03-26 16:38 UTC, geoffrey45 commented on articles/getting-started-with-quasar-framework/index.md
> +
Rewrite the sentence "This has 3 parts; the HTML, SCRIPT(JS) and STYLE(CSS)" using html tags. eg `<template>` (HTML)  to explain SFC. Don't forget to say that this tags are in a single file.
```suggestion
Here, we are going to build a component. Just like Vue.js, Quasar uses a single file components (SFC) structure. This has 3 parts; the HTML, SCRIPT(JS) and STYLE(CSS). If you have the knowledge of building Vue.js apps this should be a breeze.

```
Make the last sentence more formal.

2021-03-30 01:00 UTC, hectorkambow commented
plagiarism check done

2021-04-01 21:23 UTC, geoffrey45 approved these changes

2021-04-04 22:41 UTC, merged