Biometric 2FA in a Django Application with TypingDNA
section-engineering-education/engineering-education pull request #1809
Opened 2021-03-20 20:41 UTC by Nomzy-kush

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-21 00:04 UTC, paulodhiambo commented
@Nomzy-kush amazing article. Few things to correct before I proceed with the review.
1. Renaming the images, give them descriptive names.
2. Adding hero image.
3. Rename the image with your author profile image to avatar.
4. Your author profile description should be in `index.md` file not `index.md.TXT` file.

2021-03-21 00:06 UTC, paulodhiambo reviewed
@Nomzy-kush amazing article. Few things to correct before I proceed with the review.
1. Renaming the images, give them descriptive names.
2. Adding hero image.
3. Rename the image with your author profile image to avatar.
4. Your author profile description should be in `index.md` file not `index.md.TXT` file.

2021-03-22 00:57 UTC, Nomzy-kush commented
@paulodhiambo I have made the required changes please review.

2021-03-24 04:20 UTC, paulodhiambo commented on articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
> +Also we need to update the `register` to create new `UserProfile` objects for every registered user. To do this, update the `register` view by entering code below after the line with`user.save`:
Consider changing "Also we need to update..." to "Also, we need to update..."

2021-03-24 04:25 UTC, paulodhiambo commented on articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
> +After building our helper library, we can start saving our users’ typing patterns in our accounts for future matching. Lets first import the helper library class into our Django application and creat
Change "Lets first import" to "Let's first import"

2021-03-24 04:28 UTC, paulodhiambo commented on articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
> +After successfully enrolling to TypingDNA, we should be redirected to a page similar to the one in the image below:
Change "After successfully enrolling to TypingDNA, ..." to "After successfully enrolling in TypingDNA, ..."

2021-03-24 04:29 UTC, paulodhiambo commented on articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
> +We want to build our verification HTML page where we will verify user identities using TypingDNA biometrics. We will also create a fall-back verification page where users can verify. Lets update our
Change "Lets update our..." to "Let's update our..."

2021-03-24 04:34 UTC, paulodhiambo requested changes
@Nomzy-kush Good article though you need to pass the article through a grammar checker (Grammarly) since it has several grammar mistakes that can be corrected by grammar checker. Ping me once you have corrected the grammar mistakes.

2021-03-24 14:24 UTC, Nomzy-kush commented
@paulodhiambo I have made the necessary changes you asked me to

2021-03-30 20:33 UTC, hectorkambow commented
plagiarism check done

2021-04-01 20:11 UTC, paulodhiambo commented on articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
> +To get started, we need to create an account on their website at [TypingDNA signup](https://www.typingdna.com/clients/signup). After creating and setting up our account, we should see a page like the
Please add the image you're talking about here.

2021-04-01 20:12 UTC, paulodhiambo commented on articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
> +Next, we need to create a `UserProfile` table for use our users to start verifying typing patterns captured typing patterns containing extra details for TypingDNA authentication users in our database
This sentence is not clear.

2021-04-01 20:14 UTC, paulodhiambo requested changes
@Nomzy-kush  make the requested changes then ping me when done.

2021-04-02 10:30 UTC, Nomzy-kush commented
@paulodhiambo I have made all the requested changes

2021-04-02 11:31 UTC, paulodhiambo commented
@Nomzy-kush amazing article. Take note of the changes I have made. @hectorkambow you can give this article a final review.

2021-04-02 11:51 UTC, Nomzy-kush commented
This fixes #1727

2021-04-05 00:51 UTC, merged