Uploading images to cloudinary from django application
section-engineering-education/engineering-education pull request #1877
Opened 2021-03-27 14:03 UTC by shosenwales

Added six images.
Wrote an article on uploading images to cloudinary from django application.

2021-03-27 14:13 UTC, srishilesh commented
Hey @shosenwales,

Thanks for the PR.

While submitting a PR, do not remove the "Article Checklist". (I have added it back). Please check the tick boxes, to check if you have done everything as per the guidelines, before we get started with the review.

Thank you.

2021-03-27 17:50 UTC, srishilesh requested changes
Hey @shosenwales,

Welcome to Section EngEd community!

Great article. I have suggested a few changes, please let me know when they're done, we can move on to the tech review.

A few more changes/suggestions:
- Add a hero image of 600x400 from Unsplash
- Add your details with a headshot in Authors' page (`authors` directory) like `authors/srishilesh-p-s`. Please refer the contributing guide and revert back if any questions.
- Please perform a grammar check using Grammarly, before you submit for review.
- Always add comments to your code snippets
- Make sure to add image sources and footers describing about the image
- Add `.` at the end of each line, and capitalize letters wherever necessary.
- Most importantly, do not remove the PR checklist. Ensure that you check all the necessary check items.

Please don't hesitate to ask questions either here or via slack.

Thank you.

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +If you deploy your Django to platform like heroku, you can't save image.
```suggestion
Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult. If you deploy your Django to a platform like Heroku, you can't save images.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +In this tutorial, we look at how to save images in Django using CLoudinary.
```suggestion
In this tutorial, we learn about how to save images in Django using Cloudinary.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
```suggestion
Cloudinary is an end-to-end image and video management solution for websites and mobile apps. It covers everything from image and video uploads, storage, manipulations, and optimizations to delivery.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +### Creating and setting up a new Django project
It would be great, if you could specify an objective of what this tutorial is going to be about or what are you going to build

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Let's start by creating a new virtual environment
Add `.` at the end of line

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Activate virtual environment
Add `.` at end of line.

Do this wherever necessary.

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +To follow along with this tutorial, you need Python3 installed on your machine.
Add a link for installation of python 3 (That would help the beginners)

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Let's start by creating a new virtual environment
Explain the need for creation of virtual environment in 1 - 2 lines. Though this is out of the scope of article, this would help the beginners.

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Lets add our app to the list of installed apps. Navigate to the "photoapp" directory and edit the settings.py file
```suggestion
Let's add our app to the list of installed apps. Navigate to the `photoapp` directory and edit the `settings.py` file.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Lets add our app to the list of installed apps. Navigate to the "photoapp" directory and edit the settings.py file
Always enclose unique words or variables or filenames within ` `` ` to highlight them

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Create new Django project
```suggestion
Create a new Django project.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Click on the Sign Up button and fill in your details to create an account.
```suggestion
Now, let's head over to the [Cloudinary](https://cloudinary.com/) website to create an account.

Click on the `Sign Up` button and fill in your details to create an account.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Install the cloudinary module in our project
```suggestion
Install the Cloudinary module in our project
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Next thing is to add Cloudinary to the list of installed apps in settings.py
```suggestion
Next thing is to add Cloudinary to the list of installed apps in `settings.py`.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +We will also need to include Cloudinary's python classes in settings.py
Enclose `settings.py` within ` `` `. And, add a `.` at the end of line.

Make these changes wherever necessary.

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +we can find our account-specific configuration credentials in the Dashboard page of the account console.
```suggestion
To use the Cloudinary Django library, we have to configure at least our `cloud_name`, `api_key` and `api_secret`. We can find our account-specific configuration credentials in the Dashboard page of the account console.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +![Cloudinary Dashboard](/engineering-education/uploading-images-to-cloudinary-from-django-application/dash.png)
Add image source (if not yours), and add an image footer describing about the image. Something like this:

*Cloudinary dashboard page*

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +In the “photos” directory, edit the models.py file and add the following lines of code to it.
Enclose `photos` and `models.py` within ` `` `

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Now let's register the photos model in the admin.py file so we can modify it in the Django admin section.
```suggestion
Now let's register the model of photos in the `admin.py` file, so we can modify it in the Django admin section.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +To login to the admin section, go to this link [localhost:8000/admin](localhost:800/admin) and login with our just created superuser details.
```suggestion
To login to the admin section, go to this link [localhost:8000/admin](localhost:8000/admin) and login with our just created superuser details.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +![](/engineering-education/uploading-images-to-cloudinary-from-django-application/django-admin.png)
It is always advised to add an image alternative.

And, add image source and footer as mentioned previously.

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Click on pictures, then click "Add Photo" to add an image
Replace ` "" ` with ` `` `

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Now let's create a view to view the image. Add the following code to your views.py file
Enclose within ` `` `

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Let's create our "templates" folder. Inside the folder, create a index.html file.
```suggestion
Let's create our `templates` folder. Inside the folder, create an `index.html` file.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Before adding our html code, let's quickly create a new url for newly created view.
```suggestion
Before adding our HTML code, let's quickly create a new URL for the newly created view.
```

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +        image = CloudinaryField('image')
Add code comments

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +
Explain what is being done here

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +]
Add code comments

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +    return render(request, 'index.html', ctx)
Add comments

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +
Add a GitHub repository link containing full codes

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +
Add key takeaways from this article, as bulleted points

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +
Add a `Table of contents` section

2021-03-27 17:50 UTC, srishilesh commented on articles/uploading-images-to-cloudinary-from-django-application/index.md
> +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
In addition to this, please also add what other solutions are present, how it is better than others, what is the current method used, and if possible give advantages of using this.

In overall, you will have to give more details in the introductory paragraph and the conclusion.

2021-03-28 13:42 UTC, shosenwales commented
Hi,

Please can i get slack invite link.

On Sat, Mar 27, 2021, 6:50 PM Srishilesh P S ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @shosenwales <https://github.com/shosenwales>,
>
> Welcome to Section EngEd community!
>
> Great article. I have suggested a few changes, please let me know when
> they're done, we can move on to the tech review.
>
> A few more changes/suggestions:
>
>    - Add a hero image of 600x400 from Unsplash
>    - Add your details with a headshot in Authors' page (authors
>    directory) like authors/srishilesh-p-s. Please refer the contributing
>    guide and revert back if any questions.
>    - Please perform a grammar check using Grammarly, before you submit
>    for review.
>    - Always add comments to your code snippets
>    - Make sure to add image sources and footers describing about the image
>    - Add . at the end of each line, and capitalize letters wherever
>    necessary.
>    - Most importantly, do not remove the PR checklist. Ensure that you
>    check all the necessary check items.
>
> Please don't hesitate to ask questions either here or via slack.
>
> Thank you.
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602757159>
> :
>
> > +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> +If you deploy your Django to platform like heroku, you can't save image.
>
>
> ⬇️ Suggested change
>
> -Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> -If you deploy your Django to platform like heroku, you can't save image.
>
> +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult. If you deploy your Django to a platform like Heroku, you can't save images.
>
>
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602757398>
> :
>
> > @@ -0,0 +1,270 @@
>
> +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> +If you deploy your Django to platform like heroku, you can't save image.
>
> +
>
> +In this tutorial, we look at how to save images in Django using CLoudinary.
>
>
> ⬇️ Suggested change
>
> -In this tutorial, we look at how to save images in Django using CLoudinary.
>
> +In this tutorial, we learn about how to save images in Django using Cloudinary.
>
>
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602757729>
> :
>
> > @@ -0,0 +1,270 @@
>
> +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> +If you deploy your Django to platform like heroku, you can't save image.
>
> +
>
> +In this tutorial, we look at how to save images in Django using CLoudinary.
>
> +
>
> +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
>
>
> ⬇️ Suggested change
>
> -Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
>
> +Cloudinary is an end-to-end image and video management solution for websites and mobile apps. It covers everything from image and video uploads, storage, manipulations, and optimizations to delivery.
>
>
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602758070>
> :
>
> > @@ -0,0 +1,270 @@
>
> +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> +If you deploy your Django to platform like heroku, you can't save image.
>
> +
>
> +In this tutorial, we look at how to save images in Django using CLoudinary.
>
> +
>
> +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
>
> +
>
> +### Prerequisites
>
> +
>
> +To follow along with this tutorial, you need Python3 installed on your machine.
>
> +
>
> +### Creating and setting up a new Django project
>
>
> It would be great, if you could specify an objective of what this tutorial
> is going to be about or what are you going to build
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602758100>
> :
>
> > @@ -0,0 +1,270 @@
>
> +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> +If you deploy your Django to platform like heroku, you can't save image.
>
> +
>
> +In this tutorial, we look at how to save images in Django using CLoudinary.
>
> +
>
> +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
>
> +
>
> +### Prerequisites
>
> +
>
> +To follow along with this tutorial, you need Python3 installed on your machine.
>
> +
>
> +### Creating and setting up a new Django project
>
> +
>
> +Let's start by creating a new virtual environment
>
>
> Add . at the end of line
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602758241>
> :
>
> > +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
>
> +
>
> +### Prerequisites
>
> +
>
> +To follow along with this tutorial, you need Python3 installed on your machine.
>
> +
>
> +### Creating and setting up a new Django project
>
> +
>
> +Let's start by creating a new virtual environment
>
> +
>
> +```bash
>
> +$ python -m virtualenv env
>
> +
>
> +```
>
> +
>
> +Activate virtual environment
>
>
> Add . at end of line.
>
> Do this wherever necessary.
> ------------------------------
>
> In
> articles/uploading-images-to-cloudinary-from-django-application/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/1877#discussion_r602758816>
> :
>
> > @@ -0,0 +1,270 @@
>
> +Sometimes while working on applications that require the use of images, a simple process like uploading images to a server can become difficult.
>
> +If you deploy your Django to platform like heroku, you can't save image.
>
> +
>
> +In this tutorial, we look at how to save images in Django using CLoudinary.
>
> +
>
> +Cloudinary is an end-to-end image- and video-management solution for websites and mobile apps, covering everything from image and video uploads, storage, manipulations, optimizations to delivery.
>
> +
>
> +### Prerequisites
>
> +
>
> +To follow along with this tutorial, you need Python3 installed on your machine.
>
>
> Add a link for installation of python 3 (That would help the beginne [...]

2021-03-28 14:43 UTC, srishilesh commented
@shosenwales 

You can join via this invite: https://join.slack.com/t/sectionio-community/shared_invite/zt-6174cklt-YFpHmQIAUmc927jqN2EIZQ

2021-03-28 20:02 UTC, shosenwales commented
Hi, I think I fixed all issues. kindly review

2021-03-29 15:51 UTC, srishilesh approved these changes
Hey @shosenwales,

Thanks for making the requested changes.

I have made some corrections to your entire article. Make sure you go through every commit carefully, to understand how you could improve on your future articles.

As a general suggestion:
- Always write meaningful sentences (many sentences lacked clarity).
- Always add inline comments to your code snippets.
- Make sure to explain code snippets in-detail.
- Don't skip any step while explaining code snippets
- Add info about everything that you use. Sometimes the reader might not be familiar with something, that everyone is familiar with.

Moving this to the final review.

Feel free to reach to me, in case of any clarifications. Would be happy to help!

Thank you.

2021-03-29 16:23 UTC, shosenwales commented
Thank you, I will do that.

On Mon, Mar 29, 2021, 4:52 PM Srishilesh P S ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hey @shosenwales <https://github.com/shosenwales>,
>
> Thanks for making the requested changes.
>
> I have made some corrections to your entire article. Make sure you go
> through every commit carefully, to understand how you could improve on your
> future articles.
>
> As a general suggestion:
>
>    - Always write meaningful sentences (many sentences lacked clarity).
>    - Always add inline comments to your code snippets.
>    - Make sure to explain code snippets in-detail.
>    - Don't skip any step while explaining code snippets
>    - Add info about everything that you use. Sometimes the reader might
>    not be familiar with something, that everyone is familiar with.
>
> Moving this to the final review.
>
> Feel free to reach to me, in case of any clarifications. Would be happy to
> help!
>
> Thank you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/1877#pullrequestreview-623386698>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGUVYRNGUUJJ5HGQXTRD7VTTGCO2BANCNFSM4Z46IOSA>
> .
>

2021-04-01 22:40 UTC, hectorkambow commented
plagiarism check done

2021-04-12 12:53 UTC, shosenwales commented
Hi @srishilesh, trust you are doing well. Just checking for updates...is there anything that needs to be done from my end.

2021-04-12 12:55 UTC, srishilesh commented
> Hi @srishilesh, trust you are doing well. Just checking for updates...is there anything that needs to be done from my end. 

Hey @shosenwales,

Everything's good. This article has been moved to the final review queue.

Now, Hector will be doing the final review before publishing.

Thank you.

2021-04-12 13:15 UTC, shosenwales commented
Oh alright, thanks

On Mon, 12 Apr 2021, 1:56 pm Srishilesh P S, ***@***.***>
wrote:

> Hi @srishilesh <https://github.com/srishilesh>, trust you are doing well.
> Just checking for updates...is there anything that needs to be done from my
> end.
>
> Hey @shosenwales <https://github.com/shosenwales>,
>
> Everything's good. This article has been moved to the final review queue.
>
> Now, Hector will be doing the final review before publishing.
>
> Thank you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/1877#issuecomment-817787468>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGUVYRMB4ZEQVI6JQ3AV2ZLTILUWNANCNFSM4Z46IOSA>
> .
>

2021-04-13 18:56 UTC, hectorkambow commented
great work gentlemen @shosenwales  

cc @srishilesh

2021-04-13 18:56 UTC, merged

2021-04-13 21:39 UTC, shosenwales commented
Thanks @hectorkambow