How To Build A Custom URL Shortener Using Node.js, Express and MongoDB
section-engineering-education/engineering-education pull request #1888
Opened 2021-03-29 14:39 UTC by marienjus

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-03-29 14:40 UTC, marienjus commented
This fixes #1810

2021-03-30 15:11 UTC, marienjus commented
cc: @cyberShaw

2021-03-31 13:43 UTC, cyberShaw commented
Thank you for adding the author page, @marienjus!
I'll do the review shortly.

2021-04-01 20:15 UTC, cyberShaw requested changes
Excellent article, @marienjus!

The article was really good and is good for a beginner to get started with node and express. I've included some comments, please make those changes and we can move on to the next round of review.

And please run your article through a grammar checker like Grammarly before submitting the article. there were a couple of minor changes which I fixed.

2021-04-01 20:15 UTC, cyberShaw commented on articles/node-url-shortener/index.md
> +```js
Please add code comments here. 
I know that you've explained the code, but comments make the code more readable.

2021-04-01 20:15 UTC, cyberShaw commented on articles/node-url-shortener/index.md
> +
Please add a heading that mentions that this code is to be included inside `db.config.js`

2021-04-01 20:15 UTC, cyberShaw commented on articles/node-url-shortener/index.md
> +})
Please add code comments

2021-04-01 20:15 UTC, cyberShaw commented on articles/node-url-shortener/index.md
> +const express = require('express')
More code comments here would improve the quality of the article

2021-04-01 20:15 UTC, cyberShaw commented on articles/node-url-shortener/index.md
> +### Conclusion
It would be helpful if you could upload the final code on GitHub and paste a link to the repository

2021-04-01 23:56 UTC, marienjus commented
Hey, @cyberShaw I hope everything is okay now. Done changes

2021-04-02 04:19 UTC, cyberShaw commented
Great job on making the changes, @marienjus!
This article is ready for final review.

2021-04-06 20:34 UTC, hectorkambow commented
plagiarism check done

2021-04-06 21:50 UTC, hectorkambow commented
Great work @marienjus  
Seems like a very helpful aritcle.
🚀 
cc @cyberShaw

2021-04-06 21:50 UTC, merged

2021-04-07 00:06 UTC, marienjus commented
Thank you. Hoping to write quality stuffs as I learn.