How to set up a Node.js Express server for React
section-engineering-education/engineering-education pull request #1917
Opened 2021-03-31 23:21 UTC by verah-tech

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-04-01 00:35 UTC, verah-tech commented
This solves #1868

2021-04-01 07:01 UTC, lalith1403 commented
@cyberShaw I would like to review this article. I see you have a couple of articles on your plate. Thank you.

cc: @hectorkambow

2021-04-01 07:09 UTC, cyberShaw commented
> @cyberShaw I would like to review this article. I see you have a couple of articles on your plate. Thank you.
> 
> cc: @hectorkambow

Sure thing, @lalith1403 
Go ahead :D

2021-04-05 18:59 UTC, hectorkambow commented
plagiarism check done

2021-04-08 17:18 UTC, lalith1403 commented
This is a very good detailed and easy to follow article. Congratulations on a well written article. You will have to include a headshot pic and short bio in a folder named after your name in the authors folder. Check the authors folder for more details. 

The code is explained well and runs fine.

2021-04-08 17:28 UTC, lalith1403 requested changes
Minor changes are required. Explain webpacks to add more content to the article. Overall, terrific job.

2021-04-08 17:28 UTC, lalith1403 commented on articles/how-to-setup-nodejs-express-for-react/index.md
> +Next will be to create an Express server inside the server.js. Browse to the root directory from the terminal and run the below command:
```suggestion
The next step involves creating an Express server in the file `server.js`. Browse to the root directory from the terminal and run the command mentioned below.
```

2021-04-08 17:28 UTC, lalith1403 commented on articles/how-to-setup-nodejs-express-for-react/index.md
> +In this step, the Webpack development server was auto-generated when we ran the `create-react-app` command.  Our react App is running on the Webpack development server on the frontend.  We can proxy
Explain webpack development server in short.

2021-04-08 17:28 UTC, lalith1403 commented on articles/how-to-setup-nodejs-express-for-react/index.md
> +First will be to navigate to root directory `demoreactapp` and run the below command:
Rewrite this sentence. We navigate to the root directory `demoreactapp` and run the command below:

2021-04-08 17:28 UTC, lalith1403 commented on articles/how-to-setup-nodejs-express-for-react/index.md
> +After running the `server.js`, next will be to browse to “<http://localhost:5000/express_backend>”, and the below message will be displayed:
Mention file before mentioning file name. After running the file server.js

2021-04-08 17:28 UTC, lalith1403 commented on articles/how-to-setup-nodejs-express-for-react/index.md
> +Finally, we have rendered the data fetched from the `GET route` in `server.js` to our frontend React App, as demonstrated above. If the Express server is disconnected, the React server will continue
Last sentence needs to be broken down into 2 simpler sentences.

2021-04-09 09:40 UTC, verah-tech commented
@lalith1403 The requested changes have been done. Also, the Author's information has been updated.
Thank you

2021-04-10 19:00 UTC, lalith1403 commented
The headshot image is missing in the authors folder.

2021-04-10 19:02 UTC, lalith1403 approved these changes

2021-04-10 20:11 UTC, verah-tech commented
@lalith1403 headshot updated

2021-04-15 17:08 UTC, hectorkambow commented
great work and article @verah-tech 

cc @lalith1403  🚀

2021-04-15 17:09 UTC, merged

2021-04-16 06:40 UTC, ephnjor2021 commented
@hectorkambow Thank you

2021-04-16 06:44 UTC, verah-tech commented
@hectorkambow Thank you