Android Application Widgets Tutorial in Java
section-engineering-education/engineering-education pull request #1923
Opened 2021-04-01 14:21 UTC by manmusa100

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-04-01 14:21 UTC, manmusa100 commented
This fixes #1800

2021-04-01 14:28 UTC, BrianaNzivu commented
Hi @cyberShaw . Can I review this article since you already have more than 2 PRs.
Regards.

2021-04-01 14:37 UTC, cyberShaw commented
> Hi @cyberShaw . Can I review this article since you already have more than 2 PRs.
> Regards.

Go ahead, @BrianaNzivu

2021-04-05 13:29 UTC, BrianaNzivu requested changes
Hey @manmusa100 . Good job! The article is well articulated and easy to follow. 
I have pointed out a few corrections and suggestions on how to fix these corrections. 
Do let me know when you are done.
Good job!

2021-04-05 13:29 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +### Conclusion
You can have a sample APK and even a gif demo of the widget to illustrate what a reader should achieve after using this tutorial.

2021-04-05 13:29 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +`onDisabled()`: This method is called when the widget's last instance is deleted. For example, we can launch an activity within this function.
I think you can have the java code here just like how you've displayed your XML code.

2021-04-05 13:29 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +### Limitations of Widgets
Since you've talked about the limitations..I think you can also mention the advantages of having a widget.

2021-04-05 13:29 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +Declare the AppWidgetProvider class in the manifest file `AndroidManifest.xml` as a broadcast receiver. The IDE has already added this. If we created the widget class manually, we would have to add i
Illustrate this by adding the line of code that must be added in the manifest.

2021-04-05 13:29 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +**Step 8: Place the widget on the home screen**
I think you can use a gif demo to illustrate this rather than having screenshots. It's easier and more reader-friendly.

2021-04-05 13:29 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +![Android Studio create project](/engineering-education/android-application-widgets-tutorial-in-java/android-studio-create-empty-activity-project.jpg)
This is a basic easy step, I don't think you need to illustrate this using an image.

2021-04-05 14:30 UTC, BrianaNzivu requested changes

2021-04-05 14:30 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +- **Widget configuration:** For the widgets that need to be configured, you should creating a widget configuration activity. Widget configuration activity is an activity that opens when a user drops
This statement is unclear.

2021-04-08 13:25 UTC, BrianaNzivu commented
Hey @manmusa100 . I have noticed there is the use of a lot of personal pronouns which is not proper when it comes to technical writing. Focus on replacing "you" and "your" with the words like the usre, the developer e.t.c. Also, you are using passive voice a lot. Work on fixing that. Maybe you can do some research and read more on sentence structures and general writing. I know [Google](https://developers.google.com/tech-writing) has one of the best technical writing courses. Aside from that do take note of all the current changes I have made just to improve your writing.

Regards.

2021-04-11 18:31 UTC, manmusa100 commented
Hey, @BrianaNzivu I have worked on the suggestions. I had challenges including the code snippets in the article. Most of the code in AndroidStudio is boilerplate code which will lead to a high percentage of plagiarism. Regarding technical writing styles, I follow [https://www.prisma.io/docs/about/style-guide#word-choice](https://www.prisma.io/docs/about/style-guide#word-choice). I will also consider going through the Google guide on technical writing. Thanks.

2021-04-11 19:23 UTC, BrianaNzivu requested changes
Hey @manmusa100 . Seen the changes. Great job.  There is still one more change and we will be good to go.

Regards.

2021-04-11 19:23 UTC, BrianaNzivu commented on articles/android-application-widgets-tutorial-in-java/index.md
> +`onDisabled()`: This method is called when the widget's last instance is deleted. For example, we can launch an activity within this function.
I have seen the picture. I was wondering if we could have the code snippet instead. It's much better than a picture.

2021-04-11 19:29 UTC, BrianaNzivu commented
> Hey, @BrianaNzivu I have worked on the suggestions. I had challenges including the code snippets in the article. Most of the code in AndroidStudio is boilerplate code which will lead to a high percentage of plagiarism. Regarding technical writing styles, I follow https://www.prisma.io/docs/about/style-guide#word-choice. I will also consider going through the Google guide on technical writing. Thanks.

Oh, I see. I have also checked it out.  Last I checked your plagiarism was at 10% so I don't think there's anything for you to change- yet. I can send you the report if you want me to. If you want to hack plagiarism when it comes to Android Studio's code just change some minor things like changing the name of variables, strings, arrangement of statements, etc. It is a hack I learned from one of the technical writers which I have always used since then.  Works like a charm.

Regards.

2021-04-13 11:26 UTC, manmusa100 commented
Hi, @BrianaNzivu Thanks for the insights, I have reduced plag to 5%.

2021-04-14 11:52 UTC, BrianaNzivu approved these changes
Great. Good job.

2021-04-17 22:13 UTC, hectorkambow commented
@manmusa100  The apk file in the PR - we can not publish this - what is this file for? 
🤔

2021-04-17 22:15 UTC, hectorkambow commented
plagiarism check done

2021-04-17 22:27 UTC, BrianaNzivu commented
> @manmusa100  The apk file in the PR - we can not publish this - what is this file for? 
> 🤔 

Hey @hectorkambow 👋🏾 . I requested him to have a sample APK which can be used as a point of reference. Maybe he can try other alternatives to make the reader access the APK...🤔 For example he can have the APK hosted on Google drive and have a sharable link in the article🤔

2021-04-19 08:12 UTC, manmusa100 commented
Hey, @hectorkambow @BrianaNzivu I have deleted the apk file, uploaded the file on GOogle Drive, and provided a link.

2021-04-19 11:28 UTC, BrianaNzivu approved these changes
Hey @manmusa100 - This much better and I can see the APK is functional.
Great job!

cc: @hectorkambow .

2021-04-19 13:34 UTC, manmusa100 commented
@BrianaNzivu This is my first article. How do I submit Author's bio?

2021-04-19 15:43 UTC, hectorkambow commented
> @BrianaNzivu This is my first article. How do I submit Author's bio?

@manmusa100  

Great question - please refer to our [FAQ here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/FAQ.md#how-do-i-add-my-author-page)

2021-04-19 16:16 UTC, BrianaNzivu commented
> @BrianaNzivu This is my first article. How do I submit Author's bio?

Hey @manmusa100 . I am sorry... I didn't know it was you first time. Welcome on board.
Just check out the link Hector has provided you with.
Do ping me incase of any queries or help.
I am here to help.
Once again I am very sorry.

2021-04-19 17:41 UTC, manmusa100 commented
@BrianaNzivu No worries. Thank you. I just added the author bio
cc @hectorkambow

2021-04-19 19:15 UTC, BrianaNzivu approved these changes
Great! I think we are good to go.

cc @hectorkambow

2021-04-20 16:32 UTC, hectorkambow commented
great work @manmusa100  

Please go over any final edits I may have made just to avoid them in future articles 👍  

cc @BrianaNzivu  please do the same - and also try to add the front matter to future articles by [following these instructions. ](https://github.com/section-engineering-education/engineering-education/blob/master/peer_reviewers/front-matter-process.md)

2021-04-20 16:32 UTC, merged

2021-04-20 18:16 UTC, BrianaNzivu commented
> great work @manmusa100  
> 
> Please go over any final edits I may have made just to avoid them in future articles 👍  
> 
> cc @BrianaNzivu  please do the same - and also try to add the front matter to future articles by [following these instructions. ](https://github.com/section-engineering-education/engineering-education/blob/master/peer_reviewers/front-matter-process.md)

Hey @hectorkambow 👋🏾 . 
Noted.
Will do.