Sending SMS in Nodejs using vonage's SMS API
section-engineering-education/engineering-education pull request #1930
Opened 2021-04-01 21:04 UTC by mercymeave

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1838

2021-04-02 03:01 UTC, zolomohan commented
Hi @WanjaMIKE. I would like to review this article. I notice you have some more articles on your plate.

cc @hectorkambow

2021-04-07 13:23 UTC, WanjaMIKE commented on articles/send-sms-in-nodejs-using-vonage-api/index.md
> +Vonage's SMS API allows programmers to integrated messaging services into an application with ease. Vonage's API's benefits are support local phone numbers, low latency, high delivery rates, and mode
Vonage's SMS API allows programmers to `integrated` messaging services into an application with ease

integrate

2021-04-07 13:25 UTC, WanjaMIKE commented on articles/send-sms-in-nodejs-using-vonage-api/index.md
> +We will create a folder called `views` where we will store our view file. Under the folder, we create an `index.html` file where we will have the input fields for holding the phone number and message
We will create a folder called `views` where we will store our view `file`   -  view files

2021-04-07 13:27 UTC, WanjaMIKE commented on articles/send-sms-in-nodejs-using-vonage-api/index.md
> +#### Implemeting Nexmo
`Implementing Nexmo` also use `###` rather than `####`

2021-04-07 13:28 UTC, WanjaMIKE commented on articles/send-sms-in-nodejs-using-vonage-api/index.md
> +Next, we will send the repose data to the client to show if the SMS was sent successfully or not. To do this, we will send the response data from nexmo to the client in the `main.js` file using `io.e
Next, we will send the `repose` data to the client to show if the SMS was sent successfully or not.

Do you mean response

2021-04-07 13:30 UTC, WanjaMIKE requested changes
Nice article mercymeave. Good grammar. Could you please go through the above comments.

2021-04-07 13:40 UTC, WanjaMIKE requested changes
Nice article mercymeave. Good grammar. Could you please go through the above comments.

2021-04-08 06:09 UTC, mercymeave commented
> Nice article mercymeave. Good grammar. Could you please go through the above comments.

Thank you @WanjaMIKE , I have corrected the typo mistakes.

2021-04-08 20:32 UTC, jerimkaura commented
> @mercymeave you did not run the article through a grammar checker such as `grammarly`. This is evident from the numerous errors I have identified `throughout` in the project. Please take some time and go through the article and make other required `edits`. I did not review after `### Adding the send functionality`, so you can focus more on this part.
> 
> Also
> Ensure that you reference images correctly.
> `](/engineering-education/flutter-folder-organization/text-before-sending.png` your branch name is `send-sms-in-nodejs-using-vonage-api` not `flutter-folder-organization`.
> 
> Thanks

Thank you for the comment @WanjaMIKE , I have done so.

2021-04-11 08:39 UTC, WanjaMIKE approved these changes

2021-04-12 19:23 UTC, hectorkambow commented
plagiarism check done

2021-04-12 20:15 UTC, merged