Building your first telegram bot in Node.js
section-engineering-education/engineering-education pull request #1933
Opened 2021-04-01 22:23 UTC by calebroHQ

In this tutorial, you will learn how to build telegram bots using node.js runtime environment and telegraf library from scratch. This will act as an introduction to the Telegram bot environment that will enable you to build weather bot, vendor bots, e-commerce bot, or even dictionary bot. This tutorial will be as beginner-friendly as possible.

image1, image2,image3 are screenshots from the telegram bot I just created.

2021-04-02 02:49 UTC, cyberShaw commented
Hey, @calebroHQ!
Could you please replace the hero image with another that is of dimensions 600x400?

2021-04-02 03:09 UTC, cyberShaw requested changes
Great article on telegram bots, @calebroHQ!

The article is of only 500+ words. The requirement demands the article to be of 750 words minimum. Please add more content to the article and make the changes that I've suggested below and we can move on to the next round of review.

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +Telegram bots have made it easy to automate task in telegram channels and groups. You can even build your own telegram bot to curate news or monitor cryptocurrencies trend for you.
```suggestion
Telegram bots have made it easy to automate tasks in telegram channels and groups. You can even build your own telegram bot to curate news or monitor cryptocurrencies trend for you.
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +4. Basic knowledge on using the CLI
```suggestion
4. Basic knowledge of using the CLI
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +First go to the the telegram search bar and search @botfather (this is a special telegram bot that controls all others).We are going to use this to get a token for our new bot. There are several comm
```suggestion
First, go to the telegram search bar and search @botfather (this is a special telegram bot that controls all others). We are going to use this to get a token for our new bot. There are several commands associated with @botfather, we are going to start with /newbot then provide the desired name for the bot. The name must always end with 'bot'. Now that we have the token we can write the code.
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +Lets first create a folder for our new project, i.e: myfirstbot. Open the command line and navigate to the folder. Initialize the project by running the following commands to install telegraf:
```suggestion
Let us first create a folder for our new project, i.e: myfirstbot. Open the command line and navigate to the folder. Initialize the project by running the following commands to install telegraf:
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +We have successfully written two blocks of codes, one thats welcomes you when you start the bot and the other sends you images when you click inline keyboard buttons. Run the bot in the terminal and
```suggestion
We have successfully written two blocks of codes, one that welcomes you when you start the bot and the other sends you images when you click inline keyboard buttons. Run the bot in the terminal and then go to the telegram search bar and search the name of your bot.
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +In this article we have gone through how to get your telegram bot token, setting up your environment and writing a simple bot for displaying imagesof animals using inline keyboard feature.
```suggestion
In this article we have gone through how to get your telegram bot token, setting up your environment and writing a simple bot for displaying images of animals using the inline keyboard feature.
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +![bot results](image1.jpg)
```suggestion
![bot result 1](/engineering-education/telegram-bot-in-nodejs/image1.jpg)
```

Image paths should be of form, /engineering-education/telegram-bot-in-nodejs/image1.jpg

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +![bot results](image2.jpg)
```suggestion
![bot result 2](/engineering-education/telegram-bot-in-nodejs/image2.jpg)
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +![bot results](image3.jpg)
```suggestion
![bot result 3](/engineering-education/telegram-bot-in-nodejs/image3.jpg)
```

2021-04-02 03:09 UTC, cyberShaw commented on articles/Building-your-first-Telegram-bot-in-Node.js/index.md
> +```javascript
Please add code comments wherever you write code.
This ensures that beginners can understand the code

2021-04-02 03:10 UTC, cyberShaw commented
@calebroHQ Please pull changes before making the changes

2021-04-05 00:51 UTC, hectorkambow commented
plagiarism check done

2021-04-07 04:51 UTC, calebroHQ commented
@cyberShaw I have made the revision as suggested.

2021-04-07 23:17 UTC, cyberShaw commented
Thank you for making the changes, @calebroHQ!

I have two minor changes that need to be made:

1. Please add a hero image of dimensions 600 x 400. The hero image you added is of 600 x 368
2. Add a GitHub link that contains the final code for this tutorial.

2021-04-08 13:57 UTC, calebroHQ commented
@cyberShaw hey, It's all done.

2021-04-09 05:36 UTC, cyberShaw approved these changes

2021-04-09 20:48 UTC, hectorkambow commented
great work gentlemen @calebroHQ 

cc @cyberShaw

2021-04-09 20:52 UTC, merged