Concepts and Configuration of the Spanning Tree Protocol
section-engineering-education/engineering-education pull request #1947
Opened 2021-04-04 10:51 UTC by Dawe-7

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1851

2021-04-04 11:08 UTC, cyberShaw requested changes
Great article, @Dawe-7!
Please make some minor changes that I've requested and we can move to tech review.

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +![STP interface states](/engineering-education/concepts-and-configuration-of-stp/interface-states.jpg)
Please add the image source here

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +![STP ports](/engineering-education/concepts-and-configuration-of-stp/spanning-tree.jpg)
Please add the image source attribution for images taken from external sources.

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +- Root—The port allocated to this position is [the best route to the root switch](https://www.ciscopress.com/articles/article.asp?p=1728837).
```suggestion
- Root — The port allocated to this position is [the best route to the root switch](https://www.ciscopress.com/articles/article.asp?p=1728837).
```

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +- Designated—The port assigned to this position is chosen based on the best route to a particular switched segment; each switched segment has only one designated port.
```suggestion
- Designated — The port assigned to this position is chosen based on the best route to a particular switched segment; each switched segment has only one designated port.
```

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +- Alternate—This port is designated as a backup to the root port; [if the root port fails, this port will assume control of the root port role](https://www.yumpu.com/en/document/view/35765136/chapter
```suggestion
- Alternate — This port is designated as a backup to the root port; [if the root port fails, this port will assume control of the root port role](https://www.yumpu.com/en/document/view/35765136/chapter-9-rapid-spanning-tree-protocol-rstp-e-c-spot-on).
```

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +- Backup—The port assigned to this position is set as a fallback for the designated port; if the designated port fails, this port assumes the designated port's role.
```suggestion
- Backup — The port assigned to this position is set as a fallback for the designated port; if the designated port fails, this port assumes the designated port's role.
```

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +- Blocking State -Blocking ports do not forward traffic; instead, they listen to the network to determine if they can continue to block traffic. The port could go into listening mode if the state of
```suggestion
- Blocking State - Blocking ports do not forward traffic; instead, they listen to the network to determine if they can continue to block traffic. The port could go into listening mode if the state of the switched network changes. Following switch initialization, all ports are in a blocking mode.
```

2021-04-04 11:08 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +In a switched Ethernet network, redundant paths, on the other hand, can trigger logical and physical layer 2 loops. The Spanning Tree Protocol is a loop-prevention network protocol that [creates a lo
This courserhero link requires a subscription to view. Please add a link that readers can refer to that is free to view.

2021-04-04 13:38 UTC, Dawe-7 commented
Hey, @cyberShaw I've made the requested changes, I hope it's good to go to the next stage.
Thanks.

2021-04-05 19:23 UTC, cyberShaw commented
I'll do the review by today, @Dawe-7

2021-04-07 23:33 UTC, cyberShaw requested changes
Great article, @Dawe-7!

I've suggested some very minor changes. Please make them and we can mark the article ready for final review.

2021-04-07 23:33 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +Redundancy is an important aspect of the hierarchical architecture for avoiding network service failures and removing single points of failure. Physical paths must be added to redundant networks, but
> service failures and removing single points of failure.

Please give an illustrated example for Single Point of failure

2021-04-07 23:33 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +A root switch election occurs when all switches behave as if they are the root switch at first and continue to do so until they receive traffic from a superior switch (switch priority determines). Th
> (switch priority determines)

How is switch priority determined? Please add a line or two elaborating this so that beginners follow easily.

2021-04-07 23:33 UTC, cyberShaw commented on articles/concepts-and-configuration-of-stp/index.md
> +
Please provide a summary of the configuration that's been done in this article.

2021-04-08 20:47 UTC, Dawe-7 commented
Hi, @cyberShaw I've made the minor changes requested.

2021-04-09 05:34 UTC, cyberShaw commented
This article is ready for final review.

cc: @hectorkambow

2021-04-09 05:37 UTC, cyberShaw approved these changes

2021-04-20 17:33 UTC, hectorkambow commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Concepts and Configuration of the Spanning Tree Protocol #1947.pdf](https://github.com/section-engineering-education/engineering-education/files/6345588/Concepts.and.Configuration.of.the.Spanning.Tree.Protocol.1947.pdf)

2021-04-21 21:11 UTC, Dawe-7 commented
Hello, @hectorkambow I've added sources to fix the plagiarism. Kindly review.

cc @cyberShaw

2021-04-26 03:47 UTC, cyberShaw commented
@hectorkambow could you please do a plagiarism check for this article? Thank you.

cc: @Dawe-7

2021-04-26 21:31 UTC, hectorkambow commented
plagiarism check done

2021-04-29 16:05 UTC, hectorkambow commented
great work gents @Dawe-7  

cc @cyberShaw

2021-04-29 16:05 UTC, merged