An Introduction to K-Nearest Neighbors (KNN) Algorithm
section-engineering-education/engineering-education pull request #1949
Opened 2021-04-04 11:44 UTC by srishilesh

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1659

2021-04-04 12:05 UTC, cyberShaw requested changes
Excellent article on KNN algorithm, @srishilesh!
It was really easy and simple to follow.

I've suggested some minor changes. Please make those changes and we can move on to final review.

2021-04-04 12:05 UTC, cyberShaw commented on articles/introduction-to-knn-algorithm/index.md
> +
It would be great if you could include a link to an article that explains KNN mathematically in detail

2021-04-04 12:05 UTC, cyberShaw commented on articles/introduction-to-knn-algorithm/index.md
> +
Please include commands to install these libraries, it would be easier for readers to follow:

```bash
pip install numpy
```

2021-04-04 12:05 UTC, cyberShaw commented on articles/introduction-to-knn-algorithm/index.md
> +*The formula for Euclidean distance*
```suggestion

*The formula for Euclidean distance*
```

2021-04-04 12:12 UTC, srishilesh commented on articles/introduction-to-knn-algorithm/index.md
> +In this article, we will learn about a supervised machine learning algorithm called K-Nearest Neighbors (KNN). This algorithm can be used for tasks like classification and prediction. By the end of t
I will add the definitions of classification and regression under `### K-Nearest Neighbors algorithm`

2021-04-04 12:38 UTC, srishilesh commented
Hey @cyberShaw,

Thanks for the review.

I have made the requested changes. Please have a look.

Thank you.

2021-04-04 14:42 UTC, cyberShaw commented
Thank you for making the changes, @srishilesh!
This article is ready for final review.

2021-04-04 14:47 UTC, cyberShaw approved these changes

2021-04-20 17:38 UTC, hectorkambow commented
plagiarism check done

2021-04-26 19:03 UTC, merged