from theory to practice implementing totp 2fa in python and flask
section-engineering-education/engineering-education pull request #1957
Opened 2021-04-04 20:09 UTC by prince-joel

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-04-08 00:03 UTC, cyberShaw commented
@prince-joel could you dm me an avatar image of yourself on slack that I can upload it?

2021-04-08 00:25 UTC, cyberShaw requested changes

2021-04-08 00:25 UTC, cyberShaw commented on articles/from-theory-to-practice-implementing-totp-2fa-in-python-and-flask/index.md
> +Google Authenticator uses a software-based authentication technique made by google that implements 2FA using TOTP and HMAC-based one-time password (HOTP) for authenticating users of an application. I
> HMAC-based one-time password

Please expand HMAC and give a brief two line definition on what it is.

2021-04-08 00:25 UTC, cyberShaw commented on articles/from-theory-to-practice-implementing-totp-2fa-in-python-and-flask/index.md
> +from flask import *
Please include comments in the code that explain what is being done

This makes it easier for a beginner to follow

2021-04-08 00:25 UTC, cyberShaw commented on articles/from-theory-to-practice-implementing-totp-2fa-in-python-and-flask/index.md
> +
Please include a GitHub link of the final code of the application that you built.

2021-04-08 01:20 UTC, prince-joel commented
@cyberShaw I have added the avatar image

2021-04-08 01:34 UTC, cyberShaw commented
The Avatar looks good 👍
Also, please fill out the checkboxes in the PR description

2021-04-08 22:53 UTC, prince-joel commented
@cyberShaw I have filled out the checkboxes in the PR description

2021-04-09 05:31 UTC, cyberShaw commented
Please make the changes that I've suggested in order to move on to the next round of review.

2021-04-10 12:18 UTC, prince-joel commented
cybershaw

2021-04-10 12:24 UTC, prince-joel commented
@cyberShaw  i have made the changes you requested

2021-04-10 19:21 UTC, cyberShaw approved these changes

2021-04-20 17:47 UTC, hectorkambow commented
plagiarism check done

2021-04-27 18:22 UTC, merged