Designing IoT solutions
section-engineering-education/engineering-education pull request #1969
Opened 2021-04-05 20:54 UTC by OMONDIELLY

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

#1825

2021-04-06 17:01 UTC, OMONDIELLY commented
hello @collins-a , I have made changes that are required.
Can I revise the title of the Article or help me change it to something like "Overview of IoT Technology"

2021-04-06 17:50 UTC, collins-a requested changes
Hey @OMONDIELLY, this is a pretty good first article. I especially enjoyed how you simplified your content. However, there are a few changes to be made before we get to the final review. Some of the sections came off as a bit ambiguous or lightweight. Take note of the review comments. Just some additions and we'll be good to go.

A couple more things:

1. Your hero image. Is it from Unsplash? It's also advisable to use an image that's as close as possible to 600x400 pixels. The current one well exceeds those dimesnions.
2. As a new contributor, I encourage you to add a brief Author Bio (index.md file) and Headshot image (avatar file). Include these files in the authors folder within the GitHub repo via your forked repo similar to the article files so as to be credited for your hard work.
3. Welcome to EngEd and don't hesitate to check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) pages to make your EngEd experience much easier.

2021-04-06 17:59 UTC, OMONDIELLY commented on articles/designing-iot-solutions/index.md
> +Cloud platforms such as Azure host IoT hub where that acts as middleware for IoT solutions. Azure IoT hub provides reliable and secure communications between IoT devices and IoT applications that run
Sure , let me make the edits
Though I have Author page.

2021-04-12 11:08 UTC, collins-a commented on articles/designing-iot-solutions/index.md
> +Cloud platforms such as Azure host IoT hub where that acts as middleware for IoT solutions. Azure IoT hub provides reliable and secure communications between IoT devices and IoT applications that run
Looking through the submitted files, there is neither an author bio nor an avatar image. Do be sure to upload them

2021-04-12 11:15 UTC, collins-a commented
Hey @OMONDIELLY, just checking in to make sure you're working on the changes I requested previously.

I've updated the article title. 

And a reminder to add a brief Author Bio (index.md file) and Headshot image (avatar file). Include these files in the authors folder within the GitHub repo via your forked repo, similar to the article files.

Let me know as soon as you're done, or ping me on Slack if you require assistance.

2021-04-12 11:18 UTC, OMONDIELLY commented
Hi... actually this is my third article, so am not sure why my author folder is not showing.
I'll update it though.

2021-04-12 11:31 UTC, collins-a commented
But do be keen with the changes you make on the article. eg. there are a couple of commits that have affected the flow of the article quite a bit. I've copied and pasted an example of a paragraph.

"What is IoT
<<<<<<< HEAD <<<<<<< HEAD Internet of Things (IoT) is a network of physical objects or devices – “things” – that are embedded with sensors, software, and other technologies for the purpose exchanging data among the devices on the internet to help organizations solve problems. For example, IoT solutions provide flexibility of workforce as employees can work remotely with connected devices, thus organizations incur little operational costs that relate to employee management. "

See the "<<<<<<< HEAD <<<<<<< HEAD" for instance. I'll rectify the ones I come across, but I suggest that you go through the article and get rid of duplicated sentences, paragraphs, and any elements that aren't meant to be present. Then ping me when done so that I may complete my review

2021-04-12 11:36 UTC, OMONDIELLY commented
> But do be keen with the changes you make on the article. eg. there are a couple of commits that have affected the flow of the article quite a bit. I've copied and pasted an example of a paragraph.
> 
> "What is IoT
> <<<<<<< HEAD <<<<<<< HEAD Internet of Things (IoT) is a network of physical objects or devices – “things” – that are embedded with sensors, software, and other technologies for the purpose exchanging data among the devices on the internet to help organizations solve problems. For example, IoT solutions provide flexibility of workforce as employees can work remotely with connected devices, thus organizations incur little operational costs that relate to employee management. "
> 
> See the "<<<<<<< HEAD <<<<<<< HEAD" for instance. I'll rectify the ones I come across, but I suggest that you go through the article and get rid of duplicated sentences, paragraphs, and any elements that aren't meant to be present. Then ping me when done so that I may complete my review

Sure.. Am working on it, I think there was a problem on my end I  ended up pushing the same changes twice, sorry for that.

2021-04-12 11:36 UTC, OMONDIELLY commented
> @OMONDIELLY I've just confirmed that it's true that you have an author bio. No need to update it. Must be an error with GitHub that's categorizing you as a first-time contributor.

So I should not make any changes?

2021-04-12 11:42 UTC, collins-a commented
With regards to the author bio, unless advised otherwise, don't make any changes. Since it already exists

2021-04-12 18:39 UTC, OMONDIELLY commented
> > But do be keen with the changes you make on the article. eg. there are a couple of commits that have affected the flow of the article quite a bit. I've copied and pasted an example of a paragraph.
> > "What is IoT
> > <<<<<<< HEAD <<<<<<< HEAD Internet of Things (IoT) is a network of physical objects or devices – “things” – that are embedded with sensors, software, and other technologies for the purpose exchanging data among the devices on the internet to help organizations solve problems. For example, IoT solutions provide flexibility of workforce as employees can work remotely with connected devices, thus organizations incur little operational costs that relate to employee management. "
> > See the "<<<<<<< HEAD <<<<<<< HEAD" for instance. I'll rectify the ones I come across, but I suggest that you go through the article and get rid of duplicated sentences, paragraphs, and any elements that aren't meant to be present. Then ping me when done so that I may complete my review
> 
> Sure.. Am working on it, I think there was a problem on my end I ended up pushing the same changes twice, sorry for that.

done making changes

2021-04-13 12:44 UTC, collins-a reviewed
@OMONDIELLY good job, the article is more polished now. However, I'll remind you to always do a Grammarly check before submission. I've made the edits for you this time. Also, you missed out on one change: AMQP. In comparison to MQTT, the section is still very lightweight. I'll still ask you to mention a bit more in terms of its usage cases, security, and/or other attributes of your choosing. Make it feel like it's more of a comparison with MQTT.

After that, we'll be ready for the final review.

2021-04-13 12:48 UTC, OMONDIELLY commented
> @OMONDIELLY good job, the article is more polished now. However, I'll remind you to always do a Grammarly check before submission. I've made the edits for you this time. Also, you missed out on one change: AMQP. In comparison to MQTT, the section is still very lightweight. I'll still ask you to mention a bit more in terms of its usage cases, security, and/or other attributes of your choosing. Make it feel like it's more of a comparison with MQTT.
> 
> After that, we'll be ready for the final review


Am working on the changes

2021-04-13 15:10 UTC, OMONDIELLY commented
Done with the changes

2021-04-14 11:14 UTC, collins-a commented
@OMONDIELLY I can see you have deleted your index.md file. Ping me when it's available and done with the changes.

2021-04-14 11:24 UTC, OMONDIELLY commented
> @OMONDIELLY I can see you have deleted your index.md file. Ping me when it's available and done with the changes.


Uploaded. Sorry about that , I had problems with my machine.

2021-04-14 11:36 UTC, OMONDIELLY commented
I have made the changes requested you requested yesterday in the last commit . Kindly review.

2021-04-15 17:52 UTC, collins-a approved these changes
@OMONDIELLY I'm satisfied with the changes. Again, always remember to carry out Grammarly checks on your articles before submission and after making any changes.

2021-04-15 18:01 UTC, OMONDIELLY commented
> @OMONDIELLY I'm satisfied with the changes. Again, always remember to carry out Grammarly checks on your articles before submission and after making any changes.

Sure, I'll be doing so

2021-04-21 23:47 UTC, hectorkambow commented
plagiarism check done

2021-04-28 14:29 UTC, merged