Getting started with Node.js Paypal checkout integration
section-engineering-education/engineering-education pull request #1990
Opened 2021-04-08 03:56 UTC by okeloviolet

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1962

2021-04-28 05:40 UTC, paulodhiambo commented on articles/nodejs-paypal-checkout/index.md
> +![Paypal create a new app](/pay/paypal-create-app.png)
Add the correct image path i.e ![Paypal create a new app](/pay/paypal-create-app.png) should be ![Paypal create a new app](/engineering-education/nodejs-paypal-checkout/paypal-create-app.png)

2021-04-28 05:41 UTC, paulodhiambo commented on articles/nodejs-paypal-checkout/index.md
> +Now that you have learned how to integrate Paypal checkout into a Node.js application, add a success and error page to the application we created. The full source for the application can be downloade
The link to the full source code is missing.

2021-04-28 05:42 UTC, paulodhiambo requested changes
@okeloviolet amazing article. Review the requested changes and ping me when done.

2021-04-28 05:49 UTC, okeloviolet commented
@paulodhiambo I have made the requested changes.

2021-04-28 06:19 UTC, paulodhiambo commented
@okeloviolet amazing article. @hectorkambow you can give it a final review.

2021-04-29 16:15 UTC, hectorkambow commented
plagiarism check done

2021-05-03 16:23 UTC, hectorkambow commented
👍  nicely done @okeloviolet 
I made some minor edits for flow - please review 👍 

cc @paulodhiambo

2021-05-03 16:23 UTC, merged