Creating a Simple Real-Time Chat App using React and Socket.io with E2E Encryption
section-engineering-education/engineering-education pull request #2020
Opened 2021-04-12 11:32 UTC by ephnjor2021

…2E Encryption

Article uploaded

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-04-12 11:41 UTC, ephnjor2021 commented
This solves #1749

2021-04-12 15:59 UTC, zolomohan commented
thanks, @WanjaMIKE. will review it tonight.

2021-04-12 19:12 UTC, zolomohan requested changes

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Then, we code the file `dummyuser.js` as below:
Before you ask the reader to create a file and add the code below, give a brief one-line intro on what the file will contain and will be used for.
Then, you can explain it in detail.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +In this stage, we'll code the file `server.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next, we will create a file `/src/index.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next we create a file `/store/action/index.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Then create a file `/store/reducer/index.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next, let's create the file `App.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +After initializing the socket, the two functions listed below will be called.
Technically, the function you pass to these event listeners will be called. Please mention the event listeners.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +In the above, we add routes and importing the components. We render home components and get `username` and `roomname` from the routes on the base URL.
it's not clear on what components you are importing.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next will be coding the file `/home/home.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next will be to code the file `/chat/chat.js` as shown below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +In the above code, we take the user's input and pass it to the action `process`, and then the data will be passed to `aes` function for encryption. Then the encrypted data is sent to `socket.on("chat
```suggestion
In the above code, we take the user's input and pass it to the action `process`, and then the data will be passed to the `aes` function for encryption. Then the encrypted data is sent to `socket.on("chat")`. Also, if the message is received, I'll be passed to the `aes` function for decryption.
```

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next will be to create the file `aes.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +In the above code, we import `aes256` from `aes` module and write a function where the incoming encrypted message is decrypted and encrypts the outgoing message. Note the welcome user message is not
```suggestion
In the above code, we import `aes256` from the `aes` module and write a function where the incoming encrypted message is decrypted and encrypts the outgoing message. Note the welcome user message is not to be encrypted.
```

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +In the above code, we import `aes256` from `aes` module and write a function where the incoming encrypted message is decrypted and encrypts the outgoing message. Note the welcome user message is not
You're writing two functions, not just one.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +Next will be creating the `/process/process.js` as below:
Brief intro about the file.

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +```
```suggestion
```json
```

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +The command will compile the whole project and run the React app; once this is complete, open the web browser and go to http://localhost:3000, type the user name and room name, also launch another ta
```suggestion
The command will compile the project and run the React app. Once this is complete, open the web browser and go to http://localhost:3000, type a user name and a room name. 

Launch another tab and access http://localhost:3000 and, type a different user name but type same room name and test the app.
```

2021-04-12 19:12 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +
```suggestion
In general, the app demonstrated above is quite simple and does not have many features a modern chat app would have. However, the idea, the code behind the app, and end-to-end encryption can be used to implement a real chat app.

```

2021-04-13 16:43 UTC, zolomohan commented
@ephnjor2021 Please go through the suggestions and ping me when you are done.

2021-04-14 15:29 UTC, ephnjor2021 commented
@zolomohan The requested changes have been made. 
Thank you

2021-04-17 07:07 UTC, zolomohan requested changes
I noticed that most of the code snippets are long but none of them have comments to explain the code. Please add comments in all the code snippets to explain each statement.

2021-04-17 07:07 UTC, zolomohan commented on articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
> +```
Please provide a brief intro about these files and provide links to the concept of action and reducers.

2021-04-19 04:46 UTC, zolomohan commented
@ephnjor2021 Please go through the suggestions and ping me when you are done.

2021-04-19 07:27 UTC, ephnjor2021 commented
@zolomohan The requested changes have been made.
Thank you.

2021-04-22 00:24 UTC, hectorkambow commented
👋 Good afternoon - upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


@ephnjor2021 

[Creating a Simple Real-Time Chat App using React and Socket.io with E2E Encryption #2020.pdf](https://github.com/section-engineering-education/engineering-education/files/6354620/Creating.a.Simple.Real-Time.Chat.App.using.React.and.Socket.io.with.E2E.Encryption.2020.pdf)

2021-04-22 10:20 UTC, zolomohan commented
@ephnjor2021 Please go through the attached document and try to reduce the overlap. Ping me when you are done.

2021-04-22 21:02 UTC, ephnjor2021 commented
@zolomohan The article overlap has been done and plagiarism reduced as possible.
Thank you.

2021-04-25 20:16 UTC, zolomohan requested changes
Hi @ephnjor2021. Upon conducting a Tech Review, I noticed the frontend of the application threw a minor error in `chat/chat.scss`.

<img width="1048" alt="Screenshot 2021-04-26 at 1 37 47 AM" src="https://user-images.githubusercontent.com/45763204/116008239-14f2d900-a631-11eb-9a37-2e327b3f6630.png">

When I commented out the scrollbars mixin, the app worked perfectly. 
Please fix this error.

2021-04-26 05:55 UTC, ephnjor2021 commented
@zolomohan The minor issue with css has been fixed.
Thank you

2021-04-26 19:22 UTC, zolomohan approved these changes

2021-05-05 16:11 UTC, hectorkambow commented
OVerall good work @ephnjor2021 

please review my final edits as there were some issue and some parts that were difficult to read along. 

Please review to help avoid in future articles - also be sure to check our resources page for more tips.

cc @zolomohan

2021-05-05 16:11 UTC, merged

2021-05-07 19:06 UTC, ephnjor2021 commented
@hectorkambow Well noted. Thank you.