How To Auto-generate Admin Panels for Node.js with AdminBro
section-engineering-education/engineering-education pull request #2057
Opened 2021-04-14 18:50 UTC by KayveTech

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-04-14 18:55 UTC, WanjaMIKE commented on articles/nodejs-adminbro/index.md
> +AdminBro is an open-source package that adds an auto-generated admin interface to manage data in a single panel in Node.js applications during development. This adds the ability to find, monitor, and
Add a link to AdminBro

2021-04-14 18:56 UTC, WanjaMIKE commented on articles/nodejs-adminbro/index.md
> +#### Setting up the router middleware
Use only level three headings ```###```

2021-04-14 18:57 UTC, WanjaMIKE commented on articles/nodejs-adminbro/index.md
> +```
Could you explain the above code snippets.

2021-04-14 18:58 UTC, WanjaMIKE commented on articles/nodejs-adminbro/index.md
> +Admin panel is a useful tool in. Happy coding!
Conclusion is too brief. Add more information .

Generally, add more infor to this article to make it more detailed and informative. For now, it's to brief for a technical article. Thanks

2021-04-14 19:00 UTC, WanjaMIKE requested changes
Please check the above suggestions. Thanks

2021-04-16 11:07 UTC, KayveTech commented
Hey @WanjaMIKE it was initially a draft but I did implement the changes, kindly checkout and let me know of anything else needed.

2021-04-21 15:52 UTC, marienjus commented
Hi, did you check my changes @WanjaMIKE

2021-04-24 11:42 UTC, WanjaMIKE commented
@KayveTech why did you close this PR?

2021-04-24 11:57 UTC, KayveTech commented
Done requested the changes that you requested :+1:

2021-04-24 12:53 UTC, WanjaMIKE commented
Kindly, be patient. Am working on the PR?

2021-04-30 06:23 UTC, WanjaMIKE commented
Nice article. I have a lot about creating Admin panels in Node.js using Admin bro

2021-04-30 06:24 UTC, WanjaMIKE approved these changes

2021-05-03 17:02 UTC, hectorkambow commented
@KayveTech 👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on [plagiarism ](https://www.scribbr.com/category/plagiarism/)and what is considered as such.

cc @WanjaMIKE

2021-05-05 15:27 UTC, KayveTech commented
@hectorkambow no attached pdf?

2021-05-05 16:16 UTC, KayveTech commented
@hectorkambow, I have the pliagiarism fixed. :+1:

2021-05-05 21:06 UTC, hectorkambow commented
[2120420-dae06c4c0449fafaf46c-1620248741165.pdf](https://github.com/section-engineering-education/engineering-education/files/6430233/2120420-dae06c4c0449fafaf46c-1620248741165.pdf)

@KayveTech 

Sorry I forgot to attach the PDF

2021-05-05 21:10 UTC, KayveTech commented
@hectorkambow I did fix the pliagiarism with quetext :+1:

2021-05-06 09:35 UTC, WanjaMIKE commented
@KayveTech I noticed you changed your variables names. Did you update your repo?

`For the entire source code, check this [github repository](https://github.com/KayveTech/AdminBro-Express).`

2021-05-06 17:38 UTC, KayveTech commented
Was kinda confusing having pliagiarism from variables and keywords, updated :+1:

2021-05-11 00:02 UTC, merged

2021-05-14 08:45 UTC, KayveTech commented
@WanjaMIKE this was my first PR. It has the author details in it but the merged article I can't see. @hectorkambow is anything wrong about that?

2021-05-14 08:58 UTC, KayveTech commented
The author details named start with a capital letter, didn't know about that, kindly edit the merged PR @hectorkambow .

2021-05-14 08:59 UTC, WanjaMIKE commented
It's okay