Getting Started with deep neural systems in Matlab
section-engineering-education/engineering-education pull request #2063
Opened 2021-04-15 10:47 UTC by jumapaul

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1963

2021-04-24 15:53 UTC, paulodhiambo commented on articles/deep-neural-system-matlab/index.md
> +Neural networks form the base of deep learning and a subfield of machine learning where algorithms are inspired by the structure of the human brain. It takes in data train themselves to recognize the
Consider changing "Neural networks form the base of deep learning and a subfield of machine learning..." to "Neural networks form the base of deep learning, a subfield of machine learning..." . "It takes in data train themselves to recognize the pattern in this data..." to "It takes in data, train itself to recognize the pattern in this data..."

2021-04-24 15:57 UTC, paulodhiambo commented on articles/deep-neural-system-matlab/index.md
> +2. Matlab installed on your computer.
Consider adding links to Matlab download site. Reference a getting started article that is already published [here](https://www.section.io/engineering-education/getting-started-with-matlab/).

2021-04-24 15:58 UTC, paulodhiambo commented on articles/deep-neural-system-matlab/index.md
> +> Note that after locating the dataset folder, you can copy it to your working directory.
Provide a screenshot showing the full path

2021-04-24 16:01 UTC, paulodhiambo commented on articles/deep-neural-system-matlab/index.md
> +There are various parameters and if you want to learn all, check the documentation.
provide a link to documentation

2021-04-24 16:02 UTC, paulodhiambo requested changes
@jumapaul amazing tutorial. Revise the changes and ping me when done

2021-04-24 22:43 UTC, jumapaul commented
x-special/nautilus-clipboard
copy
file:///home/pauljuma/Documents/MATLAB/articles/image1.jpg
file:///home/pauljuma/Documents/MATLAB/articles/image2.jpg
file:///home/pauljuma/Documents/MATLAB/articles/image3.jpg
file:///home/pauljuma/Documents/MATLAB/articles/image4.jpg
file:///home/pauljuma/Documents/MATLAB/articles/image5.jpg
file:///home/pauljuma/Documents/MATLAB/articles/image6.jpg
file:///home/pauljuma/Documents/MATLAB/articles/image7.png
file:///home/pauljuma/Documents/MATLAB/articles/image8.png

2021-04-26 15:16 UTC, jumapaul commented
@paulodhiambo changes made

2021-04-26 17:56 UTC, hectorkambow commented
[Getting Started with deep neural systems in Matlab #2063.pdf](https://github.com/section-engineering-education/engineering-education/files/6379137/Getting.Started.with.deep.neural.systems.in.Matlab.2063.pdf)

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

@jumapaul

2021-04-30 20:11 UTC, paulodhiambo commented
@jumapaul amazing article. @hectorkambow you can it a final review.

2021-05-03 17:02 UTC, hectorkambow commented
plagiarism check done

2021-05-11 02:08 UTC, hectorkambow commented
@jumapaul Overall seems like a very helpful tutorial. 

Please go over my final edits closely. As I found this article really difficult to get through and some sentences were difficult to follow along. 

I had half a mind to close the PR - please be sure to only include fully polished article (ready to be published as is). 

As we do not have the resources to review and edit articles - next time we will simply close the PR. 👍  

thank you

cc @paulodhiambo please review the edits as well - as articles like this should not be pushed for final review 🚀  
thank you

2021-05-11 02:08 UTC, merged