How to Build a Speed Typing Game Using JavaScript
section-engineering-education/engineering-education pull request #2090
Opened 2021-04-18 14:23 UTC by CallmeMukty

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1937

2021-04-18 14:29 UTC, srishilesh requested changes
Hey @CallmeMukty,

Welcome to EngEd community!

Amazing article.

I have requested minor changes. Please let me know when they're done, we can move on to the tech review.

Also, rename `hero1` as `hero`

Thank you.

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +## Table of Contents
Start with `###` markdown header

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +* Additional Resources
Use `-` instead of `*`

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +* Javascript: The programming language used to add interactivity to a web page.
Use `-`

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```HTML
```suggestion
```html
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> + ```HTML
```suggestion
 ```html
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```HTML
```suggestion
```html
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```HTML
```suggestion
```html
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```CSS
```suggestion
```css
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```CSS
```suggestion
```css
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```Javascript
```suggestion
```js
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```Javascript
Make this changes for the subsequent code snippets

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +#### Conclusion
```suggestion
### Conclusion
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +#### Additional Resources
```suggestion
### Additional Resources
```

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```
Add code comments

2021-04-18 14:29 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +```
Do this for all the code snippets

2021-04-18 14:39 UTC, srishilesh requested changes
@CallmeMukty 

Few more suggestions added.

2021-04-18 14:39 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +### Why Learn Javasvript
```suggestion
### Why learn Javascript?
```

2021-04-18 14:39 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +Next thing we would work on is the `.quote-display`;
```suggestion
Next thing we would work on is the `.quote-display`:
```

2021-04-18 14:39 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +since it accepts a `function` and a second parameter specifying the number of times you want the `function` to run in milliseconds. So the `function` is going to run every second, but it has a slight
If possible, break down this para into smaller paras.

I believe you are explaining the code snippets, so you could use bulleted points as well

2021-04-18 14:39 UTC, srishilesh commented on articles/how-to-build-a-speedtyping-game-using-javascript/index.md
> +[Javascript JSON](https://www.w3schools.com/js/js_json.asp)
```suggestion
- [HTML Script Defer Attribute (w3schools)](https://www.w3schools.com/tags/att_script_defer.asp)
- [Javascript Async](https://www.w3schools.com/js/js_async.asp)
- [Javascript Promises](https://www.w3schools.com/js/js_promise.asp)
- [Javascript JSON](https://www.w3schools.com/js/js_json.asp)
```

2021-04-19 13:30 UTC, srishilesh commented
@CallmeMukty 

Are the requested changes done? Can I start the next round of review?

2021-04-19 17:22 UTC, CallmeMukty commented
> @CallmeMukty
> 
> Are the requested changes done? Can I start the next round of review?

Yes, requested changes have been done

2021-04-21 18:23 UTC, srishilesh approved these changes
Hey @CallmeMukty,

Thanks for making the requested changes.

Amazing article. Really liked the tutorial.

I have made some changes in formatting and flow. Make sure you go through all my commits carefully, to understand and improve on your future articles.

Moving this for the final review.

Thank you.

2021-04-30 15:40 UTC, hectorkambow commented
plagiarism check done

2021-05-18 16:33 UTC, hectorkambow commented
This article was a bit difficult to read at parts. @CallmeMukty 

I found myself changing every other "would" to "will" - the sentences were in the past tense when you were doing the action. 

The part before the conclusion had some parts that I did not understand - I tried to restructure the sentence. 

Overall great tutorial - but please go over the changes to avoid these grammatical issues in future articles. (to avoid PR closure.)
Also feel free to check out our resources page for more tips and tricks. 


cc @srishilesh please do the same as this article was a bit tough to read and should not be pushed for final review if not ready.

2021-05-18 16:34 UTC, hectorkambow commented
just need to preview and published - when repo changes are finalized

NOTE: Thank you - we are making some changes to the main repo now - and this is delaying a few article from being published as we want to implement the changes 1st - once these are done - we will publish this one asap. Thank you 🚀

2021-05-19 21:07 UTC, CallmeMukty commented
> This article was a bit difficult to read at parts. @CallmeMukty 
> 
> I found myself changing every other "would" to "will" - the sentences were in the past tense when you were doing the action. 
> 
> The part before the conclusion had some parts that I did not understand - I tried to restructure the sentence. 
> 
> Overall great tutorial - but please go over the changes to avoid these grammatical issues in future articles. (to avoid PR closure.)
> Also feel free to check out our resources page for more tips and tricks. 
> 
> 
> cc @srishilesh please do the same as this article was a bit tough to read and should not be pushed for final review if not ready.
> 

So sorry for the inconvenience...I will be sure to take note of the corrections for the future. Thank you ♥️

2021-05-20 00:20 UTC, hectorkambow commented
https://www.section.io/engineering-education/how-to-build-a-speedtyping-game-using-javascript/

Published

2021-05-20 00:20 UTC, closed without merging