Getting Started With Node.js Timers Tutorial: Everything you need to know
section-engineering-education/engineering-education pull request #2094
Opened 2021-04-19 06:03 UTC by owinowendy

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-05-07 14:05 UTC, srishilesh requested changes
Hey @owinowendy,

Great article.

I've suggested few changes. Please let me know when it's done, we can move on to the tech review.

Thank you.

2021-05-07 19:12 UTC, hectorkambow commented
plagiarism check done

2021-05-12 13:11 UTC, srishilesh commented
@owinowendy 

I'm so sorry.

Due to certain personal emergencies, I was not able to review them.

So, I'm assigning it to @cyberShaw . He'll continue the review from here.

Thank you.

2021-05-12 15:34 UTC, cyberShaw commented
I'll do the review by today, @owinowendy!

2021-05-15 19:42 UTC, cyberShaw requested changes
Great article, @owinowendy!
Please make the suggested changes and we can move to final review.

2021-05-15 19:42 UTC, cyberShaw commented on articles/nodejs-timers/index.md
> +While executing this method, you're likely to encounter an error as seen below, otherwise, skip this part:
Please do explain why this error is likely to be encountered in a few lines.
And please also explain why the fix you suggested works that way. Readers would get a deeper understanding of why `setImmediate()` breaks and throws an error in some cases.

2021-05-16 16:01 UTC, cyberShaw commented
This article is ready for final review. Great job, @owinowendy 

cc: @hectorkambow 🚀

2021-05-16 16:01 UTC, cyberShaw approved these changes

2021-05-19 16:03 UTC, hectorkambow commented
@owinowendy 

just need to preview and published - when repo changes are finalized

NOTE: Thank you - we are making some changes to the main repo atm - and this is delaying a few article from being published as we want to implement the changes 1st - once these are done - we will publish this one asap. Thank you 🚀

2021-05-20 17:54 UTC, hectorkambow commented
https://www.section.io/engineering-education/nodejs-timers/

published

2021-05-20 17:54 UTC, closed without merging