Introduction to Python's Virtual Environments and Dependency Managers
section-engineering-education/engineering-education pull request #2099
Opened 2021-04-19 16:59 UTC by FREDERICO23

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1887

2021-04-19 17:02 UTC, geoffrey45 commented
@Manley12 This PR is a duplicate of another one that I was working on... which I had requested changes.

2021-04-22 09:07 UTC, geoffrey45 requested changes
@FREDERICO23 Have a look at the comments below. Please work on the suggestions and push the changes.

2021-04-22 19:07 UTC, FREDERICO23 commented on articles/introduction-to- virtual- environments-and-dependency-managers/index.md
> +* Rich with features.
Fixed the requested changes

2021-04-22 19:09 UTC, FREDERICO23 commented on articles/introduction-to- virtual- environments-and-dependency-managers/index.md
> +
Done

2021-04-24 09:08 UTC, FREDERICO23 commented
Made a few more changes for easy understanding by the reader.

2021-04-27 11:57 UTC, geoffrey45 approved these changes

2021-05-03 17:07 UTC, hectorkambow commented
plagiarism check done

2021-05-21 06:04 UTC, hectorkambow commented
just need to preview and published - when repo changes are finalized

NOTE: Thank you - we are making some changes to the main repo now - and this is delaying a few article from being published as we want to implement the changes 1st - once these are done - we will publish this one asap. Thank you 🚀

2021-05-22 16:33 UTC, FREDERICO23 commented
@hectorkambow @geoffrey45 

I did some stuff that broke this pull request. I had opened a new one #2364

2021-05-22 16:33 UTC, closed without merging

2021-05-22 17:04 UTC, geoffrey45 commented
@FREDERICO23 Your article was published yesterday. Here's the link https://www.section.io/engineering-education/introduction-to-virtual-environments-and-dependency-managers/

2021-05-23 22:30 UTC, hectorkambow commented
FYI please be sure to do a git pull on your forked repo before submitting your next PR to avoid any potential merge issues.

Thank you v much again for your patience as we worked the new repo file structure.