cross site scripting
section-engineering-education/engineering-education pull request #2104
Opened 2021-04-20 00:25 UTC by Pauline-Mwangi

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-04-20 00:28 UTC, Pauline-Mwangi commented
This fixes #1927

2021-04-21 04:17 UTC, lalith1403 commented
@Pauline-Mwangi Consider adding a headshot pic and short bio under a folder named after you, placed in the author's folder in the eng-ed repository. Check the author's folder for more details.

2021-04-25 12:12 UTC, lalith1403 requested changes
Well-written article. The initial part of the article is crisp and easy to understand. Well done. I have added a few modifications that would enhance the article further in terms of readability. Review them and make the changes accordingly.

2021-04-25 12:12 UTC, lalith1403 commented on articles/how-to-prevent-cross-site-scripting-in-node.js/index.md
> +Do not pass untrusted data into executable JavaScript functions such as `eval`. In the Node.js `eval` function, enable code injections. The `eval` function takes a string argument and interprets it a
This part is not clear. What data and what is the role of the function `eval`? What are code injections? Explain it in the proper order.

2021-04-25 12:12 UTC, lalith1403 commented on articles/how-to-prevent-cross-site-scripting-in-node.js/index.md
> +The only secure way to use if you insert untrusted data into the JavaScript code is inside a quoted (")data value. That is the proper context for inserting data into a JavaScript code. For example,
This sentence is complex. Break it down into simpler sentences.

2021-04-25 12:12 UTC, lalith1403 commented on articles/how-to-prevent-cross-site-scripting-in-node.js/index.md
> +Properly sanitized input ensures that users can submit only trusted data. It ensures that only expected data is inputted, i.e. (only authorizing input fields to accept parenthesis, numbers, and hyphe
What is sanitized input? Explain a bit more in this section.

2021-04-25 12:12 UTC, lalith1403 commented on articles/how-to-prevent-cross-site-scripting-in-node.js/index.md
> +Another way to prevent XSS is preventing cookies from browser JS scripts. This is achieved by setting the cookie `httpOnly` value to `true` in the below code.
Does this come under sanitizing input section, or is it a different one? It is not clear. Also, explain what happens when the cookie value is set to `True.`

2021-04-30 12:55 UTC, Pauline-Mwangi commented
Thank you @lalith1403 I made the changes you requested

2021-05-03 17:14 UTC, hectorkambow commented
plagiarism check done

2021-05-09 11:59 UTC, lalith1403 commented
The folder name is `how-to-prevent-cross-site-scripting-in-node.js`. I suggest you change it to `how-to-prevent-cross-site-scripting-in-node-js` to avoid errors in the URL.

2021-05-10 08:45 UTC, Pauline-Mwangi commented
@lalith1403 I made the final change

2021-05-21 06:04 UTC, hectorkambow commented
just need to preview and published - when repo changes are finalized

NOTE: Thank you - we are making some changes to the main repo now - and this is delaying a few article from being published as we want to implement the changes 1st - once these are done - we will publish this one asap. Thank you 🚀

2021-05-23 22:13 UTC, hectorkambow commented
published a couple days ago - had to create a new PR to prevent merge issues 👍 
https://www.section.io/engineering-education/how-to-prevent-cross-site-scripting-in-node-js/

2021-05-23 22:13 UTC, closed without merging

2021-05-23 22:23 UTC, hectorkambow commented
FYI please be sure to do a git pull on your forked repo before submitting your next PR to avoid any potential merge issues.

Thank you v much again for your patience as we worked the new repo file structure.