Building  documentation websites with Docusaurus version 2
section-engineering-education/engineering-education pull request #2118
Opened 2021-04-21 03:09 UTC by calebroHQ

Summary

In this tutorial, we have gone through how to set up Docusaurus version 2, how to customize and deploy. Docusaurus is a very simple and convenient way of deploying a documentation site or blog.

files added are index.md, hero.jpg and image1.jpg

2021-04-21 06:54 UTC, cyberShaw requested changes
Great article, @calebroHQ!
I've suggested a minor edit. Please make them and we can move to tech review.

Please add a GitHub link to the final working code

2021-04-21 21:38 UTC, calebroHQ commented
@cyberShaw hey, it's all done.

2021-05-03 04:27 UTC, cyberShaw requested changes
Hey @calebroHQ. After reading the article, I found that there isn't much of features of docusaurus discussed other than what's given in the official documentation. 
https://docusaurus.io/docs

Please discuss more features like documentation, versioning, react and markdown features. this article needs more improvement with more docusaurus features discussed. Please do the revisions and we can move to the next round of review.

2021-05-03 04:27 UTC, cyberShaw commented on articles/building-documentation-websites-with-docusaurus-v2/index.md
> +
Please explain the difference between `npm run start` and `npm run build` in this context.

2021-05-03 04:27 UTC, cyberShaw commented on articles/building-documentation-websites-with-docusaurus-v2/index.md
> +```css
Please include custom css and explain how the changes reflect on the page.
the below CSS is already pre-populated in the `custom.css` file

2021-05-03 14:37 UTC, hectorkambow commented
@calebroHQ 

I would agree with @cyberShaw  statement - as we always want to make sure we are creating and submitting original and unique content to the community - different than what is currently on other blog posts and more importantly we never want to repeat what can be found in the official docs. 👍 

We will close this PR - just to clear some room in the PR queue - but it can still be worked on and re-submitted when it is ready for another review. 🚀

2021-05-03 14:37 UTC, closed without merging