Node.js vs Python: Which is the best Technology for backend Development?
section-engineering-education/engineering-education pull request #2126
Opened 2021-04-21 14:23 UTC by Erastuskanyatta

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1907

2021-04-21 14:31 UTC, ahmadmardeni1 commented
LOL we assigned ourselves at the same time @collins-a

2021-04-21 14:33 UTC, collins-a commented
@ahmadmardeni1 no worries sir. Happens ever so often

2021-04-26 12:42 UTC, collins-a requested changes
@Erastuskanyatta good article. Handle the handful of changes requested and we're good to go. Cheers

2021-04-26 12:42 UTC, collins-a commented on articles/node.js-vs-python/index.md
> +Node.js is used in backend development. For frontend development, developers prefer JavaScript. This saves on resources since only one team with Node.js skills is hired. This feature of Node.js has,
Please expound on this point on saving resources and hiring one team as it's not that clear.

2021-04-26 12:42 UTC, collins-a commented on articles/node.js-vs-python/index.md
> +Python is a good language for web development as well as desktop development, but unlike Node.js it is never used in mobile app development.
I can argue out that, although to a much lesser extent, Python can be, and is used for mobile app development. Please restructure this statement to remove the word 'never'.

2021-04-26 12:42 UTC, collins-a commented on articles/node.js-vs-python/index.md
> +3. [Web2Py](https://loopback.io/doc/)
This link leads to Loopback.js as opposed to Web2Py

2021-04-26 12:42 UTC, collins-a commented on articles/node.js-vs-python/index.md
> +
Correct me if I'm wrong but, although less common, can't Python also carry out an asynchronous paradigm? Rephrase this statement to reflect such.

2021-04-26 12:42 UTC, collins-a commented on articles/node.js-vs-python/index.md
> +From the above comparison,  it is evident that one software may work on one project but may not work on another different project. Thus, when choosing between Node.js and  Python, it is important to
The last sentence seems unfinished. Is it a full stop that's missing? Or was a thought cut off?

Also, might be of greater value to add a reference or two, or links to assist readers to read further on similar concepts to the ones you have covered.

2021-04-26 12:46 UTC, collins-a commented
@Erastuskanyatta also ensure that your hero image is as close to 600*400 as possible. Hoping it is copyright free as well

2021-04-28 14:46 UTC, Erastuskanyatta commented
@collins-a  changes completed.  Please check out my last commit.

2021-05-03 12:38 UTC, collins-a approved these changes
@Erastuskanyatta changes approved. 

But do take note of the commits you make as you make changes. The force-push you did made the commits I made disappear. For example, I had to re-do processes such as adding front matter. 

Until next time, good luck.

2021-05-03 21:29 UTC, hectorkambow commented
plagiarism check done

2021-05-15 20:57 UTC, merged