Getting started with Node.js 15
section-engineering-education/engineering-education pull request #2134
Opened 2021-04-22 16:39 UTC by valerio140

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1999

2021-04-24 16:07 UTC, paulodhiambo commented
@valerio140 I can't an issue for this PR. please comment with the issue number so that I can link it to this PR.

2021-04-24 18:29 UTC, valerio140 commented
> @valerio140 I can't an issue for this PR. please comment with the issue number so that I can link it to this PR.

sorry, the issue number is #1999

2021-04-25 15:53 UTC, paulodhiambo commented on articles/introduction-to-node.js-15/index.md
> +So, you've heard of Node.js but don't know what it is or how it works in your development process. Maybe you've heard people praising Node.js and you are now wondering if you should learn it as well.
Consider removing this part, it's unnecessary.

2021-04-25 15:57 UTC, paulodhiambo commented on articles/introduction-to-node.js-15/index.md
> +Thanks to a slew of new features, NPM 7 is likely to be the biggest highlight of this update. NPM workspaces are the most important aspect since they mark the beginning of built-in support for buildi
Consider changing "... Lerna should find NPM's workspace implementation to be identical." to "... Lerna should find NPM's workspace implementation identical."

2021-04-25 16:02 UTC, paulodhiambo requested changes
@valerio140 amazing article. Review the changes and ping me when done. 
**Quick note** 
Make sure to be using active voice instead of passive voice when writing articles.

2021-04-25 21:01 UTC, valerio140 commented
@paulodhiambo I am done with the revision. Thanks

2021-05-01 04:37 UTC, paulodhiambo commented
@valerio140 i can see two index.md files. Why are they two? Please correct.

2021-05-01 05:53 UTC, valerio140 commented
> @valerio140 I can see two index.md files. Why are they two? Please correct.

@paulodhiambo Please use Update index.md. It was  mistake  while uploading. Thanks

2021-05-01 06:14 UTC, paulodhiambo commented
@valerio140 delete content/articles/why-you-should-use-wakanda-javascript-framework/index.md

2021-05-01 09:19 UTC, valerio140 commented
@paulodhiambo file deleted

2021-05-03 21:30 UTC, hectorkambow commented
plagiarism check done

2021-05-05 09:04 UTC, paulodhiambo commented on articles/introduction-to-node.js-15/index.md
> +Node.js 15's V8 engine has been updated to version 8.6 from version 8.4. V8 is the JavaScript engine that runs Node.js. Since V8, the features of the JavaScript language that are available to program
Explain this section. Its not clear.

2021-05-05 09:05 UTC, paulodhiambo requested changes
@valerio140 Revise the requested changes and ping me when done.

2021-05-12 17:25 UTC, paulodhiambo commented
@valerio140 amazing article. @hectorkambow you can give it a final review

2021-05-21 18:12 UTC, paulodhiambo commented
Hello :wave:
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory from the *articles* folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new *articles* folder inside *content*](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).

Ping me via Slack if you have any problems.

2021-05-25 19:52 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-25 23:04 UTC, closed without merging