how-to-set-up-user-authentication-from-scratch-rails-6
section-engineering-education/engineering-education pull request #2136
Opened 2021-04-23 13:01 UTC by Njunu-sk

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-05-03 21:51 UTC, hectorkambow commented
plagiarism check done

2021-05-05 13:32 UTC, zolomohan requested changes
Hi @Njunu-sk. 
It seems like the article lacks explanation when it comes to each action in the controllers. Make sure you provide a thorough explanation of all the actions in all the controllers since they are the core of this application.

Please ping me when you have updated them.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +Model View Controller is a design pattern that divides related programming logic making it easier to reason about.
Please provide a link to an article that explains more about the MVC architecture.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +The generator will create files but the most important is the controller file, `app/controllers/welcome_controller.rb`
```suggestion
The generator will create some files but the most important file is the controller file located in `app/controllers/welcome_controller.rb`
```

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +The generator also created a file in `app/views/welcome/index.html.erb`, by default Rails renders a view that corresponds to the name of a controller action.
```suggestion
The generator will also create a file in `app/views/welcome/` named `index.html.erb`. By default, Rails renders a view that corresponds to the name of a controller action.
```

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +A `model` is a `Ruby` class that hold data, we define it using a generator as follows:
```suggestion
A `model` is a `Ruby` class that serves as the template to a database table that holds data. We define it using a generator as follows:
```

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +`password_digest` is used to create password fields in rails and encryption is done by the [bcyrpt_gem](https://rubygems.org/gems/bcrypt). Include the gem in your Gemfile.
Make Include `bcrypt` gem into a separate point.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +   validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
Explain these.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +- Remember to run your migrations.
Talk briefly about what migrations are and why you need to do them.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +Test our app,
```suggestion
Let's test our app by running:
```

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +Test our model.
```suggestion
Let's test our model by running:
```

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +- Update `config/routes.rb`
Please add the reason on why you are updating the routes file here.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +`session` stores data for one request and used in another request. This controller is responsible for creating a new user and saving it to the database.
More explanation required for each action in the controller.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +- touch `app/controllers/registrations_controller.rb`
Say, Let's create the` registrations_controller.rb` by running the command `touch app/controllers/registrations_controller.rb`

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +- touch `app/controllers/registrations_controller.rb`
Make sure you do this for the other controllers too.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +`SessionsController` provides login functionality to an existing user, also logs out a user by deleting session data.
More explanation required on each action in this controller. Please go through each and every line in all the actions.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +
More explanation required for each action in the controller.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +- Note inheritance hierarchy in this class, `set_current_user` will be accessed with all controllers in the subdirectory.
Say something like, Since all the other controllers import the application controller, set_current_user will be accessible in all the controllers/

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +<% end %>
Explain what happens here. You can just explain about forms once here and ignore the other forms.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +- Let's test our app
Remove this. You're not testing the app in this step.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +We have to `configure our mailers` before we complete this action, for a user has to receive an email and reset the password.
Require more explanation about each action in the controller.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +end
Please explain this action.

2021-05-05 13:32 UTC, zolomohan commented on articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
> +You can always reach out via [Twitter](https://twitter.com/njunusimon)
```suggestion
You can always reach out to me via [Twitter](https://twitter.com/njunusimon)
```

2021-05-06 05:05 UTC, Njunu-sk commented
Thank you @zolomohan for the review
I've added the requested change
I hope to hear from you.

2021-05-25 19:54 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-06-03 13:22 UTC, zolomohan approved these changes

2021-06-03 14:29 UTC, zolomohan commented
Hi @Njunu-sk. Can you please update your fork to the updated folder structure. 
Please ping me via slack if you need assistance.

2021-06-03 19:22 UTC, closed without merging