Create index.md
section-engineering-education/engineering-education pull request #2156
Opened 2021-04-25 19:33 UTC by mercymeave

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #2047

2021-05-01 04:49 UTC, paulodhiambo commented on content/articles/push-notification-in-nodejs-using-service-worker/index.md
> +- Conclusion & Further Reading
Consider changing your table of content to:-

### Table of contents
- [Introduction](#introduction)
- [Goal](#goal)
- [Table of contents](#table-of-contents)
- [Prerequisites](#prerequisites)
- [Creating the Nodejs Application](#creating-the-nodejs-application)
  - [Init application](#init-application)
  - [Install dependencies](#install-dependencies)
- [Building the server side](#building-the-server-side)
  - [Import the dependencies](#import-the-dependencies)
  - [Generate VAPID Keys](#generate-vapid-keys)
  - [Setting the VAPID Keys with web push](#setting-the-vapid-keys-with-web-push)
  - [Creating the subscribe route](#creating-the-subscribe-route)
- [Coding the client side](#coding-the-client-side)
  - [Setting the static path](#setting-the-static-path)
  - [Creating the required files](#creating-the-required-files)
  - [Setting up the service worker](#setting-up-the-service-worker)
- [Run the server](#run-the-server)
- [Conclusion  and further reading](#conclusion--and-further-reading)

2021-05-01 04:51 UTC, paulodhiambo commented on content/articles/push-notification-in-nodejs-using-service-worker/index.md
> +- Code editor. I will use visual studio code
Provide download links to Node.js and Visual Studio code.

2021-05-01 04:53 UTC, paulodhiambo requested changes
@mercymeave amazing article. Review the requested changes then ping me when done.

2021-05-05 06:37 UTC, paulodhiambo commented
@mercymeave amazing topic on Node.js push notifications. @hectorkambow you can give it a final review.

2021-05-07 18:20 UTC, hectorkambow commented
plagiarism check done

2021-05-21 18:12 UTC, paulodhiambo commented
Hello :wave:
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory from the *articles* folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new *articles* folder inside *content*](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).

Ping me via Slack if you have any problems.

2021-05-25 19:56 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-26 03:40 UTC, mercymeave reviewed
Changes made

2021-05-27 16:14 UTC, hectorkambow commented
Great work - very nice article - super easy to follow along 🚀 

Please be sure to go over the small minor edits I made for format mostly - some minor for flow 

We are getting ready to increase our volume of articles published monthly - and the best way to go about this is - reviewing articles like this one - that were well written and easy to read. 

👍  

cc @paulodhiambo

2021-05-27 16:14 UTC, merged

2021-05-27 16:24 UTC, mercymeave commented
Thank you @hectorkambow and @paulodhiambo  for the review. I'll be sure to check the edits made.