webcam and ipcam in matlab
section-engineering-education/engineering-education pull request #2183
Opened 2021-04-28 19:46 UTC by queenterbruce063

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2030

2021-04-29 06:05 UTC, srishilesh requested changes
Hey @queenterbruce063,

Welcome to EngEd community!

Amazing article. I have suggested a few changes. Please let me know when you're done, we can move on to the tech review.

Thank you.

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +>>webcamlist
Remove these `>>`.

It would help the readers to copy-paste the codes, if needed

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +>>webcamlist
Do these changes for all the subsequent code snippets.

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +![install tab](/engineering-education/webcam-matlab/windows3_1.png)
```suggestion
- Log in to your math work account at the top right corner of the Matlab window.
![sign in tab](/engineering-education/webcam-matlab/signin.jpg)

- Click on the `adds on` drop-down arrow and select the `get hardware support package`.
![add_on menu](/engineering-education/webcam-matlab/adds_on.png)

- The hardware support package opens up and on the search tab, type `Matlab support package for USB webcam`  and search.
![support package](/engineering-education/webcam-matlab/webcam.png)

- After locating it, select the support package and click on the install button.
![install tab](/engineering-education/webcam-matlab/windows3_1.png)
```

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +-Using the same process above, we will locate the `Matlab support package for IP camera` and then install it.
```suggestion
- Using the same process above, we will locate the `Matlab support package for IP camera` and then install it.
```

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +### How to access external USB camera.
```suggestion
### How to access external USB camera?
```

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +### How to access external USB camera.
Don't use `.` for headings

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +Matlab is better software to use for live video streaming. This is because it has support packages that make this process easier. It also easier to use since the codes are not bulky and also easy to
If possible, add a `Further reading` section, which contains other reference links which might help the reader understand the concept better.

2021-04-29 06:05 UTC, srishilesh commented on articles/webcam-matlab/index.md
> +
Add a `Table of contents` section

2021-04-30 12:05 UTC, queenterbruce063 commented
@srishilesh requested changes made

2021-05-02 14:06 UTC, srishilesh approved these changes
Hey @queenterbruce063,

Thanks for making the changes.

Made a few changes to the flow and formatting. Make sure to go through my commits to understand and improve on your future articles.

Also, from the next time, make sure to modify hero image to 600x400 (I have done this change now)

Moving this article for the final review.

Thank you,

2021-05-07 18:23 UTC, hectorkambow commented
@queenterbruce063 
Im noticing this PR has multiple index files. I think this was by accident or a mistake - this may lead to a merge conflict. 
Can you please revise this PR - or create a new PR altogether to only include the files needed. 

cc @srishilesh

2021-05-08 02:11 UTC, srishilesh commented
@hectorkambow 

The issue is fixed. Removed the duplicate index file.

Ready for review and plagiarism check.

Thank you.

cc. @queenterbruce063

2021-05-22 16:49 UTC, srishilesh commented
Hello 👋 @queenterbruce063 
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.

In order to publish your article as soon as possible, please do the following:

- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory from the articles folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new articles folder inside content](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).

Ping me via Slack if you have any problems.

2021-05-25 18:09 UTC, queenterbruce063 commented
@srishilesh  I am done making the changes

2021-05-25 18:19 UTC, srishilesh commented
@queenterbruce063 

Thanks for making those changes. Everything's looking good.

Also, a minor change. 

Could you change the name of the directory to `/getting-started-with-webcam-and-ipcam-in-matlab`? since it will be reflected in the URL for your article. The current file directory name looks a little vague.

Thank you.

2021-05-25 19:57 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-26 00:10 UTC, hectorkambow commented
plagiarism check done

2021-05-27 22:54 UTC, hectorkambow commented
Great article - very informative and very easy to follow along 🚀 @queenterbruce063 

cc @srishilesh

2021-05-27 22:55 UTC, merged