Building a Calclator: A JavaScript project for beginners
section-engineering-education/engineering-education pull request #2200
Opened 2021-05-01 15:35 UTC by Nomzy-kush

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-01 15:38 UTC, WanjaMIKE commented
This fixes #2027

2021-05-03 13:52 UTC, adrianmurage commented
@WanjaMIKE 
I see you have 8 PRs assigned to you
Could you let me take this one?

2021-05-03 14:07 UTC, WanjaMIKE commented
@adrianmurage No, I have two PRs. This one is already in progress. Thanks

2021-05-04 17:51 UTC, WanjaMIKE commented on articles/building-a-calculator-a-javascript-project-for-beginners/index.md
> +The first thing you need to do is add all the different elements using “grid” to lay everything out nice and neat. You will then need to create a class naming it "calculator-grid". You will put all t
You already said the `first thing ... ` before. Replace it with another term

2021-05-04 17:55 UTC, WanjaMIKE commented on articles/building-a-calculator-a-javascript-project-for-beginners/index.md
> +#####updateDisplay Function
Only use level 3 headings ```###```

2021-05-04 18:39 UTC, WanjaMIKE commented on articles/building-a-calculator-a-javascript-project-for-beginners/index.md
> +On your calculator, you may notice that when you type a string of numbers, there are no commas to really make the numbers more definitive. Well, you can change that by using a helper function and cal
Try to use shorter sentences. They are usually more understandable

2021-05-07 07:27 UTC, WanjaMIKE commented
@Nomzy-kush make sure you format your article correctly. add a space after ```###```. Only use h3 headings in your article.

2021-05-07 07:28 UTC, WanjaMIKE requested changes
Please check the above comments

2021-05-07 20:31 UTC, hectorkambow commented
plagiarism check done

2021-05-15 21:48 UTC, WanjaMIKE approved these changes
A very detailed tutorial. Thumps Up. Take note of the changes I have made across the article. Thanks

2021-05-25 19:59 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-28 17:16 UTC, closed without merging