Getting started with Data Preprocessing in R
section-engineering-education/engineering-education pull request #2201
Opened 2021-05-01 16:42 UTC by Daniel695

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #1797

2021-05-05 13:49 UTC, zolomohan requested changes
Hi @Daniel695. 
I've reviewed the first half of the article. I've noticed the article requires some proper formatting. Please make sure the markdown file is clean by leaving appropriate spaces where necessary.

A lot of paragraphs and sentences are clumped together. Please Fix them and ping me. 
I'll review the second half when you are done.

2021-05-05 13:49 UTC, zolomohan commented on articles/data-preprocessing/index.md
> +#### Output
Instead of a heading, mark it as bold.

2021-05-05 13:49 UTC, zolomohan commented on articles/data-preprocessing/index.md
> +```
I think you can provide the dataset that you used to test for the readers to use. It'll be easier to follow along.

2021-05-05 13:49 UTC, zolomohan commented on articles/data-preprocessing/index.md
> +
Please provide an overview of the steps here. Just the headings. If possible, add links to the respective sections in the article.

2021-05-05 13:49 UTC, zolomohan commented on articles/data-preprocessing/index.md
> +Executing the code we obtain:
Please format this section properly with bullet points.

2021-05-07 20:31 UTC, hectorkambow commented
plagiarism check done

2021-05-19 12:00 UTC, zolomohan commented
Hi @Daniel695. Please update the article with the suggested changes.

2021-05-25 19:59 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-30 14:33 UTC, Daniel695 commented
@zolomohan suggested changes made

2021-06-03 13:43 UTC, zolomohan requested changes
@Daniel695 Please fix these before I proceed with the tech review.

2021-06-03 13:43 UTC, zolomohan commented on articles/data-preprocessing/index.md
> +2. Package packages('caTools') installed.
Instruct users on how to install this.

2021-06-03 13:43 UTC, zolomohan commented on articles/data-preprocessing/index.md
> +```
Please provide a link to a dataset so that readers can follow.

2021-06-09 12:56 UTC, zolomohan commented
@Daniel695 Please make these changes ASAP.

2021-06-09 13:20 UTC, Daniel695 commented
@zolomohan I have made the requested changes.

2021-06-13 15:35 UTC, zolomohan commented
Hi @Daniel695. Can you please update your branch to the updated directory structure? 

- Pull the `main` branch into your branch. 
- Move your article folder from `articles/` to `content/articles`.
- Create an author in `content/author` containing a bio. Take a look at how the other authors have done it.
- Commit and Push to your branch.

If you need further assistance, please ping me via slack.

2021-06-15 21:34 UTC, hectorkambow commented
@Daniel695 

Can you please provide us with an author page.

2021-06-16 21:08 UTC, Daniel695 commented
@zolomohan  I have added the author page.

2021-06-17 18:28 UTC, merged