A Vanilla Node.js REST API Without Frameworks such as Express.js
section-engineering-education/engineering-education pull request #2243
Opened 2021-05-06 14:55 UTC by Rose-stack

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-06 15:01 UTC, Rose-stack commented
Fixes #2029

2021-05-12 19:20 UTC, kayere requested changes
Hello @Rose-stack - Great article. Please check my suggestions before we move to tech review. I'd suggest you go through your article before submitting it. I have found a lot of typos which you would have noticed if you reviewed your article. Please go through the whole article so as to catch the typos that I might have missed.

2021-05-12 19:20 UTC, kayere commented on articles/a-raw-nodejs-rest-api-without-frameworks-such-as-expressjs/index.md
> +- `res.writeHead` to  set any response headers.
Remove extra space

2021-05-12 19:20 UTC, kayere commented on articles/a-raw-nodejs-rest-api-without-frameworks-such-as-expressjs/index.md
> +- `res.write()` to send the actual content for the.response.
Fix the typo at the end of the sentence.

2021-05-12 19:20 UTC, kayere commented on articles/a-raw-nodejs-rest-api-without-frameworks-such-as-expressjs/index.md
> +- `res.end()`  to end the response.
Remove the extra space.

2021-05-12 19:20 UTC, kayere commented on articles/a-raw-nodejs-rest-api-without-frameworks-such-as-expressjs/index.md
> +4. Call the `listen()` method and pass in the `PORT` variable. The add a `console.log()` message that will indicate the server is up and running.
Fix the typo at the beginning of the second sentence.

2021-05-12 19:20 UTC, kayere commented on articles/a-raw-nodejs-rest-api-without-frameworks-such-as-expressjs/index.md
> +- Open a separate tab in Postman and **SEND** a `GET` request to `http://localhost:5000/api/todos/:id`. Replace `:id` with and id of the todo you want to fetch.
```suggestion
- Open a separate tab in Postman and **SEND** a `GET` request to `http://localhost:5000/api/todos/:id`. Replace `:id` with an id of the todo you want to fetch.
```

2021-05-12 19:20 UTC, kayere commented on articles/a-raw-nodejs-rest-api-without-frameworks-such-as-expressjs/index.md
> +**/API/todos/:id PATCH**: This will update a to indicate that the task complete, i.e., `true` or `false`. You will see the effect on the postman response console. To test it:
Fix the typo at the beginning of the sentence.

2021-05-13 08:55 UTC, Rose-stack commented
Corrected @kayere

2021-05-17 19:55 UTC, kayere approved these changes
Hello @Rose-stack, great work making the changes. The article is now good to go.
@hectorkambow - please give this article a final review.

2021-05-25 20:07 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-26 00:12 UTC, hectorkambow commented
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


[A Vanilla Node.js REST API Without Frameworks such as Express.js #2243.pdf](https://github.com/section-engi@kayere eering-education/engineering-education/files/6543037/A.Vanilla.Node.js.REST.API.Without.Frameworks.such.as.Express.js.2243.pdf)

@Rose-stack 

cc @kayere

2021-05-26 00:25 UTC, Rose-stack commented
The plagiarism stood at 11% on my end 🤔

2021-05-26 00:28 UTC, Rose-stack commented
> I'll be running a final review on your PR when ready.
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
> Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
> Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [A Vanilla Node.js REST API Without Frameworks such as Express.js #2243.pdf](https://github.com/section-engi@kayere eering-education/engineering-education/files/6543037/A.Vanilla.Node.js.REST.API.Without.Frameworks.such.as.Express.js.2243.pdf)
> 
> @Rose-stack
> 
> cc @kayere

@hectorkambow, I can't find the attached PDF, please confirm this

2021-05-26 00:34 UTC, hectorkambow commented
[A Vanilla Node.js REST API Without Frameworks such as Express.js #2243.pdf](https://github.com/section-engineering-education/engineering-education/files/6543119/A.Vanilla.Node.js.REST.API.Without.Frameworks.such.as.Express.js.2243.pdf)

2021-05-26 00:39 UTC, hectorkambow commented
> The plagiarism stood at 11% on my end 🤔, @hectorkambow

Thank you for checking on your end (that is best practice) - most checkers are different so they may differ or look for different things.

But not sure why it would be so different on the same one? 🤔  

I think many of the red lines may have been code snippets as well. Not sure if those are boilerplate or template code. 

If possible we should change code snippets unless its a needed snippet.

2021-05-27 12:11 UTC, Rose-stack commented
Yeah, It could be due to the difference in the checkers  used

2021-05-27 12:19 UTC, Rose-stack commented
@hectorkambow I have updated the flags that trigger the higher %. 

I used the same checker as you, But I got a few additional matches pointing to the [review's githubmemory as the source](https://githubmemory.com/@kayere).  Check on your end.
![Node js](https://user-images.githubusercontent.com/80707573/119824714-df2a6400-befe-11eb-9b30-2ab16acd5c75.png)

2021-05-28 22:19 UTC, hectorkambow commented
Looks good now - thank you - sorry for the confusion not sure what the issue was.

2021-05-28 22:19 UTC, hectorkambow commented
plagiarism check done

2021-05-29 21:40 UTC, hectorkambow commented
published https://www.section.io/engineering-education/a-raw-nodejs-rest-api-without-frameworks-such-as-express/

2021-05-29 21:40 UTC, closed without merging