hilt android tutorial
section-engineering-education/engineering-education pull request #2250
Opened 2021-05-07 06:59 UTC by RaphaelNdonga

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-07 06:59 UTC, RaphaelNdonga commented
This fixes #2050

2021-05-07 07:07 UTC, WanjaMIKE commented on articles/hilt-android-tutorial/index.md
> +## Getting Started with Hilt
Could you use ```###``` rather than ```##```

2021-05-07 07:10 UTC, WanjaMIKE commented on articles/hilt-android-tutorial/index.md
> +## What is dependency injection?
Combine ```## What is dependency injection?``` section with the introduction

2021-05-07 07:12 UTC, WanjaMIKE commented on articles/hilt-android-tutorial/index.md
> +This gives hilt access to the entire application. It creates a *dependency container* at the application level. Hilt can supply dependencies to any part of the app.
Replace `hilt` with `Hilt` across the article

2021-05-07 07:14 UTC, WanjaMIKE commented on articles/hilt-android-tutorial/index.md
> +## Part 4: Hilt and 3rd Party Libraries
Replace `3rd` with `third`

2021-05-07 07:15 UTC, WanjaMIKE requested changes
Nice article @RaphaelNdonga. Could you review the above comments

2021-05-07 07:49 UTC, RaphaelNdonga commented
@WanjaMIKE  I made the changes you requested

2021-05-15 22:59 UTC, WanjaMIKE approved these changes
Nice tutorial. Easy to follow and understand. Keep up!

2021-05-25 17:02 UTC, WanjaMIKE commented
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:

Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
Delete your article directory from the articles folders.
Do a git pull (take a look at the new structure of the repo after a git pull).
Upload your article files to the new articles folder inside content.
Ping me via Slack if you have any problems.```

2021-05-25 20:07 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-26 00:24 UTC, hectorkambow commented
plagiarism check done

2021-05-26 08:59 UTC, RaphaelNdonga commented
@hectorkambow @WanjaMIKE  did I perform the task correctly?

2021-05-31 17:03 UTC, hectorkambow commented
> @hectorkambow @WanjaMIKE did I perform the task correctly?

@RaphaelNdonga It seems to be in the correct structure I'll know for sure when I check it out 👍 

Thank you

2021-05-31 17:43 UTC, hectorkambow commented
great work gents 👍  Awesome tutorial - real informative and easy to follow along - keep up the great work 🚀

2021-05-31 17:43 UTC, merged