initial commit
section-engineering-education/engineering-education pull request #2262
Opened 2021-05-08 21:51 UTC by shosenwales

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [yes ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-09 04:01 UTC, shosenwales commented
This fixes #How to send SMS in Django using Twilio

2021-05-09 04:02 UTC, shosenwales commented
This fixes #2098

2021-05-09 04:04 UTC, shosenwales commented
Thanks @geoffrey45

2021-05-10 20:16 UTC, geoffrey45 requested changes
@shosenwales Thanks for submitting this amazing tutorial. It's straight to the point. 👏

However, there are some minor changes I've suggested for flow. Please see the comments attached below.

2021-05-10 20:16 UTC, geoffrey45 commented on articles/how-to-send-sms-in-django-using-twilio/index.md
> +On activating the environment, we can install Django using the following command:
Don't mix pronouns. Choose one and stick to it throughout your tutorial. Ie. Choose between `you` and `we` and use it throughout.

2021-05-10 20:16 UTC, geoffrey45 commented on articles/how-to-send-sms-in-django-using-twilio/index.md
> +    ]
Use the correct indentation here.

2021-05-10 20:16 UTC, geoffrey45 commented on articles/how-to-send-sms-in-django-using-twilio/index.md
> +
Write the second sentence as an instruction for flow. Ie. `Create a superuser by ...`

2021-05-11 14:52 UTC, shosenwales commented
Hi @geoffrey45  
I've fixed the listed issues. kindly go through

Thanks.

2021-05-21 15:09 UTC, geoffrey45 commented
Hello  @shosenwales   :wave:

As you know, we were working on a new structure for our EngEd Repo, which led to a slight slow down of article publishing. Everything is almost ready now.

In order to publish your article as soon as possible, please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory .ie. `how-to-send-sms-in-django-using-twilio` from the `articles` folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new *articles* folder inside *content*](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles) ie. `/content/articles`.

Ping me via Slack if you have any problems.

2021-05-21 16:57 UTC, geoffrey45 approved these changes

2021-05-25 20:08 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-26 00:23 UTC, hectorkambow commented
plagiarism check done

2021-05-31 21:25 UTC, hectorkambow commented
great work Gents @shosenwales 

awesome tutorial - very easy to follow along 👍 

cc @geoffrey45

2021-05-31 21:25 UTC, merged