Using ECS to deploy a docker app to AWS
section-engineering-education/engineering-education pull request #2278
Opened 2021-05-12 04:02 UTC by victorelvice

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-29 09:57 UTC, victorelvice commented
@srishilesh I have finished the article, kindly review.

2021-05-31 14:43 UTC, srishilesh requested changes
Hey @victorelvice,

Welcome to EngEd community!

Great article. Very informative and beginner friendly.

I've suggested minor changes, please let me know when it's done, we can move on to the tech review.

Thank you.

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +In this article, we will understand how to deploy a Docker-based application to Amazon Web pages using Elastic Container Service. Flask is a small python framework for building web applications.
Amazon Web pages? Isn't is Amazon Web Services?

Also, in the line `Flask is a small python framework`, remove `small`.

Explain a little more about Flask framework and how it is related to this article.

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +        app.run(debug=True)
Indent it to the left

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +Create a folder named  `templates` which contains the HTML files rendered on the webpage. In the folder, create a file named `inde.html` the add the snippets below.
index.html?

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +    </html>
Indent to the left

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +    </html>
Do this for all the code snippets

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +- Click on create the wait for the process to finish. If the procedure is successful. you should see a window as below.
Since these are sequential steps, use a numbered list instead of bulleted list

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +- Click `add` then scroll down to `create`.
Since these are sequential steps, use a numbered list instead of bulleted list

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +If you head back to the cluster page and clusk the created cluster, you should see the task status as below.
Since these are sequential steps, use a numbered list instead of bulleted list

2021-05-31 14:43 UTC, srishilesh commented on articles/using-ECS-to-deploy-a-docker-app-to-AWS/index.md
> +- You configurations should be as below before clicking the save button.
Since these are sequential steps, use a numbered list instead of bulleted list

2021-06-01 05:13 UTC, victorelvice commented
Hi @srishilesh ,

I did the changes you requested. 

Kindly Check them out.

Thank you!

2021-06-01 05:27 UTC, victorelvice commented
I also migrated the filed into the right folder.

2021-06-01 18:24 UTC, srishilesh requested changes
@victorelvice 

Thanks for making the changes.

I've suggested a few more changes. Please let me know when done, we can move on to the final review.

Please make note of all the suggestions - especially regarding the change in image path and directory name.

Thank you.

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +```py
```suggestion
```dockerfile
```

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +
You can also mention external link that details more about Dockers (something like a tutorial preferably)

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +4 Leave the remaining setting as default the click `Create repository`.
```suggestion
3. Enter the repository name. I call mine `test`.
4. Leave the remaining setting as default the click `Create repository`.
```

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +Next. we need to upload the docker image we created to ECR.
```suggestion
Next, we need to upload the docker image we created to ECR.
```

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +```
```suggestion
```bash
```

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +- [ Amazon Elastic Contaioner Service](https://docs.aws.amazon.com/ecs/index.html)
```suggestion
- [Amazon Elastic Container Service](https://docs.aws.amazon.com/ecs/index.html)
```

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +![App running locally](/engineering-education/using-ECS-to-deploy-a-docker-app-to-AWS/app-running.png)
Change `using-ECS-to-deploy-a-docker-app-to-AWS/` to `using-ecs-to-deploy-docker-app-to-aws/`.

Also, you have typed `aws` as `awws` in the directory name. Please rectify that.

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +![Docker Build](/engineering-education/using-ECS-to-deploy-a-docker-app-to-AWS/build-app.png)
Change `using-ECS-to-deploy-a-docker-app-to-AWS/` to `using-ecs-to-deploy-docker-app-to-aws/`.

Also, you have typed `aws` as `awws` in the directory name. Please rectify that.

2021-06-01 18:24 UTC, srishilesh commented on content/articles/using-ecs-to-deploy-docker-app-to-awws/index.md
> +![Docker Build](/engineering-education/using-ECS-to-deploy-a-docker-app-to-AWS/build-app.png)
Do this for all the images. And, make sure to rename the directory.

2021-06-02 05:01 UTC, victorelvice commented
@srishilesh, Thank your for the suggestions, I have rectified the issues. Kindly check them out.

2021-06-03 18:11 UTC, srishilesh commented
@victorelvice 

Your last commit `f5d071d` had many merge conflicts, where your files were replaced by 3 other articles. I tried revert those changes, but I couldn't.

Could you please revert back the changes to commit `ae0e00e`? If not, remove all the files in the current commit, and add your files again containing the latest changes.

Please ping me in case of any questions.

Thank you.

2021-06-03 23:05 UTC, victorelvice commented
Done @srishilesh. Check it out.

2021-06-05 17:05 UTC, srishilesh approved these changes
@victorelvice 

Great article.

Moving for the final review.

Thank you.

2021-06-05 17:10 UTC, srishilesh commented
@victorelvice 

Just one more thing.

Since you had merged the latest master into this branch, I would suggest you to have a look at the files changed (deleted ones), and add them back, without disturbing the current changes in your article.

Hope it's clear.

Ping me if any questions.

Thanks.

2021-06-07 00:06 UTC, hectorkambow commented
@victorelvice  

👋  Hello - Hector here from the EngEd program - I'll be giving your article a final review before it is published online. 

Just noticed that your PR has a merge conflict - it may have been when adding/deleting some files. 

(see image) 

You can check our FAQ on how to resolve a merge conflict. 

The easiest way is to create a new PR and only add the files needed for this articles to it. 

Hope that help - ping us if you have any more questions. Looking forward to reviewing your articles 🚀 

cc @srishilesh

2021-06-07 05:41 UTC, srishilesh commented
Closing this PR. Created a new PR #2507

2021-06-07 05:41 UTC, closed without merging