Applet programming in java
section-engineering-education/engineering-education pull request #2305
Opened 2021-05-15 11:02 UTC by Paul22691

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2011

2021-05-15 12:34 UTC, WanjaMIKE commented on content/articles/applet-programming-in-java/index.md
>  ### Prerequisites
Move this section after the introduction

2021-05-15 12:35 UTC, WanjaMIKE commented on content/articles/applet-programming-in-java/index.md
> +    Local applets-is a locally developed and stored applet. A local applet does not need to use an internet connection to be located simply because the directory is in the local system.
Remove extra space at beginning of the sentence

2021-05-15 12:36 UTC, WanjaMIKE commented on content/articles/applet-programming-in-java/index.md
> +### Conclusion
Add more content in the conclusion

2021-05-15 12:36 UTC, WanjaMIKE commented on content/articles/applet-programming-in-java/index.md
> +        }
Explain what the above code does

2021-05-15 12:37 UTC, WanjaMIKE commented on content/articles/applet-programming-in-java/index.md
> +```
what does the `paint()` function do. In short, explain the code above

2021-05-15 12:38 UTC, WanjaMIKE commented on content/articles/applet-programming-in-java/index.md
> +### Differences between an applet and a java stand alone application
Replace `java` with `Java` in the appropriate areas

2021-05-15 12:38 UTC, WanjaMIKE requested changes
Please review the above comments

2021-05-17 11:07 UTC, Paul22691 commented
Hello @WanjaMIKE 
changes requested resolved.

2021-05-25 17:02 UTC, WanjaMIKE commented
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:

Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
Delete your article directory from the articles folders.
Do a git pull (take a look at the new structure of the repo after a git pull).
Upload your article files to the new articles folder inside content.
Ping me via Slack if you have any problems.```

2021-05-25 20:12 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-27 13:02 UTC, Paul22691 commented
> As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
> In order to publish your article as soon as possible, please do the following:
> 
> Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
> Delete your article directory from the articles folders.
> Do a git pull (take a look at the new structure of the repo after a git pull).
> Upload your article files to the new articles folder inside content.
> Ping me via Slack if you have any problems.```



> As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
> In order to publish your article as soon as possible, please do the following:
> 
> Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
> Delete your article directory from the articles folders.
> Do a git pull (take a look at the new structure of the repo after a git pull).
> Upload your article files to the new articles folder inside content.
> Ping me via Slack if you have any problems.```


@WanjaMIKE already did. Thanks

2021-05-27 13:04 UTC, Paul22691 commented
> > As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
> > In order to publish your article as soon as possible, please do the following:
> > Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
> > Delete your article directory from the articles folders.
> > Do a git pull (take a look at the new structure of the repo after a git pull).
> > Upload your article files to the new articles folder inside content.
> > Ping me via Slack if you have any problems.```


@WanjaMIKE already did. Thanks

2021-05-28 22:30 UTC, hectorkambow commented
plagiarism check done

2021-06-07 13:12 UTC, WanjaMIKE approved these changes

2021-06-09 18:32 UTC, WanjaMIKE commented
@ahmadmardeni1 are you reviewing this order again? Am not in the loop

2021-06-09 18:36 UTC, ahmadmardeni1 commented
No no am doing the final review @WanjaMIKE 
cc @hectorkambow

2021-06-09 22:11 UTC, merged