minor updates
section-engineering-education/engineering-education pull request #2314
Opened 2021-05-17 05:53 UTC by owinowendy

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-18 15:33 UTC, paulodhiambo commented on articles/node-app-express-generator/index.md
> +
Add the output here

2021-06-18 15:33 UTC, paulodhiambo requested changes
@owinowendy amazing article. Add the missing output section.

2021-06-18 16:37 UTC, paulodhiambo commented
@owinowendy amazing article. @hectorkambow you can give it a final review.

2021-06-18 16:44 UTC, hectorkambow commented
@owinowendy question why was this PR closed on the 16th?

2021-06-18 16:45 UTC, hectorkambow commented
@paulodhiambo also - PRs need a plagiarism check before they can be ready for final.

2021-06-18 16:45 UTC, hectorkambow commented
@owinowendy FYI PRs can only be created (and submitted) once the articles are completed. 

Please refrain from creating a PR to close and then re-open. Thank you. 

Cc @paulodhiambo

2021-06-25 17:14 UTC, hectorkambow commented
@owinowendy 
What TOPIC form is this PR tied to???

2021-06-26 18:10 UTC, hectorkambow commented
plagiarism check done

2021-06-28 23:28 UTC, hectorkambow commented
@owinowendy 

Question just wanted to make sure that your tutorial does not overlap with this - it seems much of what is covered in your article may be published already??

https://www.section.io/engineering-education/express/

@paulodhiambo

2021-06-29 05:08 UTC, owinowendy commented
The express package is the framework that exposes functionalities you can use in your code
The express-generator package a utility that provides a command-line tool you can use to scaffold your project - ie create boilerplate folder structure, files and code.

As part of the boiler plate files is a package.json file defining the dependencies for your project - ie npm packages that you will need for your project. The express package is listed there. This is where my article falls in.

If you want to build your project from scratch without boilerplate files / folders, first npm init, then npm install --save express, this installs express locally to your app, the --save option adds express as a dependency in your package.json.

Bottom line, to use the express web framework, you don't have to install express-generator, but you must install express. And if you work on, say, 3 apps which use express, the easiest thing to do is to install express 3 times locally to each app. This is where the published article falls in.    

The difference between this article and the one already published lies in the use of `Express Generator`  which is not covered in the existing article.

2021-06-29 15:55 UTC, hectorkambow commented
@owinowendy 
Thank you - 👍 

Future article would benefit from that break down you provided me at the end - for a beginner audience - and it may be helpful to reference past articles if they talk about somewhat similar things 🚀

2021-06-29 15:56 UTC, merged