First commit
section-engineering-education/engineering-education pull request #2342
Opened 2021-05-20 02:27 UTC by destiny251

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-20 02:35 UTC, destiny251 commented
hello @zolomohan this is the new PR you told me to create

2021-05-20 05:36 UTC, zolomohan commented
Hi @destiny251. Please update the title of the PR with the title of the article.

2021-05-20 05:37 UTC, zolomohan commented
Duplicate of [#2158](https://github.com/section-engineering-education/engineering-education/pull/2158)

2021-05-20 06:03 UTC, destiny251 commented
Hi@zolomohan i have updated the title of the PR

2021-05-20 13:14 UTC, hectorkambow commented
@destiny251 If you could please be sure to do a git pull before re-submitting this article - it will make the merging process a lot smoother and quicker. 

@zolomohan  If you could assist with any questions - 

The main thing is that this old structure will create a merge conflict - all article NOW go in the new folder structure. Please take a look at the repo after a git pull 👍

2021-05-20 20:44 UTC, destiny251 commented
@hectorkambow I'm done with it I have pulled and push again and it shows everything is already up  to date

2021-05-21 20:49 UTC, zolomohan commented
> @destiny251 If you could please be sure to do a git pull before re-submitting this article - it will make the merging process a lot smoother and quicker.
> 
> @zolomohan If you could assist with any questions -
> 
> The main thing is that this old structure will create a merge conflict - all article NOW go in the new folder structure. Please take a look at the repo after a git pull 👍

sure thing @hectorkambow. I'll assist.

2021-05-25 20:12 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-30 08:14 UTC, zolomohan requested changes
@destiny251 Please fix these problems.

2021-05-30 08:14 UTC, zolomohan commented on content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/index.md
> +After that, you will code a “simple alert” for it to show it, the `alert(‘password copied to clipboard’)` function. With all these written down, the application can not yet generate random passwords
Why are you discussing the copy functionality before completing the generate password?
Please move this after the section where you explain the generate password function.

2021-05-30 08:14 UTC, zolomohan commented on content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/index.md
> +We are going to create a variable called `password`. This variable will store the value returned by the `generatePassword` function. The `generatePassword` function takes four arguments. Lastly, the
Please explain what the four arguments are.

2021-05-30 08:14 UTC, zolomohan commented on content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/index.md
> +Now let me explain the codes after passing the four arguments. You want the password to be lowercase if no option is checked. Inside the function, you will create a variable that will store an array
This paragraph is very long. Please break them into smaller paragraphs and fix the grammar. 
Refer to the edits I performed on the previous paragraphs.

2021-05-30 08:14 UTC, zolomohan commented on content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/index.md
> +};
Fix this code snippet.

2021-05-31 18:49 UTC, destiny251 commented on content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/index.md
> +};
@zolomohan  i have fixed the issues

2021-06-03 15:39 UTC, zolomohan approved these changes

2021-06-09 16:34 UTC, hectorkambow commented
@destiny251 overall great article - nice and easy to follow along. 
I did make some minor edit to grammar and flow. 

Fixed the image paths. 

Fixed the author md file as well. Please go over any changes made by your peer reviewers or myself to further improve future articles and help speed up the publishing process. 

cc @zolomohan please do the same to improve reviews. 

cc @ahmadmardeni1 - please do the same - notice the edits to the intro. Some minor format - 

some sentences - and the images. 👍

2021-06-09 16:35 UTC, hectorkambow commented
the images were not going to render via preview - because the PR was made before our patch . - but the image paths should be correct. changed it from jpg to png. 

The author file should be checked as well (during prelimanry review actually) - if the image is too large we can crop it. 

@ahmadmardeni1 

cc @zolomohan

2021-06-09 16:35 UTC, merged