Fundamentals of container security
section-engineering-education/engineering-education pull request #2367
Opened 2021-05-24 07:38 UTC by calebroHQ

In this article, we have gone through what containers are, what are the security risks associated with the container technology, and how best to mitigate these risks.
      
This fixes #2216

2021-05-25 20:14 UTC, hectorkambow commented
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

2021-05-25 20:47 UTC, calebroHQ commented
Thank you, @hectorkambow

2021-05-27 10:18 UTC, srishilesh requested changes
Hey @calebroHQ,

Great article.

I've suggested a few changes. Please let me know when it's done, we can move on to the final review.

Thank you.

2021-05-27 10:18 UTC, srishilesh commented on content/articles/fundamentals-of-container-security/index.md
> +3. Proper storage of secret keys and tokens- Secrets should be stored outside of container images and provided dynamically at runtime as needed. Most orchestrators provide a secret key management fea
```suggestion
3. Proper storage of secret keys and tokens - Secrets should be stored outside of container images and provided dynamically at runtime as needed. Most orchestrators provide a secret key management feature.
```

2021-05-27 10:18 UTC, srishilesh commented on content/articles/fundamentals-of-container-security/index.md
> +4. Unbounded administrative access- Administrators should use an access management model in which users are only granted the ability to perform the specific task on the specific hosts, containers, an
```suggestion
4. Unbounded administrative access - Administrators should use an access management model in which users are only granted the ability to perform the specific task on the specific hosts, containers, and images their job roles require i.e., the development team will only have access to containers used in development only.
```

2021-05-27 10:18 UTC, srishilesh commented on content/articles/fundamentals-of-container-security/index.md
> +
Add links to other Section articles related to Docker and Container.

2021-05-27 23:09 UTC, calebroHQ commented
@srishilesh, I made the changes as suggested.

2021-05-28 23:24 UTC, hectorkambow commented
[Fundamentals of container security #2367.pdf](https://github.com/section-engineering-education/engineering-education/files/6563670/Fundamentals.of.container.security.2367.pdf)

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

@calebroHQ

2021-05-29 07:05 UTC, srishilesh commented
@calebroHQ 

The plagiarism score shows 26%

Please add appropriate references, and rephrase sentences to avoid higher plagiarism scores. Let me when it's done.

2021-05-31 02:14 UTC, calebroHQ commented
hi @srishilesh, I have done the necessary revisions.

2021-06-02 18:48 UTC, srishilesh commented
@hectorkambow 

Could you perform a plagiarism check again? Just to ensure if it's below the expected score.

Thank you.

2021-06-06 18:42 UTC, srishilesh commented
@calebroHQ 

I did a quick plagiarism check by myself, and found it is 3%, which is accepted. Let me start the review tomorrow.

2021-06-07 14:51 UTC, calebroHQ commented
@srishilesh, thank you

2021-06-07 16:24 UTC, srishilesh approved these changes
@calebroHQ 

Thanks for making the changes.

Moving for the final review.

Thank you.

2021-06-09 19:52 UTC, calebroHQ commented
@srishilesh, thank you.

2021-06-15 22:38 UTC, hectorkambow commented
good work gents @calebroHQ 

cc @srishilesh 

Please (if you both) could go over my final edits as well - as there were some sentences were a bit difficult to understand so I changed them - want to make sure I did not change the meaning of the sentences. Also see how we can avoid these errors for future articles 🚀

2021-06-15 22:38 UTC, merged