Beginners' Guide to Lottie Animations in Android Using Kotlin
section-engineering-education/engineering-education pull request #2430
Opened 2021-05-29 15:26 UTC by carolinemusyoka

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-05-29 15:27 UTC, carolinemusyoka commented
This fixes #2220

2021-05-30 14:23 UTC, BrianaNzivu requested changes
Hey @carolinemusyoka 👋 . 
This is such an amazing article! 👏  
It is well articulated, very few corrections, and very easy to understand. 
Good job!
Just a few corrections before we proceed to the grammar review.

Ping me when done.

2021-05-30 14:23 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +<iframe width="478" height="269" src="https://www.youtube.com/embed/Sw6gz27DLFs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
How about we have a gif instead of a youtube video?
Since it's a screen record you can just convert it to a gif and upload it.

2021-05-30 14:23 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +
Maybe you can also have the tutorial's APK . You can host it on Google drive and get a sharable link.

2021-05-30 14:23 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +
Bring the Github link here.

2021-05-30 14:23 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +Since the project is a bit wide, we shall only go through all the basics of Lottie animations on the app. You can check out the project on Github through [this](https://github.com/carolinemusyoka/Lot
Drop the Github link to the output.

2021-05-30 19:55 UTC, carolinemusyoka commented
Hey @BrianaNzivu 

I am done with the changes. I have used an app bundle instead of apk because it is a bit smaller. Let me know if there is anything else I should change. Thank you.

2021-06-03 12:31 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +### Prerequisites
Hey @carolinemusyoka . I don't think this is the only prerequisite needed. What about having Android Studio? I think someone also needs a little bit of experience in developing android applications in order to follow this article.

2021-06-03 12:39 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +Create a new android project on Android Studio
This step is not properly explained. Is it an Empty activity? Is it a Basic activity? 
Remember we write this article mostly assuming the reader has no prior experience.
So maybe you can have something like:
"Open Android Studio and select start a new Android Studio Project -> Empty Activity.
We will name the project FingerprintAuthentication. Select Finish and wait for the project to build." This is just an example you can come up with yours.😃

2021-06-03 12:56 UTC, BrianaNzivu commented on content/articles/beginner's-guide-to-lottie-animations-in-android-using-kotlin/index.md
> +Head over to Lottie's [website](www.lottiefiles.com) and choose the animations of your choice. Most of the animations are free, while others one has to pay to use them.  Download the .json file. In o
You can explain how the raw folder is created using arrows like this: This is an example explaining how to create a new fragment. "Select New → Fragment → Fragment(Blank)."

2021-06-03 14:18 UTC, BrianaNzivu requested changes
Hey @carolinemusyoka 👋. I have requested a few more changes. Also, I'd like to point out a few things:
- Section prefers h3 and above headings. In your next article be keen to us h3 and above i.e h4,h5 and h6.
- You are leaving large spaces in between statements. Try to leave spaces only when necessary.
- When you writing a tutorial we use steps, right? Therefore try and label the heading of these steps as Step one: something. It's easier to read and flow than just numbering the steps.
- Use the [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) suggested to through your work just to ensure that your work has minimal corrections.

Aside from that, I am done with the grammar review 😄 .
**Do take note of all of the changes I have made**. 
Make the few corrections requested then we can proceed to the Tech review 🚀.

2021-06-03 15:08 UTC, carolinemusyoka reviewed
Just reviewed the changes you made. Well noted

2021-06-03 15:10 UTC, carolinemusyoka reviewed
thanks for the review

2021-06-03 15:24 UTC, BrianaNzivu commented
> thanks for the review

You are welcome 😃 .

2021-06-05 11:37 UTC, BrianaNzivu commented
Hey @carolinemusyoka 👋 . Ping me once you are done with the corrections.

2021-06-05 11:46 UTC, carolinemusyoka commented
> Hey @carolinemusyoka 👋 . Ping me once you are done with the corrections.

will do

2021-06-06 12:15 UTC, carolinemusyoka commented
Hey @BrianaNzivu have a look at the few changes I made. Do let me know if there is something else I need to work on.

2021-06-08 21:27 UTC, BrianaNzivu commented
> Hey @BrianaNzivu have a look at the few changes I made. Do let me know if there is something else I need to work on. 

Sure thing.

2021-06-12 12:42 UTC, BrianaNzivu approved these changes
Hey @carolinemusyoka 👋 .
Great! I think that is much better now. 
I have made a small change. Take note of it. 
Moving to tech review. 🚀

2021-06-14 15:44 UTC, hectorkambow commented
plagiarism check done

2021-06-18 15:38 UTC, BrianaNzivu commented
Hey @carolinemusyoka .
Done with the tech review everything seems OK.
Just doing a final check then the article will be ready for final review in the next few minutes. 🚀

2021-06-18 18:57 UTC, BrianaNzivu commented
Hey @carolinemusyoka . Great job.
Take note of all the corrections I have made in your article 😄.
Also, in case of any question or clarification (currently or in the future) do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or via my personal email (briananzivu@gmail.com).
It has been a pleasure reading and reviewing this amazing article.  
Looking forward to seeing you contribute more to EngEd. 🚀 

Kind Regards.

2021-06-20 16:17 UTC, ahmadmardeni1 commented
Great work ladies!🎉  @carolinemusyoka @BrianaNzivu 
Few edits for format & flow, please go through them.

2021-06-20 16:17 UTC, merged