Postgresql vs Mysql
section-engineering-education/engineering-education pull request #2477
Opened 2021-06-02 21:32 UTC by amchilos01

this fixes #1980

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-03 07:02 UTC, lalith1403 commented
@zolomohan, I see you have plenty number of PRs assigned. I would recommend you wait till all your PRs are published before taking on new PRs. I will be reviewing this PR. Thank you :)

cc: @hectorkambow

2021-06-03 08:01 UTC, zolomohan commented
@lalith1403 Sure go ahead.

2021-06-09 16:54 UTC, lalith1403 commented
@amchilos01 I am having trouble editing the files submitted. Can you check for edit access rights? This isn't the case with all PRs. Probably something to do with this PR. 

cc: @hectorkambow

2021-06-09 19:27 UTC, amchilos01 commented
@lalith1403 I have allowed edits. Kindly let me know if you are now able to edit. apologies for the oversight.

2021-06-14 16:39 UTC, hectorkambow commented
plagiarism check done

2021-06-16 03:54 UTC, amchilos01 commented
Hey @lalith1403, did you manage to now access this PR?

2021-06-16 04:26 UTC, lalith1403 commented
> Hey @lalith1403, did you manage to now access this PR?

Yes. Thank you.

2021-06-16 04:40 UTC, lalith1403 commented
@amchilos01 Check the author folder. We will need a headshot image and a short bio to include on your profile page. I am supposing you are submitting the article for the first time since it says first-time contributor.

2021-06-16 04:53 UTC, lalith1403 requested changes
A few minor changes and we should be able to proceed with the final review.

2021-06-16 04:53 UTC, lalith1403 commented on content/articles/postgresql-vs-mysql/index.md
> +The performance of PostgreSQL was also improved by its index design, which facilitates a comparatively quicker execution of CRUD (Create Read Update Delete) activities.
Can you talk more about index design? A short overview of what it offers and why it was introduced?

2021-06-16 04:53 UTC, lalith1403 commented on content/articles/postgresql-vs-mysql/index.md
> +
A table summarizing the two databases on the basis of features discussed in the article would help the reader gain more insights at the end of the article.

2021-06-23 19:04 UTC, amchilos01 commented
@lalith1403 the recommended changes have been successfully committed.

2021-06-27 05:43 UTC, lalith1403 commented
I see you have repeated yourself in multiple instances. This repetition reduces the quality of the article. I strongly suggest you remove these repetitions and add more information if necessary. An example would be the sentence related to GDPR and EU laws. You use it in 2 sections, and the sentences are the same.

2021-06-30 11:12 UTC, ahmadmardeni1 commented
This PR has the old structure @hectorkambow

2021-06-30 11:31 UTC, ahmadmardeni1 commented
Please delete these two files: `.vs/engineering-education/v16/.suo` &  `.vs/slnx.sqlite` and why are they in your PR? 
Also, change the dimension of your personal-picture to 600X400 @amchilos01

2021-06-30 12:34 UTC, louisefindlay23 commented
Have deleted the .vs code files, @ahmadmardeni1.

2021-06-30 12:40 UTC, ahmadmardeni1 commented
Good work gentlemen @amchilos01 @lalith1403 
And congrats on your first article.
Please go through my changes.

Please make sure to check the author folder in the next reviews.

2021-06-30 12:40 UTC, merged