Files and Exception in Python
section-engineering-education/engineering-education pull request #2483
Opened 2021-06-03 16:09 UTC by duncandegwa

files and exception in python

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 

- [x]Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-08 11:19 UTC, srishilesh requested changes
@duncandegwa 

I've requested a few changes, please let me know when done.

Also, change the name of directory to `files-and-exceptions-in-python` (`exeptions` -> `exceptions`). And, remove extra new lines (especially in code snippets).

Thanks

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +
Could the introduction be more elaborative? 

Talk in-detail about Files and exceptions in Python, what their uses are, and talk about what the reader is going to learn, what are the key takeaways and outcomes.

Have a look at other Section articles.

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> + 
The file directory name must be `files-and-exceptions-in-python`

`exeptions` -> `exceptions`

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +Working with data in a text file, you need to read the file into memory first. To read a file, you must have a file with some data.
`To read a file, you must have a file with some data.`

This is not true. You can read an empty file as well.

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +```
Remove an extra new line, after each line.

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +```
Do this for all the code snippets

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +```python
```suggestion
```bash
```

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +```
Remove new line

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +### Handling the ZeroDivisionError exception
```suggestion
#### Handling the ZeroDivisionError exception
```

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +```python
```suggestion
```bash
```

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +### Handling the FileNotFoundError exception
```suggestion
#### Handling the FileNotFoundError exception
```

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +
Explain about `try-catch-except` blocks.

2021-06-08 11:19 UTC, srishilesh commented on content/articles/files-and-exeptions-in-python/index.md
> +
Add a `Further reading`/`References` section where you add external links that helps reader gain more knowledge on this topic

2021-06-10 14:45 UTC, duncandegwa commented
@srishilesh have done the suggested changes
Thank you

2021-06-11 18:46 UTC, srishilesh approved these changes
@duncandegwa 

Thanks for making the changes.

Moving for the final review. Please go through my commits to understand and improve on your future articles.

Thanks

2021-06-14 16:45 UTC, hectorkambow commented
plagiarism check done

2021-06-22 16:14 UTC, louisefindlay23 approved these changes
Congratulations, @duncandegwa. Your article has now been passed final review and been published.

cc - @srishilesh

2021-06-22 16:14 UTC, merged