Creating a Custom Data Transformer using Scikit-Learn
section-engineering-education/engineering-education pull request #2508
Opened 2021-06-07 05:36 UTC by Agusioma

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com)
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2374

2021-06-07 16:14 UTC, hectorkambow commented
@srishilesh Please let someone else review this article - I believe you have more than 2-3 articles in reivew 👍  

Thank you

2021-06-07 16:28 UTC, srishilesh commented
> @srishilesh Please let someone else review this article - I believe you have more than 2-3 articles in reivew 👍
> 
> Thank you

Sure.

2021-06-14 17:02 UTC, hectorkambow commented
plagiarism check done

2021-06-16 18:11 UTC, lalith1403 requested changes
Can you also include a Jupyter notebook with the code separated in cells. It will help the reader test and experiment with the concepts. Use Google Colab.

2021-06-17 14:38 UTC, Agusioma commented
@lalith1403 the link to the Google Colab has been added.

2021-06-17 17:33 UTC, lalith1403 requested changes
A good article explaining the basics of data transformers and data pipelines. I would suggest add more explanation regarding the thought process behind each line of code.

2021-06-17 17:33 UTC, lalith1403 commented on content/articles/custom-transformer/index.md
> +In machine learning, a data transformer is used to make a dataset fit for the training process. Scikit-Learn is a Python library containing methods that help us achieve our machine learning process f
Scikit learn enable quick experimentation to achieve quality results with a minimal amount of time spent on implementing data pipelines involving preprocessing, machine learning algorithms, evaluation and inference.

Change the second sentence.

2021-06-17 17:33 UTC, lalith1403 commented on content/articles/custom-transformer/index.md
> +imputer = SimpleImputer(strategy="median")
Explain the code line by line. What is median strategy?

2021-06-17 17:33 UTC, lalith1403 commented on content/articles/custom-transformer/index.md
> +imputer = SimpleImputer(strategy="median")
If the line is obvious, then there is no need to explain.

2021-06-17 17:33 UTC, lalith1403 commented on content/articles/custom-transformer/index.md
> +We will use a transformer for this called the `OrdinalEncoder`. `OrdinalEncoder` is chosen because it is more pipeline friendly.
What does ordinalencoder do?

2021-06-17 17:33 UTC, lalith1403 commented on content/articles/custom-transformer/index.md
> +### Our transformer
Data transformer. Transformers have different meanings under machine learning. It's better to be precise.

2021-06-17 17:33 UTC, lalith1403 commented on content/articles/custom-transformer/index.md
> +    def __init__(self, add_bedrooms_per_room = True):
Explain this class. How did you start to approach the logic? How did you break it into different methods? Explain the thought process step by step.

2021-06-19 10:17 UTC, Agusioma commented
@lalith1403 I fixed some changes. check

2021-06-24 18:03 UTC, Agusioma commented
@lalith1403

2021-06-28 14:59 UTC, ahmadmardeni1 commented
I can't access your [Google Colab notebook](https://drive.google.com/file/u/0/d/1DVIh0LhGOU0rwVU2bbZw_VmjiXWV-daM/edit).
It is asking for a password, please change the setting so that anyone with the link can access it.
Will merge when you do that. @Agusioma

2021-06-28 15:00 UTC, ahmadmardeni1 commented
I can't access your [Google Colab notebook](https://drive.google.com/file/u/0/d/1DVIh0LhGOU0rwVU2bbZw_VmjiXWV-daM/edit).
It is asking for a password, please change the settings so that anyone with the link can access it.
Will merge when you do that. @Agusioma

2021-06-28 19:49 UTC, ahmadmardeni1 commented
Good work gentlemen @Agusioma @lalith1403

2021-06-28 19:49 UTC, merged