Understanding Docker Networking
section-engineering-education/engineering-education pull request #2570
Opened 2021-06-10 13:28 UTC by Pauline-Mwangi

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-10 13:29 UTC, Pauline-Mwangi commented
This fixes #2396

2021-06-23 17:25 UTC, ahmadmardeni1 commented
Any update on this PR? @cyberShaw

2021-06-23 17:48 UTC, cyberShaw commented
> Any update on this PR? @cyberShaw 

I'll do the review shortly

2021-06-26 17:58 UTC, ahmadmardeni1 commented
Can you please review this one? @WanjaMIKE

2021-06-26 18:00 UTC, ahmadmardeni1 commented
Sorry for the waiting, we will review it Asap @Pauline-Mwangi

2021-06-27 06:33 UTC, WanjaMIKE commented on content/articles/understanding-docker-networking/index.md
> +Networking involves communication among processes. Networking in Docker is no different. Docker networking initiate communication between Docker containers and the outside world via the [host machine
Could you elaborate more on this sentence `Networking involves communication among processes`

2021-06-27 06:35 UTC, WanjaMIKE commented on content/articles/understanding-docker-networking/index.md
> +CNM is a [libnetwork](https://github.com/moby/libnetwork). Docker and the Docker community drive it. CNM introduces interoperation between networks. It conceptualizes the steps needed to provide netw
Could elaborate more on what `libnetwork` entails

2021-06-27 06:36 UTC, WanjaMIKE requested changes
This appears to be a `well-written` article. Could you go through the above minor suggestions. Thanks

2021-06-28 15:51 UTC, hectorkambow commented
[Understanding Docker Networking #2570.pdf](https://github.com/section-engineering-education/engineering-education/files/6727580/Understanding.Docker.Networking.2570.pdf)

@Pauline-Mwangi 
👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2021-06-29 04:30 UTC, WanjaMIKE commented
@Pauline-Mwangi also correct the plagiarism before we move forward. Thanks

2021-06-29 16:44 UTC, WanjaMIKE commented
@Pauline-Mwangi any updates?

2021-07-01 14:15 UTC, Pauline-Mwangi commented
@WanjaMIKE I made the changes you suggested and worked on plagiarism

2021-07-01 21:36 UTC, WanjaMIKE commented
Checking the changes ...

2021-07-04 16:02 UTC, WanjaMIKE approved these changes
In the next article, work on your flow. Avoid `"sudden"` sentences that distract the reader.

2021-07-07 12:20 UTC, ahmadmardeni1 commented
Good work ladies 👍🚀 @Pauline-Mwangi @WanjaMIKE

2021-07-07 12:20 UTC, merged