User input and while loops in python
section-engineering-education/engineering-education pull request #2649
Opened 2021-06-19 07:17 UTC by Bonimum

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
  
This fixes #2542

2021-06-22 21:42 UTC, hectorkambow commented
plagiarism check done

2021-07-03 12:18 UTC, Bonimum commented
hey @paulodhiambo  any updates?

2021-07-03 15:19 UTC, paulodhiambo requested changes
@Bonimum amazing article on loops and input. Review the requested changes and ping when done.

2021-07-03 15:19 UTC, paulodhiambo commented on content/articles/user-input-and-while-loops-in-python/index.md
> +The `input()` function halts your program and waits the user to key in some data. When Python receives the user's input, store it in the variable that you choose to work with.
Rewrite "The `input()` function halts your program and waits the user to key in some data." to "The `input()` function halts the execution of a program and waits for the user to key in some data."

2021-07-03 15:19 UTC, paulodhiambo commented on content/articles/user-input-and-while-loops-in-python/index.md
> +The `input()` function requires one argument, that is, the instruction you want the user to see. In this example, Python executes the first line and requests the user to enter his name. The program w
Rewrite "The `input()` function requires one argument" to "The `input()` function takes in one argument"

2021-07-03 15:19 UTC, paulodhiambo commented on content/articles/user-input-and-while-loops-in-python/index.md
> +Any text the user enters using the `input()` function Python interprets it as a string. If your work is to print the input, the `input()` function works very well. But if you use the input as a numbe
Rewrite "Any text the user enters using the `input()`..." to "Any text the user input using the `input()`..."

2021-07-03 15:19 UTC, paulodhiambo commented on content/articles/user-input-and-while-loops-in-python/index.md
> +When we enter 9000 in this example, Python interprets it as a string. The amount is then converted to an integer using the `int()` function. Now Python calculates the value of the interest.
Rewrite "When we enter 9000 in this example,..." to "When we input 9000 in this example,..."

2021-07-03 15:19 UTC, paulodhiambo commented on content/articles/user-input-and-while-loops-in-python/index.md
> +The *while* loop continues to execute if the value of *count* is equal to or less than 15.
Use back ticks for function names and keywords. Change "The *while* loop continues to execute if the value of *count* is equal to or less than 15." to "The `while` loop continues to execute if the value of `count` is equal to or less than 15."

2021-07-03 16:57 UTC, Bonimum commented
> @Bonimum amazing article on loops and input. Review the requested changes and ping when done.

@paulodhiambo  changes requested done

Thank you

2021-07-04 10:03 UTC, paulodhiambo commented
@Bonimum use [Hero](https://github.com/paulodhiambo/spring-amazon/blob/master/hero.png) as your hero image.

2021-07-04 10:53 UTC, Bonimum commented
> @Bonimum use [Hero](https://github.com/paulodhiambo/spring-amazon/blob/master/hero.png) as your hero image.

@paulodhiambo Have added hero image

2021-07-04 11:09 UTC, paulodhiambo commented
@Bonimum amazing article. @hectorkambow you can give it a final review.

2021-07-06 16:43 UTC, louisefindlay23 approved these changes
Great article, @Bonimum. Final review complete. 

Thanks @paulodhiambo for peer reviewing.

2021-07-06 16:44 UTC, merged