Wavelet Transform Based Denoising of images
section-engineering-education/engineering-education pull request #2656
Opened 2021-06-19 18:06 UTC by atienodorine3

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-23 16:50 UTC, ahmadmardeni1 commented
@srishilesh 👋
Please if you have time, review this one.

2021-06-23 16:54 UTC, srishilesh commented
>  @srishilesh 👋
> Please if you have time, review this one.

Sure, will review it.

2021-06-23 16:55 UTC, ahmadmardeni1 commented
Where is the topic-suggestion for this PR? I can't find it @atienodorine3

2021-06-23 17:02 UTC, atienodorine3 commented
#2384 @ahmadmardeni1

2021-06-23 18:08 UTC, srishilesh requested changes
@atienodorine3 

I've suggested a few changes. Please let me know when done.

Perform a grammar check - I found many typos and capitalization errors.

Also, do not write every sentence in a new line. Write them as paragraphs. When you move from one para to another, you start with a newline.

Make sure you explain the code briefly (with comments) - the variable names looks too confusing, since they're shorthand notations.

Thanks.

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +labels, we have various methods such as universal threshold, Bayes, SURE, MinMax, e.t.c.
Explain in-detail about:
- discrete wavelet transform(DWT)
- Grayscale images
- Binary images
- inverse discrete wavelet transform(IDWT) - add external references

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +- Type `wavelet analyzer` on the command prompt. We get a new window below.
Where do you find this tool? How to install it? Link?

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +`mey`, `dmey` are orthogonal wavelets and have non-compact support.
I'm not sure if these are short hands. This looks unclear. Please brief about this

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +Orthogonal wavelets are a single scaling function and the wavelet while biorthogonal generates a single scaling function and wavelet for
What is a `single scaling function`?

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +KEEPAPP: it is either 0 or 1. It is 0 when the approximation coefficients cannot be thresholded and 1 if they can be.
Put these in bulleted points. And, use ` `` ` for highlighting the keywords/variables

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +```
All these variable names looks too confusing - since they are shorthands. Please change the names, and elaborate about each.

2021-06-23 18:08 UTC, srishilesh commented on content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
> +```
Explain briefly

2021-06-26 18:20 UTC, atienodorine3 commented
@srishilesh requested changes made.

2021-06-26 19:07 UTC, hectorkambow commented
plagiarism check done

2021-07-03 14:01 UTC, srishilesh approved these changes
@atienodorine3 

Thanks for making the changes.

I've made some major changes to the formatting and flow. Make sure to go through them.

Moving for the final review.

Thanks.

2021-07-04 13:15 UTC, louisefindlay23 approved these changes
Final review complete. Congrats, @atienodorine3 and thanks, @srishilesh for peer reviewing.

2021-07-04 13:16 UTC, merged