UNDERSTANDING @OUTPUT AND EVENT-EMITTER IN ANGULAR
section-engineering-education/engineering-education pull request #2665
Opened 2021-06-20 15:17 UTC by odiwuoramos

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-23 16:58 UTC, ahmadmardeni1 commented
@adrianmurage 👋
Please if you have time, review this one.

2021-07-03 05:03 UTC, odiwuoramos commented
@ahmadmardeni1 , @louisefindlay23 , is the reviewer really free to look at my article?

2021-07-03 09:19 UTC, adrianmurage commented
> 
> 
> @ahmadmardeni1 , @louisefindlay23 , is @adrianmurage really free to look at my article?

@odiwuoramos thank you for your patience.
I'm looking into it in the next few hours

2021-07-04 10:54 UTC, adrianmurage requested changes
@odiwuoramos 
The app throws the following error when run:

``` bash
Error: src/app/music-details/music-details.component.ts:11:44 - error TS2558: Expected 0 type arguments, but got 1.

11   @Output() newMusician = new EventEmitter<string>();
```

Kindly take a look and @ me when you've fixed it

2021-07-04 10:54 UTC, adrianmurage commented on content/articles/angular-output-and-input-decorator/index.md
> +cd output-decorator
I do not see the relevance of this command as there is no directory named `output-decorator`
Consider revising it.

2021-07-05 17:55 UTC, odiwuoramos commented
Hi, @adrianmurage , I've  fixed the code, could you re-execute the code again,,,you many as well have a look at the screeshots.
Thanks.

2021-07-06 16:10 UTC, hectorkambow commented
plagiarism check done

2021-07-07 14:35 UTC, adrianmurage requested changes
@odiwuoramos 
Great work!

I was able to figure out what was causing the said error. 
Kindly make the addition to the article to prevent the readers from facing the same challenges.

2021-07-07 14:35 UTC, adrianmurage commented on content/articles/angular-output-and-input-decorator/index.md
> +> It's important to note that the `@Output` decorator uses `EventEmitter` to accomplish its task.
I've discovered that `EventEmitter` can be imported from multiple places. For instance, my import in the first review was:
```javascript
import { EventEmitter } from 'stream';
```
Which caused the error I was running into.

Therefore it's important to point out that `EventEmitter` should be imported from `@angular/core` like so:
```javascript
import { Component, Input, OnInit, Output, EventEmitter} from '@angular/core';
```

2021-07-07 15:47 UTC, odiwuoramos commented
@adrianmurage, I've updated the EventEmitter imports

2021-07-07 18:41 UTC, adrianmurage commented
@odiwuoramos 
Great work with this!
Looking forward to seeing more of your work

2021-07-08 13:45 UTC, ahmadmardeni1 commented
Good work 🚀 @odiwuoramos @adrianmurage 

Please work on the front matter, it should be complete before you put the "ready for final review" label.

2021-07-08 13:45 UTC, merged