Understanding polymorphism & abstract classes using C#
section-engineering-education/engineering-education pull request #2699
Opened 2021-06-23 12:30 UTC by mohamedgh16

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2520

2021-07-06 16:44 UTC, hectorkambow commented
@mohamedgh16 
👋 Good afternoon - Hector here.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

Not sure if its boilerplate code. 🤔 


[Understanding polymorphism & abstract classes using C# #2699.pdf](https://github.com/section-engineering-education/engineering-education/files/6771486/Understanding.polymorphism.abstract.classes.using.C.2699.pdf)

2021-07-07 18:08 UTC, zolomohan requested changes
@mohamedgh16 Please go through the below suggestion and we can move to the final review.

2021-07-07 18:08 UTC, zolomohan commented on content/articles/understanding-polymorphism-abstract-classes-using-c-/index.md
> +The following example will explain how we can define an abstract class to make a Payroll System Using Polymorphism.
It seems like you can provide a detailed explanation of what abstract classes & abstract methods are before jumping into the example.

2021-07-07 18:08 UTC, zolomohan commented
Also, see if you can reduce the plagiarism percentage.

2021-07-08 18:07 UTC, mohamedgh16 commented
@hectorkambow @zolomohan Done! 👏👀

2021-07-11 17:24 UTC, ahmadmardeni1 commented
Is this one ready for a final review? @zolomohan

2021-07-11 17:25 UTC, zolomohan commented
@ahmadmardeni1 Just have to add the front matter. Will update soon.

2021-07-12 16:48 UTC, zolomohan commented
@ahmadmardeni1 it's good to go.

2021-07-13 13:33 UTC, ahmadmardeni1 commented
Good work 🚀@mohamedgh16 @zolomohan

2021-07-13 13:34 UTC, merged