Working with Styled-components in React
section-engineering-education/engineering-education pull request #2706
Opened 2021-06-23 23:27 UTC by OMONDIELLY

This fixes #2465 

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-26 17:22 UTC, hectorkambow commented
@OMONDIELLY 
Good afternoon and- thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it.  🚀

2021-07-08 16:07 UTC, lalith1403 commented
@OMONDIELLY, can you check with the SVG files in the repository. Kindly check if they are required.

2021-07-13 16:11 UTC, hectorkambow commented
@OMONDIELLY 

cc @lalith1403  

Just wanted to get a status update on this PR - see if it was ready - as Im trying to clear our the queue.

2021-07-13 16:15 UTC, OMONDIELLY commented
> @OMONDIELLY
> 
> cc @lalith1403
> 
> Just wanted to get a status update on this PR - see if it was ready - as Im trying to clear our the queue.

Hello @hectorkambow , on my end I think ok. Unless there are more changes that will be requested by the Peer reviewer.

2021-07-13 16:32 UTC, lalith1403 commented
> @OMONDIELLY 
> 
> 
> 
> cc @lalith1403  
> 
> 
> 
> Just wanted to get a status update on this PR - see if it was ready - as Im trying to clear our the queue.

Will perform the tech review today. Thank you.

2021-07-13 16:58 UTC, lalith1403 requested changes
Fantastic article. A few minor changes and additions, and this should be good to go.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +If you have worked with React in developing web applications, you will agree with me that adding style to your Components is super cool when using the styled-components feature. In any case, you have
In any case, if you have not used React or styled-components, do not worry as this article is for you.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +React is a JavaScript library built and maintained by Facebook. React is purely Open-source.
Change the second sentence, purely open-source. Insert it in the first sentence as: React is an open-source JavaScript library built and maintained by Facebook.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +When faced with the need to build elegant and responsive user interfaces/UI components, React is the go-to tool.
Go-to framework

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +Each part of your application in React is built separately and reusably as a [Component](https://www.w3schools.com/react/react_components.asp) with the component-based feature. The components are the
This needs further refining. The concept behind React is modular components. You should consider explaining it in a way such that the concept of modularity is a consequence of the design principles of React.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +Components in React can be written as Functions or Classes, all of which accept defined inputs as [props](https://reactjs.org/docs/components-and-props.html) to determine what is rendered on the brow
Further refining is required. What is the utility of functional components and class based components. Define props formally.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +To create our second component, open the *Header.js* file that is in the components folder and add the following code:
Open the Header.js file in the components folder. Add the following code to the file.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +To get things started, let's open *App.js*  which will be the base of our application, and replace all the content in it with the code below to create an App function that will load our styled-compon
Introduce react-router library briefly.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +Import Landing from "./components/Landing" //This is to import the component created in the Landing.js file.
Check your import statements.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +import {BrowserRouter as Router, Switch, Route} from "react-router-dom";
Briefly explain why react-router-dom is needed.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +*Bravo if you reached up to this point!*
Add a screenshot of the expected output at this stage. Do the same for various stages previously that you seem fit.

2021-07-13 16:58 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +#### Styling the Content Area
Explain what you are trying to do with styling. For example, The image needs to be center aligned. Therefore, I am using the following CSS properties. Flex display helps me achieve this along with other advantages.

This is the template you should follow while explaining CSS files. Why are you using the properties that you are using. Explain that.

2021-07-19 21:33 UTC, ninjaginja commented
plagiarism check completed - all good
[2120420-5ba3b6ca379c9aeaaa7d-1626730383642.pdf](https://github.com/section-engineering-education/engineering-education/files/6844038/2120420-5ba3b6ca379c9aeaaa7d-1626730383642.pdf)

2021-07-20 07:05 UTC, OMONDIELLY commented
> Fantastic article. A few minor changes and additions, and this should be good to go.
Hello @lalith1403 , I have made the requested changes.

2021-07-21 17:06 UTC, lalith1403 requested changes
2 minor improvements and this should be good to go.

2021-07-21 17:06 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +You should have the landing page background image, disney+ icon image, logo-one, and logo-two within the folder.
Add links to the images that you have used. That would be better than me going to search for images on the site mentioned.

2021-07-21 17:06 UTC, lalith1403 commented on content/articles/working-with-styled-components-in-react/index.md
> +After building components/pages in your web application, you may need to expose and let your users navigate through them. To achieve this, you need a dedicated router. [React Router](https://www.free
Explain react-router intuitively. You may direct the reader to an in-depth article on react-router. Navigational components such as react-router-dom does not convey information

2021-07-21 17:07 UTC, lalith1403 commented
@OMONDIELLY Ping me once you are done with the changes.

2021-07-21 17:33 UTC, OMONDIELLY commented
> @OMONDIELLY Ping me once you are done with the changes.

Sure.. Thanks

2021-07-21 19:12 UTC, OMONDIELLY commented
> @OMONDIELLY Ping me once you are done with the changes.

@lalith1403 , Kindly check the updates

2021-07-27 22:45 UTC, hectorkambow commented
@OMONDIELLY 
Please be sure to go over my final edits to improve future articles and reviews. 

I believe you were interested in becoming a peer reviewer - these edits are things you will be trying to fix for other students or help them prevent these mistakes.

cc @lalith1403 please do the same - some edits to the front matter and through out the article

2021-07-27 22:45 UTC, merged

2021-07-28 05:00 UTC, OMONDIELLY commented
> @OMONDIELLY
> Please be sure to go over my final edits to improve future articles and reviews.
> 
> I believe you were interested in becoming a peer reviewer - these edits are things you will be trying to fix for other students or help them prevent these mistakes.
> 
> cc @lalith1403 please do the same - some edits to the front matter and through out the article

Following the edits keenly. Thanks.