Why and when you should use kubernetes
section-engineering-education/engineering-education pull request #2761
Opened 2021-06-28 20:12 UTC by erixbiz

Wrote a short article on Why-and-when-you-should-use-Kubernetes. The Key takeaways being:-

1. understand the overview of Kubernetes and container orchestration.
2. know the top reasons why a business should go for Kubernetes and the benefits it offers.
3. understand the instances when Kubernetes can be used or not used.

Below is the link to the images that I have used in my article 
Why-and-when-you-should-use-Kubernetes/image-name/container.jpg

My author's folder is erick-wekesa

2021-06-29 06:54 UTC, BrianaNzivu commented
Hey @mbaabuones 👋🏾. 
Please note that this is a duplicate of #2663.
You can proceed with the review regardless.
Have a good day.

2021-06-29 13:39 UTC, mbaabuones commented
> 
> 
> Hey @mbaabuones 👋🏾.
> Please note that this is a duplicate of #2663.
> You can proceed with the review regardless.
> Have a good day.

@BrianaNzivu Thank you for bringing this to my notice. I was not aware. Thanks for allowing me to work on it. Good day.

2021-06-29 15:33 UTC, mbaabuones requested changes
@erixbiz Thank you for submitting your article. I am pleased to welcome you to the Section Engineering Program. This article provides meaningful information regarding Kubernetes and why we should use them. It can be improved by modifying it based on the suggested changes. Please take note of the following points and ping me when you finish making the requested changes:
- Follow [this link](https://www.section.io/engineering-education/) to read recently published articles. Pay attention to the introduction of these articles, their structure, conclusion and overall quality.
- You made 10 commits. Subsequently, ensure you have one or few commits when making a pull request. Ensure you have made all adjustments to your article before uploading the index file. 
- Please upload a hero image for this article. This is a requirement every time you make a pull request. All hero images should be 600 by 400 pixels.
-  All markdown files for our program should have at least level three headers (###). If a section has level three headers (###), the sub-sections under this section will have level four headers (####).
- In my view, the similarities and differences between VM and containers should not be part of this article. Please focus on sections that directly correlate with the topic. 
- Remove any space immediately after a section topic.
- I suggest you use the following structure. Please add the missing parts accordingly.
** introduction section- Add the two introduction paragraphs you wrote in the topic suggestion form. No need for a header here. The next sections should have a header.
** An overview of Kubernetes and container orchestration- Give an overview of Kubernetes and container orchestration.
** Why businesses should use Kubernetes- In this section, list the key points using sub-sections. Give explanation in these sub-sections. Many online materials can give you adequate information on this. Gather enough information to add value to this article.
** When you should use Kubernetes- In this section, list the key points in bullet form (bold) and make explanation. You may also decide to list them using sub-sections. 
** When you shouldn't use Kubernetes- In this section, list the key points in bullet form (bold) and make explanation. You may also decide to list them using sub-sections. 
** Conclusion- Give a brief summary of your article and the concluding remarks.

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +# WHY AND WHEN SHOULD WE USE KUBERNETES?
Remove this header. Use the suggested structure.

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +
Avoid unnecessary spacing. One space after the end of a section is enough.

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +# WHY AND WHEN SHOULD WE USE KUBERNETES?
Dont capitalize every word. Please look at how the section headers have been written in the published articles.

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +Containers are a great development tool. It offers a good way to put together different components of the application and run. When you want to ensure that you have a quick and easy way of moving to
In this section, use the aforementioned structure guidelines.

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +2) When you don't have the time it requires to learn how to use Kubernetes because it has a steep learning curve. Kubernetes is a massive tool that requires sufficient time to learn.
Use the aforementioned structure guidelines.

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +![WHY AND WHEN SHOULD WE USE KUBERNETES?](/Why-and-when-you-should-use-Kubernetes/image-name/container.jpg)
You can place the image link in the section 'Overview of Kubernetes and container orchestration.'

2021-06-29 15:33 UTC, mbaabuones commented on content/articles/Why-and-when-you-should-use-Kubernetes/index.md
> +
Delete these two sections as advised in the above guidelines.

2021-07-12 13:05 UTC, mbaabuones commented
@erixbiz It is now two weeks since this article was reviewed. Please work on the suggested changes so that we can move to the next stage.

2021-07-12 21:17 UTC, erixbiz commented
> @erixbiz It is now two weeks since this article was reviewed. Please work on the suggested changes so that we can move to the next stage.

I really apologize for the delay. Just a quick one, should I create a new pull request?

2021-07-13 23:18 UTC, hectorkambow commented
> > @erixbiz It is now two weeks since this article was reviewed. Please work on the suggested changes so that we can move to the next stage.
> 
> I really apologize for the delay. Just a quick one, should I create a new pull request or do a Push to this branch?

You should be able to make the changes on this PR via your forked PR - but if that gets to messy - the easiest way would be to create a new PR. 

What ever is easiest for you

2021-07-14 00:45 UTC, erixbiz commented
> > > @erixbiz It is now two weeks since this article was reviewed. Please work on the suggested changes so that we can move to the next stage.
> > 
> > 
> > I really apologize for the delay. Just a quick one, should I create a new pull request or do a Push to this branch?
> 
> You should be able to make the changes on this PR via your forked PR - but if that gets to messy - the easiest way would be to create a new PR.
> 
> What ever is easiest for you

Thank you

2021-07-14 01:03 UTC, erixbiz commented
@mbaabuones I have done the corrections as requested. Thanks

2021-07-20 12:38 UTC, erixbiz commented
@mbaabuones I am done with the changes. Thanks

2021-07-20 15:43 UTC, ninjaginja commented
plagiarism check completed - all good
[2120420-c3082bc8d4e242e81d2f-1626795793541.pdf](https://github.com/section-engineering-education/engineering-education/files/6849619/2120420-c3082bc8d4e242e81d2f-1626795793541.pdf)

2021-07-22 17:28 UTC, mbaabuones approved these changes

2021-07-22 17:30 UTC, mbaabuones commented
> 
> 
> @mbaabuones I am done with the changes. Thanks

@erixbiz Thank you. Please note the changes I have made.

2021-07-22 17:36 UTC, mbaabuones approved these changes

2021-07-28 13:03 UTC, louisefindlay23 approved these changes
Final review complete, @erixbiz. Great article. Be sure to look at the minor changes I made to inform future articles. Folder names shouldn't have capital letters in them.

Thanks, @mbaabuones for peer reviewing.

2021-07-28 13:03 UTC, merged

2021-07-28 19:43 UTC, erixbiz commented
@louisefindlay23 Well noted with thanks.

@mbaabuones  it was great working with you on this article as well. Thanks.