Inversion of control principle
section-engineering-education/engineering-education pull request #2769
Opened 2021-06-29 17:54 UTC by Lamouresparus

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-06-29 17:55 UTC, Lamouresparus commented
This fixes #2230

2021-07-02 16:11 UTC, hectorkambow commented
@Lamouresparus 
Good afternoon and thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

2021-07-06 06:36 UTC, BrianaNzivu commented
Hello 👋🏾 @Lamouresparus .
Briana here.
I'll be conducting the review for your article.
I'd still like to apologize on behalf of the Section EngEd team for the delayed review due to the long queue of articles but I believe right now we are set to go.🚀

Looking foward to working with you.

Regards.

2021-07-06 07:56 UTC, Lamouresparus commented
Hi Briana,

Thank you. Looking forward to work with you too 😊.

Best regards.

On Tue, Jul 6, 2021, 07:36 Briana Nzivu ***@***.***> wrote:

> Hello 👋🏾 @Lamouresparus <https://github.com/Lamouresparus> .
> Briana here.
> I'll be conducting the review for your article.
> I'd still like to apologize on behalf of the Section EngEd team for the
> delayed review due to the long queue of articles but I believe right now we
> are set to go.🚀
>
> Looking foward to working with you.
>
> Regards.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/2769#issuecomment-874499835>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIJKG5PQ5J2IN3P3ZHW6TUTTWKQAFANCNFSM47QXDFEA>
> .
>

2021-07-07 04:36 UTC, BrianaNzivu commented
Hey @Lamouresparus .
I have notice that you do not have Author bio and we'd love to give you credit for your work. 
It's easy to create it. 
Under the author folder in the content folder, in your forked branch of course, 
Create a folder (preferably name it after your name) and inside it have an index.md with your details and an avatar.png with your photo.
You can refer to the author details in the main section repo to see how it's done.

2021-07-07 16:00 UTC, BrianaNzivu requested changes
Hey @Lamouresparus :wave: 
First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.
Good job on the article. It is a very interesting read.
Just a change I need you to make as we continue with the preliminary revisions:
- Each article in Section has its own structure on how it is written. For instance, your article is more of a how-to guide. Please check out this [document](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md) and try and structure your article according to this guide.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

2021-07-07 16:00 UTC, BrianaNzivu commented on content/articles/ioc_principle/index.md
> +Inversion of Control(IoC) is a software design principle. It helps to reverse control in object-oriented programming. Control here is any extra responsibility a class has besides its main responsibil
Have this as the introduction.

2021-07-07 16:00 UTC, BrianaNzivu commented on content/articles/ioc_principle/index.md
> +
Have a conclusion that summarizes what the article has covered.

2021-07-07 16:00 UTC, BrianaNzivu commented on content/articles/ioc_principle/index.md
> +### 1. Coupling
I think we can also have the advantages of this just like you have done in step three.

2021-07-07 16:00 UTC, BrianaNzivu commented on content/articles/ioc_principle/index.md
> +### 2. Abstraction
Have the advantages also.

2021-07-09 13:49 UTC, Lamouresparus commented
Hello Briana,
Thank you for the corrections. I am on it.

On Wed, Jul 7, 2021 at 5:00 PM Briana Nzivu ***@***.***>
wrote:

> *@BrianaNzivu* requested changes on this pull request.
>
> Hey @Lamouresparus <https://github.com/Lamouresparus> 👋
> First of all, welcome to Section - EngEd. 🎉
> We are happy to have you here.
> Good job on the article. It is a very interesting read.
> Just a change I need you to make as we continue with the preliminary
> revisions:
>
>    - Each article in Section has its own structure on how it is written.
>    For instance, your article is more of a how-to guide. Please check out this
>    document
>    <https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md>
>    and try and structure your article according to this guide.
>
> In case of any question or help needed please do not hesitate to ping me
> here 😄.
> Also, notify me when you are done.
>
> Regards.
> ------------------------------
>
> In content/articles/ioc_principle/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/2769#discussion_r665487164>
> :
>
> > +status: publish
>
> +published: true
>
> +url: /engineering-education/inversion_of_control_principle/
>
> +title: Inversion of control principle
>
> +description: Inversion of Control(IoC) is a software design principle used in object-oriented programming to reverse control and achieve loose coupling of classes. Coupling measures how closely connected software modules are to each other, while control refers to any other additional responsibility a class has apart from its primary responsibility. Remember the S in SOLID principles of object-oriented design? Let me help you: Singularity of Purpose—that is the objective of IoC. Loose coupling in software engineering is often a sign of testable, well-structured, maintainable, and readable software.
>
> +author: love-otudor
>
> +date: 2021-07-16T00:00:00-11:00
>
> +topics: [Languages]
>
> +excerpt_separator: <!--more-->
>
> +images:
>
> +
>
> +  - url: /engineering-education/inversion_of_control_principle/hero.jpeg
>
> +    alt: Inversion of control principle cover image
>
> +---
>
> +
>
> +Inversion of Control(IoC) is a software design principle. It helps to reverse control in object-oriented programming. Control here is any extra responsibility a class has besides its main responsibility. IoC passes the control of an object’s creation, the flow of an application, etc. to a container or framework.
>
>
> Have this as the introduction.
> ------------------------------
>
> In content/articles/ioc_principle/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/2769#discussion_r665490689>
> :
>
> > +Say we want to create a `CashmereLaundryBot`. What behaviors of `Wash` and `Dry` do we choose from? It is advised to wash cashmere by hand to avoid tears and snags, thus we would use the `HandWash` behavior. For drying, cashmere isn't suitable for `MachineDry`. This is because the heat could shrink or damage its follicles. The `Dry` behavior to use for a cashmere then is the `SunDry`. Let’s see how this looks like in code:
>
> +
>
> +```kotlin
>
> +class CashmereLaundryBot: LaundryBot{
>
> +   override val wash: Wash = HandWash
>
> +   override val dry: Dry = SunDry
>
> +
>
> +}
>
> +```
>
> +
>
> +See how the strategy pattern has made it easy to change the behavior of this class? Nice!
>
> +
>
> +
>
> +It's been a long article, but I sure hope this helped you as much as it did me.
>
> +Thank you!
>
> +
>
>
> Have a conclusion that summarizes what the article has covered.
> ------------------------------
>
> In content/articles/ioc_principle/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/2769#discussion_r665495000>
> :
>
> > +---
>
> +
>
> +Inversion of Control(IoC) is a software design principle. It helps to reverse control in object-oriented programming. Control here is any extra responsibility a class has besides its main responsibility. IoC passes the control of an object’s creation, the flow of an application, etc. to a container or framework.
>
> +
>
> +IoC inverts the control of creating and managing objects from the programmer to a container. This container manages the creation and lifecycle of objects in the application. IoC helps us create large systems by eradicating the responsibility of creating objects.
>
> +
>
> +Imagine this: suppose you have a bakery that specializes in making egg rolls. What is an egg roll without an egg? Right. So eggs are essential in the making of egg rolls. Why egg rolls you may ask? Well, you could call it plain nepotism. So how do we get a bakery that obeys the IoC principle? Well, rather than having a poultry farm and involving yourself with all the poultry-related tasks, you order the eggs and get them delivered to you. This time, you don't have to worry about the chicks and the eggs being healthy, or if you are using the right feed, and all. With this new design, you can focus on making egg rolls, which results in a more effective baking process. This is the big idea behind IoC: separating concerns.
>
> +
>
> +### Here are some of the benefits of using IoC:
>
> +* Easy to switch between different implementations of a particular class at runtime.
>
> +* It increases the modularity of the program.
>
> +* It manages an object’s lifecycle and configuration. Some objects can be singletons, while we can create others per request.
>
> +
>
> +Before we look at some code, here are some things you should have in mind:
>
> +
>
> +### 1. Coupling
>
>
> I think we can also have the advantages of this just like you have done in
> step three.
> ------------------------------
>
> In content/articles/ioc_principle/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/2769#discussion_r665495161>
> :
>
> > +IoC inverts the control of creating and managing objects from the programmer to a container. This container manages the creation and lifecycle of objects in the application. IoC helps us create large systems by eradicating the responsibility of creating objects.
>
> +
>
> +Imagine this: suppose you have a bakery that specializes in making egg rolls. What is an egg roll without an egg? Right. So eggs are essential in the making of egg rolls. Why egg rolls you may ask? Well, you could call it plain nepotism. So how do we get a bakery that obeys the IoC principle? Well, rather than having a poultry farm and involving yourself with all the poultry-related tasks, you order the eggs and get them delivered to you. This time, you don't have to worry about the chicks and the eggs being healthy, or if you are using the right feed, and all. With this new design, you can focus on making egg rolls, which results in a more effective baking process. This is the big idea behind IoC: separating concerns.
>
> +
>
> +### Here are some of the benefits of using IoC:
>
> +* Easy to switch between different implementations of a particular class at runtime.
>
> +* It increases the modularity of the program.
>
> +* It manages an object’s lifecycle and configuration. Some objects can be singletons, while we can create others per request.
>
> +
>
> +Before we look at some code, here are some things you should have in mind:
>
> +
>
> +### 1. Coupling
>
> +Coupling is a measure of how closely bound software modules are to one another. It is the degree to which changes made to a component force a need for a change in other components or modules. Tight coupling is when a change in component A requires a change in component B. Loose coupling means that components A and B are independent. Thus a change in component A would not affect B.
>
> +Loose coupling is often a sign of testable, well-structured, maintainable, and readable software. Tight coupling leads to code fragility and code rigidity. Code fragility is the likelihood that a software will break in many places [...]

2021-07-12 19:26 UTC, BrianaNzivu approved these changes
Hey @Lamouresparus :wave: 
Great job! 
Your article is such an interesting read that I never wanted it to end.
Just a few things that I should bring to your attention:
1. Before opening a PR ensure that you have thoroughly cross-checked your article for any grammar mistakes. You can use tools like [Grammarly](https://app.grammarly.com/) or Hemmingway. Check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) document for more tools that can aid.
2. Avoid long sentences. They make the article quite hard to read.
3. Before writing an article check out the article structure for each article. As you can see your how-to guide article has a good flow now.

Aside from that please go through all the changes I have made to your article. I have done it in stages so that it can be easy for you.
Next, your article will go through a plagiarism check. Look out for updates.

Regards. :rocket:

2021-07-12 19:34 UTC, Lamouresparus commented
Hello Briana!
Thank you so much for the corrections and changes. I appreciate it.
Best regards

On Mon, Jul 12, 2021, 20:26 Briana Nzivu ***@***.***> wrote:

> *@BrianaNzivu* approved this pull request.
>
> Hey @Lamouresparus <https://github.com/Lamouresparus> 👋
> Great job!
> Your article is such an interesting read that I never wanted it to end.
> Just a few things that I should bring to your attention:
>
>    1. Before opening a PR ensure that you have thoroughly cross-checked
>    your article for any grammar mistakes. You can use tools like Grammarly
>    <https://app.grammarly.com/> or Hemmingway. Check out our resources
>    <https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md>
>    document for more tools that can aid.
>    2. Avoid long sentences. They make the article quite hard to read.
>    3. Before writing an article check out the article structure for each
>    article. As you can see your how-to guide article has a good flow now.
>
> Aside from that please go through all the changes I have made to your
> article. I have done it in stages so that it can be easy for you.
>
> Regards. 🚀
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/2769#pullrequestreview-704465843>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIJKG5N6UHMXK22ELKDYJT3TXM6WRANCNFSM47QXDFEA>
> .
>

2021-07-14 14:41 UTC, hectorkambow commented
plagiarism check done

2021-07-15 08:39 UTC, BrianaNzivu approved these changes
Hey @Lamouresparus 👋 .
I am done with the review.

Please be sure to go through all the changes I have made and take note of all the comments I have made.
Next, a content moderator will do a final review. After that, your article will be published.

Otherwise,
Congratulations on publishing your first article!! 🥳 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am ALWAYS here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2021-07-15 09:35 UTC, ahmadmardeni1 commented
This is a great tutorial, good work and welcome to Section 🎉 @Lamouresparus 

Thank you for the review 🚀, please double-check the front matter and the images paths in your next reviews. @BrianaNzivu

The Intro should always be at the beginning of the article/tutorial. Please go over the changes I made.
Again, great work ladies.

2021-07-15 09:35 UTC, merged

2021-07-15 10:26 UTC, Lamouresparus commented
Hi Briana!
Thank you so much! Thank you for the corrections and comments too. I've
learned a lot 🌝.

Best regards
On Thu, Jul 15, 2021, 09:40 Briana Nzivu ***@***.***> wrote:

> *@BrianaNzivu* approved this pull request.
>
> Hey @Lamouresparus <https://github.com/Lamouresparus> 👋 .
> I am done with the review.
>
> Please be sure to go through all the changes I have made and take note of
> all the comments I have made.
> Next, a content moderator will do a final review. After that, your article
> will be published.
>
> Otherwise,
> Congratulations on publishing your first article!! 🥳
>
> In case of any question or clarification (currently or in the future), do
> not hesitate to reach out via Slack
> <https://app.slack.com/client/T5X14SH7G/D01A6MT673R> or my personal email
> ***@***.***).
> I am ALWAYS here to help.
>
> It has been a pleasure reading and reviewing this article.
>
> Looking forward to seeing you contribute more to EngEd. 🚀
>
> Kind Regards.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/2769#pullrequestreview-707082486>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIJKG5OOHJYYC3YV7JA77S3TX2NGBANCNFSM47QXDFEA>
> .
>