Why Kubernetes is the best technology for running Cloud-Native Database
section-engineering-education/engineering-education pull request #2784
Opened 2021-07-01 12:28 UTC by ephraa

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-01 12:41 UTC, ephraa commented
This solves #2544

2021-07-02 16:12 UTC, hectorkambow commented
@ephraa 
Good afternoon and thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

2021-07-06 17:42 UTC, hectorkambow commented
plagiarism check done

2021-07-08 15:37 UTC, mbaabuones requested changes
@ephraa Great first article! The article is quite informative. I am glad to welcome you to the Section Engineering Program. I am happy that you have already uploaded your hero image, photo and author bio. That is commendable.

In your subsequent PRs, ensure you have a statement that explains what your article covers (see the comments for more details). Please work on the minor changes that I have suggested to you. Ping me when you are done.

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +﻿### Introduction
```suggestion
For a long time, every organization’s dream is to migrate its workload to the cloud. However, the statistics from most IT organizations still show that there is still much work to be done. 

Although databases in the cloud have been around for a long time, the challenges with persisting and moving the cloud data have led to slow cloud adoption. For this reason, the demand for data infrastructure that takes full advantage of cloud computing has been on the rise.

This article provides an overview of cloud native databases and explains why Kubernetes is the best technology for running them.

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +
After the above suggested paragraphs, add a new sub-title 'An overview of cloud native databases'. Under this sub-title, provide the definition of a cloud native database and add the other content.

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +### Kubernetes Design Principles
Connect these principles to the main objective of the article. For example, you can provide the following statement, 'Lets look at the design principles of Kubernetes to understand why it is the best technology for running cloud native databases.'

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +The `cass-operator` specifies the required number of nodes in a given cluster and helps manage the details of adding new nodes for scaling up and choosing which nodes to remove to scale down.
simplify this sentence.

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +Cassandra community is constantly working to make more extensions for management and metrics to be part of the core Apache project so that Cassandra will be more cloud-native to everyone and an out-o
Simplify this sentence. Tip- avoid writing very long sentences.

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +In Kassandra, for every `CassandraDataCenter` resource, the `CQL` access should be exposed as a service. The APIs for metrics and management is accessed by the `cass-operator` and the [Prometheus Ser
The APIs for metrics and management are accessed

2021-07-08 15:37 UTC, mbaabuones commented on content/articles/why-kubernetes-is-the-best-technology-for-running-cloud-native-database/index.md
> +In Kassandra, for every `CassandraDataCenter` resource, the `CQL` access should be exposed as a service. The APIs for metrics and management is accessed by the `cass-operator` and the [Prometheus Ser
K8ssandra

2021-07-10 13:43 UTC, ephraa commented
@mbaabuones The suggestions and points made have been well noted. The changes requested have been made, kindly review them.
Thank you.

2021-07-12 12:08 UTC, mbaabuones approved these changes

2021-07-12 12:25 UTC, mbaabuones commented
@ephraa Good job. Please note the changes I made after the second paragraph. In your subsequent PRs, ensure you have a statement that explains what your article covers.

2021-07-12 15:08 UTC, ephraa commented
@mbaabuones I have noted the changes and suggestions made, I will pay more attention to future articles.
Thank you

2021-07-14 17:35 UTC, merged