Handling JSON in MongoDB
section-engineering-education/engineering-education pull request #2791
Opened 2021-07-01 18:22 UTC by salvador02

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2366

2021-07-02 16:15 UTC, hectorkambow commented
@salvador02 
Good afternoon and thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Also FYI - I see you have made a few commits after creating the PR - please only create a PR when the article is fully polished and ready to be reviewed. 

Otherwise you can make all those changes and commits on your forked repo 👍  

Just an FYI to avoid potential closure of future articles. Thank you. 

cc @ahmadmardeni1 & @louisefindlay23

2021-07-07 18:45 UTC, hectorkambow commented
@Ericgacoki

Will be reviewing this PR 👍

2021-07-07 18:53 UTC, hectorkambow commented
plagiarism check done @Ericgacoki

2021-07-07 19:26 UTC, Ericgacoki commented
Hello @salvador02, welcome to the `EngEd` program 🎊. Thank you for submitting your first article. I'll be reviewing it to correct grammatical and technical errors (if any) before being published.

With appreciation @hectorkambow.

2021-07-08 23:55 UTC, Ericgacoki requested changes
Awesome article @salvador02, you've covered a great topic 🚀. Please check the suggestions I've made below.

2021-07-08 23:55 UTC, Ericgacoki commented on content/articles/handling-json-in-mongodb/index.md
> +### Table of Contents
```suggestion
### Table of content
```
Only capitalize the first word not multiple words in the heading, unless it's a proper noun, an acronym or a keyword.

2021-07-09 00:01 UTC, Ericgacoki commented
@salvador02 ping me when you're done so that we can proceed to `tech review`.

2021-07-09 09:06 UTC, salvador02 commented
@Ericgacoki , Thank you for the suggestions, I committed them. Kindly check out.

2021-07-09 09:10 UTC, salvador02 commented
@Ericgacoki , Thank you for the suggestions, I committed them. Kindly check out.

2021-07-09 11:47 UTC, Ericgacoki commented on content/authors/simon-salva/index.md
> +Simon is a a pssionate computer programmer interested in contributing in open source projects. He likes travelling and playing chess.
> Regarding your author image, please rename it to `avatar.jpg` and ensure that it's not too large. Consider using [Pixlr](https://pixlr.com/e/) or an alternative software to compress/crop it to a suitable size, preferably `600 X 600`px.

@salvador02, seems like you forgot to fix your avatar. Please do so.

2021-07-09 12:09 UTC, Ericgacoki requested changes
Hey @salvador02, be sure to go through the comments left below a suggestion before committing it to avoid missing out some points. Also, remember to `pull` changes before your next local `commit`.

2021-07-09 18:49 UTC, salvador02 commented
@Ericgacoki, kindly check out the corrections. If there is anything pending you can guide me on how to go through it. I will appreciate.

2021-07-09 19:03 UTC, Ericgacoki commented
Good work @salvador02, the only remaining thing at the moment is about your author image. I'm afraid you missed my previous comments about it. However, rename it to `avatar.jpg` and compress/crop it to a suitable size, preferably below 500KB.

2021-07-09 19:16 UTC, salvador02 commented
Is there a preferable image size? or a suggest a suitable compression tool.

2021-07-09 19:24 UTC, Ericgacoki commented
I'd recommend you to use [Pixlr](https://pixlr.com/e/) (though you're not limited to this). `600 X 600px` would be a good size for the avatar.

2021-07-10 01:54 UTC, Ericgacoki commented
Hello @salvador02, this image is similar to the one you deleted. 4MB is too large for an avatar. If you're facing any trouble addressing this issue, feel free to reach out to me via Slack for further assistance. Thank you!

2021-07-10 06:59 UTC, salvador02 commented
@Ericgacoki  I think that one is a now okay

2021-07-10 07:30 UTC, Ericgacoki commented
Yeah, that looks great🙂. We're now proceeding towards `tech review`. At this stage, your article will be reviewed for empirical truth and the work-ability of your code.

cc:@hectorkambow

2021-07-10 09:51 UTC, Ericgacoki approved these changes

2021-07-12 17:38 UTC, Ericgacoki requested changes

2021-07-12 19:34 UTC, salvador02 commented
@Ericgacoki done!

2021-07-12 21:59 UTC, Ericgacoki requested changes
Hello @salvador02, I've completed `tech-review` and I'm impressed with your clean and well formatted code, keep up!🚀 Kindly go though the following suggestions before we head to `final review`.

2021-07-12 21:59 UTC, Ericgacoki commented on content/articles/handling-json-in-mongodb/index.md
> +MongoDB is a high-performance, document-oriented NoSQL database which came to light in the mid-2000s. Unlike SQL-based databases, MongoDB uses documents (records) and collections (tables) to store no
```suggestion
---
layout: engineering-education
status: publish
published: true
url: /handling-json-in-mongodb/
title: Handling JSON in MongoDB
description: In this article, we will learn how to structure, import, export, and save JSON data in MongoDB.
author: simon-salva
date: 2021-07-13T00:00:00-00:20
topics: []
excerpt_separator: <!--more-->
images:
  - url: /engineering-education/handling-json-in-mongodb/hero.png
    alt: Handling JSON in MongoDB image
---

MongoDB is a high-performance, document-oriented NoSQL database which came to light in the mid-2000s. Unlike SQL-based databases, MongoDB uses documents (records) and collections (tables) to store non-relational data.
<!--more-->
MongoDB has grown in its use due to the scalability and its ease of use.
```
Added front matter.

2021-07-12 21:59 UTC, Ericgacoki commented on content/articles/handling-json-in-mongodb/index.md
> +- [Mongoimport](https://docs.mongodb.com/manual/reference/program/mongoimport/)
```suggestion
### Further Reading
Now that you have an understanding of how to use JSON in MongoDB, you can check out these links to find out more on this topic:
- [JSON and BSON](https://www.mongodb.com/json-and-bson)
- [Mongoexport](https://docs.mongodb.com/manual/reference/program/mongoexport/)
- [Mongoimport](https://docs.mongodb.com/manual/reference/program/mongoimport/)

Happy coding!

---

Peer Review Contributions by: [Eric gacoki](/engineering-education/authors/eric-gacoki/)
```
Added peer reviewer line.

2021-07-12 21:59 UTC, Ericgacoki commented on content/articles/handling-json-in-mongodb/index.md
> +```
Did you forget to change these ones? Please change `shell` to `bash`.

2021-07-13 22:09 UTC, Ericgacoki requested changes

2021-07-13 22:09 UTC, Ericgacoki commented on content/articles/handling-json-in-mongodb/index.md
> +```
```suggestion
```bash
db.students.find()
```
```

2021-07-14 12:20 UTC, Ericgacoki commented on content/articles/handling-json-in-mongodb/index.md
> +db.students.find()
@salvador02,
Seems like I mistakenly removed the closing back-ticks (```) in my previous suggestion. Kindly fix this and the article will be ready for `final review` 😎.

2021-07-16 17:47 UTC, salvador02 commented
@Ericgacoki  done!

2021-07-16 18:06 UTC, Ericgacoki approved these changes

2021-07-16 18:09 UTC, Ericgacoki commented
Greetings @hectorkambow, this article is `ready for final review` 🚀.

2021-07-16 19:09 UTC, hectorkambow commented
@salvador02 
Overall great work gents 

Please be sure to go over any edits made to improve future articles/reviews 🚀 


cc @Ericgacoki

2021-07-16 19:09 UTC, merged