Arrays in java
section-engineering-education/engineering-education pull request #2817
Opened 2021-07-04 15:50 UTC by Catherinemugo

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2598

2021-07-13 22:06 UTC, BrianaNzivu commented
Hey @Catherinemugo 👋🏾
Briana here.
Apologies for the delay.
I was just wrapping up on two other articles before focusing on yours fully.
Aside from that,
I believe we are set to begin this review process.

Looking foward to working with you🚀

Regards.

2021-07-15 09:09 UTC, BrianaNzivu requested changes
Hey @Catherinemugo 👋 .
Welcome to Section - EngEd 🚀 
It is a pleasure having you onboard.

I have requested for a few changes before we proceed with the preliminary revision.
Please make this changes and ping me when done.

Also, do not hesitate to reach out in case you have a problem or a question.

Regards.

2021-07-15 09:09 UTC, BrianaNzivu commented on content/articles/arrays-in-java/index.md
> +### Prerequisite
I think a compiler is also needed. 
Have the prerequisites listed instead of having it as one sentence.

2021-07-21 17:59 UTC, BrianaNzivu commented
Hey @Catherinemugo .
Are you ok?
Do you need some help?

2021-07-22 06:48 UTC, Catherinemugo commented
Hello @BrianNzivu 
i have had a tight schedule but ill be working on it very soon sorry for the inconvinience

2021-07-22 08:11 UTC, Catherinemugo commented
@BrianaNzivu resolved

2021-08-02 22:58 UTC, hectorkambow commented
@BrianaNzivu 

Just wanted to get a status update on this PR? 

If its ready for a final review - its been in our queue for quite a while now.

2021-08-03 14:56 UTC, BrianaNzivu requested changes
Hey @Catherinemugo :wave: .
First I'd love to apologize for the delay. A personal emergency came up but I am back.
Next, Good job on the article!
Interesting read.

Just a few things I'd like to point out:
1. Your hero image is in a format that is not supported. Maybe if you can change it to jpg or png, we will be good to go.
2. It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing.

Currently a plagiarism check shall be done and afterward a final review.

Thank you so much for your patience.

In case of a question, problem or clarification do not hesitate to ping me.

Regards :rocket: .

2021-08-04 06:38 UTC, Catherinemugo commented
@BrianaNzivu updated

2021-08-04 21:09 UTC, hectorkambow commented
plagiarism check done

2021-08-06 18:21 UTC, hectorkambow commented
Overall very nice job @Catherinemugo 
Please be sure to go through any changes made by your peer reviewer or myself to better improve future articles. 

There were quite a few sentences that were a bit difficult to get through. 👀  

cc @BrianaNzivu please do the same - go through my edits to better improve future reviews. 

Made some major changes throughout.

2021-08-06 18:22 UTC, merged