Semantic HTML for beginners
section-engineering-education/engineering-education pull request #2872
Opened 2021-07-09 19:01 UTC by josax01

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-09 19:03 UTC, josax01 commented
This fixes #2603

2021-07-13 15:44 UTC, lalith1403 commented
Hey @josax0, is this PR reviewed?

2021-07-13 20:21 UTC, josax01 commented
Hi, @lalith1403, no it isn't

2021-07-13 20:26 UTC, josax01 commented
No,it isn't.

On Jul 13, 2021 16:45, "Lalithnarayan C" ***@***.***> wrote:

Hey @josax0, is this PR reviewed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/section-engineering-education/engineering-education/pull/2872#issuecomment-879199358>,
or unsubscribe
<https://github.com/notifications/unsubscribe-auth/AUO7SH4ISAMZQGJT6QJ6TZTTXRNPXANCNFSM5ADJC6KA>
.

2021-07-14 17:11 UTC, BrianaNzivu commented
> Hey @josax0, is this PR reviewed?

Hey @lalith1403 .👋🏾
Were you planning to review the article?

2021-07-14 18:49 UTC, lalith1403 commented
Please proceed, @BrianaNzivu.

2021-07-21 17:16 UTC, BrianaNzivu requested changes
Hey Joshua :wave: .
First things first welcome to Section Eng-Ed. :tada: 
We are happy to have you here.
My name is Briana and I will be taking you through the review process to make your article almost perfect if not perfect for publishing.

Your article is a very interesting read. 
Good job!
I have done the first review and I have requested a few changes.

I have also noticed that your hero image is not 600 x 400. Please try and resize the image as explained in the instructions in the checklist.
 Since your article is more of a how-to guide, please read this [document](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md) and structure your article like this.

Please ping me when you are done with the corrections.

In case of any problem, question or clarification do not hesitate to reach out. I am here to help.

Regards.

2021-07-21 17:16 UTC, BrianaNzivu commented on content/articles/semantic-html-for-beginners/index.md
> +
The conclusion is a recap of the article.
So give a short summary of what your article has covered (Keep it two to three sentences)

2021-07-23 19:19 UTC, josax01 commented
@BrianaNzivu thanks for the review, I have made the needed changes 👍

2021-07-28 09:30 UTC, josax01 commented
@BrianaNzivu any update :]

2021-07-28 10:22 UTC, BrianaNzivu commented
Hey @josax01 👋🏾.
I have been wrapping up on another article but I will proceed with yours probably tomorrow.
Incase of any updates, I will let you know.

Regards 🚀

2021-08-01 16:52 UTC, josax01 commented
@BrianaNzivu any update on your review

2021-08-02 21:21 UTC, hectorkambow commented
plagiarism check done

2021-08-03 15:18 UTC, BrianaNzivu approved these changes
Hey @josax01 :wave: .
First, I'd like to apologize for the delay. 
A personal emergency came up but now I am back.

Next, Good job on the article!
An interesting read.

I'd like to point out a few things which you can implement in your next articles:
1. It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing.
2. I always know it is a good practice to have your CSS file separate from the HTML file. This time I won't raise any red flags since the focus of the article is not on styling.
3.  Just like how it is advisable to have indented code when coding, It is also advisable to have well-indented code snippets for your article.
4. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes. Remember your first article is normally for you to learn.

That's it! :smile: 

Next, a content moderator will do a final review. After that, your article will be published.

Otherwise,
Congratulations on publishing your first article!! 🥳 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2021-08-04 18:05 UTC, LinusMuema commented
Hi @josax01 
I see you were given a proper welcome by your reviewer. Thanks for submitting your first article and we hope to see more of your great content. You can check the review changes for future articles.

cc: @BrianaNzivu :rocket:

2021-08-04 18:06 UTC, merged