Dynamic programming memoization#1833
section-engineering-education/engineering-education pull request #2909
Opened 2021-07-12 21:21 UTC by elkiplangat

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-14 15:47 UTC, srishilesh commented
@elkiplangat 

Welcome to EngEd community!

Based on your commits, I notice 2 different `index.md` files. Please ensure you only upload one `index.md` file.

Also, make sure to upload a hero image of dimension 600x400. You can use Unsplash to download images, and resize it using Pixlr.

Add author's information - author bio and headshot image under `/content/authors`.

Please refer the contribution guide to understand better.

Thank you.

2021-07-14 18:31 UTC, elkiplangat commented
@srishilesh fixed. I've added a hero image and fixed the double index.md issue. MY author information is already in the /authors directory.

2021-07-19 16:44 UTC, srishilesh requested changes
@elkiplangat 

I've suggested some major changes.

Also, perform a grammar check. I found many errors in capitalization of letters, and punctuation errors. Please correct them.

This article is too short to explain this vast concept. Re-read your article from the perspective of a beginner to see if you can understand.

Explore more on what makes your article different from the already existing articles on GFG or Hackerearth. And, see how you can improve this better. Though, most of the content in your article is already found on the internet, I guess you could explain them in a much better way.

Thanks.

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +as we saw in [this]('https://www.section.io/engineering-education/introduction-to-dynamic-programming/) article, Dynamic programming is the algorithm technique where we break down a problem into smal
```suggestion
As we saw in [this](/engineering-education/introduction-to-dynamic-programming/) article, Dynamic programming is the algorithm technique where we break down a problem into smaller, simpler subproblems then find the solutions to these smaller subproblems and use these solutions to find an optimal solution to the original problem.
```

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +###prerequisites<a name='prerequisites'></a>
Remove these `<a></a>` anchor tags for every headings

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +#Complexity Analysis
`#` -> `###`

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +#Conclusion
`#` -> `###`

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +#Resources
`#` -> `###`

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +Now that you know what memoization is, let's use it to solve a common programming problem.
Don't just blindly state facts or copy stuff from other articles.

Instead walk the reader through the content. Explain them step-by-step. Explain how it works. Why we memoize it? What if we do not? Stack trace the program for sample input

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +From the definition alone, we can see that this problem can be solved using Dynamic Programming. This is because it has overlapping subproblems that when solved lead towards solving the whole problem
`From the definition alone, we can see that this problem can be solved using Dynamic Programming.`

Beginners might not be aware of DP or other programming stuff. You need to break them down.

Explain what DP is, why we use it? How is it related with DP? Why not brute force?

2021-07-19 16:44 UTC, srishilesh commented on content/articles/memoization-and-dp-in-python-beginners-guide/index.md
> +#Complexity Analysis
This is a huge topic.

I can't believe you just covered them in 2 lines. How did you derive this time or space complexity. Explain step by step.

Before all, first explain what complexity analysis is.

2021-07-21 17:38 UTC, srishilesh commented
@elkiplangat 

Any updates?

2021-07-22 11:49 UTC, elkiplangat commented
@srishilesh you suggested some major changes, I'm gonna work on them during the weekend when I have more time.

2021-07-22 15:16 UTC, srishilesh commented
@elkiplangat 

No worries. Take your own time.

2021-07-28 15:23 UTC, hectorkambow commented
plagiarism check done

2021-08-06 17:20 UTC, hectorkambow commented
@elkiplangat Any update on this ? 

If you need more time to apply the changes no worries what so ever when can close the PR - and reopen when ready. 👍 
cc @srishilesh

2021-08-10 23:15 UTC, hectorkambow commented
Just closing to make space in the queue - we can re-open it when the article is ready to be published.

2021-08-10 23:15 UTC, closed without merging