Using Multiple SSH Keys for Multiple GitHub Accounts
section-engineering-education/engineering-education pull request #2912
Opened 2021-07-13 04:02 UTC by LeahKui

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-13 04:05 UTC, LeahKui commented
This fixes #2595

2021-07-15 05:46 UTC, LeahKui commented
Hi @srishilesh, the author page and hero image are part of files committed previously

2021-07-20 13:12 UTC, srishilesh requested changes
@LeahKui 

Welcome to EngEd community!

Amazing article. It looks very beginner friendly.

I've suggested a few changes. Please let me know when they're done.

Thanks.

2021-07-20 13:12 UTC, srishilesh commented on content/authors/wangui-leah/index.md
> +Leah is an information technology enthusiast. She is passionate about software development and technical writing. Her areas of interest are Data Science and Machine learning(ML). In addition, she lov
```suggestion
---
title: Leah
type: authors
---
Leah is an information technology enthusiast. She is passionate about software development and technical writing. Her areas of interest are Data Science and Machine learning(ML). In addition, she loves playing computer games and adventure.
```

2021-07-20 13:12 UTC, srishilesh commented on content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
> +SSH is designed to offer secure encryption, verification, and communication between computers. It provides a safe way of executing commands and configuring services remotely. The SSH technology is of
`client-server model`

Add 1 - 2 lines of explanation about it, and reference a link for more info about it.

2021-07-20 13:12 UTC, srishilesh commented on content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
> +Setting up SSH, you use a pair of keys, a public key and a private key. A public key is stored on the SSH server, and a private key is stored on your SSH client. So basically, SSH uses [asymmetric en
```suggestion
Setting up SSH, you use a pair of keys, a public key and a private key. A public key is stored on the SSH server, and a private key is stored on your SSH client. So basically, SSH uses [asymmetric encryption](https://sectigostore.com/blog/what-is-asymmetric-encryption-how-does-it-work). 
```

2021-07-20 13:12 UTC, srishilesh commented on content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
> +Setting up SSH, you use a pair of keys, a public key and a private key. A public key is stored on the SSH server, and a private key is stored on your SSH client. So basically, SSH uses [asymmetric en
More info about Private and Public keys would help

2021-07-20 13:12 UTC, srishilesh commented on content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
> +Setting up SSH, you use a pair of keys, a public key and a private key. A public key is stored on the SSH server, and a private key is stored on your SSH client. So basically, SSH uses [asymmetric en
It's good that you have specified a referencing link. Adding a single of explanation would be better

2021-07-20 13:12 UTC, srishilesh commented on content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
> +2. Choose SSH and GPG keys
What is a GPG key?

2021-07-20 13:12 UTC, srishilesh commented on content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
> +That's all there is for this article. I hope it will be helpful. Also, I hope it helps you understand how to use multiple SSH keys for multiple GitHub accounts.
Give a brief summary of what you mentioned previously. Write key takeaways from this article. Tell how and where the reader could learn more about this.

If needed, you can add an additional `Further reading` section.

2021-07-22 19:37 UTC, LeahKui commented
@srishilesh, thanks for reviewing this article. worked on the revisions

2021-07-22 20:54 UTC, ninjaginja commented
plagiarism check completed - all good
[2120420-14fde1f5e2e7404e4898-1626987273357.pdf](https://github.com/section-engineering-education/engineering-education/files/6865161/2120420-14fde1f5e2e7404e4898-1626987273357.pdf)

2021-07-27 18:40 UTC, srishilesh approved these changes
@LeahKui 

Thanks for making the changes. This looks great!

Make sure to go through my commits, to understand and improve on your future articles.

Moving for the final review.

Thanks.

2021-07-29 12:32 UTC, louisefindlay23 commented
Hi, @LeahKui. Great tutorial. It certainly guides the users through each step. 

However, we value detailed and in-depth guides and feel you could add some detail to provide extra value to our readers. **Some suggested topics are:** What are SSH Keys? Why should you use SSH Keys with Git and GitHub? The difference between adding 2FA on your GitHub account vs using SSH Keys.

Thanks,
Louise - Content Moderator

2021-07-30 18:13 UTC, hectorkambow commented
Overall great work @LeahKui 

cc @srishilesh

2021-07-30 19:55 UTC, LeahKui commented
Thank you, @hectorkambow, @srishilesh, @louisefindlay23, for reviewing my article. I added the content @louisefindlay23 suggested

2021-07-31 12:18 UTC, merged

2021-07-31 12:19 UTC, louisefindlay23 commented
Thanks, @LeahKui for adding the extra content. I'm sure our readers will appreciate it. Final review complete :)

Thanks, @srishilesh for peer reviewing.