Building a Simple Nest.js Microservice Application using Redis as the Transporter
section-engineering-education/engineering-education pull request #2917
Opened 2021-07-13 15:16 UTC by kimkimani

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-14 06:35 UTC, zolomohan requested changes

2021-07-14 06:35 UTC, zolomohan commented on content/articles/building-a-simple-nestjs-microservice-application-using-redis-as-the-transporter/index.md
> +- We are going to buddle Nest.js CLI using a Node.js package. Ensure you have Node.js installed so that you can have NPM on your computer. You can download the Node.js installer here.
Please add the link to Node.js Download Page.

2021-07-14 06:35 UTC, zolomohan commented on content/articles/building-a-simple-nestjs-microservice-application-using-redis-as-the-transporter/index.md
> +- To implement a microservice architecture, we are going to use Redis as the transporter. Make sure Redis is installed on your computer.
Please add the link to Redis download page.

2021-07-14 06:45 UTC, zolomohan requested changes

2021-07-14 06:45 UTC, zolomohan commented on content/articles/building-a-simple-nestjs-microservice-application-using-redis-as-the-transporter/index.md
> +```
Please instruct the reader to start the redis-server as well.

2021-07-14 06:47 UTC, zolomohan requested changes

2021-07-14 06:47 UTC, zolomohan commented on content/articles/building-a-simple-nestjs-microservice-application-using-redis-as-the-transporter/index.md
> +```
It's a bit unclear if I should run this command inside the nest-ms folder or outside. Please make it clear here.

2021-07-21 17:13 UTC, zolomohan commented
@kimkimani any updates?

2021-07-23 21:28 UTC, zolomohan commented
@kimkimani?

2021-07-24 13:14 UTC, kimkimani commented
> @kimkimani any updates?

Check the updates @zolomohan

2021-07-28 18:50 UTC, hectorkambow commented
plagiarism check done

2021-07-30 21:00 UTC, WanjaMIKE commented
Will be conducting a final review.

2021-08-01 16:39 UTC, WanjaMIKE commented
Changing the branch name from `building-a-simple-nestjs-microservice-application-using-redis-as-the-transporter` to `building-nest-js-application-using-redis` for better SEO.

2021-08-02 19:05 UTC, hectorkambow commented
Great work gents @kimkimani 

Very easy to follow along 👍 

cc @zolomohan & @WanjaMIKE 
 🚀

2021-08-02 19:05 UTC, merged