Getting started with machine learning in Matlab
section-engineering-education/engineering-education pull request #2934
Opened 2021-07-14 18:56 UTC by peterAdongo

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-15 18:21 UTC, hectorkambow commented
@peterAdongo 

Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

2021-07-23 15:38 UTC, ahmadmardeni1 commented
this fixes #2604

2021-07-24 08:03 UTC, srishilesh commented
@peterAdongo 

Great article. On a quick glance, I see that this is a vast topic, which I believe could not be covered in a single article. I would suggest to break this down, and write articles focusing on specific topic.

Moreover, I see majority of your article was intro to AI - Supervised, unsupervised learning, and its types. We have already covered this, in the other articles.

I feel it would be better to rename the title and dive deep into that topic specifically. Just make sure that you don't have conflicts with already [existing articles](https://www.section.io/engineering-education/search/?q=matlab) in MATLAB. And, reference these articles in yours, as you see fit.

Ping me once you have decided on the new topic.

Thanks.

2021-07-29 09:37 UTC, linetachieng commented
@srishilesh I change the topic to ' how to implement linear regression in Matlab' is that ok??

2021-07-31 11:11 UTC, srishilesh commented
@linetachieng 

Sounds good.

But, changing only the title wouldn't be enough. You will have to dig deeper into linear regression concepts. (We already have articles explaining the concepts, so I would suggest to choose some other type of regression).

Fyi, there are 12 types of regression. You could choose something else which you don't find here. You'll have to explain the concepts in-detail, and go through the code tutorial step-by-step. Make sure you choose a well defined problem for the code tutorial.

Thanks.

cc. @hectorkambow

2021-08-03 17:02 UTC, hectorkambow commented
@lalith1403 may be able to add some insight on this type of topic as well.

2021-08-04 18:05 UTC, lalith1403 requested changes
Several points to be noted in this article. When we write an article, what is the case we are trying to make? What narrative do we control and present to the reader? These questions need to be answered. In your case, MATLAB as an alternative to Python is what I understand. This is something you should focus on. Explaining supervised learning, unsupervised learning is not something we would touch in such an article as it wouldn't help us make the case for MATLAB as an alternative. I hope that makes sense. Would love to hear your thoughts on this.

2021-08-04 18:05 UTC, lalith1403 commented on content/articles/getting-started-with-machine-learning-using-matlab/index.md
> +Here, you group your data based on some similarities or characteristics. It is not a must you know the grouping. This grouping can be done using clustering techniques. Clustering is the grouping of t
Clustering is just one form of unsupervised learning algorithm

2021-08-04 18:05 UTC, lalith1403 commented on content/articles/getting-started-with-machine-learning-using-matlab/index.md
> +
The distinction between partition and overlapping algorithms is not clear. More explanation is required.

2021-08-04 18:05 UTC, lalith1403 commented on content/articles/getting-started-with-machine-learning-using-matlab/index.md
> +Here, you first import data, preprocess the data. This may include creating some visualization and identifying variables of interest. In the next step, you select your model and train it on the data
Test the model on test set. That needs to be mentioned.

2021-08-04 18:08 UTC, lalith1403 commented
As mentioned earlier, pick a well defined problem/ statement that you want to write on. That way, we can focus on the core content we want to put out. We generally avoid elementary topics such as linear regression in MATLAB/Python unless it gives us a better explanation than the ones that exist.

2021-08-06 15:51 UTC, peterAdongo commented
@srishilesh  ok let me talk about how to solve the Fourier series using Matlab

cc @hectorkambow

2021-08-06 16:02 UTC, peterAdongo commented
@srishilesh ok let me talk about how to solve the Fourier series using Matlab

cc @hectorkambow, @ahmadmardeni1

2021-08-09 13:30 UTC, srishilesh commented
@peterAdongo 

I find one such documentation by MathWorks [here](https://in.mathworks.com/help/curvefit/fourier.html). How exactly will yours be different from this? What topics do you wish to cover under this?

I don't have much idea about Fourier series. Probably, @lalith1403 could help us here.

Thanks. 

cc. @hectorkambow

2021-08-09 13:46 UTC, peterAdongo commented
@srishilesh here I cover deeply and a more concise article. I will talk about how to find Fourier coefficients, Fourier series sine and cosine form. I will also look at the complex-valued coefficients and Fourier series complex-exponential form which is not in the link you provided

cc @hectorkambow

2021-08-09 17:38 UTC, srishilesh commented
@peterAdongo 

Let's wait for @lalith1403 's opinion.

2021-08-10 17:32 UTC, lalith1403 commented
Are you suggesting writing a new article? If yes, can you go through the topic suggestion form again? I will need more information on the article and the concepts that you will be covering. Fourier Series has been covered well over the net. Scope exists in the form of unique projects that you can work on. If you can visualize the complex coefficients and implement them on custom image and music data, that would be an excellent project. What do you think? 

If you are trying to make modifications to this article, can you give me more information on how you want to link ML and Fourier series?

2021-08-10 23:17 UTC, hectorkambow commented
Who is the author here @peterAdongo  or @linetachieng

2021-08-11 15:32 UTC, peterAdongo commented
@hectorkambow the author is @peterAdongo

2021-08-14 20:43 UTC, closed without merging