How to Send an Email with Django
section-engineering-education/engineering-education pull request #2936
Opened 2021-07-14 22:56 UTC by Samuel-2626

This fixes #2705

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-24 06:13 UTC, Samuel-2626 commented
@geoffrey45 any update

2021-07-24 06:25 UTC, geoffrey45 commented
> @geoffrey45 any update
> 

Hello @Samuel-2626 I will be sending out the pending comments today. Thank you for the patience.

2021-07-24 14:03 UTC, geoffrey45 requested changes
@Samuel-2626 Thank you for submitting your article for review. It is very clean and well structured 👍. 

Please check the comments below and leave a mention in a comment when you are done with the suggested change.

2021-07-24 14:03 UTC, geoffrey45 commented on content/articles/how-to-send-an-email-with-django/index.md
> +
Suggest a way of hiding the details.

2021-07-24 14:46 UTC, Samuel-2626 commented
@geoffrey45 thanks for the review, changes as been made 👍

2021-07-25 12:43 UTC, geoffrey45 requested changes
@Samuel-2626 Please take a look at the attached comments.

2021-07-25 12:43 UTC, geoffrey45 commented on content/articles/how-to-send-an-email-with-django/index.md
> +
Please include the command to migrate.

2021-07-25 12:43 UTC, geoffrey45 commented on content/articles/how-to-send-an-email-with-django/index.md
> +
There is no subject form on your forms.py. Running this will throw an error.

2021-07-25 12:43 UTC, geoffrey45 commented on content/articles/how-to-send-an-email-with-django/index.md
> +
Google accounts with 2FA enabled don't work with secure apps. Instead, they use App passwords. Please update this area providing the necessary links or guides.

2021-07-25 12:43 UTC, geoffrey45 commented on content/articles/how-to-send-an-email-with-django/index.md
> +
Mentions methods or ways of hiding these credentials. Consider mentioning [Django-environ](https://django-environ.readthedocs.io/en/latest/#django-environ).

2021-07-25 14:00 UTC, Samuel-2626 commented
@geoffrey45 thanks, changes have been made :)

2021-07-25 14:23 UTC, geoffrey45 commented on content/articles/how-to-send-an-email-with-django/index.md
> +    message = forms.CharField(widget=forms.Textarea)
@Samuel-2626 Please remove the unused form entries. `email` and `name` are not used in views.py. Also, `to` is a very short variable name. Consider changing it to be more descriptive.

2021-07-25 14:25 UTC, geoffrey45 requested changes
@Samuel-2626 Let me know when you are done.

2021-07-25 14:32 UTC, Samuel-2626 commented
@geoffrey45 Done, thanks 👍

2021-07-25 19:10 UTC, geoffrey45 approved these changes

2021-07-25 19:15 UTC, geoffrey45 commented
@hectorkambow This article is ready for final review. Awaiting plagiarism check.

2021-07-28 15:54 UTC, hectorkambow commented
plagiarism check done

2021-07-28 22:11 UTC, Samuel-2626 commented
> @hectorkambow This article is ready for final review. Awaiting plagiarism check.

Thanks @geoffrey45, plagiarism check as been done...

2021-08-02 17:47 UTC, LinusMuema approved these changes
Hi @Samuel-2626 
Thank your for your great work in this article. I noticed your work was a bit behind compared to section's master repo. Please ensure your sync your fork with the latest section repo next time before starting a new article. There are bug fixes and changes added regularly to the main repo and they help a lot even in the review process. Otherwise, keep up the amazing job.

cc: @geoffrey45 - please check if the article urls match the directory name. This is important also.

You can check my commits for minor edits. :rocket:

2021-08-02 17:48 UTC, merged