Build and Dockerize a Full-stack React app with Node.js and Nginx
section-engineering-education/engineering-education pull request #2974
Opened 2021-07-19 20:25 UTC by mosesreigns

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-20 15:15 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you. @mosesreigns

2021-07-28 18:48 UTC, hectorkambow commented
plagiarism check done

2021-07-31 11:30 UTC, srishilesh requested changes
@mosesreigns 

Great article.

I've requested for a few changes. Please ping me when done.

Thanks.

2021-07-31 11:30 UTC, srishilesh commented on content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
> +This involves two major setups a client and back-end API services. The application involves multi-stage building. You utilize several FROM statements in your Dockerfile for multi-stage builds. Then w
```suggestion
This involves two major setups a client and back-end API services. The application involves multi-stage building. You utilize several FROM statements in your Dockerfile for multi-stage builds. Then write a `docker-compose.yml` file to execute all the Dockerfiles with the proper instructions to set a fully dockerized application. To start with, create a project directory to work on. We will start by creating a Node.js back-end API with Express to expose a REST API and communicate with the MySQL database.
```

2021-07-31 11:30 UTC, srishilesh commented on content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
> +Inside your project directory, go ahead and create a new folder and name it a server. Will write our backed login inside this directory. So once created cd to this folder and initialize a Node.js app
```suggestion
Inside your project directory, go ahead and create a new folder and name it a `server`. Will write our backed login inside this directory. So once created `cd` to this folder and initialize a Node.js application with `npm init -y`. Once executed, a `package.json` file will be created to add any dependencies that we need our application to use.
```

2021-07-31 11:30 UTC, srishilesh commented on content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
> +### Create the Dockerfiles environments
You could reference other Section articles on using Dockers and containers

2021-07-31 11:30 UTC, srishilesh commented on content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
> +### Setting the Nginx server
What is proxy? What is reverse proxy? Why do we use Nginx? What other alterative solutions do we have?

2021-07-31 11:30 UTC, srishilesh commented on content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
> +
You can add a link to the GitHub repository containing the full code

2021-07-31 11:30 UTC, srishilesh commented on content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
> +#### Step3: Writing the API configurations
You can probably give idea on what is the objective of this application. What are you trying to build?

2021-08-02 09:25 UTC, mosesreigns commented
> @mosesreigns
> 
> Great article.
> 
> I've requested for a few changes. Please ping me when done.
> 
> Thanks.

Thank you @srishilesh. I have made some changes to improved on what you suggested,

2021-08-04 12:00 UTC, mosesreigns commented
Any update @srishilesh

2021-08-04 12:14 UTC, srishilesh commented
@mosesreigns 

Will review it by tonight.

2021-08-09 19:10 UTC, hectorkambow commented
@mosesreigns 
Overall nice job - very informative and detailed tutorial (there were some grammatical issues throughout the articles that needed to be addressed) - please be sure to go over any edits made by the peer reviewer or myself. Articles should come in polished and ready to publish.

cc @srishilesh please do the same- review to improve future reviews - there were some areas that needed to be fixed before we could publish. 
👍

2021-08-09 19:11 UTC, merged