understanding and working with javascript cookies
section-engineering-education/engineering-education pull request #2993
Opened 2021-07-21 13:58 UTC by fabulousDesigns

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2951

2021-07-22 08:24 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you. @fabulousDesigns

2021-07-22 11:38 UTC, fabulousDesigns commented
Noted, @ahmadmardeni1

2021-07-24 17:16 UTC, zolomohan commented
@geoffrey45 @fabulousDesigns it seems like a similar article has already been published.
https://www.section.io/engineering-education/what-are-cookies-nodejs/

2021-07-25 13:01 UTC, geoffrey45 requested changes
@fabulousDesigns Welcome to the EngEd program 🎉🎉.

Thank you for submitting your first article for review

Please take a look at the attached comments. Leave a mention in a comment when you are done with making the suggested changes.

2021-07-28 18:55 UTC, hectorkambow commented
plagiarism check done 👍

2021-08-03 17:57 UTC, geoffrey45 requested changes
@fabfabulousDesigns Check the comments below.

2021-08-03 17:57 UTC, geoffrey45 commented on content/articles/understanding-and-working-javascript-cookies/index.md
> +        }
Here, I guess you are trying to call the function `setCookie()`. Please remove the `function` keyword .

2021-08-03 17:57 UTC, geoffrey45 commented on content/articles/understanding-and-working-javascript-cookies/index.md
> +- **getCookie()** - Reads the cookie.
Explain these in order of appearance.

2021-08-03 17:57 UTC, geoffrey45 commented on content/articles/understanding-and-working-javascript-cookies/index.md
> +        alert("Welcome again, " + firstName);
Use cookies that you have used in previous examples. For example, `Username`

2021-08-03 17:57 UTC, geoffrey45 commented on content/articles/understanding-and-working-javascript-cookies/index.md
> +To erase a cookie, simply give it a new name, an empty or random value, and a max-age value of 0. You'll need to include the cookie's path and domain property when deleting it if you specified them.
Please remove the random value option

2021-08-03 17:57 UTC, geoffrey45 commented on content/articles/understanding-and-working-javascript-cookies/index.md
> +document.cookie = "firstName=; max-age=0";
This line is repeated in the below it. Please remove it.

2021-08-03 19:55 UTC, fabulousDesigns commented
@geoffrey45 Thanks for the recommendations; I've made the necessary modifications.

2021-08-05 10:29 UTC, geoffrey45 approved these changes

2021-08-06 13:58 UTC, LinusMuema commented
Hi @fabulousDesigns 
Thanks for joining section and we look forward to getting more awesome content from you.
Great job on this article.

cc: @geoffrey45

2021-08-06 13:58 UTC, merged