Implementing a GraphQL server using Prisma, SQLite, and Nest.js with Typescript
section-engineering-education/engineering-education pull request #3066
Opened 2021-07-29 11:52 UTC by JuliusGikonyoNyambura

…Typescript

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-31 13:47 UTC, Dawe-7 commented
Hi @JuliusGikonyoNyambura, I've started reviewing your article. Please don't make any changes since that might disrupt the review process.

2021-07-31 19:48 UTC, Dawe-7 requested changes
@JuliusGikonyoNyambura, I noticed that some of your sentences are too long making them hard to read. Make use of the [hemingway editor](https://hemingwayapp.com/) to avoid that. I've left a few suggestions that will improve the quality of the article. Consider making the changes and we'll move on to the next process. Overall, great article.

2021-07-31 19:48 UTC, Dawe-7 commented on content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/index.md
> +From above, we are exposing the _GraphQLModule_ and _PostModule_ in the module's imports array. In addition, we are also specifying the _typePaths_ for the _GraphQLModule_.
```suggestion
In the file above, we are exposing the _GraphQLModule_ and _PostModule_ in the module's imports array. Also, we are specifying the _typePaths_ for the _GraphQLModule_.
```

2021-07-31 19:48 UTC, Dawe-7 commented on content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/index.md
> +From above, we are simply adding the _PostResolvers_ and _PostService_ as providers.
```suggestion
In the file above, we are simply adding the _PostResolvers_ and _PostService_ as providers.
```

2021-07-31 19:48 UTC, Dawe-7 commented on content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/index.md
> +To gain more insight knowledge concerning Prisma, Nest JS, and GraphQL, check out the following resources:
```suggestion
To gain more insight knowledge on Prisma, Nest JS, and GraphQL, check out the following resources:
```

2021-08-02 11:56 UTC, JuliusGikonyoNyambura commented
@Dawe-7, I have added the changes.

2021-08-02 12:01 UTC, JuliusGikonyoNyambura commented
@Dawe-7, I have added the changes.

2021-08-02 12:31 UTC, Dawe-7 approved these changes

2021-08-02 21:11 UTC, hectorkambow commented
plagiarism check done

2021-08-08 11:08 UTC, louisefindlay23 approved these changes
Great article, @JuliusGikonyoNyambura. I especially liked your simple explanation of GraphQL and its benefits which is easy to understand for readers new to GraphQL.

Be sure to look at the edits I've made to inform future articles.

Thanks, @Dawe-7 for peer reviewing.

2021-08-08 11:09 UTC, merged