A practical approach to Date and Time in JavaScript
section-engineering-education/engineering-education pull request #3069
Opened 2021-07-29 15:47 UTC by Sajeyks

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-29 18:48 UTC, jerimkaura commented
@Sajeyks  I will be reviewing this article. 

cc: @hectorkambow

2021-07-29 19:10 UTC, jerimkaura requested changes
@Sajeyks, This seems like an amazing article, especially for beginners. However, besides the changes I have suggested, consider adding more content to it so that it gets more value and be more helpful to your readers. 

@ahmadmardeni1 You could you please add the labels for me here.

Cc: @hectorkambow

2021-07-29 19:10 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +In case we want to use the current day like today, we would be required to do some changes in terms of the formating  `Today's` formating.
```suggestion
In case we want to use the current day like today, we would be required to do some changes in terms of  `Today's` formatting.
```

2021-07-29 19:10 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +In this task, we will iterate from one date to another counting the number of weekends until we get to the given date. Also, get then the number of days between the two dates. Then we will subtract t
```suggestion
In this task, we will iterate from one date to another, counting the number of weekends until we get to the given date. Also, get then the number of days between the two dates. Then we will subtract the number of weekends from the number of days between the two dates.
```

2021-07-29 19:10 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> + You can go ahead and try the above tasks on your own now or even customize them to suit your liking, little practice wouldn't hurt. If you also chose to copy a snippet and save it with a `.html` ext
```suggestion
 You can go ahead and try the above tasks on your own now or even customize them to suit your liking, a little practice wouldn't hurt. If you also chose to copy a snippet and save it with a `.html` extension and open it with a browser, it should work just fine. Have fun coding!
```

2021-07-30 20:27 UTC, jerimkaura commented
Thank you @Sajeyks for making the changes🚀. Let me go through them just to be sure before we proceed to the tech review.

2021-07-31 16:58 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +Dates and time are crucial parts of our day-to-day lives. Knowing how to work with them is important.JavaScript has an inbuilt `Date` object that can be used for various applications. There are also
```suggestion
Dates and time are crucial parts of our day-to-day lives. Knowing how to work with them is important. JavaScript has an inbuilt `Date` object that can be used for various applications. There are also some inbuilt methods in JavaScript that can help us make use of the `Date` object.
```

2021-07-31 17:19 UTC, jerimkaura requested changes
@Sajeyks, I have done the `tech review`. Your snippets are light and easy to follow through :rocket:. There are a few changes that we must have missed. Commit them then ensure that your conclusion gives a summary of the article; some brief paragraph that one could look at and get the idea communicated in the article.

2021-07-31 17:19 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +This method will continue calling our function until we close the window or the `clearInterval()` method is called, in this case, we shall call it when the Countdown Timer gets to zero. We will also
```suggestion
This method will continue calling our function until we close the window or the `clearInterval()` method is called, in this case, we shall call it when the countdown timer gets to zero. 

We will also use the `floor()` method to return rounded-up numbers for the days, hours, minutes, and seconds after we get the difference in time.
```

2021-07-31 17:19 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +Dates and time are crucial parts of our day-to-day lives. Knowing how to work with them is important.JavaScript has an inbuilt `Date` object that can be used for various applications. There are also
```suggestion
Dates and time are crucial parts of our day-to-day lives. Knowing how to work with them is important. JavaScript has an inbuilt `Date` object that can be used for various applications. There are also some inbuilt methods in JavaScript that can help us make use of the `Date` object.
```

2021-07-31 17:19 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> + You can go ahead and try the above tasks on your own now or even customize them to suit your liking, a little practice wouldn't hurt. If you also chose to copy a snippet and save it with a `.html` e
```suggestion
 You can go ahead and try the above tasks on your own now or even customize them. Can copy the snippets and paste them into a file you name with a `.html` extension.
  
Run the code by opening the file in a browser. If you are using vscode, install a live server extension to make the task easier. Have fun coding!
```

2021-08-01 14:07 UTC, Ericgacoki commented
@jerimkaura 
I've updated the labels as you requested.

2021-08-01 19:38 UTC, jerimkaura commented
@Sajeyks thanks for making the change, let me check it.

2021-08-02 10:43 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +Dates and time are crucial parts of our day-to-day lives. Knowing how to work with them is important. JavaScript has an inbuilt `Date` object that can be used for various applications. There are also
```suggestion
Date and time are crucial parts of our day-to-day lives. Knowing how to work with them is important. JavaScript has an inbuilt `Date` object that can be used for various applications. There are also some inbuilt methods in JavaScript that can help us make use of the `Date` object.
```

2021-08-02 10:46 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +In this task, we will iterate from one date to another, counting the number of weekends until we get to the given date. Also, get then the number of days between the two dates. Then we will subtract
```suggestion
In this task, we will iterate from one date to another, counting the number of weekends until we get to the given date. Next, we will get the number of days between the two dates and then subtract the number of weekends from the number of days between the two dates.
```

2021-08-02 11:05 UTC, jerimkaura requested changes
@Sajeyks, Make the minor suggestions.

2021-08-02 11:05 UTC, jerimkaura commented on content/articles/a-practical-approach-to-date-and-time-in-javascript/index.md
> +In this task, we will iterate from one date to another, counting the number of weekends until we get to the given date. Also, get then the number of days between the two dates. Then we will subtract
```suggestion
In this task, we will iterate from one date to another, counting the number of weekends until we get to the given date. Next, we will get the number of days between the two dates and then subtract the number of weekends from the number of days between the two dates.
```

2021-08-02 21:10 UTC, hectorkambow commented
plagiarism check done

2021-08-03 15:43 UTC, hectorkambow commented
Overall great work Gents 👍 

Made some minor edits for flow/format - please be sure to review to see how future articles may be improved. 

cc @jerimkaura - please go over my minor edits to improve future reviews 👍 - overall nicely done.

2021-08-03 15:43 UTC, merged