Assertions and Design By Contract in Java
section-engineering-education/engineering-education pull request #3084
Opened 2021-07-30 19:00 UTC by Paul22691

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x]Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2659

2021-08-02 13:03 UTC, Dawe-7 commented
Hello @Paul22691, I'll be reviewing your article. I noticed that you have long sentences that are hard to read. Before we begin the review, I'll need you to use the [hemimgway editor](https://hemingwayapp.com/rl) to check on that. Also, your hero image should be saved as `hero.jpg` and not `hero.jpg.jpg`

2021-08-02 13:09 UTC, Dawe-7 commented
@Paul22691, Kindly add more content in the conclusion and revisit the article once more.

2021-08-02 22:46 UTC, hectorkambow commented
plagiarism check done

2021-08-04 07:12 UTC, Paul22691 commented
@Dawe-7 you can now proceed

2021-08-08 20:35 UTC, Dawe-7 requested changes
@Paul22691, Implement the suggestions so that we can move on to final review.

2021-08-08 20:35 UTC, Dawe-7 commented on content/articles/assertion-and-design-by-contract-in-java/index.md
> +Before reading this tutorial, you need to have basic knowledge of Java.
Can you add an IDE link where readers can run the Java program

2021-08-08 20:35 UTC, Dawe-7 commented on content/articles/assertion-and-design-by-contract-in-java/index.md
> +This program helps the learner to implement assertion by dividing two numbers.
Here, we need to add some comments in the program and an explanation of what is happening after the program

2021-08-11 06:45 UTC, Paul22691 commented
@Dawe-7 done on the changes lets proceed

2021-08-11 19:46 UTC, Dawe-7 approved these changes

2021-08-14 11:59 UTC, LinusMuema commented
Hi @Paul22691 
Thanks for the article. Keep up the good work.

cc: @Dawe-7 
Sorry it took a while to make the final review

2021-08-14 11:59 UTC, merged