Sending Notifications with Spring Boot, Angular, and Firebase Cloud Messaging
section-engineering-education/engineering-education pull request #3086
Opened 2021-07-30 22:21 UTC by john-amiscaray

This fixes #2908

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-07-31 12:59 UTC, srishilesh requested changes
@john-amiscaray 

Amazing article.

I've suggested minor changes. Please ping me once done.

Also, make sure to perform a Grammar check using Grammarly.

Thanks.

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +![a flow chart to illustrate the architecture](flow-chart.png)
`flow-chart.png`

You must specify full path for the image. For example, it must be `/engineering-education/[ARTICLE-DIRECTORY-NAME]/[IMAGE-NAME]`

Do this change for all the images that you have used.

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +On the front-end, you will more or less just need some basic angular knowledge to follow along. This includes using the CLI, the HTTP client, and basic templating. When it comes to Firebase, I won’t
Break down these paragraphs into bulleted-points.

The readers always find it easy to read points than to read bigger paragraphs.

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +Once Firebase finishes creating your project, it should bring you to the project overview. From there, click the gear icon on the left next to the **project overview** button, then select **project s
Break it down into a numbered list.

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +
Break down this code snippet into 2 smaller code snippets, with each containing one function. And, explain what each function does under the respective code snippet.

Also, add comments if possible.

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +   }
Though, this code formatting looks nice and clear to read.

Sometimes, these extra new lines look too weird after publishing it. They would occupy a majority of the page. Thus, leading the reader to scroll, to read it.

Remove the extra new lines

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +In this guide, we went through the process of sending notifications in a full-stack Spring Boot and Angular project. In the backend, we set up a REST API to tell Firebase what notifications to send a
If possible, add a `Further reading` section containing other references that might help the reader.

2021-07-31 12:59 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +![a sample notification](notification.png)
Modify this as mentioned earlier

2021-08-02 22:44 UTC, hectorkambow commented
plagiarism check done

2021-08-03 00:26 UTC, john-amiscaray commented
@srishilesh Thanks for the help! I tried to best implement your comments in the most recent commit. Please let me know if I missed anything or if any further revisions are needed.

2021-08-11 13:18 UTC, srishilesh commented
@john-amiscaray 

Could you please add an image (author headshot image) `avatar.jpg` (can be `.png` too) under `/content/authors/john-amiscray` folder?

Ping me when done, we can move on to the final review.

2021-08-11 13:35 UTC, john-amiscaray commented
> 
> 
> @john-amiscaray
> 
> Could you please add an image (author headshot image) `avatar.jpg` (can be `.png` too) under `/content/authors/john-amiscray` folder?
> 
> Ping me when done, we can move on to the final review.

@srishilesh There should already be one there. I already put that and the author's description with my first article some months back. I just edited my author's description in this pull request.

2021-08-11 13:55 UTC, srishilesh commented
> > 
> > 
> > @john-amiscaray
> > 
> > Could you please add an image (author headshot image) `avatar.jpg` (can be `.png` too) under `/content/authors/john-amiscray` folder?
> > 
> > Ping me when done, we can move on to the final review.
> 
> @srishilesh There should already be one there. I already put that and the author's description with my first article some months back. I just edited my author's description in this pull request.

Got it. Thanks for the update

@john-amiscaray

2021-08-12 13:49 UTC, srishilesh approved these changes
@john-amiscaray 

Amazing article. It was very beginner friendly. Great work!

Make sure to go through my commits, to understand and improve on your future articles.

> NOTE: Please ensure to make your GitHub repo `Public`. Or if the URL is wrong, please edit it.

Ping me when done, we can move for the final review.

Thanks.

2021-08-12 14:44 UTC, srishilesh commented on content/articles/fcm-with-spring-and-angular/index.md
> +With that created, try sending a `POST` request to our server to send notification while the app is inactive.
Yes you're right, that makes sense. Thanks for reverting. I've learnt something new today.

Please revert this change

2021-08-12 15:17 UTC, john-amiscaray commented on content/articles/fcm-with-spring-and-angular/index.md
> +To best use this guide, try making your full-stack project that uses these concepts.
I just reverted those two changes. Thanks.

2021-08-14 10:26 UTC, ahmadmardeni1 commented
As always, great article!🚀 @john-amiscaray 

Thank you for the review @srishilesh

2021-08-14 10:26 UTC, merged