Getting started with optimization in Matlab
section-engineering-education/engineering-education pull request #3101
Opened 2021-07-31 20:50 UTC by florenceatieno45

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-02 17:55 UTC, lalith1403 commented
@florenceatieno45 Welcome to Eng Ed Program. We wish you the best of luck and hope to see you write inspiring articles. To publish your article, we will need a short bio and headshot pic. For more details, refer to the contributing guidelines in the main repository, or refer to the authors folder under the content folder.

2021-08-15 12:58 UTC, lalith1403 commented
@florenceatieno45 There are several line breaks and grammatical errors in the article. Refer to the [contribution guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md) for more information. Additionally, your author folder name should ideally be in the format `firstname-lastname`. You have used your GitHub username as your folder name. Can you change that?

2021-08-16 18:31 UTC, hectorkambow commented
plagiarism check done

2021-08-17 08:55 UTC, florenceatieno45 commented
@lalith1403 requested changes done.

2021-08-18 16:47 UTC, linetachieng commented
@lalith1403 what's the progress of the article?

2021-08-18 16:52 UTC, florenceatieno45 commented
@lalith1403 what's the progress of the article?

2021-08-19 16:02 UTC, lalith1403 requested changes
Technically sound. The article requires a lot more detail to the structure of the sentences. You may also use professional revision services mentioned in the resources section if necessary. Thank you :)

2021-08-19 16:02 UTC, lalith1403 commented on content/articles/getting-started-with-optimization-in-matlab/index.md
> +Here we plot the function using the `plot` function as shown above. Then, we use the while loop to iterate over all the data points in the curve. When the current value is larger than the previous va
Check the changes made to this paragraph. You tend to use a lot of we can and then we. Avoid making it repetitive. See the changes made in this paragraph and make changes accordingly.

2021-08-19 16:02 UTC, lalith1403 commented on content/articles/getting-started-with-optimization-in-matlab/index.md
> +Now let's introduce a more complex function and find its lowest point. In this example, we have a function $ f(x)=x^3-4x $ to use. We will first plot this function and then find its lowest point of t
Avoid repeating yourself. You use just as before twice.

2021-08-19 16:02 UTC, lalith1403 commented on content/articles/getting-started-with-optimization-in-matlab/index.md
> +We will use the `fminsearch` function to find the minimum of our given mathematical function. We will first create a function script in which we will define our function as shown below;
We will is repeated in both the sentences. This makes the article sound boring even though this is a very interesting one.

2021-08-20 09:27 UTC, florenceatieno45 commented
@lalith1403 changes made.

2021-08-23 18:35 UTC, Kayere approved these changes
Congratulations on publishing your first article @florenceatieno45. Please go over the changes made by you peer reviewer and I to help improve the quality of your future articles.

Thank you for the review @lalith1403 🚀.

2021-08-23 18:36 UTC, merged