CSS hacks for web developers
section-engineering-education/engineering-education pull request #3105
Opened 2021-08-01 10:40 UTC by mosesmoses12

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2819

2021-08-01 16:32 UTC, geoffrey45 commented
@mosesmoses12 Welcome to the EngEd program 🎉. Thank you for submitting your article for review.

2021-08-01 20:02 UTC, mosesmoses12 commented
Thanks for the ping @geoffrey45, looking forward to cooperate.

2021-08-02 22:39 UTC, hectorkambow commented
plagiarism check done

2021-08-04 19:43 UTC, geoffrey45 requested changes
@mosesmoses12 Thank you for submitting your article for review. Please check the comments below.

2021-08-04 19:43 UTC, geoffrey45 commented on content/articles/css-hacks-for-web-developers/index.md
> +
This line is ambiguous. Please provide examples of usability troubles that can be caused

2021-08-04 19:43 UTC, geoffrey45 commented on content/articles/css-hacks-for-web-developers/index.md
> +        background-color: black;
In cases where different elements within different classes are the target, this method is not convenient. Please consider using classes and ids for this.

2021-08-04 19:43 UTC, geoffrey45 commented on content/articles/css-hacks-for-web-developers/index.md
> +5. ### How to style Initial Letter using CSS
`How to style the first letter in a paragraph` sounds better

2021-08-05 21:07 UTC, mosesmoses12 commented
@geoffrey45, Am done with the requested changes. Please have a look at my last commit.

2021-08-10 11:56 UTC, geoffrey45 approved these changes

2021-08-10 11:57 UTC, geoffrey45 commented
@mosesmoses12 Please check the changes I made in [this commit](https://github.com/section-engineering-education/engineering-education/pull/3105/commits/ed7c5f6a8bc84f461dbc8a8bec9e866f93cc943c).

Thank you for contributing to the EngEd community.

2021-08-17 20:42 UTC, hectorkambow commented
Overall nice work gents 🚀

2021-08-17 20:42 UTC, hectorkambow commented
Be sure to go over any suggestions / changes made by your peer reviewer to improve future articles.

2021-08-17 20:43 UTC, merged