Uploaded Article
section-engineering-education/engineering-education pull request #3113
Opened 2021-08-01 18:02 UTC by Wkd-Cyber

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixed #2780

2021-08-01 18:26 UTC, Ericgacoki commented
Greetings @Wkd-Cyber,
Welcome to the Eng-Ed program. We're excited to have you onboard. Thank you for submitting your `first` article for review.
Seems like you forgot to add author details 🤭. Please create your author folder in the `/content/authors` directory. This folder holds your author bio and an avatar. Feel free to check how other students have structured theirs.

Ping me when you're done.

2021-08-02 10:17 UTC, Wkd-Cyber commented
Changes done @Ericgacoki 
Please continue with the review

2021-08-02 14:37 UTC, Ericgacoki commented
@Wkd-Cyber, I've made a few changes to improve the flow of your article. Be sure to [take a look](https://github.com/section-engineering-education/engineering-education/pull/3113/commits/edac4624645f579685d3bad885314006840157d1).

2021-08-02 16:27 UTC, Ericgacoki requested changes
Hello @Wkd-Cyber, I've noted a few points that need more clarification to clear any reader's doubts. Generally, try to explain every bit no matter how minor it might seem to be.
Check out the comments attached below.

2021-08-02 16:27 UTC, Ericgacoki commented on content/articles/setting-up-kali-linux-for-dual-boot/index.md
> +We will first download software used to make a pen drive bootable. We'll use `Rufus` in this context. You can download [Rufus here](http://rufus.ie/en_US/).
Could you please explain why you chose `Rufus` over other software?

2021-08-02 16:27 UTC, Ericgacoki commented on content/articles/setting-up-kali-linux-for-dual-boot/index.md
> +
This only happens when the user decides to connect to a WI-FI network. Please clarify that.

2021-08-02 16:27 UTC, Ericgacoki commented on content/articles/setting-up-kali-linux-for-dual-boot/index.md
> +- Set the `Host name` and `Domain name` as you wish - This is an optional step.
Explain to the readers what these terminologies mean.

2021-08-02 16:27 UTC, Ericgacoki commented on content/articles/setting-up-kali-linux-for-dual-boot/index.md
> +Here you have to choose your favorite desktop environment. In my case, I'll' choose the `Xfce (Kali default desktop environment)`.
Remember the reader just installed Kali Linux. They don't have a favorite desktop environment yet. Consider mentioning a few (if not all) environments and their differences.
Try to answer the question - Why this and not the other one?

2021-08-02 16:27 UTC, Ericgacoki commented on content/articles/setting-up-kali-linux-for-dual-boot/index.md
> +
Just before the summary, give general importance of installing a Linux-based OS alongside Windows.

2021-08-04 10:11 UTC, Wkd-Cyber commented
Changes made @Ericgacoki 
Please continue with the review

2021-08-04 13:10 UTC, Ericgacoki approved these changes

2021-08-04 15:42 UTC, Ericgacoki commented
Greetings @Wkd-Cyber, this article will be ready for final review once `plagiarism check` is done.

cc: @hectorkambow.

2021-08-04 20:45 UTC, Ericgacoki commented
@Wkd-Cyber, I've seen the changes ✅

2021-08-10 17:10 UTC, hectorkambow commented
plagiarism check done

2021-08-12 20:59 UTC, kayere approved these changes
Congratulations for publishing your first article @Wkd-Cyber. The article is very easy to follow through. Keep up the good work.

Thank you for the review @Ericgacoki.

2021-08-12 21:00 UTC, merged