searching and sorting in matlab
section-engineering-education/engineering-education pull request #3199
Opened 2021-08-06 14:44 UTC by simonmwaniki

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-08 09:44 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Link your topic-suggestion, please.
Thank you. @simonmwaniki

2021-08-09 10:15 UTC, OMONDIELLY commented
> Good afternoon and thank you for submitting your article for publishing.
> Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
> Make sure to link your topic-suggestion the next time, please.
> Thank you. @simonmwaniki

Hello @ahmadmardeni1 , @hectorkambow . I would like to review this article.

2021-08-09 10:31 UTC, ahmadmardeni1 commented
Go ahead. @OMONDIELLY Please @ me if you have any questions.

2021-08-09 10:41 UTC, OMONDIELLY commented
> Go ahead. @OMONDIELLY Please @ me if you have any questions.

Sure. Thanks

2021-08-10 17:27 UTC, hectorkambow commented
@simonmwaniki 
This article is very light on substance - is it completed?

cc @OMONDIELLY  @ahmadmardeni1

2021-08-10 17:47 UTC, OMONDIELLY commented
> @simonmwaniki
> This article is very light on substance - is it completed?
> 
> cc @OMONDIELLY @ahmadmardeni1

@hectorkambow I have started reviewing it and I guess this is @simonmwaniki first article. We'll see how things flow in due course.
cc @simonmwaniki @ahmadmardeni1

2021-08-10 17:52 UTC, hectorkambow commented
🤔

2021-08-10 17:54 UTC, hectorkambow commented
> > @simonmwaniki
> > This article is very light on substance - is it completed?
> > cc @OMONDIELLY @ahmadmardeni1
> 
> @hectorkambow I have started reviewing it and I guess this is @simonmwaniki first article. We'll see how things flow in due course.
> cc @simonmwaniki @ahmadmardeni1

Understood - but the articles does not seem complete. 

Thank you - let us know what your thoughts are after a review 👍

2021-08-10 17:57 UTC, OMONDIELLY commented
> > > @simonmwaniki
> > > This article is very light on substance - is it completed?
> > > cc @OMONDIELLY @ahmadmardeni1
> > 
> > 
> > @hectorkambow I have started reviewing it and I guess this is @simonmwaniki first article. We'll see how things flow in due course.
> > cc @simonmwaniki @ahmadmardeni1
> 
> Understood - but the articles does not seem complete.
> 
> Thank you - let us know what your thoughts are after a review 👍

Sure. Once I compile all the adjustments needed,  I'll tag @simonmwaniki and you of course.

2021-08-10 18:38 UTC, ahmadmardeni1 commented
Agree with you @hectorkambow. This is a draft, not the full article.

Please only open a PR when your article is fully ready to be reviewed. We can close this PR and open it when you are ready. @simonmwaniki

2021-08-10 19:23 UTC, OMONDIELLY commented
Hey @simonmwaniki , this is a pretty good start. However, there are  changes to be made before we get the review going. 
Kindly note that some sections of your article came off as a bit lightweight and inconsistent. 

Take note of the review comments and be sure to go over the [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page as well.
So first things first:
1. It's advisable to use an image that's as close as possible to 600x400 pixels which will be a cover image to your article.
2. As a new contributor, you'll need to add a brief Author Bio (index.md file) and Headshot image (avatar file). Include these files in the authors folder within the GitHub repo via your forked.
3. Ensure that in your new PR, you add table of contents to show what the article will cover and give readers nice flow.

2021-08-10 19:31 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +Here, we will look at the two closely related problems: Searching and sorting. Both problems appear in applications involving databases, and without efficient solutions to these problems, databases w
Introduce searching and sorting more clearly and how common you find them in databases in order to hook a reader to your article. Kindly elaborate on the 'problems. '

2021-08-10 19:38 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +
After prerequisites, kindly connect the article, maybe use a subheading and build on what you had introduced.
Make the article flowing

2021-08-10 19:48 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +Here, we will look at the two closely related problems: Searching and sorting. Both problems appear in applications involving databases, and without efficient solutions to these problems, databases w
Also minimize repetitions while building your content

2021-08-10 19:52 UTC, OMONDIELLY requested changes

2021-08-10 19:52 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +selection-sort algorithm:
Do simple explanations on your matlab code using comments to help readers understand the code more

2021-08-10 19:56 UTC, OMONDIELLY commented
> Agree with you @hectorkambow. This is a draft, not the full article.
> 
> Please only open a PR when your article is fully ready to be reviewed. We can close this PR and open it when you are ready. @simonmwaniki
> cc @OMONDIELLY

I think it will be okay if the PR is closed and @simonmwaniki to open a new one once he has made all the adjustments with the article fully ready.
@hectorkambow kindly advise.

2021-08-10 19:57 UTC, OMONDIELLY commented
Feel free to ping me incase of any issue @simonmwaniki .

2021-08-11 10:44 UTC, ahmadmardeni1 commented
I'm going to close it to clear the queue, please @ me when it is fully ready to be reviewed and I will re-open it again. @simonmwaniki 
cc @OMONDIELLY

2021-08-13 14:03 UTC, ahmadmardeni1 commented
Hey @simonmwaniki 👋 You @ me in your topic suggestion. I still think this PR is not ready to be reviewed, there is no conclusion here.

2021-08-15 09:53 UTC, ahmadmardeni1 commented
I reopened the PR. Please commit the changes you told me about. Also, add a hero image and the author's info. @simonmwaniki

2021-08-16 18:43 UTC, hectorkambow commented
plagiarism check done

2021-08-16 19:56 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +Searching is the process of locating a given object or data within a large number of data. Sorting is the arrangement of data in a specific required order. These algorithms are used in the computer d
```suggestion
Searching is the process of locating a given object or data within a large set of data. Sorting on the other hand, is the arrangement of data in a specific required order. 
These algorithms are commonly used in databases and other computer applications. A computer database is where all the computer data is stored. In the absence of searching and sorting algorithms, locating data in the computer is likely to take a lot of time; thus, these algorithms simplify this process and minimize the time search and sorting. (**how is this a bad thing? make it more clear. Other than time, how does it affect computing?** ).
There are various applications of searching and sorting, but the primary application is locating data within a given vector similar to the target.
```

2021-08-16 20:37 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +The main target of the search is the uniqueness of the data. For example, if you go to a bank, they ask for your bank number to get your bank account. It is made possible by search algorithms. There
```suggestion
The main target of the search is the uniqueness of the data. For example, if you visit bank, the process of retrieving your account details is made possible by searching algorithms. There are two types of search algorithms. These are;
```

2021-08-16 20:37 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +It is also known as linear search. Here, the target variable is compared to the entire vector or stop in a variable similar to the target. For example, we are given a vector and a target value to loc
```suggestion
It is also known as linear search.  (Define sequential search independently or give a link with  a more detailed definition) 
Here, the target variable is compared to the entire vector space (briefly define vector space) or stop in a variable similar to the target. For example, we are given a vector space and a target value to locate. 

First, we should identify the target value within this vector. If we find a similar variable, we give its index as the output, and if we fail to find, we provide an impossible index as the output. This impossible index could be something like -1. It is to show that the value is not found.
Below is a sample code that implements searching in matlab.
```

2021-08-16 20:37 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +### 2. Binary search
Kindly explain more on binary search or link an article with more explanation. Maybe how binary search operates.
Also avoid using the word 'here' and 'it' , find an alternative that gives your article more command and style.

Do pass your article on Grammarly to help you remove the passive voices and repetitions.

2021-08-16 20:39 UTC, OMONDIELLY commented
> plagiarism check done

Great, @simonmwaniki kindly work on the adjustments and other changes to get your article going.

2021-08-16 20:46 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +### Sorting
Just like searching, add a bit more details or link to where a reader can find more.

2021-08-16 20:46 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +It is the most efficient type of sort and also easy to understand.
I find this a bit loose and ambiguous, please give a reader a clear description of quick sort. Just briefly.

2021-08-16 20:46 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +It is the most efficient type of sort and also easy to understand.
Also before you proceed to code sample, introduce a reader on what you are trying to do or achieve.

2021-08-16 20:46 UTC, OMONDIELLY commented on content/articles/searching-and-sorting-in-matlab/index.md
> +Generally, this quicksort divides the data into three parts: v (1), smaller, and remainder. v(1)is the first value in the vector. Smaller is a list consisting of all vectors less than v(1), while the
I think a reader would find this difficult to follow, kindly break it down.

2021-08-16 20:50 UTC, OMONDIELLY commented
@simonmwaniki , You can also check articles written by other authors in your local repository for correct article introduction, folder structure , author details.
Feel free to message me in slack in case of any issue.
cc @ahmadmardeni1  @hectorkambow

2021-08-19 11:11 UTC, simonmwaniki commented
@OMONDIELLY changes made

2021-08-19 11:49 UTC, OMONDIELLY commented
Great @simonmwaniki, I'm happy to see that you have made the requested improvements. 
cc @ahmadmardeni1 , @hectorkambow.
I'll be doing my last round of revisions. Stay in the loop.

2021-08-19 11:50 UTC, OMONDIELLY approved these changes
updates

2021-08-19 13:19 UTC, simonmwaniki commented
Ok, and how do you call yourself in slack? am trying to find but i can't.

2021-08-22 19:47 UTC, OMONDIELLY commented
@ahmadmardeni1 , @hectorkambow kindly note that I have completed my round of revision.

2021-08-25 16:35 UTC, hectorkambow commented
Please be sure to go over all the edits made by our peer reviewer and myself.  @simonmwaniki 
This article was very difficult to go through and made many edits in order to publish. 

Please review our resources as well to improve future articles and reviews. 

Please - only submit polished articles ready to publish. You can work on them on your forked repo and only create a PR when it is ready. 


cc @OMONDIELLY  @ahmadmardeni1

2021-08-25 16:36 UTC, merged

2021-08-25 16:49 UTC, OMONDIELLY commented
> Please be sure to go over all the edits made by our peer reviewer and myself. @simonmwaniki
> This article was very difficult to go through and made many edits in order to publish.
> 
> Please review our resources as well to improve future articles and reviews.
> 
> Please - only submit polished articles ready to publish. You can work on them on your forked repo and only create a PR when it is ready.
> 
> cc @OMONDIELLY @ahmadmardeni1

Great suggestions here.