Cryptanalysis of data after a ransomware attack
section-engineering-education/engineering-education pull request #3203
Opened 2021-08-06 20:48 UTC by RuthAMare

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-06 21:05 UTC, Sajeyks commented
Hello @RuthAMare. I shall be reviewing your pr 
cc @hectorkambow

2021-08-07 04:42 UTC, RuthAMare commented
Hey @Sajeyks
Okay

2021-08-08 21:35 UTC, Sajeyks reviewed
Everything looks good, you just have to make a few changes and your article will be ready.

2021-08-08 21:35 UTC, Sajeyks commented on content/articles/cryptanalysis-of-data-after-a-ransomware-attack/index.md
> +- [What is cryptanalysis?](#what-is-cryptanalysis?)
Please remove the question mark in your link description as it is breaking the link.

2021-08-08 21:42 UTC, Sajeyks commented
this fixes #2996

2021-08-08 22:19 UTC, Ericgacoki commented
> In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states "This fixes #(enter your Idea Content Form #)" to link and close your Idea Content (issue) when the PR is merged.
> 
> To help you do it the right way, take a [look](https://github.com/section-engineering-education/engineering-education/pull/3161#issue-703326896) at how other contributors have added theirs.

@Sajeyks, I linked the issue when I came across the first version of this comment.

2021-08-09 05:46 UTC, RuthAMare commented
hey @Sajeyks 
Changes requested have been made.

2021-08-09 11:47 UTC, Sajeyks commented
@RuthAMare it also seems like your PR contains two different articles and hero images respectively. I suggest you get rid of the other article that seems to have been published already.

2021-08-09 11:51 UTC, Sajeyks commented on content/articles/cryptanalysis-of-data-after-a-ransomware-attack/index.md
> +Cryptanalysis is a technique that has been majorly applied to helping find weaknesses in cryptographic algorithms and improve on them to make encryption robust to threats. Cryptanalysis can, however,
U forgot to change malicious

2021-08-10 08:52 UTC, RuthAMare commented
@Sajeyks Spelling has been corrected and the previous PR deleted

2021-08-10 12:11 UTC, Sajeyks commented
> @Sajeyks Spelling has been corrected and the previous PR deleted

Seems like You forgot to remove the 3 images that belong to the previous article as well.

2021-08-10 17:30 UTC, RuthAMare commented
@Sajeyks seems it's not possible to delete the images on my end

2021-08-10 17:34 UTC, RuthAMare commented
It worked, I guess.
It's done @Sajeyks

2021-08-10 17:36 UTC, hectorkambow commented
plagiarism check done

2021-08-11 10:35 UTC, Sajeyks commented
> It worked, I guess.
> It's done @Sajeyks

Great job @RuthAMare

2021-08-11 17:51 UTC, srishilesh commented
Moving for the final review as requested by the test peer reviewer.

Cc. @Sajeyks @RuthAMare

2021-08-12 16:08 UTC, srishilesh requested changes
Hey @RuthAMare 

Could you please commit these changes as well?

@Sajeyks Please make note these suggestions.

2021-08-12 16:08 UTC, srishilesh commented on content/articles/cryptanalysis-of-data-after-a-ransomware-attack/index.md
> +topics: []
```suggestion
topics: [Security]
```

2021-08-12 16:08 UTC, srishilesh commented on content/articles/cryptanalysis-of-data-after-a-ransomware-attack/index.md
> +The possible decryption algorithms will also be identified to be able to help the reader know their possible go-to option when they fall prey to a ransomware attack.
```suggestion
description: This article seeks to explore the concept of cryptanalysis in light of data encrypted by a malicious actor seeking ransom to decrypt the data. The process of cryptanalysis will be clearly outlined, highlighting the various ethical ways to do the same putting into consideration the possible cryptographic algorithm that may have been employed in encrypting the data.
```

2021-08-12 16:08 UTC, srishilesh commented on content/articles/cryptanalysis-of-data-after-a-ransomware-attack/index.md
> +---
```suggestion
---
Peer Review Contributions by: [Samuel Mwangi](/engineering-education/authors/samuel-mwangi/)
```

2021-08-12 19:55 UTC, RuthAMare commented
Hey @srishilesh 
Changes commited.

2021-08-23 10:37 UTC, ahmadmardeni1 commented
Great work ladies and gentlemen @RuthAMare @Sajeyks @srishilesh 

Please go through the minor changes I made.

2021-08-23 10:37 UTC, merged