Getting started with decorators in python
section-engineering-education/engineering-education pull request #3256
Opened 2021-08-10 10:25 UTC by mia-roberts

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-10 10:27 UTC, mercymeave commented
@mia-roberts  I will be reviewing this PR for my second test-review.

Can someone add me the labels please?

@ahmadmardeni1 , @hectorkambow

2021-08-10 10:28 UTC, mia-roberts commented
This fixes #2718

2021-08-10 10:44 UTC, mercymeave commented
Thank you Erick :wink:

2021-08-10 10:46 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +Appreciating that everything in Python programming comes as an object is a key to understanding this concept. The reader should be well conversant with Python, although the explanations are simple an
```suggestion
Appreciating that everything in Python programming comes as an object is a key to understanding this concept. The reader should be well conversant with Python, although the explanations are simple and precise for beginners.
```

2021-08-10 10:53 UTC, mercymeave requested changes
Hello @mia-roberts 

Thank you for submitting your article for review. Upon conducting a prelimiary review, I noticed some minor mistakes and sugggeted corrections on the same.

Secondly, ensure that the hero image for the article is 600*400 pixels.


Kindly go through the suggestion and make appropriate changes then we move foraward.

2021-08-10 10:53 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +Appreciating that everything in Python programming comes as an object is a key to understanding this concept. The reader should be well conversant with Python, although the explanations are simple an
Make this point to come out clear  to the reader.

2021-08-10 10:53 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +- A working installation of Python on your computer
Add python download link.

2021-08-10 10:53 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +The concept of Python decorators is unclear to many people, even though it's simple. For this reason, you can consider Python decorators as high-level functions in Python which that takes another fun
Python dcorators being unclear is not a reason to make it a high level function.  Give a good reason as to why moajority of programmers do not understand python decorators.

2021-08-10 10:53 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +Sometimes we will need to define a decorator function that accepts parameters. We can achieve this by passing the parameters to the wrapper function, which we then pass to the function that is being
```suggestion
Sometimes we may need to define a decorator function that accepts parameters. We can achieve this by passing the parameters to the wrapper function, which we then pass to the function that is being decorated.
```

2021-08-10 10:53 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +Python allows the use of multiple decorators together. This process involves decorating a single function more than once with the same or different decorators. To use several decorators, we place the
```suggestion
Python allows the use of multiple decorators together. This process involves decorating a single function more than once with the same or different decorators.

  To use several decorators, we place the decorators just above the desired function. Python automatically does the chaining of the decorators. 
```

2021-08-10 12:22 UTC, mia-roberts commented
@mercymeave I have made the changes, kindly take a look.

2021-08-10 12:26 UTC, mercymeave approved these changes
Well done, I will proceed to tech review.

One of the content moderators will remove the revisions label.

@ahmadmardeni1 , @Ericgacoki

2021-08-10 12:28 UTC, mercymeave commented
Thanks Erick

2021-08-10 14:33 UTC, mercymeave commented
@mia-roberts , your article looks amazing with easy to follow snippets. One more thing before we finalize, add a table of content for easy navigatrion of your article.

2021-08-10 18:06 UTC, mia-roberts commented
@mercymeave, updated, kindly check it out.

2021-08-10 18:07 UTC, mercymeave commented
On it.

2021-08-10 18:10 UTC, mercymeave requested changes
@mia-roberts, Make the minor corrections then the article will be ready for final review.

2021-08-10 18:10 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +- [Passing parameters to decorators](#passing-parameters-to-ecorators)
```suggestion
- [Passing parameters to decorators](#passing-parameters-to-decorators)
```

2021-08-10 18:10 UTC, mercymeave commented on content/articles/python-decorators/index.md
> +As observed, decorators wrap functions. The original function and its parameter are all masked by the wrapper. This issue poses a challenge on debugging and calls for the need to solve this challenge
```suggestion
As observed, decorators wrap functions. The original function and its parameter are all masked by the wrapper. This issue poses a challenge on debugging and calls for the need to solve this challenge. 

However, Python provides a `functools.wraps()` decorator that copies the metadata from the undecorated function to the decorated wrapper function. Let's see how to do this.
```

2021-08-10 18:20 UTC, hectorkambow commented
plagiarism check done

2021-08-10 18:29 UTC, mercymeave approved these changes

2021-08-10 18:31 UTC, mercymeave commented
@mia-roberts  An amazing article :clap: 

In your coming articles, be sure to go over the minor suggestios and edits to polish them even further. Your articel is ready for final review.

@hectorkambow , @ahmadmardeni1, Would you please add me the PRC line and concuct a final review on this PR.

Thanks

2021-08-10 19:29 UTC, mercymeave commented
@ahmadmardeni1 , You missed my name when you added the PRL. :smile:  Its Mercy Meave

2021-08-10 20:09 UTC, ahmadmardeni1 commented
Oh I'm so sorry! I copied the line and forgot to edit the first part. @mercymeave

2021-08-11 14:58 UTC, hectorkambow commented
> Oh I'm so sorry! I copied the line and forgot to edit the first part. @mercymeave

Happens from time to time 👍  

😄

2021-08-11 15:39 UTC, mia-roberts commented
@mia-roberts I think i must have missed it when making edits.

It is fine now.

2021-08-11 17:51 UTC, hectorkambow commented
Overall great work @mia-roberts - very easy to follow along 🚀 

cc @mercymeave

2021-08-11 17:52 UTC, merged