How to migrate an on-prem application to serverless?
section-engineering-education/engineering-education pull request #3265
Opened 2021-08-10 16:59 UTC by ogoti-lilian

The article covers the following:
the problems faced with on-prem applications and why opt for seeverless way, the journey to serverless solution and the migration approach from on-prem to serverless using practical example, and the challenges likely to faced during development and delivery phase.

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-10 17:01 UTC, ogoti-lilian commented
This solves issue #2968

2021-08-13 11:47 UTC, Ericgacoki commented
Hello @ogoti-lilian, this article is well written and flows well. However, be sure to check out the [changes that I made](https://github.com/section-engineering-education/engineering-education/pull/3265/commits/d7402ddbc1de1e63c1991c7e537e5e5f237a50a1).

2021-08-13 11:51 UTC, Ericgacoki requested changes
I have one suggestion at the moment...

2021-08-13 11:51 UTC, Ericgacoki commented on content/articles/how-to-migrate-an-on-prem-application-to-serverless/index.md
> +It is usually a good idea to start small, rather than waiting for one big move. These incremental steps allow the developers to learn from their past mistakes, iterate, and try again. It is not a goo
Please paraphrase the first sentence.

2021-08-13 13:58 UTC, Ericgacoki commented
@ogoti-lilian, resize your hero image to `600 X 400px`

2021-08-13 14:05 UTC, ogoti-lilian commented
> Hello @ogoti-lilian, this article is well written and flows well. However, be sure to check out the [changes that I made](https://github.com/section-engineering-education/engineering-education/pull/3265/commits/d7402ddbc1de1e63c1991c7e537e5e5f237a50a1).

Thank you. I have noted the changes you made and I will improve on the next article.

2021-08-13 14:06 UTC, ogoti-lilian commented
@Ericgacoki The changes requested have been made.
Thank you

2021-08-13 14:10 UTC, Ericgacoki approved these changes

2021-08-13 14:14 UTC, Ericgacoki commented
Seems like you have decided to change your author image. Well, you may proceed.🤗

2021-08-13 14:18 UTC, ogoti-lilian commented
> @ogoti-lilian, resize your hero image to `600 X 400px`

Sorry for the confusion the requested change has been made.
Thank you

2021-08-13 14:19 UTC, ogoti-lilian commented
> Seems like you have decided to change your author image. Well, you may proceed.🤗

@Ericgacoki It was a slight mistake but I have rectified it. 
Thank you

2021-08-13 14:21 UTC, Ericgacoki commented
No problem. It happens from time to time 😀
Remember to upload a better `hero` image :rocket:

2021-08-16 21:31 UTC, hectorkambow commented
plagiarism check done

2021-08-21 15:01 UTC, Kayere commented
Great article @ogoti-lilian - very informative and easy to follow through.
Thank you for the awesome review @Ericgacoki.

2021-08-21 15:02 UTC, merged