Image Compression using PCA
section-engineering-education/engineering-education pull request #3267
Opened 2021-08-10 18:39 UTC by DeewakarChakraborty

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
     
This fix is #3200     

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-15 13:51 UTC, lalith1403 requested changes
Hello @DeewakarChakraborty, Welcome to the Section EngEd Program. This is an amazing article. I thoroughly enjoyed reading through the article. It challenged me on various levels thus leading to greater learning objectives being met. Kudos to a fantastic first article. Look forward to many more! 

There are a few minor changes required on your end. Consider making them and ping me once done. 

Cheers,

Lalith

2021-08-15 13:51 UTC, lalith1403 commented on content/articles/image-compression-using-PCA/index.md
> +![first-graph](plot-1.png)
All images go with the following URL:

\[alt text\]\(/engineering-education/image-compression-using-PCA/image.type\)

2021-08-15 13:51 UTC, lalith1403 commented on content/articles/image-compression-using-PCA/index.md
> +![image2](plot-2.jpg)
Same here as well

2021-08-15 13:51 UTC, lalith1403 commented on content/articles/image-compression-using-PCA/index.md
> +Principal Component Analysis, PCA, is a dimensionality reduction method used to reduce the dimensionality of a dataset by transforming the data to a new basis where the dimensions are non-redundant(l
Explain the basic terminologies used in Linear Algebra:

1. row/column vectors
2. basis 
3. covariance
and other terms used.

2021-08-15 13:51 UTC, lalith1403 commented on content/articles/image-compression-using-PCA/index.md
> +#### Desideratum
This heading may not be followed by everyone. Can you modify this?

2021-08-15 13:51 UTC, lalith1403 commented on content/articles/image-compression-using-PCA/index.md
> +#### Orthogonal  Transformation
Remove additional space

2021-08-16 21:44 UTC, hectorkambow commented
plagiarism check done

2021-08-23 15:33 UTC, lalith1403 requested changes
Modification is required in equations. Can you change them to Latex equations? Refer to this [PR.](https://github.com/section-engineering-education/engineering-education/pull/3101) Look at the inline equations used and replicate the same.

2021-08-23 15:33 UTC, lalith1403 commented on content/articles/image-compression-using-PCA/index.md
> +`x<sub>i</sub> = &prop;<sub>i1</sub>p<sub>1</sub> + &prop;<sub>i2</sub>p<sub>2</sub> + ....... + &prop;<sub>in</sub>p<sub>n</sub>`
This is how this equation is in preview. 
![image](https://user-images.githubusercontent.com/26842636/130475012-29e4bb51-c964-4a5f-8cc4-2c7ab8085e5a.png)

You will have to use in-line Latex for all the equations.

2021-08-30 15:23 UTC, hectorkambow commented
@lalith1403  

Just wanted to get a status on this PR?

2021-08-30 20:11 UTC, hectorkambow commented
Overall great work 👍 

Made some changes for format and flow
Please review to improve future articles and reviews. 

Please refrain from using HTML syntax - refer to any markdown for proper syntax 👍 

cc @lalith1403

2021-08-30 20:11 UTC, merged