Building a simple translation app using Python for beginners
section-engineering-education/engineering-education pull request #3272
Opened 2021-08-11 01:51 UTC by smkinyan

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

This fixes #3227.      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-11 01:53 UTC, smkinyan commented
This fixes #3227

2021-08-11 03:38 UTC, bloodprashure commented
@hectorkambow I'd like to test-review this article.

2021-08-15 14:28 UTC, smkinyan commented
Hi @bloodprashure What's the progress with this PR?

2021-08-15 16:48 UTC, bloodprashure reviewed
Hey @smkinyan, the review will be complete in 24 hours.
Thanks!

2021-08-15 16:48 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +Want to build your very own language translation app?
Please add the front matter to this article. You can find one [here](https://raw.githubusercontent.com/section-engineering-education/engineering-education/master/content/articles/boosting-algorithms-python/index.md) and edit yours according to that.

2021-08-15 16:48 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +
Do remove the whitelines between the headers and the paragraphs.

2021-08-15 16:48 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +To understand the contents of this tutorial, a reader needs to be familiar with the Python programming language and machine learning. I'm also going to be using [Google Colab](https://colab.research.
Do link external resources for Python and machine learning. You could also link a few articles on machine learning from the Section community itself. If you do decide to do so, the format is as follows:
```
[text](engineering-education/boosting-algorithms-python/)
```
Also, I can see that you've used PyTorch. So, do link a few PyTorch resources as well.

2021-08-15 16:48 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +```
This could be in a bash code block.

2021-08-15 16:48 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +```
This could be put in a bash codeblock as well. Also, the actual command need not be indented.

2021-08-16 22:03 UTC, hectorkambow commented
plagiarism check done

2021-08-17 19:12 UTC, bloodprashure requested changes
Hey @smkinyan! 
This is a great draft! Do make the requested changes so that we can move forward to the tech review.
Thanks!

2021-08-17 19:12 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +
This section can be a bit confusing to the reader as you've mentioned at the end of the section which ones to install and which ones not to. If you could shift that to the beginning of the paragraph and ensure that a reader would be able to grasp which code blocks to run on his machine and which code blocks to run on the Colab notebook, it'd be much better.

2021-08-17 19:12 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +> An important point to note is that recently, Google Colab comes pre-installed with PyTorch. You may need to ignore the PyTorch installation if you're using Colab. Only follow the steps if installin
This is what I was talking about in the previous comment.

2021-08-17 19:12 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +```
Do mention in a sentence that this command can both be used in the Command Prompt for a local machine and can be run as a cell in the Colab notebook.

2021-08-17 19:12 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +
As mentioned before, add a brief section about the model and what a pipeline is before using it.

2021-08-18 08:20 UTC, smkinyan commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +Well, in this tutorial, I'll show you how you can build one yourself using Hugging Face Transformers and Gradio!
The Front matter and Peer review lines are added by the peer reviewer and not the author.

2021-08-18 08:23 UTC, smkinyan commented
Let me make the requested changed. However, on the bit about the front matter, it is usually added by the peer reviewer, not the author.

2021-08-18 08:25 UTC, bloodprashure commented
> Let me make the requested changed. However, on the bit about the front matter, it is usually added by the peer reviewer, not the author.

It is, yeah. But since I'm not a peer reviewer yet, I do not have the permissions to edit a PR. I can only do inline Github comments.
Hope you understand.
Thanks!

2021-08-18 09:33 UTC, smkinyan commented
> > Let me make the requested changed. However, on the bit about the front matter, it is usually added by the peer reviewer, not the author.
> 
> It is, yeah. But since I'm not a peer reviewer yet, I do not have the permissions to edit a PR. I can only do inline Github comments.
> Hope you understand.
> Thanks!

Okay. No problem

2021-08-18 11:16 UTC, smkinyan commented
@bloodprashure I'm done making the requested changes.

2021-08-21 12:30 UTC, smkinyan commented
@bloodprashure What's the progress with this article?

2021-08-21 18:29 UTC, bloodprashure requested changes
Hey @smkinyan, the tech review is complete. Please make the suggested changes so that we can move the article to the final review.
Thanks!
@hectorkambow This might need another plagiarism check as a bit of content has been added.

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +Hugging Face is a great open-source library that is doing powerful work in the Natural Language Processing (NLP) space. The library has a bunch of pre-trained models which you can leverage or fine-tu
Please add one external resource each for BERT, GPT-2 and GPT, and edit "but for our case" to "but for our purpose"

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +[Gradio](https://gradio.app/), on the other hand, allows us to quickly create customizable UI components around PyTorch models. It allows you to create interfaces for your ML models. It helps you qui
Capitalize the "g" in "gradio", and edit the last sentence to "The reader is encouraged to take a look at the examples in the documentation for better understanding."

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +    pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
The code has unnecessary indentations (the initial spaces). Please remove them in all the code blocks in the draft.

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +`gradio` gives you a nice way to demonstrate and interact with your ML model.
The point-of-view used seems to be inconsistent. The first sentence uses "us" whereas the second and the third uses "you". Please choose one (first person or second person) and stick to that for the entire article. Please make all necessary changes in the entire draft.

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +Hugging Face has many Transformer pipelines. You can check them on this [documentation](https://huggingface.co/transformers/main_classes/pipelines.html). For our tutorial, we will select the `Transla
1. The "T" in "Transformer" need not be capitalized. 
2. Add a comma after `TranslationPipeline`.
3. Remove the word "the" in the phrase "that allows the translation from one language to another"
4. The fullstop must be replaced with a comma in the phrase "to translate. `xx` being the language..."
5. Please replace the word "experiment" with an appropriate word.

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +We create the gradio interface by writing following pieces of code:
Capitalize gradio in this sentence (Gradio)

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +
You can remove the source of the image as it is your own and not an external source.

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +
This can be removed as well.

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +This tutorial gives us an idea of how one can build a simple translation app. We installed our dependencies, loaded our translation model, and finally used gradio to build our user interface. This is
"Machine Learning" can be replaced with "machine learning", and capitalize the word "french"

2021-08-21 18:29 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +You can find the full implementation of the code on this tutorial on my [Colab](https://colab.research.google.com/drive/1MMgN89Xn7fz5zVh1XCuLd66ZBIoZ70DZ#scrollTo=62a4vvW_dLsx).
Change it to "on my [Colab notebook]"

2021-08-22 06:17 UTC, smkinyan commented
@bloodprashure I've made the changes. I've requested @Bayler to help you add the necessary labels to help this process go faster.

2021-08-22 06:47 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +This web app allows a user to pass through some text and have it translated.
Do add a few sentences about what a web-app is and link an external resource or two to it.

2021-08-22 06:49 UTC, bloodprashure reviewed
@smkinyan Thanks for making the requested changes! I've asked for one more, my apologies for not mentioning it in the previous review.
@hectorkambow This article is ready for the final review.

2021-08-22 16:14 UTC, smkinyan commented
> @smkinyan Thanks for making the requested changes! I've asked for one more, my apologies for not mentioning it in the previous review.
> @hectorkambow This article is ready for the final review.

@bloodprashure done.

2021-08-22 17:06 UTC, Bayler commented
Hi @bloodprashure I've helped you put the necessary labels and added the PRC line for you. If you need any other assistance, Please let me know.

2021-08-22 17:19 UTC, bloodprashure requested changes

2021-08-22 17:19 UTC, bloodprashure commented on content/articles/building-a-simple-translation-app-using-python-for-beginners/index.md
> +
Please indent the code.

2021-08-22 17:19 UTC, bloodprashure commented
@hectorkambow The article is ready for the final review.
Cc @Bayler

2021-08-22 17:30 UTC, hectorkambow commented
plagiarism check done

2021-08-22 17:36 UTC, bloodprashure commented
@hectorkambow The article is ready for the final review
Cc @Bayler

2021-08-22 17:36 UTC, bloodprashure approved these changes

2021-08-26 10:52 UTC, merged