HOSTING A WEBSERVER USING A RASPBERRYPI
section-engineering-education/engineering-education pull request #3282
Opened 2021-08-11 18:13 UTC by eunice-wanjiku

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-11 18:56 UTC, WanjaMIKE commented
@eunice-wanjiku 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2021-08-14 19:02 UTC, Dawe-7 reviewed
Hello @eunice-wanjiku - Welcome to Section's engineering education program. I'll be reviewing your article. Before we begin the review, i need you to make the following changes:
1. Use subheadings format for listing the steps. Use `###` for headings and `####` or lower for subheadings.  The steps heading should give a brief description of what is happening in each step. Take a look at this [tutorial](https://github.com/section-engineering-education/engineering-education/pull/1250/files) to understand this better.
2. I also noticed some of your images are in the correct file format but are in capital. 
As soon as you make the changes we'll begin the review. Also revisit your article one more time to make the review process faster.

2021-08-14 20:43 UTC, eunice-wanjiku commented
> Hello @eunice-wanjiku - Welcome to Section's engineering education program. I'll be reviewing your article. Before we begin the review, i need you to make the following changes:
> 
> 1. Use subheadings format for listing the steps. Use `###` for headings and `####` or lower for subheadings.  The steps heading should give a brief description of what is happening in each step. Take a look at this [tutorial](https://github.com/section-engineering-education/engineering-education/pull/1250/files) to understand this better.
> 2. I also noticed some of your images are in the correct file format but are in capital.
>    As soon as you make the changes we'll begin the review. Also revisit your article one more time to make the review process faster.

@Dawe-7 Done

2021-08-16 22:04 UTC, hectorkambow commented
plagiarism check done

2021-08-17 14:02 UTC, Dawe-7 commented
> > Hello @eunice-wanjiku - Welcome to Section's engineering education program. I'll be reviewing your article. Before we begin the review, i need you to make the following changes:
> > 
> > 1. Use subheadings format for listing the steps. Use `###` for headings and `####` or lower for subheadings.  The steps heading should give a brief description of what is happening in each step. Take a look at this [tutorial](https://github.com/section-engineering-education/engineering-education/pull/1250/files) to understand this better.
> > 2. I also noticed some of your images are in the correct file format but are in capital.
> >    As soon as you make the changes we'll begin the review. Also revisit your article one more time to make the review process faster.
> 
> @Dawe-7 Done

@eunice-wanjiku, Kindly revisit the suggestions once more because i can see some of the changes requested have not been implemented. Also, revisiting your article and making changes where necessary will make the review process faster. Consider using the [hemimgway editor](https://hemingwayapp.com/) and [grammarly](https://www.grammarly.com/) to polish up your article.

2021-08-18 05:14 UTC, eunice-wanjiku commented
@Dawe-7 Kindly check the updated files. I have uploaded the revision as requested

2021-08-19 13:51 UTC, Dawe-7 requested changes
@eunice-wanjiku, I've left you a few suggestions which will improve the quality of your article. Consider making the changes and we can move on to the next step. Also, identify your terminal commands output as `bash`. I have illustrated that in `step 2` so you understand and do the same for the rest of the commands. Adding some more content in your conclusion will also be helpful.

2021-08-19 13:51 UTC, Dawe-7 commented on content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
> +You can create a local Pi webserver to deliver various contents while you are continuously surfing over the internet. To make the webserver operational, the Raspberry Pi should be connected to the lo
```suggestion
You can create a local Pi webserver to deliver various contents while you are surfing over the internet. To make the webserver operational, the Raspberry Pi should be connected to the local network.  And, ensured that it has the latest version of the operating system of **Raspbian**. These are the defined instructions that you need for any model to work even on the pocket-sized Raspberry Pi Zero W and the very powerful Raspberry Pi 4.
```

2021-08-19 13:51 UTC, Dawe-7 commented on content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
> +For the reader to follow through and be guided accordingly, they are assumed to have an installed operating system with the Pixel window manager. In summary, you need to have;
```suggestion
For the reader to follow through, they are assumed to have an installed operating system with the Pixel window manager. In summary, you need to have:
```

2021-08-19 13:51 UTC, Dawe-7 commented on content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
> +Note: When prompted to change the root password, please choose a strong password for MySQL and make sure to write it down somewhere you can refer to later on.
```suggestion
>Note: When prompted to change the root password, please choose a strong password for MySQL. Make sure to write it down somewhere you can refer to later on.
```

2021-08-19 13:51 UTC, Dawe-7 commented on content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
> +In this step, we will make sure that the available packages in our Raspberry pi are updated by typing the below command into the Terminal. This ensures you have the current versions of any file you d
```suggestion
In this step, we will make sure that the available packages in our Raspberry pi are updated by typing the command below into the Terminal. This ensures you have the current versions of any file you download afterwards.
```

2021-08-19 13:51 UTC, Dawe-7 commented on content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
> +Note: When prompted to change the root password, please choose a strong password for MySQL and make sure to write it down somewhere you can refer to later on.
```suggestion
>Note: When prompted to change the root password, please choose a strong password for MySQL. Make sure to write it down somewhere you can refer to later on.
```

2021-08-20 08:00 UTC, eunice-wanjiku commented
@Dawe-7 Adjusted the article as requested. Kindly verify

2021-08-20 09:56 UTC, Dawe-7 approved these changes
@eunice-wanjiku, Thanks for the changes, the article looks great.

@hectorkambow, this article is ready for final review.

2021-08-20 17:25 UTC, ahmadmardeni1 commented
Congrats on your first article and welcome to Section EngEd 🎉 @eunice-wanjiku
Please go through the changes I made @eunice-wanjiku @Dawe-7 

Thank you for the review @Dawe-7

2021-08-20 17:25 UTC, merged