Getting Started with Image Preprocessing in python
section-engineering-education/engineering-education pull request #3306
Opened 2021-08-13 03:42 UTC by FREDERICO23

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #3188

2021-08-15 14:02 UTC, lalith1403 commented
Hello @FREDERICO23. There are several grammatical errors and many paragraphs that are tough to comprehend. Kindly check and change them. Once done, ping me.

2021-08-16 22:50 UTC, hectorkambow commented
plagiarism check done

2021-08-17 02:43 UTC, FREDERICO23 commented
@lalith1403 Revisions done

2021-08-19 16:44 UTC, lalith1403 requested changes
Very well-written article. Explain why the techniques work. How would data augmentation help? Why would random transformation to images help?

2021-08-19 16:44 UTC, lalith1403 commented on content/articles/image-preprocessing-in-python/index.md
> +#### Normalization
Explain why normalization works! Why would rescaling [0,255] to [-1,1] or [0,1] help? How would it help? Do this for all the techniques mentioned.

2021-08-22 07:23 UTC, FREDERICO23 commented
Changes Done

2021-08-23 15:38 UTC, lalith1403 commented
Hello @FREDERICO23. I had made a lot of changes in the earlier commit. You have updated the changes without pulling my changes. Please can you consider pulling the changes made in my commit and then push your changes.

2021-08-30 15:24 UTC, hectorkambow commented
@lalith1403 
Can we get a status on this PR

2021-08-31 18:39 UTC, WanjaMIKE commented
Nice article @FREDERICO23. Good review @lalith1403

2021-08-31 18:40 UTC, WanjaMIKE commented
Merged #3306

2021-08-31 18:40 UTC, merged