Cloud Management
section-engineering-education/engineering-education pull request #3363
Opened 2021-08-15 22:37 UTC by kwennB

Cloud management caters to products and services. It allows the operations of the kinds of cloud infrastructure. Also, it manages products and services, including its flexibility. The scalability, security, and adaptation when the wants arise.

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-16 07:31 UTC, OMONDIELLY commented
I'll like to review this article @hectorkambow.

2021-08-21 12:37 UTC, srishilesh requested changes
@kwennB 

Nice article.

I've suggested a few changes on formatting and enhancements. Please ping me when done.

Thanks.

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +In this article, we will discuss how cloud management and understand what there is to know about it.
You could start with a more descriptive introduction.

Why does the reader want to know about cloud management? What is it? How will it help the reader?  Then, share the goals/objectives of this tutorial

You must make the reader feel interested about this article.

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +### Table of Contents
```suggestion
### Table of contents
```

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +- Functionalites of a decent cloud manager
Add clickable links. Refer to my articles to understand them better.

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +In this article, we will discuss how cloud management and understand what there is to know about it.
Start with cloud. Explain how apps migrated from local to cloud.

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +### Cloud Management
Before you get into this topic, state about the current scenario.

Explain the current drawback. What's the need to manage? 

Don't just state facts. Walk the reader through the problem, and give a solution

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +**Cost Management**
Convert them into sub-topics with headers `####`

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +**Cost Management**
Do the same for below sub-topics too

2021-08-21 12:37 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +Thank you for reading!
Add a reference links for further reading

2021-08-21 16:07 UTC, kwennB commented
Thank you for the feedback @srishilesh 
I will see to requested changes.

2021-08-22 16:30 UTC, hectorkambow commented
@kwennB 
Upon a quick glance this article seem rather light on substance. 

cc @srishilesh

2021-08-22 16:30 UTC, hectorkambow commented
plagiarism check done

2021-08-29 05:20 UTC, srishilesh commented
@kwennB 

Any updates on this PR?

2021-08-29 06:32 UTC, kwennB commented
@srishilesh

I am working on it. 
I'll push soonest.
I sent you a message on slack.

2021-09-01 13:21 UTC, srishilesh commented
@kwennB 

Are all the changes done? Can I start my review?

2021-09-01 20:22 UTC, kwennB commented
@srishilesh 

Yes. You can start the review.

2021-09-02 19:36 UTC, srishilesh requested changes
@kwennB 

After going through your changes, I noticed that you have not gone through all my suggestions. There are a few more changes left.

Please ping me when everything is done.

Thanks.

2021-09-02 19:36 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +* Keep records: Write down what you do, document your experience.
`*` -> `-`

2021-09-02 19:36 UTC, srishilesh commented on content/articles/cloud-management/index.md
> +Cloud management is an essential knowledge. We need it to grasps the workings of cloud computing while starting out. It does not matter if you have an enterprise or intend on getting one. If you are
Add key takeaways

2021-09-02 19:42 UTC, kwennB commented
@srishilesh 

Noted 

Will do.

2021-09-04 20:33 UTC, kwennB commented
@srishilesh 

I have made the suggested changes. Kindly check them.

Thank you.

2021-09-06 20:34 UTC, hectorkambow commented
@srishilesh  

Just looking for a update on this article 👍

2021-09-07 00:43 UTC, srishilesh commented
@hectorkambow 

I'll complete the review by the end of the day.

2021-09-07 17:50 UTC, srishilesh approved these changes
@kwennB 

I've made several changes to formatting and flow. Make sure to go through all my commits.

Moving for the final review.

Thanks.

2021-09-07 22:14 UTC, hectorkambow commented
@kwennB 

Thank you for submitting your topic to the EngEd program and jumping on your revisions. 
As a rule of thumb - we can only accept articles (pull requests) that are fully polished and complete articles - articles that are ready to be published.
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 

Please be sure to go over any edits made by your peer reviewer to improve future articles and reviews and prevent any PR closure.

2021-09-07 22:49 UTC, hectorkambow commented
Overall nice job - made some minor edits to the format and for the flow. 
Easy to follow along - please go over any edits made to improve future articles and reviews. 

👍

2021-09-07 22:49 UTC, merged

2021-09-10 12:42 UTC, kwennB commented
@hectorkambow 
@srishilesh 

Thank you. All the feedback have been noted.