Understanding Cross Site Request Forgery Attacks
section-engineering-education/engineering-education pull request #3372
Opened 2021-08-16 12:12 UTC by Pauline-Mwangi

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

2021-08-16 12:13 UTC, Pauline-Mwangi commented
This fixes #2866

2021-08-16 13:58 UTC, geoffrey45 commented
Hello @Pauline-Mwangi Welcome to EngEd 🎉🎉

Please create an author folder in the `content/authors` directory. Feel free to check other students' folders to get started.

2021-08-16 14:18 UTC, Pauline-Mwangi commented
Hello @geoffrey45, thank you.
Sorry, this is my third article to contribute to the section community.

2021-08-16 14:26 UTC, geoffrey45 commented
@Pauline-Mwangi Sorry for the confusion

2021-08-17 00:22 UTC, hectorkambow commented
@Pauline-Mwangi 

[Understanding Cross Site Request Forgery Attacks #3372.pdf](https://github.com/section-engineering-education/engineering-education/files/6996019/Understanding.Cross.Site.Request.Forgery.Attacks.3372.pdf)

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2021-08-18 08:49 UTC, geoffrey45 requested changes
@Pauline-Mwangi Very nice article. Very clean and straightforward.

Please check the 2 comments below.

2021-08-18 08:49 UTC, geoffrey45 commented on content/articles/cross-site-request-forgery-attack/index.md
> +
Please provide links that explain cross site scripting and SQL injections at a general level. You can then add the section article links at the bottom of your article under a further reading section.

2021-08-18 08:49 UTC, geoffrey45 commented on content/articles/cross-site-request-forgery-attack/index.md
> +
Please provide explanation about these testing terms or add links to pages that explain more about them.

2021-08-20 10:28 UTC, louisefindlay23 commented
@Pauline-Mwangi, in the future, please add your This Closes comment in the original PR message as it usually doesn't work by adding a new comment.

2021-08-20 10:53 UTC, geoffrey45 requested changes
@Pauline-Mwangi Please check the comments below.

2021-08-20 10:53 UTC, geoffrey45 commented on content/articles/cross-site-request-forgery-attack/index.md
> +2. [Cross Site Requester](http://yehg.net/lab/pr0js/pentest/cross_site_request_forgery.php)
The 2nd link points to a 404

2021-08-20 10:53 UTC, geoffrey45 commented on content/articles/cross-site-request-forgery-attack/index.md
> +3. [SQL injection](https://www.section.io/engineering-education/how-to-fix-and-prevent-sql-injection-in-wordpress/)
Please use the actual article titles .ie. 

`How to prevent cross-site scripting in Node.js` instead of `Cross-site scripting`

2021-08-24 10:32 UTC, Pauline-Mwangi commented
@geoffrey45 I made changes you suggested

2021-08-24 11:25 UTC, geoffrey45 commented
@Pauline-Mwangi Very nice article. Detailed 🔍. Keep up the good work 🔥.

2021-08-24 11:26 UTC, geoffrey45 approved these changes

2021-08-28 11:51 UTC, ahmadmardeni1 commented
Great article, simple and easy-to-follow. @Pauline-Mwangi 

Thank you for the review @geoffrey45

2021-08-28 11:51 UTC, merged