10 of the most annoying UI/UX mistakes to avoid
section-engineering-education/engineering-education pull request #3408
Opened 2021-08-18 09:44 UTC by wanjirualice6194

### Article checklist
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
This closes #3088

2021-08-18 09:46 UTC, geoffrey45 commented
@wanjirualice6194 Welcome to the EngEd program 🎉.

Thank you for submitting your article for review.

2021-08-19 09:44 UTC, geoffrey45 requested changes
@wanjirualice6194 Very nice article.

Please check the comments below.

2021-08-19 09:44 UTC, geoffrey45 commented on content/articles/10-ui-ux-mistakes/index.md
> +You can get balanced color palletes from <https://coolors.co>
```suggestion
You can get balanced color palletes from [coolors.co](https://coolors.co)
```

2021-08-19 09:44 UTC, geoffrey45 commented on content/articles/10-ui-ux-mistakes/index.md
> +Large paragraphs make it hard to follow a sentence to the next line. Paragraphs should take a maximum of 2/3 of the width of the screen or less. They should also be centered to help the users concent
There are different screen sizes in various devices. The statement "2/3 of the screen" is misleading. Please use another measurement unit to drive your point.

2021-08-22 17:50 UTC, hectorkambow commented
plagiarism check done

2021-08-25 10:03 UTC, wanjirualice6194 commented
Hello @geoffrey45 I have made the requested changes

2021-08-25 10:26 UTC, geoffrey45 approved these changes

2021-08-25 10:27 UTC, geoffrey45 commented
@wanjirualice6194 Very nice article. Very clean. Keep up the good work 🔥

2021-09-08 17:14 UTC, WanjaMIKE commented
Merged #3408

2021-09-08 17:15 UTC, merged