Different Techniques of Encoding Data for Transmission
section-engineering-education/engineering-education pull request #3411
Opened 2021-08-18 11:49 UTC by 254-geo

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3323

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-18 12:00 UTC, Qodestackr commented
Hi I'll be your peer reviewer

2021-08-19 19:42 UTC, Qodestackr commented
@254-geo I will be taking you through a preliminary review.

2021-08-19 19:43 UTC, Qodestackr commented on content/articles/different-techniques-of-encoding-data-for-transmission/index.md
> +
Make sure to add alt text to all your image paths.

2021-08-19 19:51 UTC, Qodestackr commented
Going through your article, I have noticed that this article has an abrupt ending. The length of the article does not seem to involve the reader through the concepts. Make sure the ending isn't abrupt. Could you consider adding the pros and cons?

2021-08-19 19:55 UTC, Qodestackr commented on content/articles/different-techniques-of-encoding-data-for-transmission/index.md
> +Includes 4B/5B and 8B/6T encoding techniques.
This is too short.

2021-08-19 19:58 UTC, Qodestackr requested changes

2021-08-19 19:58 UTC, Qodestackr commented on content/articles/different-techniques-of-encoding-data-for-transmission/index.md
> +For this data to be encoded it has to be converted to signal variations. This signal variations include;
Make sure to format your intro section to improve readability. It seems to be technical for beginners.
Ping me when done :+1:

2021-08-20 13:17 UTC, GeoffreyKangu commented
> Going through your article, I have noticed that this article has an abrupt ending. The length of the article does not seem to involve the reader through the concepts. Make sure the ending isn't abrupt. Could you consider adding the pros and cons?

Changes made @Qodestackr

2021-08-20 20:27 UTC, Qodestackr commented
Glad you made changes. Kindly run the article through Grammarly once more so that I can head over to the next review

2021-08-22 18:00 UTC, hectorkambow commented
@GeoffreyKangu 

[Different Techniques of Encoding Data for Transmission #3411.pdf](https://github.com/section-engineering-education/engineering-education/files/7027870/Different.Techniques.of.Encoding.Data.for.Transmission.3411.pdf)


👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2021-08-22 18:41 UTC, Qodestackr commented
@GeoffreyKangu kindly fix pliagiarism as well as I proceed with further reviews. 👌

2021-08-23 19:46 UTC, GeoffreyKangu commented
@hectorkambow  Hello I seen the plagiarism and am working on it . Thank you.

2021-08-23 19:47 UTC, GeoffreyKangu commented
@Qodestackr  Hello am working on it I will let you when done

2021-08-23 20:33 UTC, GeoffreyKangu commented
@Qodestackr   Hello, I have made changes.

2021-08-30 23:46 UTC, hectorkambow commented
[Different Techniques of Encoding Data for Transmission #3411 2nd.pdf](https://github.com/section-engineering-education/engineering-education/files/7080154/Different.Techniques.of.Encoding.Data.for.Transmission.3411.2nd.pdf)


% is around the same.

2021-08-30 23:46 UTC, hectorkambow commented
Plagiarism check done

2021-09-02 10:15 UTC, Kayere requested changes
Hello @GeoffreyKangu, thank you for submitting this PR. I have done a review on  your article and I feel like there is more to cover in this topic. Could you please add more content on your article so as to add value. You could add some real examples of how data can be encoded using the techniques you have mentioned.

Also, make sure your article is unique. Please make the changes and ping me when you are done. Thanks.

2021-09-06 18:03 UTC, Kayere approved these changes
Congratulations for publishing your first article @GeoffreyKangu. Keep up the good work.
Thank you for the review @Qodestackr.

2021-09-06 18:03 UTC, merged