Webscraping with javascript
section-engineering-education/engineering-education pull request #3413
Opened 2021-08-18 12:01 UTC by kimanikevin254

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-18 12:01 UTC, marienjus commented
Hi I'll be your peer reviewer. Glad to see you've included the author details in your first PR!

2021-08-18 12:07 UTC, marienjus commented
Remove the backticks and include your issue number as this fixes #3177. I will be taking you through preliminary review

2021-08-18 12:12 UTC, kimanikevin254 commented
This fixes #3177

2021-08-19 08:35 UTC, Kayere commented
Hello @marienjus - Thank you for showing interest in reviewing this article. However, test reviewers are only allowed to review one article at a time. I am going to un-assign you so that another reviewer can review this article.

Regards.

2021-08-22 18:14 UTC, hectorkambow commented
@kimanikevin254 
[Webscraping with Javascript #3413.pdf](https://github.com/section-engineering-education/engineering-education/files/7027915/Webscraping.with.Javascript.3413.pdf)


There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).


cc @Dawe-7

2021-08-28 09:48 UTC, kimanikevin254 commented
@hectorkambow Could you please consider reopening this PR. I fixed the plagiarism mistakes. The problem was that I had included definitions from the official products page.

2021-08-31 03:21 UTC, kimanikevin254 commented
@hectorkambow ?

2021-08-31 13:48 UTC, BrianaNzivu commented
@hectorkambow I have re-opened this PR. 
Maybe you can run a check again to ensure of it is fine.
@Dawe-7 you can resume with the review if everything is alright. 

Regards. 🚀 

Cc @Dawe-7
Cc @keerthivarumbudy

2021-08-31 15:38 UTC, Dawe-7 commented
> @hectorkambow I have re-opened this PR.
> Maybe you can run a check again to ensure of it is fine.
> @Dawe-7 you can resume with the review if everything is alright.
> 
> Regards. 
> 
> Cc @Dawe-7
> Cc @kimanikevin254

@hectorkambow, Could we kindly have another plagiarism check on this PR before i begin the review.

2021-08-31 15:50 UTC, hectorkambow commented
plagiarism check done @kimanikevin254 

cc @Dawe-7

2021-09-05 17:58 UTC, Dawe-7 requested changes
Hello @kimanikevin254, awesome article, it's an interesting read and easy to follow through. I've left a few suggestions that i think will improve the quality of your article.  Also check on your article formatting, the headings should be `###` and subheadings should be `####` and lower. Lastly, adding more content in your conclusion will be nice.

> Ensure you pull the changes i've made before making the changes.

We will move on to tech review once you've implemented the changes.

2021-09-05 17:58 UTC, Dawe-7 commented on content/articles/introduction-to-web-scraping-with-javascript-and-puppeteer/index.md
> +In this tutorial, this is the URL of the product that we will be tracking on amazon: https://www.amazon.com/Redragon-S101-Keyboard-Ergonomic-Programmable/dp/B00NLZUM36/
```suggestion
In this tutorial, this is the [URL](https://www.amazon.com/Redragon-S101-Keyboard-Ergonomic-Programmable/dp/B00NLZUM36/)  of the product that we will be tracking on amazon: 
```

2021-09-05 17:58 UTC, Dawe-7 commented on content/articles/introduction-to-web-scraping-with-javascript-and-puppeteer/index.md
> +But we can also get data from any website even if it does not provide a public API. This process is known as **web scraping**, and it has been described in this article.
```suggestion
But we can also get data from any website even if it does not provide a public API. This process is known as **web scraping**, and we will take a look at it in this article. 
```

2021-09-05 17:58 UTC, Dawe-7 commented on content/articles/introduction-to-web-scraping-with-javascript-and-puppeteer/index.md
> +Before doing this, open your browser and go to the url provided (https://www.amazon.com/Redragon-S101-Keyboard-Ergonomic-Programmable/dp/B00NLZUM36/). From this page, we need to get the image of the
```suggestion
Before doing this, open your browser and go to the [URL](https://www.amazon.com/Redragon-S101-Keyboard-Ergonomic-Programmable/dp/B00NLZUM36/)  provided. From this page, we need to get the image of the keyboard, its price, and its name. Follow these steps:
```

2021-09-06 04:39 UTC, kimanikevin254 commented
@Dawe-7   Requested changes done

2021-09-07 14:43 UTC, Dawe-7 approved these changes
@kimanikevin254 , thanks for the changes.

@Kayere, this article is ready for final review.

2021-09-08 12:18 UTC, ahmadmardeni1 commented
Great work. Congrats on your first article and welcome to Section EngEd 🎉 @kimanikevin254 

Thank you for the review @Dawe-7 
Please go over the changes I made, and:
1. We always call it Node.js, not NodeJS.
2. Make sure to double-check the author's file in your next reviews.

2021-09-08 12:18 UTC, merged