Curve fitting using matlab
section-engineering-education/engineering-education pull request #3422
Opened 2021-08-18 16:44 UTC by linetachieng

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-19 16:51 UTC, lalith1403 requested changes
Can you perform a basic review of formatting and grammatical checks? The article appears to be a bit clunky.

2021-08-19 16:51 UTC, lalith1403 commented on articles/curve-fitting-using-matlab/index.md
> +![new fit](curve_eleven.png)
Update the image URLs. It will be /engineering-education/name of the folder/ image name.type

2021-08-19 16:51 UTC, lalith1403 commented on articles/curve-fitting-using-matlab/index.md
> +Curve fitting is the process of fitting models to data and analyzing the accuracy of the fit. Engineers and scientists use data fitting techniques to model acquired
Check the formatting here. The line seems to have moved to the next line.

2021-08-20 10:22 UTC, louisefindlay23 commented
@linetachieng, please remember to fill in the `This closes #issue-number` in the Article Checklist by removing the backticks and replacing `issue-number` with the issue number of your topic suggestion so you can be correctly paid out and your topic suggestion closed when this has been merged. Have done this for you above.

2021-08-24 14:49 UTC, louisefindlay23 commented
@linetachieng, upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF and revise your introduction accordingly.

![Curve Fitting Using Matlab - #3422 Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7040076/Curve.Fitting.Using.Matlab.-.3422.Report.pdf)

cc - @hectorkambow and @lalith1403

2021-08-31 16:20 UTC, hectorkambow commented
@lalith1403 

Can we get a status update on this PR?

2021-09-01 16:11 UTC, lalith1403 requested changes
Technically this article is sound. However, grammatically this article needs a lot of correction. You have used a lot of future tenses, which is avoided in technical writing. Please refer to the contribution guidelines for more information. You may refer to published articles and also may use professional editing services, if required.

Thanks,
Lalith

2021-09-02 08:00 UTC, linetachieng commented
@lalith1403 changes made.

2021-09-07 10:57 UTC, ahmadmardeni1 commented
This article is using the old structure. Please open a new PR and put your files in the correct folders. @linetachieng 
cc @lalith1403

2021-09-09 07:29 UTC, linetachieng commented
@ahmadmardeni1 change in the structure is made.
cc @lalith1403

2021-09-10 14:06 UTC, lalith1403 commented
@ahmadmardeni1 Can you take a look into this whenever you get a chance? Thank you

2021-09-11 11:34 UTC, ahmadmardeni1 commented
Great tutorial 🚀 @linetachieng 

Thank you for the review @lalith1403

2021-09-11 11:34 UTC, merged