Displaying images with fresco library in android
section-engineering-education/engineering-education pull request #3438
Opened 2021-08-19 15:49 UTC by brandy-kay

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #3163

2021-08-19 16:03 UTC, Ericgacoki commented
Greetings @brandy-kay,
Welcome to Section's Eng-Ed program. We're excited to have you on board. Thank you for submitting your `first article` for review.
I'll be reviewing it to check and help you fix any errors before being published! :rocket:

2021-08-19 16:13 UTC, Ericgacoki requested changes
Hello @brandy-kay, on a quick glance, your article structure looks great - kudos for that :rocket:. However, you might have accidentally duplicated the whole article seven times - for instance, there are seven conclusions 😟.
Please fix this before we proceed.

2021-08-19 16:13 UTC, Ericgacoki commented on content/articles/displaying-images-with-fresco-library-in-android/index.md
> +- [Fresco Official Documentation](https://frescolib.org/).Fresco was created by Facebook engineers to make efficient use of memory and improves productivity. Fresco was open-sourced for the first tim
I think the article ends at this point.

2021-08-19 16:13 UTC, Ericgacoki commented on content/articles/displaying-images-with-fresco-library-in-android/index.md
> +- Have Android Studio installed.
Everything beyond this point is a duplicate.

2021-08-19 17:01 UTC, brandy-kay commented
Hello @Ericgacoki I have fixed the duplication error, sorry for the inconvenience

2021-08-19 17:14 UTC, Ericgacoki approved these changes

2021-08-22 18:44 UTC, hectorkambow commented
@brandy-kay 

[Displaying images with fresco library in android #3438.pdf](https://github.com/section-engineering-education/engineering-education/files/7027948/Displaying.images.with.fresco.library.in.android.3438.pdf)


👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2021-08-23 11:51 UTC, brandy-kay commented
hello @Ericgacoki I have fixed the plagiarism problem

2021-08-24 12:51 UTC, Ericgacoki commented
@hectorkambow, please run a second plagiarism check 🙂

2021-08-30 06:44 UTC, WanjaMIKE commented
@brandy-kay could you fix the minor plagiarism highlighted in the attached report.
[Displaying images with fresco library in android #3438.pdf](https://github.com/section-engineering-education/engineering-education/files/7074704/Displaying.images.with.fresco.library.in.android.3438.pdf)
 the following report.

2021-09-01 14:54 UTC, Ericgacoki commented
Hello @brandy-kay, kindly take a look at the [changes](https://github.com/section-engineering-education/engineering-education/pull/3438/commits/e684d5b4ccd651b3bc3071c4337a6a0a1d7fee30) I've made.

2021-09-01 15:01 UTC, Ericgacoki requested changes

2021-09-01 15:01 UTC, Ericgacoki commented on content/articles/displaying-images-with-fresco-library-in-android/index.md
> +Fresco is a unique library that offers features such as animations, streaming, image loading, and transformation. Explore more on the other features provided by Fresco from their official documentati
Referring to the documentation for "other features" means that you didn't cover them in this article. Please give a none-contradicting conclusion.

2021-09-01 18:23 UTC, brandy-kay commented
hello @Ericgacoki have updated the conclusion

2021-09-01 20:26 UTC, Ericgacoki commented
Looks good :rocket:

2021-09-01 20:27 UTC, Ericgacoki approved these changes

2021-09-05 10:57 UTC, ahmadmardeni1 commented
Welcome to Section EngEd and congrats on your first article🎉

Please go over the changes I made.
Thank you for the review. @Ericgacoki

2021-09-05 10:57 UTC, merged

2021-09-05 10:58 UTC, Ericgacoki commented
Thank you Ahmad.