Creating a Shopping Cart using Arrays and Objects using vanilla JavaS…
section-engineering-education/engineering-education pull request #3448
Opened 2021-08-19 21:20 UTC by twish-254

…cript

complete article

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3284`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-19 21:27 UTC, geoffrey45 requested changes
@twish-254 Thank you for submitting your article for review.

Please check the comments below.

2021-08-19 21:27 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +The *createNode function* will create a new node and return it. It will take a node as a parameter.
Please convert this into an ordered list.

2021-08-19 21:27 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +    display: flex;
Use CSS syntax highlighting: ```css

2021-08-19 21:27 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +- Call the takeAction function to remove the item from the cart.
Remove the empty lines between these items.

2021-08-19 22:00 UTC, twish-254 commented
@geoffrey45  I have made all the changes requested

2021-08-21 06:19 UTC, geoffrey45 requested changes
@twish-254 Please check the comments below

2021-08-21 19:25 UTC, twish-254 commented
@geoffrey45 I have made the changes

2021-08-24 10:35 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +
@twish-254 This statement is redundant throughout your article. Please replace all the appearances after the first one with something similar to this: `Add the following code to script.js`

2021-08-25 10:35 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +   <div id="container">
@twish-254 This Html block is missing the head and body tags. Please add them.

2021-08-25 10:46 UTC, geoffrey45 requested changes
@twish-254 There are some Html characters in your JavaScript code. Please check the suggestions below.

2021-08-25 10:46 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +            item_node.innerHTML = `${item.name}
```suggestion
        item_node.setAttribute("id", item.id);

        if (item.count > 0) {
            item_node.innerHTML = `${item.name} 
```

2021-08-25 10:46 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +        let item = items[i];
```suggestion
    items_container.innerHTML = '';

    for (let i = 0; i < items.length; i++) {
        let item = items[i];
```

2021-08-25 10:46 UTC, geoffrey45 commented on content/articles/JavaSript-Shopping-Cart/index.md
> +                })[0];
```suggestion
            if (item_id !== "items" && item_id !== "badge") {
                let item = items_array.filter(function (item) {
                    return item.id == item_id;
                })[0];
```

2021-09-07 11:25 UTC, ahmadmardeni1 commented
Great article @twish-254 
Thank you for the review @geoffrey45

2021-09-07 11:25 UTC, merged