How to LookUp Ip Addresses in Java
section-engineering-education/engineering-education pull request #3454
Opened 2021-08-20 15:42 UTC by apondi-911

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-20 15:58 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing. @apondi-911 
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

2021-09-02 19:22 UTC, hectorkambow commented
@apondi-911 
Closing to clear up the queue while the require revisions are made

2021-09-13 07:13 UTC, apondi-911 commented
Can my article be opened?

On Thu, Sep 2, 2021, 22:23 hectorkambow ***@***.***> wrote:

> Closed #3454
> <https://github.com/section-engineering-education/engineering-education/pull/3454>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/3454#event-5249559291>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT7YMXFPWY5KSDG62NBKFU3T77FJXANCNFSM5CQSAEDA>
> .
>

2021-09-13 07:15 UTC, apondi-911 commented
Asking if my article can be opened

On Mon, Sep 13, 2021, 10:12 Ashley Apondi ***@***.***> wrote:

> Can my article be opened?
>
> On Thu, Sep 2, 2021, 22:23 hectorkambow ***@***.***> wrote:
>
>> Closed #3454
>> <https://github.com/section-engineering-education/engineering-education/pull/3454>
>> .
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/section-engineering-education/engineering-education/pull/3454#event-5249559291>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AT7YMXFPWY5KSDG62NBKFU3T77FJXANCNFSM5CQSAEDA>
>> .
>>
>

2021-09-13 21:53 UTC, Dawe-7 commented
@louisefindlay23
Could we run another plagiarism check before i begin the review.

cc: @hectorkambow

2021-09-14 09:12 UTC, apondi-911 commented
Not yet

On Sep 14, 2021 00:53, "Dawe Daniel" ***@***.***> wrote:

@louisefindlay23 <https://github.com/louisefindlay23>
Could we run another plagiarism check before i begin the review.

cc: @hectorkambow <https://github.com/hectorkambow>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/section-engineering-education/engineering-education/pull/3454#issuecomment-918606615>,
or unsubscribe
<https://github.com/notifications/unsubscribe-auth/AT7YMXG2EZZS6UHJD7OQTS3UBZXGDANCNFSM5CQSAEDA>
.

2021-09-14 10:21 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-14 14:39 UTC, Dawe-7 commented
> Hi, @apondi-911. Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revise your article accordingly.
> 
> Your article is quite short and not as detailed as we usually accept (thus is similar to other tutorials of the same nature). Please add more detail in order to make this more original and unique.
> 
> [How to Look Up IP Address in Java - Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7059490/How.to.Look.Up.IP.Address.in.Java.-.Report.pdf)

@apondi-911 I noticed that you haven't made any changes to your article. The article is still short, consider adding more content then i can begin the review.

2021-09-14 14:40 UTC, apondi-911 commented
Noted

On Sep 14, 2021 17:39, "Dawe Daniel" ***@***.***> wrote:

Hi, @apondi-911 <https://github.com/apondi-911>. Upon running your article
through our 3rd party plagiarism checker it seemed to raise a few flags and
the % was higher than we typically accept. Please see attached PDF - and
revise your article accordingly.

Your article is quite short and not as detailed as we usually accept (thus
is similar to other tutorials of the same nature). Please add more detail
in order to make this more original and unique.

How to Look Up IP Address in Java - Report.pdf
<https://github.com/section-engineering-education/engineering-education/files/7059490/How.to.Look.Up.IP.Address.in.Java.-.Report.pdf>

@apondi-911 <https://github.com/apondi-911> I noticed that you haven't made
any changes to your article. The article is still short, consider adding
more content then i can begin the review.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/section-engineering-education/engineering-education/pull/3454#issuecomment-919215615>,
or unsubscribe
<https://github.com/notifications/unsubscribe-auth/AT7YMXGOQA5PEMNTKKF3A6TUB5NBBANCNFSM5CQSAEDA>
.

2021-09-16 12:24 UTC, Dawe-7 commented
@apondi-911 is this article ready for review ?. What's the update ?

2021-09-16 12:27 UTC, apondi-911 commented
Yes it's ready

On Thu, Sep 16, 2021, 15:25 Dawe Daniel ***@***.***> wrote:

> @apondi-911 <https://github.com/apondi-911> is this article ready for
> review ?. What's the update ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/3454#issuecomment-920855537>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT7YMXAQMRQIQN3OJSFHF5LUCHO2BANCNFSM5CQSAEDA>
> .
>

2021-09-16 14:31 UTC, Dawe-7 requested changes
@apondi-911 nice article, i've left you a few suggestions to implement. Adding a prerequisites section for readers would be helpful.  Also, your hero image should be` hero.jpg` and not `hero image.jpg`.

2021-09-16 14:31 UTC, Dawe-7 commented on content/articles/how-to-lookup-ip-addresses-in-java/index.md
> +### Commonly used methods.
```suggestion
### Commonly used methods
```

2021-09-16 14:31 UTC, Dawe-7 commented on content/articles/how-to-lookup-ip-addresses-in-java/index.md
> +#### public static InetAddress[]getAllByName(String hostName) throws UnknownHostException
This should not be a subheading. If it is a note change it to the appropriate method to represent things the reader should note. You can use `>` to identify a note. Do the same for the rest.

2021-09-16 14:58 UTC, Dawe-7 commented
@apondi-911 ping me when all changes have been made.

2021-09-16 16:17 UTC, Dawe-7 commented
@apondi-911 i noticed you still don't have a prerequisites section for readers. Kindly add one.

2021-09-21 04:52 UTC, apondi-911 commented
🙋

2021-09-21 14:05 UTC, Dawe-7 approved these changes
@apondi-911, kindly go through the changes made to improve on your future articles.

@Kayere, this article is ready for final review.

2021-09-22 16:48 UTC, WanjaMIKE commented
@apondi-911 Kindly, take note of the edits I have done across the article. Thanks

2021-09-22 16:48 UTC, WanjaMIKE commented
Merged #3454 into master.

2021-09-22 16:49 UTC, merged