Intergrating Airtable API with Next.js serverless functions
section-engineering-education/engineering-education pull request #3487
Opened 2021-08-22 19:38 UTC by giridhar7632

### Article checklist

#### Pre-submission checks

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)(2766)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**(3%)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #2955

2021-08-29 11:00 UTC, WanjaMIKE commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[Intergrating Airtable API with Next.js serverless functions #3487.pdf](https://github.com/section-engineering-education/engineering-education/files/7072316/Intergrating.Airtable.API.with.Next.js.serverless.functions.3487.pdf)

2021-08-30 12:28 UTC, giridhar7632 commented
hey @WanjaMIKE most of the plagiarism error was because of the code. Both the examples are todo apps built using next.js and tailwind css. Should I change the example in my article?

2021-09-09 06:24 UTC, giridhar7632 commented
Hey @katungi I have changed the content acc to the suggestions by @WanjaMIKE 
Please review it

2021-09-09 17:11 UTC, WanjaMIKE commented
Hi @giridhar7632 several issues were raised during the review process. Could you work more on the article, specifically, fix grammar errors, sentence structure, formatting  - then open a new PR when its really ready. Thanks

2021-09-09 17:11 UTC, closed without merging

2021-09-09 17:12 UTC, katungi requested changes
Please fix those changes mentioned in the comments. At Section we have a desired quality for our articles. Your article needs a lot of grammar changes and revisions to sentence structure and it would be easier if you fixed them first before we move on. 

Feel free to ask for any clarification from the community. We are all here to help you produce the best article possible.

2021-09-09 17:12 UTC, katungi commented on content/articles/integrate-airtable-with-nextjs/index.md
> +![Hero image](https://cloud-ed45a3xcq-hack-club-bot.vercel.app/1hero-img.png)
Hey @giridhar7632. Section does not allow cdn images. We prefer all the images hosted locally. 
Please revert that change. Please refer to the [docs](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md) and fix image links.

Finally, please run your article through a grammar checker like [Grammarly](https://www.grammarly.com/) to improve the quality of the article.