Monitoring a Microsoft SQL Server database using Solar Winds Database Performance Analyzer
section-engineering-education/engineering-education pull request #3523
Opened 2021-08-25 06:47 UTC by ruphus-muita

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-25 06:50 UTC, ruphus-muita commented
@srishilesh This is the new PR. I believe it is now looking okay

2021-08-25 06:54 UTC, srishilesh commented
> @srishilesh This is the new PR. I believe it is now looking okay

@ruphus-muita 

This looks perfect

2021-08-25 06:55 UTC, srishilesh commented
Duplicate if #3471

2021-08-29 10:23 UTC, WanjaMIKE commented
Could you fix the minor issues highlighted in this plagiarism report. Thanks
[Monitoring a Microsoft SQL Server database using Solar Winds Database Performance Analyzer #3523.pdf](https://github.com/section-engineering-education/engineering-education/files/7072270/Monitoring.a.Microsoft.SQL.Server.database.using.Solar.Winds.Database.Performance.Analyzer.3523.pdf)

2021-08-29 12:12 UTC, ruphus-muita commented
> Could you fix the minor issues highlighted in this plagiarism report. Thanks
> [Monitoring a Microsoft SQL Server database using Solar Winds Database Performance Analyzer #3523.pdf](https://github.com/section-engineering-education/engineering-education/files/7072270/Monitoring.a.Microsoft.SQL.Server.database.using.Solar.Winds.Database.Performance.Analyzer.3523.pdf)

@WanjaMIKE  This done. Please check. Thanks

2021-08-31 17:06 UTC, srishilesh commented
@ruphus-muita 

Thanks for the change.

I'll complete my next round of review by tomorrow.

2021-09-05 12:08 UTC, ruphus-muita commented
> @ruphus-muita 
> 
> Thanks for the change.
> 
> I'll complete my next round of review by tomorrow.

Are you done?

2021-09-05 14:38 UTC, srishilesh requested changes
@ruphus-muita 

I've suggested a few changes. Please ping me when done.

I would suggest you to rename the images - all in small case, separated by `-`.

On completion, we'll move to the tech review.

Thanks.

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +
Can you talk more about the goals of this tutorial? What are the key takeaways? Objective of the code tutorial?

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +9.	Exclude the DPA directory from antivirus scanning to ensure smooth installation: C:\Program Files\SolarWinds\DPA
These need not be a numbered list - convert them to normal bulleted points `-`

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +![File Extraction](/engineering-education/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/File Extraction.png)
I would suggest using image names separated by `-`, and all the letters in small case.

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +![File Extraction](/engineering-education/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/File Extraction.png)
Could you do this change for all the images?

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +4.	Open SolarWindsDPASetup-x64.exe and run it. Click next once the installer has started.
```suggestion
4.	Open `SolarWindsDPASetup-x64.exe` and run it. Click next once the installer has started.
```

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +	The privileged user must have the following privileges for self-managed SQL Server database instances: SYSADMIN (system administrator).
Can you converted these bullets to `-`?

2021-09-05 14:38 UTC, srishilesh commented on content/articles/monitoring-microsoft-sql-server-using-solar-windows-database-analyzer/index.md
> +#### Note: Each instance must be registered separately
```suggestion
> NOTE: Each instance must be registered separately
```

2021-09-07 06:49 UTC, ruphus-muita commented
@srishilesh All done

2021-09-10 04:36 UTC, ruphus-muita commented
@srishilesh are we done with this PR?

2021-09-10 04:40 UTC, srishilesh commented
> @srishilesh are we done with this PR?

@ruphus-muita 

The final round of review by me, is in progress. Please wait patiently.

2021-09-11 11:32 UTC, srishilesh approved these changes
@ruphus-muita 

Good job.

I've made a few changes to your article. Make sure to go through the commits to understand them

Moving for the final review.

Thanks.

2021-09-13 20:48 UTC, WanjaMIKE commented
@ruphus-muita could you perform more analyses using the tool. I found that most of the article focused on the installation part which seems more straight-forward. Thanks

2021-09-13 20:56 UTC, ruphus-muita commented
@WanjaMIKE Kindly clarify on what you mean by more analyses.

2021-09-13 21:23 UTC, WanjaMIKE commented
I mean use the tool to conduct further tests and then explain them in the article. Thanks

2021-09-14 09:56 UTC, ruphus-muita commented
> I mean use the tool to conduct further tests and then explain them in the article. Thanks

@WanjaMIKE This is done. Kindly confirm

2021-09-17 17:27 UTC, hectorkambow commented
Overall nice job gents 👍

2021-09-17 17:27 UTC, merged