Understanding the Flutter Getx ecosystem for state management
section-engineering-education/engineering-education pull request #3561
Opened 2021-08-27 13:03 UTC by Lekwacious

### Article checklist

#### Pre-submission checks

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3259.

2021-08-28 13:40 UTC, louisefindlay23 commented
@Lekwacious, I have copied and pasted the article checklist back into your PR comment. In the future, please do not delete this. Now you should go through the checklist and check the steps as you have completed them so your article is ready for review.

2021-08-28 14:05 UTC, Lekwacious commented
Done. Thank you @louisefindlay23.

2021-09-06 15:41 UTC, Lekwacious commented
Hi @louisefindlay23 no body has been assigned to review my PR. Just checking on the status of the PR

2021-09-06 15:44 UTC, louisefindlay23 commented
@WanjaMIKE, if you're free, could you take a look at this article? I don't have experience with Flutter but I know that you have.

2021-09-13 10:06 UTC, WanjaMIKE commented
@louisefindlay23 Okay, I will.

2021-09-13 10:07 UTC, WanjaMIKE commented on content/articles/understanding-the-flutter-getx-ecosystem-for-state-management/index.md
> +State management allows for the sharing of application state between screens, across your app. Put differently, it enables you to pass data from one User Interface to another so that when the state o
Break into 2-3 paragraphs

2021-09-13 10:08 UTC, WanjaMIKE commented on content/articles/understanding-the-flutter-getx-ecosystem-for-state-management/index.md
> +![GetX Documentation](getx-documentation.png)
What is GetX. Could explain more on it

2021-09-13 10:09 UTC, WanjaMIKE commented on content/articles/understanding-the-flutter-getx-ecosystem-for-state-management/index.md
> +#### The Cart Controller
What will the cart controller do? Explain

2021-09-13 10:11 UTC, WanjaMIKE commented on content/articles/understanding-the-flutter-getx-ecosystem-for-state-management/index.md
> +- ``obs``: We have declared a variable that is going to hold a list of all orders and we made it an observable by making it an obs using the dot notation. By making it an obs, every time the orders c
use ``` `obs` ```

2021-09-13 10:12 UTC, WanjaMIKE requested changes
Please heck the following comments

2021-09-13 11:07 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. @Lekwacious 
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.
cc @WanjaMIKE @louisefindlay23 

[Understanding the Flutter Getx ecosystem for state management#3561](https://github.com/section-engineering-education/engineering-education/files/7153709/New.Scan.10_57.AM.Copyleaks.Report.pdf)

2021-09-15 02:31 UTC, Lekwacious commented
@WanjaMIKE  Thanks for the review. I have effected the changes you requsted

2021-09-18 10:48 UTC, WanjaMIKE commented
@Lekwacious did you correct the plagiarism?

2021-09-18 16:59 UTC, Lekwacious commented
@WanjaMIKE  Yes I did correct the plagiarism

2021-09-21 13:38 UTC, Kayere commented
Great article @Lekwacious, keep up the good work 🚀.

2021-09-21 13:38 UTC, merged