Completed lru cache implementation in javascript
section-engineering-education/engineering-education pull request #3564
Opened 2021-08-27 15:34 UTC by erixbiz

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

---
Completed the write-up on LRU Cache Implementation in Javascript.

2021-08-28 08:01 UTC, geoffrey45 commented
@erixbiz Thank you for submitting your article for review.

Carefully go through the text that I have added to this pull request's header, checking the necessary check boxes.

You can check a box by adding an `x` in the `[ ]` like this: `[x]`

---
Another thing, you have added your code as images. Please use code blocks instead.

2021-08-28 08:11 UTC, geoffrey45 requested changes
@erixbiz Please check the comments below.

2021-08-28 08:11 UTC, geoffrey45 commented on content/articles/lru-cache-implementation-in-javascript/index.md
> +
Please explain what is `'cold' entries` and `'hot' data`

2021-08-28 08:11 UTC, geoffrey45 commented on content/articles/lru-cache-implementation-in-javascript/index.md
> +
Please download the image and add a link to the source. This way, if the source fails, you still have the image on your article.

2021-08-29 08:18 UTC, WanjaMIKE commented
Plagiarism check done.

@erixbiz could you correct the following paragraph which appeared to have been copied verbatim.

```
In-memory caches such as Memcached and Redis are key-value stores between your application and your data storage. Since the data is held in RAM, it is much faster than typical databases where data is stored on a disk. RAM is more limited than disk. Cache invalidation algorithms such as least recently used (LRU) can help invalidate 'cold' entries and keep 'hot' data in RAM.
```

2021-09-01 13:24 UTC, erixbiz commented
@geoffrey45 I have made all the changes requested and gone through it against the checklist as well. Looking forward to hearing from you once reviewed. Thank you.

2021-09-06 08:39 UTC, geoffrey45 commented
Hello @erixbiz Looks like you have 5k+ files changed. This was caused by force pushing your last commit.

Please download your latest files and open a new pull request.

Leave a comment for me in your new pull request.

2021-09-09 08:58 UTC, geoffrey45 commented
@erixbiz Please let me know when you open the new pull request.

2021-09-09 08:58 UTC, closed without merging