Getting Started With Dependency Injection in Angular 12+
section-engineering-education/engineering-education pull request #3585
Opened 2021-08-29 06:59 UTC by NaomiSeint

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3230

2021-08-29 08:03 UTC, WanjaMIKE commented
Plagiarism check done - Proceed. 
[Getting Started With Dependency Injection in Angular 12+ #3585.pdf](https://github.com/section-engineering-education/engineering-education/files/7072115/Getting.Started.With.Dependency.Injection.in.Angular.12%2B.3585.pdf)

2021-09-05 12:54 UTC, jumamiller commented on content/articles/angular-12-dependency-injection/index.md
> +
Hello @NaomiSeint , ensure that your article aligns with the guidlines set, kinldy restructure it well and remove all spaces where necessary as shown on this paragraph.

2021-09-05 12:56 UTC, jumamiller commented on content/articles/angular-12-dependency-injection/index.md
> +We've also created the `getStudentsList()` method that we're using to get student details from the service. We then assign the results to the students array we've locally created. We call this method
There is a misplaced backtick on this paragraph, kindly check.

2021-09-05 12:56 UTC, jumamiller commented on content/articles/angular-12-dependency-injection/index.md
> +In this tutorial, we've discussed a wide range of concepts of Angular DI with examples. We've seen how the services are created and then consumed within a component. We've also gone a step further to
Conclusion should cover what has been covered on the entire article. Kindly fix.

2021-09-05 12:57 UTC, jumamiller requested changes
@NaomiSeint, there are minor suggestions I've made, kindly go over and rectify.Addtionally, I cant trace your author details.

2021-09-15 05:32 UTC, NaomiSeint commented
@jumamiller ,all changes are done

2021-09-15 05:34 UTC, jumamiller commented
Great work @NaomiSeint , finishing up tech review today!

2021-09-15 05:44 UTC, jumamiller commented
Hello @NaomiSeint , could you add the author details before we move forward to final review.

2021-09-16 05:08 UTC, NaomiSeint commented
Author details added.

2021-09-16 05:10 UTC, jumamiller approved these changes
A great way to kick off your articles,, looking forward for more improved articles. Great work @NaomiSeint!

2021-09-17 03:28 UTC, LinusMuema commented
Hi @jumamiller 
The article does not have a hero image so please check on that.
My concern is that I am seeing some mistakes occurring for the third time this time. I had told you to [check my commit](https://github.com/section-engineering-education/engineering-education/pull/3312#issuecomment-907614928) for the changes but it seems you didn't. The same mistakes in the introduction and table of contents are there. 

Please make sure you check the CM's final edits to improve your review and prevent this from happening. 

cc: @hectorkambow advice on the same?

2021-09-17 06:10 UTC, jumamiller commented
Hi @LinusMuema, I did check the commits and the changes were mainly on the spacings,  I'll be sure to look for a better a editor to improve on them.

2021-09-17 06:11 UTC, LinusMuema commented
Awesome.
It's just the introductions and table of contents...

2021-09-17 18:11 UTC, LinusMuema commented
Hi @NaomiSeint 
Thank you for joining section and we look forward to getting more amazing content from you. Awesome job!

cc: @jumamiller

2021-09-17 18:11 UTC, merged