Core Concepts Of Redux Store Management
section-engineering-education/engineering-education pull request #3586
Opened 2021-08-29 10:23 UTC by Horlawhumy-dev

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x]  Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
This fixes issue #3486
#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-08-29 10:23 UTC, Horlawhumy-dev commented
Yeah, I am done with the article.

2021-08-31 17:54 UTC, Horlawhumy-dev commented
I just hope this article has not been left out @hectorkambow @ahmadmardeni1 @WanjaMIKE

2021-08-31 18:39 UTC, hectorkambow commented
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

2021-09-01 07:46 UTC, Horlawhumy-dev commented
Thanks, @M0nicah

2021-09-03 11:19 UTC, Horlawhumy-dev commented
Yeah, I have done the plagiarism test. The updated article has been re-uploaded.

2021-09-04 11:19 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-06 16:03 UTC, hectorkambow commented
@M0nicah  

I believe this PR have pass the plagiarism check and can go through prelim review.

2021-09-06 16:56 UTC, Horlawhumy-dev commented
Yes sir. It has passed plagiarism test. With my best of knowledge, it only requires the reviewer to move it to the next stage.

2021-09-08 10:11 UTC, M0nicah requested changes
Hello @Horlawhumy-dev, I've gone through your PR  and there seems to be some problems. Please go through the comments and suggestions I have put forward so you could make your article better.

**Note:** The title of your article should be in lowercase.
Thanks.

2021-09-08 10:11 UTC, M0nicah commented on content/articles/index.md
> +To demonstrate an instance of asynchronous calls in the Redux application, I came up with the codes below.
```suggestion
To demonstrate an instance of asynchronous calls in the Redux application, I came up with the code below.
```

2021-09-08 10:11 UTC, M0nicah commented on content/articles/index.md
> +Generally speaking, Redux is said to be a JavaScript library that depicts how the state of the application should be managed and accessed. Redux manages every application state, by providing a centra
This paragraph seems a little bit long. Try to break the sentences to make them shorter.
Let each paragraph explain one concept for clear understanding.

2021-09-08 14:45 UTC, Horlawhumy-dev commented
I have corrected the article and perfeced the hero issues. @M0nicah ma

2021-09-10 15:18 UTC, M0nicah commented
great article @Horlawhumy-dev , please review the changes I made in the commits to help improve the flow and format for your future articles.

2021-09-10 15:34 UTC, Horlawhumy-dev commented
Wow! I have gone through the changes. Thanks @M0nicah

2021-09-14 15:02 UTC, merged