Html client for web services using dhtml behavior
section-engineering-education/engineering-education pull request #3636
Opened 2021-09-01 21:20 UTC by borosteve

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3349 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-01 22:46 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing. @borosteve 
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

2021-09-06 21:39 UTC, hectorkambow commented
plagiarism check done - article will benefit from going over the % of red flags. 

[Html client for web services using dhtml behavior #3636.pdf](https://github.com/section-engineering-education/engineering-education/files/7117870/Html.client.for.web.services.using.dhtml.behavior.3636.pdf)

2021-09-07 10:32 UTC, borosteve commented
Hi, @hectorkambow 
I have made the changes you requested. It is now okay.
Thank you.

2021-09-12 12:37 UTC, borosteve commented
Hi, @Dawe-7 
Would you update me on the progress of this PR please,
Thanks you.

2021-09-12 15:19 UTC, Dawe-7 commented
> Hi, @Dawe-7
> Would you update me on the progress of this PR please,
> Thanks you.

@borosteve, am reviewing one more article then i'll work on yours.

2021-09-12 17:34 UTC, borosteve commented
@Dawe-7 
Aright, thank you for the update.

2021-09-21 13:36 UTC, Dawe-7 requested changes
@borosteve, welcome to Section's Eng Ed and congratulations on submitting your first article. Your article is an interesting read. To improve the quality of it, I've left you a few suggestions. Consider making those changes. Also, do on the following:
1. Add a prerequisites section - This would be very helpful to readers as they would know what is required before reading.
2. Change the `avator.jpeg` to `avatar.jpg` , `exploler.jpeg` to `explorer.jpg`, `postmethode.jpg` to `postmethod.jpg`. 
3. We do not accept the `.jpeg` image format so use the `.jpg` format, make changes where necessary.

2021-09-21 13:36 UTC, Dawe-7 commented on content/articles/html-client-for-web-services-using-dhtml-behavior/index.md
> +8. Only HTML can be used for user-side code, but DHTML is utilized for server-side code.
```suggestion
8. HTML can be used in user-side coding whereas DHTML is used for server-side coding.
```

2021-09-23 12:14 UTC, Dawe-7 commented
@borosteve, any updates on this PR?

2021-09-25 08:22 UTC, borosteve commented
Hi @Dawe-7 
Sorry for the delay, I had problems with my laptop.
I have done all the changes you requested.
Thank you.

2021-09-27 21:07 UTC, Dawe-7 approved these changes
@borosteve, kindly go through the changes that I've made. I noticed you didn't implement some of the suggestions i gave. In your future articles, ensure all the suggestions given are implemented to avoid several rounds of revision which leads to article closure. Also, make use of the [hemingway app](https://hemingwayapp.com/) and [grammarly](http://www.grammarly.com/) to check on your article readability. Otherwise, great article. 

@hectorkambow, this article is ready for final review.

cc: @Kayere

2021-09-28 09:40 UTC, borosteve commented
Hello, @hectorkambow 
I have made the requested changes.
Thank you.
cc @Dawe-7

2021-09-28 11:09 UTC, Dawe-7 commented
> Hello, @hectorkambow I have made the requested changes. Thank you. cc @Dawe-7

@hectorkambow, I think the changes seem okay. What do you think?

2021-10-04 21:19 UTC, hectorkambow commented
@borosteve 

Please be sure to go through the edits made by your peer reviewer and content moderator (and myself) to improve future articles.
As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published.
Our team of peer reviewers do not provide revisions services at this time in order to review them all in a timely manner. 

All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

Thank you 🚀 

cc @Dawe-7 please do the same to improve future reviews 

cc @WanjaMIKE please do the same.

2021-10-04 21:19 UTC, merged