Abstractive summarization using deep learning
section-engineering-education/engineering-education pull request #3651
Opened 2021-09-02 18:03 UTC by smkinyan

This closes #3542

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-06 21:47 UTC, hectorkambow commented
[Abstractive Summarization Using Deep Learning #3651.pdf](https://github.com/section-engineering-education/engineering-education/files/7117881/Abstractive.Summarization.Using.Deep.Learning.3651.pdf)
 plagiarism check done - it will benefit the article to review the red flags in the repot.

2021-09-22 16:02 UTC, collins-a requested changes
Hey @smkinyan, simple tutorial on Abstractive Summarization. However, there are a few changes required as highlighted by my comments.

Ping me when done.

2021-09-22 16:32 UTC, smkinyan commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +summary = model.generate(**tokens)
Solved

2021-09-23 14:24 UTC, collins-a commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +This command will successfully install the huggingface transformer library.
Consider removing this sentence

2021-09-23 14:30 UTC, collins-a commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +Let's go ahead and try to summarize this text.
```suggestion
It's time to summarize our text.
```

2021-09-23 14:32 UTC, collins-a commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +Let's check our generated summary results. We do this by typing the following command:
```suggestion
To check our generated summary results in tokens, we type `summary`.
```

2021-09-23 14:34 UTC, collins-a commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +These may be just a bunch of numbers to humans, but not to machines. This is how they understand language. Decoding these values will help us make sense of these numbers.
```suggestion
These results represent our output tensors. These may be just a bunch of numbers to humans, but not to machines. This is how they understand language. Decoding these values will help us make sense of these numbers.
```

2021-09-23 14:36 UTC, collins-a commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +All that big block of text summarized into that short text.
```suggestion
Running the above command shows our summarized text. Isn't it impressive how that block of text has been summarized?
```

2021-09-23 14:38 UTC, collins-a commented on content/articles/abstractive-summarization-using-deep-learning/index.md
> +So, here's the actual test. If you go through the huge block of text, you'll find that this summarized version of the text doesn't exist. It's novel and has been completely generated by the model.
The beginning of this sentence is a bit unclear. A reader will likely ask, what exactly is being tested?

2021-09-24 00:26 UTC, collins-a approved these changes

2021-09-24 05:50 UTC, LinusMuema commented
Hi @smkinyan 
Thank you for this amazing article. We'd like to see more of such great content.

cc: @collins-a

2021-09-24 05:50 UTC, merged