Concurrency in Go
section-engineering-education/engineering-education pull request #3666
Opened 2021-09-03 13:50 UTC by Anitaachu

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-03 14:04 UTC, Anitaachu commented
This closes #3397

2021-09-03 14:18 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing. @Anitaachu 
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

2021-09-06 22:31 UTC, hectorkambow commented
@Anitaachu 
There are TWO index files in this PR. 

🤔

2021-09-06 22:43 UTC, hectorkambow commented
[Understanding concurrency in Go #3666.pdf](https://github.com/section-engineering-education/engineering-education/files/7117954/Understanding.concurrency.in.Go.3666.pdf)

plagirism check done 

@Anitaachu 

It will improve the article to go through the red flags in the report.

2021-09-08 09:43 UTC, Anitaachu commented
Requested changes have been and I ran the test again

2021-09-09 08:50 UTC, adrianmurage commented
@Anitaachu You seem to have added images and an article related to "integrating-graphql-api-in-a-django-application"

Kindly remove any files unrelated to "Understanding concurrency in Go"

2021-09-09 10:15 UTC, adrianmurage requested changes
@Anitaachu 

I like the article thus far but It feels incomplete. 
As a reader, I don't really get to see the effects of the implementation of concurrency. You introduced the aspect of time before implementing concurrency but never revisit it once you implemented concurrency you don't revisit the time concept. 

It would be really great if you could clearly illustrate how introducing concurrency affects the performance of the application. Otherwise, the significance of concurrency is lost on the reader. 

Looking forward to seeing how you do this. Kindly @ me when the necessary changes are made.

2021-09-15 16:06 UTC, adrianmurage commented
@Anitaachu ?

2021-09-16 19:53 UTC, Anitaachu commented
@adrianmurage I'm sorry for the delayed response. I noticed some errors and had to restructure the drafts. All requested changes have been made. Thank you

2021-09-21 10:29 UTC, adrianmurage submitted a review, later dismissed
@Anitaachu  Awesome job with the update. You implemented the recommendations in a satisfactory manner. Thank you!

I've pointed out a few more changes in the formating that you need to address after which we can mark the article ready for final review

2021-09-21 10:29 UTC, adrianmurage commented on articles/concurrency-in-go/index.md
> +In both scenarios, customers are served at the same time. Parallelism is a tool used by concurrency to achieve its goal however, it is not the goal of concurrency.
```suggestion
In both scenarios, customers are served at the same time. Parallelism is a tool used by concurrency to achieve its goal, however, it is not the goal of concurrency.

```

2021-09-21 10:29 UTC, adrianmurage commented on articles/concurrency-in-go/index.md
> + [Goroutines](https://www.golangprograms.com/goroutines.html) are functions that run at the same time alongside other code or programs. Goroutines are unique to Go. They’re not OS threads though they
```suggestion
 [Goroutines](https://www.golangprograms.com/goroutines.html) are functions, unique to Go, that run at the same time alongside other code or programs.

They’re not OS threads, though, they may be considered lightweight threads.

Goroutines are deeply integrated with Go's runtime. Go's runtime monitors goroutine behavior and suspends them when they become blocked, then resumes them once they are unblocked. 

This makes them preemptible in some ways, but only when the goroutine is blocking.

The runtime and the logic of a goroutine work together. Goroutines can communicate with one another and synchronize their execution. In Go, one of the synchronization elements is called a channel. 

Though channels are used to synchronize memory access, they are best used for communicating information between goroutines. When data is to be shared across goroutines while performing a concurrent activity as a goroutine, channels function as a conduit (pipe) between the goroutines and provide a method that ensures asynchronous exchange.

```

2021-09-21 10:29 UTC, adrianmurage commented on articles/concurrency-in-go/index.md
> +The program was executed at exactly, 8.937s
This time does not reflect the time shown in your image above

2021-09-21 21:08 UTC, Anitaachu commented
Thank you @adrianmurage. All requested changes and corrections have been made.

2021-09-22 06:35 UTC, adrianmurage commented
@Anitaachu 
You still have files related to the `integrating-graphql-api-in-a-django-application` article in your PR.
Kindly delete them.

2021-09-22 07:02 UTC, Anitaachu commented
@adrianmurage they've been deleted. Thank you.

2021-09-22 18:25 UTC, adrianmurage commented
@Anitaachu 
Great job with the article. Kindly go through the changes I made.
Looking forward to seeing more of your work!

2021-09-23 05:50 UTC, LinusMuema commented
Hi @Anitaachu 
Awesome job on the article. The final review is done :rocket: 

cc: @adrianmurage you can check my commit for the changes I have made. The image extensions were in caps but it was a small change.

2021-09-23 05:50 UTC, merged