How to create an Android Wear OS app
section-engineering-education/engineering-education pull request #3687
Opened 2021-09-04 15:10 UTC by Antonymuriuki

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #2919

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-04 15:13 UTC, Ericgacoki commented
Greetings @Antonymuriuki,
Welcome to Section's Eng-Ed program. We're excited to have you here. Thank you for submitting your `first article` for review.
I'll be reviewing it to check and help you fix any errors before being published! :rocket:

2021-09-04 15:25 UTC, Ericgacoki requested changes
Hello @Antonymuriuki, on a quick glance, your article looks great. However, take a look at the suggestions attached below and work on them before I proceed with the review.
Let me know when you're done.

2021-09-04 15:25 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +
Seems like you forgot to add the prerequisites. Please do so.

2021-09-04 15:25 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +
```suggestion
### Creating a Wear OS project on Android Studio

```

2021-09-04 15:25 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +
Please add an introduction paragraph to this heading. Avoid assuming the reader is conversant with navigation.

2021-09-06 22:58 UTC, hectorkambow commented
@Antonymuriuki 

[How to create an Android Wear OS app #3687.pdf](https://github.com/section-engineering-education/engineering-education/files/7117972/How.to.create.an.Android.Wear.OS.app.3687.pdf)


👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2021-09-07 00:06 UTC, Antonymuriuki commented
@Ericgacoki, I have made the requested changes.
@hectorkambow, I have fixed the code that raised plagiarism although most of it is auto-generated by Android Studio and can not be edited.

2021-09-07 00:10 UTC, Ericgacoki commented
@hectorkambow, Kindly run a second plagiarism check on this article. Thank you!

2021-09-12 11:21 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-12 13:39 UTC, Ericgacoki requested changes
Hey @Antonymuriuki, go through the suggestions attached below and let me know when you're done.

2021-09-12 13:39 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +We normally concentrate on only two types of devices when developing mobile apps: tablets and smart phones. Have you ever considered how to build applications for wearables?
This seems too brief 🤭. Please give a more descriptive introduction.

2021-09-12 13:39 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +- Have Android studio installed
Could you please paraphrase this? It would sound better as, "To follow through this tutorial, the reader should..."

2021-09-12 13:39 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +
capitalize the component name like the others.

2021-09-12 13:39 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +    tools:contect=".MainActivity">
I can spot a typo and I assume you wanted to write `context` instead of `contect`. Please fix that and test your code to ensure that it works.

2021-09-12 13:39 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +            android:layout_width="60dp"
Hard coded dimensions result to an unresponsive UI. No user would like this. Kindly use `wrap_content` and/or `match_parent` where applicable.

2021-09-12 13:39 UTC, Ericgacoki commented on content/articles/how-to-create-an-android-wear-os-app/index.md
> +drawer.setAdapter(MainDrawerAdapter(this))
You might have forgotten to use the correct ID. Please confirm and reference it properly. Otherwise, this won't work.

2021-09-12 14:12 UTC, Antonymuriuki commented
> Hey @Antonymuriuki, go through the suggestions attached below and let me know when you're done.

Hey @Ericgacoki, the changes have been made.

2021-09-12 14:30 UTC, Ericgacoki approved these changes

2021-09-15 11:39 UTC, Kayere commented
@Antonymuriuki - Great article, seems to be of great value to the community. Just one note, could you please add images related to the different steps. This will give the reader a visual representation of what is going on and or what has been accomplished.

Ping me when you are done.

cc @Ericgacoki

2021-09-15 19:21 UTC, Antonymuriuki commented
@Kayere, done.

cc: @Ericgacoki

2021-09-15 19:51 UTC, Kayere commented
@Antonymuriuki - Your article is ready for publishing. However, the avatar image you have provided is not acceptable. Please upload a picture of yourself instead.

2021-09-15 20:07 UTC, Antonymuriuki commented
@Kayere, done.

cc: @Ericgacoki.

2021-09-15 20:12 UTC, Kayere commented
Congratulations for publishing your first article @Antonymuriuki.

2021-09-15 20:12 UTC, merged