How to solve initial value problem using ode45 in Matlab
section-engineering-education/engineering-education pull request #3689
Opened 2021-09-04 16:34 UTC by josephodhis

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #3170

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-06 23:36 UTC, hectorkambow commented
@josephodhis 

[How to solve initial value problem using ode45 in Matlab #3689.pdf](https://github.com/section-engineering-education/engineering-education/files/7118025/How.to.solve.initial.value.problem.using.ode45.in.Matlab.3689.pdf)


👋 Good afternoon - I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2021-09-13 12:39 UTC, lalith1403 requested changes
@josephodhis Welcome to Eng-Ed program. This is a wonderful article with thought provoking examples. Can you add more explanation wherever you are explaining the problem and the code. Once that is done, we can move to the final review. 

Also, perform a periodic check for grammatical errors using services such as Grammarly.

2021-09-13 12:39 UTC, lalith1403 commented on content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/index.md
> +dx/dt = f(t,x), x(t0) = xo
Use Latex to display mathematical equations.

2021-09-13 12:39 UTC, lalith1403 commented on content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/index.md
> +Here, `t` is the independent variable, `x` is a vector of dependent variables to be found, and f (t, x) is a function of t and x. The mathematical equation is defined when the `x` of functions on the
Use Inline latex to denote mathematical terms. Refer to the earlier published article on MATLAB.

2021-09-13 12:39 UTC, lalith1403 commented on content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/index.md
> +In this article, we will consider the Matlab algorithm `ode45` to solve the IVP. IVP is an ODE together with some initial value(s). Here you have a differential equation describing the dynamics of ho
First occurrence of abbreviation should contain the full form as well.

2021-09-13 12:39 UTC, lalith1403 commented on content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/index.md
> +In Runga Kutta 4 method, we obtain the solution of $y_i$ at various values of $t_i$ between the range $t_0$ and $t_n$. The intermediate value at which the computations are done is calculated internal
Explain Runge Kutta method. Check the spelling. It is Runge Kutta.

2021-09-13 12:39 UTC, lalith1403 commented on content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/index.md
> +The plug flow reactor may be figured as one long tube or several short tubes. They range in diameter from few centimetres to several meters. The choice of diameter is based on the construction cost,
PFR needs through explanation. This explanation does not guide the reader on what the problem is.

2021-09-18 06:00 UTC, lalith1403 commented
@josephodhis Any updates on this?

2021-09-18 09:23 UTC, josephodhis commented
@lalith1403 changes made.

2021-09-24 06:00 UTC, LinusMuema commented
> @josephodhis
> 
> [How to solve initial value problem using ode45 in Matlab #3689.pdf](https://github.com/section-engineering-education/engineering-education/files/7118025/How.to.solve.initial.value.problem.using.ode45.in.Matlab.3689.pdf)
> 
>  Good afternoon - I'll be running a final review on your PR when ready.
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
> Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
> Be sure to see our resources page to see more info on plagiarism and what is considered as such.

Hi @hectorkambow could you check the plagiarism issues you raised here to check if the article is ready for a final review...

2021-09-24 14:06 UTC, josephodhis commented
@LinusMuema the plagarism issue is corrected. please check

2021-09-29 12:16 UTC, josephodhis commented
@hectorkambow would you please check this.

2021-09-30 20:23 UTC, hectorkambow commented
plagiarism check done

2021-09-30 21:20 UTC, hectorkambow commented
@josephodhis 
Please be sure to go through the edits made by your peer reviewer and content moderator to improve future articles.

As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published.
Our team of peer reviewers do not provide revisions services at this time in order to review them all in a timely manner. 

All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

cc @lalith1403 
Please go through the edits as well. 👍

2021-09-30 21:20 UTC, merged