How password hashing occurs
section-engineering-education/engineering-education pull request #3718
Opened 2021-09-07 09:58 UTC by Koros-Meshack

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3554`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-07 12:13 UTC, Ericgacoki commented on content/articles/how-password-hashing-occurs/index.md
> +```
Please add the language identifier.

2021-09-07 18:20 UTC, Koros-Meshack commented on content/articles/how-password-hashing-occurs/index.md
> +```
changes made @Ericgacoki

2021-09-14 10:23 UTC, ahmadmardeni1 commented
plagiarism check done ✅

I think this article is light on substance. What do you think? @Ericgacoki

2021-09-14 12:18 UTC, Ericgacoki commented
Greetings @ahmadmardeni1, I think the author has covered quite enough content on hashing algorithms and hash tables. I also believe that there's a need to add more content to this article to make it stand out.

@Koros-Meshack, you can apply the existing knowledge to come up with a sample project that will help the readers understand this topic better.

2021-09-14 12:59 UTC, Koros-Meshack commented
Thanks for highlighting that @Ericgacoki
I'll make the necessary updates to add value to the article and add more content as you have mentioned
I'll ping you as soon as am done
cc: @ahmadmardeni1

2021-09-17 12:09 UTC, Koros-Meshack commented
I have made necessary changes and Content Addition @Ericgacoki

2021-09-17 16:01 UTC, Ericgacoki requested changes
Hello @Koros-Meshack, Nice tutorial -very easy to follow along. I have one suggestion attached below...

2021-09-19 08:32 UTC, Koros-Meshack commented on content/articles/how-password-hashing-occurs/index.md
> +```
All changes made @Ericgacoki 
Please continue with the review

2021-09-19 13:42 UTC, Ericgacoki approved these changes

2021-09-22 10:51 UTC, WanjaMIKE commented
Merged #3718 into master

2021-09-22 10:51 UTC, merged