Firestore data modeling and query customization in Android
section-engineering-education/engineering-education pull request #3730
Opened 2021-09-08 09:06 UTC by nonimdiana

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #2893

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-09 08:21 UTC, Ericgacoki requested changes
Awesome tutorial @nonimdiana. Kindly go through the comments attached below and let me know when you're done.

2021-09-09 08:21 UTC, Ericgacoki commented on content/articles/firestore-data-modeling-and-query-customization-in-android/index.md
> +- Be familiar with the Firebase Console.
I think Coroutines and ViewBinding knowledge is required too. I've seen you've implemented them in your code. Kindly include them and in this list.

2021-09-09 08:21 UTC, Ericgacoki commented on content/articles/firestore-data-modeling-and-query-customization-in-android/index.md
> +    android:layout_height="match_parent" >
This seems to be disarranged. Please format it properly.
> Hint: Press `Ctrl`+`Alt`+`l` to auto format your code.

2021-09-09 08:21 UTC, Ericgacoki commented on content/articles/firestore-data-modeling-and-query-customization-in-android/index.md
> +- `array-contains`: Checks if the value is present
I believe there are a few operators that you missed out. List them as well.

2021-09-14 10:34 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-15 19:34 UTC, Ericgacoki approved these changes

2021-09-28 08:43 UTC, WanjaMIKE commented
Well done gentlemen/lady. Nice to article. Keep up! @nonimdiana cc @Ericgacoki

2021-09-28 08:48 UTC, WanjaMIKE commented
Merged #3730 into master

2021-09-28 08:48 UTC, merged