Django kivy
section-engineering-education/engineering-education pull request #3740
Opened 2021-09-08 17:18 UTC by JohnKiguru

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-08 17:55 UTC, Qodestackr commented
Hi @JohnKiguru I'd like to be your test reviewer for this article :+1:

2021-09-09 02:54 UTC, srishilesh commented
@JohnKiguru 

On a quick glance, I don't think this article is ready for review.

I see that there are 2 `index.md` files - `content/articles/using-django-in-kivy-framework/index.md` and `content/articles/DjangoKivy/index.md`. Please remove the one that's not needed.

I suggest you rename the article to more meaningful one.

And, the image URLs are not right.

I would suggest you to take a look at your previous article reviews, correct them as needed, and make a ready to publish PR.

Thanks.

2021-09-09 04:49 UTC, JohnKiguru commented
I think I have done that...

2021-09-10 05:05 UTC, srishilesh commented
@JohnKiguru 

Looks good.

There's one more change left.

Rename `content/articles/DjangoKivy/` -> `content/articles/using-django-in-kivy-application/` for all the files.

2021-09-10 08:02 UTC, JohnKiguru commented
I think am done...

2021-09-10 10:55 UTC, srishilesh commented
@JohnKiguru 

Perfect. This looks good.

Will start the review soon.

2021-09-11 07:38 UTC, srishilesh requested changes
@JohnKiguru 

Great article.

I've suggested a few changes. Please let me know when done.

Make sure to perform a grammar check.

Thanks.

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Tasks Home Page](section-engineering-education/engineering-education/content/articles/using-djnago-in-kivy-application/tasks_home_page.png)
```suggestion
![Tasks Home Page](/engineering-education/content/articles/using-djnago-in-kivy-application/tasks_home_page.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Create Task Page](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/create_task_page.png)
```suggestion
![Create Task Page](/engineering-education/content/articles/using-django-in-kivy-application/create_task_page.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Task Created](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/task_created.png)
```suggestion
![Task Created](/engineering-education/content/articles/using-django-in-kivy-application/task_created.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Original Kivy App](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/original_kivy_app.png)
```suggestion
![Original Kivy App](/engineering-education/content/articles/using-django-in-kivy-application/original_kivy_app.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Creating The Action Bar](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/creating_the_action_bar.png)
```suggestion
![Creating The Action Bar](/engineering-education/content/articles/using-django-in-kivy-application/creating_the_action_bar.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Displaying Tasks from server](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/displaying_tasks_from_server.png)
```suggestion
![Displaying Tasks from server](/engineering-education/content/articles/using-django-in-kivy-application/displaying_tasks_from_server.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Creating a task](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/creating_a_task.png)
```suggestion
![Creating a task](/engineering-education/content/articles/using-django-in-kivy-application/creating_a_task.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +![Task submitted successfully](section-engineering-education/engineering-education/content/articles/using-django-in-kivy-application/task_submitted_successfully.png)
```suggestion
![Task submitted successfully](/engineering-education/content/articles/using-django-in-kivy-application/task_submitted_successfully.png)
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +We have learnt how create a kivy application and how to use Django in such applications. You can therefore
Conclusion could have been more elaborate.

Give a summary of what was covered.

Add a topic `Further reading` that lists out various reference links

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +Kivy is a popular library for developing applications that can run across all major platforms.
`developing applications`

Be specific. Applications can be anything -front end, backend. What does Kivy help to build?

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +using the `requests` library. We are going to use Django to develop the server that holds the data we want to manipulate.
Here, every sentence is in a new line.

If possible, make them into a paragraph. One para must talk about one idea

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +### Prerequisites.
Remove `.`

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +### Prerequisites.
Do this for all the topic headings

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +```
```suggestion
.
└── TodoAPI
    ├── manage.py
    ├── tasks
    │   ├── admin.py
    │   ├── apps.py
    │   ├── __init__.py
    │   ├── migrations
    │   │   └── __init__.py
    │   ├── models.py
    │   ├── tests.py
    │   └── views.py
    └── TodoAPI
        ├── asgi.py
        ├── __init__.py
        ├── settings.py
        ├── urls.py
        └── wsgi.py
```
```

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +    'rest_framework'
What are these for? Please explain if anything is specific to the app you are building

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +Let's create a `serializer.py` file that handles serialization and deserialization of task instances.Add the following lines of code to it:
`serialization and deserialization`

Explain in 1 - 2 lines about these, and reference links for these

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +We are going to also create some views to render data to a web page. There are different ways to create the views and we will use
Give 1 line explanation of what views are? And, what function-based views are?

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +
Explain this.

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +We then create a `urls.py` file to for routing our views. Create the file and add the following code:
Can we create a subtopic for this? Like `#### Routing views`.

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +We are going to also create some views to render data to a web page. There are different ways to create the views and we will use
Subtopic `#### Creating views`

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +]
Explain this mapping of routes with functions

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +]
Explain

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +of our application and every execution begins from there.
Make it into a paragraph.

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +```
` The description of what is happening will be explained after the code`

???

2021-09-11 07:38 UTC, srishilesh commented on content/articles/using-django-in-kivy-application/index.md
> +and see the "Home" text in the `HomeScreen` and "Add to list..." in the `AddScreen`
Make it as bulleted points

2021-09-12 21:09 UTC, hectorkambow commented
@JohnKiguru 
Good afternoon and thank you for submitting your topic to the EngEd program. 
If it seems this PR is still quite a bit aways from being completed. 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
All revisions and edits should be completed on your own forked repo (as to not create a huge backlog in the queue). 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself.

2021-09-13 02:36 UTC, srishilesh commented
@hectorkambow 

Reopening this PR , since the author has made requested changes.

Will close again if there's anymore changes left.

2021-09-14 10:36 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-15 14:49 UTC, srishilesh commented
I'll complete my review by tomorrow

2021-09-15 15:47 UTC, JohnKiguru commented
Great...

2021-09-20 14:02 UTC, srishilesh commented
I'll complete the review by today. Apologies for the delay

2021-09-20 17:33 UTC, srishilesh approved these changes
@JohnKiguru 

Thanks for making the changes.

It looks great now. The tutorial was very beginner friendly. Though, the code snippets were understandable, it could have been explained more briefly.

Please make sure to go through my commits.

Moving for the final review.

Thanks.

2021-09-22 06:37 UTC, JohnKiguru commented
No worries...

On Mon, 20 Sep 2021, 17:03 Srishilesh P S, ***@***.***> wrote:

> I'll complete the review by today. Apologies for the delay
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/3740#issuecomment-922957173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASTGUE7PHK35E3FZKHUJRILUC45JVANCNFSM5DVJ6JIA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-29 18:04 UTC, Kayere commented
Great article @JohnKiguru.
Thank you for the review @srishilesh.

2021-09-29 18:07 UTC, merged