Java native interface
section-engineering-education/engineering-education pull request #3744
Opened 2021-09-08 19:22 UTC by Shikomary

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3521 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-14 17:22 UTC, Shikomary commented
Hi, @BrianaNzivu 
Would you update me the progress of this PR please it has been quite some time with no updates.
Thank you.

2021-09-15 07:00 UTC, BrianaNzivu commented
Hey @Shikomary.
Apologies for the delay.
Working on it.

2021-09-15 14:30 UTC, Shikomary commented
Hello, @BrianaNzivu 
Aright thank you for the update

2021-09-15 17:57 UTC, BrianaNzivu requested changes
Hey @Shikomary 👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.
Good job on the article. It is a very interesting read.
Just a few changes I need you to make as we continue with the preliminary revisions:
- Each article in Section has its own structure on how it is written. For instance, your article is more of a how-to guide. Please check out this [document](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md) and try and structure your article according to this guide.
- Your article has quite a lot of grammatical mistakes and unclear sentences. You can use 
[Grammarly](https://app.grammarly.com/ddocs/1287976180) to correct it. 
-Please correct the spelling for your avatar image. Have it as `avatar.png`.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

2021-09-18 15:34 UTC, Shikomary commented
Hi @BrianaNzivu 
I have done the changes you requested but am unable to commit the changes in my branch. I will be glad for your help.
Thank you.

2021-09-18 17:49 UTC, Shikomary commented
Hi @BrianaNzivu 
I have done the changes that  you requested on the tutorial.
However am unable to change the name (avatar.png). Please guide me on that. 
Thank you.

2021-09-21 06:27 UTC, BrianaNzivu commented
> Hi @BrianaNzivu 
> I have done the changes that  you requested on the tutorial.
> However am unable to change the name (avatar.png). Please guide me on that. 
> Thank you.

Hey @Shikomary .
You can delete the current one on the PR and upload a new one.

2021-09-21 16:44 UTC, Shikomary commented
Hi, @BrianaNzivu 
I have done all the changes.
Thank You.

2021-09-21 20:47 UTC, BrianaNzivu commented
Still seeing two avatar images. Please delete the `avatar.png.jpg` one.

2021-09-21 20:49 UTC, BrianaNzivu commented on content/authors/mary-wanjiku/index.md
> +type: authors
Please do not make changes to the author bio.

2021-09-23 09:50 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-25 09:08 UTC, Shikomary commented
Hi, @BrianaNzivu 
I have changed the name of the author as it was initially.  You can update me on any issues you get.
Thank you.

2021-09-25 09:17 UTC, BrianaNzivu commented
> Hi, @BrianaNzivu 
> I have changed the name of the author as it was initially.  You can update me on any issues you get.
> Thank you.

It's ok.
I still need you to delete the extra avatar image...
The one labeled avatar.png.jpg

2021-09-25 19:20 UTC, Shikomary commented
hello, @BrianaNzivu 
I have deleted the avatar image.
Thank you.

2021-09-27 13:14 UTC, BrianaNzivu commented
Tech review done 👍

2021-09-27 13:24 UTC, BrianaNzivu approved these changes
Hey @FranciscaNg  👋 .
The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2021-09-28 09:47 UTC, Shikomary commented
Hi, @BrianaNzivu 
Thank you for reviewing my PR and for your guide. 
I appreciate that.

2021-09-29 19:50 UTC, Kayere commented
Congratulations for publishing your first article @Shikomary. Please go over the changes made by your peer reviewer and I to help improve the quality of your future articles.

Otherwise, awesome work done. We hope this is the first of many quality articles 🚀.

Thank you for the review @BrianaNzivu 🚀.

2021-09-29 19:51 UTC, merged