Building A Personality Test App with Java
section-engineering-education/engineering-education pull request #3767
Opened 2021-09-10 05:21 UTC by CaptainBKola

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

-[ ]@ahmadmardeni1 @hectorkambow @RuthAMare The duplicate to the article previously closed by    ###@hectorkambow.

2021-09-10 05:34 UTC, CaptainBKola commented
@ahmadmardeni1 @hectorkambow @RuthAMare.  duplicate to the article previously closed.

2021-09-10 07:21 UTC, RuthAMare requested changes
Hey @CaptainBKola .
Thanks for your determination to polish this article.
See the changes below and commit them when you're done incorporating them.
Also, space the work adequately especially the steps under building the personality test app. Leave at least a blank line before the next step.
Also, rename the branch on which you have opened this PR to building-a-personality-test-app-with-java instead of new-profile.

Let me know when you're done.

2021-09-10 07:21 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +We create an empty array like this;
```suggestion
We create an empty array like this:
```

2021-09-10 07:21 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +Whenever we declare and initialize an array with array literals, we wouldn't need the new keyword except for a boolean data type. We declare and initialize boolean values like this;
```suggestion
Whenever we declare and initialize an array with array literals, we wouldn't need the new keyword except for a boolean data type. We declare and initialize boolean values like this:
```

2021-09-10 07:21 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +In this file, define a class with the same name PersonalityTest like this;
```suggestion
In this file, define a class with the same name PersonalityTest like this:
```

2021-09-10 07:21 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +- [Explaining the Methods](#explaining-the-methods)
```suggestion
- [Explaining the methods](#explaining-the-methods)
```

2021-09-10 07:21 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +- [Introduction to Java Arrays](#introduction-to-java-arrays)
```suggestion
- [Introduction to Java arrays](#introduction-to-java-arrays)
- [How to create arrays](#how-to-create-arrays)
```

2021-09-10 07:21 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +#### This method serves questions and gets options
```suggestion
#### Method for serving questions and getting options
```

2021-09-10 20:38 UTC, CaptainBKola commented
everything is fine now @RuthAMare

2021-09-10 20:48 UTC, CaptainBKola commented
@RuthAMare  renaming a branch is while on pr is not technically feasible on github.

2021-09-10 20:48 UTC, CaptainBKola commented
@RuthAMare renaming a branch while on pr is not technically feasible on github.

2021-09-10 20:50 UTC, CaptainBKola commented
@RuthAMare, I can only close this pr and make new pr with a new branch and the old one deleted

2021-09-10 21:51 UTC, CaptainBKola commented
#Duplicate pull request

2021-09-10 22:21 UTC, CaptainBKola commented
Duplicate pull request

2021-09-12 09:21 UTC, RuthAMare commented
@CaptainBKola please add the title ### How to create arrays to the table of contents
It's part of the content but not listed on the table of contents

2021-09-12 09:22 UTC, RuthAMare commented on content/articles/myers-briggs-personality-test-app/index.md
> +- [Introduction to Java Arrays](#introduction-to-java-arrays)
The above is what I want you to add

2021-09-12 09:27 UTC, RuthAMare commented
Hey @ahmadmardeni1, @CaptainBKola seems to have fixed most of the issues apart from the above.

2021-09-12 21:38 UTC, CaptainBKola commented
Oh okay @RuthAMare thank you

2021-09-16 11:20 UTC, RuthAMare commented
Good Job @CaptainBKola.

2021-09-16 13:12 UTC, CaptainBKola commented
@RuthAMare thank you

2021-09-20 22:23 UTC, hectorkambow commented
👍 
Overall nice work @CaptainBKola 

cc @RuthAMare

2021-09-20 22:23 UTC, merged

2021-09-21 05:27 UTC, CaptainBKola commented
@hectorkambow @RuthAMare @ahmadmardeni1  thank you guys