uploading files
section-engineering-education/engineering-education pull request #3807
Opened 2021-09-12 10:20 UTC by Joshuathuo

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`
This closes 3591

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-13 10:39 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing. @Joshuathuo 
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

2021-09-13 13:14 UTC, paulodhiambo commented on content/articles/adding-custom-methods-for-linq-queries/index.md
> +By introducing extension methods to the IEnumerableT> interface, you may expand the set of methods available for LINQ queries. Any data sequence can be converted into one single value by creating you
change "Any data sequence can be converted into one single value by creating your custom aggregate method in SQL Server. " to "You can convert any data sequence into one value by creating your custom aggregate method in SQL Server. "

2021-09-13 13:15 UTC, paulodhiambo commented on content/articles/adding-custom-methods-for-linq-queries/index.md
> +You may apply your methods to any enumerable collection when you extend the IEnumerableT> interface. In this article, we shall deeply take a look at various custom methods that are used in LINQ queri
change "In this article, we shall deeply take a look at various custom methods that are used in LINQ queries in C#." to "In this article, we shall look at various custom methods used in LINQ queries in C#."

2021-09-13 13:16 UTC, paulodhiambo commented on content/articles/adding-custom-methods-for-linq-queries/index.md
> +To accept sequences of different types, you can overload your aggregate method. Overloading each type is the typical technique. It's also possible to use a delegate to build an overload for a generic
consider rewriting "It's also possible to use a delegate to build an overload for a generic type. Combining both approaches is also an option." to "However, it's also possible to use a delegate to build an overload for a generic type. Combining both approaches is also an option."

2021-09-13 13:20 UTC, paulodhiambo requested changes
@Joshuathuo, make the requested changes and ping me when done.

2021-09-13 13:37 UTC, Joshuathuo commented
@paulodhiambo I have done the edits you can please have a look

2021-09-15 11:23 UTC, ahmadmardeni1 commented
plagiarism check done ✅
I think this article is light on substance - What do you think? @paulodhiambo

2021-09-18 06:35 UTC, Joshuathuo commented
@paulodhiambo  may I know the status update on this PR kindly??

2021-09-26 17:34 UTC, paulodhiambo commented
@Joshuathuo please consider explaining how to add the LINQ queries in a real application scenario.

2021-09-28 08:56 UTC, Joshuathuo commented
A LINQ query is added say after maybe one has created a data source  and the a query is added as follows as an example

// Adding the query
//  "var cityQuery ="
IEnumerable<Cities> cityQuery =
    from city in cities
    where city.Population[0] > 10,000
    select city;

2021-10-05 13:52 UTC, Joshuathuo commented
@paulodhiambo  please consider my comment above

2021-10-05 14:18 UTC, paulodhiambo commented
@Joshuathuo your article is good but short, that's why I requested you to explain how we can use LINQ queries in a real application scenario. For example, try retrieving some data from the from an API like [JSON API](https://jsonplaceholder.typicode.com/) then apply the LINQ query to response, this would be more helpful.

2021-10-08 09:24 UTC, Joshuathuo commented
@paulodhiambo  I have a question. Should I add it at the end of the article or where specifically should I add it

2021-10-08 10:01 UTC, Joshuathuo commented
@paulodhiambo  I have added it you can have a look

2021-10-10 07:01 UTC, Joshuathuo commented
I have just updated @paulodhiambo  you can have a look at it now

2021-10-13 17:09 UTC, merged