Geofencing in android with kotlin
section-engineering-education/engineering-education pull request #3819
Opened 2021-09-13 13:25 UTC by brandy-kay

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #3440

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-13 13:39 UTC, brandy-kay commented
hello @Ericgacoki have added hero image

2021-09-15 11:27 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Geofencing in Android with Kotlin](https://github.com/section-engineering-education/engineering-education/files/7169607/New.Scan.11_17.AM.Copyleaks.Report.pdf)

2021-09-16 14:24 UTC, brandy-kay commented
hello @ahmadmardeni1 and @Ericgacoki i have fixed the plagiarism the most percentage is raised by code part which can't be changed because they are  built-in methods.

2021-09-18 10:10 UTC, ahmadmardeni1 commented
The % is still high, but most of it is the code. Please let me know if it can't be changed/edited as Brandy said. @Ericgacoki 

[Geofencing in Android with Kotlin](https://github.com/section-engineering-education/engineering-education/files/7189708/New.Scan.10_05.AM.Copyleaks.Report.pdf)

2021-09-18 10:56 UTC, Ericgacoki commented
@ahmadmardeni1,
As Brandy mentioned, most of the code consist of inbuilt and lifecycle callback methods that can't be edited. These methods are applicable in numerous use cases including Geo-Fencing. I think that's what is causing a high plagiarism.

Do you think I should proceed with the review?

2021-09-19 10:34 UTC, ahmadmardeni1 commented
Okay, then no problem. 
Yes, proceed with the review, please. @Ericgacoki

2021-09-19 22:51 UTC, Ericgacoki requested changes
Hi @brandy-kay, kindly fix the following issues and ping me when you're done!

2021-09-19 22:51 UTC, Ericgacoki commented on content/articles/geofencing-in-android-with-kotlin/index.md
> +            }
I can't seem to find where these codes (Request code and Result code) were initialized 🤭. Kindly assign them some values.

2021-09-19 22:51 UTC, Ericgacoki commented on content/articles/geofencing-in-android-with-kotlin/index.md
> +            client.checkLocationSettings(builder.build())
...
I think a lot is happening in this snippet. Add an explanation either via comments or a plain text just below the code.

2021-09-19 22:51 UTC, Ericgacoki commented on content/articles/geofencing-in-android-with-kotlin/index.md
> +            .setExpirationDuration(Geofence.NEVER_EXPIRE)
These arguments are also not initialized. Kindly give a sample value for the `latitude`, `longitude`, and `radius`.

2021-09-22 16:59 UTC, brandy-kay commented
Hello @Ericgacoki  have made the requested changes

2021-10-05 22:42 UTC, Ericgacoki approved these changes

2021-10-06 07:17 UTC, WanjaMIKE commented
Merged #3819 into master

2021-10-06 07:17 UTC, merged