How to build a simple router using window event listeners in JavaScript
section-engineering-education/engineering-education pull request #3835
Opened 2021-09-14 11:36 UTC by nancy-maina

### Article checklist

#### Pre-submission checks
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #3307

2021-09-14 11:40 UTC, geoffrey45 commented
@nancy-maina Please add a hero image for your article.

2021-09-14 11:46 UTC, nancy-maina commented
@geoffrey45 I have added a hero image.

2021-09-15 11:46 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-16 12:34 UTC, geoffrey45 commented
@nancy-maina Your article is 610 words minus the code. Please update your article to reach the minimum requirements. ie 750 words.

2021-09-22 19:42 UTC, geoffrey45 requested changes
@nancy-maina Please check the comments below.

2021-09-22 19:42 UTC, geoffrey45 commented on content/articles/js-router/index.md
> +
Please provide an example of such a router and leave a link to it.

2021-09-22 19:42 UTC, geoffrey45 commented on content/articles/js-router/index.md
> +
Add a link to the arrow functions MDN docs page.

2021-09-30 19:07 UTC, geoffrey45 commented
@nancy-maina

2021-10-01 11:47 UTC, nancy-maina commented
I hav made the changes @geoffrey45

2021-10-04 09:43 UTC, geoffrey45 commented on content/articles/js-router/index.md
> +    link.innerText = 'About';
@nancy-maina The link: `#about` throws an error. Please change it to `#/about`

2021-10-04 09:43 UTC, geoffrey45 commented on content/articles/js-router/index.md
> +    link.innerText = 'Home';
The link `#home` should be `#/`. There is no route defined as `home` in your code.

2021-10-04 10:05 UTC, nancy-maina commented
Hello @geoffrey45

I have made all the changes that you requested. Please check now.

2021-10-05 10:45 UTC, WanjaMIKE commented
Nice job guys. @nancy-maina @geoffrey45

2021-10-05 10:47 UTC, WanjaMIKE commented
Merged #3835 into master

2021-10-05 10:47 UTC, merged