Initial Commit
section-engineering-education/engineering-education pull request #3876
Opened 2021-09-16 18:09 UTC by tanmay69

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-09-19 10:44 UTC, ahmadmardeni1 commented
plagiarism check done ✅

2021-09-22 15:25 UTC, lalith1403 requested changes
Very well written article. Congratulations on an excellent first article. Look forward to reading many more :)

Few minor changes and this should be good to go.

2021-09-22 15:25 UTC, lalith1403 commented on content/articles/building-spotify-recommendation-engine/index.md
> +- Implementing a Spotify playlist Recommender Engine from scratch using Python
You should talk about the lapses of a recommendation system. Where does it fail as a system and what precautions should one take?

2021-09-22 15:25 UTC, lalith1403 commented on content/articles/building-spotify-recommendation-engine/index.md
> +- User-item interactions: Information that defines user-item relationship(rating, like/dislike, etc.)
relationship (rating, like/dislike, etc.) 

Add space here.

2021-09-22 15:25 UTC, lalith1403 commented on content/articles/building-spotify-recommendation-engine/index.md
> +As in this blog, the recommender system that we will implement is based on Content-Based Filtering. Therefore, we are going to limit our discussion of the Collaborative-Filtering system up to its def
Add some sources that describe this in detail.

2021-09-22 15:25 UTC, lalith1403 commented on content/articles/building-spotify-recommendation-engine/index.md
> +Firstly open the Spotify Web API [dashboard](https://developer.spotify.com/dashboard/login). Log in using your Spotify account credentials. After logging in, your homepage will look something like th
Add a link to an article that talks about registration as well.

2021-09-22 15:25 UTC, lalith1403 commented on content/articles/building-spotify-recommendation-engine/index.md
> +!pip install spotipy
Mention that you are working on a jupyter notebook. Else, make it generic and remove the !.

2021-09-22 15:25 UTC, lalith1403 commented on content/articles/building-spotify-recommendation-engine/index.md
> +Using the concept of cosine similarity, we have seen that we were able to generate recommendations of songs that are similar to our playlist. But we have to note that Recommendation Systems are not p
Add a link to the colab notebook containing the entire code. This will ensure reproducibility of the code.

2021-09-22 15:28 UTC, tanmay69 commented
Thank you.
Will make the necessary changes.

Regards,
Tanmay


On Wed, 22 Sep 2021, 20:55 Lalithnarayan C, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Very well written article. Congratulations on an excellent first article.
> Look forward to reading many more :)
>
> Few minor changes and this should be good to go.
> ------------------------------
>
> In content/articles/building-spotify-recommendation-engine/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/3876#discussion_r714047964>
> :
>
> > +- [Implementation](#implementation)
> +  - [Feature Engineering](#feature-engineering)
> +  - [Connecting to Spotify Web API](#connecting-to-spotify-web-api)
> +  - [Creating Playlist Vector](#creating-playlist-vector)
> +  - [Generating Recommendations](#generating-recommendations)
> +- [Conclusion](#conclusion)
> +
> +### Prerequisites
> +The reader should have basic knowledge of python libraries like [pandas](https://pandas.pydata.org/), [numpy](https://scikit-learn.org/stable/), [scikit-learn](https://scikit-learn.org/stable/), and the basics of vector algebra. Also, readers are requested to go through the documentation of the [Spotipy](https://spotipy.readthedocs.io/en/2.19.0/) library. *Spotipy* is a lightweight Python library that we will be using to access the [Spotify Web API](https://developer.spotify.com/documentation/web-api/).
> +
> +### Key takeaways
> +By the end of this blog, you will know the following:
> +- How Recommendation Systems work
> +- Types of Recommendation Systems
> +- Mathematics behind Recommendation Systems
> +- Implementing a Spotify playlist Recommender Engine from scratch using Python
>
> You should talk about the lapses of a recommendation system. Where does it
> fail as a system and what precautions should one take?
> ------------------------------
>
> In content/articles/building-spotify-recommendation-engine/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/3876#discussion_r714048983>
> :
>
> > +### Prerequisites
> +The reader should have basic knowledge of python libraries like [pandas](https://pandas.pydata.org/), [numpy](https://scikit-learn.org/stable/), [scikit-learn](https://scikit-learn.org/stable/), and the basics of vector algebra. Also, readers are requested to go through the documentation of the [Spotipy](https://spotipy.readthedocs.io/en/2.19.0/) library. *Spotipy* is a lightweight Python library that we will be using to access the [Spotify Web API](https://developer.spotify.com/documentation/web-api/).
> +
> +### Key takeaways
> +By the end of this blog, you will know the following:
> +- How Recommendation Systems work
> +- Types of Recommendation Systems
> +- Mathematics behind Recommendation Systems
> +- Implementing a Spotify playlist Recommender Engine from scratch using Python
> +
> +### Introduction
> +#### What is a Recommendation System?
> +A Recommendation System aims to predict the user's choices and recommend the product or service that is likely to be interesting. These systems can do so because of user data. The function of a Recommendation System mainly depends on two kinds of information:
> +
> +- Characteristic information: Information that defines the profile of a product(tag, category, etc.) or a user(preferences, profile, etc.)
> +- User-item interactions: Information that defines user-item relationship(rating, like/dislike, etc.)
>
> relationship (rating, like/dislike, etc.)
>
> Add space here.
> ------------------------------
>
> In content/articles/building-spotify-recommendation-engine/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/3876#discussion_r714054160>
> :
>
> > +
> +To understand it better, let us take an example of two items, item 1 and item 2, and two features $x_1$ and $x_2$, which define an item. The plot below represents item 1 and item 2 as vectors in a feature space.
> +
> +![cosine-similarity](/engineering-education/building-spotify-recommendation-engine/cosine-similarity.png)
> +
> +The lesser the angle between vectors more the cosine similarity.
> +
> +#### Collaborative Filtering
> +
> +Collaborative filtering systems use user-item interactions to generate recommendations. This means collaborative filtering uses similarities between users and items simultaneously to provide recommendations. To explain it better, let us refer to the diagram below.
> +
> +![collaborative-filtering](/engineering-education/building-spotify-recommendation-engine/collaborative-filtering.jpg)
> +
> +As we can see in the diagram, there are two users, user A, and user B. Both users have similar taste in music as both of them liked song-1 and song-2, but there is a song-3 which user A likes, but user B never listened to it. The system will recommend song-3 to user A based on these user-item interactions.
> +
> +As in this blog, the recommender system that we will implement is based on Content-Based Filtering. Therefore, we are going to limit our discussion of the Collaborative-Filtering system up to its definition.
>
> Add some sources that describe this in detail.
> ------------------------------
>
> In content/articles/building-spotify-recommendation-engine/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/3876#discussion_r714055257>
> :
>
> > +![collaborative-filtering](/engineering-education/building-spotify-recommendation-engine/collaborative-filtering.jpg)
> +
> +As we can see in the diagram, there are two users, user A, and user B. Both users have similar taste in music as both of them liked song-1 and song-2, but there is a song-3 which user A likes, but user B never listened to it. The system will recommend song-3 to user A based on these user-item interactions.
> +
> +As in this blog, the recommender system that we will implement is based on Content-Based Filtering. Therefore, we are going to limit our discussion of the Collaborative-Filtering system up to its definition.
> +
> +#### How to use Spotify Web API to fetch data
> +
> +For this blog, we will implement a custom playlist recommender for which we will require our current Spotify playlist data, using which we will further generate recommendations.
> +For this purpose, Spotify provides a web API to create a custom application and fetch Spotify data. The Spotify Web API endpoints return JSON metadata about music artists, albums, and tracks directly from the Spotify Data Catalogue based on simple REST principles.
> +
> +![api](/engineering-education/building-spotify-recommendation-engine/web-api.jpg)
> +
> +**Simple steps to use Spotify Web API**
> +
> +Firstly open the Spotify Web API [dashboard](https://developer.spotify.com/dashboard/login). Log in using your Spotify account credentials. After logging in, your homepage will look something like this:
>
> Add a link to an article that talks about registration as well.
> ------------------------------
>
> In content/articles/building-spotify-recommendation-engine/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/3876#discussion_r714055991>
> :
>
> > +![dashboard](/engineering-education/building-spotify-recommendation-engine/dashboard.png)
> +
> +Now click on create an application. This will generate a unique client id and password, which will be used further.
> +And now open the application.
> +
> +![application-page](/engineering-education/building-spotify-recommendation-engine/spotify-api.png)
> +
> +Finally, go to the edit settings options and add your localhost URL. It will be used for user authentication later. And now we are all set to implement a Spotify-based playlist recommender system.
> +
> +
> +### Implementation
> +
> +To access the Spotify Web API, we will use a python-based library known as Spotipy, so let us first install this library.
> +
> +```python
> +!pip install spotipy
>
> Mention that you are working on a jupyter notebook. Else [...]

2021-09-23 11:19 UTC, louisefindlay23 commented
@tanmay69, welcome to the programme. Quick note: please ollow the Topic suggestion this closes instructions in the PR template correctly to link your topic suggestion to your PR. This helps ensure a swift payout.

You should remove the backticks from the line below and add your issue number there.

2021-09-23 17:43 UTC, tanmay69 commented
@lalith1403 I have updated the required changes.

2021-10-07 20:39 UTC, hectorkambow commented
Overall nice work gents

2021-10-07 20:44 UTC, merged