How to create a font chooser App
section-engineering-education/engineering-education pull request #4177
Opened 2021-10-06 08:46 UTC by majiezra

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4082 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-15 02:21 UTC, geoffrey45 requested changes
@majiezra Please check the comments below.

2021-10-16 22:25 UTC, majiezra commented on content/articles/how-to-create-font-chooser-app/index.md
> +```
Done @geoffrey45

2021-10-20 21:43 UTC, geoffrey45 requested changes
Hello @majiezra 👋

Your article looks good. Just a few issues.

You have spent a large chunk of the article talking about the GUI and Tkinter for data analysis. Yet, your article aims at guiding the reader on building a font chooser application using Tkinter.

I feel like you should be talking more about fonts, how they work, or something related to fonts and what your article aims at helping the reader achieve.

Please don't stray away from the topic of discussion.

If you feel like the history of the GUI and how Tkinter can be used for data analysis is something the readers need to know, please leave external links to published material containing the information.

Feel free to dedicate a whole new article to this topics.

Please remove this unrelated areas, and replace them with content that is related to what your article is talking about.

2021-10-20 21:43 UTC, geoffrey45 commented on content/articles/how-to-create-font-chooser-app/index.md
> +- It is simple to use.
1st statement in this list:

The GUI is not simple to use. It's simpler than the CLI. Please update your statement to reflect this.

2021-10-20 21:43 UTC, geoffrey45 commented on content/articles/how-to-create-font-chooser-app/index.md
> +- It allows more than one application and program to run at the same time.
The 3rd point in this list is not fully true. The CLI can also run multiple applications simultaneously using background processes.

Please update your statement to use well defined words like "multitasking", etc.

2021-10-20 21:43 UTC, geoffrey45 commented on content/articles/how-to-create-font-chooser-app/index.md
> +- It is self-explanatory.
The 5th statement in this list:

The meaning of the word "self-explanatory" is "[capable of being understood without explanation](https://www.merriam-webster.com/dictionary/self-explanatory#:~:text=:%20explaining%20itself%20:%20capable%20of%20being%20understood%20without%20explanation)". The self-explanatory-ness of a GUI depends on how simple or complex it is.

Please remove or update this statement  to enhance the correctness.

2021-10-20 21:43 UTC, geoffrey45 commented on content/articles/how-to-create-font-chooser-app/index.md
> +```
Properly format your code blocks.

2021-10-20 21:43 UTC, geoffrey45 commented on content/articles/how-to-create-font-chooser-app/index.md
> +```
Properly format your code blocks.

2021-10-20 21:43 UTC, geoffrey45 commented on content/articles/how-to-create-font-chooser-app/index.md
> +
Please include the author of this book in this reference. ie. `Python GUI programming with Tkinter - By author name`

2021-10-21 19:34 UTC, hectorkambow commented
@majiezra 

As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
All revisions and edits should be completed on your own forked repo (as to not build up a backlog in the queue). 

cc @geoffrey45 
If during the tech review we discover the PR still needs more work - we can close this PR and have the author re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself.

2021-10-22 08:49 UTC, closed without merging