How to create and run a .NET Unit Testing Project
section-engineering-education/engineering-education pull request #4188
Opened 2021-10-06 21:40 UTC by Ushter21

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3596 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-17 15:40 UTC, zolomohan requested changes

2021-10-17 15:40 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +   > If you are unable to access the Program.cs file directly, you may do so by double-clicking it in Solution Explorer.
Please add screenshots for visual guidance.

2021-10-17 15:40 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +6. When you open the Reference Manager dialog box, expand Projects, select Solution, and select College from the Reference Manager drop-down menu. Click OK to continue.
Please add screenshots for visual guidance.

2021-10-17 15:40 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +4. To explore more about a technique, open Test Explorer and click on the technique's name.
Please add screenshots for visual guidance.

2021-10-17 15:40 UTC, zolomohan commented
Hi @Ushter21. Please add screenshots for visual guidance. Ping me when done.

2021-10-17 15:47 UTC, zolomohan requested changes

2021-10-17 15:47 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +    private readonly string n_studentName;
The variable name is `n_studentName` here but `n_studentIdentity` is being used below.

2021-10-17 15:47 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +    }
Duplicate code? These functions have the same name with the same signature. The second function has one if condition missing.

2021-10-17 15:47 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +      ba.Balance(754.50);
Balance is not definend.

2021-10-17 15:47 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +      Console.WriteLine("Current Balance is ${0}", ba.Balance;
There is no get for ba.Balance?

2021-10-17 15:47 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +  double actual = finance.AdmNo;
The get is set as `admNo` but here it's `AdmNo`

2021-10-17 15:47 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +  Assert.AreEqual(expected, actual, 2334, "Fees not summed correctly");
What is the 3rd argument `2334`?

2021-10-20 17:40 UTC, hectorkambow commented
@Ushter21 
Good afternoon and thank you for submitting your topic to the EngEd program. It seems this PR is still quite a bit aways from being completed. 
As a rule of thumb - please only submit articles (pull requests) with a **complete and fully polished article - ready to be published.** 
All revisions and edits should be completed on your own forked repo (as to not build up a backlog in the queue). 

We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 


cc @zolomohan

2021-10-20 17:40 UTC, closed without merging