End to End Speech Recognition with Deep Recurrent Neural Networks (RNNs)
section-engineering-education/engineering-education pull request #4261
Opened 2021-10-10 11:40 UTC by extravaganza77

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4075

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-12 21:09 UTC, extravaganza77 commented
@lalith1403 
Just a request, would you help me remove the backticks.

2021-10-31 11:38 UTC, extravaganza77 commented
@lalith1403 
requested changes are in place

2021-11-01 16:57 UTC, lalith1403 requested changes
Several errors exist. Would you please rectify all the errors? Unfortunately, another round of revision will lead to the closure of the article.

2021-11-01 16:57 UTC, lalith1403 commented on content/articles/End-to-end-speech-recognition-with-deep-Recurrent-Neural-Networks(RNNs)/index.md
> +![CTC.jpg](CTC.jpg)
Check the image format required to publish articles.

\!\[CTC.jpg\]\(/End-to-end-speech-recognition-with-deep-Recurrent-Neural-Networks(RNNs)/CTC.jpg\) 

Additionally, shorten the name of the folder. The current name of the folder is too long for SEO purposes.

2021-11-01 16:57 UTC, lalith1403 commented on content/articles/End-to-end-speech-recognition-with-deep-Recurrent-Neural-Networks(RNNs)/index.md
> +### `Encoding texts in CTC`
No need to use any highlighting for headings.

2021-11-01 16:57 UTC, lalith1403 commented on content/articles/End-to-end-speech-recognition-with-deep-Recurrent-Neural-Networks(RNNs)/index.md
> +Whаt tо dо when the сhаrасter tаkes mоre thаn оne time steр in the imаge is а рrоblem with аррrоасhes thаt dо nоt use СTС. In this саse, а nоn-СTС аррrоасhes wоuld fаil, resulting in reрeаted сhаrасt
Divide the paragraphs into smaller paragraphs. Well explained.

2021-11-01 16:57 UTC, lalith1403 commented on content/articles/End-to-end-speech-recognition-with-deep-Recurrent-Neural-Networks(RNNs)/index.md
> +We need CRNN to provide us with output on unseen textual content photos because it has been tortured. To position it in another manner, we need the most likely text given a CRNN output matrix. Analyz
To put it in simpler words, we need the most likely text given a CRNN output matrix.

2021-11-01 16:57 UTC, lalith1403 commented on content/articles/End-to-end-speech-recognition-with-deep-Recurrent-Neural-Networks(RNNs)/index.md
> +For sequencing duties with an uncertain alignment between the input sequence, X, and the output targets, Y, Graves proposed the RNN-T as an extension of the cognitive scientist's temроrаl сlаssifiсаt
What are duties?

2021-11-02 00:12 UTC, hectorkambow commented
@lalith1403 

 @extravaganza77 
Good afternoon and thank you for submitting your topic suggestion.
 
It seems this PR is still quite a bit aways from being completed. As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
**We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself.** 

**Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.**
 
👍

2021-11-02 00:12 UTC, closed without merging