Object Oriented Programming in Python
section-engineering-education/engineering-education pull request #4284
Opened 2021-10-11 21:29 UTC by Temmy5113

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #2606

2021-10-15 01:49 UTC, geoffrey45 requested changes
@Temmy5113 Your article is 680 words (minus code) which is relatively shorter than the required article length (750 words). Please add more content to your article to meet the minimum requirements.

2021-10-15 01:49 UTC, geoffrey45 commented on content/articles/object-oriented-programming-in-python/index.md
> +```python
Explain this using words and not code. You are introducing the reader to this concepts, so the reader doesn't understand the code.

2021-10-17 01:50 UTC, Temmy5113 commented
@geoffrey45 changes have been made

2021-10-20 22:10 UTC, geoffrey45 commented on content/articles/object-oriented-programming-in-python/index.md
> +
@Temmy5113 Please explain both of these statements more clearly.

2021-11-01 18:37 UTC, geoffrey45 commented
@Temmy5113 Please create an author folder in the `/content/authors`. The folder carries your author photo and bio. Feel free to check the other student's folders.

2021-11-02 00:15 UTC, hectorkambow commented
@geoffrey45 

Is that all this PR needs? To be ready for a final review?

2021-11-02 07:36 UTC, geoffrey45 commented
@hectorkambow Yes. Only the author folder

2021-11-03 07:06 UTC, Temmy5113 commented
@geoffrey45 made the necessary adjustment

Cc: @hectorkambow

2021-11-04 06:45 UTC, WanjaMIKE commented on content/articles/object-oriented-programming-in-python/index.md
> +For the last four years, security researchers have reported a tremendous increase in security breaches. About 20-30,000 websites get hacked every day. There are several ways websites get hacked, XML
@mercymeave I believe, you copied the wrong description in the front matter. Am I right?

2021-11-04 10:10 UTC, WanjaMIKE commented
Merged #4284 into master

2021-11-04 10:12 UTC, merged