Getting started with Principal Component Analysis with sklearn in python
section-engineering-education/engineering-education pull request #4372
Opened 2021-10-14 18:03 UTC by nelsonnrl

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4213

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-17 16:13 UTC, srishilesh requested changes
@nelsonnrl 

Great article.

You've not got into the math behind PCA. It would be better if you explain that as well.

**IMPORTANT: Please move you article folder to `/content/articles`, and the author folder to `/content/authors`**

Currently, it's in the root folder.

Make sure to modify the image paths, and explain code snippets.

Ping me when the changes are done.

Thanks.

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +In Machine learning, it is common to come across data sets with hundreds or even thousands of features. Implementing models on such datasets can be challenging in terms of computational cost. Also, m
Explain about dimensionality in-detail

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +*Dimensionality Reduction* involves transforming features of a high-dimensional space dataset to a low-dimensional space. Some of the techniques used in the *dimensionality reduction* include *PCA, L
Add `Table of contents` section

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +For more knowledge on the mathematical concept behind the PCA algorithm, I recommend you read this [article](https://www.section.io/engineering-education/image-compression-using-pca/).
```suggestion
For more knowledge on the mathematical concept behind the PCA algorithm, I recommend you read this [article](/engineering-education/image-compression-using-pca/).
```

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +This article will teach how to implement the PCA algorithm in python using the sklearn library. In this implementation, we will work with a structured dataset that we can download [here]().
Link not added

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +The dataset we are applying PCA on in this session consists of features of different types of wine, with the target variable consisting of the customer segment to which a wine belongs. We can downloa
Add link

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +
Before pre-processing, explain about the dataset. Use `head()` and display the first 5 rows. Explain what we are going to do with the dataset

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +
Explain about the number of components

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +accuracy_score(y_test, y_pred)
Explain

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +
Explain. 

Add necessary links

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +X_test = pca.transform(X_test)
Explain

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +From our results above, we notice the model we implemented on our new dataset has an accuracy of 97.2%. This is an indication that not only was the PCA was able to reduce the model complexity by redu
Break down this paragraph. It's too big.

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +plt.legend()
Explain

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +
Explain

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +*c* argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with *x* & *y*.  Please use the *color* keyword
Isn't this a warning that you get when we plot graphs?

If so, you can just remove this

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +![image](/engineering-education/logistic-regression-in-python/logistic_test_set.png)
Change image path

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +![image](/engineering-education/logistic-regression-in-python/image.png)
```suggestion
![image](/engineering-education/principal-component-with-sklearn-in-python/image.png)
```

2021-10-17 16:13 UTC, srishilesh commented on principal-component-with-sklearn-in-python/index.md
> +In this article, we've learned steps involve in the PCA algorithm. Lastly, we showed how to implement this algorithm in python. Our implementation showed the importance of PCA, such as reducing the c
Add a `Further reading` section

2021-10-20 10:29 UTC, LinusMuema commented
Hi @srishilesh 
Please add the plagiarism check label once @nelsonnrl makes all the necessary changes and you approve of them.

2021-10-21 20:55 UTC, hectorkambow commented
Pinged the reviewer via Slack as well

2021-11-06 22:26 UTC, hectorkambow commented
jumping on this one

2021-11-06 23:08 UTC, hectorkambow commented
@nelsonnrl 
Please go over any final edits I may have made to further improve future articles and reviews. 

cc @srishilesh

2021-11-06 23:12 UTC, hectorkambow commented
@nelsonnrl FYI - any future PR that requires this level of revision will be closed immediately to allow you to make any required edits. 👍

2021-11-06 23:12 UTC, merged