sentiment analysis implementation with naive bayes algorithms
section-engineering-education/engineering-education pull request #4405
Opened 2021-10-15 13:23 UTC by wizardcalidad

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-15 13:28 UTC, wizardcalidad commented
@lalith1403 
@hectorkambow

2021-10-17 09:21 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-10-29 18:28 UTC, lalith1403 requested changes
This is a detailed article. Here are the suggestions to improve the readability.

1. Outline the various algorithms that will be covered in this article and give a brief overview of what the reader can expect from the article.
2. Explain the code. Explain the thought process behind writing code. Why are you writing it? How are you writing it? What factors are you taking into consideration?
3. There are several indentation errors in the code. Correct it.

Additionally, add a link to a notebook for each algorithm separately. This way, the reader will be able to reproduce the code efficiently. 

Overall, excellent work.

2021-10-29 18:28 UTC, lalith1403 commented on content/articles/sentiment-analysis-with-naive-bayes-algorithms/index.md
> +The Bayesian theorem is the core principle behind Naive Bayes algorithms. It assumes that all features are independent of one another. Thus, we can as well say that the classifier believes that one p
The independence notion is incorrect. The data samples are independent of each other, not the attributes of the data. Please correct the entire paragraph.

2021-10-29 18:28 UTC, lalith1403 commented on content/articles/sentiment-analysis-with-naive-bayes-algorithms/index.md
> +Categorical and Gaussian naive Bayes models keep flagging errors because they can't take the samples of data provided all at once for some reason which might be due to memory allocation. Therefore, a
Identify the cause of the problem. Raising unanswered questions might confuse the reader.

2021-10-29 18:28 UTC, lalith1403 commented on content/articles/sentiment-analysis-with-naive-bayes-algorithms/index.md
> +    train_texts = []
Error in code formatting.

2021-10-29 18:28 UTC, lalith1403 commented on content/articles/sentiment-analysis-with-naive-bayes-algorithms/index.md
> +    train_texts = []
Indentation error

2021-11-06 00:29 UTC, hectorkambow commented
@wizardcalidad 

Closing this PR to clear up the queue - no rush if you are still working through any required edits/revisions 👍 

Can be reopened at any time (or a new fresh PR can be created) when ready.

2021-11-06 00:29 UTC, closed without merging