Servlet: filter API
section-engineering-education/engineering-education pull request #4461
Opened 2021-10-17 20:27 UTC by Tumorbenson

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4142

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-19 16:22 UTC, Tumorbenson commented
How are you doing, @BrianaNzivu? I'd like to know how far along the review of this article is, and if there are any changes or modifications you'd like me to make.

2021-10-20 11:10 UTC, BrianaNzivu requested changes
Hey @Tumorbenson 👋  .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

Good job on the article. It is a very interesting read.

Just a few changes I need you to make as we continue with the preliminary revisions:
- Your article has quite a lot of grammatical mistakes and unclear sentences. You can use 
[Grammarly](https://app.grammarly.com/ddocs/1287976180) to correct it. 
- I have noticed some of your images are large. All your images including your avatar image should be scaled down to 600 x 400 px as required. You can use [Befunky](https://www.befunky.com/) to do this.
- Please rename your png images from `PNG` to `png`.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

2021-10-20 11:10 UTC, BrianaNzivu commented on content/articles/Servlet-Filter-API/index.md
> +- [Conclusion](#conclusion)
You forgot to mention the goals/key takeaways of this article. Have it before the table of contets.

2021-10-20 11:10 UTC, BrianaNzivu commented on content/articles/Servlet-Filter-API/index.md
> +**Step 3:** Filter 1 and `com.demo` package:
Have the step headings as h4 by that I mean (####)

2021-11-01 10:51 UTC, Kayere commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Servlet_ filter API #4461 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7452534/Servlet_.filter.API.4461.Copyleaks.Report.pdf)

2021-11-01 16:46 UTC, Tumorbenson commented
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [Servlet_ filter API #4461 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7452534/Servlet_.filter.API.4461.Copyleaks.Report.pdf)

@Kayere  I'm done.

2021-11-02 09:35 UTC, Kayere commented
@Tumorbenson - It is now at 16%

[(Second check) Servlet_ filter API #4461 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7459460/Second.check.Servlet_.filter.API.4461.Copyleaks.Report.pdf)

2021-11-02 16:05 UTC, Tumorbenson commented
> @Tumorbenson - It is now at 16%
> 
> [(Second check) Servlet_ filter API #4461 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7459460/Second.check.Servlet_.filter.API.4461.Copyleaks.Report.pdf)

Hello @Kayere? Imports of Java code and inbult methods account for the majority of the total plag. If I try to delete or edit the code, it will not fully execute.
Thank you.

2021-11-04 09:47 UTC, BrianaNzivu commented on content/articles/Servlet-Filter-API/index.md
> +#### Step 1:
Please give a brief title for this steps and all the other steps i.e
Step one: Creating a file

2021-11-04 17:13 UTC, BrianaNzivu approved these changes
Hey @Tumorbenson   👋 .
I would love to sincerely apologize for the delayed review on your article.
The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. I'd like to recommend taking Google's technical writing [course](https://developers.google.com/tech-writing) which is absolutely free and can come in handy.
3. Lastly please go through **ALL** the corrections I have made so that you can not repeat the same mistakes.
4.  Don't  forget to name your images properly and to always have their size as 600 x 400 px.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2021-11-13 15:53 UTC, ahmadmardeni1 commented
👋 Thank you very much for contributing your 1st article - and Welcome to the EngEd Program. @Tumorbenson 

There are some significant readability challenges/grammar mistakes/unclear sentences in your article. You are not explaining to the reader well about what filters are and why they would want to use them/read about them.

We do not provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal.

Please feel free to review our resources page on how to better improve our technical writing - and feel free to explore another topic when ready. 👍

Thank you very much for your review and I'm sure the level of feedback you provided is very helpful. @BrianaNzivu

2021-11-13 15:53 UTC, closed without merging

2021-11-14 06:52 UTC, Tumorbenson commented
> 👋 Thank you very much for contributing your 1st article - and Welcome to the EngEd Program. @Tumorbenson
> 
> There are some significant readability challenges/grammar mistakes/unclear sentences in your article. You are not explaining to the reader well about what filters are and why they would want to use them/read about them.
> 
> We do not provide editing services and recommend that students leverage online editing services (there are both free and paid services that you can explore), or try engaging with the community or other peers in your network to have them review prior to submitting a revised proposal.
> 
> Please feel free to review our resources page on how to better improve our technical writing - and feel free to explore another topic when ready. 👍
> 
> Thank you very much for your review and I'm sure the level of feedback you provided is very helpful. @BrianaNzivu

Hello @hectorkambow and @ahmadmardeni1   ? Would it be possible for me to make some changes to this article and resubmit it for review?

2021-11-27 17:29 UTC, ahmadmardeni1 commented
You can open a new PR. @ me and your peer reviewer, but please make sure your article is ready to be reviewed. @Tumorbenson 
Note for the peer reviewer: (add the duplicate label please).