Snorkel Python for Labeling Datasets Programmatically
section-engineering-education/engineering-education pull request #4486
Opened 2021-10-19 09:40 UTC by charles721

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4189 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-01 17:10 UTC, lalith1403 requested changes
Excellent article. Loved the way it is written. A few minor changes and we can move onto the final round of review.

2021-11-01 17:10 UTC, lalith1403 commented on content/articles/snorkel-python-for-labeling-datasets-programmatically/index.md
> +author:
Add the author name. I was unable to find your folder

2021-11-01 17:10 UTC, lalith1403 commented on content/articles/snorkel-python-for-labeling-datasets-programmatically/index.md
> +This tutorial aims to be able to label a sentence as either a question or not a question. If a sentence is a question, it is labelled `1`, and a non-question sentence(general statement) is labelled `
aims to label a sentence

2021-11-01 17:10 UTC, lalith1403 commented on content/articles/snorkel-python-for-labeling-datasets-programmatically/index.md
> +- Know how to use [Google colab notebooks.](https://colab.research.google.com)
Google Colab. It is a proper noun.

2021-11-01 17:10 UTC, lalith1403 commented on content/articles/snorkel-python-for-labeling-datasets-programmatically/index.md
> +We have defined our function as `def lf_keyword_lookup(x)` with the help of the `@labeling_function()` method.
The function name does not include def. Remove def when referring to `lf_keyword_lookup`. 

Secondly, @labeling_function is not a method. It is a decorator.

2021-11-01 17:10 UTC, lalith1403 commented on content/articles/snorkel-python-for-labeling-datasets-programmatically/index.md
> +def lf_regex_contains_what(x):r
Check this code once. There is an extra character

2021-11-02 12:27 UTC, charles721 commented
Hello @lalith1403, thanks for the review, I have made the changes

2021-11-11 17:32 UTC, ahmadmardeni1 commented
Great work gentlemen @charles721 @lalith1403

2021-11-11 17:33 UTC, merged