Convert HTML to PDF with Docraptor
section-engineering-education/engineering-education pull request #4490
Opened 2021-10-19 13:42 UTC by taves-hub

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images    
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?
#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
#### Topic suggestion this closes
This closes #4179

2021-10-31 11:36 UTC, taves-hub commented
@mercymeave All set

2021-11-02 07:31 UTC, mercymeave requested changes
Hello @taves-hub :wave: 

Thank you for the article. You have a great article here that will benefit most readers in working with pdfs and HTML.

However, there are a few concerns we need to address.

- Give a  clear explanation of how one will set up and use the API.
- For this case, it seems like you are working on a project. Provide details of the project from prerequisites, software to work with, initialization, folder structure and files to work with.
- In every step, mention the file you are working on and use the appropriate snippet identifier.
- Add proper comments and explanations to your code.
- Finally provide a link to the project in github.

I also suggest you go through the docs to see the structure and in-depth format of the articles.
Work on these changes so that we proceed. 

I will be closing this PR  to create more room as I wait for you to work on the changes.  It is not a problem just ping me to reopen it after you are done working on the changes.

2021-11-02 07:31 UTC, mercymeave commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +
Elaborate on how this is done clearly. I am trying to understand where the author is coming from. Let the reader know the complete steps of installation. Remember we are writing for beginners as well.

2021-11-02 07:31 UTC, mercymeave commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +```
Is this Javascript or php?

2021-11-02 07:31 UTC, mercymeave commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +```
What are archives in this case? Would someone who has no programming knowledge know what you mean here?

2021-11-02 07:31 UTC, mercymeave commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +Given that DocRaptor may also convert reports into various records, such as HTML to Excel, we must create the right archive for each report.
How does one convert a report into a record?

2021-11-02 07:31 UTC, mercymeave commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +```
You wrote a PHP script and identified it as javascript.

2021-11-04 17:11 UTC, taves-hub commented
@mercymeave  I'm done with all the changes that were required to move, everything is set.

2021-11-04 18:22 UTC, mercymeave commented
I will re-open the PR then you push the changes.

2021-11-05 08:56 UTC, taves-hub commented
@mercymeave, requested changes have been executed accordingly

2021-11-05 14:49 UTC, mercymeave commented
Hello @taves-hub,

I have gone through the changes. You have a great piece of article that would help our readers. However apart from what is in the documentation, would you please provide real-life use cases? 

The example you used is similar to what they used in the documentation.

Think of something like how to create a website and include it as a plugin that converts a specific webpage to a pdf. Take for instance I have a website that displays records or generates receipts, how would I implement Docraptor to perform this action for my site?

I think giving readers this level of content will yield more value to our platform and your portfolio as well.

No rush just take your time. Ping me once you are done.

cc: @hectorkambow

2021-11-05 14:49 UTC, mercymeave requested changes
Hello @taves-hub,

I have gone through the changes. You have a great piece of article that would help our readers. However apart from what is in the documentation, would you please provide real-life use cases? 

The example you used is similar to what they used in the documentation.

Think of something like how to create a website and include it as a plugin that converts a specific webpage to a pdf. Take for instance I have a website that displays records or generates receipts, how would I implement Docraptor to perform this action for my site?

I think giving readers this level of content will yield more value to our platform and your portfolio as well.

No rush just take your time. Ping me once you are done.

cc: @hectorkambow

2021-11-06 00:26 UTC, hectorkambow commented
👍 Great feedback and guidance @mercymeave 

🚀  

Well done - if more time is needed - we can close the PR to allow the author the proper time to make the required edits.

2021-11-06 07:02 UTC, kymomolly commented
@mercymeave working on it

2021-11-06 07:04 UTC, taves-hub commented
@mercymeave  working on it

2021-11-06 09:05 UTC, taves-hub commented
@mercymeave, requested illustration committed

2021-11-07 15:31 UTC, kymomolly commented
Hi @mercymeave what next

2021-11-07 15:33 UTC, taves-hub commented
Hi @mercymeave what next?

2021-11-09 05:17 UTC, mercymeave requested changes
Hello @taves-hub 

Thank you for adding more content to the article. However, kindly ensure that all content must appear in the `index.md` file. Add it to the index file with a detailed explanation then we proceed.

2021-11-09 09:13 UTC, taves-hub commented
@mercymeave, necessary changes have been put into place

2021-11-10 12:52 UTC, mercymeave commented
ON IT.

2021-11-11 23:26 UTC, hectorkambow commented
@taves-hub  

If any other edits are needed during the tech review - we will be closing this PR and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer.  👍  

cc @mercymeave  

As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
 🚀

2021-11-12 08:39 UTC, taves-hub commented
@mercymeave ,@hectorkambow, i believe that this article is more than ready to proceed to final review. Thank you

2021-11-12 09:30 UTC, jerimkaura commented
> @mercymeave ,@hectorkambow, i believe that this article is more than ready to proceed to final review. Thank you

I urge you to be patient as I work on refining your article. We encourage authors to be patient so that we don't rush publishing article that are not polished enough.

2021-11-12 09:33 UTC, mercymeave commented
Hello @taves-hub 

I urge you to be patient as I work on polishing this article. We highly encourage publishing very well polished articles for the benefit of our readers. Thank you for your patience.

2021-11-12 20:03 UTC, mercymeave requested changes
Hello @taves-hub 

Kindly remove this folder and its file. `illustration-on-docraptor/converted-pdf-with-docraptor.png ` then the article will be ready for final review.

2021-11-13 06:44 UTC, taves-hub commented
@mercymeave, Done

2021-11-15 18:19 UTC, mercymeave commented
Hello, you don't have a `hero` image. Secondly, delete one of the redundant `converted-pdf-with-docraptor.png` file. Just one is enough.

2021-11-15 21:15 UTC, hectorkambow commented
@mercymeave  

This PR should have been closed days ago

2021-11-15 21:17 UTC, hectorkambow commented
@taves-hub Please be sure to go through ALL the edits by our peer reviewer and make the last edit required. 

Place all these in a new PR and we can add a duplicate label to it. 

This PR has gone way far into revision - our team can not provide revisions services. 

Our team can only review before publishing. 👍

2021-11-15 21:17 UTC, closed without merging

2021-11-15 21:18 UTC, hectorkambow commented
@mercymeave 

This should NOT occur:
>I urge you to be patient as I work on polishing this article. We highly encourage publishing very well polished articles for the benefit of our readers. Thank you for your patience.

2021-11-15 21:19 UTC, hectorkambow commented
> 👍 Great feedback and guidance @mercymeave
> 
> 🚀
> 
> Well done - if more time is needed - we can close the PR to allow the author the proper time to make the required edits.

We should have closed this around 10 days ago - to allow the author the time to properly make the edits - WE ARE NOT TO MAKE THE EDITS FOR THE AUTHORS.