Building and run unikernels with ops
section-engineering-education/engineering-education pull request #4613
Opened 2021-10-25 16:06 UTC by Gladysoby

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? 
- [X] Is your article properly formatted in Markdown?
- [X] Have you used our preferred heading structure? 
- [X] Does your article follow any of the suggested structure formats?
- [X] Is your article over 750 words? 
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? 
- [X] Can your article be understood by beginners?
- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it?
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article?
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit.
- [X] Have you checked your article for readability?
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4390.

2021-10-31 17:31 UTC, hectorkambow commented
@Gladysoby 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2021-10-31 17:32 UTC, hectorkambow commented
@section-engineering-education/peer-reviewers 

If anyone is available to begin a prelim review on this PR.

2021-11-01 13:11 UTC, louisefindlay23 commented
Hi, @Gladysoby. Please remove extra spaces and add line breaks (to create paragraphs) where needed to get your article in a ready to review state.

2021-11-01 15:50 UTC, Gladysoby commented
@louisefindlay23 I have done the changes you requested

2021-11-02 16:57 UTC, louisefindlay23 requested changes

2021-11-02 16:57 UTC, louisefindlay23 commented on content/articles/building and run unikernel with OPS/index.md
> +### Building and Run Unikernels with OPS
Folder names can not have spaces: should be `content/articles/building-and-run-unikernel-with-ops`

2021-11-02 16:57 UTC, louisefindlay23 commented on content/articles/building and run unikernel with OPS/index.md
> +Unikernels are constructed with the usage of compilers that leverage library working systems, which might be collections of libraries that constitute a working gadget's core capabilities. This lets a
Remove `<br>` tags.

2021-11-02 16:57 UTC, louisefindlay23 commented on content/articles/building and run unikernel with OPS/index.md
> +A unikernel is an executable image that can be executed on a hypervisor without the need for a separate working system. The image consists of software code, as well as all the working machine capabil
Lines like this should have an additional line break to separate into paragraphs.

2021-11-03 20:23 UTC, hectorkambow commented
@Gladysoby 
Good afternoon and thank you for submitting your topic suggestion. As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 

All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
If it seems this PR is still quite a bit aways from being completed. We may be closing this PR. 

If so you can go ahead and please re-submit a new PR when its ready to be published (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

2021-11-05 14:53 UTC, closed without merging

2021-11-05 16:25 UTC, 07BLAIZER commented
@louisefindlay23 hello
I did the changes you requested but you have closed the PR without giving the specific reason

2021-11-06 13:08 UTC, louisefindlay23 commented
@Gladysoby, you still need to remove the `content/articles/building and run unikernel with OPS/hero.jpg` file because you haven't deleted the old version once you correctly renamed the folder.