Object based image analysis using matlab
section-engineering-education/engineering-education pull request #4669
Opened 2021-10-28 14:58 UTC by alpho361

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4204

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-01 13:02 UTC, louisefindlay23 commented
Hi, @alpho361. Welcome to the EngEd program. 

To get your article in a ready to review state, please rename your article to index.md not index,md and your image file extensions to lowercase

Thanks,
Louise - Content Moderator

2021-11-01 16:19 UTC, alpho361 commented
@louisefindlay23 Changes made.

2021-11-02 16:58 UTC, louisefindlay23 commented
Thanks, @alpho361 but you also need to rename the image extensions themselves (in the image filenames) as well as the index.md file.

2021-11-03 14:54 UTC, alpho361 commented
@louisefindlay23 The extension (PNG) is by default, i have tried changing it in the image filename and it seems unchangeable.

2021-11-07 14:10 UTC, louisefindlay23 commented
Images can only be renamed using the command line. See this [tutorial](https://docs.github.com/en/repositories/working-with-files/managing-files/renaming-a-file#renaming-a-file-using-the-command-line) for instructions.

2021-11-09 14:10 UTC, alpho361 commented
@louisefindlay23  Changes made.

2021-11-11 11:13 UTC, louisefindlay23 commented
Thanks, @alpho361. Your article is now ready for review. One of our peer reviewers will review your article as soon as one becomes available.

2021-11-11 23:01 UTC, hectorkambow commented
@section-engineering-education/peer-reviewers 

If anyone is available to review this one after they finish up any others in the queue. 👍

2021-11-15 19:44 UTC, jumamiller commented
@alpho361, a nice article, but you need to add more value by explaining each code snippet to help readers follow along!

2021-11-16 14:15 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-17 14:13 UTC, alpho361 commented
@jumamiller Changes mede

2021-11-17 16:40 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +
Ensure all functions have opening and closing brackets, e.g `rgb2gray()`. Edit where applicable throughout the article!

2021-11-17 16:41 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +se = strel('disk',5); % specyfying strel lenght
Have you explained all these snippets? Kindly explain all codes in this article!!

2021-11-17 16:42 UTC, jumamiller requested changes
Kindly explain all code snippets, it's important to let readers know what's going on.

2021-11-17 20:42 UTC, alpho361 commented
@jumamiller Changes made.

2021-11-19 06:12 UTC, jumamiller commented
> @jumamiller Changes made.

I asked you to explain code snippets for the third time and you've not updated. I'll close this article for now. When you have finished explaining all the snippets, let me know to reopen the article!

2021-11-20 11:27 UTC, alpho361 commented
@jumamiller Changes made.

2021-11-20 12:04 UTC, jumamiller commented
Opening this article to check for latest commits as pointed above!

2021-11-20 12:11 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +```
Hello, what does code do? why is the `edge(i2,'canny')`, described this way? I've requested this severally @alpho361!

2021-11-20 12:15 UTC, jumamiller requested changes
@alpho361, why don't you reach out for help? Explaining a code is simply walking the reader through the code to understand what you're doing!
For example, when I've got a method 'createUser(Request $request)`, I would say, for instance, "the above method createUser(...), takes in a single paramater request that......."

2021-11-20 12:16 UTC, jumamiller commented
> @jumamiller Changes made.

Not even a single code explained? did you follow the requirements?

2021-11-21 14:54 UTC, alpho361 commented
@jumamiller  Changes made.

2021-11-22 10:39 UTC, jumamiller commented
@alpho361, kindly work on the grammar. See the above commits to improve your articles in the future.

2021-11-22 10:41 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +
what do you mean by 'For example, such data......". Give a precise description of what you're covering.

2021-11-22 10:43 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +Object-based image analysis is useful, especially in analyzing satellite maps, machine vision, and obtaining information based on object characteristics in an image.
Generall, tell us what this article will cover. Kindly go thro' past articles to get more info about introductions!

2021-11-22 10:44 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +
Could you refrain from "we will". It's almost everywhere in the article!

2021-11-22 10:46 UTC, jumamiller commented on content/articles/object-based-image-analysis-using-matlab/index.md
> +First, we import the image using the function `imread()` as demonstrated with the below codes.
Have these explanations after the code. The current way is affecting the general article flow!

2021-11-22 10:48 UTC, jumamiller requested changes
@alpho361, I think this article is still far behind to be published. Please take your time, and work on a ready to publish article.

- I've fixed multiple grammar mistakes, but it seems the general flow ain't there. Read previous articles to understand how you can keep your readers glued on the article.

2021-11-22 10:49 UTC, jumamiller commented
I'll close for now untill all changes are done!

2021-11-27 06:53 UTC, alpho361 commented
@jumamiller Can you please reopen the PR, have made changes.

2021-11-27 07:03 UTC, lalith1403 commented
Can you create a new PR and ping the peer reviewer. Thanks.

2021-11-27 07:15 UTC, jumamiller commented
> @jumamiller Can you please reopen the PR, have made changes.

reopening to reflect commits

2021-11-27 08:13 UTC, jumamiller approved these changes
@alpho, you have done great work reworking on this article.

2021-11-27 17:57 UTC, hectorkambow commented
jumping on this one

2021-11-27 18:43 UTC, hectorkambow commented
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

2021-11-27 18:43 UTC, merged