Implementing a Generic Singly linked list Data Structure in Java
section-engineering-education/engineering-education pull request #4691
Opened 2021-10-29 15:49 UTC by LynnMumo

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4382

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-01 15:41 UTC, Kayere commented
Plagiarism check done ✔️

2021-11-18 12:17 UTC, Dawe-7 requested changes
@LynnMumo, welcome to Section's EngEd and congratulations on submitting your first article. The article is an interesting read and to make it better I've left you a few suggestions. Also, your `avatar.jpg` should be a snapshot of yourself and not a random image.

Ping me when done so we can move on to tech review. Thanks.

2021-11-18 12:17 UTC, Dawe-7 commented on content/articles/implementing-a-generic-singly-linked-list-data-structure-in-java/index.md
> +In this section, we'll explore how generics can be used to implement a singly linked list in a type-safe, parameterized fashion. We will use the Java program below to generate our own type-safe linke
The last sentence here, what is available for download?

2021-11-18 12:17 UTC, Dawe-7 commented on content/authors/lynn-mumo/index.md
> +---
```suggestion
github: https://github.com/LynnMumo
  - url: /engineering-education/authors/lynn-mumo/avatar.jpg
---
```
Add this after your github link

2021-11-18 14:48 UTC, LynnMumo commented
@Dawe-7 Done with the edits. Thanks.

2021-11-18 14:54 UTC, Dawe-7 commented
@LynnMumo, kindly add the snapshot of yourself in your 'avatar.jpg' file. You missed on that  .

2021-11-18 14:56 UTC, LynnMumo commented
> @LynnMumo, kindly add the snapshot of yourself in your 'avatar.jpg' file. You missed that.

Adding it right away @Dawe-7

2021-11-21 04:31 UTC, LynnMumo commented
@Dawe-7 Done

2021-11-22 13:06 UTC, Dawe-7 reviewed
@LynnMumo, upon running your code, i got errors. Kindly make sure your code runs. [Here](https://replit.com/@Dawe7/codeTest2#Main.java) is a link of the code test. After you've made sure that your code runs, add [replit](https://replit.com/~) links in your article before the output to make it easier for the reader to run your code.

Use this template after the code:
```
Go ahead and run the code [here](replit link provided here)
```

2021-11-23 14:21 UTC, LynnMumo commented
@Dawe-7 Done

2021-11-23 14:43 UTC, Dawe-7 commented
@LynnMumo, your code works, but, a brief explanation of what is happening in the code would be very helpful to readers. Also, could we have more comments in the code.  Plus, do the same thing you've done with the first code, add the code output and the quick-run link. 

Do this and your tutorial will be ready for final review.

2021-11-24 05:13 UTC, LynnMumo commented
> @LynnMumo, your code works, but, a brief explanation of what is happening in the code would be very helpful to readers. Also, could we have more comments in the code. Plus, do the same thing you've done with the first code, add the code output and the quick-run link.
> 
> Do this and your tutorial will be ready for final review.

Done @Dawe-7

2021-11-24 08:37 UTC, Dawe-7 approved these changes
Great first article @LynnMumo. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you, looking forward to more of your contributions in the EngEd program.

@Kayere, this article is ready for final review.

2021-11-25 18:25 UTC, lalith1403 commented
Jumping on this one

2021-11-25 18:37 UTC, lalith1403 requested changes
Make the change and let me know.

2021-11-25 18:37 UTC, lalith1403 commented on content/articles/implementing-a-generic-singly-linked-list-data-structure-in-java/index.md
> +By removing the challenges of an array, such as the need for contiguous memory and the difficulty of array insertion and deletion, an array data structure is improved. A linked list, but, makes it si
Could not understand this sentence. Can you work on it?

2021-11-25 18:39 UTC, lalith1403 commented
Additionally, do a thorough check once. There were several errors that I noticed at a glance. 

@Dawe-7 Please check for any errors once the edits are made. Thank you :)

2021-11-25 20:15 UTC, LynnMumo commented
> Make the change and let me know.

Done @lalith1403

2021-11-25 20:27 UTC, Dawe-7 commented
@LynnMumo, ping me when done with the changes.

2021-11-25 20:40 UTC, LynnMumo commented
@Dawe-7 already done. Thanks

2021-11-25 21:10 UTC, Dawe-7 approved these changes
Thanks for the changes @LynnMumo 

@lalith1403, peer review has been completed. Could we have a final review, thanks.

2021-11-26 17:42 UTC, lalith1403 commented
The article is an introduction to linked list in Java. You should talk about the code that explains the logic behind building and using linked lists. Moreover, the explanations are not clear. Work on it and note the comments made. 

It is very importatnt we deliver absolute value that is scarce on the web. If we are adding value in terms of content that is easily avaialble, we make sure to take it a step further and break down the details of implementing the concepts.

2021-11-26 17:43 UTC, lalith1403 commented
This PR needs a lot of revision. I will be closing this PR. Please feel free to submit a revised and edited new PR. Ping us once done. Thank you.

2021-11-26 17:43 UTC, closed without merging