Getting Started with Polynomial regression in Python
section-engineering-education/engineering-education pull request #4694
Opened 2021-10-29 17:51 UTC by Faith034

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4419

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-31 16:23 UTC, lalith1403 requested changes
Welcome to the EngEd program. You have started your journey on a positive note. The article seems to be really interesting. Can you refer to the contribution guidelines for submission details. Additionally, we will need a short bio and headshot pic for your profile. Refer to the contribution guidelines for adding the required information.

2021-10-31 16:23 UTC, lalith1403 commented on content/articles/polynomial-regression-in-python/index.md
> +## Prerequisites
All headings should be H3 and Beyond.

2021-10-31 16:23 UTC, lalith1403 commented on content/articles/polynomial-regression-in-python/index.md
> +**Obtaining the $\bold w$**
Treat this as a subsection. Use h4 heading.

2021-10-31 16:23 UTC, lalith1403 commented on content/articles/polynomial-regression-in-python/index.md
> + # Conclussion
H3 heading

2021-11-01 15:56 UTC, Kayere commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Getting Started with Polynomial regression in Python #4694 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7454487/Getting.Started.with.Polynomial.regression.in.Python.4694.Copyleaks.Report.pdf)

2021-11-08 18:51 UTC, lalith1403 commented
Have the necessary changes been made? Ping us once done.

2021-11-14 16:17 UTC, lalith1403 commented
@Faith034 Any updates?

2021-11-14 17:06 UTC, mbici commented
@lalith1403 am working on the plagiarism part right now. I'll be notifying you shortly.

2021-11-14 19:27 UTC, Faith034 commented
@lalith1403
 Am done with the requested changes.

2021-11-24 17:31 UTC, lalith1403 commented
This article is ready for final review. Can you add the author details (headshot pic and bio) in the authors folder? Thank you.

2021-11-24 18:22 UTC, lalith1403 commented
Also, a picture is required.

2021-11-24 18:27 UTC, Faith034 commented
@lalith1403 
Everything is in place now!

2021-11-25 18:31 UTC, lalith1403 requested changes
Review the equations rendering once. The equations need to be wrapped in dollar signs to display the equations.

2021-11-25 18:31 UTC, lalith1403 commented on content/articles/polynomial-regression-in-python/index.md
> +\[E(\bold w)=\frac{1}{2}\sum ( {y(x_n , w) − y_n } )^2\]
Wrap these equations within \$\$ to render them

2021-11-25 20:22 UTC, Faith034 commented
@lalith1403 
I've enclosed equations within dollar sign and are now okay.

2021-11-26 22:58 UTC, hectorkambow commented
jumping on this one

2021-11-26 23:59 UTC, merged