[Languages] How to build a Chrome Extension that displays motivational quotes using Javascript.
section-engineering-education/engineering-education pull request #4717
Opened 2021-10-30 23:04 UTC by deverten

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4129 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-31 06:54 UTC, geoffrey45 commented
Hello @deverten 👋
Welcome to the EngEd program. Thank you for submitting your first article. We will review your article for technical correctness, among other things, before it's published.

Please remove this file: `Muhammed-Umar/section-workspace.code-workspace`

2021-10-31 06:55 UTC, geoffrey45 commented
Hello @deverten 👋
Welcome to the EngEd program. Thank you for submitting your first article. We will review your article for technical correctness, among other things, before it's published.

Please remove this file: `Muhammed-Umar/section-workspace.code-workspace`

2021-11-02 07:54 UTC, geoffrey45 requested changes
Hello @deverten 

Welcome to the EngEd program. We will review your article for technical correctness, etc, before it gets published.

Please add code to your article as code blocks instead of images. Then remove the code images.

2021-11-02 10:21 UTC, Kayere commented
Plagiarism check done ✔️

2021-11-08 17:17 UTC, geoffrey45 reviewed
@deverten Please check the comments below.

2021-11-08 17:17 UTC, geoffrey45 commented on content/articles/How-to-build-a-Chrome-Extension-that-displays-motivational-quotes-using-Javascript/index.md
> +  - [Getting started](#Getting-started)
Please fix the table of contents. Links are not working

2021-11-08 17:17 UTC, geoffrey45 commented on content/articles/How-to-build-a-Chrome-Extension-that-displays-motivational-quotes-using-Javascript/index.md
> +
Uppercase letters are not supported in the article URL. ie. `How-to-build-a-Chrome-Extension-that-displays-motivational-quotes-using-Javascript`. Please replace them with lowercase letters.

Fix all your images.

2021-11-08 17:17 UTC, geoffrey45 commented on content/articles/How-to-build-a-Chrome-Extension-that-displays-motivational-quotes-using-Javascript/index.md
> +- https://www.youtube.com/watch?v=ew9ut7ixIlI&t=1s
Please name your references. for example, `Getting started - Chrome Developers`, etc

2021-11-09 04:41 UTC, geoffrey45 commented
@deverten Your pull request looks messy (195 files changed). Please close this pull request and open a new one with only your file changes. 

Mention me when you open the new pull request so that I can finish the review.

2021-11-09 05:02 UTC, closed without merging