Serialization in C#
section-engineering-education/engineering-education pull request #4719
Opened 2021-10-31 07:04 UTC by Tonybishop11

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3216 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-10-31 07:54 UTC, Ericgacoki commented
![tab-crash](https://user-images.githubusercontent.com/54077752/139573586-380670b5-1ae7-4f72-a9db-195d58526f5b.png)

Hey @Tonybishop11, the author image you've provided is too large. Kindly crop it to around 600X600 PX and maintain it between 100KB and 1MB.

2021-11-02 10:22 UTC, Kayere commented
PLagiarism check done ✔️

2021-11-04 13:41 UTC, Ericgacoki requested changes
Hey @Tonybishop11, kindly take a look at the following review-comments and ping me when you're done 😊

2021-11-04 13:41 UTC, Ericgacoki commented on content/articles/serialization-in-csharp/index.md
> +- Have [visual studio 2019](https://visualstudio.microsoft.com/vs/) software installed. It is the compiler used to run Csharp programs.
`Visual Studio 2019` is not a compiler. It's an IDE instead.

2021-11-04 13:41 UTC, Ericgacoki commented on content/articles/serialization-in-csharp/index.md
> +- Domain to domain transfer - A JSON or XML data string can be used to transport an item over a firewall.
Paraphrase the first list item to align with the intro sentence such that the two can be read without loss of flow.

2021-11-04 13:41 UTC, Ericgacoki commented on content/articles/serialization-in-csharp/index.md
> +- Instance of Runtime.Serialization.Formatter
How is `"It's a system"` applied as a requirement here? 🤔

2021-11-04 13:41 UTC, Ericgacoki commented on content/articles/serialization-in-csharp/index.md
> +
You've already defined what Serialization is. You don't need to repeat that.

2021-11-04 13:41 UTC, Ericgacoki commented on content/articles/serialization-in-csharp/index.md
> +The System.Runtime.Serialization is a namespace that includes binary serialization classes. In computing, a namespace is a collection of symbols used to identify and refer to various things. A namesp
Split this into two.

2021-11-04 13:41 UTC, Ericgacoki commented on content/articles/serialization-in-csharp/index.md
> +From the above code, we created an instance of our sample class and called it erick nyaga, and then we serialized it using the value 34. After that we create a file stream to accept our output using
Quote the actual line(s) of code you're referring to and avoid using different tenses in the same paragraph/sentence.

2021-11-04 13:41 UTC, Ericgacoki commented on content/authors/erick-kiragu/index.md
> +Student of data science with a passion for software development, artificial intelligence, and python scripting. I have proven my potential to expand technological knowledge by displaying exceptional
This would sound better as, "`<name>` is a Data Science student..."

2021-11-05 06:23 UTC, Tonybishop11 commented
hello @Ericgacoki I have done the requested changes. Please check

2021-11-09 11:27 UTC, Ericgacoki approved these changes

2021-11-18 02:53 UTC, hectorkambow commented
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

2021-11-24 18:33 UTC, lalith1403 commented
Taking this one 👍

2021-11-24 18:49 UTC, lalith1403 commented
> Plagiarism check done ✔️

What is the plagiarism percentage for this PR? Using another source, I got a score of 8%.

2021-11-24 19:24 UTC, lalith1403 requested changes
@Ericgacoki @Tonybishop11 The article has many errors. Please rectify all the errors.

2021-11-24 19:24 UTC, lalith1403 commented on content/articles/serialization-in-csharp/index.md
> +With apps, we must store data on durable or non-durable media for later retrieval. Serialization may help. Serialization is needed to transmit an object over a network. Serializing in C#, the app nee
Why are you using the square brackets?

2021-11-24 19:24 UTC, lalith1403 commented on content/articles/serialization-in-csharp/index.md
> +With apps, we must store data on durable or non-durable media for later retrieval. Serialization may help. Serialization is needed to transmit an object over a network. Serializing in C#, the app nee
If you are referring to the code, use backticks... \`\`.

2021-11-24 19:24 UTC, lalith1403 commented on content/articles/serialization-in-csharp/index.md
> +Below is a biliary Serialization example:
check spelling.

2021-11-24 19:24 UTC, lalith1403 commented on content/articles/serialization-in-csharp/index.md
> +{
Check the code. Brackets are not matched.

2021-11-24 19:53 UTC, Tonybishop11 commented
Hello @Ericgacoki done correcting requested changes

2021-11-24 20:02 UTC, lalith1403 commented
Make sure all the errors are changed. I had only mentioned a few errors that I found on a glance.

2021-11-24 20:32 UTC, Ericgacoki commented
Hey @lalith1403, I have made a few more necessary changes. Kindly take a look.
Apologies for the inconveniences caused! 🤝

2021-11-25 17:21 UTC, lalith1403 approved these changes

2021-11-25 17:23 UTC, merged