Momentum Based Gradient Optimizer and Optimization Techniques for Gradient Descent
section-engineering-education/engineering-education pull request #4732
Opened 2021-10-31 20:25 UTC by NdoloBonface

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4527 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-02 10:28 UTC, NdoloBonface commented
Hello @lalith1403 
Could you please look at this PR, please.

2021-11-03 17:30 UTC, Kayere commented
Plagiarism check done ✔️

2021-11-19 18:36 UTC, lalith1403 requested changes
Many changes are required. This is a good article but needs more information. Please add more info where necessary. I have highlighted a few areas that need additional info. However, there are many more places that would benefit from a detailed explanation.

2021-11-19 18:36 UTC, lalith1403 commented on content/articles/momentum-based-gradient-optimizer-and-optimization-techniques-for-gradient-descent/index.md
> +Utilize an Adaptive Optimization Algorithm (AOA) that uses exponentially-weighted averaging of gradients from prior rounds to keep convergence from deviating. Most real-world applications, such as de
Can you explain AOA before you introduce it?

2021-11-19 18:36 UTC, lalith1403 commented on content/articles/momentum-based-gradient-optimizer-and-optimization-techniques-for-gradient-descent/index.md
> +```
Use latex to write mathematical equations.

2021-11-19 18:36 UTC, lalith1403 commented on content/articles/momentum-based-gradient-optimizer-and-optimization-techniques-for-gradient-descent/index.md
> +To describe a gradient descent algorithm, the term `momentum` is used. This method works by detecting the direction of the steepest slope in its present state and then travelling in the direction of
This is factually incorrect. Momentum is not used to describe the algorithm, it is additional information used to converge faster.

2021-11-19 18:36 UTC, lalith1403 commented on content/articles/momentum-based-gradient-optimizer-and-optimization-techniques-for-gradient-descent/index.md
> +D = 0
use latex

2021-11-19 18:36 UTC, lalith1403 commented on content/articles/momentum-based-gradient-optimizer-and-optimization-techniques-for-gradient-descent/index.md
> +Improve AdaGrad by applying the adaptive learning rate method based on the Root Mean Square. The exponential moving average is used rather than the cumulative sum of squared gradients used by AdaGrad
Needs more explanation

2021-11-20 07:22 UTC, NdoloBonface commented
@lalith1403 Done 
Thanks.

2021-11-22 20:49 UTC, lalith1403 commented on content/articles/momentum-based-gradient-optimizer-and-optimization-techniques-for-gradient-descent/index.md
> +D = 0
This is not latex. Latex equations begin with $ and end with $. Please check published articles with equations in them and update accordingly.

2021-11-22 20:49 UTC, lalith1403 requested changes
Check published articles for latex references. Thank you.

2021-11-23 15:52 UTC, lalith1403 commented
I will be closing this PR now. Please research the latex part and submit a new PR.

2021-11-24 05:36 UTC, NdoloBonface commented
@lalith1403 I did some changes. Some of the code did not render when I tried to view it. Thanks.

2021-11-24 17:19 UTC, hectorkambow commented
> I will be closing this PR now. Please research the latex part and submit a new PR.

This was the correct move - if the PR still needs more revisions. 

Close it and a new PR will be needed.

👍  

@lalith1403

2021-11-24 17:20 UTC, closed without merging