Creating Custom Extendable and Expandable Floating Action Button In Android Using Kotlin
section-engineering-education/engineering-education pull request #4760
Opened 2021-11-02 17:14 UTC by omondi-alex

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #3974

2021-11-03 17:53 UTC, Kayere commented
Plagiarism check done ✔️

2021-11-21 11:18 UTC, Ericgacoki requested changes
Hello @omondi-alex, check out the following comments and ping me when you're done!

2021-11-21 11:18 UTC, Ericgacoki commented on content/articles/creating-custom-expandable-fab/index.md
> +    <alpha
Explain what these tags, attributes and values mean.

2021-11-21 11:18 UTC, Ericgacoki commented on content/articles/creating-custom-expandable-fab/index.md
> +import com.example.expandablefabdemo.databinding.ActivityMainBinding
I don't think it is necessary to include the package name and imports. Android Studio can handle that.

2021-11-21 15:56 UTC, omondi-alex commented
Done with the corrections

On Sun, Nov 21, 2021, 14:18 Eric G ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @omondi-alex <https://github.com/omondi-alex>, check out the
> following comments and ping me when you're done!
> ------------------------------
>
> In content/articles/creating-custom-expandable-fab/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/4760#discussion_r753783940>
> :
>
> > +1. `from_bottom_animation.xml`:
> +```xml
> +<?xml version="1.0" encoding="utf-8"?>
> +<set xmlns:android="http://schemas.android.com/apk/res/android"
> +
> +    android:fillAfter="true">
> +    <translate
> +        android:duration="300"
> +        android:fromYDelta="300%"
> +        android:toYDelta="0%" />
> +
> +    <scale
> +        android:pivotY="50%"
> +        android:pivotX="50%"
> +        android:toXScale="0.9"
> +        android:toYScale="0.9"/>
> +
> +    <alpha
>
> Explain what these tags, attributes and values mean.
> ------------------------------
>
> In content/articles/creating-custom-expandable-fab/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/4760#discussion_r753784227>
> :
>
> > +package com.example.expandablefabdemo
> +
> +import android.content.Intent
> +import androidx.appcompat.app.AppCompatActivity
> +import android.os.Bundle
> +import android.view.View.INVISIBLE
> +import android.view.View.VISIBLE
> +import android.view.animation.Animation
> +import android.view.animation.AnimationUtils
> +import android.widget.Toast
> +import com.example.expandablefabdemo.databinding.ActivityMainBinding
>
> I don't think it is necessary to include the package name and imports.
> Android Studio can handle that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/4760#pullrequestreview-811908245>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRNFKPOGUI5MIP7TGAN5MDUNDIR5ANCNFSM5HG7N2ZQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-25 00:03 UTC, Ericgacoki reviewed
Hello @omondi-alex, this is quite impressive and easy to follow tutorial. However, some parts of the code aren't explained clearly and beginners might find it difficult to understand some snippets. Take a look at the comments below!

2021-11-25 18:34 UTC, omondi-alex commented
Changes completed @Ericgacoki

2021-11-25 21:32 UTC, Ericgacoki approved these changes

2021-11-27 05:39 UTC, lalith1403 commented
Jumping on this one.

2021-11-27 06:05 UTC, lalith1403 approved these changes

2021-11-27 06:06 UTC, lalith1403 approved these changes

2021-11-27 06:06 UTC, lalith1403 approved these changes
A straightforward and easy to read tutorial. Well done :)

2021-11-27 06:12 UTC, merged

2021-11-27 06:37 UTC, Ericgacoki commented on content/articles/creating-custom-expandable-fab/index.md
> +  - url: /engineering-education/creating-a-custom-fab-in-android/hero.png
Noted :heavy_check_mark:

2021-11-27 12:12 UTC, omondi-alex commented
> A straightforward and easy to read tutorial. Well done :)

Thanks for your reply