How to create and run a C# unit testing project
section-engineering-education/engineering-education pull request #4775
Opened 2021-11-03 07:08 UTC by Ushter21

2021-11-03 07:10 UTC, Ushter21 commented
Hello @zolomohan I have created a new PR. 
Duplicate of #4188

2021-11-03 16:48 UTC, hectorkambow commented
@zolomohan lets wait until you get your new setup before we take on any new reviews. 👍

2021-11-03 16:56 UTC, zolomohan commented
@hectorkambow I can take this. Working with a temporary setup, not an issue 😄

2021-11-11 12:08 UTC, Ushter21 commented
Hello, @zolomohan @hectorkambow I wish to enquire about the progress of my PR. Thank you.

2021-11-14 09:03 UTC, Ushter21 commented
Hello, @ahmadmardeni1 @hectorkambow @zolomohan . What's the progress of my PR. Thank you.

2021-11-18 17:46 UTC, zolomohan requested changes
Hi @Ushter21 Please add proper spacing between lines and paragraphs.
Also, add proper indentation to code snippets.

2021-11-18 17:46 UTC, zolomohan commented on content/articles/how-to-create-and-run-a-.net-unit-testing -project/index.md
> +Write a test code in Visual Studio. It's also used to run an ASP.Net application's test code. It becomes much easier to check for faults in an ASP.Net application this way. The testing module in Visu
The Introduction is not very strong. Please find a way to improve it.

2021-11-21 09:34 UTC, Ushter21 commented
Hello @zolomohan I have done the changes you requested. Thank you.

2021-11-23 17:28 UTC, zolomohan approved these changes

2021-11-26 21:04 UTC, hectorkambow commented
Jumping on this one.

2021-11-26 21:37 UTC, hectorkambow commented
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

cc @zolomohan please be sure to go through the author index file as well to check for any mistakes and please do not forget to add the new meta image line 👍

2021-11-26 21:37 UTC, merged