End to end speech recognition with deep recurrent neural networks(RNN)
section-engineering-education/engineering-education pull request #4789
Opened 2021-11-03 20:38 UTC by extravaganza77

@hectorkambow  @lalith1403 This is an article update on End-to-end Speech Recognition with Recurrent Neutral Networks

2021-11-06 12:05 UTC, lalith1403 commented
Can you help me with your author folder name?

2021-11-06 12:11 UTC, lalith1403 requested changes
There are several errors. Please check before submitting for grammatical errors, formatting errors and conceptual errors. Additionally, the folder name should be in small caps. You have used a capital letter.

2021-11-06 12:11 UTC, lalith1403 commented on End-to-end-speech-recognition/index.md
> +RNNs are prone to оverfitting due to their mоdeling power, so regulаrisаtiоn is essential for good performance. This paper uses early stopping and weight loss (adding a zero-mean, fixed-variance Gaus
Gaussian noise

2021-11-06 12:11 UTC, lalith1403 commented on End-to-end-speech-recognition/index.md
> +For sequencing with an uncertain alignment between the input sequence, X, and the output targets, Y, Graves proposed the RNN-T as an extension of the cognitive scientist's temроrаl сlаssifiсаtiоn (CT
what is cognitive scientist's temporal classification?

2021-11-06 18:54 UTC, extravaganza77 commented
@lalith1403 
requested changes are in place

2021-11-08 18:53 UTC, lalith1403 commented
The folder directory itself is wrong. I will be closing this PR as a lot of the fundamental contribution guidelines are being ignored. Thank you.

2021-11-08 18:53 UTC, closed without merging