The Basics to Making your Web Application Work Offline
section-engineering-education/engineering-education pull request #4820
Opened 2021-11-05 12:52 UTC by artmuth

This fixes #4437

2021-11-08 11:56 UTC, mbaabuones requested changes
@artmuth Great article! Your article is well structured and easy to understand. Please work on the minor suggestions highlighted in the article and ping me when you are done.

2021-11-08 11:56 UTC, mbaabuones commented on content/articles/the-basics-to-making-your-web-application-work-offline/index.md
> +However, there are instances when users experience internet connection losses, which disrupts the use of online applications. Some of the causes of internet connection losses include poor weather, po
```suggestion
However, there are instances when users experience lost internet connection, which disrupts the use of online applications. Some of the causes of internet connection losses include poor weather, power outages, and poor internet coverage. Such instances have increased the need for applications that can work in offline mode.

2021-11-08 11:56 UTC, mbaabuones commented on content/articles/the-basics-to-making-your-web-application-work-offline/index.md
> +- **Service workers:** These tools work as proxies for the client-side of applications. When clients make network requests, ServiceWorkers intercept them and send responses to the clients.  Offline m
use 'service workers consistently in your article

2021-11-08 11:56 UTC, mbaabuones commented on content/articles/the-basics-to-making-your-web-application-work-offline/index.md
> +When the user is in offline mode due to a lost internet connection, he can still perform some actions. The IndexedDB stores these user actions. The corresponding data is synchronized with the server
put IndexedDB in bold

2021-11-10 12:51 UTC, WanjaMIKE commented
Please correct the plagiarism in highlighted areas. Thanks

[New Scan 12_43 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7512805/New.Scan.12_43.PM.Copyleaks.Report.pdf)

2021-11-11 13:48 UTC, artmuth commented
> Please correct the plagiarism in highlighted areas. Thanks
> 
> [New Scan 12_43 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7512805/New.Scan.12_43.PM.Copyleaks.Report.pdf)

@WanjaMIKE Done.

2021-11-11 13:48 UTC, artmuth commented
@mbaabuones I have finished revising the article.

2021-11-25 00:37 UTC, hectorkambow commented
Jumping on this one

2021-11-25 00:56 UTC, hectorkambow commented
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

2021-11-25 00:56 UTC, merged