How to Build a Deep Learning Model Using Tensorflow with Python
section-engineering-education/engineering-education pull request #4828
Opened 2021-11-05 20:42 UTC by TimedH

Here is the PR on how to build a deep learning model using tensorflow with python, i believe it will be of good help to readers.

2021-11-05 20:53 UTC, TimedH commented
Hello @Kayere kindly be my peer reviewer in this PR.

2021-11-05 21:12 UTC, TimedH commented
This closes #4194

2021-11-09 17:31 UTC, WanjaMIKE commented
Plagiarism check is done. @lalith1403 just an alert, there seems to be duplicate files in this PR. Thanks

2021-11-09 19:49 UTC, lalith1403 commented
@TimedH can you delete the duplicate file? Thank you

2021-11-09 22:47 UTC, TimedH commented
Hi @lalith1403 changes requested are in place

2021-11-22 20:48 UTC, lalith1403 requested changes
There are many changes required in this article. Please consider making the necessary changes. Thank you. I have highlighted only a few of the errors in the article. There are several errors.

2021-11-22 20:48 UTC, lalith1403 commented on how-to-build-deep-learning-model-using-tensorflow-with-python/Index.md
> +- Tensorflow is very compatible with a lot of languages like;  javascript, python, c#, swift, c++, and ruby hence the user may be choose any language to use tensorflow.
Languages are proper nouns...

2021-11-22 20:48 UTC, lalith1403 commented on how-to-build-deep-learning-model-using-tensorflow-with-python/Index.md
> +- With its graphical approach, TensorFlow offers a superior way of visualizing data hence with the aid of TensorBoard, it is possible to easily debug nodes.
This is factually incorrect. The underlying structure is a graph. It is not the approach.

2021-11-22 20:48 UTC, lalith1403 commented on how-to-build-deep-learning-model-using-tensorflow-with-python/Index.md
> +- TensorFlow also has its own TPU architecture, which makes calculations faster than the GPU and CPU. Models built using TPU can be easily installed in the cloud at a cheaper price and used at a fast
Factually incorrect.

2021-11-24 17:21 UTC, hectorkambow commented
@TimedH 
Good afternoon and thank you for submitting your topic suggestion.
 It seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
**We will be closing this and please re-submit when it is ready to be published as a new PR** (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 

cc @lalith1403

2021-11-24 17:21 UTC, closed without merging