The concept of cookies in servlets
section-engineering-education/engineering-education pull request #4832
Opened 2021-11-06 00:14 UTC by Evanslodoctor

This fixes #4521

2021-11-07 13:59 UTC, paulodhiambo requested changes
Hello @Evanslodoctor make the requested changes. I'll proceed to Tech review.

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> +The `Cookie` class in the Servlet API is used to create cookies. Cookies are created using the Servlet API's 'Cookie' class. This class employs a variety of approaches to give various cookie activiti
Change "It sends cookie data from a client to a server or from a server to a client using the `HTTP` response." to "Then, it sends cookie data from a client to a server or server to a client using the `HTTP` response."

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> +When a client makes a new request to a Web Server, the web server assigns a unique ID as a `cookie`, which is then sent back with the response to the client and saved in the client's browser.
Change "web server" to " webserver "

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> + A `Cookie`, is a class that contains several cookie-related methods that allow you to use cookies.
Change to " A `Cookie` class contains several cookie-related methods that allow you to use cookies."

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> +- `void setPath()`: This method is used to specify a cookie path. In a web application, for example, it is possible to specify a specific path for the cookies to be saved.
Change to "- `void setPath()`: This method is used to specify a cookie path. For example, in a web application, it is possible to specify a specific path for the cookies to be saved."

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> +By right-clicking on the`Example to demonstrate cookies in servlet` project selecting New Servlet, you can code a Servlet page as shown below. Provide your Servlet class name. I will call it `Process
Change to "You can code a Servlet page as shown below by right-clicking on the`Example to demonstrate cookies in servlet` project selecting New Servlet. First, provide your Servlet class name. I will call it `ProcessOneServlet`."

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> +#### Step 3: Creating a ReadingValuesFromCookies Servlet page
This should be #### Step 4

2021-11-07 13:59 UTC, paulodhiambo commented on content/articles/The-concept-of-cookies-in-servlets/index.md
> +By right-clicking on the`Example to demonstrate cookies in servlet` project selecting New Servlet, you can code a Servlet page as shown below. Provide your Servlet class name. I will call it `Reading
Change to "You can code a Servlet page as shown below by right-clicking on the`Example to demonstrate cookies in servlet` project selecting New Servlet. Provide your Servlet class name. I will call it `ReadingValuesFromCookies`."

2021-11-07 15:19 UTC, Evanslodoctor commented
> Hello @Evanslodoctor make the requested changes. I'll proceed to Tech review.

Hello @paulodhiambo? I'm done.

2021-11-09 17:37 UTC, WanjaMIKE commented
Plagiarism check is done. Could you revisit some of the highlighted areas in the attached pdf. Thanks
[Uploading New Scan 5_33 PM Copyleaks Report.pdf…]()

2021-11-10 08:14 UTC, Evanslodoctor commented
> Plagiarism check is done. Could you revisit some of the highlighted areas in the attached pdf. Thanks Uploading New Scan 5_33 PM Copyleaks Report.pdf…

@WanjaMIKE , how are you? This document is not available in PDF format. Could you please send it again? When I try to open it, it takes me back to this page.

2021-11-10 08:26 UTC, WanjaMIKE commented
Sure, I will

2021-11-10 12:14 UTC, Evanslodoctor commented
> Sure, I will

Waiting.

2021-11-11 22:50 UTC, hectorkambow commented
Pinged Mike via slack as well 👍

2021-11-12 03:37 UTC, WanjaMIKE commented
Please check the pdf. Thanks
[The concept of cookies in servlets #4832 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7524692/The.concept.of.cookies.in.servlets.4832.Copyleaks.Report.pdf)

2021-11-12 09:44 UTC, Evanslodoctor commented
> Please check the pdf. Thanks [The concept of cookies in servlets #4832 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7524692/The.concept.of.cookies.in.servlets.4832.Copyleaks.Report.pdf)

I am done. The remaining plagiarisms is for java imports and functions which are predefined. eg.,
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
@WebServlet("/ReadingValuesFromCookies")
public class ReadingValuesFromCookies extends HttpServlet


thank you.

2021-11-12 12:30 UTC, paulodhiambo commented
> > Please check the pdf. Thanks [The concept of cookies in servlets #4832 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7524692/The.concept.of.cookies.in.servlets.4832.Copyleaks.Report.pdf)
> 
> I am done. The remaining plagiarisms is for java imports and functions which are predefined. eg., import java.io.IOException; import java.io.PrintWriter; import javax.servlet.ServletException; import javax.servlet.annotation.WebServlet; import javax.servlet.http.Cookie; import javax.servlet.http.HttpServlet; import javax.servlet.http.HttpServletRequest; import javax.servlet.http.HttpServletResponse; @WebServlet("/ReadingValuesFromCookies") public class ReadingValuesFromCookies extends HttpServlet
> 
> thank you.

@Evanslodoctor please don't include the import statements unless necessary to keep the article clean.

2021-11-15 18:05 UTC, hectorkambow commented
@paulodhiambo 

Any update on this PR? 

Keeping in mind that any extra revisions should occur outside of the queue as to not increase the back log.

2021-11-17 10:18 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-22 16:38 UTC, hectorkambow commented
@ahmadmardeni1  

Why did we run two plagiarism checks on this ?

2021-11-22 16:38 UTC, hectorkambow commented
@paulodhiambo can we get a status update on this PR?

2021-11-23 04:20 UTC, paulodhiambo commented
Good article @Evanslodoctor, please change your article folder name from "The-concept-of-cookies-in-servlets" to "the-concept-of-cookies-in-servlets"

2021-11-26 09:48 UTC, merged