Building FAQ page using React-styled components and React.js
section-engineering-education/engineering-education pull request #4856
Opened 2021-11-07 09:46 UTC by KingsleyJack

2021-11-07 12:09 UTC, srishilesh commented
@KingsleyJack 

Welcome to EngEd program!

Could you please add the PR description back? Also, ensure that you've completed all those checks by checking those boxes.

Thanks.

2021-11-07 13:06 UTC, KingsleyJack commented
@srishilesh 
i have tried bringing back the PR description, also i have my hero image, avatar and authors page present.
thanks

2021-11-07 14:26 UTC, srishilesh requested changes
@KingsleyJack 

Until we wait for this PR to get plagiarism checked, I've suggested few formatting changes. Please make sure to do them.

Thanks.

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +v. Creating reusable components with React-styled components
Make these bulleted points using `-`

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +#### Key takeaways
Start with markdown headers `###`. (Title of the article not included)

Make these changes throughout the article

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +Yarn create-react-app Faq-app
Yarn?

Isn't `Y` in lower case?

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +```
Format this code neatly. (Proper indentations)

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +Let's go over what is happening with our code block. First, we created and used a context API named `ToggleContext` to monitor the state of our accordion component and to ensure that two questions ca
Make these to bulleted points instead of big para

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +```
Add comments if necessary

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +```
Code formatting

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +```
Do this for all the code snippets

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +![faq page](/engineering education/ building-faq-page-using-react-styled-components-with-react/image2)
Add extension.

The image path is not right. Please check the guidelines again or refer other articles.

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +![faq page](/engineering education/ building-faq-page-using-react-styled-components-with-react/image1)
Check the image path. It's not right.

2021-11-07 14:26 UTC, srishilesh commented on content/authors/kingsley-jack/index.md
> +type: engineering-education/author
```suggestion
type: /authors

```

2021-11-07 14:26 UTC, srishilesh commented on content/articles/building-faq-page-using-react-styled-components-and-react/index.md
> +
Add a link to the GitHub repo containing full code

2021-11-09 17:58 UTC, WanjaMIKE commented
The plagiarism test finds a majority of your code to be similar to https://stackoverflow.com/questions/66469220/i-am-having-error-when-trying-to-map-a-data-in-react-objects-are-not-valid-as. Please fix it

2021-11-10 17:45 UTC, srishilesh commented
@KingsleyJack 

Looks like this article might higher percentage, as mentioned by the CM.

Please make the necessary changes and then ping me.

Thanks.

2021-11-10 20:12 UTC, KingsleyJack commented
hello @srishilesh 
I have updated and hopefully fixed the plagiarism issues
thank you
cc.
@WanjaMIKE

2021-11-11 22:34 UTC, hectorkambow commented
@WanjaMIKE 

Lets be sure to please attach the copyleaks PDF on any PR that does not pass the plagiarism check for future review (and to make sure we do not do double the scans). 

cc @section-engineering-education/content-moderator-team

2021-11-11 22:48 UTC, hectorkambow commented
@srishilesh lets be sure to go through the edits already made - if anymore are needed - lets consider closing the PR to allow the author the time to improve the overall article. 

👍  

Your call depending on how extensive the needed edits are.

2021-11-12 05:28 UTC, srishilesh commented
> @srishilesh lets be sure to go through the edits already made - if anymore are needed - lets consider closing the PR to allow the author the time to improve the overall article.
> 
> 👍
> 
> Your call depending on how extensive the needed edits are.

@hectorkambow 

The author has made the requested changes. And, on a quick glance, the formatting changes looks good to me.

Let me proceed with the tech review. Will close this, if any more revisions are required.

Thanks.

cc. @KingsleyJack

2021-11-15 18:04 UTC, hectorkambow commented
@srishilesh  

Sounds good thank you - let us know - as we are working on clearing out the queue where possible. 👍

2021-11-16 17:56 UTC, srishilesh commented
@KingsleyJack 

Can you share a GitHub URL containing the full code? (Share it as a comment here, I'll add it to the article)

After few changes, the formatting and flow looks good. Need to perform the tech review.

2021-11-16 21:25 UTC, KingsleyJack commented
@srishilesh 
here is the link to the GitHub repository containing the codes
link: https://github.com/KingsleyJack/faq-app.git

2021-11-18 04:07 UTC, srishilesh approved these changes
@KingsleyJack 

Moving for the final review.

Make sure to go through my commits.

Thanks.

2021-11-27 19:46 UTC, hectorkambow commented
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in.

We are going through are ready articles in the order they were received and working on improving our review time as well.

🚀

2021-11-27 19:46 UTC, hectorkambow commented
jumping on this one

2021-11-28 01:41 UTC, merged

2021-11-29 21:48 UTC, hectorkambow commented
@KingsleyJack  

can you please DM via Slack asap 👍  

Thank you