How to set up a Simple Python WebSocket with AioHTTP
section-engineering-education/engineering-education pull request #4871
Opened 2021-11-07 20:55 UTC by wanjcarol

How to set up a Simple Python WebSocket with AioHTTP

2021-11-08 07:15 UTC, wanjcarol commented
This fixes #4711

2021-11-09 17:44 UTC, WanjaMIKE commented
Plagiarism check is done.

2021-11-14 14:51 UTC, paulodhiambo commented
@wanjcarol please add a link to the complete source code

2021-11-23 04:57 UTC, paulodhiambo commented
Good article @wanjcarol, please add your author profile

2021-11-24 17:46 UTC, paulodhiambo commented
Hello @wanjcarol you have been inactive for quite sometime, I'll will vlose this article for now and reopen later after you made the requested changes. For any assistance please ping me on slack.

2021-11-25 05:33 UTC, wanjcarol commented
Hello @paulodhiambo, I hope you are doing fine. Can you reopen the article so that I can submit the above details?

2021-11-25 09:16 UTC, wanjcarol commented
@paulodhiambo Author bio and avatar added.

2021-12-01 18:27 UTC, lalith1403 commented on content/articles/how-to-set-up-a-python-web-socket-with-aiohttp/index.md
> +![Sending data response](/engineering-education/how-to-set-up-a-python-web-socket-with-aiohttp/sending-data-response.png)
You may paste the output rather than taking a screenshot of the output. Do the same for all the images.

2021-12-01 18:28 UTC, lalith1403 requested changes
All outputs to be pasted instead of taken screenshots of. Kindly update and ping me. @paulodhiambo note the changes made.

2021-12-01 19:58 UTC, wanjcarol commented
Hello @lalith1403 @paulodhiambo, I have replaced the screenshots  with the console outputs

2021-12-02 16:30 UTC, merged