How to develop an API architecture
section-engineering-education/engineering-education pull request #4875
Opened 2021-11-08 06:50 UTC by kerubo-tech

> ### Article checklist
> #### Pre-submission checks
> > Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing
> 
> > If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.
> 
> > For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.
> 
> #### Formatting and structure checks
> * [x]  Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
> * [x]  Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
> * [x]  Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
> * [x]  Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
> * [x]  Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
> * [x]  Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
> * [x]  Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
> * [x]  Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
> * [x]  Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
> 
> #### Grammar & plagiarism checks
> * [x]  Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com)
> * [x]  Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
> * [x]  Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
> * [x]  Have you added sources for quotes and images that aren't yours?
> 
> #### Technical checks
> * [x]  Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
> * [x]  Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
> * [x]  Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
> 
> #### Topic suggestion this closes
> > Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.
> 
> This closes #4735
> 
> > Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-10 12:36 UTC, WanjaMIKE commented
Plagiarism check done.

2021-11-11 13:11 UTC, mbaabuones requested changes
@kerubo-tech Great article! The content is rich and well-written. Please work on the suggested changes to improve the article. After revising the article, go through the article to check and correct grammar errors. Ping me when you are done.

2021-11-11 13:11 UTC, mbaabuones commented on content/articles/how-to-develop-an-api-architecture/index.md
> +- An API should draw its focus on its consumption and ensure consistency
Put full stops

2021-11-11 13:11 UTC, mbaabuones commented on content/articles/how-to-develop-an-api-architecture/index.md
> +API should ensure components' reusability in application development.  This saves development time and prevents the developers from performing redundant and repetitive tasks repeatedly. This also ass
delete the word 'repeatedly'

2021-11-11 22:33 UTC, hectorkambow commented
@kerubo-tech

It seems this PR is still quite a bit aways from being completed. 

We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer.

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue. 👍 Be sure to consult previously published materials to get a better understanding of the level of quality the community expects.

Please feel free to go through our provided resources as well - those are there to help all our students improve their overall technical writing. To be able to take those skills to any position or program.

2021-11-11 22:33 UTC, closed without merging