Understanding Diffie Helman and Elgamal Asymmetric Encryption
section-engineering-education/engineering-education pull request #4888
Opened 2021-11-08 15:20 UTC by njerigitahi

2021-11-20 11:05 UTC, jumamiller commented on content/articles/diffie-hellman-elgamal/index.md
> +![Asymmetric encryption.](/\engineering-education\content\articles\understanding-diffie-helman-and-elgamal-asymmetric-encryption/asymmetric-encryption.png)
Describe what this image does!

2021-11-20 11:09 UTC, jumamiller commented on content/articles/diffie-hellman-elgamal/index.md
> +```
Describe what's happening on this section!

2021-11-20 11:09 UTC, jumamiller commented on content/articles/diffie-hellman-elgamal/index.md
> +Value  = 8
Explain this code snippet!

2021-11-20 11:10 UTC, jumamiller commented on content/articles/diffie-hellman-elgamal/index.md
> +It involves exchanging secret/asymmetric keys between sender and receiver by using asymmetric encryption(public and private key)
Could explain the DHKE protocol?

2021-11-20 11:10 UTC, jumamiller commented on content/articles/diffie-hellman-elgamal/index.md
> + `B < Q`
Steps involved to accomplish what?

2021-11-20 11:11 UTC, jumamiller requested changes
Hello @njerigitahi, kindly work on the suggestions!

2021-11-21 15:40 UTC, jumamiller commented on content/articles/diffie-hellman-elgamal/index.md
> +<!--more-->
The second sentence in this paragraph is too long and needs to be broken down.

2021-11-25 07:14 UTC, njerigitahi reviewed
@jumamiller, changes done!

2021-11-25 07:19 UTC, jumamiller approved these changes
@njerigitahi, you have made progress updating this article!

2021-12-01 11:12 UTC, Kayere commented
Congratulations on publishing your first article @njerigitahi. Please go through the changes made by your peer reviewer and I to help improve the quality of your future articles.

Thank you for the review @jumamiller.

2021-12-01 11:12 UTC, merged