Understanding Support Vector Machine(SVM) algorithm
section-engineering-education/engineering-education pull request #4908
Opened 2021-11-09 17:37 UTC by jmuchina

This PR is on issue number #4055

2021-11-10 17:49 UTC, srishilesh commented
@jmuchina 

Welcome to EngEd program!

Congratulations on your first article.

Before we begin with the review, could you please add the PR description back? And, please ensure if you followed all the checks mentioned there. (If so, please check those boxes).

Let's wait for the CMs to get this PR, plagiarism checked, before we can start with the actual review.

Thanks.

2021-11-14 08:18 UTC, ahmadmardeni1 commented
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

2021-11-14 08:47 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[Understanding Support Vector Machine(SVM) algorithm#4908](https://github.com/section-engineering-education/engineering-education/files/7533417/New.Scan.8_25.AM.Copyleaks.Report.pdf)

2021-11-14 21:18 UTC, jmuchina commented
Hello, @ahmadmardeni1 
I have made the required changes
Thank You.

2021-11-15 14:36 UTC, srishilesh commented
@jmuchina 

Great.

Let's get started with the review.

Meanwhile, please add a GitHub repo link containing the full code, after the conclusion.

Also, please have a look at the guidelines for authors information. There was an update to it, 2 days ago.

Ping me when these are done. I'll get started with the preliminary review.

Thanks.

2021-11-16 15:47 UTC, srishilesh commented
@jmuchina 

The formatting looks good.

Just make sure to perform a Grammarly check, if you haven't.

Also, rename the directory and image paths for `content/articles/understanding-support-vector-machine-smv-algorithm/index.md` (smv -> svm)

And, don't forget the GitHub URL containing full code.

Ping me when the changes are done.

2021-11-23 04:45 UTC, srishilesh commented
Just an update.

I'll complete the next round of review by the end of the day.

2021-11-23 17:03 UTC, srishilesh commented
@jmuchina 

Can you ping me (@srishilesh ) via Slack?

2021-11-23 17:14 UTC, srishilesh requested changes
@jmuchina 

On performing a tech review, your PR lacks quality and clarity in explaining concepts.

Moreover, the code snippets are not explained properly. You have just stated the facts, and not explained "why" or "how"

The GitHub URL is totally a different code.

We will be closing this PR to allow you to make necessary changes. Ping me in the new PR, when it's ready.

Make sure that your new PR must not require any additional revisions, and must be ready to publish article.

Thanks.

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> +Three hyper-planes may be seen in this picture (A, B, and C).
Firstly, what's a hyperplane?

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> +Using a scenario and dataset to better understand how SVM operates for classification will be the next step.
Where's the dataset?

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> +### Tuneing Parameters in SVM
Typo

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> + A variety of options are available from the kernel in this situation, including `linear,` `rbf,` and `poly` (the default being rbf ). It is preferable to employ the notions of `rbf` and `poly` for n
Where are we discussing these?

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> +sklearn.svm.SVC(C=1.0, kernel='rbf', degree=2, gamma=0.0, coef0=0.0, shrinking=True, probability=False,tol=0.01, cache_size=150, class_quantity=None, verbose=False, maximum_iters=-1, random_nature=No
Explain

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> +Here is the full code [repo link](https://gist.github.com/mblondel/586753/f740949d0336484567dd422fe53445ac8821f5b2) of Support Vector Machines.
Was this the code that you used in the tutorial?

It's a totally different code

2021-11-23 17:14 UTC, srishilesh commented on content/articles/understanding-support-vector-machine-algorithm/index.md
> +### Conclution
Typo

2021-11-23 17:14 UTC, closed without merging

2021-11-29 16:26 UTC, srishilesh commented
@jmuchina 

Do we have any updates on this?

Let me know if you need help in creating a new PR.

Thanks.