Working with gridbag layout in Java
section-engineering-education/engineering-education pull request #4914
Opened 2021-11-10 07:24 UTC by princeibs

In this article, we talked about working with layout managers and the different types of layout managers in Java. And then finally, diving deep into working with gridbag layout, including a project to demonstrate it's functionalities.

2021-11-12 09:04 UTC, paulodhiambo commented
@princeibs please link this article to an issue.

2021-11-12 11:56 UTC, princeibs commented
This article closes issue #4620

@paulodhiambo

2021-11-14 08:18 UTC, ahmadmardeni1 commented
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

2021-11-14 08:48 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-18 14:36 UTC, paulodhiambo commented on content/articles/working-with-gridbag-layout-in-java/index.md
> +The gridbag layout manager places components in rows and columns similar to the grid layout. But with gridbag layout, you can specify the size of each row or column. You can also decide whether a com
Be consistent, rename all occurrence of the word "gridbag" to "Gridbag"

2021-11-18 14:38 UTC, paulodhiambo requested changes
Hello @princeibs please always ensure you are consistent with your naming, I'll proceed with tech review.

2021-11-20 08:18 UTC, princeibs commented
I have updated the article to reflect the requested change. Thanks
@paulodhiambo

2021-11-23 05:01 UTC, paulodhiambo commented
@princeibs why is your PR having more than 600 filea

2021-11-23 05:09 UTC, paulodhiambo commented
@princeibs please sync your forked repo with the section repository and create another PR. I'll close this PR. For any assistance, ping me through slack.

2021-11-23 05:09 UTC, closed without merging