Integrate Facebook Ads into your Android App in Android Studio
section-engineering-education/engineering-education pull request #4934
Opened 2021-11-11 04:09 UTC by del-ui

2021-11-11 21:22 UTC, Jethro-magaji commented
I would like to review this article @ahmadmardeni1

2021-11-13 10:40 UTC, ahmadmardeni1 commented
Go ahead @Jethro-magaji

2021-11-16 14:41 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-18 15:09 UTC, del-ui commented
@Jethro-magaji  is there any progress?

2021-11-22 00:37 UTC, Jethro-magaji requested changes
Hello @del-ui 
Well done for coming up with such an amazing article, however, there are some grammatical errors like typos and grammar structure. I highly suggest you use [Grammarly](https://www.grammarly.com/) to edit your article for typos and grammar. Please also add an explanation below your code. Thanks.

2021-11-22 00:37 UTC, Jethro-magaji commented on index.md
> +For those without a ready Application, open your Android Studio and create a new project with Ads activity. Since it is a test Application, you can use it without altering. This [article](https://www
Please, you second person pronoun here "For those without a ready Application,". it should be "if you don't an application created already."

2021-11-22 00:37 UTC, Jethro-magaji commented on index.md
> +This dependece integrates the SDL to your Application.
There are spelling typos here...

2021-11-22 03:48 UTC, del-ui commented
Hello @Jethro-magaji I seem to have a problem making changes to this PR since I didn't create a branch while creating the PR. Should I open a new branch with the requested changes?....Kindly

2021-11-22 16:41 UTC, hectorkambow commented
@del-ui 

Yes - every PR should be its own distinct branch - be sure to check out our FAQ and resources for more details. 

👍

2021-11-22 16:41 UTC, hectorkambow commented
@del-ui 
 it seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 

cc @Jethro-magaji

2021-11-22 16:41 UTC, closed without merging