Introducing Threads in Java Socket Programming
section-engineering-education/engineering-education pull request #4937
Opened 2021-11-11 08:34 UTC by SteveadeNick

2021-11-11 08:35 UTC, SteveadeNick commented
This fixes #4554

2021-11-16 14:39 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such. 
Also, Why did you delete our template before submitting your PR? @SteveadeNick 

[Introducing Threads in Java Socket Programming#4937](https://github.com/section-engineering-education/engineering-education/files/7547300/New.Scan.2_30.PM.Copyleaks.Report.pdf)

2021-11-17 03:56 UTC, SteveadeNick commented
@ahmadmardeni1 
Hello
I have the revisions with me. Could you please reopen so as I can commit them for a final plagiarism check.
Thank you.

2021-11-17 10:48 UTC, ahmadmardeni1 commented
Just added the template. Please check what matched your aricle. @SteveadeNick

2021-11-17 10:50 UTC, SteveadeNick commented
Thanks @ahmadmardeni1

2021-11-23 05:11 UTC, paulodhiambo commented
@SteveadeNick please explain your code, at least add inline comments to explain parts of your code.

2021-11-23 14:48 UTC, SteveadeNick commented
> @SteveadeNick please explain your code, at least add inline comments to explain parts of your code.

Done @paulodhiambo

2021-11-30 18:18 UTC, SteveadeNick commented
Any progress with this article?

2021-11-30 18:19 UTC, SteveadeNick commented
@paulodhiambo @ahmadmardeni1 
I revised this article.

2021-12-02 07:12 UTC, paulodhiambo requested changes
Hello @SteveadeNick please make this changes, I'll close this article for now and reopen once you are done making the changes to clear the queue.

2021-12-02 07:12 UTC, paulodhiambo commented on content/articles/introducing-threads-in-java-socket-programming/index.md
> +Our implementation showed the importance of threads in java and enhancing understanding of threads in java socket programming.
reword to "This article has learned socket programming, thread and its use, server-side programming, and client-side programming.
Our implementation showed the importance of threads in Java and enhancing understanding of threads in java socket programming."

2021-12-02 07:12 UTC, paulodhiambo commented on content/articles/introducing-threads-in-java-socket-programming/index.md
> +It does thread matter where you save the two applications. Afterward, run the Server.java and the Client.java one after the other. In order to execute numerous instances of the client program at the
reword to "It does thread matter where you save the two applications. Afterward, run the Server.java and the Client.java one after the other. To execute numerous instances of the client program simultaneously, utilize an IDE like multiple instances, or run the client software in separate files. To get the results data input stream played above, you will need numerous clients."

2021-12-02 07:12 UTC, paulodhiambo commented on content/articles/introducing-threads-in-java-socket-programming/index.md
> +- A new thread is started to connect to the server for each request made by a client. To communicate with the client, the newly assigned thread is given access to the available streams.
reword to " A new thread is started to connect to the server for each request made by a client. For a connection to be established, the newly assigned thread is given access to the available streams."

2021-12-02 07:12 UTC, paulodhiambo commented on content/articles/introducing-threads-in-java-socket-programming/index.md
> +- A while loop is used to build socket objects that receive connections from server socket objects.
reword to "**Server class:** Client-side construction begins with a collection of streams and port numbers from the server and then follows these steps:
- A while loop is used to build socket objects that receive connections from server socket objects."

2021-12-02 07:12 UTC, paulodhiambo commented on content/articles/introducing-threads-in-java-socket-programming/index.md
> +There are two methods for creating a new thread in Java:
reword to "It's also essential that the server can handle multiple clients at once. Having the ability to manage several consumers simultaneously is a requirement of our design framework. Our server-side implementation needs threading to assign each request a data input stream thread as it comes in."

2021-12-02 07:12 UTC, paulodhiambo commented on content/articles/introducing-threads-in-java-socket-programming/index.md
> +Each sequential program begins, progresses through its execution, and ends. In a thread, the program's control travels in a logical order. It's a separate path through the program's source code. When
reword to "Each sequential program begins, progresses through its execution, and ends. In a thread, the program's control travels in a logical order. It's a separate path through the program's source code. When a high number of events or actions need to coincide, many applications are developed to function on a single thread. It is common for one thread to take a different path through the same code as the others when numerous threads are running at the same time.Java.lang is responsible for creating and managing every thread in `Java.Class` of threads."

2021-12-02 07:40 UTC, SteveadeNick commented
@paulodhiambo I was in the middle of editing the article before you even started.

2021-12-02 07:41 UTC, SteveadeNick commented
![Screenshot (34)](https://user-images.githubusercontent.com/89961529/144378668-6377ed32-cc61-48e9-aa56-e5b786951ba2.png)

2021-12-02 07:46 UTC, SteveadeNick commented
![Screenshot (35)](https://user-images.githubusercontent.com/89961529/144379209-3d1dbda7-7fb9-4c10-af91-d8c055a04257.png)

Also, I was adding the table of contents and the prerequisites section.

2021-12-02 07:48 UTC, SteveadeNick commented
@paulodhiambo You can reopen. Thanks in advance.

2021-12-03 04:23 UTC, SteveadeNick commented
@paulodhiambo 
Hello.
I have the changes with me, just waiting to be committed. Please reopen so that I can push them and ensure I have revised the article once more so that there will be no more revisions. Thank you in advance.

2021-12-04 04:19 UTC, SteveadeNick commented
@paulodhiambo should I reopen a new PR?

2021-12-04 05:06 UTC, SteveadeNick commented
@paulodhiambo Done

2021-12-06 18:07 UTC, hectorkambow commented
@paulodhiambo can we get a status on this PR? 

It would be best for the author to submit the polished article via a PR ifi any more edits are needed. 

Or if its ready for a final let us know 👍

2021-12-06 20:27 UTC, paulodhiambo commented
@SteveadeNick Please go through your article, there are several sentences that are incomplete. Check on how I have edited the first section of your article. For any assistance, ping me on slack.

2021-12-06 20:27 UTC, closed without merging

2021-12-08 18:25 UTC, SteveadeNick commented
Can you please reopen @paulodhiambo

2021-12-09 03:51 UTC, SteveadeNick commented
@paulodhiambo should I a new PR?

2021-12-09 13:08 UTC, paulodhiambo commented
@SteveadeNick please open a new PR and ping me.

2021-12-09 13:58 UTC, SteveadeNick commented
@hectorkambow closed the topic i suggested

2021-12-09 14:54 UTC, paulodhiambo commented
No problem, I'll reopen an link the issue