Client-Server Implementation of reCAPTCHA with React and Django
section-engineering-education/engineering-education pull request #4939
Opened 2021-11-11 08:46 UTC by KayveTech

2021-11-11 08:47 UTC, KayveTech commented
This fixes #4680

2021-11-12 13:31 UTC, jumamiller commented on content/articles/client-server-react-django-recaptcha/index.md
> +
Could you attach a screenshot for this part?

2021-11-12 13:38 UTC, jumamiller requested changes
Great article, fix minor suggestions and then we're good to move to tech review.

2021-11-12 13:38 UTC, jumamiller commented on content/articles/client-server-react-django-recaptcha/index.md
> +- In the above code, we have a contact form that contains the fields; name, email, and message. We keep track of the data entered in these fields using the useState() hook.
Have all methods enclosed with  backticks (` `) i.e the `useState()` hook.Update where applicable on the entire article.

2021-11-12 13:38 UTC, jumamiller commented on content/articles/client-server-react-django-recaptcha/index.md
> +- The `handleRecaptcha` function takes in a value that we send to the backend for server-side verification. You can console.log the value to see it. We use the Fetch API to make a POST request to the
Add the opening and closing brackets for method definitions, i.e `handleRecaptcha()`.Update where applicable!

2021-11-16 16:44 UTC, KayveTech commented
> Plagiarism check done ✅ Why did you delete our template before submitting your PR? @KayveTech

@ahmadmardeni1, I didn't delete the template. It didn't appear when I was opening the PR.

2021-11-16 16:45 UTC, KayveTech commented
@jumamiller, I'll take care of the requested changes soon...

2021-11-20 10:28 UTC, KayveTech commented
@jumamiller, requested changes done 🚀

2021-11-21 15:20 UTC, jumamiller commented
Upload new image for 'recaptchaSnap.PNG '. The current one has a wrong format!

2021-11-21 15:26 UTC, jumamiller commented on content/articles/client-server-react-django-recaptcha/index.md
> +
Fix the image path

2021-11-22 04:25 UTC, KayveTech commented
@jumamiller, is the image path okay now?

2021-11-22 13:44 UTC, jumamiller commented
> @jumamiller, is the image path okay now?

Upload new image, the current one has wrong extension. or does it show on your end?

2021-11-24 17:26 UTC, hectorkambow commented
> > @jumamiller, is the image path okay now?
> 
> Upload new image, the current one has wrong extension. or does it show on your end?

as long as the image is either .png or .jpg it should be fine (the image path needs to match). 👍

2021-11-25 15:29 UTC, jumamiller approved these changes

2021-11-28 19:22 UTC, hectorkambow commented
jumping on this one

2021-11-30 01:16 UTC, hectorkambow commented
check

2021-11-30 01:36 UTC, hectorkambow commented
Very nice work gents @KayveTech 

cc @jumamiller  

Very easy to follow along 🚀  

keep up the excellent work.

2021-11-30 01:36 UTC, merged