Creating Responsive Line and Bar charts with React and Semantic-ui
section-engineering-education/engineering-education pull request #4944
Opened 2021-11-11 11:57 UTC by FredBenson

this closes #

2021-11-16 14:38 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-16 14:38 UTC, ahmadmardeni1 commented
Why did you delete our template before submitting your PR? @FredBenson

2021-11-16 14:42 UTC, FredBenson commented
@ahmadmardeni1 
I apologize, but it wasn't there when I submitted. Please could you help me fix it?

2021-11-16 14:56 UTC, ahmadmardeni1 commented
I edited your initial comment and added the template. Check what matches your article please. @FredBenson

2021-11-23 07:16 UTC, jerimkaura reviewed
Hello @FredBenson :wave: 

Thank you for your great article. Take note of the changes I made to polish your future articles.

Proceeding to tech review :+1:

2021-11-23 07:34 UTC, jerimkaura reviewed
@FredBenson  Kindly provide an author image in the same folder as your profile.

2021-11-27 20:05 UTC, FredBenson commented
hello 
@jerimkaura I have added the author image as requested, for some reason it disappeared.

2021-11-30 11:16 UTC, jerimkaura requested changes

2021-11-30 11:16 UTC, jerimkaura commented on content/articles/creating-responsive-line-and-bar-charts-with-semantic-ui-and-react/index.md
> +A graphic illustration is a basic form of content presentation in front-end web development. For example, line and bar charts may have various applications to show statistics of user engagements, use
Explain what will make it simple to implement

2021-11-30 11:16 UTC, jerimkaura commented on content/articles/creating-responsive-line-and-bar-charts-with-semantic-ui-and-react/index.md
> +This tutorial requires intermediate knowledge of React.js, CSS, and any modern web styling libraries similar to Semantic-UI. So, for absolute beginners, take a moment and enroll in a crash course.
Provide a link for the course or tutorial.

2021-11-30 11:16 UTC, jerimkaura commented on content/articles/creating-responsive-line-and-bar-charts-with-semantic-ui-and-react/index.md
> +React functional component is a recent enhancement to React.js, the former being a class-based component. A functional component is a react function that accepts a `props` and returns a JSX (JavaScri
Tell the user what a prop is.

2021-11-30 12:09 UTC, FredBenson commented
@jerimkaura done as requested

2021-12-01 10:01 UTC, jerimkaura approved these changes
Hello @FredBenson  

Thank you for being patient up to this time :100: Your article was clear and precise. Take note of the change any reviewer or I make or will make to polish your future article even more.

This article is ready for final review. :rocket:

2021-12-02 19:02 UTC, lalith1403 requested changes
I have highlighted a few places of errors that we expect. Sentences should be short and crisp. Variables highlighted properly. Terminologies used correctly and explained if required. 

Most importantly, fact-checking and making sure any statements are backed by facts.

Please make the above changes and submit a new PR. I will be closing this PR for now to make room for other PRs. Thank you.

cc: @jerimkaura Please make note of the changes made. All articles should be factually, grammatically and formatted correctly. Thank you.

2021-12-02 19:02 UTC, closed without merging