Extensible Messaging and Presence Protocol - XMPP with NodeJs and Docker
section-engineering-education/engineering-education pull request #4962
Opened 2021-11-11 22:02 UTC by Horlawhumy-dev

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4943

2021-11-14 17:48 UTC, jumamiller commented
@Horlawhumy-dev, ensure that all code snippets are well explained!

2021-11-14 17:54 UTC, Horlawhumy-dev commented
I will review it ASAP. Thank you

2021-11-14 19:02 UTC, Horlawhumy-dev commented
@jumamiller kindly check it out.

2021-11-16 14:51 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-18 01:27 UTC, Horlawhumy-dev commented
@jumamiller sir!!!

2021-11-20 11:35 UTC, jumamiller commented on content/articles/extensible-messaging-and-presence-protocol-with-nodejs-and-docker/index.md
> +
what do you mean with term `concects`,connect?

2021-11-20 11:36 UTC, jumamiller commented on content/articles/extensible-messaging-and-presence-protocol-with-nodejs-and-docker/index.md
> +</stream:stream'>
check the apostrophe? do we need it?

2021-11-20 11:38 UTC, jumamiller requested changes
Excellent work, however your article lacks introduction! I would also love it if you added a table of contents for more straightforward navigation!

2021-11-20 12:50 UTC, Horlawhumy-dev commented
Thank you @jumamiller 

I have added some explanations in the introduction section.

2021-11-25 15:36 UTC, jumamiller requested changes
@Horlawhumy-dev, could we have full paragraphs? I noticed you have a lot of spacings which makes it hard to follow the article. Reformat them well.

2021-11-25 16:43 UTC, Horlawhumy-dev commented
Formatting done.

2021-11-30 14:43 UTC, jumamiller approved these changes
@Horlawhumy-dev, check the changes made during the review t improve your future articles!

2021-11-30 16:29 UTC, Horlawhumy-dev commented
I have gone through them. Thank you, sir!

2021-11-30 19:24 UTC, hectorkambow commented
@jumamiller  I think you are doing too much during your reviews. 

We need to be mindful of all our pull requests and all our students.

2021-11-30 19:52 UTC, merged