Graph cycle detection code - c#
section-engineering-education/engineering-education pull request #4963
Opened 2021-11-11 22:13 UTC by erixbiz

This fixes #4644

2021-11-13 10:35 UTC, ahmadmardeni1 commented
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

2021-11-16 17:11 UTC, munyite-megzs commented
@hectorkambow  I still don't have a reviewer 5 days later after creating the PR. Are you able to assist me to get someone? Thank you

2021-11-18 09:14 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-18 12:57 UTC, munyite-megzs commented
Great
Kind Regards

Margaret Sitati


On Thu, Nov 18, 2021 at 12:14 PM Ahmad Mardeni ***@***.***>
wrote:

> Plagiarism check done ✅
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/4963#issuecomment-972675173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABSXZGSGG33SIA2DSU5TGODUMS7XLANCNFSM5H3OW5VQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-20 11:58 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +With this brief description, we can get to know what a cycle is and how to detect that in a graph.
Could we have this part moved into the article's body while only briefly introducing this section? I mean it's too long to be an introduction!

2021-11-20 11:59 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +            - Cycle Detection on an undirected graph
Combining both uppercase and lowercase on a sentence? Combining both uppercase and lowercase on a sentence?

2021-11-20 11:59 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +```c#
Ensure all methods are included take the following format: `MakeGraph()`

2021-11-20 12:00 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +               new int[]{ 4,1},
Explain all code snippets!

2021-11-20 12:01 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +I hope that after going through this article, the concept of cycle detection is clearer to you. Happy Coding!
Conclusion is meant to cover what you discussed on the article!

2021-11-20 12:01 UTC, jumamiller requested changes
Hello, work on the above suggestions!

2021-11-23 08:42 UTC, erixbiz commented
@jumamiller  done with the changes requested

2021-11-25 15:39 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +
Where is the intro?

2021-11-25 15:40 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +```c#
Not fixed!

2021-11-25 15:40 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +### OUTPUT
Output shouldnt be heading!

2021-11-25 15:43 UTC, jumamiller requested changes
@erixbiz you have not polished the article. It lacks the general flow, no introduction, the suggested changes were not edited.

I'll close this article for now, kindly go thro' past articles and get the general flow!Ping me here when done.

2021-11-25 15:43 UTC, closed without merging

2021-11-25 16:43 UTC, erixbiz commented
@jumamiller sorry for that. will go through it thoroughly and let you know once done