An Overview of web 3.O
section-engineering-education/engineering-education pull request #4971
Opened 2021-11-12 09:08 UTC by JudyNduati

2021-11-12 09:12 UTC, JudyNduati commented
@ahmadmardeni1, I opened a PR

2021-11-12 09:15 UTC, JudyNduati commented
This closes #4645

2021-11-12 14:49 UTC, srishilesh commented
@JudyNduati Could you please add the PR description back? And, ensure you have followed all the checks. (Also, please check the boxes, if done)

2021-11-13 05:37 UTC, jumamiller commented on content/articles/an-overview-of-web-3-0/index.md
> +
Fix the table of contents, each with its own line.

2021-11-13 05:38 UTC, jumamiller commented on content/articles/an-overview-of-web-3-0/index.md
> +The World wide web is a crucial element of our modern life. It has become part of us, and it would not be easy to outgrow our lives without it. This is because technology has greatly advanced as peop
World Wide Web and not World wide web, also consider adding (WWW) which much popular.

2021-11-13 05:40 UTC, jumamiller commented on content/articles/an-overview-of-web-3-0/index.md
> +Web 2.O is the interactive version of 1.0 since you can read and write on the internet as well. There are many content creators in Web 2.O since we have Youtube, Google, Microsoft, and social media a
Rewrite this sentence, using 'as well' makes it hard to follow.

2021-11-13 05:43 UTC, jumamiller commented on content/articles/an-overview-of-web-3-0/index.md
> +Web 1.O was the first phase of the web revolution, also referred to as read-only web. It is primarily categorized by static websites that don't do much but display information on the page. You can re
You should be using a transition on this paragraph, i'e,   "For example,you can read text" to something like. Keep your sentences as simple as possible.

2021-11-13 05:47 UTC, jumamiller commented on content/articles/an-overview-of-web-3-0/index.md
> +Most people are probably wondering what the future web will be like. Well, Web 3.O (Web 3) is the future web. Many people are confused about what the next generation internet (Web 3) will be like. We
Using preposition at the end of your sentence? It's less formal though? could you check it out?

2021-11-13 05:47 UTC, jumamiller requested changes
Hello @JudyNduati, minor edits and we're good!

2021-11-13 13:06 UTC, WanjaMIKE commented
@JudyNduati could you paraphrase this portion it seems to show some plagiarism `To let it free and make its own decisions, we'll need a decentralized service that no one controls. Combining this capability with natural language processing (NLP), computers can easily understand information like humans, thus providing faster and more relevant results. They become more intelligent to satisfy people's needs.`

2021-11-16 11:01 UTC, JudyNduati commented
Hello @jumamiller , @WanjaMIKE I made changes

2021-11-17 15:20 UTC, jumamiller approved these changes
@JudyNduati, great article!

2021-11-18 02:54 UTC, hectorkambow commented
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

2021-11-26 22:08 UTC, hectorkambow commented
jumping on this one. 🔍

2021-11-26 22:43 UTC, merged