Build Autocorrect Feature Using NLP with Python
section-engineering-education/engineering-education pull request #4991
Opened 2021-11-12 23:42 UTC by dentex22

2021-11-13 06:20 UTC, okeloviolet commented
@hectorkambow I will be reviewing this article

2021-11-13 10:32 UTC, ahmadmardeni1 commented
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

2021-11-16 08:04 UTC, dentex22 commented
> Please always use the template provided by us. I edited your initial comment and added the template. Check what matches your article.

@ahmadmardeni1 any updates ??

2021-11-16 14:24 UTC, okeloviolet requested changes
Hello @dentex22 Make the request changes, I will proceed to tech review.

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +One application of Natural Language Processing (NLP) is the Autocorrect function. This feature works on every smartphone keyboard regardless of the brand, it is specially programmed to generalize all
remove the comma between brand and it. Replace "it is specially programmed to generalize all the correct words that are in the vocabulary and tries to find the most similar words to those words, not in the vocabulary." with " It is specially programmed to generalize all the correct words in the vocabulary and try to find the most similar words to those words, not in the vocabulary.	"

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +To understand how it works, will cover Natural Language Processing in this article and how we can use it with Python to build the autocorrect feature showing all the steps involved.
Change to " To understand how it works, we will cover Natural Language Processing in this article and use it with Python to build the autocorrect feature showing all the steps involved."

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +To download and install the Pycharm IDE on your PC, go to this [site](https://www.jetbrains.com/pycharm/download/#section=windows).
Change to " Go to this [site] to download and install the Pycharm IDE on your PC, go to this [site](https://www.jetbrains.com/pycharm/download/#section=windows)."

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +It paves the door for more interactivity and productivity in a variety of fields:
Change to " Natural Language Processing (NLP) is a branch of computer science and artificial intelligence that allows computers to understand and process natural human language. NLP is a programming language that enables computers to evaluate and interpret large volumes of natural language data."

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +The Autocorrect model is completely based on Natural Language Processing (NLP), and it is programmed to correct spellings and errors while inputting text and tries to locate the most comparable relat
Change to " The Autocorrect model is completely based on Natural Language Processing (NLP). It is programmed to correct spellings and errors while inputting text and locating the most comparable related words, as the name suggests. It compares the words in the vocabulary dictionary and the typed words on the keyboard. "

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> + - *Filtering Suggested Candidates* - Only correctly spelt real words from our created candidate list are considered, so we can compare them to the words in the dictionary and then filter out the one
Change "spelt" to "spelled"

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +# a get_count function that returns a dictionary of word vs frequency
Change to " # a get_count function that returns a dictionary of word versus frequency"

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +Each of the 4 edit functions is implemented as shown below each performing different tasks as early illustrated. We can also combine the functions to be able to find a list of all the strings that ar
Change to " Each of the four edit functions is implemented below, each performing different tasks as illustrated earlier. We can also combine the functions with finding a list of all the strings that are n edited to execute."

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +The program prompts the user to enter a word, if the word exists in the dictionary it is assumed to be right else a similar word is produced by the program. This is implemented by this piece of code.
Change to "The program prompts the user to enter a word. If the word exists in the dictionary, it is assumed to be right, or else the program produces a similar word. This piece of code implements this."

2021-11-16 14:24 UTC, okeloviolet commented on content/articles/build-autocorrect-feauture-using-nlp-with-python/index.md
> +As we have seen, Natural Language Processing plays a crucial role in enabling computers to understand and process human natural language. This is as implemented above using the autocorrect system.
Change "human natural language" to "natural human language"

2021-11-16 14:28 UTC, dentex22 commented
> Hello @dentex22 Make the request changes, I will proceed to tech review.

ook

2021-11-16 14:42 UTC, dentex22 commented
@okeloviolet done with changes

2021-11-16 15:18 UTC, dentex22 commented
> @okeloviolet done with changes

label update?? @okeloviolet

2021-11-18 09:16 UTC, ahmadmardeni1 commented
👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content. Take your time and revisit your article. @dentex22 

[New Scan 9_08 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7561562/New.Scan.9_08.AM.Copyleaks.Report.pdf)

2021-11-18 09:16 UTC, closed without merging