Phone verification in laravel using twilio
section-engineering-education/engineering-education pull request #5014
Opened 2021-11-14 03:45 UTC by philzy94

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com)
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-11-15 06:24 UTC, jumamiller commented on content/articles/phone-verification-in-laravel-using-twilio/index.md
> +- Conlusion
Ensure you fo

2021-11-15 06:26 UTC, jumamiller requested changes
Ensure that you follow the set guidelines for an article on [this](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md) link.

Ensure all you code snippets are well explained!

2021-11-16 14:02 UTC, philzy94 commented
@jumamiller the article has been updated as you demanded

2021-11-17 10:32 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[Phone verification in laravel using twilio#5014](https://github.com/section-engineering-education/engineering-education/files/7553813/New.Scan.10_27.AM.Copyleaks.Report.pdf)

2021-11-17 20:20 UTC, philzy94 commented
@ahmadmardeni1 I will revisit the article but from the guide, we were asked to use quetext which I used and got less than 10% plagiarism.

2021-11-18 12:31 UTC, ahmadmardeni1 commented
We are not using Quetext anymore; we are using CopyLeaks but you can use any plagiarism checker. @philzy94

2021-11-18 19:40 UTC, philzy94 commented
> We are not using Quetext anymore; we are using CopyLeaks but you can use any plagiarism checker. @philzy94

@ahmadmardeni1 ok sir. I have done some modifications to my article, especially the code since that is where the plagiarism is more.

2021-11-19 10:46 UTC, philzy94 commented
@ahmadmardeni1 all necessary editing has been made

2021-11-20 11:40 UTC, jumamiller commented on content/articles/phone-verification-in-laravel-using-twilio/index.md
> +
What's this spacing for?

2021-11-20 11:42 UTC, jumamiller commented on content/articles/phone-verification-in-laravel-using-twilio/index.md
> +
The article lacks introduction part!

2021-11-20 11:42 UTC, jumamiller commented on content/articles/phone-verification-in-laravel-using-twilio/index.md
> +
Kindly avoid this repetitions 'you are having', look for a better alternative!

2021-11-20 11:43 UTC, jumamiller commented on content/articles/phone-verification-in-laravel-using-twilio/index.md
> +
Introduction within article's body?

2021-11-20 11:44 UTC, jumamiller commented on content/articles/phone-verification-in-laravel-using-twilio/index.md
> +
Is this supposed to be a command/ sentence?? bash? php? Laravel? Use appropriate markdown commands!

2021-11-20 11:46 UTC, jumamiller requested changes
Kindly remove all spacings( I've given an example above). Then, restructure the article to have the intro on top!

2021-11-22 16:41 UTC, hectorkambow commented
@philzy94

2021-11-22 16:42 UTC, hectorkambow commented
@philzy94 
 it seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 
cc @jumamiller

2021-11-22 16:42 UTC, closed without merging