Mock a datasource for react using json server
section-engineering-education/engineering-education pull request #5054
Opened 2021-11-16 03:58 UTC by blacklihgt

### Article checklist
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #4836

2021-11-19 03:51 UTC, srishilesh commented
@jumamiller 

Are you going to review this article? Looks like you've removed your assignment.

If not, I can take it up.

2021-11-19 07:56 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2021-11-19 11:38 UTC, srishilesh requested changes
@blacklihgt 

I believe this your 4th article here at EngEd program. Going through your previous reviews would definitely help in improving the quality of this article. This article lacked explanation of code snippets.

Few suggestions:
- `content/articles/hero.png`. Hero image must be inside your article directory
- Code snippets were not explained properly
- Instead of mentioning just to copy-paste the code snippets, you must walk the reader through the code.
- Perform a grammarly check. There were some inconsistencies in uppercase/lowercase of words.

Please ping me when the changes are done.

Fyi, if this PR requires more revisions even after the next round of review, we would be closing it, allowing you to make necessary changes in your forked branch.

Thanks.

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +Datasource mainly used may include DBMS systems such as MySQL, Postgres, SQL, among many others. The problem with this approach is that during prototyping, e.g., in Rapid Prototyping Approach, it wil
What's a datasource?

Add reference for rapid prototyping approach

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +### key takeaways
First letter in upper case

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +The use of the Json-Server library can solve such data sources problems.
json-server is the name of the library?

If so, make it `json-server` ( enclose within ` `` `)

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +It allows routes to access data items stored in the Mock database file(in JSON format). They may include examples such as `GET    /posts`, `PUT    /posts/1`, or `DELETE /posts/1`.
Remove extra spaces in the example requests

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +- **Homepage**: e.g. `GET /`. Using the ' ./public ' path, one can serve the application files in the public folder.
Along with examples, add some description

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +- In the 'Header.js', copy and paste the code below:
`copy and paste`

Avoid using this.

Instead, explain and walk the reader through the process.

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +```
Explain what this code does. (Use bullet points to explain them)

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +```
Explain

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +  - It displays the item and the amount
Format them neatly. (Indentation)

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +  - It displays the item and the amount
Explain the code above more clearly.

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +- In the 'Budget.js' file, the following will be its code:
What is this file for? What does it contain?

Don't just specify the file name. The reader wouldn't be able to understand your thought process, just with the filename

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +- In the 'Budget.js' file, the following will be its code:
Do this for other code snippets as well

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +- Now, once done with components, do this to the 'App.js' file:
???

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +- In the 'Budgets.js' file, the following will be the code:
What does it do?

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +```
Break this down into smaller code blocks and explain them

2021-11-19 11:38 UTC, srishilesh commented on content/articles/mock-a-datasource-for-react-using-json-server/index.md
> +}
Usually, there's nothing much to explain in styling. So, this could be replaced with a GitHub/Gist link containing this CSS file.

2021-11-20 08:54 UTC, blacklihgt commented
> @blacklihgt
> 
> I believe this your 4th article here at EngEd program. Going through your previous reviews would definitely help in improving the quality of this article. This article lacked explanation of code snippets.
> 
> Few suggestions:
> 
> * `content/articles/hero.png`. Hero image must be inside your article directory
> * Code snippets were not explained properly
> * Instead of mentioning just to copy-paste the code snippets, you must walk the reader through the code.
> * Perform a grammarly check. There were some inconsistencies in uppercase/lowercase of words.
> 
> Please ping me when the changes are done.
> 
> Fyi, if this PR requires more revisions even after the next round of review, we would be closing it, allowing you to make necessary changes in your forked branch.
> 
> Thanks.

Got you @srishilesh, am going to do the necessary changes as specified

2021-11-22 16:42 UTC, hectorkambow commented
100 % agree @blacklihgt 

Please go through our docs for more info and tips.

2021-11-22 16:42 UTC, hectorkambow commented
@blacklihgt 
 it seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 

cc @srishilesh

2021-11-22 16:42 UTC, closed without merging

2021-11-23 04:57 UTC, srishilesh commented
@blacklihgt 

You can create a new PR with all these suggested changes. Ping me once you're done.

Make sure that your new PR is ready to be published, and needs no extra revisions.

Thanks.