getting-started-with-python-plug-ins-for-gimp
section-engineering-education/engineering-education pull request #5083
Opened 2021-11-17 06:42 UTC by kmwangi-ken

2021-11-19 03:48 UTC, srishilesh requested changes
@kmwangi-ken 

Let's wait for the plagiarism check, before we get started with the tech review.

Before that, there are some changes to be made in your PR:
- Add the PR description back. Ensure you've performed all the checks (If so, check those boxes)
- Perform a grammarly check. Found some inconsistencies in uppercase/lowercase
- Have a careful look at your codes. Your Python codes seem to be missing indentations. Hope you know that, it gives errors if not properly indented.
- Image paths are incorrect.
- Add GitHub URL containing full working code.

Have a look at few of my articles [here](https://www.section.io/engineering-education/authors/srishilesh-p-s/) on how to go about formatting and flow of the article.

Fyi, if we find more corrections/revisions required even after the next round of review, we would be closing this PR, to allow you to polish your article better such that it's ready to be published.

Thanks.

2021-11-19 03:48 UTC, srishilesh commented on content/articles/getting-started-with-python-plug-ins-for-gimp/index.md
> +![Plug-ins folder](plugins.png)
The image doesn't look right.

It should be something like:
`/engineering-education/[ARTICLE-DIRECTORY]/[IMAGE-WITH-EXTENSION]`

Do this change for all the images

2021-11-19 03:48 UTC, srishilesh commented on content/articles/getting-started-with-python-plug-ins-for-gimp/index.md
> +gimp_plugins)
`From gimpfu import *` Do you think this would work?

Why is this `def gimp_plugins(image, drawable):return` empty?

2021-11-19 03:48 UTC, srishilesh commented on content/articles/getting-started-with-python-plug-ins-for-gimp/index.md
> +then, at that point, compose the accompanying order
You can use ` `` ` for keywords, variables, functions, filenames, image names or directories.

Do this change throughout the article

2021-11-19 03:48 UTC, srishilesh commented on content/articles/getting-started-with-python-plug-ins-for-gimp/index.md
> +```
Do you think this code will work?

2021-11-19 03:48 UTC, srishilesh commented on content/articles/getting-started-with-python-plug-ins-for-gimp/index.md
> +```
In Python, everything runs on proper indentation. It seems to be missing

2021-11-19 03:48 UTC, srishilesh commented on content/articles/getting-started-with-python-plug-ins-for-gimp/index.md
> +### Conclusion
Can you add a GitHub URL containing full working code?

2021-11-19 03:48 UTC, srishilesh commented on content/authors/Taves-mwangi/index.md
> +---
`content/authors/Taves-mwangi/index.md` -> `content/authors/taves-mwangi/index.md`

Change the article directory with all the letters in lowercase

2021-11-19 03:48 UTC, srishilesh commented on content/authors/Taves-mwangi/index.md
> +---
You seem to be missing something.

Please have a look at the documentation or refer files of other authors to correct this.

2021-11-23 04:48 UTC, srishilesh commented
@kmwangi-ken 

Do we have any updates?

If you still need more time, we can close this PR for now. You can still work on those changes, submit as a new PR, and ping me there.

2021-11-23 09:55 UTC, kmwangi-ken commented
@srishilesh, there are updates.  To be submitted soon

2021-11-24 07:29 UTC, LinusMuema commented
Hi @kmwangi-ken 

Your article appears to have many sentences that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
 
We're really looking for unique/original content.

[Getting started with python plug-ins for GIMP Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7593545/Getting.started.with.python.plug-ins.for.GIMP.Copyleaks.Report.pdf)

2021-11-24 07:29 UTC, closed without merging

2021-11-29 16:27 UTC, srishilesh commented
@kmwangi-ken 

Do we have any updates?

Let me know if you need help creating a new PR