convert-html-to-pdf-with-docraptor
section-engineering-education/engineering-education pull request #5084
Opened 2021-11-17 07:44 UTC by taves-hub

2021-11-17 07:52 UTC, taves-hub commented
@hectorkambow, @mercymeave, I have done the required changes on my article. You may have a look at it when you are free

2021-11-18 13:11 UTC, mercymeave commented
Hello @taves-hub

2021-11-18 13:11 UTC, mercymeave commented
I will check it out.

2021-11-18 13:23 UTC, mercymeave approved these changes
Take note of the changes made for clearer articles in the future.

2021-11-18 18:09 UTC, kymomolly commented
@mercymeave, have taken note, for a better article in the future. Thanks

2021-11-18 18:12 UTC, taves-hub commented
@mercymeave, have taken note, for a better article in the future. Thanks

2021-11-18 18:28 UTC, taves-hub commented
@mercymeave, I think you forgot to include tech tutorial label

2021-11-18 18:29 UTC, taves-hub commented
@mercymeave, I think you forgot to include tech tutorial label

2021-11-18 18:33 UTC, taves-hub commented
@mercymeave, I think you forgot to include tech tutorial label

2021-11-28 17:31 UTC, taves-hub commented
@mercymeave, hello was inquiring about the `tech tutorial` label. Thank you

2021-12-03 18:40 UTC, lalith1403 commented
jumping on this one 👍

2021-12-03 19:05 UTC, lalith1403 requested changes
Please rectify the errors that exist in the article. There are several readbility issues. You may rectify them and create a new PR. I will be closing this one. Once you create a new PR, we will review the article one more time to make sure we give the author another opportunity to make changes. We encourage you to be diligent about rectifying all the errors and only publishing a polished article. Thank you.

@mercymeave There are many errors in the article. There were spelling mistakes in the article. Please look into the changes made.

2021-12-03 19:05 UTC, lalith1403 commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +To get started with Docraptor, we need to install it in our local machine. Installation can be done in two ways. The first way is using composer dependency manager, while the second way is by downloa
give a bried intro to compose dependency manager.

2021-12-03 19:05 UTC, lalith1403 commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +Navigate through [this](https://docraptor.com/documentation) link to find the installation zip file. Download the file, then extract it into your workspace. Create a new file and name it `docraptor.p
can you provide the link to the zip file?

2021-12-03 19:05 UTC, lalith1403 commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +Navigate through [this](https://docraptor.com/documentation) link to find the installation zip file. Download the file, then extract it into your workspace. Create a new file and name it `docraptor.p
`autoload.php`

2021-12-03 19:05 UTC, lalith1403 commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +Every project where an API is used needs an API key. The key identifies the machine from where the request for specific resources is coming. Our project is not an exception; therefore, we need to add
API key. Avoid unnecessary capitalization.

2021-12-03 19:05 UTC, lalith1403 commented on content/articles/convert-html-to-pdf-with-docraptor/index.md
> +Every project where an API is used needs an API key. The key identifies the machine from where the request for specific resources is coming. Our project is not an exception; therefore, we need to add
What do you mean by you get after sending an HTTP request? It is not clear.

2021-12-03 19:05 UTC, closed without merging

2021-12-03 19:29 UTC, hectorkambow commented
>NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
 
Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍

2021-12-03 20:32 UTC, taves-hub commented
@lalith1403, How are you doing sir? I was just requesting if you may open this PR so that I may push the requested changes that you have suggested. I have already corrected the changes and any other that may have appeared. I would really appreciate it. thank you

2021-12-03 20:56 UTC, lalith1403 commented
As per the guidelines of the community, we request you to open a new PR and ping me. Also, note the comment by @hectorkambow. Thanks.

> > NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
> 
> Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
> 
> 👍

2021-12-03 21:01 UTC, taves-hub commented
@lalith1403, Okay.