Beginners intro to Generative Modeling
section-engineering-education/engineering-education pull request #5109
Opened 2021-11-18 17:05 UTC by tanmay69

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5007`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-19 02:52 UTC, hectorkambow commented
@lalith1403  

Will you be able to finish this one before Monday? 

It may be best to let another PR (peer reviewer) take this one if needed.

2021-11-19 14:32 UTC, lalith1403 commented
I had finished a preliminary round of review before this one was uploaded. I have gone through the article and can positively complete it.

2021-11-24 08:02 UTC, LinusMuema commented
plagiarism check done :heavy_check_mark:

2021-11-26 16:32 UTC, tanmay69 commented
@lalith1403 Please review this article.

2021-11-30 18:24 UTC, lalith1403 requested changes
Hello @tanmay69 
Several changes are required. Also, break paragraphs into shorter paragraphs and ensure that you are looking out for spelling and grammatical errors. 

Tech review to be done.

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +Most machine learning practitioners are exposed to the classification or the regression tasks in machine learning first due to its extensive scope and straightforward approach. However, the generativ
No need to capitalize generative modeling.

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +Let's try to break the above paragraph by taking a real-life example. Consider a scenario where you get appointed as a machine learning engineer in some company. Now, you give this excellent news to
Break this into smaller paragraphs and a sub section if necessary.

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +Machine learning models can broadly be categorized into two categories, Discriminative and Generative Models. Before we compare both of them, let's talk about the discriminative models. In simple ter
discriminative and generative.

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +Generative modeling is a most underrepresented topic in machine learning. However, still, a lot of research is going on this topic. This section will discuss why generating data is essential and how
How are you saying it is underrepresented? When you make such claims, you should back it up with data. If not, it is not ideal to make such claims.

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +The most trending topic in generative modeling is GAN. It is the most effective technique when it comes to generating data. We will talk more about GAN in the next section. For now, let's stick to it
How do you say it is the most effective technique to generate data. Cite sources?

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +One more important application of generative modeling is data augmentation. Of course, the most crucial aspect for applying any ML technique is training data. Still, there are certain areas where we
For example, one such work....

2021-11-30 18:24 UTC, lalith1403 commented on content/articles/beginners-intro-to-generative-modeling/index.md
> +The word __adversarial__ in GAN refers to the competition like the arrangement between generator and discriminator where the generator tries to fool the discriminator. The discriminator's job is to d
Sentence has grammatical errors.

2021-12-01 19:00 UTC, hectorkambow commented
@tanmay69 

Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) - this allow all revisions to be done on your forked personal repo. 
 
We will be closing this PR and please re-submit it when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

>NOTE: A duplicate PR will go back into the queue and will not received any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 



 cc @lalith1403

2021-12-01 19:00 UTC, closed without merging