Email validator in flutter
section-engineering-education/engineering-education pull request #5116
Opened 2021-11-19 08:44 UTC by joni-kano

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3932

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-19 08:46 UTC, joni-kano commented
@jerimkaura @Kayere I have polished the article

2021-11-23 04:32 UTC, WanjaMIKE commented
@jerimkaura could you take  up this PR. It appears you were reviewing it before. Thanks

2021-11-26 10:21 UTC, LinusMuema commented
plagiarism check done :heavy_check_mark:

2021-11-30 02:29 UTC, hectorkambow commented
@jerimkaura @Kayere  

Can we get a status on this PR. 

If we need to get this re-assigned we can do so 👍

2021-11-30 02:30 UTC, hectorkambow commented
@joni-kano 
Good afternoon and thank you for submitting your article for publishing. With the recent increase in article volume out team has been working diligently to review every article. 

Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2021-12-01 19:53 UTC, hectorkambow commented
Peer reviewer pinged via Slack as well :thumb

2021-12-01 21:18 UTC, jerimkaura requested changes
Hello @joni-kano 

A quick one. Take the corrections I have suggested in the comments and address them in detail. Remember it is just about a working code, we need to have a great flow and easy-to-read content as well.

Your article seems to have a lot of readability issues. Furnish it then ping me here or on slack @jerimkaura

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +The constructor for this class is pretty simple: Create a new instance of this class and set the validator type to either 1 or 2 (defaults to 1). The constructor should pass a string and an array of
Explain type 1 and 2 and what each type does.

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +For this reason, it protects the email sender score while maximizing the efficiency of the flutter application. The key concepts from the use of this package are validity, risk, and the invalidity of
Explain the key concepts

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +If either of the first two arguments contains an error, then false should be returned. Otherwise, true should be returned, and our string should be validated.
Where are the arguments? Explain them in detail with a proper example to enable understanding of the concept.

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +4. You can add it as a pre-requisite while submitting the app to the app store and google play store for review purposes.
Explain how each benefit is acheived.

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +- This example brings us to the understanding usage of this API for serverless flutter applications.
Provide a detailed explanation of how email validation works in each of the specified areas. What module of the system implemented it. At what level does it work. For instance, answer the question How is `GeocodeLongitude & Latitude Data` applying this concept?

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +Email validator works better in that it is a more accurate validation tool. In addition to validating email addresses, it also checks that domains are not likely to exist soon.
More accurate than........? And will it determine that a domain will not exist soon?

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +Domain Validation Tool is a free service that allows you to search up to 500 domains from your list for availabilitydor and immediate results. It's the most potent domain availability checker availab
This is the first time you mention this in the article and it looks new. How will a reader connect it to the parent concept being discussed?

2021-12-01 21:18 UTC, jerimkaura commented on content/articles/email-validator-in-flutter/index.md
> +I recommend any programmer to use any flutter application due to its' compatibility with all levels of flutter application, be it flutter web application, flutter mobile application, or any other app
A conclusion should summarize your article as well. What can be learned from your article is the conclusion here.

2021-12-02 06:11 UTC, joni-kano commented
Noted with thanks.i am working on it

On Thu, Dec 2, 2021, 12:18 AM Jerim Kaura ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @joni-kano <https://github.com/joni-kano>
>
> A quick one. Take the corrections I have suggested in the comments and
> address them in detail. Remember it is just about a working code, we need
> to have a great flow and easy-to-read content as well.
>
> Your article seems to have a lot of readability issues. Furnish it then
> ping me here or on slack @jerimkaura <https://github.com/jerimkaura>
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760569141>
> :
>
> > +Email validator is a Flutter package that checks whether an email is valid or not. It is not based on regular expression, but rather checks if the email entered is linked to a reliable domain. Domains that exist are Gmail, Yahoo, Outlook, among others.
> +<!--more-->
> +### Key takeaways
> +- What is an email validator?
> +- Explaining how an email validator works.
> +- Create a simple app to show email validator.
> +- Understand the implementation of email validator.
> +
> +### Working mechanism of email validator
> +Email validator runs a check on the emails through a process called `swift process`. This process detects typographical errors or deliberate mistakes. Furthermore, it helps to organize and clean all email addresses in a flutter application.
> +
> +For this reason, it protects the email sender score while maximizing the efficiency of the flutter application. The key concepts from the use of this package are validity, risk, and the invalidity of any email address.
> +
> +This package consists of a class and a function.
> +
> +The constructor for this class is pretty simple: Create a new instance of this class and set the validator type to either 1 or 2 (defaults to 1). The constructor should pass a string and an array of strings for validation.The arguments are also key factors.
>
> Explain type 1 and 2 and what each type does.
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760569796>
> :
>
> > +
> +  - url: /engineering-education/flutter-email-validator/hero.png
> +    alt: Flutter Email Validator Hero Image
> +---
> +Email validator is a Flutter package that checks whether an email is valid or not. It is not based on regular expression, but rather checks if the email entered is linked to a reliable domain. Domains that exist are Gmail, Yahoo, Outlook, among others.
> +<!--more-->
> +### Key takeaways
> +- What is an email validator?
> +- Explaining how an email validator works.
> +- Create a simple app to show email validator.
> +- Understand the implementation of email validator.
> +
> +### Working mechanism of email validator
> +Email validator runs a check on the emails through a process called `swift process`. This process detects typographical errors or deliberate mistakes. Furthermore, it helps to organize and clean all email addresses in a flutter application.
> +
> +For this reason, it protects the email sender score while maximizing the efficiency of the flutter application. The key concepts from the use of this package are validity, risk, and the invalidity of any email address.
>
> Explain the key concepts
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760570869>
> :
>
> > +The first argument is self-explanatory. It is just a boolean that specifies whether we are using the ***@***.***` format or `domain.com` as our string to validate.
> +
> +The second argument allows you to pass an array of strings that are valid domains for the email. This argument is only necessary if the string passed in as our first argument is in `domain.com` format; otherwise, it can be omitted.
> +
> +If either of the first two arguments contains an error, then false should be returned. Otherwise, true should be returned, and our string should be validated.
>
> Where are the arguments? Explain them in detail with a proper example to
> enable understanding of the concept.
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760571249>
> :
>
> > +1. Makes sure the user enters a correctly formatted email address while signing up.
> +2. Ensures emails are not on the blocklist and are not sent to blacklisted email addresses or domains.
> +3. Alerts if the username is available on the website during the registration process.
> +4. You can add it as a pre-requisite while submitting the app to the app store and google play store for review purposes.
>
> Explain how each benefit is acheived.
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760572960>
> :
>
> > +- Address CaptureSingle-line Address Verification Software.
> +- Address VerifyAddress Enhancement.
> +- Data CleanseBatch Data Cleanse & Maintenance.
> +- Bank VerificationBank Account, Sort Code & IBAN Validation.
> +- GeocodeLongitude & Latitude Data.
> +- Email ValidationCheck and Verify Email Addresses.
> +- This example brings us to the understanding usage of this API for serverless flutter applications.
>
> Provide a detailed explanation of how email validation works in each of
> the specified areas. What module of the system implemented it. At what
> level does it work. For instance, answer the question How is GeocodeLongitude
> & Latitude Data applying this concept?
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760573582>
> :
>
> > +1. Makes sure the user enters a correctly formatted email address while signing up.
> +2. Ensures emails are not on the blocklist and are not sent to blacklisted email addresses or domains.
> +3. Alerts if the username is available on the website during the registration process.
> +4. You can add it as a pre-requisite while submitting the app to the app store and google play store for review purposes.
> +
> +### Areas of application
> +- Address CaptureSingle-line Address Verification Software.
> +- Address VerifyAddress Enhancement.
> +- Data CleanseBatch Data Cleanse & Maintenance.
> +- Bank VerificationBank Account, Sort Code & IBAN Validation.
> +- GeocodeLongitude & Latitude Data.
> +- Email ValidationCheck and Verify Email Addresses.
> +- This example brings us to the understanding usage of this API for serverless flutter applications.
> +
> +### Benefits of using Email Validator.
> +Email validator works better in that it is a more accurate validation tool. In addition to validating email addresses, it also checks that domains are not likely to exist soon.
>
> More accurate than........? And will it determine that a domain will not
> exist soon?
> ------------------------------
>
> In content/articles/email-validator-in-flutter/index.md
> <https://github.com/section-engineering-education/engineering-education/pull/5116#discussion_r760574381>
> :
>
> > +3. Alerts if the username is available on the website during the registration process.
> +4. You can add it as a pre-requisite while submitting the app to the app store and google play store for review purposes.
> +
> +### Areas of application
> +- Address CaptureSingle-line Address Verification Software.
> +- Address VerifyAddress Enhancement.
> +- Data CleanseBatch Data Cleanse & Maintenance.
> +- Bank VerificationBank Account, Sort Code & IBAN Validation.
>  [...]

2021-12-03 13:06 UTC, joni-kano commented
@jerimkaura I have revised the article as you would want

2021-12-03 21:14 UTC, hectorkambow commented
> @jerimkaura I have revised the article as you would want

@joni-kano 

Please be sure you are going over the entire article as our peer reviewers are not responsible to point out every mistake - that is the authors responsibility. 

If any more major revisions are needed - we will be closing this PR asap. 👀 

cc @jerimkaura

2021-12-04 06:50 UTC, joni-kano commented
Acknowledged.

On Sat, Dec 4, 2021, 12:15 AM hectorkambow ***@***.***> wrote:

> @jerimkaura <https://github.com/jerimkaura> I have revised the article as
> you would want
>
> @joni-kano <https://github.com/joni-kano>
>
> Please be sure you are going over the entire article as our peer reviewers
> are not responsible to point out every mistake - that is the authors
> responsibility.
>
> If any more major revisions are needed - we will be closing this PR asap.
> 👀
>
> cc @jerimkaura <https://github.com/jerimkaura>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/5116#issuecomment-985832577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANT5VXKFWW47NMIJFP7F6VTUPEXNXANCNFSM5ILTDCCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-06 18:23 UTC, hectorkambow commented
reviewer pinged via slack

2021-12-06 18:56 UTC, jerimkaura commented
Hello @joni-kano 

Seem like your article still has a lot of readability issues. I will be closing this PR. Feel free to write on another topic or polish this until it's ready for publishing.

2021-12-06 18:56 UTC, closed without merging

2021-12-07 05:31 UTC, joni-kano commented
I will polish this until it's ready

On Mon, Dec 6, 2021, 9:56 PM Jerim Kaura ***@***.***> wrote:

> Closed #5116
> <https://github.com/section-engineering-education/engineering-education/pull/5116>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/5116#event-5722674657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANT5VXPID7FPY2UKPIGF7TTUPUBONANCNFSM5ILTDCCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>