Dealing with python's missing values: A complete guide
section-engineering-education/engineering-education pull request #5124
Opened 2021-11-19 14:50 UTC by jgesare

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4949 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-21 04:52 UTC, jgesare commented
@lalith1403 could you give this PR a look. Thanks

2021-11-21 04:56 UTC, jgesare commented
@srishilesh could you give this PR a look. Thanks

2021-11-22 12:48 UTC, srishilesh requested changes
@jgesare 

Welcome to EngEd program!

I've suggested a few major changes. It requires both formatting and flow changes. And, more importantly, I couldn't find in-depth explanation of concepts. (I have pointed out a few).

A few other suggestions:
- The article directory should be separated only with `-` with all letters in lowercase
- The format of author's info has been updated. Please make sure to update it here.
- Grammarly check must be done.

Take a look at other Section articles to get an idea on formatting and flow changes.

To allow you to make these changes, we would be closing this PR now. You can work on these changes in your forked branch.

Once you're done, you can create a new PR, and ping me.

Thanks.

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> + Machine learning and deep learning frameworks have nothing to do with data purification. As part of pre-processing, we'll look into Data Cleaning. The dataset's data structure can be improved by rem
A more briefer introduction could have been given.

Talk about what are missing values & preprocessing? why do we need to handle them? how to deal with it? what if we don't? Any live examples?

Have a look at other Section articles, to get an idea.

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +### The significance of completing the missing values
Add `Table of contents` and `Prerequisities`

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> + Machine learning and deep learning frameworks have nothing to do with data purification. As part of pre-processing, we'll look into Data Cleaning. The dataset's data structure can be improved by rem
A single line explanation of each would be enough for the intro

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +- Parameter estimations could be affected if data is lost.
Explain

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +- **Missing not at Random**
Formatting doesn't look good

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +dataset = pan.read_csv("IncomeAndGender.csv")
Where are we getting the dataset from?

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +dataset.shape
I guess you were trying this out in jupyter notebook/colab.

Make sure to use print statements here

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +There are both advantages and disadvantages to removing the rows/columns; for example, the model becomes more robust after deleting missing data. If you have a large amount of missing data, your mode
`There are both advantages and disadvantages to removing the rows/columns`

Please state them

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +After calculating the non-missing values in a column, each missing value can be restored individually and independently. This tool is severely limited if you want to use it with anything other than n
`This tool is severely limited` Tool?

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +Imputation based on the mean has a number of drawbacks, including the fact that technique only works with numerical datasets and fails when independent variables are correlated.
`Imputation based on the mean has a number of drawbacks`

State them

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +The median values of the population can be used to deal with outliers in the prior procedure. When sorting, a column's center value is updated rather than an outlier. No correlation between the indep
What are outliers?

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +The median values of the population can be used to deal with outliers in the prior procedure. When sorting, a column's center value is updated rather than an outlier. No correlation between the indep
What are independent variables?

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +It can be applied to categorical variables with a restricted number of values. You can use the drop-down menu to select the most common value. Education level is a good example of an ordinal categori
`You can use the drop-down menu to select the most common value.`

Drop down menu? Where did we get this from?

2021-11-22 12:48 UTC, srishilesh commented on content/articles/dealing-with-python's-missing-values-a-complete-guide/index.md
> +Data Cleaning is a feature of the data pre-processing module that we explored in this post. Furthermore, the loss of data may lead to skewed parameter estimations, reduced sample representativeness,
This looks like an abrupt ending to the article. Make sure to give a proper conclusion by specifying the results, key takeaways, a URL containing full working code, and reference links

2021-11-22 12:48 UTC, closed without merging

2021-11-27 16:12 UTC, jgesare commented
@srishilesh Please reopen my PR. I have all the changes waiting to be committed. Thanks in advance.