machine-learning-image-classification-with-javascript-and-nyckel
section-engineering-education/engineering-education pull request #5127
Opened 2021-11-19 18:25 UTC by vifabulous

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4833 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-20 12:22 UTC, jumamiller requested changes
-Introduction comes first.
-Remove extra spaces.
- Ensure all code snippets are well explained!

2021-11-20 14:01 UTC, vifabulous commented
@jumamiller I have made the neccesary changes. About the snippets, they have comments which explains the purpose of the code where neccesary

2021-11-26 10:34 UTC, LinusMuema commented
Hi @vifabulous 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Machine Learning image classification with Javascript and Nyckel #5127 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7608132/Machine.Learning.image.classification.with.Javascript.and.Nyckel.5127.Copyleaks.Report.pdf)

2021-11-27 05:37 UTC, vifabulous commented
@jumamiller I have made the requested changes

2021-11-30 14:27 UTC, vifabulous commented
@jumamiller ....What is the status of this article?

2021-11-30 14:47 UTC, jumamiller requested changes
Explain all code snippets! If possible, do not include CSS files unless necessary!

2021-11-30 17:35 UTC, vifabulous commented
@jumamiller  I have eliminated the CSS code and created a link for those who would like to get the code for a proper follow-up.
On the case of the understability of the code, I have preferred using comments inside the code at every step for step-by-step elaboration.

2021-12-01 18:36 UTC, hectorkambow commented
@jumamiller 

Thank you for the great feedback - lets take a look at the recent changes provided.

IF any other revisions are needed - lets provide some guidance on how to get the article up to par - and consider closing the PR. To allow the author the proper time to make any and all needed corrections.

2021-12-02 05:56 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +
Remove these spaces where applicable throughout your article!

2021-12-02 05:58 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +Nyckel is a Machine Learning API that provides automated training to models instead of manually writing the code. It also allows these models to be integrated into applications with the best simplici
You have alternating caps on the `Machine Learning!` except for API! Kindly fix that

2021-12-02 05:59 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +
Requirements should be placed right after table of contents!

2021-12-02 06:00 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +![styled](engineering-education/machine-learning-image-classification-with-javascript-and-nyckel/styled.png)
Fix this image path, there are multiple occurrence with this minor omission of '/' at the start!

2021-12-02 06:00 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +Javascript helps in client-side scripting. It mostly uses functions to enabled some activities in a webpage. Example of such activities to be enabled by these functions in this page include; upload b
Fixing alternating caps!

2021-12-02 06:02 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +This code below contains such functions. Create a Javascript file(.js) and place the code below in it. The functions have been clearly explained using comments to help you get everything right.
'This code below', could we find a better way? I think it's a wrong usage of 'this'. make your article flow!

2021-12-02 06:04 UTC, jumamiller requested changes
I've gone through your codes and I feel like the comments are not enough for explanations given the extensive nature of your codes! Kindly add code explanations right after the snippets!

Thank you!

2021-12-02 06:53 UTC, vifabulous commented
@jumamiller I believe the changes I have made settles all the issues

2021-12-02 07:00 UTC, jumamiller commented
> @jumamiller I believe the changes I have made settles all the issues

I'm still not satisfied with your code explanations. You see article can be read by any user, so please don't assume all readers will understand everything! Please don't risk an article being closed for this minor edit!

2021-12-02 07:02 UTC, vifabulous commented
Ok, I will be working on it right away

2021-12-02 07:30 UTC, vifabulous commented
I believe it's more clear now @jumamiller

2021-12-02 07:46 UTC, jumamiller reviewed
Closing for now. You may submit a new polished article with all the required explanations!

2021-12-02 07:46 UTC, jumamiller commented on content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
> +```
I'm closing this article due to lack of flow on this part. It has important code snippets that require thorough explanations.
The author has added in-line comments but they are not enough for the reader to understand the general flow of the article!

2021-12-02 07:47 UTC, jumamiller commented
I'm closing this article as it requires more levels of revisions!

2021-12-02 07:47 UTC, closed without merging