Building a lyrics search app with vanilla javascript.
section-engineering-education/engineering-education pull request #5131
Opened 2021-11-19 22:42 UTC by shegz101

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-23 08:24 UTC, adrianmurage commented
@section-engineering-education/content-moderator-team Kindly run this plagiarism check for me.
Thanks 😄

2021-11-26 10:39 UTC, LinusMuema commented
Hi @adrianmurage & @shegz101 

Please check the files submitted. I can see there are duplicates especially in the index.md

2021-11-26 12:55 UTC, shegz101 commented
> Hi @adrianmurage & @shegz101
> 
> Please check the files submitted. I can see there are duplicates especially in the index.md

Please I do not really understand this,I thought I submitted just one index.md file.

2021-11-26 13:14 UTC, LinusMuema commented
Check the files section of this PR

2021-11-26 18:11 UTC, adrianmurage commented
@shegz101 

You submitted two directories: 
`building-a-lyrics-search-app-with-vanilla-javscript`
`building-a-lyrics-search-app-with-vanilla-javascript`

Kindly delete one

I will be reviewing the one with JavaScript spelled correctly

2021-12-01 18:34 UTC, hectorkambow commented
@adrianmurage can we get a status on this PR. 

If it needs any revisions lets consider closing the PR to allow the author the proper time to implement the needed corrections.

2021-12-01 21:34 UTC, shegz101 commented
@hectorkambow this is the second PR am opening for this article, the first was closed due to some errors in the article and I have fixed the issues in this new PR

2021-12-03 15:33 UTC, adrianmurage requested changes

2021-12-03 15:33 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-javascript/index.md
> +##Prerequisites
Kindly use the correct heading structure 
```suggestion
### Prerequisites
```

2021-12-03 15:33 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-javascript/index.md
> +..* A laptop with an internet connection
Kindly use the correct list structure

2021-12-03 15:33 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-javascript/index.md
> +##Structuring The Lyrics Search App With Html5.
Kindly use the correct heading structure

2021-12-03 15:33 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-javascript/index.md
> +..*`lyrics.js`
Kindly use the correct list structure

Though, I'm not sure whether or not this is supposed to be a list 🤔

2021-12-03 15:42 UTC, adrianmurage commented
Hey @shegz101     👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

Good job on the article. It is a very interesting read.

Just a few changes I need you to make as we continue with the preliminary revisions:
- Your headings do not follow the EngEd guidelines. Refer to the [Example Article Submission](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/example_article_submission.md) for what you're supposed to do instead
- I noticed a few incorrectly formatted lists. Kindly correct those. You can refer to the [Example Article Submission](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/example_article_submission.md) for the same
- All your images including your avatar image should be scaled down to 600 x 400 px as required. You can use [Befunky](https://www.befunky.com/) to do this.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Meanwhile I'll be closing this PR to clear up the PR queue. When you make all the changes and ensure your article is ready to be published. Open a new PR and ping me : )

Looking forward to reviewing and publishing your work!
Regards.

2021-12-16 07:09 UTC, closed without merging