Building Autocorrect Feature Using NLP with Python
section-engineering-education/engineering-education pull request #5135
Opened 2021-11-20 12:29 UTC by dentex22

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4941 `

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-20 12:30 UTC, dentex22 commented
reference #4991

2021-11-22 13:45 UTC, dentex22 commented
@srishilesh any updates??

2021-11-22 13:49 UTC, srishilesh commented
> @srishilesh any updates??

@dentex22 

Please wait for your previous test reviewer @okeloviolet to review this.

Thanks.

2021-11-23 17:19 UTC, srishilesh commented
@hectorkambow 

Are we still allowing test peer-reviewers to review articles?

If not, I can take up and review this PR. It has been pending for a while.

Thanks.

2021-11-23 17:29 UTC, okeloviolet commented
@srishilesh feel free to review the article though I started reviewing the article here #4991

2021-11-25 13:51 UTC, srishilesh commented
@dentex22 

I'll start my review ASAP.

2021-11-25 22:03 UTC, dentex22 commented
> @dentex22
> 
> I'll start my review ASAP.

ok

2021-11-27 06:55 UTC, srishilesh requested changes
@dentex22 

Your article formatting looks great.

I've suggested very minor changes. Please ping me when it's done.

Thanks.

2021-11-27 06:55 UTC, srishilesh commented on content/articles/building-autocorrect -feature-using-nlp-with-python/index.md
> +```python
bash

2021-11-27 06:55 UTC, srishilesh commented on content/articles/building-autocorrect -feature-using-nlp-with-python/index.md
> +    print(f"word {i}: {word_prob[0]}, probability {word_prob[1]:.6f}")
Can we break this big code block down into several code blocks for each method?

And, you could explain each of them below the code snippet.

2021-11-27 06:55 UTC, srishilesh commented on content/authors/antony-lia/index.md
> +type: authors
Could you please refer the latest updated authors file?

2021-11-27 09:10 UTC, dentex22 commented
@srishilesh done with changes

2021-11-28 12:47 UTC, srishilesh approved these changes
@dentex22 

Great article.

I've made some changes to the formatting and flow. Make sure to go through the commits.

Also, thanks for adding the front matter and PRC line.

Moving for the final review.

Thanks.

2021-11-28 16:16 UTC, dentex22 commented
> @dentex22
> 
> Great article.
> 
> I've made some changes to the formatting and flow. Make sure to go through the commits.
> 
> Also, thanks for adding the front matter and PRC line.
> 
> Moving for the final review.
> 
> Thanks.

ook @srishilesh

2021-12-04 13:43 UTC, ahmadmardeni1 commented
Welcome to Section EngEd and congrats on your first article @dentex22 
Thank you for the review @srishilesh 

Please go over the changes I've made.

2021-12-04 13:43 UTC, merged

2021-12-10 20:26 UTC, hectorkambow commented
Please reach out to me via Slack DM @dentex22