Introduction To PHP Graphic Techniques
section-engineering-education/engineering-education pull request #5138
Opened 2021-11-20 22:23 UTC by SarahAsuquo

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4768 `

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-20 22:30 UTC, SarahAsuquo commented
Hello @WanjaMIKE,@jumamiller this is a duplicate of #4953. I have effected all the necessary changes and hopefully it is ready for review. 
Cc.
@hectorkambow

2021-11-22 17:00 UTC, jumamiller commented
> Hello @WanjaMIKE,@jumamiller this is a duplicate of #4953. I have effected all the necessary changes and hopefully it is ready for review. Cc. @hectorkambow

Seems you got multiple files?

2021-11-22 17:45 UTC, SarahAsuquo commented
@jumamiller sorry, I don't quite understand your question. My intention is to resubmit an already closed pull request that needed changes. Could you please delete the multiple files for me if they're not needed.

2021-11-30 02:24 UTC, hectorkambow commented
@SarahAsuquo  

Please look at our [resources ](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors)to see how to go about fixing this 👍 
 Thank you

2021-11-30 02:26 UTC, hectorkambow commented
The pull request should have only the file(s) [index file and any corresponding images] you plan on submitting and having published. 🚀

2021-11-30 02:27 UTC, hectorkambow commented
Not sure which one needs to be deleted (are the merely duplicates) copies??

2021-11-30 17:53 UTC, jumamiller requested changes
Kindly explain all code snippets as much as possible.

2021-11-30 17:53 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +•	 A code editor like Visual Studio Code[link].
The link seems to be incomplete?

2021-11-30 17:53 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +•	 Apache web server, Preferably WAMP[link] or XAMPP[link].
XAMPP/WAMPP is a stack, are they really servers?

2021-12-01 14:04 UTC, SarahAsuquo commented
@jumamiller I have made the necessary corrections.

2021-12-01 14:24 UTC, SarahAsuquo commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +•	 Apache web server, Preferably WAMP[link] or XAMPP[link].
I'm sorry for the mistake, it was a typographical error. I've corrected it in the updated file.

2021-12-01 18:31 UTC, hectorkambow commented
@SarahAsuquo our peer reviewer will jump on the updates asap - he is busy reviewing other pull request as well. 

Thank you for your patience as our team is working diligently to work through the increased volume of articles.

2021-12-03 21:15 UTC, hectorkambow commented
@jumamiller 
can we get a status on this PR ? 

If any more major revisions are needed - we will be closing this PR asap. 👀

2021-12-04 05:40 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +PHP has the inherent ability to create and manipulate graphics independently. The scope and capabilities of PHP graphic handling is quite deep and powerful. It does this with the aid of the GD librar
- This should be a standalone paragraph. Also, The second sentence should have some transitions to aid in article flow. For example, `....Therefore, the scope and capabilities`,.

-  Fix singular verb that doesn't agree with plural compound subject.
- Make good use of commas.
-  Quote unrecognised English words.

2021-12-04 05:42 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +This tutorial aims at providing a solid foundation on the first steps to take to start doing exploits with PHP graphics. If you’re as excited as I am, then let’s proceed.
This sentence here is not quite clear and it's hard to follow. Let's have a simple sentence.

For example `This tutorial aims to provide a solid foundation on the first steps to start doing exploits with PHP graphics.` is much better that what you currently have!

2021-12-04 05:43 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +•	 Apache web server, Preferably [WampServer](https://www.wampserver.com/en/).
Ensure you write mnemonics correctly as they appear in documentations!

2021-12-04 05:44 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +•	 GD library/extension. You can confirm if you have it installed by searching for “gd” in your php.ini file. You should find “etension=php_gd2.dll” else download it for free on the internet.
What does `etension` in PHP?

2021-12-04 05:44 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +Assuming you are a conventional artist and you want to draw a picture, you will likely require three things: a canvas to draw on, a paint brush to draw with and you’ll need ink for the paint brush to
Punctuations!

2021-12-04 05:48 UTC, jumamiller requested changes
Hi, kindly rework on this article to fix punctuation marks mistakes. Reorganise your article to have flow, this includes avoiding wordy words and breaking them into distinct paragraphs!

Meanwhile the changes are quite a number, that I feel you should revise the entire work to fix your grammar as well. This helps in fixing minor singular ,plural mistakes et cetera.

Feel free to reach me on Slack (@Miller).

2021-12-05 08:55 UTC, jumamiller commented
> Hi, kindly rework on this article to fix punctuation marks mistakes. Reorganise your article to have flow, this includes avoiding wordy words and breaking them into distinct paragraphs!
> 
> Meanwhile the changes are quite a number, that I feel you should revise the entire work to fix your grammar as well. This helps in fixing minor singular ,plural mistakes et cetera.
> 
> Feel free to reach me on Slack (@miller).

still waiting for updates!

2021-12-05 11:52 UTC, SarahAsuquo commented
@jumamiller please I'm working on the corrections currently, I'll be done in a few hours. Thanks for your patience.

2021-12-05 15:03 UTC, SarahAsuquo commented
@jumamiller i have made the requested updates to the file. Please take a look.

2021-12-05 16:24 UTC, jumamiller commented on content/articles/introduction-to-php-graphic-techniques/index.md
> +•	GD library/extension. You can confirm if you have it installed by searching for “gd” in your php.ini file. You should find “extension=php_gd2.dll” else download it for free on the internet.
Fix formatting issues here..

2021-12-05 16:27 UTC, jumamiller requested changes
Hello @SarahAsuquo which updates have you made? I can see you have very very long paragraphs...kindly break them down. Revise the whole article, just take your time and polish it well! If you have any query, contact me on Slack.

FYI: Any further revision from this step will result in article closure!

2021-12-05 20:07 UTC, SarahAsuquo commented
@jumamiller I have given the article a total review and changes have been made. I sincerely hope it meets standard this time.

2021-12-06 11:58 UTC, jumamiller commented
Hi, reach me on slack @Miller.

2021-12-06 18:24 UTC, hectorkambow commented
@SarahAsuquo 
Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) - this allow all revisions to be done on your forked personal repo. 
 
We will be closing this PR and please re-submit it when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 
 
>NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
 
Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 
cc @jumamiller

2021-12-06 18:24 UTC, closed without merging