Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python
section-engineering-education/engineering-education pull request #5147
Opened 2021-11-21 17:08 UTC by iannjari

Created:    /content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
This article gives a tutorial on Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python
Image:   /content/articles/save-and-load-stacked-ensembles-in-onnx/index.md

Added Author Profile:   /content/authors/ian-njari/index.md
Avatar:   /content/authors/ian-njari/avatar.jpg
This closes #5060

2021-11-22 13:31 UTC, srishilesh requested changes
@iannjari 

Welcome to EngEd program!

Great article. I've suggested a few changes. Have a look at them.

Let's wait for plagiarism check, before we start the next round of review.

Ping me when you're done with the changes.

Thanks.

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +Stacked ensemble models are learners that increase predictive performance over stand-alone learners by combining the results of two or several models and running them through a meta-learner. The stac
```suggestion
Stacked ensemble models are learners that increase predictive performance over stand-alone learners by combining the results of two or several models and running them through a meta-learner. The stacked models are different (not a single type), unlike in bagging methods (just decision trees) and each of the model in the stack does not correct the predictions of the previous ones as it happens in boosting. You can learn how to build one by reading [this article by Adhinga Fredrick](/engineering-education/ensemble-learning-based-regression-model-using-python/).
```

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +Open Neural Network Exchange (ONNX) is an open source format for deep and traditional machine learning developed by Microsoft that has a unified schema for saving models despite the library they were
Add link for ONNX

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +Container-based methods of pushing models to production like Docker can also be by-passed altogether.
Could you brief more about these 2 lines?

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +## Table of Contents
```suggestion
### Table of contents
```

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +  5. Loading the model using ONNX runtime Inference Session
Make these unordered lists using `-`, and indent them towards left.

Add hyperlinks if possible

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +  4. Python(with pip,numpy,pandas and Scikit-Learn) installed on your computer, or an online environment like Google Colab or Kaggle
Use `-`

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> ++ If using pip, on your terminal;
Use `-` for bullet points

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +```
```suggestion
```bash
```

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +```
Do this change for all the code snippets

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +Let's start by importing pandas and the data
Explain more about the dataset, and where are we getting this from?

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +![DataFrame](df1.png)
Image path is incorrect. Please rectify.

Do this for all the images

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +data
Use print(), since this would be a python code snippet and not a notebook script

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +Import packages;
Add links that speak about these models and give a single line explanation of each

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +pipeline.score(x_test,y_test)
print()

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +***Note:** If establishing the initial types is challenging, for example, the data has too many features, the ```to_onnx``` method handles this directly for you.
```suggestion
> NOTE: If establishing the initial types is challenging, for example, the data has too many features, the ```to_onnx``` method handles this directly for you.
```

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +You just need to pass the x test data (or one of it's column) as an argurment and ONNX extracts it automatically.
```suggestion
You just need to pass the `x_test` data (or one of it's column) as an argurment and ONNX extracts it automatically.
```

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +[Common errors with onnxruntime](http://onnx.ai/sklearn-onnx/auto_examples/plot_errors_onnxruntime.html?highlight=errors)
Make these as bulleted points

2021-11-22 13:31 UTC, srishilesh commented on content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
> +
Add an URL containing full working code. (It can be colab notebook or Github repo)

2021-11-22 16:36 UTC, hectorkambow commented
@iannjari 
 it seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 
cc @srishilesh

2021-11-22 16:36 UTC, closed without merging

2021-11-23 04:50 UTC, srishilesh commented
@iannjari 

You can create a new PR with all these suggested changes. Ping me once you're done.

Make sure that your new PR is ready to be published, and needs no extra revisions.

Thanks.