how-to-build-discord-bot-with-javascript
section-engineering-education/engineering-education pull request #5159
Opened 2021-11-22 08:10 UTC by Kamau-ke

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-22 08:17 UTC, Kamau-ke commented
this fixes #5159

2021-11-26 11:25 UTC, LinusMuema commented
Hi @Kamau-ke 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[How to build discord bot with JavaScript #5159 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7608432/How.to.build.discord.bot.with.JavaScript.5159.Copyleaks.Report.pdf)

2021-12-01 07:28 UTC, Kamau-ke commented
@LinusMuema Hello, I made the changes that you requested.

2021-12-01 12:11 UTC, mercymeave requested changes
Hello @Kamau-ke 

Thank you for submitting your first article. Here is a list of things to take care of as we get your article ready for publish.

- Avoid using contractions.
- Organize your ideas into sentences to explain the concepts you deliver instead of instructions. Basically, every operation is explained to the user. 
- Use comments for your application to aid in explaining the code.
- Provide a link to the code of the application built.

2021-12-01 12:11 UTC, mercymeave commented on content/articles/how-to-build-discord-bot-with-javascript/index.md
> +in case you don't have a server. Login to your discord account and create one.
Provide a name to your images for example,    `![image name]/education-engineering/how-to-build-discord-bot-with-javascript/bot.png)`

2021-12-01 12:11 UTC, mercymeave commented on content/articles/how-to-build-discord-bot-with-javascript/index.md
> +Dependencies are packages that are required by other packages to work. Here we will be using ``discord.js``, ``dotenv`` and ``nodemon``.
Add a space between one heading and the next. This should be done across the article to make it readable.

2021-12-01 12:11 UTC, mercymeave commented on content/articles/how-to-build-discord-bot-with-javascript/index.md
> +nodemon restart the server every time we make a change to our files.
1. Provide deeper explanations for these. Yours look like you are taking short notes.
2. Start all sentences with a capital letter.
3. Avoid too much bulleted work and try to explain in full sentences.

2021-12-01 12:11 UTC, mercymeave commented on content/articles/how-to-build-discord-bot-with-javascript/index.md
> +It's done by clicking the copy button in the bot tab. As shown below
I recommend you refrain from using contractions. Do that throughout the article.

2021-12-01 12:11 UTC, mercymeave commented on content/articles/how-to-build-discord-bot-with-javascript/index.md
> +Below is our entire code:
Avoid bulleted points. Explain these in a paragraph with sentences related to each other.

2021-12-01 12:11 UTC, mercymeave commented on content/articles/how-to-build-discord-bot-with-javascript/index.md
> +})
Why do you have a code snippet after your summary?

2021-12-01 18:21 UTC, hectorkambow commented
@Kamau-ke 
It seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - we only accept content (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

**Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.**

Looking forward to published your completed and polished article 🚀

2021-12-01 18:21 UTC, closed without merging