Working with Ktor-Client: How to Build and Make HTTP Requests With Ktor-Client in Android Jetpack Compose
section-engineering-education/engineering-education pull request #5231
Opened 2021-11-25 17:16 UTC by manmusa100

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4858

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-01 18:38 UTC, louisefindlay23 commented
Plagiarism check complete

2021-12-10 13:23 UTC, Ericgacoki requested changes
Hello @manmusa100,
It's amazing to see how well you've covered Ktor in this tutorial. Just a few changes (see the comments attached below) and we'll be good to go :rocket:

2021-12-10 13:23 UTC, Ericgacoki commented on content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/index.md
> +
Did you mean `Let's see how we can...`?
If so, fix the first sentence.

2021-12-10 13:23 UTC, Ericgacoki commented on content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/index.md
> +        value = apiService.getProducts()
👏

2021-12-10 13:23 UTC, Ericgacoki commented on content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/index.md
> +
Just before the conclusion, provide at least one image - a screenshot of what to expect upon running the app.

2021-12-11 15:08 UTC, manmusa100 commented
Hi @Ericgacoki, Check the changes I have added.

`gradle` identifier failed to render the code syntax, I have used `koltin` instead.

2021-12-11 15:17 UTC, Ericgacoki commented
> Hi @Ericgacoki, Check the changes I have added.
> 
> `gradle` identifier failed to render the code syntax, I have used `koltin` instead.

`gradle` usually doesn't highlight the syntax properly especially on VsCode. Don't worry about it 😇

2021-12-15 13:33 UTC, Ericgacoki approved these changes

2021-12-16 10:12 UTC, LinusMuema commented
Hi @manmusa100 

Great work on the article.

cc: @Ericgacoki

2021-12-16 10:12 UTC, merged

2021-12-17 19:47 UTC, hectorkambow commented
@manmusa100 I think this article has the wrong author on it 🤔  

@Ericgacoki 
cc @LinusMuema 

not sure - trying to double check

2021-12-17 19:57 UTC, Ericgacoki commented
I've checked @manmusa100's author file(s) and his previous article(s). The author name is similar to the one used in this article (`author: moses-chege`).