[c#]Cycle Detection in a graph
section-engineering-education/engineering-education pull request #5235
Opened 2021-11-25 22:45 UTC by erixbiz

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes  #4644

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-25 22:47 UTC, erixbiz commented
@jumamiller  kindly have a look at this new PR. Gone through the article and others as well. I am optimistic that there is a flow now. Thank you.

2021-12-01 17:29 UTC, hectorkambow commented
@jumamiller 

Just wanted to get a status on this PR. 

Lets be sure to NOT be assigning ourselves too many PRs at once - as we do not want our review time to be affected.

2021-12-01 17:29 UTC, hectorkambow commented
cc @section-engineering-education/content-moderator-team

2021-12-01 18:07 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +
Remove these extra spacings throughout your article!

2021-12-01 18:08 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +2. Some ordered pairs of the form (u, v) are called edges.
Could we have a better intro?

2021-12-01 18:08 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +#### Prerequisite
Prerequisites?

2021-12-01 18:09 UTC, jumamiller commented on content/articles/graph-cycle-detection-c#/index.md
> +
Kindly work on these spacings!

2021-12-01 18:10 UTC, jumamiller requested changes
Hi, kindly work on the intro part as suggested. Next work on your spacings where applicable!

2021-12-02 23:54 UTC, erixbiz commented
@jumamiller  kindly have a look. Thank you

2021-12-03 21:31 UTC, hectorkambow commented
@jumamiller 

can we get a status on this PR ?

If any more major revisions are needed - we will be closing this PR asap. 👀

@erixbiz 
Please be sure you are going over the entire article as our peer reviewers are not responsible to point out every mistake - that is the authors responsibility.

2021-12-05 11:54 UTC, jumamiller commented
Hi @erixbiz, kindly reach me on Slack ASAP!

2021-12-05 12:02 UTC, jumamiller commented
Hi @erixbiz, kindly fix all image paths  to this:` graph-cycle-detection-c#` the current one is misses the `-c#` part...

2021-12-05 13:45 UTC, jumamiller approved these changes
Approved!

2021-12-08 20:46 UTC, hectorkambow commented
jumping on this one

2021-12-08 21:10 UTC, hectorkambow commented
@erixbiz 

This article is somewhat difficult to understand. 

There seems to be steps missing??

2021-12-08 21:11 UTC, hectorkambow commented
@erixbiz 
How are we going from step 7 back to a number 6?? 

![image](https://user-images.githubusercontent.com/60800358/145285057-8e75bc95-7568-4291-a42b-371b61550418.png)

cc @jumamiller

2021-12-10 19:08 UTC, hectorkambow commented
Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) - this allow all revisions to be done on your forked personal repo. 
 
We will be closing this PR and please re-submit it when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 
 
>NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
 
Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍

2021-12-10 19:08 UTC, closed without merging