Build a Static Next.js Markdown Files Blog with Typescript, MDX and Tailwind CSS
section-engineering-education/engineering-education pull request #5245
Opened 2021-11-26 14:56 UTC by Rose-stack

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-06 12:16 UTC, Kayere commented
Hello @Rose-stack.

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Build a Static Next.js Markdown Files Blog with Typescript, MDX and Tailwind CSS #5245 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7660542/Build.a.Static.Next.js.Markdown.Files.Blog.with.Typescript.MDX.and.Tailwind.CSS.5245.Copyleaks.Report.pdf)

2021-12-07 18:02 UTC, srishilesh commented
@zolomohan 

I'll take up this PR for further review.

2021-12-07 18:09 UTC, srishilesh requested changes
Hey @Rose-stack ,

I've suggested very minor changes. Please ping me when they're done.

Also, have a look at the plagiarism check and make changes accordingly.

Thanks.

2021-12-07 18:09 UTC, srishilesh commented on content/articles/build-a-static-nextjs-markdown-files-blog-with-typescript-mdx-tailwindcss/index.md
> +To use with MDX;
Can we add an additional paragraph that talks about MDX?

2021-12-07 18:09 UTC, srishilesh commented on content/articles/build-a-static-nextjs-markdown-files-blog-with-typescript-mdx-tailwindcss/index.md
> +```ts
` ```ts `

Is it not `js`?

2021-12-07 18:09 UTC, srishilesh commented on content/articles/build-a-static-nextjs-markdown-files-blog-with-typescript-mdx-tailwindcss/index.md
> +
Can we have the full working code in a GitHub URL?

2021-12-07 18:09 UTC, srishilesh commented on content/articles/build-a-static-nextjs-markdown-files-blog-with-typescript-mdx-tailwindcss/index.md
> +Next.js is an amazing React-based framework. It allows you to work with almost any aspect of bot server-side and client-side content. It is very lightweight and allows you to create full fledge fast
It would be great if you could add some reference links that the reader could go through

2021-12-08 07:01 UTC, Rose-stack commented
Hello, @srishilesh Check the newly added changes and recommendations.

2021-12-14 16:57 UTC, srishilesh commented
Jumping to this for final tech review.

2021-12-14 18:11 UTC, srishilesh approved these changes
@Rose-stack 

Amazing article.

Made some minor changes to flow and formatting. Make sure to go through them.

Moving for the final review.

Thanks.

2021-12-15 20:28 UTC, hectorkambow commented
jumping on this one

2021-12-15 21:01 UTC, merged