How to integrate safaricom lipa na mpesa in php
section-engineering-education/engineering-education pull request #5246
Opened 2021-11-26 14:57 UTC by HillaryKiprono

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4972

2021-11-28 08:10 UTC, jumamiller commented on content/articles/how-to-integrate-safaricom-lipa-na-mpesa-in-php/index.md
> +Inside the file declare and initialize the following variables using your credentials obtain from an app you created in  safaricom Daraja.
Why are we declaring these variables?

2021-11-28 08:11 UTC, jumamiller commented on content/articles/how-to-integrate-safaricom-lipa-na-mpesa-in-php/index.md
> +```
What's the use of this auth token?

2021-11-28 08:12 UTC, jumamiller commented on content/articles/how-to-integrate-safaricom-lipa-na-mpesa-in-php/index.md
> +```
This code doesn't work!

2021-11-28 08:12 UTC, jumamiller commented on content/articles/how-to-integrate-safaricom-lipa-na-mpesa-in-php/index.md
> +
The whole code cannot work!

2021-11-28 08:13 UTC, jumamiller commented on content/articles/how-to-integrate-safaricom-lipa-na-mpesa-in-php/index.md
> +
Attach these outputs on each step

2021-11-28 08:13 UTC, jumamiller requested changes
Explain your code snippets! The current code doesn't work too!

2021-12-05 13:46 UTC, jumamiller commented
Any update @HillaryKiprono ?

2021-12-06 12:20 UTC, Kayere commented
Hello @HillaryKiprono.

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[How to integrate safaricom lipa na mpesa in php #5246 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7660573/How.to.integrate.safaricom.lipa.na.mpesa.in.php.5246.Copyleaks.Report.pdf)

2021-12-06 12:21 UTC, Kayere commented
@HillaryKiprono - The article seems to be a bit short and of low substance. Please add more content to the article to give it more value.

2021-12-06 12:23 UTC, closed without merging