Implementing a generic singly linked list data structure in java
section-engineering-education/engineering-education pull request #5261
Opened 2021-11-27 12:07 UTC by LynnMumo

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4382

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-27 12:09 UTC, LynnMumo commented
@lalith1403 @Dawe-7 
This is the new PR
Duplicate of #4691

2021-12-01 16:07 UTC, Dawe-7 requested changes
Hello @LynnMumo, could you check on the comment i've left.

2021-12-01 16:07 UTC, Dawe-7 commented on content/articles/implementing-a-generic-singly-linked-list-data-structure-in-java/index.md
> +- Add an element to a specific location, use add(T data, int index).
@LynnMumo, The paragraph here doesn't seem to flow very, especially how you started listing the methods "Last but not least. Kindly rephrase it in a more comprehensive way.

2021-12-01 17:27 UTC, hectorkambow commented
@Dawe-7 we will be closing this PR to allow the author the proper time to make any and all needed corrections.

This is a duplicate PR - if any more changes were needed (in general) we should close the PR immediately especially if its a duplicate PR (generally there are always exceptions).

 cc @LynnMumo 
 
 It seems this PR is still quite a bit aways from being completed.  As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is _ready to be published_ as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

2021-12-01 17:35 UTC, Dawe-7 commented
> @Dawe-7 we will be closing this PR to allow the author the proper time to make any and all needed corrections.
> 
> This is a duplicate PR - if any more changes were needed (in general) we should close the PR immediately especially if its a duplicate PR (generally there are always exceptions).
> 
> cc @LynnMumo
> 
> It seems this PR is still quite a bit aways from being completed. As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published.
> 
> All revisions and edits should be completed on your own forked repo (as to not take up room in the queue).
> 
> We will be closing this and please re-submit when it is _ready to be published_ as a new PR (and you can add the duplicate label) and ping the reviewer and myself.
> 
> Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

Okay @hectorkambow

2021-12-01 19:27 UTC, LynnMumo commented
@Dawe-7 
I have done some edits for the requested changes. You can reopen the PR and have a look at my last commit. Thanks.
cc @hectorkambow

2021-12-01 19:30 UTC, Dawe-7 commented
@linetachieng, reopening so changes can be effected.

2021-12-03 21:33 UTC, hectorkambow commented
@LynnMumo 

Good afternoon and thank you for submitting your topic to the EngEd program. 
If it seems this PR is still quite a bit aways from being completed. 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
All revisions and edits should be completed on your own forked repo (as to not build up a backlog in the queue). 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
 
👍

2021-12-04 05:50 UTC, LynnMumo commented
@hectorkambow the article was ready. I did some changes when the article was closed. I don't understand why you closed it again.

2021-12-04 06:15 UTC, Dawe-7 commented
@hectorkambow, the author created a new PR and it was in final review on my end. I was going through everything to ensure it was ready for publishing. The article did not have extensive revisions, any delays caused were on my end.

2021-12-04 06:59 UTC, Dawe-7 commented
@hectorkambow, reopening to finish review.

2021-12-04 07:02 UTC, Dawe-7 approved these changes
@LynnMumo, kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

@hectorkambow , this article is ready for final review.

2021-12-07 20:44 UTC, hectorkambow commented
I'll be jumping on this one

2021-12-07 21:23 UTC, merged

2021-12-07 23:16 UTC, hectorkambow commented
@LynnMumo 

Question how did you start to submit your article without signing up with the program?

2021-12-08 04:08 UTC, LynnMumo commented
We were having a discussion about EngEd with my friends and that's how I
found out that I never enrolled. All I knew was that you only submit a
topic and the other activities follow. I'm sorry.

On Wed, Dec 8, 2021, 2:16 AM hectorkambow ***@***.***> wrote:

> @LynnMumo <https://github.com/LynnMumo>
>
> Question how did you start to submit your article without signing up with
> the program?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/5261#issuecomment-988331894>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVN5LCNPRX3V7FP7SMWMCUDUP2IUBANCNFSM5I4D2KTQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>