Testing vue components with Cypress
section-engineering-education/engineering-education pull request #5267
Opened 2021-11-28 05:44 UTC by Wanjiku25

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4723

2021-11-28 08:17 UTC, jumamiller commented on content/articles/testing-vue-components-with-cypress/index.md
> +We may make assertions on the covering that Vue Test Utils gives around the mounted part utilizing cypress. We can test the part's usefulness as a client without composing any system explicit code, a
Too long for a paragraph in this case! Break them down!

2021-11-28 08:18 UTC, jumamiller requested changes
Could you attach your test case screenshots or link to the code?

2021-11-28 10:16 UTC, Wanjiku25 commented
@jumamiller, The changes are in place

2021-11-30 01:55 UTC, hectorkambow commented
@jumamiller just added a label of assigned - not sure if any other labels are needed. 

If we have too many PRs on our plate - lets consider pinging our Peer reviewer team members to help out. 

We need to be mindful of all the students in the queue.

2021-12-05 13:48 UTC, jumamiller commented on content/articles/testing-vue-components-with-cypress/index.md
> +In the wake of performing something Vue-explicit, you never need to trust that a '$nexttick' from Vue will refresh the condition of the part
This is very long, break down into paragraphs!

2021-12-05 13:48 UTC, jumamiller commented on content/articles/testing-vue-components-with-cypress/index.md
> +The code in that repo is organized in a pretty normal manner, with a plugins subdirectory containing plugins that produce veutif instances. The application imports this, but our test setup may also i
This paragraph should be separated to the one following it below!

2021-12-05 13:49 UTC, jumamiller commented on content/articles/testing-vue-components-with-cypress/index.md
> +This takes use of Cypress's need to create a root element to which your component may be attached. That root element, which has the ID __cy root, is your component's parent. This gives everyone a han
Very long sentence? Is it possible to break it down into paragraphs?

2021-12-05 13:49 UTC, jumamiller commented on content/articles/testing-vue-components-with-cypress/index.md
> +Recommendation: put the mounting order and its conditions in its own record and only use it in component tests when necessary.
Separate paragraphs with a space in between!

2021-12-05 13:49 UTC, jumamiller commented on content/articles/testing-vue-components-with-cypress/index.md
> +
Breakdown into 2 paragraphs!

2021-12-05 13:50 UTC, jumamiller requested changes
Hi, you have multiple long sentences, kindly break them down into paragraphs where applicable!

2021-12-06 18:51 UTC, hectorkambow commented
@Wanjiku25 

👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content
[Testing vue components with Cypress #5267.pdf](https://github.com/section-engineering-education/engineering-education/files/7662890/Testing.vue.components.with.Cypress.5267.pdf)


cc @jumamiller

2021-12-06 18:51 UTC, closed without merging

2021-12-07 05:28 UTC, Wanjiku25 commented
Hello 👋@hectorkambow,thank You for the reference where I can check for plagiarism,I used my own words to paraphrase, requesting whether you can re-open my PR again I check for plagiarism using that site by kindly.