Object detection with YOLOv5 and PyTorch
section-engineering-education/engineering-education pull request #5270
Opened 2021-11-28 08:52 UTC by FREDERICO23

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4636 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-28 08:54 UTC, FREDERICO23 commented
@srishilesh kindly review the tutorial now. It was one commit away before a final review.

2021-11-29 14:43 UTC, srishilesh requested changes
@FREDERICO23 

I've suggested a few changes. Please go through them.

On a quick glance, your code snippets lacks explanation. Please don't just state these code snippets, instead explain the "why" and "how" of each block.

Ping me when the changes are done.

Duplicate of #5038.

Thanks.

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +When it comes to perfomance, YOLO outperforms other object detectors by far. In real-time, it is able to process images at a rate of around 155 frames per second, achieving double the mAP(Mean Averag
`mAP(Mean Average Precision)`

Explain more about it

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +YOLOv5, the latest release of the YOLO family is a group of compound-scaled object detection models trained on the COCO dataset used for model ensembling, Test Time Augmentation (TTA) and hyperparame
`model ensembling, Test Time Augmentation (TTA) and hyperparameter evolution.`

Add single line explanation about these

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +```
What are we testing here? Be brief

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images
Explain these arguments as well.

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +```
What do you mean by other objects?

Be clear.

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +results.pandas().xyxy[0]
What are we doing here?

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +Since the COCO dataset is automatically downloaded from [YOLOv5 latest releases](https://github.com/ultralytics/yolov5/releases), we will proceed to train our model.
What dataset it is? Adding a sample would be good

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights '' --cfg yolov5s.yaml --cache
Explain these arguments

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +python val.py --weights yolov5x.pt --data coco.yaml --img 640 --iou 0.65 --half
Explain arguments

2021-11-29 14:43 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +
Do we have the full code in the GitHub URL that you'd specified earlier?

Add colab notebook or notebook with all the code snippets executed.

2021-11-30 20:00 UTC, FREDERICO23 commented
@srishilesh I've done the requested changes

2021-12-01 17:25 UTC, hectorkambow commented
@srishilesh 

Thank you for the great feedback - lets take a look at the recent changes provided. 

IF any other revisions are needed - lets provide some guidance on how to get the article up to par - and CLOSE the PR. To allow the author the proper time to make any and all needed corrections. 

This is a duplicate PR - if any more changes were needed (in general) we should close the PR immediately especially if its a duplicate PR (generally there are always exceptions). 


cc @section-engineering-education/peer-reviewers

2021-12-03 13:53 UTC, srishilesh requested changes
@FREDERICO23 

Thanks for the changes. 

I found a duplicate index file `content/articles/index.md`. Not sure, on while file you had made the changes.

I've suggested a few other changes as well.

I believe you're trying to discuss both about using pre-trained YOLO models for object detection, and training custom datasets with YOLO. Since, the overall idea looks chaotic, without clearly stating what we are trying to do or why we're doing it, there has been so many revisions to your article.

I had to re-read this article (especially the code parts) several times, to clearly understand what you were trying to say, since you're jumping between ideas, without stating what idea you were in.

Btw, the introduction and other stuff looks good to me.

Also, in the GitHub URL, I found codes only related to testing the pre-trained YOLO models, but not training or testing the custom datasets. It would be great, if you add them too.

Ping me when the changes are done.

Hope you learn from this and improve on your future articles.

Thanks.

cc. @hectorkambow Let's keep this duplicate PR open. Hopefully, on making the requested changes, it'll become more polished and ready for publishing.

2021-12-03 13:53 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +Since the COCO dataset is automatically downloaded from [YOLOv5 latest releases](https://github.com/ultralytics/yolov5/releases), we will proceed to train our model.
Do you mean to download the entire source code? Or any particular file in the release?

2021-12-03 13:53 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights '' --cfg yolov5s.yaml --cache
Where do we get coco128.yaml from?

Also, as you had mentioned YOLO is a pre-trained model. What are we training here again? Is it some custom dataset? If so, specify the URLs for the custom dataset.

I found a dataset in Kaggle - https://www.kaggle.com/ultralytics/coco128

Are you referring to this?

2021-12-03 13:53 UTC, srishilesh commented on content/articles/object-detection-with-yolov5-and-pytorch/index.md
> +```
Why don't we have these snippets in your GitHub URL?

Also, the training snippets?

2021-12-03 15:04 UTC, FREDERICO23 commented
@srishilesh Hello, concerning the 2 `index.md` files, I realized I messed up with the commits. I will make the requested changes and open a new PR just to avoid git headaches. For now, I'll close this PR

cc @hectorkambow

2021-12-03 15:04 UTC, closed without merging