Statefull vs stateless architectures
section-engineering-education/engineering-education pull request #5284
Opened 2021-11-29 10:59 UTC by Su-sid

### Article checklist

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #2966

2021-11-29 11:01 UTC, Su-sid commented
@Dawe-7 kindly continue on with the review.

2021-11-29 20:08 UTC, Dawe-7 commented
@Su-sid, someone else from the team will be handling your article.

2021-11-30 04:50 UTC, WanjaMIKE commented
@EKahuha could you review this article. Thanks

2021-11-30 06:46 UTC, EKahuha commented
@Su-sid I will be reviewing this article.

2021-11-30 13:25 UTC, lin-chez commented
It will be my pleasure @EKahuha

2021-11-30 13:26 UTC, lin-chez commented
It will be a pleasure @EKahuha

2021-11-30 13:30 UTC, Su-sid commented
thanks for the confirmation @EKahuha  it will be a pleasure.

2021-12-01 08:52 UTC, EKahuha requested changes

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +### What Are Stateful And Stateless Architectures
"and" should be lowercase

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +These are the architectural frameworks that define how users interact with services on the internet. Stateful architecture-based services maintain track of clients records or sessions and apply diffe
These are the architectural frameworks...Delete article 'the'

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +In a stateless build system, extra information is  held on the client-side. Thus, as the system conveys different information, each session'reminds' the server of its preceeding sessions through the
'Cookies' should be lowercase

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +### Examples
Restructure these subheadings to:  Examples of Stateless Protocols 
                                                          Examples of Stateful protocols

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +### API-based Internet Services and their Relation to Stateful and Stateless Architectures
API-Based

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +The move to switch from a statefuk designed system to a stteless alternative is linked to the popularity of the diverse ways of building application programming interfaces (APIs) and web apps. At the
Do you mean 'statefuk' or 'stateful'?
 'stteless' or 'stateless' 
'develooed' or 'developed'

..... was a prevalent design pattern....

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +RESTful services developed in popularity as a result of its stateless design, eventually surpassing SOAP in usage. In the design world, Graph QL is gaining traction. RESTful services, like Graph QL-b
'e nd-users' or 'end-users'?

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +### Differences Between Atateless and Atateful Architectures
Atateless and Atateful?

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +The main difference between the two architectures is how they handle user states and sessions. The differences between the two areas are highlighted in the table below:
The main differences between the two architectures relate to how they handle user states and sessions. These differences are highlighted in the table below.

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +Rely on clients to store session state information using cookies and local storage.|Rely on servers to store session state information.
Relies

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +The server handles requests much faster as it does not need to look beyond the single request sent to it as the request contains all the information the server needs to handle it.|The server handles
Break this sentence 'The server handles requests much faster as it does not need to look beyond the single request sent to it as the request contains all the information the server needs to handle it., into two sentences.

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +### Advantages Stateless Architecture
Advantages of Stateless Architectures

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +5.	They can easily handle multiple sessions simultaneously since every request is isolated.
They can handle multiple sessions .....

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +### Disadvantages of Stateless Protocols
The Disadvantage of Stateless Protocols. 
You've only provided one disadvantage, so it cannot be disadvantages. 

Also this 'Advantages of Stateful Architecture'

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +1.	Stateful architecture may add a security advantage to systems. That is why many banks rely on it to allow users to make online transactions. Its disadvantages, however, outweigh its benefits.
A stateful

2021-12-01 08:52 UTC, EKahuha commented on content/articles/statefull-vs-stateless-architectures/index.md
> +Majority of present systmes are designed using a stateless design. The statelsss design gained popularity from the server focused statefull way where clients were passive interfaces dependent on serv
The sentences in this paragraph are very long. Shorten them for ease of readability.

2021-12-01 08:57 UTC, EKahuha commented
Great article @Su-sid. 
There is an error in your article title. Use the correct spelling of stateful. 
Kindly ensure to proofread your article or use a grammar editor like Grammarly. 
Implement the suggested changes so that we can move on to tech review.

2021-12-01 10:27 UTC, Su-sid reviewed
All changes have been observed and implemented. Kindly continue on with the revision process @EKahuha

2021-12-01 10:34 UTC, EKahuha commented
Also, correct the spelling of 'stateful' on your article and image paths.

2021-12-01 10:46 UTC, Su-sid commented
Changes completed. Any other area that needs my attention?

2021-12-01 10:53 UTC, EKahuha commented
> Also, correct the spelling of 'stateful' on your article and image paths.

content/articles/**statefull**-vs-stateless-architectures/index.md
content/articles/**statefull**-vs-stateless-architectures/hero.png

2021-12-01 11:02 UTC, Su-sid commented
Done

2021-12-03 21:35 UTC, hectorkambow commented
@Su-sid 
Please be sure you are going over the entire article as our peer reviewers are not responsible to point out every mistake - that is the authors responsibility.

cc @EKahuha

2021-12-03 21:42 UTC, hectorkambow commented
@EKahuha 

FYI your review is too extensive - we should not be fixing the articles for the authors - our peer reviewer team is here  to review not revise. 

A PR of this quality should be close to allow the author the proper time to look over their work.

2021-12-04 16:42 UTC, Su-sid commented
@EKahuha minor changes have been made to the pr. Kindly approve them for the article to continue on to its final stages. Kindly add your information to the `Peer Review Contributions` section.

2021-12-05 09:58 UTC, EKahuha commented
@Su-sid I am waiting for a plagiarism check so that we can move to final review.

2021-12-06 05:09 UTC, Su-sid commented
Kindly, can you do a plagiarism check on this PR?  @WanjaMIKE ,@Kayere or @LinusMuema

2021-12-07 16:03 UTC, Kayere commented
Plagiarism check done.

2021-12-07 19:54 UTC, WanjaMIKE commented
@EKahuha can I add the `ready for final review label`?

2021-12-08 06:54 UTC, EKahuha requested changes
@Su-sid 
I have reviewed your article's first paragraph, and I can still find grammatical errors. Run your article through Grammarly editor and proofread it thoroughly.

2021-12-08 06:56 UTC, EKahuha commented on content/articles/stateful-vs-stateless-architectures/index.md
> +When developing applications and services, developers consider several factors to ensure their applications run in the most optimum way. Factors such as the scalability of the application/service, th
optimal way
hardware needs

2021-12-08 06:58 UTC, EKahuha commented
> @EKahuha can I add the `ready for final review label`?

Not yet @WanjaMIKE

2021-12-08 16:57 UTC, Su-sid reviewed
.

2021-12-10 05:27 UTC, EKahuha commented
@Su-sid  I sent you a messsage on slack

2021-12-13 07:58 UTC, EKahuha commented
This is ready for final review @WanjaMIKE

2021-12-13 19:25 UTC, WanjaMIKE commented
Nice test review @EKahuha

2021-12-13 20:10 UTC, WanjaMIKE commented
Merged #5284 into master

2021-12-13 20:11 UTC, merged