Getting started with multi task learning (mtl) in deep neural networks
section-engineering-education/engineering-education pull request #5295
Opened 2021-11-30 09:53 UTC by puritymutunga

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4734

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-11-30 09:54 UTC, puritymutunga commented
@mbaabuones 
This is the new PR.
Duplicate of #5123

2021-12-01 14:21 UTC, mbaabuones requested changes
@puritymutunga Thank you for submitting your article. The quality of this article has been enhanced. Note the changes that I have made. Please make the highlighted minor changes. Ping me when you are done.

2021-12-01 14:21 UTC, mbaabuones commented on content/articles/getting-started-with-multi-task-learning-(mtl)-in-deep-neural-networks/index.md
> +The group-sparsity constraint limits our model to examine only a few features, although these features are used extensively in all tasks. In other words, all of the above theories presuppose that mul
Revise this section to enhance ease of understanding

2021-12-01 14:21 UTC, mbaabuones commented on content/articles/getting-started-with-multi-task-learning-(mtl)-in-deep-neural-networks/index.md
> +In several machine learning applications, such as natural language processing, speech recognition, and computer vision, multi-task learning has proven successful. We've covered the basics of MTL in a
Revise this section as follows:
In this article, we have looked at how you can get started with multi-task learning in deep neural networks. To summarize:
1. We have gained an overview of multi-task learning.
2. We have learned the MTL methods for deep learning. 

use this example to re-write your conclusion.

2021-12-04 02:08 UTC, puritymutunga commented
Hi  @mbaabuones  I have done the requested changes

2021-12-04 15:04 UTC, mbaabuones approved these changes

2021-12-08 15:31 UTC, Kayere commented
Hello @puritymutunga

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[[Duplicate of #5123]_ Getting Started with Multi Task Learning (MTL) in Deep Neural Networks #5295 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7677073/Duplicate.of.5123._.Getting.Started.with.Multi.Task.Learning.MTL.in.Deep.Neural.Networks.5295.Copyleaks.Report.pdf)

2021-12-09 03:01 UTC, puritymutunga commented
Hi @mbaabuones I have made changes to the article after the plagiarism check was done.

2021-12-18 12:54 UTC, louisefindlay23 commented
@puritymutunga, please remove the brackets from your branch name and this conflicts with Git.

2021-12-18 17:20 UTC, closed without merging