Understanding the Resilient Packet Ring Technology
section-engineering-education/engineering-education pull request #5302
Opened 2021-11-30 18:11 UTC by eunice-wanjiku

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-01 15:21 UTC, mbaabuones requested changes
@eunice-wanjiku Nice article. Although the article is informative, there is room for improvement.
 - The content of the article (minus the table of contents and resources) is less than the threshold size- 750 words. Add content to reach at least 750 words. 
- I have also noticed that you have only one paragraph in every section. To make your article unique and more appealing, every section should consist of at least two paragraphs. If possible, some of the sections can be sub-divided into sub-sections. 
- There are many good articles that have described the basics of phenomena. Take time to go through them to see how they have been crafted. Here are two good examples: one on [means end analysis](https://www.section.io/engineering-education/basics-of-means-end-analysis-in-ai/) and another on [production system in AI](https://www.section.io/engineering-education/breaking-down-the-production-system-in-ai/).
- Your article has some grammatical errors. After making the suggested changes, use Grammarly.com to identify and correct grammatical errors. 
- Other changes have been suggested in the article. Ping me when you finish all the revisions.

2021-12-01 15:21 UTC, mbaabuones commented on content/articles/understanding-the-resilient-packet-ring-technology/index.md
> +The traffic present is associated with Class of Service, which is categorized into classes A, B, and C. They signify high, medium, and low traffic simultaneously. Class A is a virtual circuit bandwid
How is this section connected with the topic of your article? Give further explanations to connect it with the topic of the article. If it is a sub-section, then you should use a level four header.

2021-12-01 15:21 UTC, mbaabuones commented on content/articles/understanding-the-resilient-packet-ring-technology/index.md
> +RPR is commonly used in national SONET, metropolitan, and ethernet carrier networks. This architecture is normally incorporated into the SONET networks so that they can gain the ability to transfer p
If possible, this section can be sub-divided into sub-sections.

2021-12-01 18:18 UTC, eunice-wanjiku commented
@mbaabuones all done

2021-12-03 14:51 UTC, mbaabuones commented
> @mbaabuones all done

@eunice-wanjiku Thank you for revising your article. However, I am still concerned that the content of your article is thin. The sections 'adopted types of transmission data', 'applications' and 'limitations' can still be expanded to add value to your article. If you decide to use sub-sections, make sure there are at least two subsections in every section. You can provide a leading statement before branching to your sub-sections. For example, in the section 'applications', you can provide a statement that highlights the main applications. After this statement, you can list them in sub-sections to give further explanations. This can also be applied in the section 'adopted types of transmission data'. Please refer to the two articles I suggested to you. Please work on these changes.

2021-12-03 18:05 UTC, eunice-wanjiku commented
@mbaabuones Check the changes made. I believe this is what you were going for?

2021-12-04 06:33 UTC, mbaabuones commented
> @mbaabuones Check the changes made. I believe this is what you were going for?

@eunice-wanjiku Yes. Just a minor issue. The section after 'the basics of RPT' has a level four header. Based on the new structure, this section fits to have a level three header. Change this and ensure there are at least two paragraphs in this section. There should be only one space between paragraphs. In some cases, there are two or more spaces. Remove the extra spaces.

2021-12-05 10:27 UTC, eunice-wanjiku commented
@mbaabuones Confirm the changes

2021-12-07 11:46 UTC, mbaabuones approved these changes

2021-12-08 15:33 UTC, Kayere commented
Plagiarism check done.

2021-12-18 13:00 UTC, merged