Build A Weather Forecast App With Next Js
section-engineering-education/engineering-education pull request #5335
Opened 2021-12-01 21:52 UTC by oyedeletemitope

### Article checklist

#### Pre-submission checks
> I am submitting the article linked with the issue I opened which is 'building a weather forecast app with next js'

> 
#### Formatting and structure checks
I made sure I followed every instruction by including my picture and a little about myself. 
included in the article are two links to my GitHub repo, the first is for the frontend which users will use to build this project while the second is for the finished project.
-[ ] the article was written in markdown
-[ ] I wrote over 750 words
-[ ] The article is well detailed as I gave an explanation for every code I wrote. I also introduced Next js before going into the project
- [ ]the article was written for those who have knowledge of React and want to learn Next js
- [ ] I used the correct folder structure

      
#### Grammar & plagiarism checks
-[ ] i ensured my article was spellchecker using Grammarly
- [ ] had a high percentage of uniqueness

#### Technical checks
-[ ] I ensured my codes were running properly
- [ ] i ensured my programs and packages were up to date 

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4754

2021-12-05 07:54 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing. 
With the recent increase in article volume out team has been working diligently to review every article. Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2021-12-08 06:18 UTC, srishilesh requested changes
@oyedeletemitope 

Welcome to EngEd program!

I've suggested some minor changes related to markdown formatting. Please go through them.

On a quick note:
- Start markdown headers from `###`, and for sub-topics use `####`.
- The image path looks incorrect.
- Code snippets needs to be formatted (indentation and remove extra new lines)
- Avoid full capitalization of words
- Avoid using "I"

Let me know when the changes are done.

Thanks.

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +The API we’ll be using for this tutorial is openweather API but to do that we’ll have to sign up with them to be able to make use of their API.
Add link to the API

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +- fetch an external API in next
Inconsistency in upper case and lower case of first letters

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +### OVERVIEW
Make it in lowercase

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +## What is Next js?
You can make it Next.js or NextJS.

No spaces.

Do this change throughout the article.

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +## What is Next js?
Use `###`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +## Why should you use it?
`###`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +- Rendering on the Server (SSR)
Instead of `-` use `####`.

Do the same for other sub topics as well

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +- Improved Search Engine Optimization
`####`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +- Enhanced performance
`####`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +- Static Site Generation
`####`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +## Comparing Next.js with React
`###`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +
Avoid additional spaces and new lines

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +Since Next.js is a React framework then why compare it with its library? Well, as developers we tend to favor a library or framework over the other depending on taste. I’m sure React fans take Next.j
Try replace "I" with "we" throughout the article.

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +Create React App is a wonderful approach to learning React if you're just starting started with it. If you want to utilize React to create a Single Page Application, the CRA will offer you a head sta
Add reference links for SPA.

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +Because Create React App simply creates the front-end assembly, you can use it with any server you choose, including Node. You should also be aware that CRA employs Babel and Webpack behind the scene
Links for babel and webpack

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +### Speed of coding
`####`

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +![api_key](build-a-weather-forecast-app-with-next-js/api_key.PNG)
The image path is incorrect. Please refer the guidelines or have a look at other files.

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +![front-end.PNG](build-a-weather-forecast-app-with-next-js/front-end.PNG)
Image path incorrect. Do this change for all the images.

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +        return setResults(matchingCities);
Remove additional new lines. And, indent the codes properly

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +### DISPLAYING OUR MATCHING CITIES:
Lowercase

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +### DISPLAYING TODAY’S WEATHER
Lowercase

2021-12-08 06:18 UTC, srishilesh commented on content/articles/build-a-weather-forecast-app-with-next-js/index.md
> +<span>
Code formatting needs to be done

2021-12-08 16:40 UTC, Kayere commented
Hello @oyedeletemitope

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Build A Weather Forecast App With Next Js #5335 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7677542/Build.A.Weather.Forecast.App.With.Next.Js.5335.Copyleaks.Report.pdf)

2021-12-09 04:13 UTC, oyedeletemitope commented
Thanks. I'll revisit and make changes asap

2021-12-09 17:56 UTC, srishilesh commented
@oyedeletemitope 

To allow you to make changes, let's close this PR for now.

You can reopen a new PR with all the changes made, such that your article is ready to be published. Make sure to perform a grammarly check, and refer other articles to see if you have missed out anything in formatting.

You can ping me in the new PR once created.

2021-12-09 17:56 UTC, closed without merging