Python Metaclasses for Metaprogramming
section-engineering-education/engineering-education pull request #5345
Opened 2021-12-02 13:08 UTC by Dick7603

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #4692 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-10 11:34 UTC, Kayere commented
Hello @Dick7603,

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Python Metaclasses for Metaprogramming #5345 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7692354/Python.Metaclasses.for.Metaprogramming.5345.Copyleaks.Report.pdf)

2021-12-12 19:05 UTC, jerimkaura requested changes

2021-12-12 19:05 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +- It is possible to hook on `new`, `init`, and `call` hooks. So you may do other things, as a result.
Explain these reasons in detail. The one-line statements provided are not clear enough.

2021-12-12 19:05 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +- If the user is a developer of application programming interfaces.
Elaborate on these to add more value.

2021-12-12 19:05 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +```
Explain the code snippet here well. Tell the user what it does and how it does it.

2021-12-12 19:07 UTC, jerimkaura requested changes
Hello @Dick7603 

You have an amazing article here. However, please go over the article to work on the changes highlighted and to ensure readability. You need to ensure every article is clear to the readers. 

Work on the changes then ping me here or via slack.

2021-12-19 19:18 UTC, jerimkaura commented
Hello @Dick7603 

Please work on all the changes so that I can proceed with the review. The commit did not take in all the suggested changes.

2021-12-19 19:19 UTC, jerimkaura requested changes
Hello @Dick7603 

Please work on all the changes so that I can proceed with the review. The commit did not take in all the suggested changes.

2021-12-21 19:22 UTC, jerimkaura approved these changes
Hello @Dick7603 

Great piece here :rocket: Take note of the changes for better articles in the future. Great Work!

2021-12-22 11:33 UTC, WanjaMIKE commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +Metaclasses are classes whose instances are other classes used to build objects. Metaclasses can be created by modifying how classes are instantiated.
This statement appears unclear. Could you rephrase it.

2021-12-22 11:34 UTC, WanjaMIKE commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +A class is an instance of metaclass since it is an object in Python. Therefore, various class types can be found via the metaclass. This, therefore, establishes new classes and class objects. For ins
Rephrase this paragraph

2021-12-22 11:35 UTC, WanjaMIKE commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +The general public seldom utilizes metaclasses since they are primarily employed in complex scenarios. However, metaclasses may be used in the following limited number of situations:
Replace `the general public` with developers to be more specific.

2021-12-22 11:36 UTC, WanjaMIKE commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +The preceding example shows that the type may be sent in as a single parameter. It may be called with three different arguments by the user. Creating the class will be done by this. Some of the argum
This statement is unclear `Creating the class will be done by this?`

2021-12-22 20:54 UTC, Dick7603 commented
hello @WanjaMIKE, I have implemented the changes your requested please check

2021-12-23 06:46 UTC, WanjaMIKE commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +A metaclass in Python is a class of a class that defines how a class behaves. A class is itself an instance of a metaclass. A class in Python defines how the instance of the class will behave.
You copied this content directly from https://www.datacamp.com/community/tutorials/python-metaclasses

![copycat](https://user-images.githubusercontent.com/38399942/147200011-106e6622-c375-49a9-839b-34d83f325f73.png)

2021-12-23 06:48 UTC, WanjaMIKE commented
I am closing this PR because it seems it wasn't publish-ready. You can make the changes outside the queue and create a new duplicate PR.

2021-12-23 06:48 UTC, closed without merging