Animations in Jetpack Compose [duplicate of #5316]
section-engineering-education/engineering-education pull request #5357
Opened 2021-12-03 05:40 UTC by Janenjoki

### Article checklist

#### Pre-submission checks

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3571

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-03 05:41 UTC, Janenjoki commented
Hello @Ericgacoki, I have opened a new PR. Please take a look. Thanks!

2021-12-03 21:36 UTC, hectorkambow commented
@Ericgacoki 

Duplicate articles only need a new plagiarism check if the content added is major. 

If its just a few formatting issue - then it may not be needed. 

I'll let you make the call since you are familiar with the changes that were asked.

2021-12-03 21:37 UTC, hectorkambow commented
@Ericgacoki 
If any more major revisions are needed - we will be closing this PR asap. 👀

@Janenjoki 
Please be sure you are going over the entire article for any other mistakes or errors, as our peer reviewers are not responsible to point out every mistake - that is the authors responsibility to properly review and proofread their work.

2021-12-03 22:16 UTC, Ericgacoki commented
@hectorkambow
The previous PR was closed due to a bulk file deletion. Plagiarism check `wasn't done` and I `hadn't requested` any changes yet.

2021-12-03 22:17 UTC, hectorkambow commented
> @hectorkambow
> 
> The previous PR was closed due to a bulk file deletion. Plagiarism check `wasn't done` and I `hadn't requested` any changes yet.

Understood good call

2021-12-10 11:44 UTC, Kayere commented
Plagiarism check done.

2021-12-19 07:29 UTC, Ericgacoki requested changes
Hey @Janenjoki, well done on this one. I can see a great improvement from your previous article(s). Kindly work on the following areas and ping me when you're done!

2021-12-19 07:29 UTC, Ericgacoki commented on content/articles/animations-in-jetpack-compose/index.md
> +
Use `####` for such headings instead.

2021-12-19 07:29 UTC, Ericgacoki commented on content/articles/animations-in-jetpack-compose/index.md
> +            Text(text = "Animate")
Seems like you're missing a button here 🥴...check and fix that.

2021-12-19 07:29 UTC, Ericgacoki commented on content/articles/animations-in-jetpack-compose/index.md
> +                    Text(text = "")
Consider using `myState` instead of `myStte`.

2021-12-19 07:29 UTC, Ericgacoki commented on content/articles/animations-in-jetpack-compose/index.md
> +            ) {
This Box needs a Modifier to specify its height and such properties.

2021-12-19 08:51 UTC, Janenjoki commented
Hello @Ericgacoki, I've updated the article as per your suggestions.

2021-12-21 16:14 UTC, Ericgacoki approved these changes

2021-12-23 15:03 UTC, LinusMuema commented
Hi @Janenjoki 

Awesome read. Quite helpful as I am also working with compose. 
Keep at it.

cc: @Ericgacoki

2021-12-23 15:04 UTC, merged