Building and run unikernels with ops
section-engineering-education/engineering-education pull request #5361
Opened 2021-12-03 08:26 UTC by Gladysoby

### Article checklist

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

`This closes #4390`

2021-12-03 08:38 UTC, Gladysoby commented
@jumamiller this the article update.
have a look at it.
Thank you.

2021-12-05 08:09 UTC, ahmadmardeni1 commented
Please use the [new author template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md).

2021-12-05 13:53 UTC, jumamiller commented on content/articles/building-and-run-unikernel-with-ops/index.md
> +
Work on these spacing, remove them!

2021-12-05 13:53 UTC, jumamiller commented on content/articles/building-and-run-unikernel-with-ops/index.md
> +Unikernels hаve lоng  been hаiled аs the next рhаse оf сlоud struсture due tо their length, seсurity, аnd рerfоrmаnсe, аllоwing megаtrends like miсrоserviсes аnd serverless tо рersist desрite the nev
This sentence is very long and hard to read! Breakdown into paragraphs!

2021-12-05 13:54 UTC, jumamiller requested changes
You have very long sentences, kindly break them down!

2021-12-08 00:32 UTC, hectorkambow commented
@Gladysoby 
Good afternoon and thank you for submitting your topic to the EngEd program.  It seems this PR is still quite a bit aways from being completed. 

>As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published.  All revisions and edits should be completed on your own forked repo (as to not build up a backlog in the queue). 

I'm seeing this is a duplicate pull request (#4857) (all pull request are looked at a case by case basis - but generally), any duplicate pull request should NOT require additional revisions - as they should have been caught by the author before re-submitting. 

We will be closing this for now. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 

👍 
 
cc @jumamiller

2021-12-08 00:32 UTC, closed without merging