Introduction to Kernel Methods in Machine Learning
section-engineering-education/engineering-education pull request #5365
Opened 2021-12-03 09:46 UTC by Brian3811

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-03 09:48 UTC, Brian3811 commented
This closes #4567

2021-12-03 14:11 UTC, Brian3811 commented
Hello @paulodhiambo this is an update of PR #5309

2021-12-06 14:27 UTC, paulodhiambo requested changes
@Brian3811 make the requested changes then I'll proceed with the tech review

2021-12-06 14:27 UTC, paulodhiambo commented on content/articles/introduction-to-kernel-methods-in-machine-learning/Index.md
> +- The reader should be able to understand basic terms like Support Vector Machine, classifications, unsupervised learning and supervised learning.
reword to "- The reader should understand basic terms like Support Vector Machine, classifications, unsupervised learning, and supervised learning."

2021-12-06 14:27 UTC, paulodhiambo commented on content/articles/introduction-to-kernel-methods-in-machine-learning/Index.md
> +The assumed model for the likelihood, however, may not be correct; the "actual" distribution may be skewed, multimodal, with different components, and so on. In general, the scientist analyzing the d
reword to "However, the assumed model for the likelihood may not be correct; the "actual" distribution may be skewed, multimodal, with different components, and so on. In general, the scientist analyzing the data is unaware of this. This article aims to demonstrate the fundamental concepts underlying kernels and their applications in statistics and machine learning."

2021-12-06 14:27 UTC, paulodhiambo commented on content/articles/introduction-to-kernel-methods-in-machine-learning/Index.md
> +Kernels, <span style="color:blue">also known as kernel techniques or kernel functions, are a collection of distinct forms of pattern analysis algorithms.</span> Using a linear classifier, they are ut
be consistent, either use non-linear or nonlinear throughout the article.

2021-12-06 15:52 UTC, Brian3811 commented
Hello @paulodhiambo the requested changes are in place

2021-12-08 00:26 UTC, hectorkambow commented
@Brian3811 lets be sure to go through the entire article to catch any issues that may have not been caught by our peer reviewer. 

>Our Peer Reviewer and Content Moderator teams do NOT provide any revisions services. All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner.
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

cc @paulodhiambo be sure to keep this mind as we go through the changes and tech review 👍

2021-12-08 17:49 UTC, paulodhiambo commented on content/articles/introduction-to-kernel-methods-in-machine-learning/Index.md
> +by KSC.
Format this section to make the equation readable.

2021-12-10 12:22 UTC, Kayere commented
Hello @Brian3811,

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Introduction to Kernel Methods in Machine Learning #5365 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7692635/Introduction.to.Kernel.Methods.in.Machine.Learning.5365.Copyleaks.Report.pdf)

2021-12-10 12:22 UTC, closed without merging