How to set up Svelte with vite, TypeScript and Tailwind CSS
section-engineering-education/engineering-education pull request #5396
Opened 2021-12-04 15:56 UTC by Joakim-gakure

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-05 07:54 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing. 
With the recent increase in article volume out team has been working diligently to review every article. Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2021-12-08 02:25 UTC, Jethro-magaji commented
@ahmadmardeni1 I would like to review this one.

2021-12-08 16:33 UTC, ahmadmardeni1 commented
Go ahead @Jethro-magaji

2021-12-10 12:45 UTC, Kayere commented
Hello @Joakim-gakure,

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[How to set up Svelte with vite, TypeScript and Tailwind CSS #5396 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7692737/How.to.set.up.Svelte.with.vite.TypeScript.and.Tailwind.CSS.5396.Copyleaks.Report.pdf)

2021-12-11 16:11 UTC, Jethro-magaji reviewed
Hello @Joakim-gakure 
Well done for coming up with such a wonderful article. However, there're so many grammatical errors, I highly suggest using tools like Grammarly and ProWriterAid to edit your article.
Add comments inline or below your code for a better explanation.
Use 2nd person pronouns "You" instead of "We".

2021-12-11 16:11 UTC, Jethro-magaji commented on content/articles/svelte-with-vite-typescript-and-tailwind-css/index.md
>  - [Vite guide](https://vitejs.dev/guide/#overview)
These links should be under the heading named "Additional Resources"

2021-12-15 21:49 UTC, Joakim-gakure commented
@Jethro-magaji, I have submitted the changes above

2021-12-15 21:52 UTC, Joakim-gakure commented
> Hello @Joakim-gakure,
> 
>  Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
> 
> Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
> 
> Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [How to set up Svelte with vite, TypeScript and Tailwind CSS #5396 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7692737/How.to.set.up.Svelte.with.vite.TypeScript.and.Tailwind.CSS.5396.Copyleaks.Report.pdf)

@Kayere, I have updated the plagiarism flags, the few remaining % are HTML tags, which I can't change, they are basic boilerplate HTML tags.

2021-12-22 00:40 UTC, Jethro-magaji requested changes
Hi @Joakim-gakure 
I have dropped some reviews for you. Please use Grammarly and ProWritingAid to edit your article as there are still some grammatical errors. Else the next revision will require the closure of this PR.
Thanks.

2021-12-22 00:40 UTC, Jethro-magaji commented on content/articles/svelte-with-vite-typescript-and-tailwind-css/index.md
> +Svelte is a JavaScript front-end framework for building reactive and interactive UI components like React, Angular, and Vue. Svelte is a compiler, unlike its peers, which provides a JavaScript runtim
Rephrase to this for clarity "Svelte is a JavaScript front-end framework for building reactive and interactive UI components like React, Angular, and Vue, it is also a compiler. Unlike other frameworks, which provide a JavaScript runtime to the browser to make your code work, Svelte converts the declarative code that you write into imperative code that works with native browser APIs. This produces high-performance applications with a small codebase, allowing you to write complex applications."

2021-12-22 00:40 UTC, Jethro-magaji commented on content/articles/svelte-with-vite-typescript-and-tailwind-css/index.md
> +This tutorial will build a portfolio application that demonstrates how to utilize Vite, TypeScript, and Tailwind CSS in a Svelte application.
Rephrase to this for clarity "In this tutorial will build a portfolio application that shows how to use Vite, TypeScript, and Tailwind CSS in a Svelte application."

2021-12-22 00:40 UTC, Jethro-magaji commented on content/articles/svelte-with-vite-typescript-and-tailwind-css/index.md
> +Vite is a JavaScript development server tooling that makes front-end development more easier. Vite distributes your app source files through native ES modules, allowing you to quickly start or reload
Rephrase to this - Vite is a JavaScript development server tool that makes front-end development easier.

2021-12-22 00:40 UTC, Jethro-magaji commented on content/articles/svelte-with-vite-typescript-and-tailwind-css/index.md
> +This guide has illustrated how you set up a TypeScript Svelte boilerplate that you can use to write TypeScript code within a Svelte application. We also configured and used TailwindCSS to create a Sv
Please, include links to the GitHub repo and live demo site for a better understanding.

2021-12-30 05:46 UTC, WanjaMIKE commented
Plagiarism check done.

2021-12-31 12:28 UTC, ahmadmardeni1 commented
Can you give me a status update? @Jethro-magaji Is this article ready for a final review?

2022-01-01 03:19 UTC, Jethro-magaji commented
Hi! @ahmadmardeni1
The Author has made the required changes, and I have done my part of the review, please complete the review process by adding front matter and other necessary tags.
Cc @WanjaMIKE
Thanks.

2022-01-04 08:02 UTC, WanjaMIKE commented
Nice work gents @Joakim-gakure @Jethro-magaji

2022-01-04 08:03 UTC, WanjaMIKE commented
Merged #5396 into master

2022-01-04 08:03 UTC, merged

2022-01-05 12:34 UTC, Jethro-magaji commented
I have just finished my final test review.
cc @WanjaMIKE @section-engineering-education/content-moderator-team @ahmadmardeni1 

![Screenshot (868)](https://user-images.githubusercontent.com/53092121/148217765-a8335663-a449-4eca-bb37-b010dc6181d3.png)