DevOps Pipelines Automation with Cloud Build and Triggers
section-engineering-education/engineering-education pull request #5442
Opened 2021-12-07 05:26 UTC by damikanye

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

This closes issue #5258

2021-12-09 18:03 UTC, srishilesh requested changes
@damikanye 

Until we get this PR plagiarism checked, let's work on some minor suggestions.

Make sure to go through each suggestion and address them.

Ping me when done.

Thanks.

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +13. You have some files now, so save them to the repository. First, you need to add all the files you created to your local Git repo. In Cloud Shell, enter the following code:
Change this for other points as well

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +```git
bash

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +```git
bash

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +```
bash

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +![Result of deployment](/devops-pipelines-automation-with-cloud-build-and-triggers/result1.png)
It's incorrect. Please refer previous suggestion

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +```Flask
Change the type of code snippets everywhere. It's incorrect

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +```
dockerfile

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +9. On the Create an instance page, specify the following, and leave the remaining settings as their defaults:
Use `-`

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +
Can we have all the codes in a GitHub repo?

It'll be easy for the readers to refer to.

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +In this tutorial, you built a continuous integration pipeline using the Google Cloud tools Cloud Source Repositories, Cloud Build, build triggers and Container Registry.
Make it more brief.

Add key takeaways and a short summary.

2021-12-09 18:03 UTC, srishilesh commented on articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
> +Happy hacking!
Add additional references if possible.

2021-12-10 12:31 UTC, damikanye commented
Thank you sir @srishilesh. All the minor changes have been rectified.

2021-12-10 13:40 UTC, Kayere commented
Hello @damikanye 

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[DevOps Pipelines Automation with Cloud Build and Triggers #5442 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7693095/DevOps.Pipelines.Automation.with.Cloud.Build.and.Triggers.5442.Copyleaks.Report.pdf)

2021-12-11 08:55 UTC, damikanye commented
@srishilesh done with the revisions sir.

2021-12-14 18:58 UTC, srishilesh commented
I'll complete my tech review by tomorrow.

2021-12-15 17:43 UTC, srishilesh approved these changes
@damikanye 

I've made some major changes to the flow and formatting. Make sure to go through them.

Moving for the final review.

We highly recommend you to take up [this](https://developers.google.com/tech-writing) course by Google on technical writing.

Thanks.

2021-12-15 18:10 UTC, damikanye commented
Thank you @srishilesh. I will go through the recommended course and improve on my next writing.

2021-12-22 09:46 UTC, LinusMuema commented
Hi @damikanye 

Awesome job on the article.

cc: @srishilesh

2021-12-22 09:46 UTC, merged