Building a lyrics search app with vanilla javascript
section-engineering-education/engineering-education pull request #5447
Opened 2021-12-07 14:54 UTC by shegz101

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-07 14:57 UTC, shegz101 commented
@adrianmurage have gone through the article and I can boldly say the code runs now, some lyrics are not returned because they do not exist on the ap

2021-12-07 14:58 UTC, shegz101 commented
> @adrianmurage have gone through the article and I can boldly say the code runs now, some lyrics are not returned because they do not exist on the ap

because they do not exist on the api.

2021-12-07 15:00 UTC, shegz101 commented
> @adrianmurage have gone through the article and I can boldly say the code runs now, some lyrics are not returned because they do not exist on the ap

because they do not exist on the api.

2021-12-07 18:36 UTC, shegz101 commented
@adrianmurage I have fixed the issue of code not running, it now works without error.

2021-12-08 00:03 UTC, hectorkambow commented
Just sharing this past article to make sure that 1) it does not overlap & 2) to see if it can be referenced at all (if it makes sense).

2021-12-08 00:04 UTC, hectorkambow commented
Is this PR a duplicate?

2021-12-08 06:05 UTC, shegz101 commented
@hectorkambow it is not a duplicate because I  changed a lot in it, compared to the last PR.

2021-12-08 06:06 UTC, shegz101 commented
@hectorkambow the last PR was closed.

2021-12-08 17:08 UTC, adrianmurage commented
> Is this PR a duplicate?

Yes @hectorkambow. It duplicates a closed PR with the changes I requested @shegz101 to make on their initial submission.

2021-12-08 17:39 UTC, adrianmurage requested changes
Awesome job @shegz101 

The article reads smoothly and I managed to run it without any problems. Good work indeed!
I have a few more concerns you need to address before we can mark your article as ready for final review. 

Kindly look over them and when you've addressed them kindly @ me

Thank you for your great work. Looking forward to getting your work published

2021-12-08 17:39 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-js/index.md
> +    <script src="script.js">
```suggestion
    <script src="lyrics.js">
```

2021-12-08 17:39 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-js/index.md
> +The `/g` is a regular expression flag, it means globally, the entire document to be searched through(all matches).
you do not have the regular expressions code in the article so it might be a little confusing when you talk about it without a frame of reference

2021-12-08 21:20 UTC, shegz101 commented
@adrianmurage I have made the necessary corrections

2021-12-09 12:47 UTC, adrianmurage commented on content/articles/building-a-lyrics-search-app-with-vanilla-js/index.md
> +The `/g` is a regular expression flag, it means globally, the entire document to be searched through(all matches).
@shegz101 
have you addressed this?

2021-12-09 15:32 UTC, adrianmurage commented
Hey @shegz101    👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

It took a few tries but eventually, we got your article up to par. I am super proud of you for the hard work! 👏 

Just a few things I'd like to point out:
- I suggest that you check out our resources page which has links to various resourceful tools for writing just to minimize the changes being made by the reviewer.
- Lastly, note all the corrections we have made so that you can not repeat the same mistakes.

That's it! :smile: 

Once I finalize my part of the review, a final review will be done by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via Slack or my personal email (adrianmurage21@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Once again good job! 👍 

Kind Regards.

2021-12-10 00:38 UTC, shegz101 commented
@adrianmurage am so happy it is finally coming to life, you have been of great help to me in this journey and am super grateful, I have noted all corrections made and looking forward to write better articles for section which won't be full of errors. I wish you could just be the one reviewing more of my articles.

2021-12-10 00:39 UTC, shegz101 commented
@adrianmurage it is a pleasure connecting with a great reviewer like you, thanks once again.

2021-12-10 08:27 UTC, adrianmurage commented
> @adrianmurage am so happy it is finally coming to life, you have been of great help to me in this journey and am super grateful, I have noted all corrections made and looking forward to write better articles for section which won't be full of errors. I wish you could just be the one reviewing more of my articles.

I am glad I was able to have such a positive impact on your experience and I look forward to seeing more of your work! I assure you that the peer reviewer team is full of amazing reviewers who you will like just as much 😄

2021-12-10 08:39 UTC, shegz101 commented
@adrianmurage yes I look forward to connecting with other peer reviewers, I know it would be an amazing experience, still planning to see if I can still write one more article before the year runs out, more great articles next year by God's grace.

2021-12-10 08:43 UTC, shegz101 commented
So I should be looking at the article getting published before the end of this week, early next week.

2021-12-12 17:27 UTC, shegz101 commented
@adrianmurage I sent you a message on slack

2021-12-20 22:19 UTC, hectorkambow commented
jumping on this one

2021-12-20 23:02 UTC, hectorkambow commented
I started a final review and made some other changes - still noticing a few errors throughout the article. 
Most grammatical - please be sure to go through our resources page to get more tips, guides, and resources on [how to improve overall technical writing](https://developers.google.com/tech-writing/overview).  

We will be closing this pull request. 

Thank you. 

cc @adrianmurage  there were some errors that were noticed during the final review, and some sentences that were a bit difficult to read through.

2021-12-20 23:02 UTC, closed without merging

2021-12-21 08:56 UTC, shegz101 commented
@hectorkambow the PR and issue are both closed, does that mean when I feel am good enough, I should open a fresh issue, just want to know the next line of action

2021-12-21 08:57 UTC, shegz101 commented
@hectorkambow can you please point out example of the errors

2021-12-21 12:39 UTC, shegz101 commented
@hectorkambow can you just suggest the necessary changes please, have been on this for so long only for it to be totally closed and for me to start afresh

2021-12-21 12:42 UTC, shegz101 commented
@adrianmurage please what is next, do I have to go through suggesting topic ,and when it is approved rewrite this article, @hectorkambow have started going through the resources you sent, please let me know what is expected of me

2021-12-21 21:36 UTC, shegz101 commented
@hectorkambow please can you reopen it, I just finished going through the resources you sent me, please give me a chance to make corrections

2021-12-21 21:38 UTC, hectorkambow commented
Left a message via slack

2021-12-21 21:38 UTC, hectorkambow commented
> @hectorkambow can you just suggest the necessary changes please, have been on this for so long only for it to be totally closed and for me to start afresh

Our team does not provide revision services - and I believe the reviewers were going an extra step by providing some highlights before.
Please do go through our resources for extra help :rocket:

2021-12-21 21:39 UTC, hectorkambow commented
We can not pin point every single change that is required. 

That would not be fair to the students who are submitting proofread content.

2021-12-21 21:41 UTC, shegz101 commented
OK but am free to start the process afresh, by opening a new issue