Building web application with Kotlin and Typescript
section-engineering-education/engineering-education pull request #5466
Opened 2021-12-08 13:54 UTC by 07BLAIZER

### Article checklist

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #4920 `

2021-12-09 07:47 UTC, ahmadmardeni1 commented
Good afternoon and thank you for submitting your article for publishing.
With the recent increase in article volume out team has been working diligently to review every article. Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2021-12-13 16:55 UTC, 07BLAIZER commented
@ahmadmardeni1  hello 👋
Its been 5 days and no peer reviewer has been assigned on this.
Thanks ☺️

2021-12-13 22:04 UTC, paulodhiambo commented
@ahmadmardeni1 @07BLAIZER picking up this.

2021-12-13 22:15 UTC, paulodhiambo requested changes
@07BLAIZER amazing article, make the suggested changes as I proceed with the tech review.

2021-12-13 22:15 UTC, paulodhiambo commented on content/articles/building-web-application-with-kotlin-and-typescript/index.md
> +Integration of Kotlin generated modules with Typescript web browser application has been well illustrated in this article. It requires build script codes which are simplified by the use Gradle plugin
Simplify "It requires build script codes which are simplified by the use Gradle plugin..." to "It requires build script codes simplified by the Gradle plugin…".
It should be "multiplatform" not "multiplartform"

2021-12-13 22:15 UTC, paulodhiambo commented on content/articles/building-web-application-with-kotlin-and-typescript/index.md
> +The nodeKotlin dependencies require to be resolved and artifacts that contain the JavaScript codes should be unpacked to the node_modules directory.
rephrase to "The nodeKotlin dependencies require resolving, and we should unpack artifacts containing the JavaScript codes to the node_modules directory."

2021-12-13 22:15 UTC, paulodhiambo commented on content/articles/building-web-application-with-kotlin-and-typescript/index.md
> +import statement on the second time is not much important it also develops a good alias for the content of the modules which helps to reduce more writing of fully qualified names all the time we use
refrase to "Import statement on the second time is not much important. It also develops a good alias for the content of the modules, which helps to reduce more writing of fully qualified names all the time we use Kotlin generated modules."

2021-12-15 17:04 UTC, lalith1403 commented
The plagiarism percentage is way greater than what we typically accept. I will be closing this PR for now. Feel free to make the changes outside of the queue and submit a new PR. 

[Uploading Building web application with Kotlin and Typescript #5466.pdf…]()

2021-12-15 17:04 UTC, closed without merging