commit
section-engineering-education/engineering-education pull request #5476
Opened 2021-12-09 02:47 UTC by del-ui

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4585 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-09 02:54 UTC, del-ui commented
@Jethro-magaji I have done some refinement on this article to enhance readability as directed earlier

2021-12-09 03:32 UTC, Jethro-magaji commented
> @Jethro-magaji I have done some refinement on this article to enhance readability as directed earlier

Please take your time to make serious edits on your article and don't rush to submit. Because your PR was closed twice due to quality and this is the third time i will be making a review on your article, which takes time from your reviewer. 
I highly recommend you get a good editor to edit your article before submitting. However, if you're sure that the current PR is good to go, then i can proceed with the review but note that it would be closed if all doesn't go well.
Thanks.

Cc @WanjaMIKE  @hectorkambow

2021-12-09 07:52 UTC, ahmadmardeni1 commented
This is the last round of revision @Jethro-magaji If the article is not ready then please close it and the author can submit a new topic after going through our docs.
Our team does NOT provide editing services. @del-ui Thank you.

2021-12-10 22:11 UTC, Jethro-magaji requested changes
Hi @del-ui 
I still think your article has more work to be done, I suggest running your article on tools like Grammarly for corrections. I have dropped some reviews please go over them and also check the section EngEd docs.
Thanks.

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +To install, you can download your SDK manually from [here](https://developers.facebook.com/resources/audience-network-sdk-6.8.0.zip) (Not recommended) or follow the steps in [Initial integration step
Rephrase this sentence, emphasis on recommended method.

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +The first and foremost step is to set up a business page where your ads will appear. You can follow this short [video](https://www.youtube.com/watch?v=fzW4eHQQLFk) to see how you can create your page
No need for "First & foremost".

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +Once you have created your FAN account, click on the extension/dropdown button at the top and select the monetization manager. Click on integration>properties, key in your Application name and id the
Edit this "Click on integration>".

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +Don't have an Application? No need to worry since you can set up a simple application in a few steps below.
Rephrase this sentence.

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +In this case, we are going to add Banner Ads as follows;
Use second person "You" not "We".

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +- People/users might hate the App due to **disturbances from ads pop-up**. This may discourage users from using known Applications with in-App advertisements.
The bold sentences are supposed to be at the beginning of the points as headings and not inline sentences.

2021-12-10 22:11 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +```kotlin
Add comments of what the code does or below the code.

2021-12-14 06:34 UTC, del-ui commented
@Jethro-magaji I have everything in place

2021-12-22 01:33 UTC, Jethro-magaji requested changes
Hi @del-ui 
I have dropped some reviews for you. Please use Grammarly and ProWritingAid to edit your article as there are still some grammatical errors. Else the next revision will require the closure of this PR.
Thanks.

2021-12-22 01:33 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
>  Monetizing an application is just as an important goal for a developer as producing the required product. This motivates developers and programmers to come up with more software with a financial thou
Please rephrase this "Monetizing an application is just as an important goal for a developer as producing the required product. This motivates developers and programmers to come up with more software with a financial thought in mind which triggers quality."

2021-12-22 01:33 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +### Demerits of integrating into some Applications
Integrating what? In-App ads or what?

2021-12-22 01:33 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +- For some people, it may be **difficult to navigate**. Some interested customers may not get to see the advertisement due to the incompatibility of the ads with some phones.
This "**difficult to navigate**"should be at the beginning of the sentence

2021-12-22 01:33 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +The verdict on whether to integrate your application with these Ads is always the owners' preference.
The owner in what context are you taking about here. Please rephrase this sentence.

2021-12-22 01:33 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +With your Android studio installed and working properly, you will needto install a Facebook Audience Network (FAN) account sdk.
"needto" give some spacing in between

2021-12-22 01:33 UTC, Jethro-magaji commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +To install, you can download your SDK manually from [here](https://developers.facebook.com/resources/audience-network-sdk-6.8.0.zip) (Not recommended) or follow the steps in [Initial integration step
What is the recommended method, is it the steps below? if it is, then specify it by telling the reader else explain the recommended method.

2021-12-23 23:36 UTC, hectorkambow commented
> Hi @del-ui I have dropped some reviews for you. Please use Grammarly and ProWritingAid to edit your article as there are still some grammatical errors. Else the next revision will require the closure of this PR. Thanks.

@Jethro-magaji 

Why was this PR not closed as indicated? 

![image](https://user-images.githubusercontent.com/60800358/147299625-ff442fd8-fe38-44f3-bcf0-2d8f41fd80ee.png)

2021-12-24 10:02 UTC, Jethro-magaji commented
> > Hi @del-ui I have dropped some reviews for you. Please use Grammarly and ProWritingAid to edit your article as there are still some grammatical errors. Else the next revision will require the closure of this PR. Thanks.
> 
> @Jethro-magaji
> 
> Why was this PR not closed as indicated?
> 
> ![image](https://user-images.githubusercontent.com/60800358/147299625-ff442fd8-fe38-44f3-bcf0-2d8f41fd80ee.png)

He made some the required changes that's why I left it open.

2021-12-27 03:37 UTC, Jethro-magaji commented
Hi! @ahmadmardeni1 
I have done my part of the review, please complete the review process by adding a format matter and other necessary tags.
Thanks.

2021-12-29 19:40 UTC, WanjaMIKE commented
@ahmadmardeni1, @Kayere, @LinusMuema

2022-01-04 18:30 UTC, lalith1403 commented
Jumping on this one 🚀

2022-01-04 18:33 UTC, lalith1403 commented
Hello @Jethro-magaji @del-ui, Can you shorten the URL of the article? It is way too long.

2022-01-04 18:47 UTC, lalith1403 requested changes
Several errors and readability issues exist over a glance. Please rectify these and let me know. The URL needs to be crisp and short. Make the change and make sure to change them in all instances.

2022-01-04 18:47 UTC, lalith1403 commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +- **Cost incurred on the user** to get the advertisement. To get the advertisement, the user's internet bundles get consumed from an unintended advertisement viewing task.
This point isn't clear. The user's internet bundle? If you are referring to cellular data, it may be better to reword it.

2022-01-04 18:47 UTC, lalith1403 commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +**FAN (Facebook Audience Network) SDK installation**
If this is a subsection, use H4 heading.

2022-01-04 18:47 UTC, lalith1403 commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +#### Step 1. **Set-up a  Business Page**
No need to bold headings

2022-01-04 18:47 UTC, lalith1403 commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +Consumers prefer in-App advertising over display advertising on mobile websites. Smartphone consumers find ads on the mobile web to be compacted and unpleasant. In-App advertisements are resized to f
Is this true though? @hectorkambow Need your help to review this para.

2022-01-04 18:47 UTC, lalith1403 commented on content/articles/integrating-facebook-ads-into-your-android-application-in-android-studio/index.md
> +Consumers prefer in-App advertising over display advertising on mobile websites. Smartphone consumers find ads on the mobile web to be compacted and unpleasant. In-App advertisements are resized to f
*this section

2022-01-04 19:00 UTC, lalith1403 commented
Hello @del-ui @Jethro-magaji. There are several readability issues with this article even after 4 rounds of revisions. I will go ahead and close this indefinitely. Please refer to the docs in the repo to understand the quality of articles we expect.

2022-01-04 19:00 UTC, closed without merging