How to build a client server application using Rust
section-engineering-education/engineering-education pull request #5504
Opened 2021-12-10 16:09 UTC by wanjcarol

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5334

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-11 06:06 UTC, EKahuha commented
I would like to review this @WanjaMIKE

2021-12-13 19:59 UTC, lalith1403 commented
plagiarism check done ✔️

2021-12-16 09:12 UTC, EKahuha requested changes
Great article @wanjcarol 
Make the recommended changes so that we can move on to tech review.

2021-12-16 09:12 UTC, EKahuha commented on content/articles/how-to-build-a-client-server-application-using-rust/index.md
> +We need a couple of Rust modules to set up this server and client. This includes;
These include;

2021-12-16 09:12 UTC, EKahuha commented on content/articles/how-to-build-a-client-server-application-using-rust/index.md
> +Before setting up a server, the server needs to handle the client's messages. The server has first to access these messages then decide what operation to perform.
The server must first access these messages ....

2021-12-17 15:56 UTC, wanjcarol commented
@EKahuha, I have made the above changes.

2021-12-21 18:59 UTC, EKahuha commented
This tutorial is ready for final review. @WanjaMIKE

2021-12-23 16:32 UTC, EKahuha approved these changes

2021-12-28 00:06 UTC, hectorkambow commented
I'll leave the Final Review to the CM team - as they will assess the test reviews. 
@section-engineering-education/content-moderator-team  

cc @ahmadmardeni1 @Kayere @LinusMuema  

🚀

2021-12-28 20:13 UTC, ahmadmardeni1 commented
I'm on it @hectorkambow 🚀

2021-12-29 08:38 UTC, ahmadmardeni1 commented
Great tutorial. Please go through all the changes I've made. @wanjcarol 
cc @EKahuha Do the same. Please make sure you go through our [Peer Reviewers](https://github.com/section-engineering-education/engineering-education/tree/master/peer_reviewers) docs before your next test review.

2021-12-29 08:38 UTC, merged