Configuring and unconfiguring a dhcp server
section-engineering-education/engineering-education pull request #5521
Opened 2021-12-11 21:05 UTC by immah-mul

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure?
- [X] Is your article properly formatted in Markdown? - 
- [X] Have you used our preferred heading structure? - 
- [X] Does your article follow any of the suggested structure formats? 

- [X] Is your article over 750 words? 
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? 
- [X] Can your article be understood by beginners? 

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it?
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article?
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit.
- [X] Have you checked your article for readability?
- [] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

`This closes #4743`

2021-12-11 21:10 UTC, immah-mul commented
@M0nicah done all the needed revisions

2021-12-29 13:16 UTC, M0nicah commented
hi @immah-mul, nice article.
I would like to point out sth I noticed:

- The commands and code are supposed to be clearly named/labeled. If the code is in Javascript ensure that you indicate it after the first backticks.
- Your article just has steps of what is to be done. I would advise you to at least add introduction paragraphs after each heading. These paragraphs explain what is to be done in that particular section. You can also explain why the step is important or why it should be done, then go ahead and explain how it is done. This will help the reader prepare for what they are going to read next and also flow easily throughout the step.

Kindly implement the changes, hit me up on slack in case of any questions.
Ping me when you are done.

**Note**: While writing a tutorial do not totally assume that your audience knows everything.

2021-12-29 22:51 UTC, immah-mul commented
@M0nicah 
I've taken time to make the requested changes. Kindly check

2022-01-04 11:40 UTC, M0nicah requested changes
@immah-mul , kindly check how you indicate your commands. I noticed you indicated some steps/instructions as commands.
You can remove that and take screenshots of the results and instructions that the reader is supposed to have/see.

ping me in case of a question.

2022-01-04 11:40 UTC, M0nicah commented on content/articles/configuring-a-dhcp-server/index.md
> +```bash
kindly explain this part. Is this a command? if yes, kindly explain what it does.

2022-01-04 11:43 UTC, M0nicah requested changes
@immah-mul , kindly check how you indicate your commands. I noticed you indicated some steps/instructions as commands.
You can remove that and take screenshots of the results and instructions that the reader is supposed to have/see.

ping me in case of a question.

2022-01-04 11:43 UTC, M0nicah commented on content/articles/configuring-a-dhcp-server/index.md
> +Соnfigure BООTР/DHСР оn lосаl LАN netwоrk: 102.21.0.0? ([Y]/N):N
This does not seem to be a command

2022-01-13 07:11 UTC, immah-mul commented
@M0nicah I've done the needed revisions

2022-01-14 14:59 UTC, Kayere commented
Congratulations for publishing your first article @immah-mul. Please go over the changes made by your peer reviewer and I to help improve the quality of your future articles.

cc @M0nicah

2022-01-14 15:02 UTC, merged

2022-01-25 16:26 UTC, hectorkambow commented
@immah-mul can you please DM me via slack 👍  

Thank you