License Plate Detection And Recognition Using OpenCv And Pytesseract
section-engineering-education/engineering-education pull request #5545
Opened 2021-12-12 19:11 UTC by kirurisimon

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5255

2021-12-15 17:55 UTC, lalith1403 commented
plagiarism check done ✔️

2021-12-28 10:27 UTC, collins-a requested changes
@kirurisimon good tutorial on plate detection and recognition. A few very minor changes and we shall move on to the final review.

Additionally, where applicable in future tutorials, consider using notebooks such as Google Colab (and share the link at the end of the tutorial) to allow readers to follow along and tweak the code for themselves without having to install an IDE.

Ping me when done.

2021-12-28 10:27 UTC, collins-a commented on content/articles/license-plate-detection-and-recognition-using-opencv-and-pytesseract/index.md
> +This technology applies in many areas. On roads, it is used to identify the cars that are breaking the traffic rules. On security, it is used to capture the license plates of the vehicles getting int
Pay closer attention to grammar in this paragraph. _On security_ does not sound right in the second line. _Packed_ is incorrect in the second last line.

2021-12-28 10:27 UTC, collins-a commented on content/articles/license-plate-detection-and-recognition-using-opencv-and-pytesseract/index.md
> +- Have **pycharm** installed on their computer. You can download **pycharm community edition** from here. [Pycharm Community Edition ](https://www.jetbrains.com/pycharm/download/)
It's much more fitting having the link on the word **here** as opposed to adding a phrase after it.

2021-12-28 10:27 UTC, collins-a commented on content/articles/license-plate-detection-and-recognition-using-opencv-and-pytesseract/index.md
> +! Happy coding
Send the exclamation mark to the end of the phrase. Also, consider always adding a few references/ further reading links for the reader to get more content on the topic.

2021-12-30 13:29 UTC, kirurisimon commented
@collins-a 
Finished working on the changes.

2021-12-31 09:30 UTC, collins-a approved these changes

2021-12-31 13:07 UTC, ahmadmardeni1 commented
Great tutorial @kirurisimon 
Thank you for the review. @collins-a

2021-12-31 13:07 UTC, merged