Localization and internationalization in android
section-engineering-education/engineering-education pull request #5554
Opened 2021-12-13 11:28 UTC by nia-vee

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5011

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-15 17:08 UTC, BrianaNzivu requested changes
Hey @nia-vee  👋 
Welcome to Section - EngEd. 🎉 
We are happy to have you here.
Just a few things I would love to point out before we proceed with the preliminary revisions:
- I am noticing that your images are not 600 x 400 px. Please scale down your images. You can use [BeFunky](https://www.befunky.com/) to do this,
- Your article has quite a lot of mistakes. I suggest you use [Grammarly](https://app.grammarly.com/) to make these corrections. 
- Please structure your article as required by Section. You can check out a tutorial's structures [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md).

Ping me when done.

Kind Regards.

2021-12-16 10:11 UTC, nia-vee commented
Hello @BrianaNzivu i have made the requested changes 
Thanks

2021-12-18 17:56 UTC, BrianaNzivu commented
Hey @nia-vee 👋 .
This article still has a lot of grammatical errors. Please cross-read it and use [Grammarly](https://app.grammarly.com/) to go through it to avoid closure of the closure of this PR.

**Please note: Our Peer Reviewer and Content Moderator teams do NOT provide any revisions services. All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner.**

2021-12-20 10:01 UTC, BrianaNzivu commented
Hey @nia-vee 👋🏾.
Everything OK?
Need some help?

2021-12-20 17:14 UTC, nia-vee commented
Hello @BrianaNzivu Have sent a message on slack.
Thanks in advance and am looking forward to get some help..

2021-12-22 08:50 UTC, BrianaNzivu commented
Tech review done.

2021-12-30 05:47 UTC, WanjaMIKE commented
Plagiarism check done

2022-01-03 17:09 UTC, BrianaNzivu approved these changes
Hey @nia-vee 👋 .

Very good job on the article. It is a very interesting read and has minimal mistakes. This is very impressive considering you are a first-time contributor 👏 .

Just a few things I'd like to point out:
- I suggest that you check out our resources page which has links to various resourceful tools for writing just to minimize the changes being made by the reviewer.
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Once again good job! 👍 

Kind Regards.

*P.s Wishing you a happy new year and a prosperous 2022.*

2022-01-05 10:41 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +Globalization is the process of building and developing a software product that functions in multiple cultures and locales.
Globalization has a wider meaning. Could you rephrase

2022-01-05 12:03 UTC, nia-vee commented
Hello @WanjaMIKE have given the clear definition 
Thank you.

2022-01-05 16:25 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +In this tutorial, we have learned localization, globalization, and internationalization. How the Android SDK deals with localized resources. We also learned the localization of strings and images. Be
`How the Android SDK deals with localized resources` this sentence is oddly placed. Rephrase

2022-01-05 16:27 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +Name the directory similar to the available image directory and select drawable on the resource type on the wizard that appears under the available qualifier.
This section seems rushed. Highlight things such as folder names etc. Explain it more clearly.

2022-01-05 16:28 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +Select locale hit the forward arrows to choose the appropriate qualifier, and hit ok. You will notice that the directory name is appended with the specified qualifier symbol, as shown below.
Replace hit with another synonym. Minimize repetition.

2022-01-05 16:29 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +Locate the newly created drawable subdirectory and add an image you wish to display for the specified locale. Ensure the image added within the new drawable folder has a similar name as that within t
Highlight key points like `this`

2022-01-05 16:30 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +-Text-to-Speech is audio that speaks out any text within the `string.xml` or hardcoded in the application.
is text-to-speech an audio or engine?

2022-01-05 16:31 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +- Ensure that the qualifier naming rule is followed. The best way to follow this naming rule is by creating an alternate resource directory using the new resource directory wizard and not doing it ma
Use another synonym for `follow`. Avoid repetition

2022-01-05 16:33 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +### Precautions when localizing your application
Is this section similar to `Best Practices ...`?. I think so.

2022-01-05 16:34 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +- Recorded Audio files - These are any audio file example, MP3, which are embedded in your application and played at different times.
No need to define recorded audio files.

2022-01-06 12:38 UTC, WanjaMIKE commented on content/articles/localization-and-internationalization-in-android/index.md
> +To get the full implementation of the project, visit this [GitHub Repository](https://github.com/nia-vee/LocalizationInternationalizationDemo)
The link you included here does not work.

2022-01-06 15:24 UTC, nia-vee commented
Hello? @WanjaMIKE 
Kindly don't remove the link i have fixed it i think i had included the URl wrongly but i have check on it is now working.
Thank you

2022-01-06 15:49 UTC, WanjaMIKE commented
@nia-vee Kindly, take note of the edits to improve in your future submission.

2022-01-06 15:53 UTC, WanjaMIKE commented
Merged #5554 into master

2022-01-06 15:53 UTC, merged