Creation of Calendar Heatmaps to Display Time-Series Quantitative Data with Python
section-engineering-education/engineering-education pull request #5562
Opened 2021-12-13 17:27 UTC by GeekEdmund

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5354

2021-12-21 17:24 UTC, JoelKanyi commented
Hello @hectorkambow Can I review this PR?

2021-12-22 01:42 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team lets keep an eye on this PR as @JoelKanyi is testing out a peer review.

2021-12-22 10:29 UTC, JoelKanyi commented
Hello @GeekEdmund ,  after going through your article, I am a fan of Python and I have to say that this is an informative article. However, it has some minor grammatical mistakes. 
- Please run the article through grammar checking software like [Grammarly](https://app.grammarly.com) to help improve the quality of your article.
- This being a tutorial, please structure your article as required by Section. You can check out a tutorial's structures [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md).
- Also check the requested changes below.

Ping me when you are done with the changes.

2021-12-22 10:37 UTC, JoelKanyi requested changes
Please make those changes so that we can proceed with the review. 

### Note - Please make sure you have used the correct format to write your article. Check on the template that I have suggested for you.

2021-12-22 10:37 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +- Evaluate current accomplishments.
I think this sentence is unnecessary - "In this  simple well-elaborated tutorial we have a lot of alternatives when it comes to choosing a visualization for our data."
Also, use spaces to separate your sentences as they are crowded.

2021-12-22 10:37 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
Because this is only one Python command, you can just use single backticks - ` `

2021-12-22 10:37 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
For your code snippets, please add the full language identifier - ```python
Please do so for the rest of your code snippets.

2021-12-22 10:37 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +
These whitespaces are unnecessary, please remove them

2021-12-22 14:22 UTC, JoelKanyi commented
@GeekEdmund  when you are done, please let me know. If you are facing an issue or would like help. Text me on Slack

2021-12-22 22:36 UTC, JoelKanyi commented
@ahmadmardeni1 could you please add a revision-needed label

2021-12-26 08:31 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +Weeks divide the days into columns, which are then classified by months and years. This allows us to immediately spot daily and weekly patterns as well as to detect anomalies in the data.
@GeekEdmund 
This seems just like paraphrasing.

2021-12-26 08:33 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
This one too

![copy1](https://user-images.githubusercontent.com/50293753/147403016-740e0222-60f5-4532-8b40-900bb6c90df0.png)
o

2021-12-26 08:35 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
![copy2](https://user-images.githubusercontent.com/50293753/147403043-8301e94c-e3e9-4608-a0a1-6437a79eab06.png)

2021-12-26 08:35 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
![copy3](https://user-images.githubusercontent.com/50293753/147403053-6534ae56-7c46-43d8-b685-a0c28ffcd100.png)

2021-12-26 08:36 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
![copy4](https://user-images.githubusercontent.com/50293753/147403065-3a59b81a-c13a-4e1c-ac2c-3b22d0bb8719.png)

2021-12-26 08:37 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
![copy5](https://user-images.githubusercontent.com/50293753/147403084-1ead7e3d-3a45-40db-916c-324a4580133b.png)

2021-12-26 08:38 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
![copy6](https://user-images.githubusercontent.com/50293753/147403103-939d779c-d3bb-4614-b011-c7f944c139a0.png)

2021-12-26 08:39 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
![copy7](https://user-images.githubusercontent.com/50293753/147403118-a8885c4a-1569-4222-89de-e0431583c131.png)

2021-12-26 08:42 UTC, JoelKanyi commented on content/articles/creation-of-calendar-heatmaps-to-display-time-series-quantitative-data-with-python/index.md
> +```
Hello @GeekEdmund 
I find your article not unique, it is just like a replica of this article:
[Calendar Heatmaps : A perfect way to display your time-series quantitative data](https://medium.com/analytics-vidhya/calendar-heatmaps-a-perfect-way-to-display-your-time-series-quantitative-data-ad36bf81a3ed)

@ahmadmardeni1 @hectorkambow 
I need your help on this article, the author says he used the other article as a source of reference.

2021-12-27 17:26 UTC, hectorkambow commented
Great question - and great sense of reviewing! 

We always push for unique and original content - anything that seems to be other than that is a great time to question! 

👏  

@JoelKanyi

2021-12-27 17:43 UTC, hectorkambow commented
@GeekEdmund 
>Thank you for submitting an article suggestion.
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites.
We lean towards content that offers an original viewpoint/approach around programming-centric topics.

cc @JoelKanyi

2021-12-27 17:43 UTC, closed without merging