Factor affecting the performance of deep learning
section-engineering-education/engineering-education pull request #5584
Opened 2021-12-14 10:07 UTC by KayTee24

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-14 16:48 UTC, KayTee24 commented
This closes #3630

2021-12-15 16:38 UTC, duncandegwa commented
Hello @hectorkambow  @ahmadmardeni1 I would like to review this article.

2021-12-16 08:35 UTC, ahmadmardeni1 commented
Go ahead @duncandegwa

2021-12-16 14:33 UTC, lalith1403 commented
plagiarism check done ✔️

2021-12-16 14:36 UTC, lalith1403 commented
plagiarism check done ✔️

The introduction and key takeaways paragraph needs to be re-written. They are completely plagiarized. Apart from that, the entire article is original. Thank you.

2021-12-16 16:05 UTC, KayTee24 commented
Hello, Good day to you.

Are you making reference to
https://github.com/section-engineering-education/engineering-education/issues/3630#issue-985236042

If your last mail meant I should review my Topic proposal, then I just have
done that.
Thanks & Regards

On Thu, 16 Dec 2021, 3:36 pm Lalithnarayan C, ***@***.***>
wrote:

> plagiarism check done ✔️
>
> The introduction and key takeaways paragraph needs to be re-written. They
> are completely plagiarized. Apart from that, the entire article is
> original. Thank you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/5584#issuecomment-995875345>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU6TTOMUK6AOKHHAMA6DV23URH2PRANCNFSM5KAOJ7HQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <section-engineering-education/engineering-education/pull/5584/c995875345@
> github.com>
>

2021-12-16 17:59 UTC, duncandegwa commented
Hello @KayTee24  Add author details I think this is your first article. Right?

2021-12-16 18:05 UTC, hectorkambow commented
@duncandegwa Have you checked in with me before doing a review via Slack 🤔  

cc @section-engineering-education/content-moderator-team 
cc @ahmadmardeni1

2021-12-16 18:08 UTC, hectorkambow commented
> Hello @hectorkambow @ahmadmardeni1 I would like to review this article.

This needs to be approved via slack 👍 @duncandegwa

2021-12-16 18:10 UTC, KayTee24 commented
> Hello @KayTee24  Add author details I think this is your first article. Right?

Yeah, it is.

2021-12-24 18:52 UTC, hectorkambow commented
@section-engineering-education/peer-reviewers

Is anyone available to review this PR?

Thank you

2021-12-25 11:41 UTC, srishilesh requested changes
@KayTee24 

Welcome to EngEd program!

I've suggested some major changes to article. Please make sure to address every points. Here are a few important things you have missed out:
- A hero image with dimension 600x400
- Lack of flow and clarity in explaining points
- Not enough research supporting your points. Add links wherever while stating facts or research.
- Markdown doesn't look good.
- Terminologies not explained
- Table of contents, Prerequisities and References sections missing.

Overall, I feel this article needs some major improvements, since it's not very beginner friendly. I would suggest you to take a step back, have a look at other Section articles.

If needed, you can attend [this](https://developers.google.com/tech-writing) course by Google on technical writing.

To allow you to make changes, we will be closing this PR for now. You can work on these changes in your forked repository. Once you're done, create a new PR and ping me.

Thanks.

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +* How can devices move accurately without human beings controlling them?
For bulleted points, always use `-`

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +      An excessive volume of information (data sets) can be trained. This uses learning algorithms in deep learning. Deep learning systems tend to gather functional facts from larger datasets. This e
This statement is unclear

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +
We can have a more briefer intro.

Give an insight of what the reader is going to learn, what is this topic about, why should they learn, see if beginners can understand this article. And, don' try to beat around the bush, directly get to the point.

Have a look at other articles to get an idea of how intro could be

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +
Add `Table of contents` section (Make sure to use markdown hyperlinks) and `Pre-requisities` section.

Have a look at other articles

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +#### Do you think deep learning will make current technologies better?
Start with `###` markdown header

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +Deep learning is, without a doubt, at the pinnacle of the most current technological hierarchy. The ability to collect data is crucial for systems (information). The data acquired enables exact forec
There is no flow between lines. It looks very unclear.

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +#### i. Taking into account the issue (considered problem) that the system will be tasked with resolving;
```suggestion
#### Taking into account the issue (considered problem) that the system will be tasked with resolving; 
```

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +* How easily will re-engineering be made possible?
Use `-`

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +          According to research, the Adam optimiser offers the highest and best performance rate. The ability to outperform other approaches (optimisers) is lacking.
Remove these additional tab spaces. And, you can remove these roman numerals as well.

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +#### ii. Evaluation difficulties of default hyperparameters for multiple optimisers.
Beginners might not be aware of these terms. Please make sure to explain them

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +          Poor accuracy is obtained here as a result of low awareness from training the system data sets. The Adams optimiser is used in this deep system algorithm, which is adaptable.
Don't think we can state this fact without linking adequate research papers or articles.

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +          According to research, the Adam optimiser offers the highest and best performance rate. The ability to outperform other approaches (optimisers) is lacking.
` According to research`

Please link the paper

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +Manipulation of GAN's unit-producing outlets is complicated by artificial pruning. Trained images, like adversarial examples, are developed, categorized, and highlighted on certain neurons. These neu
Why are these points more aligned towards CNN or GAN? Shouldn't it be generalized?

Explanation of various terminologies are missing

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +The theory (lottery subspaces) seeks to repeat data from prior training experiments. It then establishes the settings for a low-dimensional projection. It compares the parameters to such a trajectory
It looks very technical, and is not beginner friendly.

Please make sure to explain the necessary keywords and maintain a flow between sentences.

2021-12-25 11:41 UTC, srishilesh commented on content/articles/factors_that_affects_the_performance_of_system_using_deep_learning/index.md
> +### Diagram Demonstrating The Different Scenarios One Can Fall Into When Configuring The Learning Rate.
Is this subtopic incomplete? Why is this after conclusion? Have you missed out something?

2021-12-25 11:41 UTC, closed without merging