Implementing an auto-logout feature for Android(Kotlin)
section-engineering-education/engineering-education pull request #5606
Opened 2021-12-15 16:24 UTC by vinstex

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5413 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-15 17:13 UTC, BrianaNzivu requested changes
Hey @vinstex 👋 .
My name is Briana and I will be conducting the review for your article.
Just one small thing I want you to correct as I proceed with preliminary revisions. I need you to scale down your images to the required 600 x 400 px. You can use [BeFunky](https://www.befunky.com/) to do this.

2021-12-15 17:26 UTC, vinstex commented
Greetings Nzivu. I used to think it's only the hero image that needs to be scaled down. Anyway, I'm doing it right away. My author folder is `vincent-ngunzulu`

2021-12-15 17:28 UTC, vinstex commented
Or I can remove the screenshot part. Because they really look awkward when I reduce the to that size. @BrianaNzivu

2021-12-15 17:40 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team 
Team lets keep an eye on this PR for quality - as the author has expressed an interest in becoming a peer reviewer. 

I've mentioned the 1st step would be to publish an article with little to no revisions required. 

cc @BrianaNzivu  

🚀  

Thank you

2021-12-15 17:48 UTC, BrianaNzivu commented
> @section-engineering-education/content-moderator-team 
> Team lets keep an eye on this PR for quality - as the author has expressed an interest in becoming a peer reviewer. 
> 
> I've mentioned the 1st step would be to publish an article with little to no revisions required. 
> 
> cc @BrianaNzivu  
> 
> 🚀  
> 
> Thank you 

Noted 👍🏾

2021-12-15 18:09 UTC, vinstex commented
@BrianaNzivu . there is some error I did during the typing of the document. I put a return value on some two methods which didn't any return type😃. Noticed? I will change that when you are done with some revisions😃😃

2021-12-15 18:14 UTC, lalith1403 commented
plagiarism check done ✔️

2021-12-15 18:36 UTC, BrianaNzivu commented
> @BrianaNzivu . there is some error I did during the typing of the document. I put a return value on some two methods(`onLongPress()` and `onShowPress()`) which didn't any return type😃. Noticed? I will change that when you are done with some revisions😃😃. My bad. Apologies for that

I was just about to raise this issue. You can correct it before I proceed with the tech review.

2021-12-15 18:44 UTC, vinstex commented
@BrianaNzivu, I fixed that. Thank you for your understanding.

2021-12-15 19:12 UTC, BrianaNzivu commented
> @BrianaNzivu, I fixed that. Thank you for your understanding.

No worries.
Proceeding with tech review.

2021-12-16 09:32 UTC, BrianaNzivu commented
Tech review done 👍

2021-12-16 09:37 UTC, BrianaNzivu commented on content/articles/android-autologout-kotlin/index.md
> +Run the app and do some touches, scrolls, and wait 15 seconds to check the feature. Also, do the same before the seconds elapse and check. Change the numbers and check too.
Hey @vinstex .
Maybe you can link the repo that will contain this project's code here and a downloadable sample APK for this project linked which you can host on Google drive.

2021-12-17 08:20 UTC, BrianaNzivu approved these changes
Hey @vinstex   👋 .
Great job on the article! Interesting read and very minimal corrections to be made. Keep up the great job!
Just a final comment: 
- All images should be 600 x 400 px. Never forget that.
- Please go through all the changes I have made to avoid repeating the same mistakes in your future articles.

That's it! :smile: 

Wishing you all the best in your endeavors of becoming a peer reviewer. You will be a great addition to our team. If you make it in, please do not hesitate to ask for assistance in case you need some help because it is also a journey to becoming a great reviewer.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 

I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2021-12-17 18:34 UTC, vinstex commented
Ta-da!

2021-12-17 18:34 UTC, vinstex commented
@hectorkambow

2021-12-17 20:57 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team

2021-12-20 18:46 UTC, hectorkambow commented
jumping on this one

2021-12-20 19:21 UTC, merged