how-to-create-a-winforms-io-manager-for-removable-drives-in-c#
section-engineering-education/engineering-education pull request #5632
Opened 2021-12-16 20:12 UTC by Donel254

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5331 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-24 05:15 UTC, owinowendy commented
@ahmadmardeni1 should I review this?

2021-12-24 07:10 UTC, WanjaMIKE commented
Jumping on to this one

2021-12-24 09:21 UTC, owinowendy commented
@WanjaMIKE am I reviewing this?

2021-12-25 04:21 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> +From the `Toolbox`, drag and drop a groupbox just below the instruction label and set its dimensions to `560, 150` under its size property. Change the `groupBox1` text to `Enable/Disable then change
Ensure all backticks are properly enclosed!

2021-12-25 04:24 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> +2. Basic knowledge in C# language and the .NET framework.
The usual preposition that follows knowledge is `of`. Don't use the prepositions in.

2021-12-25 04:26 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> + On the next window(Create a new project) :
Format this correctly. The sentence should start from the beginning!

2021-12-25 04:27 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> + we will select the `Windows Forms App` template then select `Next`:
The sentence begins with a capital letter....fix where applicable!

2021-12-25 04:28 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> +### Step 2 - Designing the UI
Let's have `user interface ` instead of just UI

2021-12-25 04:28 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> +#### 2.4 - Add Instructions label
Only the first letter should begin with a capital. Fix where applicable throughout your article!

2021-12-25 04:30 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> +To edit the code, right-click on the form(the teal background) then select `view code` and Visual Studio will load `Form1.cs`. Now we will add the namespaces commented `new` just below the default on
This sentence is quite hard to read, try breaking it down if possible or rewrite it altogether!

2021-12-25 04:31 UTC, owinowendy commented on content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-c#/index.md
> +`System.Runtime.InteropServices` - supports COM interop and platform invoke services.
These are hanging, are they explanations of the prev code? Work on your article flow! It's there throughout the article!

2021-12-25 04:35 UTC, owinowendy requested changes
- Hi, I have suggested to you a few fixes to work on. I noticed most of them are repetitive. Go through your article again.

-  Your article lacks the general flow at some points, for example, you start explaining some code snippets without informing the reader which one...
- Ensure all code snippets are well explained!

2021-12-25 09:14 UTC, WanjaMIKE commented
@owinowendy could you pause with the review. We will try you out soon. Thanks

2021-12-29 20:05 UTC, Donel254 commented
> * Hi, I have suggested to you a few fixes to work on. I noticed most of them are repetitive. Go through your article again.
> * Your article lacks the general flow at some points, for example, you start explaining some code snippets without informing the reader which one...
> * Ensure all code snippets are well explained!

Thanks but you were harsh ... its my first article mahn! ...go easy on me

2021-12-29 20:45 UTC, Donel254 commented
Hello @WanjaMIKE ...I made some changes, please take a look.

2021-12-30 06:22 UTC, WanjaMIKE commented
Plagiarism check done. Some of your code seem to be derived from other sites especially functions and variable names. Please fix them.  
[New Scan 6_13 AM Copyleaks Report (1).pdf](https://github.com/section-engineering-education/engineering-education/files/7791723/New.Scan.6_13.AM.Copyleaks.Report.1.pdf)

2021-12-30 21:07 UTC, Donel254 commented
> Plagiarism check done. Some of your code seem to be derived from other sites especially functions and variable names. Please fix them. [New Scan 6_13 AM Copyleaks Report (1).pdf](https://github.com/section-engineering-education/engineering-education/files/7791723/New.Scan.6_13.AM.Copyleaks.Report.1.pdf)

Revisions done

2022-01-05 10:36 UTC, WanjaMIKE commented
@Donel254 Please add a better avatar. Your current pic seems a bit dark

2022-01-06 22:32 UTC, Sajeyks commented
> @Donel254 Please add a better avatar. Your current pic seems a bit dark

Done.

2022-01-12 16:15 UTC, ahmadmardeni1 commented
Great work @WanjaMIKE @Donel254

2022-01-12 16:15 UTC, merged