Understanding how cluster markers work
section-engineering-education/engineering-education pull request #5664
Opened 2021-12-19 18:30 UTC by Adebogunabdulroheem

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-24 18:52 UTC, hectorkambow commented
@section-engineering-education/peer-reviewers

Is anyone available to review this PR?

Thank you

2021-12-25 04:42 UTC, jumamiller commented
> @section-engineering-education/peer-reviewers
> 
> Is anyone available to review this PR?
> 
> Thank you

@hectorkambow I'm available to work on this!

2021-12-25 04:45 UTC, jumamiller commented on content/articles/understanding-how-cluster-marker-works/index.md
> +  This is no more a news, as we are all aware that big data is the keyword of the 21st century, and It's shocking to realize that only a few people understand that a large part of data is categorized
This is a very hard-to-read paragraph. Break it down into multiple paragraphs.

2021-12-25 04:46 UTC, jumamiller commented on content/articles/understanding-how-cluster-marker-works/index.md
> +To Understand this tutorial, it is assumed that the reader knows the below technologies:
Work on this grammar. Go straight to the point and make this article flow!

2021-12-25 04:47 UTC, jumamiller commented on content/articles/understanding-how-cluster-marker-works/index.md
> +At the end of this guide, we'll build a map with clustering features, and these include:
You don't build the features at the end!! Do you build it from the start? In the end what should have the learner gain reading your article?

2021-12-25 04:48 UTC, jumamiller requested changes
Hi, the article is of very low quality, in terms of grammar and flow and even the formatting. Kindly work on it afresh to avoid its closure! Thank you!

2021-12-26 05:22 UTC, jumamiller commented
Hi, I'll close this for now, kindly re-submit a ready-to-publish article!

2021-12-26 05:22 UTC, closed without merging