Implementing Pre-Loading and Buffering Videos in Android with ExoPlayer
section-engineering-education/engineering-education pull request #5704
Opened 2021-12-22 08:40 UTC by codewithjudy

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes  #5256

2021-12-22 08:49 UTC, Ericgacoki commented
Hello @codewithjudy, Welcome to Section Eng-ed 🤗.
On a quick glance, your article looks good but it seems like you forgot to add a `hero image`. Add a `600X400`px image named `hero.png` or `hero.jpg` in the same folder as `index.md` and ping me when you're done!

2021-12-22 08:54 UTC, codewithjudy commented
@Ericgacoki thank you for deciding to review my article.

I have added the hero image and a few screenshots that I had forgotten

2021-12-30 10:02 UTC, WanjaMIKE commented
Plagiarism check done.

2022-01-11 20:10 UTC, Ericgacoki requested changes
Hello @codewithjudy, this is quite impressive - considering it's your first article 👏.
Kindly fix the following issues and let me know when you're done!

2022-01-11 20:10 UTC, Ericgacoki commented on content/articles/implementing-preloading-and-buffering-videos-in-android-with-exoplayer/index.md
> +
There seems to be a few such empty lines. Consider removing them.

2022-01-11 20:10 UTC, Ericgacoki commented on content/articles/implementing-preloading-and-buffering-videos-in-android-with-exoplayer/index.md
> +            mProgressListener,
This could fit in a single line! Kindly fix that.
Also, remember to indent your code properly and indicate the language identifier!

2022-01-11 20:10 UTC, Ericgacoki commented on content/articles/implementing-preloading-and-buffering-videos-in-android-with-exoplayer/index.md
> +When pre-caching a video, it is good to do it in a different `Activity` or `Fragment`. So that when the user navigates to the actual Destination, he/she finds the video is ready. Like on youtube, vid
Use a more descriptive heading while maintaining it short.

2022-01-11 20:10 UTC, Ericgacoki commented on content/articles/implementing-preloading-and-buffering-videos-in-android-with-exoplayer/index.md
> +
Remove the unnecessary space (as mentioned earlier).

2022-01-11 20:10 UTC, Ericgacoki commented on content/articles/implementing-preloading-and-buffering-videos-in-android-with-exoplayer/index.md
> +
Remove the unnecessary space (as mentioned earlier).

2022-01-11 20:10 UTC, Ericgacoki commented on content/articles/implementing-preloading-and-buffering-videos-in-android-with-exoplayer/index.md
> +In this tutorial, we have understood what preloading and precaching are. We went ahead and implemented a simple app that preloads video Url. With this knowledge, go ahead and implement it in your med
Give a little more detailed conclusion.

2022-01-12 03:23 UTC, codewithjudy commented
@Ericgacoki, I have made the requested changes

2022-01-14 18:55 UTC, Ericgacoki approved these changes

2022-01-18 19:59 UTC, hectorkambow commented
jumping on this one

2022-01-18 20:26 UTC, merged