Python metaclasses for metaprogramming
section-engineering-education/engineering-education pull request #5730
Opened 2021-12-23 17:36 UTC by Dick7603

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4692

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-23 17:39 UTC, Dick7603 commented
Duplicate of #5345

2021-12-23 17:40 UTC, Dick7603 commented
Hello, @jerimkaura I`ve done the changes. Thank you.

2021-12-24 12:58 UTC, srishilesh commented
@jerimkaura 

Assigning this PR to you, since you had reviewed this PR before.

2021-12-24 23:50 UTC, jerimkaura requested changes
Hello @Dick7603 

Kindly take a look at the changes, work on them then ping me. Don't be in hurry, just make sure you are done completely to minimize the risk of closure.

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +Metaprogramming is the practice of writing code that manipulates other code. It refers to the ability of a program to regulate itself.
It would be really great if you expounded on how a program regulates itself.

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +Object-oriented programming(OOP) is essential in Python. This concept relies on metaprogramming.
Form a complete paragraph from these sentences. It is unprofessional to have one line paragraphs

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +Object-oriented programming(OOP) is essential in Python. This concept relies on metaprogramming.
Tell the readers how OOP relies on metaprogramming.

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +To follow along, you need some some knowledge of decorators and object-orented programming concepts in Python.
```suggestion
To follow along with this article, you need to have:
- Knowledge of decorators 
- Object-oriented programming concepts in Python.

```

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +Metaclasses in Python are classes of classes that specify the behavior of a class. A class is a metaclass in its own right. How the class is implemented is defined by its class definition in Python.
This point is not clear. I am having trouble understanding. Would you please elaborate?

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +We need to add additional code or processes to the Metaclass framework. Although end-users seldom use Metaclasses, they are essential in some programming problems.
Explain why we add additional code. What are these processes?

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +- It is possible to hook on `new`, `init`, and `call` hooks.
@Dick7603  These points are great but you need to clarify them. Provide some in-depth explanation for the benefit of readers.

2021-12-24 23:50 UTC, jerimkaura commented on content/articles/python-metaclasses-for-metaprogramming/index.md
> +
Explain these points well and provide real-life examples.

2021-12-27 20:59 UTC, jerimkaura reviewed
Hello kindly work on the changes then we proceed

2022-01-01 06:49 UTC, jerimkaura commented
Hello, if you need more time to work on this PR you can on your forked repo. I will be closing this PR. You can open a new PR Once you are done with the article.

2022-01-01 06:49 UTC, closed without merging

2022-01-05 06:52 UTC, Dick7603 commented
Hello @jerimkaura I had tried to reach you via slack. Kindly check. Thank you.

2022-01-05 06:52 UTC, Dick7603 commented
Hello @jerimkaura I had tried to reach you via slack. Kindly check. Thank you.