Road layout design programmatically using matlab
section-engineering-education/engineering-education pull request #5752
Opened 2021-12-24 17:23 UTC by vitalisodhis

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5089 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-24 18:53 UTC, hectorkambow commented
@section-engineering-education/peer-reviewers

Is anyone available to review this PR?

Thank you

2021-12-25 11:01 UTC, owinowendy commented
@hectorkambow I'd love to review this!

2021-12-30 04:56 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +
Hi, kindly reduce these spacings!

2021-12-30 04:59 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +
Restructure the article, such that we've got this intro part appearing on the top! followed by the ToC in that order.

2021-12-30 05:01 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +
Hi, I think these ones best fit the objectives rather than having them on the introduction part?

2021-12-30 05:08 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +The first step of designing any road layout is defining the `Scenario` function as  `drivingscenario`, that is `scenario=drivingScenario`.  After the declaration of scenario function the road center
This paragraph is quite long, consider breaking it down. You may also rewrite this part: `.... function as  `drivingscenario`, that is `scenario=drivingScenario...`

2021-12-30 05:08 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +The first step of designing any road layout is defining the `Scenario` function as  `drivingscenario`, that is `scenario=drivingScenario`.  After the declaration of scenario function the road center
> This paragraph is quite long, consider breaking it down. You may also rewrite this part: `.... function as `drivingscenario`, that is `scenario=drivingScenario...`

Work on punctuations as well to make your sentences easy to read!

2021-12-30 05:10 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +The first step of designing any road layout is defining the `Scenario` function as  `drivingscenario`, that is `scenario=drivingScenario`.  After the declaration of scenario function the road center
Simplify your words, for example, `obtained` is better than `gotten`. Be as simple as possible!

2021-12-30 05:10 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +To make a road intersection layout, one has to make two different roads. One of the two roads will be vertically oriented while the other one horizontally oriented. For demonstrations, we will interc
Consider breaking this down into multiple paragraphs!

2021-12-30 05:15 UTC, owinowendy requested changes
Hi @vitalisodhis, I have reviewed your article and noticed a few mistakes:

- You have long paragraphs in most cases; I've given you a few instances. Fix them where applicable throughout your article.
- There are a couple of punctuation mistakes. For example, you omit full stops or commas, kindly consider using Grammarly to fix them where necessary.

Ping me when you're done.

Regards.

2021-12-30 10:22 UTC, WanjaMIKE commented
Plagiarism check is done.

2021-12-30 23:13 UTC, vitalisodhis commented
@owinowendy Changes made.

2022-01-04 05:19 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +In designing road layout, we use the `drivingscenario` function. `scenario` function allows for simulation of an activity or a structure that can be found in the real world. `Drivingscenario` functio
Kindly break down this into two paragraphs. It's too hard to read!

2022-01-04 05:20 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +
Remove this spacing!

2022-01-04 05:29 UTC, owinowendy reviewed
Hi @vitalisodhis, you have done an amazing job improving the quality of this article. 

However, I have to point out that there exist some sentences which are complex to read either missing correct punctuation marks or grammatical.

For example,`...The more road center coordinates used the more the formation of a complex curve road...` should read as `...The more road center coordinates used, the more a complex curve road formed...`

Kindly revise those minor mistakes before we move to the next phase of the review!

2022-01-04 06:41 UTC, vitalisodhis commented
@owinowendy  Changes made.

2022-01-04 07:03 UTC, owinowendy reviewed
Hi, there are still a couple of punctuation marks missing, just take your time and read the entire article as if you were the reader(and NoT as the author). 

Always ensure your article is in active and not passive voice!

You may as well use tools such as Grammarly to improve the general quality!

Regards,

2022-01-05 11:55 UTC, vitalisodhis commented
@owinowendy changes made.

2022-01-06 16:05 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +### Road layout design programmatacally using matlab
Hi, kindly fix this heading to: `Road layout design programmatically using MatLab`

2022-01-06 16:08 UTC, owinowendy commented on content/articles/road-layout-design-programatically-using-matlab/index.md
> +You can use the `Drivingscenario` function to create different road layout designs by plotting the road layout in 2D or 3d graphs. It is done by specifying the coordinates of the road center using fu
Ensure consistency while using dimensions, in this case, 2D,3D, and not `3d`.

2022-01-06 19:25 UTC, vitalisodhis commented
@owinowendy  Changes made.

2022-01-07 07:42 UTC, owinowendy commented
Great work @vitalisodhis.
@ahmadmardeni1 this article is ready for final review pending front-matter and peer reviewer-line.

Thank you!

2022-01-20 16:58 UTC, merged

2022-01-21 16:06 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team  

I don't think this test reviewer was approved - have no recollection of the student asking beforehand!

2022-01-21 19:39 UTC, ahmadmardeni1 commented
Hey @Wilkistermumbi Did you contact any CM and got approval before doing this test review? 

@jumamiller Please do NOT assign anyone in the future. This is our team job.