Getting Started With NLP Transformers
section-engineering-education/engineering-education pull request #5760
Opened 2021-12-25 07:32 UTC by norah254

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5338 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-29 05:45 UTC, jumamiller commented on content/articles/getting-started-with-nlp-transformers/index.md
> +In today's world of daily new improvements and developments in technology, the field of Natural Language Processing (NLP) has not been left behind. New developments like Transfer Learning, Transforme
Kindly break this down into 2 paragraphs.

2021-12-29 05:45 UTC, jumamiller commented on content/articles/getting-started-with-nlp-transformers/index.md
> +
Ensure this spacing between the heading and first paragraph is removed throughout your article!

2021-12-29 05:47 UTC, jumamiller requested changes
Hi, work on those minor edits before we move to tech review!

2021-12-29 13:12 UTC, jumamiller commented
The changes have not been reflected on the above commit?

2021-12-29 13:39 UTC, norah254 commented
Check well, the changes have just not been highlighted.

2021-12-29 13:42 UTC, jumamiller commented on content/articles/getting-started-with-nlp-transformers/index.md
> +* Model more [NLP Transformer tasks](https://www.kaggle.com/varunyadav17/nlp-transformer-tasks#Sequence-Classification-Task--).
And these?

2021-12-29 13:42 UTC, jumamiller commented on content/articles/getting-started-with-nlp-transformers/index.md
> +
This one too

2021-12-29 13:43 UTC, jumamiller commented on content/articles/getting-started-with-nlp-transformers/index.md
> +
> Ensure this spacing between the heading and first paragraph is removed throughout your article!

This comment here; FIX THE ENTIRE ARTICLE!

2021-12-30 08:49 UTC, jumamiller commented
Hi, are you having challenges making edits? The commits you're making are not resolving the requested changes!

Also, ensure you pass the article on Grammarly, 'cause it has a couple of mistakes.

Kindly reach me on Slack(@Miller) in case you're stuck.

2021-12-30 10:25 UTC, WanjaMIKE commented
Plagiarism check is done.

2022-01-03 09:11 UTC, jumamiller approved these changes
Hi @norah254, kindly check if the author details have been correctly entered!

A great article to get you started @section. Kudos!

2022-01-20 14:00 UTC, louisefindlay23 requested changes
Please rename the images where you have the file extensions to be block capitals to lowercase.

2022-01-21 01:08 UTC, norah254 commented
@louisefindlay23 and @jumamiller since GitHub web interface doesn't allow editing of images, Could I close the PR and ping you on a new one once the changes are done?

2022-01-21 05:09 UTC, jumamiller commented
@louisefindlay23 I think images should just work fine. I have tested them on my end(Not sure of your opinion on this).

@norah254 to edit, delete the specific image(s) and then re-upload. Do not close the PR.

2022-01-26 08:39 UTC, norah254 commented
@louisefindlay23 the changes are done

2022-01-26 08:40 UTC, jumamiller commented
@louisefindlay23 images have been renamed!

2022-02-01 04:56 UTC, jumamiller commented
@ahmadmardeni1, @Kayere  are you in a position to publish this article?

2022-02-03 14:05 UTC, WanjaMIKE commented
Merged #5760 into master

2022-02-03 14:05 UTC, merged