Getting Started with Optical Character Recognition
section-engineering-education/engineering-education pull request #5762
Opened 2021-12-25 08:55 UTC by lcheptoo

This closes #5697

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-30 10:28 UTC, WanjaMIKE commented
The following code shows plagiarism. This includes variable names. Please correct it.

```python

img = cv2.imread("image-one.jpg")

spacer = 100

for detection in results:

top_left = tuple(detection[0][0])

bottom_right = tuple(detection[0][2])

text = detection[1]

img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),3)

img = cv2.putText(img,text,(20,spacer), font, 0.5,(0,255,0),2,cv2.LINE_AA)

spacer+=15


plt.imshow(img)

plt.show()

```

2022-01-06 13:26 UTC, collins-a commented
> The following code shows plagiarism. This includes variable names. Please correct it.
> 
> ```python
> img = cv2.imread("image-one.jpg")
> 
> spacer = 100
> 
> for detection in results:
> 
> top_left = tuple(detection[0][0])
> 
> bottom_right = tuple(detection[0][2])
> 
> text = detection[1]
> 
> img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),3)
> 
> img = cv2.putText(img,text,(20,spacer), font, 0.5,(0,255,0),2,cv2.LINE_AA)
> 
> spacer+=15
> 
> 
> plt.imshow(img)
> 
> plt.show()
> ```

@lcheptoo just following up to ensure you saw the above comments on the areas of your code that need changing before I review your article.

2022-01-14 06:54 UTC, lcheptoo commented
> > The following code shows plagiarism. This includes variable names. Please correct it.
> > ```python
> > img = cv2.imread("image-one.jpg")
> > 
> > spacer = 100
> > 
> > for detection in results:
> > 
> > top_left = tuple(detection[0][0])
> > 
> > bottom_right = tuple(detection[0][2])
> > 
> > text = detection[1]
> > 
> > img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),3)
> > 
> > img = cv2.putText(img,text,(20,spacer), font, 0.5,(0,255,0),2,cv2.LINE_AA)
> > 
> > spacer+=15
> > 
> > 
> > plt.imshow(img)
> > 
> > plt.show()
> > ```
> 
> @lcheptoo just following up to ensure you saw the above comments on the areas of your code that need changing before I review your article.

@collins-a done.

2022-01-21 13:27 UTC, collins-a requested changes
Near flawless tutorial on OCR @lcheptoo. A couple of changes and we're set for the final review.

2022-01-21 13:27 UTC, collins-a commented on content/articles/getting-started-with-optical-character-recognition/index.md
> +![Multiple lines](/engineering-education/getting-started-with-optical-character-recognition/multiple-lines.png)
This image is missing from the article files

2022-01-21 13:27 UTC, collins-a commented on content/articles/getting-started-with-optical-character-recognition/index.md
> +Result:
Running the code block for **handling multiple lines** yields the following error

```python
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-22-61b6150f70c9> in <module>()
      5     bottom_right = tuple(detection[0][2])
      6     text = detection[1]
----> 7     img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),3)
      8     img = cv2.putText(img,text,(20,spacer), font, 0.5,(0,255,0),2,cv2.LINE_AA)
      9     spacer+=15

error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2
```

2022-01-24 19:09 UTC, lcheptoo commented
> Near flawless tutorial on OCR @lcheptoo. A couple of changes and we're set for the final review.

@collins-a done.

2022-01-25 23:02 UTC, collins-a approved these changes

2022-01-26 09:14 UTC, ahmadmardeni1 commented
Great work team. @lcheptoo @collins-a

2022-01-26 09:14 UTC, merged