Build Vue.js Application with Django REST API and Axios
section-engineering-education/engineering-education pull request #5766
Opened 2021-12-25 21:49 UTC by dentonya

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5401 `

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-26 16:41 UTC, mercymeave requested changes
Hello @dentonya 

You have a really nice article here. I like how detailed it is. However, please commit the suggestions so that we proceed to the next round of revision

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +When developing applications, it's common to use APIs to consume and display data. We can make this possible using the Axios library, that can be used to create Vue.js apps where Django, a python-bas
Break this sentence into smaller simple sentences.

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +
```suggestion
The reader should have  the following to follow along with this tutorial:
- Fundamental understanding of the Django REST framework and REST API.
- Knowledge about Vue.js and the Axios library.
- Know how to use PyCharm, Visual Studio Code, or any other IDE for working with Python Django and Vue js.

```

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +- Know how to use PyCharm,Visual Studio Code or any other IDE for working with Python Django and Vue js.
Provide links to the pieces of  software

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +To implement this, we'll create a simple Vue Todo Application together with the Django REST API and Axios.
```suggestion
**Django** is a Python-based backend framework used to create native applications or as an API using the Django rest framework package. Additionally, we can also combine it with Vue.js; a JavaScript-based front-end framework, in building applications.

This process is made possible by including the Vue.js scripts directly into the Django template HTML code. However, we can also use the Django API to consume and display data using the HTTP client library called **Axios**. To implement this, we will create a simple Vue Todo Application together with the Django REST API and Axios.
```

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +We'll start by setting up the Django and Vue.js in our machines together with the Axios library.
Minimize the suer of contractions in formal writing. Do this across the entire artile.

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +The complete code can be found [here](https://github.com/dentonya/Todo-Application-using-Vue.js-Django-REST-API-and-Axios/tree/master/vue.js/todoapp).
```suggestion
Running the project again, you should see two tasks to the left(work to do) and one to the right which is done. The complete code can be found [here](https://github.com/dentonya/Todo-Application-using-Vue.js-Django-REST-API-and-Axios/tree/master/vue.js/todoapp).
```

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +As seen from the above tutorial,it is possible using the Axios library to fetch and display data when building Vue.js applications where Django framework  used purely as an API.
```suggestion
As seen from the above tutorial, it is possible using the Axios library to fetch and display data when building Vue.js applications where the Django framework used purely as an API.
```

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +Once the vue app is created we then communicate with the backend usig the `Axios` libary and display the tasks by inserting the code below inside the `HelloWorld.vue` file under the `src` folder.
```suggestion
Once the Vue.js app is created we then communicate with the backend using the `Axios` library and display the tasks by inserting the code below inside the `HelloWorld.vue` file under the `src` folder.
```

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +Once the project runs successfully the output  below is displayed in the browser.
```suggestion
Once the project runs successfully, the output below is displayed in the browser.
```

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +Run all the database migrations and use the command below to open the python shell and type a few of the tasks and their descriptions then close the shell.
Break this into multiple sentences.

2021-12-26 16:41 UTC, mercymeave commented on content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
> +Since we are using the rest_framework, we need to create another file under the todo application folder called `serializers.py`  and add the code below:
Tell the reader what the serializer.py file does.

2021-12-26 17:23 UTC, dentonya commented
Ook

2021-12-26 21:39 UTC, dentonya commented
@mercymeave done with the changes

2021-12-30 10:40 UTC, WanjaMIKE commented
Most of your code including comments, variables names, comments, and functions appear to have been taken from other articles such as https://codewithstein.com/combining-django-and-vuejs-everything-you-need-to-know/ We focus more on unique content. Thanks

[New Scan 10_30 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7792548/New.Scan.10_30.AM.Copyleaks.Report.pdf)

2021-12-30 10:40 UTC, closed without merging