Building a Lyrics Search App Using Vanilla JavaScript
section-engineering-education/engineering-education pull request #5782
Opened 2021-12-26 21:33 UTC by shegz101

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-30 00:46 UTC, hectorkambow commented
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2022-01-02 12:16 UTC, srishilesh requested changes
@shegz101 

Welcome to EngEd!

The markdown formatting changes looks good. I've suggested a few other minor changes. Please go through them and address them all.

Ping me when you're done.

Thanks.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +### Prerequisites
```suggestion
### Pre-requisites
```

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +
You can add a `Table of contents` section as well.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +In the `lyrics.html` file, copy the code below and paste it in your code editor to create the structure for the lyrics search app.
` copy the code below and paste`

Instead of saying this, explain what is being done here and why are we doing it.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +In the `lyrics.html` file, copy the code below and paste it in your code editor to create the structure for the lyrics search app.
Do the same for other code snippets as well.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +```
Usually, there is nothing much to explain in CSS unless the whole article is about CSS.

If you're not doing anything significant, I would suggest you to remove a few of them. Instead, add a reference link mentioning the GitHub repo containing the same contents.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +```
If you're adding some important attributes, make sure to add comments/explain them.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +![Screenshot for design](/building-lyrics-search-app-using-vanilla-javascript/design-screenshot.png)
```suggestion
![Screenshot for design](/engineering-education/building-lyrics-search-app-using-vanilla-javascript/design-screenshot.png)
```

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +![Screenshot for design](/building-lyrics-search-app-using-vanilla-javascript/design-screenshot.png)
Make this change for other images as well.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +[OVH API](https://api.lyrics.ovh).
You can mention a brief overview about this API in the Introduction as well. Explain how it works in general.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +[OVH API](https://api.lyrics.ovh).
Add images or examples if necessary

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +
Explaining why we are using async and await here, would help

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +Comment out the showData function in the code snippet above (remember to uncomment the showData function), then launch the web app using the [live server vs code extension](https://marketplace.visual
Make this paragraph to bulleted points.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +![Screenshot for consoled data](/building-lyrics-search-app-using-vanilla-javascript/console-screenshot.png)
/engineering-education

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +You will be creating the search app using HTML5, CSS3, Vanilla JavaScript, async-await with fetch method, OVH API, and ECMAScript 2015 (ES6) features like arrow functions.
To this intro, add an overview of OVH API. Also, add how async and await would help and why are we using it here.

2022-01-02 12:16 UTC, srishilesh commented on content/articles/building-a-lyrics-search-app-using-vanilla-javascript/index.md
> +You will be creating the search app using HTML5, CSS3, Vanilla JavaScript, async-await with fetch method, OVH API, and ECMAScript 2015 (ES6) features like arrow functions.
If possible, rename this article with a better title.

2022-01-03 15:16 UTC, Kayere commented
Plagiarism check done ✅

2022-01-06 13:25 UTC, srishilesh commented
@shegz101 

I noticed a few commits. Are we done with the changes?

2022-01-06 15:42 UTC, shegz101 commented
@srishilesh I still have one or two things to commit , after that I should be done with the changes

2022-01-06 16:35 UTC, shegz101 commented
@srishilesh I have made the changes

2022-01-08 12:17 UTC, srishilesh commented
@shegz101 

I see a few commits after your last comment. Are you done?

I'll start my review in a while.

2022-01-08 19:03 UTC, shegz101 commented
@srishilesh I think am done now, I noticed some things that needed corrections, that's why I made some commits after last comment.

2022-01-09 08:08 UTC, shegz101 commented
@srishilesh you can proceed with your review. Thanks.

2022-01-09 14:09 UTC, srishilesh approved these changes
@shegz101 

Good work on making the changes.

Make sure to go through my commits to understand the changes.

Moving for the final review.

Thanks.

2022-01-09 14:27 UTC, shegz101 commented
@srishilesh I just went through your commits and indeed I have learnt a lot, I would improve on my next article. Thanks

2022-01-09 17:44 UTC, shegz101 commented
@srishilesh I made a commit I noticed the link to the brief intro to ovh api wasn't working. Like the one in table of content when clicked isn't taking the user to a brief intro to ovh api section, so I corrected it to work

2022-01-09 17:49 UTC, srishilesh commented
@shegz101 

Thanks for correcting it. I forgot to edit the change in the `Table of contents` section, after editing it in the sub-heading.

2022-01-09 17:55 UTC, shegz101 commented
@srishilesh Thanks

2022-01-11 09:33 UTC, ahmadmardeni1 commented
Hey @shegz101 Change your hero image please. It belongs to this app: https://lyrix.io/ And we don't have the legal right to use it.
cc @srishilesh

2022-01-11 12:35 UTC, srishilesh commented
> Hey @shegz101 Change your hero image please. It belongs to this app: https://lyrix.io/ And we don't have the legal right to use it. cc @srishilesh

@ahmadmardeni1 

Thanks for pointing that out. I didn't notice that.

2022-01-11 17:00 UTC, louisefindlay23 commented
Locate the image, remove it and then add a new one. Then commit and push the changes. You'll find the file location in the Files tab of this PR, @shegz101.

2022-01-11 17:26 UTC, shegz101 commented
@srishilesh I am still facing issues, unfortunately. I can't delete the image, it says I must be on a branch.

2022-01-11 17:37 UTC, srishilesh commented
> @srishilesh I am still facing issues, unfortunately. I can't delete the image, it says I must be on a branch.

@shegz101 

That's strange. Usually, you must checkout to the same branch that this PR is on, pull it, and make changes.

Anyway, I've done it for you this time. Make sure to do it on your own from next time.

2022-01-11 17:40 UTC, shegz101 commented
Thanks @srishilesh I would take note while writing another article

2022-01-12 14:50 UTC, louisefindlay23 commented
Should be good to review now, @ahmadmardeni1.

2022-01-13 08:04 UTC, ahmadmardeni1 commented
Good morning/evening. @shegz101 
After a quick glance:
- I've found too many grammar mistakes/unnecessary commas/etc... I've fixed some of them (be4b567) for your reference. 
- You are using the old author's file structure.
Please take your time and do the necessary changes.
cc @srishilesh

2022-01-13 09:16 UTC, srishilesh commented
> Good morning/evening. @shegz101 
> After a quick glance:
> - I've found too many grammar mistakes/unnecessary commas/etc... I've fixed some of them (be4b567) for your reference. 
> - You are using the old author's file structure.
> Please take your time and do the necessary changes.
> cc @srishilesh 

@ahmadmardeni1 

I guess I've missed out the grammar check for this article, which I usually do at last before labeling it ready for final review.

Apologies for the trouble caused during the review. From next time, will make sure I don't miss that out.

@shegz101 Please have a look at the latest structure of author file. And, check for grammar.

Ping me when done.

2022-01-13 09:27 UTC, shegz101 commented
@srishilesh Goodmorning, am on it. I will tell you when am done

2022-01-13 10:03 UTC, shegz101 commented
@srishilesh help me check if my author's file is the updated one

2022-01-13 11:13 UTC, shegz101 commented
@srishilesh am done with the changes

2022-01-19 12:21 UTC, srishilesh commented
Hey @ahmadmardeni1 ,

I believe the author has fixed all the grammar issues. And, it's ready for your final review.

Thanks.

Cc. @shegz101

2022-01-22 05:54 UTC, WanjaMIKE commented
It seems this PR has an issue and cannot render. Could you close this one and recreate a new - duplicate PR. Thanks

2022-01-22 08:04 UTC, shegz101 commented
@WanjaMIKE should I just create a new PR and tag you when done.

2022-01-22 08:14 UTC, srishilesh commented
> @WanjaMIKE should I just create a new PR and tag you when done.

@shegz101 

Yes that's right.

Create a new PR with all these commits. Ping both of us when done.

2022-01-22 08:49 UTC, shegz101 commented
@srishilesh have opened a new pr and tagged both of you

2022-01-22 08:50 UTC, shegz101 commented
Thanks

2022-01-22 09:07 UTC, closed without merging