Creating dummy data in python using faker package
section-engineering-education/engineering-education pull request #5791
Opened 2021-12-27 14:19 UTC by Dianapeter

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4951

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-30 00:46 UTC, hectorkambow commented
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2022-01-02 12:28 UTC, srishilesh requested changes
@Dianapeter 

This PR looks too low on the technical content.

There are several points that needs to be improved on, I've suggested a few of them. These were not explained or they lacked clarity. You can add examples to explain them.

Adding a example scenario of where we use them, would definitely help.

See how you can add value from what is not there in the Faker python documentation.

Since, this would require several revisions, we would be closing this PR for now. You can work on your forked repo.

You can create a new PR with all the changes, and ping me there.

Thanks.

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +For various reasons, it's essential to have phoney data on hand. In this post, dummy data is generated using the Python Faker library. It's critical to test and evaluate software and hardware with du
`For various reasons, it's essential to have phoney data on hand`

??

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +Pip install Faker
Pip?

It should be `pip`

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +#### 1. Faker generators can be created and initialized
This is not a method right? It's common to all of the them. So, don't add it as a subheading

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +You may wish to use the same collection of data again. Seeding the generator is a viable option. The following code generates dummy data using the seed() method:
Explain what seeding is, and where it is used.

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +2. Community Providers- [This](https://faker.readthedocs.io/en/stable/communityproviders.html) site has a wealth of data on locally developed service providers.
Explain them here. Don't just add reference link

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +```
I'm not sure if Section website supports other languages' alphabets. I would suggest you to replace with some other language that contains English alphabets.

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +1. In Python, Numpy's Random module can be accessed: Pseudorandom numbers can be generated with the random package. Many functions are available, including `rand()`, `randint()`, and many more.
Add examples

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +2. Fauxfactory: To test your code quickly, you can use this anytime. [Here](https://fauxfactory.readthedocs.io/en/latest/#), you may learn more about it.
Explain more about it

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +When the coefficient of an explanatory or independent variable is set to zero, it cannot affect the dependent variable. Still, the intercept will be affected when its coefficient is set to 1.
What is regression? 

`For various reasons, it's essential to have phoney data on hand` -> What are they?

Explain in-detail

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +Dummy variables are created via one-hot encoding. One of these variables must be used as the starting point to avoid perfect multicollinearity.
What is one hot encoding? What is multicollinearity?

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +With this encoding method, the categorical variable is converted into a set of binary variables. One-hot encoding employs N binary variables for N categories in a variable. Dummy encoding is an impro
Add example

2022-01-02 12:28 UTC, srishilesh commented on content/articles/creating-dummy-data-in-python-using-faker-package/index.md
> +Dummy variable traps can be avoided if you have many characteristics that are highly connected (Multicollinear). When categorical data is encoded using one-hot encoding, we can predict one dummy vari
Explain more about this. Tell where we face this scenario. Add examples.

2022-01-02 12:29 UTC, closed without merging