Threads and isolate in flutter
section-engineering-education/engineering-education pull request #5819
Opened 2021-12-29 12:38 UTC by waigwakanoi

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4136`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2021-12-30 00:43 UTC, hectorkambow commented
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

2022-01-04 17:45 UTC, BrianaNzivu requested changes
Hey @waigwakanoi  👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

On behalf of the team, I would love to apologize for the long wait in the queue. I promise to make this review as fast and as swift as possible, with your help of course 😄 .

Good job on the article. It is a very interesting read. Barely any grammar changes to be made.
This is very impressive considering you are a first-time contributor. Keep up the good work 👍 .

Just a few changes I need you to make as we continue with the preliminary revisions:
- Please structure your article according to this [sample](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md). I need you to clearly highlight and explain your steps. Where you can add more detail please do so.
- Scale down your avatar and hero image to 600 x 400 px as required. You can use [Befunky](https://www.befunky.com/) to do this.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

2022-01-05 13:06 UTC, waigwakanoi commented
@BrianaNzivu kindly reviews changes

2022-01-06 13:45 UTC, Kayere commented
Plagiarism check done ✅

2022-01-06 22:14 UTC, BrianaNzivu requested changes
Hey @waigwakanoi 👋 
Just a few more corrections to be made.

Regards.

2022-01-06 22:14 UTC, BrianaNzivu commented on content/articles/threads-and-isolates-in-flutter/index.md
> +- Introduction
The table of contents has not been linked well. It is done this way:
[Introduction](#introduction)

Do the same for the rest.

2022-01-06 22:14 UTC, BrianaNzivu commented on content/articles/threads-and-isolates-in-flutter/index.md
> +Threads and isolates are two of the essential abstractions you will need to know when developing apps in Flutter. They allow developers to utilize multicore processors, improve user experience by red
Maybe you can define what threads and isolates are.

2022-01-06 22:14 UTC, BrianaNzivu commented on content/articles/threads-and-isolates-in-flutter/index.md
> +- In the following code snippets, a comment starting with // [START isolate] means that an isolated thread is started. A comment beginning with // [END isolate] means the corresponding isolation is t
You can explain this in a better way. Talk about in this step we will be creating the states. Talk about the methods being used and then complete with the statement you have written.

2022-01-06 22:14 UTC, BrianaNzivu commented on content/articles/threads-and-isolates-in-flutter/index.md
> +### Step 4 - Serialization
of what?

2022-01-06 22:14 UTC, BrianaNzivu commented on content/articles/threads-and-isolates-in-flutter/index.md
> +### Step 5 - Provide Function
To what?

2022-01-06 22:14 UTC, BrianaNzivu commented on content/articles/threads-and-isolates-in-flutter/index.md
> +  /// Sends a message to update the counter with a value of newValue and /// with isStarting set to true if start
Have this code properly indented

2022-01-12 06:20 UTC, BrianaNzivu commented
Tech review done 👍

2022-01-12 06:30 UTC, BrianaNzivu approved these changes
Hey @waigwakanoi 👋 .

Very good job on the article. It is a very interesting read and has minimal mistakes. This is very impressive considering you are a first-time contributor 👏 .

Just a few things I'd like to point out:
- I suggest that you check out our resources page which has links to various resourceful tools for writing just to minimize the changes being made by the reviewer.
- Ensure you explain your steps clearly and also indent your code properly.
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Once again good job! 👍 

Kind Regards.

2022-01-21 19:00 UTC, merged

2022-01-21 19:01 UTC, lalith1403 commented
Amazing job, @waigwakanoi and @BrianaNzivu. Thanks for the wonderful article. Keep up the fantastic work :)

2022-01-21 19:25 UTC, hectorkambow commented
@waigwakanoi Please DM me via Slack asap. 

This article will not received a payout this period - we have no PayPal on file - and the cut off time for this period is up.

2022-01-21 19:27 UTC, hectorkambow commented
Also you may want to consider changing your avatar image (to a more professional looking one) as these articles are intended to help student jump start their developer careers and may be seen by potential employers.

2022-01-23 17:12 UTC, waigwakanoi commented
okay sir


On Fri, 21 Jan 2022 at 22:26, hectorkambow ***@***.***> wrote:

> @waigwakanoi <https://github.com/waigwakanoi> Please DM me via Slack asap.
>
> This article will not received a payout this period - we have no PayPal on
> file - and the cut off time for this period is up.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/5819#issuecomment-1018795610>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVWXVTRKDHKAQ4MK4JKDQSDUXGXMZANCNFSM5K54JVLQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/5819/c1018795610
> @github.com>
>