How to work with Observables in Angular 12
section-engineering-education/engineering-education pull request #5836
Opened 2021-12-30 08:39 UTC by owinowendy

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**
#### Pre-submission checks
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #2575

2021-12-30 08:41 UTC, jumamiller commented on content/articles/angular-observables/index.md
> +- [Table of contents](#table-of-contents)
I think you should remove these 2!

2021-12-30 08:41 UTC, jumamiller commented on content/articles/angular-observables/index.md
> +![observer response](/observer-response.png)
Fix all these image paths!

2021-12-30 08:42 UTC, jumamiller commented on content/articles/angular-observables/index.md
> +However, JavaScript has a library, RxJS (Reactive Extension for Javascript), that we can use to handle our observables.
Add link to RxJS documentation!

2021-12-30 08:43 UTC, jumamiller requested changes
Looks nice! Work on the few suggestions above and we're good!

2021-12-30 10:49 UTC, WanjaMIKE commented
Plagiarism check is done.

2022-01-03 12:06 UTC, owinowendy commented
@jumamiller changes are done!

2022-01-03 12:15 UTC, jumamiller approved these changes
Approved! Great work!

2022-01-18 15:24 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +images:
Please edit your hero image to use a capital S in the title, Subscribe to Observables.

2022-01-18 15:35 UTC, louisefindlay23 requested changes
See comments for minor flow and formatting issues. Please use the examples highlighted to review your article for other occurrences.

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +With a basic idea on observables, let's implement a sample observer class to get in-depth knowledge on how they work.
of instead of on

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +// ( 5 seconds) I have got the response!
Remove extra space between ( and 5

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +You notice from the above script that we define our class and its constructor. We then proceed to pass an argument to this constructor.
You **will** notice

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +Now that we've basic concepts of an observable in pure JavaScript let's proceed and set up our Angular 12 project.
Add a comma after JavaScript and before let's.

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +First, open terminal (Ctrl+Alt+T), and run the following commands:
open **the** terminal

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +...
Remove these dots and others like it

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +To subscribe to this observable, let's  now edit the observable component as shown below:
Remove extra space

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +import { Component, OnInit } from '@angular/core';
Remove extra space

2022-01-18 15:35 UTC, louisefindlay23 commented on content/articles/angular-observables/index.md
> +// next,create observable
Add spaces between the comma

2022-01-19 14:03 UTC, owinowendy commented
@louisefindlay23 changes done.

cc @jumamiller

2022-01-19 17:27 UTC, louisefindlay23 approved these changes
Final review complete. Congrats on your published article.

2022-01-19 17:27 UTC, merged