How to Setup the Glassmorphism Frosty Effect in a React.js App with TypeScript
section-engineering-education/engineering-education pull request #5845
Opened 2021-12-30 15:19 UTC by mosesreigns

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5694

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-03 15:23 UTC, Kayere commented
Plagiarism check done ✅

@mosesreigns - Your article seems to be too short - word count (excluding code snippets) is less than 750. Please consider adding more content to your article to meet the minimum word count.

2022-01-08 09:07 UTC, mosesreigns commented
Am on it ASAP @Kayere

2022-01-11 07:30 UTC, mosesreigns commented
@adrianmurage Check this out

2022-01-20 09:07 UTC, adrianmurage requested changes
@mosesreigns 
Your article is good but it lacks a few things:
1. The article is still shorter than the required word count (excluding code blocks). Kindly think of a way to get it up to par before requesting another review. 
2. The article has a few non-specific styles. Explicitly state to what class are these styles being applied.

2022-01-20 09:07 UTC, adrianmurage commented on content/articles/setup-glassmorphism-effect-in-reactjs-app/index.md
> +```
To what class are these styles being applied?

2022-01-20 09:07 UTC, adrianmurage commented on content/articles/setup-glassmorphism-effect-in-reactjs-app/index.md
> +```
To what class are these styles being applied?

2022-01-20 09:07 UTC, adrianmurage commented on content/articles/setup-glassmorphism-effect-in-reactjs-app/index.md
> +```
To what class are these styles being applied?

2022-01-20 09:07 UTC, adrianmurage commented on content/articles/setup-glassmorphism-effect-in-reactjs-app/index.md
> +```
To what class are these styles being applied?

2022-01-20 10:16 UTC, mosesreigns commented
@adrianmurage @Kayere Regarding the word count, I had capitalized on adding code comments instead of writing them out of the code block. What's your advice on that?

2022-01-26 16:27 UTC, adrianmurage commented
> @adrianmurage
> 
> @Kayere
> 
> Should this pull request be closed?

@hectorkambow No need, the necessary changes were made

2022-01-26 16:36 UTC, adrianmurage commented
> @adrianmurage @Kayere Regarding the word count, I had capitalized on adding code comments instead of writing them out of the code block. What's your advice on that?

I think that that should be fine. Although for a final word about that you should consult @hectorkambow

2022-01-27 07:51 UTC, ahmadmardeni1 commented
Great work team. @mosesreigns @adrianmurage

2022-01-27 07:51 UTC, merged

2022-01-28 17:12 UTC, hectorkambow commented
How to Setup the Glassmorphism Frosty Effect in a React.js App with TypeScript