How to Set up Rust API Servers with the Diseal ORM and the PostgreSQL
section-engineering-education/engineering-education pull request #5962
Opened 2022-01-07 09:11 UTC by wanjcarol

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5840

2022-01-08 06:11 UTC, jerimkaura commented
Hello @wanjcarol 

Thank you for submitting this great article. I however feel you have not included the conclusion section that provides a summary of whatever is captured in the article.  Providing this recap not only adds value to the article and its format but also comes in line with the conventional article format by section.io. 
![Screenshot from 2022-01-08 09-07-29](https://user-images.githubusercontent.com/50904889/148633705-2a93daa1-72dd-4324-aa7f-5660be2ed29b.png)

Take a look at this screenshot. Davis is providing a summary of his article which completes it well.

Let me know if you have any challenges with this.

2022-01-08 06:32 UTC, wanjcarol commented
Yes @jerimkaura , am adding that right away

2022-01-13 17:43 UTC, WanjaMIKE commented
Apart from the boiler plate code, could you @wanjcarol correct the other sentences showing plagiarism. Thanks

[New Scan 5_10 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7864822/New.Scan.5_10.PM.Copyleaks.Report.pdf)

2022-01-13 17:45 UTC, WanjaMIKE commented
@jerimkaura could you check if this article is similar to https://www.freecodecamp.org/news/building-powerful-graphql-servers-with-rust/

2022-01-14 15:09 UTC, wanjcarol commented
I have updated the sentences @WanjaMIKE

2022-01-16 20:29 UTC, jerimkaura commented
> @jerimkaura could you check if this article is similar to https://www.freecodecamp.org/news/building-powerful-graphql-servers-with-rust/

Hello @WanjaMIKE , 

I did a check on the article. They are share implementation concepts but are completely different.

2022-01-16 20:42 UTC, jerimkaura requested changes
Hello @wanjcarol 

Thanks for this article.:rocket:  I like how well you formatted the article :tada: However, there seem to be some readability issues with your article that are worth looking at. Not a problem :handshake: just countercheck keenly to address them well. I mentioned a few but not across the whole article.

Work on readability and clarity to speed up the review process.

2022-01-16 20:42 UTC, jerimkaura commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +
This paragraph is bulky, consider breaking into smaller understandable related sentences.

2022-01-16 20:42 UTC, jerimkaura commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +ORM (Object Relation Mapping) is a common technique for storing, retrieving, updating, and deleting data from a database, specifically within a relational database. Common languages such as Node.js h
Is it lines of code or lines of codes?

2022-01-16 20:42 UTC, jerimkaura commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +The concept of ORM is widely supported by many languages such as Rust. Rust uses the Diseal framework to help you write your schema queries within your rust application. In this guide, we learn more
Many Languages should be more than one, not just just a single language as mentioned.

2022-01-16 20:42 UTC, jerimkaura commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +This tutorial will help you learn more about the ORM and understand how to use ORM in Rust using Diseal. We will also create a Rust API server that uses Diseal to connect to PostgreSQL and then gener
This statement is repeated. Summarize it together with line 5

2022-01-16 20:42 UTC, jerimkaura commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +Rust uses Cargo to set up and run its applications. Cargo gets installed once the Rust compiler gets installed in your computer. To set up a basic Rust application, proceed to your desired project lo
Explain to the user what cargo is.

2022-01-18 10:54 UTC, wanjcarol commented
Check the changes @jerimkaura

2022-01-19 22:05 UTC, jerimkaura requested changes
Hello @wanjcarol :wave: 

You have a great article with good content :rocket: However, there are minor enhancements that we need to do for the clarity of the article.

Remember, it's best practice to publish well-refined articles that readers find easy to read and comprehend :blush:

I recommend that you go over the suggestions I made in the article and work on them to enhance reliability, clarity and understanding of your code snippets.

Reach out to me via slack in case you need any assistance.

Thank you!

2022-01-19 22:05 UTC, jerimkaura commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +Replace `EmptyMutation` from a schema with `MutationRoot`:
Why are we conducting this step?

2022-01-24 10:22 UTC, wanjcarol commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +Now proceed to `main.rs` and set up the HTTP server to ensure that the schema is passed and called. However, first, update the imports as follows.
In the `src` folder, create a `graphql_schema.rs` file and import `EmptyMutation` and `RootNode` from `juniper` as shown below. Then implement GraphQL schema as shown in the following steps;

I had already stated this at the begging of this `### Set up the GraphQL schema`

2022-01-24 10:40 UTC, wanjcarol commented
I have added the minor enhancements @jerimkaura

2022-01-24 13:04 UTC, jerimkaura reviewed
@wanjcarol 

Great work Proceeding to tech review.

Thanks.

2022-01-31 19:47 UTC, jerimkaura approved these changes
Hey @wanjcarol 

Great article here :tada:

Check out the changes I made to improve on future articles.

Thanks for the great work!

2022-02-01 17:49 UTC, lalith1403 commented on content/articles/how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/index.md
> +url: /how-to-set-up-rust-api-servers-with-the-diseal-orm-and-the-postgresql/
Shorten the URL. This is too long.

2022-02-01 18:30 UTC, jerimkaura commented
Hey @wanjcarol 

I renamed your article folder to shorten the URL. Please upload the images to the new folder and delete the old folder. 

Let me know if you have any difficulties via slack. @jerimkaura

2022-02-02 10:41 UTC, wanjcarol commented
@jerimkaura and @lalith1403 This should be good to go

2022-02-02 12:09 UTC, jerimkaura approved these changes
This can now be finalized @lalith1403

2022-02-02 17:45 UTC, merged