Getting Started with Support Vector Regression in Python
section-engineering-education/engineering-education pull request #5968
Opened 2022-01-07 14:10 UTC by BejaminNaibei

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4897

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-12 15:40 UTC, srishilesh commented
@BejaminNaibei 

The mathematical equations in markdown format looks incorrect. Please refer the screenshot below:

![image](https://user-images.githubusercontent.com/32015336/149172230-f3ce5a1b-5b64-408a-99fe-23bb4d868614.png)

2022-01-13 10:07 UTC, jerimkaura commented
Hello @BejaminNaibei 

Always welcome once again to EngEd, always be sure to ask Content Moderator or a peer reviewer to open the issue linked to your PR before you open the PR.

2022-01-14 16:54 UTC, srishilesh requested changes
@BejaminNaibei 

I've suggested some minor changes. Please ping me when you are done.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +Support Vector Regression, denoted as SVR, is a regression function that generalizes the finite Support Vector Machines model on a continuous-valued output. Although less popular in real-valued funct
`that generalizes the finite Support Vector Machines model on a continuous-valued output`

This statement is not easily understood by the beginners unless they have some idea about SVM. So, add 1 - 2 lines of explanation about it.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +Support Vector Regression, denoted as SVR, is a regression function that generalizes the finite Support Vector Machines model on a continuous-valued output. Although less popular in real-valued funct
Also, in the intro make sure to add why we are learning about SVR, and what are we going to learn in this article.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +### Prerequsites:
```suggestion
### Pre-requisites
```

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +- Ordinary Least Squares method
Add a reference link

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +To understand how the SVR model works, let's first recap the simple linear regression. In linear regression, we represent the regression line as:
While recapping, please use a definition or explain it in words before directly jumping into visual representation using graphs.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +dataset = pd.read_csv('/content/drive/MyDrive/Position_Salaries.csv')
Add a reference link from where the dataset can be downloaded

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +### Output:
Did you miss adding the printed output?

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +It's seen from the output above that the y_p variable is a vector, i.e., a 1D array. Also, we need to note that the values of y_p are huge compared to x_l. Therefore, if we implement a model on this
Making them as bulleted points would look better and make it easier for the reader to read.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +The next thing we will do is to import the `StandardScalar` class and get our X_l and y_p variables scaled separately to the same range.
Adding 1 - 2 lines more about standard scaler and its working would help

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +As we can see from the obtained output, both variables were scaled within the range -3 and +3.
```suggestion
As we can see from the obtained output, both variables were scaled within the range `-3` and `+3`.
```

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +The plot shows a nonlinear relationship between the `Levels` and the `Salary`. Therefore, we will use a kernelized version of the SVR model.
`kernelized version of the SVR model`

Explain more about this

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +To implement our model, first, we need to import it from the sk-learn and create an object to itself. Since we declared our data to be nonlinear, we will pass a kernel as `rbf`, which stands for, *Ra
What is RBF? Explain in a few words and add necessary links.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +A
Use print statements. The reader may or may not not be running in jupyter notebook cells

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +We need to note that the predicted values are returned in 1D array. However, we had reshaped our study variable into 2D array. So, for any predicted value to correspond with such a new dimension, it
Why are we exactly transforming 1D to 2D array? It can be more descriptive here. It's not very clear.

2022-01-14 16:54 UTC, srishilesh commented on content/articles/support-vector-regression-in-python/index.md
> +
Add a GitHub repo URL containing full source code

2022-01-17 12:24 UTC, srishilesh commented
Hello @BejaminNaibei ,

Just checking if we have got any updates here. Ping me if you need any help.

Thanks.

2022-01-17 19:35 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-20 16:49 UTC, srishilesh commented
@BejaminNaibei 

I'm closing this PR for now. You work on these changes in your forked repository and create a new PR with all the suggested changes.

Ping me when you're done.

2022-01-23 17:39 UTC, srishilesh commented
@BejaminNaibei 

Do we have any updates?

2022-01-28 06:24 UTC, BejaminNaibei commented
Hello @srishilesh.
You had close this PR #5968 due to delayed revision. I was occupied with some exams and that's why i couldn't manage to do the revision on time. Right now am done with all changes you requested and I'm requesting if you may reopen the PR for submission again.

2022-01-29 07:07 UTC, srishilesh commented
Reopening the PR, since the author was occupied with school exams and the PR has very minor revisions to be made.

2022-01-29 07:07 UTC, srishilesh commented
@BejaminNaibei 

You may push your changes now.

2022-01-29 12:33 UTC, BejaminNaibei commented
@srishilesh 
changes are done

2022-01-31 15:11 UTC, srishilesh commented
Starting my final review now.

2022-01-31 15:12 UTC, srishilesh commented
@BejaminNaibei 

Until I do my final review, can you add a hero image with dimensions 600x400?

2022-02-02 19:46 UTC, BejaminNaibei commented
hero image uploaded

2022-02-02 19:55 UTC, hectorkambow commented
@srishilesh 
During your final review - if any other changes are needed we will be closing the PR 👍

2022-02-03 14:00 UTC, srishilesh commented
Apologies for the delay. I'll complete my final review by today.

2022-02-03 18:16 UTC, srishilesh approved these changes
@BejaminNaibei ,

Great work! You have explained the concepts very well.

But, you would have to improve on the markdown formatting changes and few other flow changes. Make sure to go through my commits to understand them.

Moving for the final review.

Thanks.

2022-02-04 17:37 UTC, lalith1403 commented
Jumping on this one 🚀

2022-02-04 18:17 UTC, lalith1403 commented
@srishilesh Please consider adding the MathJax script when latex equations are used. 

Thanks for a great article @BejaminNaibei. Thank you for the review @srishilesh

2022-02-04 18:18 UTC, merged