Quantum Ai
section-engineering-education/engineering-education pull request #5994
Opened 2022-01-09 10:44 UTC by Romans70

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5735

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-09 14:25 UTC, raboba2re commented
@ahmadmardeni1  i will like to review this article

2022-01-10 15:21 UTC, WanjaMIKE commented
There appears to be numerous sentences showing plagiarism. Please check the report and correct them. Thanks

[New Scan 3_12 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7839830/New.Scan.3_12.PM.Copyleaks.Report.pdf)
s

2022-01-10 18:06 UTC, Romans70 commented
Plagiarism changes done @WanjaMIKE

2022-01-15 12:39 UTC, srishilesh commented
@raboba2re 

Looks like the plagiarism check is done. You may proceed with your preliminary review.

2022-01-15 16:33 UTC, raboba2re commented
@srishilesh  Thank you, I will go on with the review right away.

2022-01-15 19:12 UTC, raboba2re reviewed
Below your conclusion, please add a **Further reading** section and provide links to related articles for your reader. 
Please tag me when you are done.

2022-01-15 19:12 UTC, raboba2re commented on content/articles/quantum-ai/index.md
```suggestion
1. Construct a quantum data collection: Tensors represent quantum data. Cirq quantum network generates quantum data. TensorFlow controls all the activities on the system creating a quantum database.

2. Assess the quantum neural system design: Cirq can be used to design a quantum neural system that will then be embedded in a TensorFlow computing structure. Customized quantum systems may be chosen from many groups depending on the quantum's data nature. 
The model's purpose is to use quantum computation to retrieve information concealed in a usually entangled form. The quantum model frees the incoming quantum data. It then retains the concealed information stored in classical associations. Hence available to localized measures and classical post-processing.

```

2022-01-15 19:12 UTC, raboba2re commented on content/articles/quantum-ai/index.md
Can you please tell your reader the meaning of **Cirq** or embed a link to an article that talks about it for your reader to learn more about it.

2022-01-16 10:02 UTC, Romans70 commented
@raboba2re, all requested changes made.

2022-01-18 19:40 UTC, raboba2re commented on content/articles/quantum-ai/index.md
```suggestion
1. Construct a quantum data collection - Tensors represent quantum data. [Cirq quantum network](https://quantumai.google/cirq)  generates  this quantum data and TensorFlow controls all the activities on the system creating a quantum database.

```

2022-01-18 19:40 UTC, raboba2re commented on content/articles/quantum-ai/index.md
>  2. Assess the quantum neural system design - Cirq can be used to design a quantum neural system that will then be embedded in a TensorFlow computing structure. Customized quantum systems may be chose
```suggestion
2. Assess the quantum neural system design - Cirq can be used to design a quantum neural system that will then be embedded in a TensorFlow computing structure. Customized quantum systems may be chosen from many groups depending on the quantum's data nature. 
The model's purpose is to use quantum computation to retrieve information concealed in an entangled form. The quantum model frees incoming quantum data and then retains the concealed information stored in classical associations. Hence available to localized measures and classical post-processing.
```

2022-01-18 19:40 UTC, raboba2re commented on content/articles/quantum-ai/index.md
>  At the moment, a typical home computer is incapable of processing enormous volumes of data at once. Quantum computers may be capable of reaching into a database. It accesses all things at once, and d
```suggestion
At the moment, a typical home computer is incapable of processing enormous volumes of data at once. Quantum computers may be capable of reaching into a large database and delivering an evaluation in seconds, with this we can discover patterns within a short period of time using quantum technology.
```

2022-01-18 19:40 UTC, raboba2re commented on content/articles/quantum-ai/index.md
> +For further reading you can go through the following:
```suggestion

```

2022-01-18 19:40 UTC, raboba2re commented on content/articles/quantum-ai/index.md
> +* [Quantum's AI breakthroughs](https://www.captechu.edu/blog/recent-breakthroughs-quantum-ai)
```suggestion
* [Google's Quantum AI](https://quantumai.google/)
* [Quantum Trading bot](https://quantum-ai.io/)
* [Quantum's AI breakthroughs](https://www.captechu.edu/blog/recent-breakthroughs-quantum-ai) 
```

2022-01-22 11:48 UTC, srishilesh commented
Hey @raboba2re ,

I believe the author has made the requested changes.

You may proceed with the tech review. If you find any more revisions to be made, do not hesitate to close the PR and ask the author to make ready to be published PRs.

Closing PRs helps clearing the backlog - allowing the peer-reviewers and CMs to provide faster reviews for publishing them.

Let me know if you need any help.

Thanks.

2022-01-22 14:49 UTC, raboba2re commented
@srishilesh  on it Sir.
cc @Romans70

2022-01-23 11:39 UTC, Romans70 commented
Added author page @raboba2re

2022-01-23 12:23 UTC, raboba2re commented on content/authors/Carlos-Kahuru/author.md
> +Carlos Kaharu is a student at Meru University. Developing  Artificial Intelligence software and applications that a particular business might use is what I'm always interested in. To program systems
Carlos Kaharu is a student at Meru University. Developing  Artificial Intelligence software and applications that a particular business might use is what I'm always interested in. To program systems that will change to suit the business’s needs based on the data collected and analyzed is the main goal.

2022-01-23 12:23 UTC, raboba2re commented on content/authors/Carlos-Kahuru/author.md
> +Carlos Kaharu is a student at Meru University. Developing  Artificial Intelligence software and applications that a particular business might use is what I'm always interested in. To program systems
```suggestion
Carlos Kaharu is a student at Meru University. Carlos is interested in developing Artificial Intelligence softwares and applications for businesses to suit their needs. He spends most of his time learning about AI and writing technical articles. 
```

2022-01-24 08:24 UTC, ahmadmardeni1 commented
Hey @Romans70 Please use our [author's template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md). [This is](https://github.com/section-engineering-education/engineering-education/blob/master/content/authors/Apondi-Ashley/index.md) an example.

2022-01-28 10:39 UTC, Romans70 commented
I have made the change @ahmadmardeni1 
cc: @raboba2re

2022-01-31 15:18 UTC, hectorkambow commented
@raboba2re @ahmadmardeni1  

Any update on this PR - if any other edits are needed - lets go ahead and close this 👍

2022-01-31 16:32 UTC, ahmadmardeni1 commented
He has updated the author file. Can you proceed with the tech review? @raboba2re

2022-02-01 07:19 UTC, raboba2re reviewed
@Romans70  Please approve these suggestions so that we can move your article to final review.

2022-02-01 07:19 UTC, raboba2re commented on content/articles/quantum-ai/index.md
> +* Quantum [Trading bot](https://quantum-ai.io/)
```suggestion
* [Google's Quantum AI](https://quantumai.google/)
* [Quantum Trading bot](https://quantum-ai.io/)
```

2022-02-01 07:19 UTC, raboba2re commented on content/articles/quantum-ai/index.md
> +The workable goal for quantum AI developers is to build quantum algorithms that outperform.
```suggestion
The workable goal for quantum AI developers is to build quantum algorithms that out perform classical computer algorithms.
```

2022-02-01 11:51 UTC, Romans70 commented
@raboba2re  I've made the requested changes

2022-02-01 12:34 UTC, raboba2re commented
@ahmadmardeni1  this article is ready for final review

2022-02-01 13:56 UTC, srishilesh requested changes
Hey @raboba2re @Romans70 ,

I don't think it's ready for final review yet. We have few more changes to make:

- Rename the article directory to a more descriptive name
- Start markdown headers with `###`
- Use only lowercase letters separated by `-` for all directory names
- Remove any additional new lines
- Use `-` for bulleted points.
- Perform a grammar check (I noticed a few grammatical and punctuation errors)

@raboba2re Have a look at other approved/merged PRs to see how peer reviewers have reviewed PRs, and how they've formatted the articles. I've purposefully left out a few suggestions. So, go through them and make sure to suggest them to the author.

Thanks.

2022-02-01 13:56 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +
@raboba2re Can you request the author to add front-matter on behalf of you? Or you can post them as a comment, I'll add it for you.

2022-02-01 13:56 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +* Quantum's AI Crypto Bot
Use `-` instead of `*`

2022-02-01 13:56 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +#### Table of contents
Start with markdown headers from `###`

2022-02-01 13:56 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +4. Quantum computing surpasses classical computing in intriguing AI applications.
Remove additional new lines

2022-02-01 13:56 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +* [Quantum's AI breakthroughs](https://www.captechu.edu/blog/recent-breakthroughs-quantum-ai)
Use `-`

2022-02-01 15:32 UTC, ahmadmardeni1 commented
Great comment. Thank you @srishilesh

2022-02-02 08:16 UTC, raboba2re commented on content/articles/quantum-ai/index.md
>  4. Quantum game theory is a model-based procedure used in AI uses.   The quantum game theory is an extended version of this theory to the quantum field. It can be an exciting tool for solving vital i
This paragraph is difficult to understand. There is a tautology here.

2022-02-02 08:16 UTC, raboba2re commented on content/articles/quantum-ai/index.md
> +At the moment, a typical home computer is incapable of processing enormous volumes of data at once. Quantum computers may be capable of reaching into a large database and delivering an evaluation in
```suggestion
At the moment, a typical home computer is incapable of processing enormous volumes of data at once. Quantum computers may be capable of reaching into an extensive database and delivering an evaluation in seconds; with this, we can discover patterns within a short period using quantum technology. 
```

2022-02-02 08:16 UTC, raboba2re commented on content/articles/quantum-ai/index.md
>  The site is overlooked by blockchain to enhance its user's security. It uses the blockchain version of Smart Contracts. It provides a streamlined dispute resolution mechanism.
```suggestion
The site uses blockchain's version of Smart Contract to enhance its user's security and it also provides a streamlined dispute resolution mechanism.
```

2022-02-02 18:05 UTC, Romans70 commented
@raboba2re @srishilesh I've made the requested changes

2022-02-02 19:48 UTC, hectorkambow commented
@raboba2re  @srishilesh  If any other edits are needed - we will be closing this PR. 👍

2022-02-03 16:09 UTC, srishilesh commented
Hey @raboba2re,

Please verify the changes done by the author.

2022-02-04 15:55 UTC, raboba2re commented
@srishilesh  He has made the changes.

2022-02-06 19:49 UTC, hectorkambow commented
@srishilesh  Any update on this?  

Upon a glance this article seems rather light on substance. 🤔

2022-02-06 19:49 UTC, hectorkambow commented
If any other edits are needed ... lets go ahead and close the article

2022-02-07 07:16 UTC, srishilesh requested changes
Hey @Romans70 ,

The formatting changes looks good now. Although, it has a few typos and grammatical errors to be taken care of.

As @hectorkambow mentioned it looks a little low on content. I've pointed out several instances where this article could be improved. These facts that you've stated are not backed by proper research or citations. Moreover, you haven't explained many concepts in-detail - which makes it not very beginner friendly.

Therefore, we will be closing this PR allowing you to polish this article.

Thanks.

cc. @raboba2re @hectorkambow

2022-02-07 07:16 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +6. Examine Gradients & Upgrade Parameters - After examining the cost function, the pipeline's available parameters should be adjusted in a way that reduces the cost. Gradient descent is the known way
There are so many terminologies that could be explained in-detail. Without that the beginners will find it difficult to understand the context and concepts

2022-02-07 07:16 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +- Classical decision issues are stated in decision trees, and quantum methods for decision problems are based on them. Forming branches from particular places is one way to get at the solutions. The
State existing works. How Quantam computing helps improve it? Any existing products that we have? How would the performance be?

State them with examples.

2022-02-07 07:16 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +6. Examine Gradients & Upgrade Parameters - After examining the cost function, the pipeline's available parameters should be adjusted in a way that reduces the cost. Gradient descent is the known way
Do we have any resources that validates or verifies these steps?

2022-02-07 07:16 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +4. Quantum computing surpasses classical computing in intriguing AI applications.
Explain more about these. These milestones doesn't look very specific to Quantam AI - it looks more generalized.

Only way to go about it, is to validate your points with right resources and explanations.

2022-02-07 07:16 UTC, srishilesh commented on content/articles/quantum-ai/index.md
> +The Quantum-based robot performs all the work for you since it is automated. To get started, create a free Quantum AI account. After you sign up, you'll have access to Quantum AI's pro services, whic
I think this could be a new topic altogether. We could focus and add in-depth explanations about other quantam concepts.

2022-02-07 07:16 UTC, closed without merging

2025-11-20 00:48 UTC, kmk142789 approved these changes