An Absolute Beginner Guide to Run your React Native Apps with Typescript
section-engineering-education/engineering-education pull request #6016
Opened 2022-01-10 18:01 UTC by kimkimani

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5851

2022-01-13 17:57 UTC, WanjaMIKE commented
In your TypeScript objects, please use original content rather than the current ones. They are showing a high level of plagiarism. Thanks

[New Scan 5_49 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7864929/New.Scan.5_49.PM.Copyleaks.Report.pdf)

2022-01-13 18:22 UTC, Jethro-magaji commented
> In your TypeScript objects @kimkimani , please use original content rather than the current ones. They are showing a high level of plagiarism. Thanks
> 
> [New Scan 5_49 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7864929/New.Scan.5_49.PM.Copyleaks.Report.pdf)

@kimkimani Make the edits so that I can carry on with the review process.

2022-01-16 00:41 UTC, Jethro-magaji commented
Hi @kimkimani 
Well done for coming up with such an amazing article but however, there're a few grammatical errors. Please use 2nd person singular "You" instead of "We", also I highly suggest you use tools like [Grammarly](https://grammarly.com/) and [ProWritingAid ](https://prowritingaid.com/Free) to edit your work.
Make these changes and I will continue the review process.
Thanks.

2022-01-19 22:45 UTC, Jethro-magaji requested changes
Hi @kimkimani 
Well done for the edits. However, please make these minor changes.
Thanks.

2022-01-19 22:45 UTC, Jethro-magaji commented on content/articles/guide-to-run-react-native-app-with-typescript/index.md
> +React Native runs of JavaScript by default. However, to leverage Typescript's advantages (a superset of JavaScript) offers, it is possible to set up your whole React Native apps to run entirely on Ty
React Native runs of JavaScript by default; Do you mean "runs on" or "runs of"? I think it should be "runs on".

2022-01-19 22:45 UTC, Jethro-magaji commented on content/articles/guide-to-run-react-native-app-with-typescript/index.md
>  ### Requirements
Please rename it to "Pre-requisites".

2022-01-19 22:45 UTC, Jethro-magaji commented on content/articles/guide-to-run-react-native-app-with-typescript/index.md
> +This guide walked you through a reflective introduction to Typescript and React Native. For better understanding, we have created a whole application that uses React Native to run the Typescript code
Include any next or final steps summarizing the tasks the audience just completed with possible next steps.
Also, include a link to the Github repo or live site, if you can.

2022-01-24 09:26 UTC, kimkimani commented
@Jethro-magaji Check this out

2022-01-30 01:08 UTC, Jethro-magaji approved these changes
Hi! @kimkimani 
Well done for such an amazing, please take note of the reviews I made and effect them in your next article to minimize revisions next time. 
Thanks.

2022-02-02 11:44 UTC, WanjaMIKE commented
Merged #6293 into master

2022-02-02 11:45 UTC, merged

2022-02-04 14:33 UTC, WanjaMIKE commented
@Jethro-magaji ensure that you put the correct author name in the front matter.

2022-02-04 14:49 UTC, Jethro-magaji commented
> @Jethro-magaji ensure that you put the correct author name in the front matter.

Noted, thanks