Understanding and implementing graphs in java
section-engineering-education/engineering-education pull request #6021
Opened 2022-01-11 09:31 UTC by terry254

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #3569 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-12 06:39 UTC, WanjaMIKE commented
Apart from the boilerplate code, there appears to be numerous sentences showing plagiarism. Please correct them. Thanks

[New Scan 6_27 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7852255/New.Scan.6_27.AM.Copyleaks.Report.pdf)

2022-01-12 13:16 UTC, terry254 commented
Hello @WanjaMIKE I have made the changes. 
cc: @BrianaNzivu

2022-01-12 13:17 UTC, terry254 commented
Hello @WanjaMIKE I have made the changes. 
cc: @BrianaNzivu

2022-01-12 17:27 UTC, WanjaMIKE commented
Apart from the boiler plate code, there appear to be several sentences showing plagiarism. Please correct them. Thanks

[New Scan 5_02 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7856546/New.Scan.5_02.PM.Copyleaks.Report.pdf)

2022-01-12 17:28 UTC, WanjaMIKE commented
@BrianaNzivu could you check if this article is similar to:
https://www.softwaretestinghelp.com/java-graph-tutorial/
and
https://www.javatpoint.com/java-graph

2022-01-12 18:26 UTC, terry254 commented
@WanjaMIKE I have fixed the issue.
CC: @BrianaNzivu

2022-01-17 19:35 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-26 06:29 UTC, BrianaNzivu requested changes
Hey @terry254   👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

Good job on the article. It is a very interesting read.

Just a few changes I need you to make as we continue with the preliminary revisions. 

In case of any question or help needed please do not hesitate to ping me here or on Slack.
Also, notify me when you are done.

Regards.

2022-01-26 06:29 UTC, BrianaNzivu commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +In this case, the adjacency list is defined by the class `Plot`, which is an instance of `Chart`. Generating, updating and searching
These statements are unclear.

2022-01-26 06:29 UTC, BrianaNzivu commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +private int Apexes;
Make sure your code is properly indented.

2022-01-26 06:29 UTC, BrianaNzivu commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +System.out.print(rnode+" ");
Ensure your code is properly indented.

2022-01-26 14:39 UTC, terry254 commented
Hello, @BrianaNzivu I have done the changes you requested. Thank you.

2022-01-31 16:49 UTC, BrianaNzivu commented
Tech review done 👍

2022-02-01 17:57 UTC, BrianaNzivu approved these changes
Hey @terry254  👋 .

Very good job on the article. It is a very interesting read👏 .

Just a few things I'd like to point out:
- You check out our resources page which has links to various resourceful tools for writing just to minimize the changes being made by the reviewer.
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards

2022-02-04 14:47 UTC, WanjaMIKE commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +There are possibilities of storing information in a java data structure graph. The idea of a graph depicts a network that links several different points in time.
Use *Java* rather than *java* - correct all instances.

2022-02-04 14:48 UTC, WanjaMIKE commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +While covering graph data structure, we will learn about the various types of graphs, their implementation, and traversal over the graph. We will also cover the fundamental principles as a data struc
The word *Graph* appears numerous times in the above sentence - rephrase.

2022-02-04 14:57 UTC, WanjaMIKE commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +A graph data structure holds data related to a network of people or cities. It is made up of nodes known as vertices. The formation of the linkages is a connection of a vertex to another forming edge
A graph data structure holds data related to a network of `people` or `cities`  -  is not limited to these two.

2022-02-04 14:57 UTC, WanjaMIKE commented on content/articles/understanding-and-implementing-graphs-in-java/index.md
> +1. Directed graphs: The graph's edges show the graph's orientation. Instead of using lines, a directed graph uses arrows (edges). The direction of a node's path is indicated by its arrow. We may eith
The graph's edges show the graph's orientation  - Rephrase

2022-02-04 14:58 UTC, WanjaMIKE commented
It seems this PR is still quite a bit aways from being completed. It also seems this PR is rather light on substance. We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer.

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue. 👍 Be sure to consult previously published materials to get a better understanding of the level of quality the community expects.

Please feel free to go through our provided resources as well - those are there to help all our students improve their overall technical writing. To be able to take those skills to any position or program.

2022-02-04 14:58 UTC, closed without merging