Introduction to handles and handle pruning in compiler design
section-engineering-education/engineering-education pull request #6022
Opened 2022-01-11 10:52 UTC by root5086

### Article checklis

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?.

`This fixes #5808

2022-01-16 22:38 UTC, Jethro-magaji requested changes
Hi @root5086 
Well done for coming up with such an amazing article. However, there are a few corrections you need to make, please go over my reviews and make the corrections.
I suggest you run your article on tools like Grammarly and ProwritingAid to edit your work.
Thanks.

2022-01-16 22:38 UTC, Jethro-magaji commented on content/articles/handle-and-handle-pruning/index.md
> +### Conclusion
Please summarize what you have done in the article here.

2022-01-16 22:38 UTC, Jethro-magaji commented on content/articles/handle-and-handle-pruning/index.md
> +The reader should have a prior understanding of the following concept:
Use 2nd person singular here "You". instead of "The reader".

2022-01-17 19:38 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-18 06:47 UTC, root5086 commented
@Jethro-magaji .....Corrections made.

2022-01-20 00:05 UTC, Jethro-magaji requested changes
Hi @root5086 
Well done for the edits. However, please make these minor changes, also explain each block of code below it.

2022-01-20 04:45 UTC, root5086 commented
Hi @Jethro-magaji ...the updates have been made...thanks

2022-01-21 01:42 UTC, Jethro-magaji approved these changes
Hi @root5086 !
Well done for the awesome article, please take note of the reviews next time you submit an article.
Thanks, overall it's a great article.

2022-02-07 21:15 UTC, hectorkambow commented
jumping on this one

2022-02-07 21:36 UTC, merged