Simulating a Simple Epidemic Spreading Process on Graphs with Julia
section-engineering-education/engineering-education pull request #6046
Opened 2022-01-12 15:39 UTC by csamuelsm

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5972

2022-01-17 19:39 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-18 00:28 UTC, Jethro-magaji requested changes
Hi @csamuelsm 
Well done for such an amazing article. However, there're a few corrections you need to make based on my reviews.
Please, run your article on tools like Grammarly and ProWritingAid for better editing.
Thanks.

2022-01-18 00:28 UTC, Jethro-magaji commented on content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/Simulating a Simple Epidemic Spreaging Process on  40a38af8bf6a4743a874f9bdcc487a61.md
> +```julia
Explain every block of code at the end for better understanding, do this for every instance that's necessary.

2022-01-18 12:33 UTC, csamuelsm commented
@Jethro-magaji revisions done!

2022-01-20 01:59 UTC, Jethro-magaji commented on content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/Simulating a Simple Epidemic Spreaging Process on  40a38af8bf6a4743a874f9bdcc487a61.md
> +Package installation is done, now let’s open Jupyter-lab:
Although using "We" conveys the idea of learning together. Using the "You" perspective allows the writer to make a connection with his or her audience by focusing on the reader. It goes a step further by creating an interactive literary experience, bringing the reader into the story.

You can adjust this for some instances where "You" can replace "We".

2022-01-20 02:04 UTC, Jethro-magaji requested changes

2022-01-20 02:04 UTC, Jethro-magaji commented on content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/Simulating a Simple Epidemic Spreaging Process on  40a38af8bf6a4743a874f9bdcc487a61.md
>  end
The code above isn't properly formated. Please check other code blocks that need formatting and edit them.

2022-01-20 13:09 UTC, csamuelsm commented
@Jethro-magaji the code formatting problems are because of my marktext editor, it was not the first time this happened. I will not use it anymore! Anyway, the corrections are done!

2022-01-23 01:37 UTC, Jethro-magaji commented
> @Jethro-magaji revisions done!

Hi @csamuelsm 
I just noticed that your images are not properly formatted in the link.
Here's an example of the right formatting style "![Simulator-interface](/engineering-education/implementing-africa-talking-sms-api-using-nodejs/simulator-interface.png)"

2022-01-23 11:18 UTC, csamuelsm commented
@Jethro-magaji Sorry, it was my first time using images in an article. Thank you for pointing that out! The corrections are done!

2022-01-23 15:20 UTC, Jethro-magaji approved these changes
Hi! @csamuelsm 
Well done for coming up with such an amazing article. Please take note of the corrections I made, to minimize revision for your next article and also read the EngEd [docs](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors).
Thanks.

2022-02-07 22:33 UTC, hectorkambow commented
jumping on this

2022-02-07 23:00 UTC, hectorkambow commented
@csamuelsm Thank you for your patience (as we have recently seen an influx with PR coming in). 

👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review. 
 
cc @Jethro-magaji Please do the same 👍

2022-02-07 23:02 UTC, merged

2022-02-07 23:28 UTC, Jethro-magaji commented
> @csamuelsm Thank you for your patience (as we have recently seen an influx with PR coming in).
> 
> 👍 overall nice work - very detailed and straight forward tutorial
> 
> Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.
> 
> cc @Jethro-magaji Please do the same 👍

Alright, noted. Thanks.