Solutions to Django Common Errors in Web Development
section-engineering-education/engineering-education pull request #6052
Opened 2022-01-12 19:16 UTC by OkothAlvan

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-14 14:49 UTC, srishilesh commented
@OkothAlvan 

Welcome to EngEd community!

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.

Thanks.

2022-01-18 01:06 UTC, Jethro-magaji requested changes
Hi @OkothAlvan 
Well done for such an amazing article. However, there're a lot of corrections you need to make.
Please, run your article on tools like Grammarly and ProWritingAid for better editing.
We will be closing this PR to allow you to polish the article.
Visit the EngEd new contributor's docs [here](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to guide you.
Thanks.

cc @section-engineering-education/content-moderator-team please close this PR

2022-01-18 02:17 UTC, OkothAlvan commented on content/articles/solutions-to-django-common-errors-in-web-development/index.md
> +## **Introduction**
Hi @Jethro-magaji 
What happens after I will be done with the revisions if the PR is closed?

2022-01-18 04:56 UTC, srishilesh commented
> Hi @OkothAlvan Well done for such an amazing article. However, there're a lot of corrections you need to make. Please, run your article on tools like Grammarly and ProWritingAid for better editing. We will be closing this PR to allow you to polish the article. Visit the EngEd new contributor's docs [here](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to guide you. Thanks.
> 
> cc @section-engineering-education/content-moderator-team please close this PR

@Jethro-magaji 

You may point out all the corrections to be made, and close the PR by yourself.

2022-01-18 05:31 UTC, OkothAlvan commented
Noted. Thank you.

On Tue, Jan 18, 2022, 7:56 AM Srishilesh P S ***@***.***>
wrote:

> Hi @OkothAlvan <https://github.com/OkothAlvan> Well done for such an
> amazing article. However, there're a lot of corrections you need to make.
> Please, run your article on tools like Grammarly and ProWritingAid for
> better editing. We will be closing this PR to allow you to polish the
> article. Visit the EngEd new contributor's docs here
> <https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors>
> to guide you. Thanks.
>
> cc @section-engineering-education/content-moderator-team
> <https://github.com/orgs/section-engineering-education/teams/content-moderator-team>
> please close this PR
>
> @Jethro-magaji <https://github.com/Jethro-magaji>
>
> You may point out all the corrections to be made, and close the PR by
> yourself.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/6052#issuecomment-1015070735>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDCMYVBHUTKS4RHRR4RLMLUWTXHFANCNFSM5LZY6CHA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/6052/c1015070735
> @github.com>
>

2022-01-18 06:09 UTC, closed without merging