Adding permissions to flutter apps
section-engineering-education/engineering-education pull request #6061
Opened 2022-01-13 12:40 UTC by jasminemilito

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5833 `

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-14 15:00 UTC, srishilesh commented
@jasminemilito 

Welcome to EngEd community!

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.

To avoid potential closure of the PR:
- Perform a grammar check
- Make sure the hero image is of dimension 600x400
- Start markdown headers from `###`
- Go through the markdown guidelines that we follow here, by referring to our contribution guidelines
- For using bulleted points, use - instead of *
- For code snippets, make sure to explain them properly or add comments wherever needed
- The image paths are correct
- The author info is correct (Refer to the guidelines to view the latest update in author info section)
- The directory names are in lower case, separated by `-`

We also suggest you to go through other approved PRs to see how the authors have formatted their articles.

Thanks.

2022-01-18 01:44 UTC, Jethro-magaji requested changes
Hi @jasminemilito 
Well done for such an amazing article. However, there're a lot of corrections you need to make.
Please, run your article on tools like Grammarly and ProWritingAid for better editing.
We will be closing this PR to allow you to polish the article.
Visit the EngEd new contributor's docs [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md) to guide you.
Thanks.

2022-01-18 01:44 UTC, Jethro-magaji commented on content/articles/adding-permission-to-flutter-apps/index.md
> +The first important thing to know is that the android system uses permissions. You can for example for your app to be able to use the internet or access the camera.
Please edit this paragraph again, it has some typos.

2022-01-18 01:44 UTC, Jethro-magaji commented on content/articles/adding-permission-to-flutter-apps/index.md
> +I will write my application so that the user has to accept permissions when he wants them. Users have an option to see all installed apps and select which one can see your camera.
Use 2nd person singular "You" instead of "I, we, or let", correct this for all instances.

2022-01-18 01:44 UTC, Jethro-magaji commented on content/articles/adding-permission-to-flutter-apps/index.md
> +### Prerequisite
These don't sound like prerequisites.
Please follow this doc [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md) for guidance.

2022-01-18 04:54 UTC, srishilesh commented
> Hi @jasminemilito Well done for such an amazing article. However, there're a lot of corrections you need to make. Please, run your article on tools like Grammarly and ProWritingAid for better editing. We will be closing this PR to allow you to polish the article. Visit the EngEd new contributor's docs [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md) to guide you. Thanks.
> 
> cc @section-engineering-education/content-moderator-team please close this PR

@Jethro-magaji 

Please point out all the major suggestions to be made. And, ask the author to refer the resources for more information or refer other published articles for understanding the format.

As a peer-reviewer, you have permissions to close the PR by yourself.

2022-01-18 16:13 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-24 02:00 UTC, Jethro-magaji requested changes
Hi! @jasminemilito 
For the sake of your first time, I have decided to continue the review process, to help you understand the quality of content we need.
Please go over my last review and this one to guide you. 
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/5924/commits/c081a0c67bd777e21d60815634c955e5565d9f00) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd slack channel.
Thanks.

2022-01-27 00:25 UTC, Jethro-magaji commented
Hi! @jasminemilito 
Are you done with the editing?
I noticed your avatar image isn't a proper headshot, please check it out and fix it.

2022-01-31 15:15 UTC, hectorkambow commented
Good afternoon and thank you for submitting your topic to the EngEd program and jumping on your revisions. 
As a rule of thumb - we can only accept articles (pull requests) that are fully polished and complete articles - articles that are ready to be published.
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue).

2022-01-31 15:15 UTC, closed without merging