Understanding Computer network services
section-engineering-education/engineering-education pull request #6067
Opened 2022-01-13 15:08 UTC by gorleroy

### Article checklist

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4993

2022-01-13 18:33 UTC, WanjaMIKE commented
Plagiarism check is done.

2022-01-14 12:08 UTC, mbaabuones requested changes
@gorleroy Thank you for submitting your first article. I take this opportunity to welcome you to the Section Engineering program. Your article is informative and easy to understand. However, the article needs some changes to meet the threshold for publication. Please go through the following points keenly and revise the article accordingly. 
* As a first time contributor, you are required to upload your author bio and photo (named avatar) in the **authors** folder situated in the **contents** folder. 
* Please revisit [this folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to familiarize yourself with all the contribution guidelines.
* The introduction paragraphs and conclusion of this article can be optimized. Please go through the [published articles](https://www.section.io/engineering-education/) to see how authors have structured their articles. The published articles will help you gain an overview of the desired quality. 
* There are some grammatical errors in the article. Use Grammarly.com to check and correct these errors. 
* Please address the specific comments pointed out in the article. 
This PR will be closed so that you can work on all the comments outside the queue. This will allow other ready articles to be processed. Please make sure all the suggested changes are made. When you finish working on the changes, open a new PR and indicate in the subject line that it is a duplicate. Ping me when you do this. Please note that if there are further changes needed after opening a duplicate PR, it will be closed again. To avoid this, ensure you have addressed all the highlighted issues. 

NB: Ensure you proofread the article when you finish revising it. Fix any other error, typo, or flow issue in the article.

2022-01-14 12:08 UTC, mbaabuones commented on content/articles/computer-network-services/index.md
> +It is an approach to manage network services and resources That is; automating configuration, testing, maintenance, provision, management, and operation of a network and its’ devices both virtual and
Revise this sentence. Please avoid such errors.

2022-01-14 12:08 UTC, mbaabuones commented on content/articles/computer-network-services/index.md
> +
Introduce a section for conclusion. In this section, provide a summary of what the article has covered and the concluding remarks. You can write two paragraphs.

2022-01-14 12:08 UTC, mbaabuones commented on content/articles/computer-network-services/index.md
> +### Scaling a Network
write all headers in the required format. Please refer to other published articles.

2022-01-14 12:09 UTC, closed without merging