Facrecognition using wavelet features
section-engineering-education/engineering-education pull request #6069
Opened 2022-01-13 19:51 UTC by simonmwaniki

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5889 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-18 16:22 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-28 10:13 UTC, Dawe-7 requested changes
Nice tutorial @simonmwaniki, I've left you a few suggestions, kindly make the changes and we'll move on to tech review.

2022-01-28 10:13 UTC, Dawe-7 commented on content/articles/face-recognition-using-wavelet-features/index.md
> +It involves getting the wavelet feature and projecting them to the PCA space.
```suggestion
It involves getting the wavelet features and projecting them to the PCA space.
```

2022-01-28 10:13 UTC, Dawe-7 commented on content/articles/face-recognition-using-wavelet-features/index.md
> +The wavelet feature can be used to make a face recognition system. Using this method, we find a very robust method. Even if the image is distorted, it is still possible to recognize the faces accurat
```suggestion
In this tutorial, we have looked at how the wavelet feature is used to make a face recognition system. This method as we have seen is a very robust method. Even if the image is distorted, it is still possible to recognize the faces accurately using these features.

2022-01-28 20:21 UTC, simonmwaniki commented
@Dawe-7 changes made.

2022-01-30 16:28 UTC, Dawe-7 reviewed
Hello @simonmwaniki, as i was doing a final review on my end before marking this article as `ready for final review` i noticed that you have extra images. I haven't seen any image links to them in the article, if they are unnecessary kindly remove them. There also two hero images, kindly check on that. 

Ping me when done.

2022-02-01 08:11 UTC, Dawe-7 commented
> Hello @simonmwaniki, as i was doing a final review on my end before marking this article as `ready for final review` i noticed that you have extra images. I haven't seen any image links to them in the article, if they are unnecessary kindly remove them. There also two hero images, kindly check on that.
> 
> Ping me when done.

Any updates @simonmwaniki

2022-02-01 19:27 UTC, simonmwaniki commented
@Dawe-7 I checked the images, they were ok and all links. No extra image. Check slack please.

2022-02-02 05:20 UTC, Dawe-7 approved these changes
Awesome Job on the article @simonmwaniki. The unwanted images were outside your article but pushed together with it and i guess that's why you missed it. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

2022-02-09 13:28 UTC, ahmadmardeni1 commented
Great work team. @Dawe-7 @simonmwaniki

2022-02-09 13:30 UTC, merged