Implementing a GraphQL API server using Go lang and a MongoDB database
section-engineering-education/engineering-education pull request #6077
Opened 2022-01-14 14:03 UTC by Joakim-gakure

### Article checklist
#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [GitHub Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5927

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-14 14:58 UTC, srishilesh commented
Hello @Joakim-gakure ,

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.

To avoid potential closure of the PR:
- Perform a grammar check
- Make sure the hero image is of dimension 600x400
- Start markdown headers from `###`
- Go through the markdown guidelines that we follow here, by referring to our contribution guidelines
- For using bulleted points, use `-` instead of `*`
- For code snippets, make sure to explain them properly or add comments wherever needed
- The image paths are correct
- The author info is correct (Refer to the guidelines to view the latest update in author info section)
- The directory names are in lower case, separated by `-`

We also suggest you to go through other approved PRs to see how the authors have formatted their articles.

Thanks.

2022-01-18 16:27 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. @Joakim-gakure 
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Implementing a GraphQL API server using Go lang and a MongoDB database#6077](https://github.com/section-engineering-education/engineering-education/files/7890711/New.Scan.4_19.PM.Copyleaks.Report.pdf)

2022-01-18 16:30 UTC, ahmadmardeni1 commented
Please unassign this PR @Jethro-magaji - You can only review 2/3 PRs at the same time.

2022-01-18 16:55 UTC, Jethro-magaji commented
> Please unassign this PR @Jethro-magaji - You can only review 2/3 PRs at the same time.

Alright, done ✅.

2022-01-23 13:20 UTC, srishilesh commented
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. @Joakim-gakure Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [Implementing a GraphQL API server using Go lang and a MongoDB database#6077](https://github.com/section-engineering-education/engineering-education/files/7890711/New.Scan.4_19.PM.Copyleaks.Report.pdf)

@Joakim-gakure 

Are the plagiarism changes done?

If you still need more time, you can work on your forked repository and create a new PR when done.

2022-01-24 06:47 UTC, Joakim-gakure commented
Yes @srishilesh, Am adding the changes ASAP.

2022-01-24 08:38 UTC, Joakim-gakure commented
Changes done @srishilesh and @ahmadmardeni1

2022-01-24 12:47 UTC, srishilesh commented
@Joakim-gakure 

Please wait until a peer-reviewer pings you with the changes to be made.

@section-engineering-education/peer-reviewers Is anyone available to review this PR?

2022-01-29 17:18 UTC, ahmadmardeni1 commented
Hey @Bonimum  We have filled our peer reviewers team. You will be considered when we have open positions.

2022-02-06 01:32 UTC, Jethro-magaji requested changes
Hi! @Joakim-gakure 
Well done for such an amazing article, please go over my reviews and make the changes, I recommend editing your article with Grammarly or ProWriterAid just to double-check for typos or errors. 
Use "You" or "Your" instead of "We" or "Lets" in some instances.
Thanks.

2022-02-06 01:32 UTC, Jethro-magaji commented on content/articles/implement-graphql-api-using-golang-and-mongodb-database/index.md
> +To run this GraphQL API, we need to expose the methods we have created to localhost to access them using an endpoint. To implement this, follow the following steps.
There's a typo here "we have created to localhost to ".

2022-02-06 01:32 UTC, Jethro-magaji commented on content/articles/implement-graphql-api-using-golang-and-mongodb-database/index.md
>  query Movies{
Your conclusion section should include any next or final steps, summarizing the tasks the audience just completed with possible next steps.

2022-02-06 19:46 UTC, hectorkambow commented
@Joakim-gakure 
Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits **should be completed on your own forked repo** (as to not take up room in the queue) - this allows all revisions to be done on your forked personal repo.

2022-02-13 23:46 UTC, Jethro-magaji approved these changes
Hi! @Joakim-gakure 
Well done for coming up with such an awesome article. Please take note of the reviews made here and consider them next time you submit an article to minimize revision. 
Thanks.

2022-02-15 13:39 UTC, WanjaMIKE commented
Nice work guys @Joakim-gakure  cc @Jethro-magaji

2022-02-15 13:40 UTC, WanjaMIKE commented
Merged #6077 into master

2022-02-15 13:41 UTC, merged