A Guide to Missing Values Handling in Time Series using Python
section-engineering-education/engineering-education pull request #6093
Opened 2022-01-15 15:13 UTC by DennisKimt

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5904

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-16 07:10 UTC, wilkistermumbi commented
@ahmadmardeni1 I'd like to review this PR. 

cc: @hectorkambow

2022-01-19 15:42 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-19 15:43 UTC, ahmadmardeni1 commented
Hey @wilkistermumbi I'm sorry for the late reply. Can you choose another PR?

2022-01-27 21:49 UTC, BrianaNzivu requested changes
Hey @DennisKimt  👋 .

Good job on the article. It is a very interesting read. Barely any grammar changes to be made.
This is very impressive. Keep up the good work 👍 .

Just a few changes I need you to make as we continue with the preliminary revisions:
- Please structure your article according to this [sample](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md). I need you to clearly highlight and explain your steps. Where you can add more detail please do so.
- Please refer to the comment that I have made.

I would also love to know if this is your first article?

In case of any question or help needed please do not hesitate to ping me here or on Slack.
Also, notify me when you are done.

Regards.

2022-01-27 21:49 UTC, BrianaNzivu commented on content/articles/missing-values-in-time-series/index.md
> +### Python Implementation
Let's have the steps clearly highlighted and well explained. By that I mean, 
Step one: ....

2022-01-27 21:49 UTC, BrianaNzivu commented on content/articles/missing-values-in-time-series/index.md
> +
Maybe you can add the table of contents to this article here.

2022-01-27 21:49 UTC, BrianaNzivu commented on content/articles/missing-values-in-time-series/index.md
> +In this session, we will work with the following libraries.
Maybe you can list down the libraries.

2022-01-27 21:49 UTC, BrianaNzivu commented on content/articles/missing-values-in-time-series/index.md
> +author:
Please link your author folder's name here.

2022-01-27 21:50 UTC, BrianaNzivu commented
Proceeding with tech review meanwhile.

2022-02-01 17:59 UTC, BrianaNzivu commented
Tech review done 👍

2022-02-01 18:00 UTC, BrianaNzivu commented
@DennisKimt 👋 .
How's the progress with the corrections?

2022-02-03 17:13 UTC, BrianaNzivu requested changes
Hey @DennisKimt 👋 .
You haven't made any of the changes I requested except linking your author name. Please refer to all the comments I made.

Ping me when done.
Regards.

2022-02-06 20:11 UTC, DennisKimt commented
@BrianaNzivu  I've completed the changes you requested

2022-02-07 08:14 UTC, BrianaNzivu approved these changes
Hey @DennisKimt  👋 .

Very good job on the article. It is a very interesting read 👏 .

Just a few things I'd like to point out:
- I suggest that you check out the [structure](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) for the various articles accepted by Section.
-  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2022-02-14 17:55 UTC, lalith1403 commented
Jumping on this one 🚀

2022-02-16 16:47 UTC, merged

2022-02-18 19:23 UTC, hectorkambow commented
@DennisKimt Please reach out via DM on slack