Using service classes to design an authentication API in Flutter
section-engineering-education/engineering-education pull request #6100
Opened 2022-01-16 07:30 UTC by vincentkims49

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #6013

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-16 19:59 UTC, vincentkims49 commented
@BrianaNzivu could you take a look at this topic if you are free please.

2022-01-17 11:58 UTC, srishilesh reviewed
@vincentkims49 

Welcome to EngEd community!

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.

Meanwhile, we suggest you to go through other approved PRs/articles to see how the authors have formatted their articles, to avoid any potential closure of your PR.

Thanks.

2022-01-19 15:46 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[6100](https://github.com/section-engineering-education/engineering-education/files/7898462/New.Scan.3_37.PM.Copyleaks.Report.pdf)

2022-01-23 06:22 UTC, vincentkims49 commented
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such. [6100](https://github.com/section-engineering-education/engineering-education/files/7898462/New.Scan.3_37.PM.Copyleaks.Report.pdf)

Done. Thanks.

2022-01-28 17:30 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-31 09:32 UTC, vincentkims49 commented
Any changes required ping me @BrianaNzivu please.

2022-01-31 15:16 UTC, hectorkambow commented
@BrianaNzivu If any more edits are needed - we will be closing this PR. 

Thank you (this includes any minor edits you may make)

2022-02-01 18:42 UTC, BrianaNzivu requested changes
Hey @vincentkims49  👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

Good job on the article. It is a very interesting read though I feel like your article is covering content that is widely covered. I was just wondering maybe if you can enhance your article. Maybe you can use service classes to create something cool in Flutter.

Also, just a few changes I need you to make as we continue with the preliminary revisions:
- Please structure your article according to this [sample](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorialtemplate.md). I need you to clearly highlight and explain your steps. Where you can add more detail please do so.
- Please make changes that I have commented on also below.

In case of any question or help needed please do not hesitate to ping me here or on Slack.
Also, notify me when you are done.

I will temporarily close this PR just to create space on the queue and to allow you adequate time to make this enhancement. Once you are done, please create a new PR with the changes and ping me.

Regards.

2022-02-01 18:42 UTC, BrianaNzivu commented on content/articles/using-service-classes-to-design-an-authentication-api/index.md
> +Whether you're building a new flutter app from scratch or integrating an already existing one, you can use `FirebaseAuth`. You'll just need to know whether or not your user is signed in.
Use FirebaseaAuth for what?

2022-02-01 18:42 UTC, BrianaNzivu commented on content/articles/using-service-classes-to-design-an-authentication-api/index.md
> +1. How will you deal with modifications in future versions of firebase authentication that cause problems?
We have these as statements instead of questions.

2022-02-01 18:42 UTC, BrianaNzivu commented on content/articles/using-service-classes-to-design-an-authentication-api/index.md
> +The firebase authentication API calls are demonstrated in our below sample code using the `Firebase Authentication Service` class. All operations of the firebase authentication service class should r
This statement is not clear.

2022-02-01 18:42 UTC, BrianaNzivu commented on content/articles/using-service-classes-to-design-an-authentication-api/index.md
> +Service classes are designed to separate a certain operation from the rest of the app and hide its implementation details.
Can you have the points listed down instead of a paragraph

2022-02-01 19:27 UTC, vincentkims49 commented
Hello @BrianaNzivu please reopen so as I can work on them right away. Thanks in advance.

2022-02-02 06:38 UTC, vincentkims49 commented
@BrianaNzivu Done

2022-02-03 17:29 UTC, BrianaNzivu commented
Hey @vincentkims49 👋 .
I can see you've made the changes I requested but you have not enhanced the article. What I mean by enhancing the article is adding something to it that will make the content better and more unique. Your article is covering a subject that is widely covered by other blogs and even the official documentation, what I wanted you to do is create a cool feature (literally anything) in a flutter app using service classes at least it will make your article unique.

*Please note we typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into the programming-centric concepts.*

Once more I will give you another opportunity to enhance your article but outside the queue. I will be closing the PR simply to make room in the queue for other authors - but I can gladly reopen it anytime once the article is ready to publish.

**Note: You can still work on another article meanwhile if you feel like you will need some more time to figure this one out. Just open a new topic suggestion form and wait for a go ahead from a content moderator**

Regards.

2022-02-03 17:29 UTC, closed without merging

2022-02-03 17:44 UTC, vincentkims49 commented
Thanks. I'll add more content and ping you when done.

On Thu, Feb 3, 2022, 8:29 PM Briana Nzivu ***@***.***> wrote:

> Hey @vincentkims49 <https://github.com/vincentkims49> 👋 .
> I can see you've made the changes I requested but you have not enhanced
> the article. What I mean by enhancing the article is adding something to it
> that will make the content better and more unique. Your article is covering
> a subject that is widely covered by other blogs and even the official
> documentation, what I wanted you to do is create a cool feature (literally
> anything) in a flutter app using service classes at least it will make your
> article unique.
>
> *Please note we typically refrain from publishing content that is covered
> widely on the net or other blogs. As we're more interested in original,
> practitioner-focused content that takes a deeper dive into the
> programming-centric concepts.*
>
> Once more I will give you another opportunity to enhance your article but
> outside the queue. I will be closing the PR simply to make room in the
> queue for other authors - but I can gladly reopen it anytime once the
> article is ready to publish.
>
> *Note: You can still work on another article meanwhile if you feel like
> you will need some more time to figure this one out. Just open a new topic
> suggestion form and wait for a go ahead from a content moderator*
>
> Regards.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/6100#issuecomment-1029227621>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLZW7AI47GFUK4VEYU527TUZK3P7ANCNFSM5MCLJUVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/6100/c1029227621
> @github.com>
>

2022-02-04 04:48 UTC, vincentkims49 commented
> Hey @vincentkims49 wave . I can see you've made the changes I requested but you have not enhanced the article. What I mean by enhancing the article is adding something to it that will make the content better and more unique. Your article is covering a subject that is widely covered by other blogs and even the official documentation, what I wanted you to do is create a cool feature (literally anything) in a flutter app using service classes at least it will make your article unique.
> 
> _Please note we typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into the programming-centric concepts._
> 
> Once more I will give you another opportunity to enhance your article but outside the queue. I will be closing the PR simply to make room in the queue for other authors - but I can gladly reopen it anytime once the article is ready to publish.
> 
> **Note: You can still work on another article meanwhile if you feel like you will need some more time to figure this one out. Just open a new topic suggestion form and wait for a go ahead from a content moderator**
> 
> Regards.

Sorry I didn't get at first. I will add a feature where service classes store a state of an app. Please reopen so as I can add the content. Thanks.

2022-02-04 15:18 UTC, BrianaNzivu commented
Hey @vincentkims49 👋.
I'd advice you open a new PR with the new content just to avoid any merge conflicts.
You can add the duplicate label.
Lastly,
Ping or request a review from me on the new PR.

_Please note that the new PR should have content that is ready to be published with minimal corrections. If not, I will be obligated to close the PR immediately_.

Regards.