How to Adjust Image to Higher or Lower Resolution using Python
section-engineering-education/engineering-education pull request #6102
Opened 2022-01-16 13:32 UTC by lizpart

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5469

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-16 13:38 UTC, lizpart commented
@collins-a  Submitted a new PR

2022-01-18 07:50 UTC, lizpart commented
@Dawe-7 submitted  a new PR

2022-01-18 15:48 UTC, Dawe-7 commented
> @Dawe-7 submitted a new PR

@lizpart, this is a duplicate PR of which PR number?

2022-01-19 15:59 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-01-25 08:33 UTC, Dawe-7 requested changes
Hello @lizpart, i'll be reviewing your article. But, before we begin the review process, kindly check on the following:
1. Check your article for readability - as i glanced through your article i noticed an incomplete sentence. Make sure all your sentences are comprehensive and complete.
2. Do a grammar check on your article - when i ran your article through [grammarly](https://app.grammarly.com), it showed a lot of errors. Always make sure to submit a fully polished article for review to prevent article closure.
3. I have made your URL (how you've saved the branch of your article in vscode) shorter because it was too long - Kindly adjust the image paths accordingly based on the new change. In future, avoid using lenghty URL's.
4. Make use of backticks where necessary - There are some words i feel need to have backticks. Use them in places where you need to highlight certain/important words.
5. Use the proper language identifier - use `py` instead of `python` after the backticks.

Lastly, ensure your article is fully polished and ready for review before submitting a PR. Ping me when done with the above.
4.

2022-01-27 12:42 UTC, Dawe-7 requested changes
@lizpart, I've left you a few suggestions to improve your article, kindly ping me when done. It is always recommendable for the author to revisit the article from the introduction to conclusion once you've effected the changes requested correcting any unseen errors.

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +The reader has to be familiar with the Python programming language basics to follow along with this tutorial. Refer to this [beginners guide to python](/engineering-education/a-beginners-guide-to-pyt
```suggestion
The reader has to be familiar with the Python programming language basics to follow along with this tutorial. Refer to this [beginners guide to Python](/engineering-education/a-beginners-guide-to-python/)
```

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +### How to install and use Pillow and Numpy
```suggestion
### How to install and use Pillow and NumPy
```

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +This occurs when one color in the RGB format is omitted, let's say if blue is, the image will lack the blue pigment and any traces of it since every single pixel has blue taken away from it leaving o
There is a word missing here after `let's say blue is` ?

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +To construct the Laplacian Pyramid Super-Resolution Network, we will be taking the top-level layer of the Gaussian Pyramid which is the last image generated using the loop function then create a list
This sentence is a whole paragraph, break it down and make sure it is comprehensive

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +To understand it better a code snippet will do:
Rephrase this sentence in a better way

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +The output should be similar to the below image:
```suggestion
Your output should be like the image shown below.
```

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +Your output should match the below image:
```suggestion
Your output should be like the image shown below.
```

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +- **Medicine**: Images received from scans such as the X-Rays require adjustment of resolutions to provide detailed and accurate information.
```suggestion
- **Astronomy** - This is achieved by focusing on tiny information of images to higher resolutions that bring out clearer vision.
- **Closed Circuit Television** -  Feeds received from a CCTV footage can be focused to get clearer images by resolving and fixing the colors where possible.
- **Medicine** - Images received from scans such as the X-Rays need adjustment of resolutions to provide detailed and accurate information.
```

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +Covering all the details required in this tutorial, you are now equipped to handle matters concerning this tutorial. Being able to accurately work with this area of discussion and produce maximum res
I feel this conclusion is very basic. Give a better conclusion that summarizes the content of your article briefly.

2022-01-27 12:42 UTC, Dawe-7 commented on content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
> +In this tutorial, we will need to use some basic tools such as OpenCV, used in computer vision-based tasks, and the main function is required in our tutorial for image processing.
What is the main function you are referring to here?

2022-01-28 09:57 UTC, lizpart commented
@Dawe-7 Completed requested changes

2022-02-01 19:48 UTC, Dawe-7 approved these changes
Awesome Job on the article @lizpart . Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

2022-02-01 19:54 UTC, lizpart commented
@Dawe-7 ✅ okay checked Thanks

2022-02-09 14:33 UTC, merged