Introduction to Secrets Management with Doppler
section-engineering-education/engineering-education pull request #6112
Opened 2022-01-17 08:11 UTC by LynetteMwe

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-17 12:01 UTC, srishilesh commented
Hello @LynetteMwe ,

Welcome to EngEd community!

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.

Meanwhile, we suggest you to go through other approved PRs/articles to see how the authors have formatted their articles, to avoid any potential closure of your PR.

Thanks.

2022-01-24 04:44 UTC, LynetteMwe commented
> Hello @LynetteMwe ,
> 
> Welcome to EngEd community!
> 
> Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.
> 
> Meanwhile, we suggest you to go through other approved PRs/articles to see how the authors have formatted their articles, to avoid any potential closure of your PR.
> 
> Thanks.

Noted with thanks, very eager to get this reviewed.

2022-01-24 13:06 UTC, srishilesh requested changes
Hey @LynetteMwe ,

Good job on your first article.

I've suggested some major changes for improving the quality of the article. Make sure to go through all the suggestions carefully and address them.

I would also highly recommend you to go through other approved PRs/published articles to see if you have missed out any. This would help avoid PR closure.

Make sure your hero image is of 600x400 dimension, and you perform a grammar check.

Ping me when done.

Thanks.

2022-01-24 13:06 UTC, srishilesh commented on content/articles/introduction-to-secrets-management-with-doppler/index.md
> +Doppler CLI is convenient for local development, CI/CD pipelines and production environments.
How?

2022-01-26 07:39 UTC, lalith1403 commented
PFA the plagiarism report. It is higher than we typically accept. Please make the changes. Thank you
[Introduction to Secrets Management with Doppler.pdf](https://github.com/section-engineering-education/engineering-education/files/7939728/Introduction.to.Secrets.Management.with.Doppler.pdf)
.

2022-01-26 20:09 UTC, LynetteMwe commented
> PFA the plagiarism report. It is higher than we typically accept. Please make the changes. Thank you [Introduction to Secrets Management with Doppler.pdf](https://github.com/section-engineering-education/engineering-education/files/7939728/Introduction.to.Secrets.Management.with.Doppler.pdf) .

Hello @lalith1403 , I have made adjustments.

2022-01-26 20:10 UTC, LynetteMwe commented
> Hey @LynetteMwe ,
> 
> Good job on your first article.
> 
> I've suggested some major changes for improving the quality of the article. Make sure to go through all the suggestions carefully and address them.
> 
> I would also highly recommend you to go through other approved PRs/published articles to see if you have missed out any. This would help avoid PR closure.
> 
> Make sure your hero image is of 600x400 dimension, and you perform a grammar check.
> 
> Ping me when done.
> 
> Thanks.

I have completed the suggested revisions. I also had updated and uploaded front matter, image , and hero as required . Kindly confirm.

2022-01-29 07:13 UTC, srishilesh commented
I'll complete by tech review by EOD

2022-01-30 13:29 UTC, LynetteMwe commented
> I'll complete by tech review by EOD

Could you please adjust the other labels, like the hero and author profile.

2022-01-30 13:38 UTC, srishilesh commented
> > I'll complete by tech review by EOD
> 
> Could you please adjust the other labels, like the hero and author profile.

Don't worry about it. I'm aware of that. On verifying them, I'll remove it.

2022-01-31 08:26 UTC, LynetteMwe commented
> > > I'll complete by tech review by EOD
> > 
> > 
> > Could you please adjust the other labels, like the hero and author profile.
> 
> Don't worry about it. I'm aware of that. On verifying them, I'll remove it.

2022-01-31 08:31 UTC, srishilesh commented
@LynetteMwe 

Why did you close the PR?

The tech review is in progress.

2022-01-31 14:26 UTC, srishilesh approved these changes
@LynetteMwe 

Great article. It was very beginner friendly and easy to read.

I've made some minor changes.

Also, looks like you've missed out to add 2 images. Please ping me after you add them, I'll move it for the final review.

Thanks.

2022-01-31 14:26 UTC, srishilesh commented on content/articles/introduction-to-secrets-management-with-doppler/index.md
> +![Project](/engineering-education/introduction-to-secrets-management-with-doppler/get.png)
We don't have this image. Please add it. Make sure the extensions are in lowercase

2022-01-31 19:51 UTC, LynetteMwe commented
Hello @srishilesh , I am done with the images. Please confirm.

2022-01-31 19:55 UTC, LynetteMwe commented
> @LynetteMwe
> 
> Great article. It was very beginner friendly and easy to read.
> 
> I've made some minor changes.
> 
> Also, looks like you've missed out to add 2 images. Please ping me after you add them, I'll move it for the final review.
> 
> Thanks.

Done

2022-02-10 09:21 UTC, ahmadmardeni1 commented
Great work team. @srishilesh @LynetteMwe 

Welcome to Section EngEd and congrats on your first article. @LynetteMwe

2022-02-10 09:21 UTC, merged