How to Build an IP Address Tracker with Mapbox API and Vue.
section-engineering-education/engineering-education pull request #6143
Opened 2022-01-19 20:52 UTC by Abiola-Farounbi

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #5068

2022-01-19 20:55 UTC, Abiola-Farounbi commented
Hi @lalith1403,
I have made the edits and changes to the article.

2022-01-19 21:07 UTC, vinstex commented
@srishilesh, please add a duplicate label for this.

2022-01-20 16:56 UTC, srishilesh commented
Duplicate of #5701

2022-01-20 16:57 UTC, srishilesh commented
Assigning this duplicate PR #5701 to @vinstex, since he was test-reviewing it previously.

2022-02-05 18:48 UTC, louisefindlay23 requested changes
This article needs revising further before final review. 

There are formatting issues with spaces missing before brackets coupled with flow and readability issues, particular with the use of would where will would be more suitable and the overuse of This and The instead of linking sentences more. 

I've pointed out occurrences of this but it is your responsibility to scour your article and correct them all where they occur.

2022-02-05 18:48 UTC, louisefindlay23 commented on content/articles/build-an-ip-address-tracker/index.md
> +An IP(Internet Protocol) address is a set of numbers that represents the location website or device. Each number in the set ranges from 0 to 255, that is from 0.0.0.0 to 255.255.255.255.
Add a space between IP and (

2022-02-05 18:48 UTC, louisefindlay23 commented on content/articles/build-an-ip-address-tracker/index.md
> +IPv4 is old and limited to 32-bit addresses while IPv6 is the new standard and allows for 128-bit addresses. The creation of IPv6 is because all possible IPv4 addresses are close to being exhausted a
Are these meant to be two separate paragraphs?

2022-02-05 18:48 UTC, louisefindlay23 commented on content/articles/build-an-ip-address-tracker/index.md
> +IPv4 is old and limited to 32-bit addresses while IPv6 is the new standard and allows for 128-bit addresses. The creation of IPv6 is because all possible IPv4 addresses are close to being exhausted a
IPv6 was created because flows better than The creation of IPv6 is because

2022-02-05 18:48 UTC, louisefindlay23 commented on content/articles/build-an-ip-address-tracker/index.md
> +The IP Address of a user can be used for various dynamic purposes one of which is **IP Geolocation**. This is the identification of a geographic location of a device by using an IP address. This invo
add a comma after purposes. This is the indentification of a grographic location = IP Geolocation is.

Flow/readability edits.

Missing comma after region(city)

2022-02-05 18:48 UTC, louisefindlay23 commented on content/articles/build-an-ip-address-tracker/index.md
> +In this guide, we’ll build an IP Address Tracker from scratch using the Vue.js framework, an IP geolocation API, and the Mapbox API. We’ll cover the process of building the front-end, handling the us
readers will or readers should

2022-02-05 18:48 UTC, louisefindlay23 commented on content/articles/build-an-ip-address-tracker/index.md
> +> It is important to note that result gotten from each API service varies. In this tutorial, we will be using the [IPWHOIS](https://ipwhois.io/) API service.
gotten = returned

2022-02-05 23:11 UTC, Abiola-Farounbi commented
Hi @louisefindlay23, 
Thanks for the review edits, I have made the required changes.

2022-02-06 11:26 UTC, louisefindlay23 approved these changes
Final review complete. Please look over the changes, @Abiola-Farounbi to inform your future articles.

2022-02-06 11:26 UTC, merged

2022-02-06 16:21 UTC, Abiola-Farounbi commented
> Final review complete. Please look over the changes, @Abiola-Farounbi to inform your future articles.

Thanks
Yes, I will.