Create a registration form using React.js ( Hooks ) and connect with firebase
section-engineering-education/engineering-education pull request #6151
Opened 2022-01-20 12:28 UTC by anubhavb11

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-20 17:02 UTC, srishilesh commented
Hello @anubhavb11 

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you for the changes to be made.

Can you please link your PR to an issue?

2022-01-21 10:28 UTC, anubhavb11 commented
this resolves.  [issue ](https://github.com/section-engineering-education/engineering-education/issues/3484)

2022-01-26 07:52 UTC, lalith1403 commented
PFA the plagiarism report. It is higher than what we accept. Please make the changes accordingly. Thank you.
[Create a registration form using React.js ( Hooks ) and connect with firebase.pdf](https://github.com/section-engineering-education/engineering-education/files/7939818/Create.a.registration.form.using.React.js.Hooks.and.connect.with.firebase.pdf)

2022-01-27 01:24 UTC, Jethro-magaji requested changes
Hi! @anubhavb11 
Well done for such an amazing article. However, there're a lot of corrections you need to make. If you haven't finished polishing your article, please close the PR and work on it because it seems like you are still working on it. 
Please, properly format the markdown and run your article on tools like Grammarly and ProWritingAid for better editing. 
Use 2nd person "You" instead of "I", "We" or "Lets".
Visit the EngEd new contributor's [docs](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md) here to guide you.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd slack channel.

Thanks.

2022-01-27 01:24 UTC, Jethro-magaji commented on content/articles/how-to-make-form-using-react/index.md
> +For styling make a `style.css` file inside the component folder here we will write all are styles and include in your registration form component.
Instead of this "For styling make" use " For styling create".

2022-01-27 01:24 UTC, Jethro-magaji commented on content/articles/how-to-make-form-using-react/index.md
> +Now we will start learning how to connect fire base to our Registration from. For that we need to do the following.
"Firebase" not "fire base"

2022-01-27 01:24 UTC, Jethro-magaji commented on content/articles/how-to-make-form-using-react/index.md
> +- At first what we required? We required a space where we can record our data. For that we will go to firebase homepage [Click here.](https://firebase.google.com/) Or Type firebase.google.com
"At first what we required?" this seems incorrect.

2022-01-27 01:24 UTC, Jethro-magaji commented on content/articles/how-to-make-form-using-react/index.md
> +Congratulation you have successfully learn how to make registration form and connect it to firebase to store real time data.
There's supposed to be a conclusion section, summarizing what you have done in the tutorial.

2022-01-27 17:01 UTC, anubhavb11 commented
@Jethro-magaji  I will work on the corrections and will improve the readability and English or article more sorry for unpolished article will improve it in 1 week.

2022-02-03 18:40 UTC, hectorkambow commented
All edits should be made out of the queue. Closing for now

2022-02-03 18:40 UTC, closed without merging