How to build a Meme Generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas
section-engineering-education/engineering-education pull request #6172
Opened 2022-01-21 17:41 UTC by Nomzy-kush

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-21 19:07 UTC, Jeff-mwangi commented
@hectorkambow and @ahmadmardeni1 I would like to review this article

2022-01-21 19:45 UTC, ahmadmardeni1 commented
Go ahead. @Jeff-mwangi

2022-01-23 08:00 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

2022-01-23 08:01 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. @Nomzy-kush 
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


[How to build a Meme Generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas#6172](https://github.com/section-engineering-education/engineering-education/files/7920025/New.Scan.7_57.AM.Copyleaks.Report.1.pdf)

2022-01-28 14:45 UTC, Nomzy-kush commented
>
> Hey Jeff,
>
Upon running the draft through several Plagiarism checkers, I’ve only seen
little to no plagiarism. I was wondering if you can send me the link to the
Plagiarism report you got.

Thanks,
Onome

Message ID:
> <section-engineering-education/engineering-education/pull/6172/c1020905879
> @github.com>
>

2022-01-31 12:56 UTC, Nomzy-kush commented
Hello @ahmadmardeni1 you can go ahead to recheck this draft again for plagiarism.

2022-01-31 16:36 UTC, ahmadmardeni1 commented
Plagiarism check done ✅ @Nomzy-kush

2022-02-01 12:09 UTC, Jeff-mwangi commented on content/articles/how-to-build-a meme-generator-with-vanilla-javascript-skeleton-and-the-html5-canvas/index.md
> +Memes are a stimulating and fun way to pass messages across to people. This tutorial will take you through a step-by-step guide on how you can build a simple meme generator with JavaScript(no framewo
```suggestion
Memes are a stimulating and fun way to pass messages to people. This tutorial will take you through a step-by-step guide on how you can build a simple meme generator with JavaScript(no frameworks involved) and style its components with CSS and [Skeleton](http://getskeleton.com/). With the [HTML 5 Canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API), users will be able to upload images and texts of their choice and or from an online source to create comical memes for a mass online audience. 
```

2022-02-01 21:05 UTC, Jeff-mwangi commented on content/articles/how-to-build-a meme-generator-with-vanilla-javascript-skeleton-and-the-html5-canvas/index.md
> +## Prerequisites for this tutorial
Add table of contents

2022-02-03 08:55 UTC, Jeff-mwangi commented
Hello @Nomzy-kush Consider doing all the changes first and then commit them once.

2022-02-03 09:39 UTC, Nomzy-kush commented
Hey @Jeff-mwangi I have made all the necessary changes you requested.

2022-02-03 18:40 UTC, hectorkambow commented
@Jeff-mwangi 

If any more edits are needed, we will be closing this PR 👍

2022-02-06 19:52 UTC, hectorkambow commented
@jeff-mwangi any updates on this?

2022-02-08 17:47 UTC, Jeff-mwangi commented
> @Jeff-mwangi any updates on this?

Working on tech review

2022-02-08 19:27 UTC, Jeff-mwangi requested changes
@Nomzy-kush Add front matter and PRC line.

2022-02-08 19:27 UTC, Jeff-mwangi commented on content/articles/how-to-build-a meme-generator-with-vanilla-javascript-skeleton-and-the-html5-canvas/index.md
> +### How to build a Meme Generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas
Add front matter
```suggestion
---
layout: engineering-education
status: publish
published: true
url: /how-to-build-a meme-generator-with-vanilla-javascript-skeleton-and-the-html5-canvas/
title: Building a meme generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas
description: This tutorial will show you how to build a meme generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas
author: doro-onome
date: 2022-02-09T00:00:00-22:15
topics: [Languages]
excerpt_separator: <!--more-->
images:

  - url: /engineering-education/how-to-build-a meme-generator-with-vanilla-javascript-skeleton-and-the-html5-canvas/hero.jpg
    alt: Building a meme generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas
---
```

2022-02-08 19:35 UTC, louisefindlay23 commented
Please link your topic suggestion so we can accurately pay out if this article is published

2022-02-08 20:16 UTC, hectorkambow commented
> Please link your topic suggestion so we can accurately pay out if this article is published

🤔  

Not sure how the article topic is connected to the payout (unless im misunderstanding) - important step nonetheless

2022-02-08 20:17 UTC, hectorkambow commented
> > @Jeff-mwangi any updates on this?
> 
> Working on tech review

Thank you - lets try to keep our reviews (wait time to a minimum if possible - we understand things come up but) to be fair to our authors and other in the queue.

2022-02-08 20:17 UTC, hectorkambow commented
@Jeff-mwangi  

If any other edits are needed - we will be closing the PR - this has underwent an extensive review already 🚀

2022-02-08 22:00 UTC, Nomzy-kush commented
> Please link your topic suggestion so we can accurately pay out if this article is published

This fixes #5765

2022-02-11 18:45 UTC, Jeff-mwangi approved these changes
Thank you @Nomzy-kush . The changes looks good now. Let's move it for the final review.

2022-02-11 18:47 UTC, Jeff-mwangi commented
@ahmadmardeni1 This article is now ready for final review.

cc: @hectorkambow

2022-02-24 20:13 UTC, Nomzy-kush commented
Hey @hectorkambow and @louisefindlay23, isn't this PR ready to be merged?

2022-02-24 21:33 UTC, hectorkambow commented
jumping on this one

2022-02-24 21:57 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team 
We should have pushed this article along as well. 👀

2022-02-24 21:57 UTC, merged