Initial Commit
section-engineering-education/engineering-education pull request #6213
Opened 2022-01-23 19:13 UTC by gmcodes20

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5869

2022-01-27 13:46 UTC, srishilesh commented
Hey @gmcodes20 ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you with the changes to be made.

Meanwhile, we suggest you to go through other approved PRs/published articles to see if you have missed out anything, which might avoid a potential PR closure.

Thanks.

2022-02-02 18:05 UTC, LinusMuema commented
plagiarism check done ✅

2022-02-09 08:43 UTC, Dawe-7 requested changes
Nice article @gmcodes20, I've left you a few suggestions and comments. Kindly effect the changes so that we can move on to tech review. Your hero image is too large, make sure it is of the size 600x400 pixels. Resize your other images as well if they are too large.

Also, make sure to cross check your article for readability because there were some readability issues in review.

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +This tutorial will explain how to create an **ajax type-ahead feature** for your website using the [cities.json file](). This file contains information about states and cities in America. What this f
Add the missing link here.

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +Part of the job of a front-end developer is to create intuitive user interfaces that deliver the best user experience to website users. Part of getting this job done is by creating search suggestions
I feel the start of your article is not very intuitive, kindly rephrase it. You could start by saying this 
` Creating intuitive user interfaces that deliver the best user experience to website users is part of the job of a front-end developer`.   

Kindly avoid being repetitive - the word `part`.

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +- A Code editor.
```suggestion
- A code editor.
```

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +> The blobdata object, in turn, does not contain the actual JSON response body but is instead a representation of the entire HTTP response. To extract the JSON body content from the Response object,
Is the object supposed to be `blobdata` or `BLOB data`. Could you break down the second sentence here as it is too long. Also, add the MDN link properly.

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +![Blobdata output](./returned-blobdata.png)
```suggestion
![Blobdata output](/engineering-education/create-an-ajax-type-ahead-feature-for-a-website/returned-blobdata.png)
```
Use the same format for your other images as well. Also, if your images are from third party sources/ are not screenshots, add the image source links.

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +- In the function, we return a filtered subset of the `cities` array and check to see if what the user typed is returned. To check if what the user typed is inside the array, we will [use Regex](http
```suggestion
 In the function above, we return a filtered subset of the `cities` array and check if what the user typed is returned. To check if what the user typed is inside the array, we will use [Regex](https://www.w3schools.com/js/js_regexp.asp) to check if the searched word matches any state or city in the `cities` array.
```

2022-02-09 08:43 UTC, Dawe-7 commented on content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
> +`Fetch(URL, options)`
Place this method in backticks and identify the language.

2022-02-10 00:17 UTC, Dawe-7 approved these changes
Awesome Job on the article @gmcodes20 . Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

2022-02-10 00:36 UTC, gmcodes20 commented
> Awesome Job on the article @gmcodes20 . Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

Thank you @Dawe-7 , I'll keep that in mind.

2022-02-11 09:47 UTC, Kayere commented
Great work gents 🚀.

2022-02-11 09:48 UTC, merged

2022-02-11 09:51 UTC, gmcodes20 commented
> Great work gents 🚀.

Thank you 😊