How to use brotli compression algorithm method
section-engineering-education/engineering-education pull request #6215
Opened 2022-01-23 21:38 UTC by Newton-cyber

### Article checklist

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #5731`

2022-01-24 06:26 UTC, Newton-cyber commented
@srishilesh Done a new PR but the merge branch keeps on coming to my PR

2022-01-24 13:18 UTC, srishilesh requested changes
Hey @Newton-cyber ,

On having a quick glance at your article, it looks like we may have close this PR, since it's not very beginner friendly.

Your article:
- Lacks explanation of concepts and terminologies
- The code snippets are not explained properly
- You do not direct the reader with step by step implementation
- Few code snippets looks very technical - you don't specify where or how to run them
- You have covered several topics in one short article. Cover 1 - 2 concepts at max in an article.
- Overall content looks quite low.
- This PR has an unwanted additional image file `integration-of-ros-with-arduino/WhatsApp Image 2021-08-08 at 17.57.26.jpeg`

I'll be closing this PR now. You may work on all the changes and submit only ready to be published PRs.

I highly recommend you to go through approved PRs/Published articles to see how other authors have formatted and structured the flow. This will help you avoid potential PR closure.

Thanks.

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +Static assets such as *.js*, *.CSS* and *.json* text files are commonly used in web application projects, with redundancy and compression playing an important role. ,Data compression is the process o
```suggestion
Static assets such as *.js*, *.css* and *.json* text files are commonly used in web application projects, with redundancy and compression playing an important role.  Data compression is the process of encoding files to reduce their size, making them take up less space on your server and allowing them to be transferred to site clients more quickly. Compression reduces the amount of bandwith required for website rendering, which speeds up the process.

```

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +- Compression algorithm
Make this as a complete sentence.

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +Brotli is a lossless data compression algorithm that employs a variant of the *LZ77 algorithm*, as well as *Huffman coding* and *second-order context modelling*. Its compression ratio is comparable t
Please explain these terminologies. Beginners might not understand them easily.

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +- Compression algorithm
Before jumping into brotli, start with explaining what compression algo is

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +The browser sends an `Accept-Encoding` header with the algorithms it supports and their priority order; the server chooses one, uses it to compress the body of the `content-encoding` header to inform
`Accept-Encoding` and `content-encoding`

What is this for? Add example image or sample header to explain them first.

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +The browser sends an `Accept-Encoding` header with the algorithms it supports and their priority order; the server chooses one, uses it to compress the body of the `content-encoding` header to inform
` it supports and their priority order;`

What do you mean by priority order?

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +The browser sends an `Accept-Encoding` header with the algorithms it supports and their priority order; the server chooses one, uses it to compress the body of the `content-encoding` header to inform
`content negotiation was used to select a representation based on its encoding`

Explain

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +The browser sends an `Accept-Encoding` header with the algorithms it supports and their priority order; the server chooses one, uses it to compress the body of the `content-encoding` header to inform
`caches to cache the various representations of the resource.`

Explain

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +2. Enabling Brotli on CDNs
What is a webserver and what is CDN?

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +### Compression with Nginx statically
What is nginx

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +```
Explain

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +```
Where do you store this? Or how will you work with this?

2022-01-24 13:18 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +```
Explain

2022-01-24 13:18 UTC, closed without merging

2022-02-08 14:01 UTC, srishilesh commented
@Newton-cyber 

Do we have any updates?