[Duplicate of #5365] Introduction to Kernel Methods in Machine Learning
section-engineering-education/engineering-education pull request #6234
Opened 2022-01-25 07:14 UTC by Brian3811

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-25 07:16 UTC, Brian3811 commented
hello @paulodhiambo changes requested are in place

2022-02-03 19:52 UTC, hectorkambow commented
@paulodhiambo  

If any other edits are needed - we will be closing the PR.

2022-02-08 20:03 UTC, louisefindlay23 commented
Plagiarism check complete

2022-02-10 00:56 UTC, Jethro-magaji requested changes

2022-02-10 00:56 UTC, Jethro-magaji commented on content/articles/introduction-to-kernel-methods-in-machine-learning/fixed index.md
> +### Introduction
"Introduction" should come before the "Prerequisite"

Add a "Table of content" section.

2022-02-10 00:56 UTC, Jethro-magaji commented on content/articles/introduction-to-kernel-methods-in-machine-learning/fixed index.md
> +### _What are kernels?_
There's no need to italicize this heading.

2022-02-10 00:56 UTC, Jethro-magaji commented on content/articles/introduction-to-kernel-methods-in-machine-learning/fixed index.md
> +### Conclusion
Summarizing the tasks the audience just completed.

2022-02-10 12:41 UTC, Brian3811 commented
hello @Jethro-magaji  changes requested are in place

2022-02-14 00:55 UTC, Jethro-magaji commented
Hi! @Brian3811 
Please change the current hero image to a high resolution free stock image of 600x400 PX.
Change the PR branch name to something readable, like this "introduction-to-kernel-methods-in-machine-learning"

2022-02-14 00:58 UTC, Jethro-magaji commented on content/articles/index.md
> +___Supervised machine learning___ is also known as supervised learning. It is distinguished by using labelled datasets to train algorithms that accurately classify data or predict outcomes.
You only mentioned supervised learning here, what about unsupervised learning?

2022-02-14 22:31 UTC, Jethro-magaji approved these changes
Hi @Brian3811 !
Well done for the awesome article, please take note of the reviews and edits next time you submit an article.
Thanks, overall it's a great article.

2022-02-23 18:15 UTC, merged