How to Write a Rust GraphQL Server With MongoDB, Juniper and Actix Web
section-engineering-education/engineering-education pull request #6265
Opened 2022-01-26 11:48 UTC by Catemacharia

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5600

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-26 14:23 UTC, jerimkaura commented
Hello @Catemacharia :wave:

Happy to see you here again.  I am currently learning GraphQL so I  will be reviewing this with pleasure. Let us use this opportunity to build ourselves :rocket:

I look forward to learning more from you. :tada:

2022-01-29 12:48 UTC, lalith1403 commented
plagiarism check done ✔️

2022-01-31 20:11 UTC, jerimkaura requested changes
Hello @Catemacharia 

Great article but you have several glaring errors that you need to address.

If you go with first-person pronouns, maintain it across the whole article. If you chose second, do the same.

Go over the article to correct any grammatical errors that you have. We highly recommend fully published articles for publish.

I haven't read the whole content so you need to do an in-depth reading andanalysis of the article to ensure it is error-free.

Let me know of any issues.

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +To follow up in this article, it is helpful to have the following:
Follow up or follow along?

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +To use the above dependencies, we need to make them available for our project. Navigate to the `Cargo.toml` file in the project root directory and update is as follows:
Available in

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +The dependencies will be installed. This will still give you the output `Hello, world!` since we have not added our code logic yet. And this implies you are good to go to the next step.
You should not start a sentence with "AND"

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +Schema is a collection of types with fields that are populated from your back-end application. They are the defining GraphQL API blueprint. Apart from fields, a schema also defines types such as quer
This statement is not clear. It also incomplete. Correct it, make it clear and break it down into smaller readable paragraphs.

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +Navigate to your `main.rs` and start by updating the imports as follows modules and dependencies:
Read your statements to see if they are understandable.

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +The above function returns an asynchronous call with either a successful state or an error state. It gets the GraphQL request in JSON executes them. Then chains them to `.map_err` in case an error oc
User  a proper subject-verb agreement

2022-01-31 20:11 UTC, jerimkaura commented on content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
> +APIs powers many world applications. These APIs must have the capacity to deliver data of all shapes, capabilities, and sizes. Exposing APIs with GraphQL enables clients to access this data in diffre
APIs power.

2022-02-03 19:32 UTC, jerimkaura commented
Good afternoon and thank you for submitting your topic to the EngEd program.
Upon a quick glance we noticed that this articles has some grammatical errors (or is a bit difficult to read) and does not seem ready to be published.

In order to keep our backlog to a minimum, we will be closing this PR, as all edits should be completed on authors forked repo not in the queue.

2022-02-03 19:32 UTC, closed without merging