Handling User Authentication in Firebase and Vue.js Applications
section-engineering-education/engineering-education pull request #6282
Opened 2022-01-27 07:25 UTC by annemwangi

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5452

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-01-27 13:54 UTC, srishilesh commented
Hello @annemwangi ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you with the changes to be made.

Meanwhile, we suggest you to go through other approved PRs/published articles to see if you have missed out anything, which might avoid a potential PR closure.

Thanks.

2022-02-07 07:03 UTC, adrianmurage commented
@section-engineering-education/content-moderator-team

2022-02-08 20:19 UTC, louisefindlay23 commented
Plagiarism check complete

2022-02-19 14:43 UTC, adrianmurage requested changes
@annemwangi 
Your tutorial reads smoothly but, sadly, in the end nothing renders.
Meaning that you will need to review your article and make sure it's working as expected.

The best way to do this is to start from scratch and follow your tutorial word for word and see if you end up with the expected end result. This will help you catch anything you might have omitted in the writing process.

I'll be closing this PRuntil you do. Once everything is ready we can reopen the PR.

@ me when you're ready for me to take a look

2022-02-20 04:13 UTC, annemwangi commented
@adrianmurage, could you please explain to me what "nothing renders means"?
Because the code was working perfectly. I have also tested it right now and it's still working perfectly.

2022-02-23 11:01 UTC, adrianmurage commented
@annemwangi 

after following through your article with 2 different machines, I end up with the same issue:
```bash
 ERROR  Failed to compile with 1 error                                                                                         1:58:59 PM


/home/m/Code/reviews/firebase-vue-user-management/src/components/Navbar.vue
  1:1  error  Component name "Navbar" should always be multi-word  vue/multi-word-component-names

/home/m/Code/reviews/firebase-vue-user-management/src/views/Home.vue
  1:1  error  Component name "Home" should always be multi-word  vue/multi-word-component-names

/home/m/Code/reviews/firebase-vue-user-management/src/views/Login.vue
  1:1  error  Component name "Login" should always be multi-word  vue/multi-word-component-names

/home/m/Code/reviews/firebase-vue-user-management/src/views/Signup.vue
  1:1  error  Component name "Signup" should always be multi-word  vue/multi-word-component-names

✖ 4 problems (4 errors, 0 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
ERROR in 
/home/m/Code/reviews/firebase-vue-user-management/src/components/Navbar.vue
  1:1  error  Component name "Navbar" should always be multi-word  vue/multi-word-component-names

/home/m/Code/reviews/firebase-vue-user-management/src/views/Home.vue
  1:1  error  Component name "Home" should always be multi-word  vue/multi-word-component-names

/home/m/Code/reviews/firebase-vue-user-management/src/views/Login.vue
  1:1  error  Component name "Login" should always be multi-word  vue/multi-word-component-names

/home/m/Code/reviews/firebase-vue-user-management/src/views/Signup.vue
  1:1  error  Component name "Signup" should always be multi-word  vue/multi-word-component-names

✖ 4 problems (4 errors, 0 warnings)


webpack compiled with 1 error
```

![Screenshot from 2022-02-23 13-59-33](https://user-images.githubusercontent.com/47227271/155306688-4c1cdfae-b41b-48f4-a0a4-1ffc39b8a9a0.png)

2022-02-23 11:53 UTC, adrianmurage commented
I started again from scratch up to the point where you introduce Navbar.
Upon renaming `Navbar.vue` to `NavBar.vue`, I got it to render out.

I also found [documentation](https://v2.vuejs.org/v2/style-guide/#Multi-word-component-names-essential) that explains the error. 

I am assuming if you fix this, the app should work as expected

![Screenshot from 2022-02-23 14-50-12](https://user-images.githubusercontent.com/47227271/155314407-dcc6220c-5230-4d3c-a6c3-6059693dbc04.png)
![Screenshot from 2022-02-23 14-50-23](https://user-images.githubusercontent.com/47227271/155314411-fa76da01-7d2f-454d-b401-4d326e605699.png)

2022-02-24 12:47 UTC, adrianmurage reviewed
@annemwangi 

It seems that the reason my app was not rendering was as a result of a typo in your `firebase/config.js` file

2022-02-24 12:47 UTC, adrianmurage commented on content/articles/firebase-vue-authentication/index.md
> +import { inititializeApp } from 'firebase/app'
The word `initialize` is spelled wrong and that is what was causing my app to not render.

```suggestion
import { initializeApp } from 'firebase/app'
```

2022-02-24 12:47 UTC, adrianmurage commented on content/articles/firebase-vue-authentication/index.md
> +inititializeApp(firebaseConfig)
The word `initialize` is spelled wrong and that is what was causing my app to not render.

```suggestion
initializeApp(firebaseConfig)
```

2022-02-24 13:18 UTC, adrianmurage commented
@annemwangi 
Good job with this article.

Do however take note of the value of working through your article from a reader's perspective to help catch any errors in your future work

Otherwise, keep up the good work and I look forward to seeing more of your work published by EngEd

2022-02-24 16:11 UTC, annemwangi commented
> @annemwangi Good job with this article.
> 
> Do however take note of the value of working through your article from a reader's perspective to help catch any errors in your future work.
> 
> Otherwise, keep up the good work and I look forward to seeing more of your work published by EngEd.

Thanks a lot for taking the time to review my article and for the advice :rocket:

2022-03-02 09:38 UTC, WanjaMIKE commented
Merged #6282 via #5452

2022-03-02 09:38 UTC, merged