Testing Java Projects with JUnit and Mockito- Doing more with Mockito
section-engineering-education/engineering-education pull request #6291
Opened 2022-01-27 15:07 UTC by ehizman

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Pre-submission checks

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6138

2022-02-01 16:13 UTC, srishilesh commented
Hello @ehizman 

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review.

Meanwhile, we suggest you to go through approved PRs/published articles to see if you have missed out anything. This would help us avoid any potential closure of the PR.

Thanks.

2022-02-01 22:55 UTC, ehizman commented
> Hello @ehizman
> 
> Thanks for submitting this PR.
> 
> Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review.
> 
> Meanwhile, we suggest you to go through approved PRs/published articles to see if you have missed out anything. This would help us avoid any potential closure of the PR.
> 
> Thanks.

2022-02-04 05:08 UTC, ehizman commented
Hello @srishilesh 
It's been days now and my PR has not been attended to.
???

2022-02-07 14:41 UTC, srishilesh commented
Hey @ehizman ,

The peer-reviewers are working towards completing existing reviews to take up more. Please wait patiently until a peer-reviewer pings you to get started.

Thanks.

2022-02-09 03:47 UTC, srishilesh commented
Hey @ehizman ,

I'll get started with the preliminary review by EOD.

Thanks.

2022-02-09 05:02 UTC, srishilesh requested changes
Hey @ehizman ,

On going through your article, I found several instances where it requires explanation of code snippets. I've pointed out a few.

Moreover, this tutorial is a little low on content. I believe on addressing my suggestions, it should be good to go.

Also, I found several instances where the content was repetitive. Always make sure to re-read your article once you finish it.

As you know that, any PRs that requires major revisions will be closed. So, you make work on these changes locally, and create a new PR when done. Ping me in the new PR.

Let me know if you have any questions.

Thanks.

2022-02-09 05:02 UTC, closed without merging

2022-02-11 22:15 UTC, ehizman commented on content/articles/testing-java-projects-using-junit-and-mockito-doing-more-with-mockito/index.md
> +The aim of this tutorial is to guide readers on how to write effective units tests using Mockito and JUnit. This tutorial is a continuation of [Testing Java Projects using JUnit and Mockito](https://
What if I like a personal touch to my writing?

2022-02-12 07:58 UTC, srishilesh commented on content/articles/testing-java-projects-using-junit-and-mockito-doing-more-with-mockito/index.md
> +The aim of this tutorial is to guide readers on how to write effective units tests using Mockito and JUnit. This tutorial is a continuation of [Testing Java Projects using JUnit and Mockito](https://
@ehizman 
I totally get it. Here, at Section, it's a bit more formal. And, to maintain standards, we suggest this.

Alternatively, you can use "we", "us", "let's" and so on. You can take a look at other articles to see how they've done it.