How to use brotli compression method for web applications
section-engineering-education/engineering-education pull request #6334
Opened 2022-01-29 23:57 UTC by Newton-cyber

### Article checklist

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? 
- [X] Is your article properly formatted in Markdown? 
- [X] Have you used our preferred heading structure?
- [X] Does your article follow any of the suggested structure formats? 

- [X] Is your article over 750 words? 
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? 
- [X] Can your article be understood by beginners? 

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article?) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. 
- [X] Have you checked your article for readability? 

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting 
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #6215 `

2022-01-30 00:03 UTC, Newton-cyber commented
@srishilesh have taken time to do the requested revisions in this article

2022-01-30 00:07 UTC, Newton-cyber commented
@srishilesh would you help me delete the first article that comes up. #integration of ROS with Arduino. I've tried to delete it but ain't working

2022-01-30 09:49 UTC, srishilesh requested changes
Hey @Newton-cyber ,

I don't think you have addressed all my suggestions that was stated in #6215.

In this PR, I have specified an in-detail suggestion. Please go through them carefully and address them.

Also, I had asked you to go through other published tutorials. The standard for code and concepts explanation were not good, and was not very beginner friendly.

Since the article needs several revisions to be made, we would have to close this PR again.

Take some time to understand how other authors have done it. I'm sure you can do it too. You're almost there!

Ping me when you're done in the new PR.

Thanks.

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +Data compression is the process of encoding files to reduce their size, making them take up less space on your server and allowing them to be transferred to site clients more quickly. Compression red
`tatic assets` -> `static assets`

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +- Compression algorithms(Lossy & Lossless data compression)
What are they? Explain them in the below sections.

I believe this suggestion was not addressed from your previous PR

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +This is the process of reducing files in order to decrease their size and make them more portable.
Reducing files?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +During the decompression process, it's also utilized to restore data to its original state.
Since this is a technical article, I guess you would explain a little more deeper. This explanation is not enough

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +
Talk about what loss less and lossy compression are?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +*LZ77 algorithm*,*Huffman coding* and *second-order context modelling* are lossless type of data compression algorithms.
You haven't explained them here? I had asked you to add atleast 1 - 2 lines of explanations with references

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +First, download and build Brotli if it's not already installed on your system.
Where to download from? How do you install?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +The browser sends an `Accept-Encoding` header with the algorithms it supports and its order of precedence; the server chooses one, uses it to compress the body of the `content-encoding` header to inf
Again here, you have not addressed my suggestion.

I had asked you to add an image of the full header. it helps the reader understand better

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +- `content-encoding` response header lists any encodings that have been applied to the representation.
What is encoding? Explain

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +CDNs refers to distributed servers that work together to provide fast delivery of internet content.
I had asked you to explain this - you have done it. Good work!

But, adding more info on how brotli affects these would really help? How exactly would it work here?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +Nginx is an open-source web server that can also work as a reverse proxy.
Add reference

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +```
What are you doing here? There's no start or end to the tutorial. You have just stated this code snippet. You have not instructed what to do with this

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +gulp brotliCompress
Did you mention this in prerequisities?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +This is how to specify Brotli-encoded assets to Apache web server;
Why do you jump from nginx to apache? 

At least add proper heading.

The explanation for nginx was not enough

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +For browsers that do not understand Brotli encoding, you can also specify gzip-encoded version:
Which browsers do not understand?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +For browsers that do not understand Brotli encoding, you can also specify gzip-encoded version:
What version should we specify?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +```
What are you doing here?

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +
Explain

2022-01-30 09:49 UTC, srishilesh commented on content/articles/how-to-use-brotli-compression-method/index.md
> +Compared to *gzip*, Brotli is a more powerful compression method. You will experience significant sie speeed improvements when you use Brotli for static content, especially in low bandwidth settings.
Many typos and grammatical errors.

2022-01-30 09:49 UTC, closed without merging

2022-03-04 09:56 UTC, Newton-cyber commented
@srishilesh Please Reopen for me this PR for review

2022-03-10 11:11 UTC, Newton-cyber commented
@srishilesh I have taken time to Make the changes you requested

2022-03-10 13:25 UTC, srishilesh commented
Hey @Newton-cyber ,

I have already replied to the same message that you had asked me via Slack.

Let me repeat it here again.

As per the guidelines at Section, any PR that requires major revisions will be closed. And, the author would have reopen a new PR with all the changes addressed.

Fyi, this is already 2nd duplicate PR. If your next PR is closed, then your linked topic suggestion will also be closed. That means, you will have to suggest a new topic and work on it again.

Thanks.