Overview of Microsoft SSIS
section-engineering-education/engineering-education pull request #6366
Opened 2022-02-01 08:57 UTC by Yakobo5

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5939

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-02 15:29 UTC, Kimosop-Wakanda commented
Greetings @ahmadmardeni1 , @hectorkambow .
I would like to review this article.

2022-02-05 12:59 UTC, mbaabuones requested changes
@Yakobo5 Thank you for submitting your first article. I take this opportunity to welcome you to the Section Engineering program. I have noticed that you have already uploaded your author bio and photo. That is commendable. The article is informative and well structured. I have suggested some minor changes that can improve the quality of this article. Please work on ALL the suggested changes carefully to avoid closure of this PR. When you finish revising the article, proofread it to ensure there are no grammatical or typographical errors. Ping me when you are done so that I can continue with the review process.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +
Before the table of contents, write one or two introduction paragraphs showing what your article intends to cover. Look at other published articles like [this one](https://www.section.io/engineering-education/basics-of-means-end-analysis-in-ai/) to get an overview of how this is done.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +### Introduction
Rename this section 'Introduction to Microsoft SSIS and place it after the table of contents.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +- [SSIS Packages](#ssis-packages)
adjust this table of contents to correspond to the changes made in the document.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +The control flow is the main component of the SSIS package. It acts as the SSIS's brain.  It assists in arranging the execution sequence for all of its components. Containers and tasks are controlled
```suggestion
- **Control Flow:** The control flow is the main component of the SSIS package. It acts as the SSIS's brain.  It assists in arranging the execution sequence for all of its components. Containers and tasks are controlled using priority restrictions inside the components.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +2. Precedence Constraints
use the example in no. 1 above and apply it throughout this section.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +  * A container for sequences.  A Sequence Container enables a user to gather and arrange secondary tasks perform operations, and allocate logs to the container.
put the key words in bold.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +## SSIS Tasks
change it to level three header. Look at other published articles to see how headers are formatted.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +**Data Flow Task**
Use the suggestions in the section 'SSIS components' to format this section.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +**Event Handlers**
For all the sub-sections in this section, use level 5 headers.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +**1. Operational data**.
Use the suggested format in the section 'SSIS components'.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +
remove the extra spaces.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +2. SSIS uses tricky data to access, such as FTP, HTTP, and Analysis services, among others.
use consistent spacing.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +**1. Sorting**
use the suggested format in the section 'SSIS components'.

2022-02-05 12:59 UTC, mbaabuones commented on content/articles/microsoft-ssis/index.md
> +During the load operation, SSIS provides activities for transforming and validating data and transformations for inserting data into its destination. It's better to understand the various SSIS tasks
The conclusion can be optimized by providing a summary of what was covered in the article. Your conclusion should have at least two paragraphs.

2022-02-06 09:49 UTC, Yakobo5 commented
Hello @mbaabuones, I have made the requested changes

2022-02-08 19:42 UTC, louisefindlay23 commented
Plagiarism check complete

2022-02-08 20:50 UTC, hectorkambow commented
@mbaabuones  

Any update on this PR? :rocket

2022-02-09 10:49 UTC, mbaabuones approved these changes

2022-02-09 10:50 UTC, mbaabuones commented
> @mbaabuones
> 
> Any update on this PR? 🚀

@hectorkambow This article is in the tech review.

2022-02-27 18:17 UTC, hectorkambow commented
jumping on this one

2022-02-27 19:07 UTC, merged