Automating windows applications using Python
section-engineering-education/engineering-education pull request #6420
Opened 2022-02-03 09:37 UTC by Bonimum

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-07 14:52 UTC, srishilesh commented
Hello @Bonimum ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started.

Meanwhile, we suggest you to go through existing approved PRs/published articles to see if you have missed out anything.

Thanks.

2022-02-09 05:22 UTC, srishilesh requested changes
Hey @Bonimum ,

On going through your article, I found several errors - typos, typos in code snippets that might lead to compilation errors. The code snippets lacks explanation. The image paths are incorrect. Several markdown formatting changes needs to be done.

Moreover, this PR looks low on content. We definitely need to add new topics.

I feel we can change this title too. Since you are focusing on automating operations in notepad and excel - automating windows application would be incorrect. Can you think of a better title?

As you know, we accept only PRs that requires little or no revisions. Since your PR requires several revisions, we will be closing this PR.

You may create a new PR and ping me when done.

Let me know if you have any questions.

Thanks.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +In this article, I will be demonstrating how to automate boring stuff in windows using the Pywinauto module. Pywinauto is a bundle of Python modules for automating the Microsoft Windows GUI(Graphic u
Avoid using "I"

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +In this article, I will be demonstrating how to automate boring stuff in windows using the Pywinauto module. Pywinauto is a bundle of Python modules for automating the Microsoft Windows GUI(Graphic u
`Pywinauto` Add link

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +```python
bash

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> + - unpack and run `python setup.py install`
Add instructions on how each of these packages can be installed

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +We then need to retrieve the top window of the notepad. This can be implemented by:
What do you mean by top window?

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +This returns the top window for all opened apps including the notepad app. W lets add some text on the opened notepad application. The message we intend to display is passed as a string in the text a
`W lets add some text on`

Was it a typo?

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +We will now use `is maximize ()` technique to expand the notepad panel because it is not always in widescreen when notepad is opened.
`is maximize ()`

It's a typo

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +![Notepad](/automating-windows-applications-withpython/automating-notepad.jpg)
Image path is wrong. Refer the guidelines.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +![Notepad](/automating-windows-applications-withpython/automating-notepad.jpg)
Do we have any other additional operations to be performed on Notepad?

These content would be very less.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +f_path = r"D:\Users\Felix\mysample.xlsx" #file path
What's the difference between program path and file path?

By program, you mean the python file path?

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +f_path = r"D:\Users\Felix\mysample.xlsx" #file path
What exe file are you referring to? The installation file? Be specific

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +ap = application.Application ()
I guess this will give a compilation error. Can you recheck?

`ap = application.Application ()`

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +ap.top_windoow ():
It will give a compilation error.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +app = application.Application(backend= "uia"). start(r'{} "{}"'.format(p_path, f_path))
Compilation error again.

Explain the functions and parameters used

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +As we did with notepad, we must now choose the window `mysample.xlxs` that we need to deal with. Then print the results.
xlxs?

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +```
bash

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +[, , , ,]
Explain the output. Why do we get this? It's unclear

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +We can either `select ()` index window or simply get it by specifying the name.
`select()` ?

Explain further.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +![Excel](/automating-windows-applications-withpython/exel-1.jpg)
Incorrect image path.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +Because data is entered in cells A1, B1, C1, and D1, the automation id for cell A1 is A1, and the automation id for cell B1 is B1, and so on. The following is the program that we will use to read the
Use ` `` ` for keywords, variables or functions.

Eg: `A1`, `B1`

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +print("mysample.xlsx contains the following text:",(txt))
Explain what are we doing here. At least add comments.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +print("mysample.xlsx contains the following text:",(txt))
This will give a compilation error.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +```
bash

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +Inside the for loop, we are constructing an `auto_id`(automation id) for each cell, `dlg. child_window ()` is used to obtain certain aspects where the `auto_id` is supplied as an argument. Then we ut
This statement needs more explanation. Explain with proper context.

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> + ![Excel](/automating-windows-applications-withpython/exel2.jpg)
Incorrect path

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +#### Beautifull Soup
Typo

2022-02-09 05:22 UTC, srishilesh commented on content/articles/automating-windows-applications-withpython/index.md
> +
Add a GitHub repo URL containing the full source code

2022-02-09 05:22 UTC, closed without merging

2022-02-19 10:10 UTC, Bonimum commented
@srishilesh Still working on the changes . Will ping you when done

2022-03-13 03:58 UTC, srishilesh commented
Hey @Bonimum ,

Do we have any updates?

Let me know if you need any help.

2022-03-14 18:17 UTC, Bonimum commented
almost done plagiarism check remaining