Sending sms using twilio in flutter
section-engineering-education/engineering-education pull request #6442
Opened 2022-02-04 07:16 UTC by gideonkaruga

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4321`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-10 12:50 UTC, gideonkaruga commented
@WanjaMIKE @srishilesh a duplicate updated version on the idea

2022-02-10 13:35 UTC, srishilesh commented
Hey @gideonkaruga ,

Can you specify the duplicate PR number here? Also, ping your previous reviewer who was reviewing that.

2022-02-14 05:57 UTC, gideonkaruga commented
@srishilesh my apologies sir its not a duplicate.

2022-02-14 06:48 UTC, srishilesh commented
> @srishilesh my apologies sir its not a duplicate.

Hey @gideonkaruga ,

So, this PR is not related with #4616?

2022-02-14 07:05 UTC, gideonkaruga commented
@srishilesh I repeated the whole content but the topic is the same

2022-02-16 08:20 UTC, Kayere commented
Plagiarism check done ✅

2022-02-18 01:26 UTC, Jethro-magaji requested changes
Hi! @gideonkaruga 
Well done for such an amazing article. However, there are some corrections you need to make.
Please, run your article on tools like Grammarly and ProWritingAid for better editing.
Please change your author image and upload another a bit professional.
Also, try to add some images in your article to give the readers an idea of what they would build.
Thanks.

2022-02-18 01:26 UTC, Jethro-magaji commented on content/articles/sending-sms-twilio-in-flutter/index.md
> + - Conclusion
Add a "Prerequisites" section here, to provide the audience with any prerequisites that may be required to follow your tutorial.

2022-02-18 01:26 UTC, Jethro-magaji commented on content/articles/sending-sms-twilio-in-flutter/index.md
> +### Project Breakdown
Don't you think it would be necessary to talk about how to initialize a new flutter project?

2022-02-18 01:26 UTC, Jethro-magaji commented on content/articles/sending-sms-twilio-in-flutter/index.md
> +#### Key takeaways
Please rephrase these takeaways, it sounds like a question rather than what the reader would learn.

2022-02-18 01:26 UTC, Jethro-magaji commented on content/articles/sending-sms-twilio-in-flutter/index.md
> +```dart
Please properly format your code blocks, do this for all instances.

2022-02-18 01:26 UTC, Jethro-magaji commented on content/articles/sending-sms-twilio-in-flutter/index.md
> +### Conclusion
Include any next or final steps summarizing the tasks the audience just completed with possible next steps.

2022-02-18 06:44 UTC, gideonkaruga commented
@Jethro-magaji I hope its fine now

2022-02-18 19:39 UTC, hectorkambow commented
@Jethro-magaji  

If any other issues persist - we will be closing this PR. 
👍

2022-02-18 23:45 UTC, Jethro-magaji commented
Hi! @gideonkaruga 
You haven't made the necessary changes, it turns out your article would be needing a thorough editing, the EngEd peer review team don't offer editing services, please make use software editing tools to edit your work.

For now, I will be closing your PR to give you time to polish your article. When you're ready, ping me to reopen it.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or require help, you can reach out to me on the EngEd slack channel.
Thanks.

2022-02-18 23:46 UTC, closed without merging