Reading and processing android sensor data using python with CSV read()
section-engineering-education/engineering-education pull request #6457
Opened 2022-02-04 19:24 UTC by josephodhis

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #6159 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-07 14:56 UTC, srishilesh commented
Hello @josephodhis ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started.

Meanwhile, we suggest you to go through existing approved PRs/published articles to see if you have missed out anything.

Thanks.

2022-02-10 07:23 UTC, paulodhiambo requested changes
Amazing article, please add a link to complete source code.

2022-02-10 07:23 UTC, paulodhiambo commented on content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/index.md
> +![Offline processing](/engineering-education/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-four)
Add the image extension for this image

2022-02-10 14:33 UTC, louisefindlay23 commented
Plagiarism check complete

2022-02-12 16:28 UTC, josephodhis commented
@paulodhiambo changes made.

2022-03-09 08:09 UTC, Kayere requested changes
Hi @josephodhis, please go over the changes I have requested so I can continue with the final review.

2022-03-09 08:09 UTC, Kayere commented on content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/index.md
> +# python program to read .csv file
Maximum header size allowed is header three.

2022-03-09 08:09 UTC, Kayere commented on content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/index.md
> +import numpy as np
Please add backticks to your code snippets.

2022-03-09 08:09 UTC, Kayere commented on content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/index.md
> +#separate plots using subplots
Change this header size too.

2022-03-09 08:17 UTC, paulodhiambo commented
Hello @Kayere I made the corrections, didn't notice the contributor made some changes after completing tech review.

2022-03-09 09:29 UTC, Kayere commented
Hi @josephodhis, I am done with the final review. Just one request before I merge this PR. Please change your author avatar - upload a professional picture.

2022-03-09 10:31 UTC, josephodhis commented
@Kayere i have uploaded a new avatar.

2022-03-09 16:51 UTC, merged