Testing for Broken Authentication in Web Apps
section-engineering-education/engineering-education pull request #6467
Opened 2022-02-06 12:46 UTC by shosenwales

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #6224

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-07 14:57 UTC, srishilesh commented
Hello @shosenwales ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started.

Meanwhile, we suggest you to go through existing approved PRs/published articles to see if you have missed out anything.

Thanks.

2022-02-13 16:34 UTC, srishilesh requested changes
Hey @shosenwales ,

Good to see you again!

Great article! Found it interesting.

On performing a preliminary and tech review, I've suggested some minor changes. Please make sure to address all the changes before pinging me.

Avoid using "I"s, instead prefer "we", "let's", "us", and so on. And, add the missed sections that I've mentioned as part of suggestions.

Let me know when done.

Thanks.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +
A glimpse of what is going to covered in this article - would help.

Specify the goals and objectives.

Also, add a `Table of contents` and `Pre-requisites` sections.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +According to the [OWASP Top 10 2021 report](https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/), Broken Authentication is ranked number 7 and grouped under `Identification a
Add a little more about the report would definitely help - any insights from data or any new information that is relevant to this topic

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +To carry out this attack, I'll be making use of an intentionally vulnerable web application called [Juice shop](https://github.com/juice-shop/juice-shop).
Avoid using "I".

Instead use "we", "let's", or "us".

Do this change throughout the article.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +To carry out this attack, I'll be making use of an intentionally vulnerable web application called [Juice shop](https://github.com/juice-shop/juice-shop).
Do you run this locally? If so, brief a little about installation steps and setting up, before you get started with the actual stuff.

If you are not going to use local, then make sure to specify this hosted URL - http://demo.owasp-juice.shop/#/login

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +This is a poor practice because it allows for user enumeration. When an attacker uses brute force to guess valid users in a system, this is known as user enumeration.
Adding more explanation about user enumeration would help.

Add any reference links too.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +Firstly, I want to check how the application reacts if I provide incorrect login credentials.
State the correct login credentials first - before stating the incorrect ones. Do you register yourself first? 

If so, specify those steps before jumping into login

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +To demonstrate this, I'll try to login into the admin account and intercept the request using the burp suite.
Can you brief more about burp suite usage? How to use and what to do?

Add URL for it too.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +To demonstrate this, I'll try to login into the admin account and intercept the request using the burp suite.
What does it do? How does it help here? - Explain

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +I'll copy and click on paste in the payload options section.
Too many usage of "I"s. Avoid it.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +Next, I'll highlight the password parameter, this allows me to substitute the password value with a list of passwords. To do that I'll click on the `Add` button, click on the `payloads` tab, and unde
Why are we doing this?

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +
Add key takeaways from this article.

2022-02-13 16:34 UTC, srishilesh commented on content/articles/testing-for-broken-authentication-in-web-apps/index.md
> +- Multi-factor authentication: provide an extra layer of security for users.
Can you add reference links for each of the above methods? This might help the reader to follow up on each of the above said method.

2022-02-13 19:44 UTC, shosenwales commented
Hello, @srishilesh thanks for the review. I have made some changes, kindly go through them.

2022-02-14 04:07 UTC, srishilesh commented
@shosenwales 

Thanks for making the changes. I'll final review it ASAP.

2022-02-14 08:18 UTC, Kayere commented
Plagiarism check done ✅.

2022-02-14 15:56 UTC, srishilesh commented
Starting my final review on this.

2022-02-14 16:24 UTC, srishilesh approved these changes
Hey @shosenwales ,

Great work!

Thanks for making the changes. Moving for the final review.

Make sure to go through my commits to avoid these mistakes in the future.

Thanks.

2022-02-22 17:47 UTC, LinusMuema commented
Hi @shosenwales 

Awesome Job on the article.

cc: @srishilesh

2022-02-22 17:47 UTC, merged