How to perform containerized static application security testing(SAST) using MobSF within a Docker container
section-engineering-education/engineering-education pull request #6488
Opened 2022-02-07 16:09 UTC by RuthAMare

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #6058 `

2022-02-09 18:16 UTC, srishilesh commented
Hello @RuthAMare ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started.

Meanwhile, we suggest you to go through existing approved PRs/published articles to see if you have missed out anything.

Thanks.

2022-02-12 12:44 UTC, louisefindlay23 commented
Plagiarism check complete

2022-02-22 14:37 UTC, collins-a requested changes
Decent tutorial on SAST @RuthAMare. However, consider my review comments. Correctly paragraph your sentences where applicable and have a quick Grammarly check to handle a couple of errors.

2022-02-22 14:37 UTC, collins-a commented on content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/index.md
> +- [Advantages and Disadvantages of SAST](#advantages-and-disadvantages-of-sast)
Fix this link to reflect the subtopics in the body of your tutorial

2022-02-22 14:37 UTC, collins-a commented on content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/index.md
> +Customized reports downloadable and visible offline are supported by most SAST tools and can also be tracked through dashboards.
Consider arranging this section into paragraphs as opposed to rather isolated lines

2022-02-22 14:37 UTC, collins-a commented on content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/index.md
> +The above-mentioned detect security vulnerabilities in applications except in a unique way for each. Below are some of the critical comparisons of SAST between DAST:
Consider simplifying this line to better convey the contrast between SAST and DAST

2022-02-22 14:37 UTC, collins-a commented on content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/index.md
> +2.	A basic understanding of containerized storage.
It is likely that a reader may appreciate having the prerequisites section higher up the article to help them decide whether to continue reading.

2022-02-23 08:44 UTC, RuthAMare commented
> Decent tutorial on SAST @RuthAMare. However, consider my review comments. Correctly paragraph your sentences where applicable and have a quick Grammarly check to handle a couple of errors.

Thanks @collins-a , all changes made accordingly.

2022-02-23 11:56 UTC, collins-a approved these changes

2022-02-24 08:52 UTC, ahmadmardeni1 commented
Great work team. @RuthAMare @srishilesh

2022-02-24 08:52 UTC, merged