Wand library in python
section-engineering-education/engineering-education pull request #6583
Opened 2022-02-11 09:48 UTC by mukono10

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #4835

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-18 12:47 UTC, srishilesh requested changes
Hey @mukono10 ,

Congratulations on your first article at Section. Good work!

However, on a quick glance at your PR, I found several errors - both formatting and flow. I've suggested a few of them.

Moreover, the content of the article is too low - you have just blown up the article by repeating code snippets. No concepts have been dealt in-depth.

Also, the directories and image paths looks incorrect. And, I couldn't find a hero image.

I would highly recommend to go through the guidelines first and then make changes accordingly. You can also go through other approved PRs/published articles to see what you have missed out.

Since it requires too many revisions, I'm closing this PR. You can work on the changes locally, and ping me in your new PR - when done.

Let me know if you have any questions.

Thanks.

2022-02-18 12:47 UTC, srishilesh commented on content/authors/ezra-mukono/index.md
> +---
This is incorrect. Please refer to the guidelines or check other author files

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +Using Python programming language, which created a library known as Imagemagick, and this is what we term as the Wand. The library, therefore, provides Imagick API functionalities across various vers
`provides Imagick API functionalities across various versions of Python`

What functionalities

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +$pip install Wand
Remove `$` from the codes. It makes it easier for the reader to copy-paste things

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +```python
bash

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +Again, we must include the Imagick dependencies because the wand library is an Imagick API. And in our case, we are still  going to install the Imagick dependencies in Ubuntu Linux
Is it `Imagick` or `ImageMagick`?

It's inconsistent throughout the article.

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +Again, we must include the Imagick dependencies because the wand library is an Imagick API. And in our case, we are still  going to install the Imagick dependencies in Ubuntu Linux
Why separate installation in Linux? Doesn't Python installation suffice? Mention the reason for doing so

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +[ImageMagick](https://imagemagick.org/index.php) is an attribute developed to change the format of an image. ImageMagick is extensively used due to its capability to work with image formats in the br
Make the intro briefer

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +Another essential and robust feature of the Python wand is the image transform feature. It is used to transform an image to be displayed differently from the display of the original image. The image
What type of transformation can be done? State them. These statements are unclear.

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +```
What are you doing here? Like what does `flip()` do? Don't say flip function helps you flip the image. Explain

2022-02-18 12:47 UTC, srishilesh commented on wand-library-in-python/index.md
> +### Defining Wand library.
Add pre-requisities and table of contents sections.

2022-02-18 12:47 UTC, closed without merging

2022-02-19 07:15 UTC, mukono10 commented
@srishilesh I have done the changes, you can reopen so that I can resubmit

2022-02-21 19:31 UTC, mukono10 commented
@srishilesh I already made the changes ,, open so that I can submit it

2022-02-22 03:40 UTC, srishilesh commented
Hey @mukono10 ,

As you might have seen the guidelines, any PR that requires major revisions will be closed. You would have to work on them locally, and push to create a new PR.

We reopen PRs only in exceptional cases. But, since there were some major revisions to be done, we suggest you to create a new PR 

After you create a new PR, ping me in the PR.

Thanks

2022-02-22 03:49 UTC, mukono10 commented
Thanks @srishilesh