Introduction to Prisma with Docker
section-engineering-education/engineering-education pull request #6593
Opened 2022-02-11 17:31 UTC by Faithdroid

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #4322

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-22 18:10 UTC, srishilesh commented
I'll complete my preliminary review by tomorrow.

2022-02-23 17:36 UTC, WanjaMIKE commented
There appears to be several sentences taken from other sources. Please correct them. Thanks
[New Scan 5_19 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8126522/New.Scan.5_19.PM.Copyleaks.Report.pdf)

2022-02-24 12:39 UTC, srishilesh requested changes
Hey @Faithdroid ,

Thanks for submitting this PR.

Please carefully go through the minor suggestions that I've made. Also, make sure to recheck the plagiarism report.

Ping me when you're done with the changes.

Thanks.

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +Prisma falls under the category of an ORM, and it has all features of a typical ORM, such as mongoose and sequelize. Unlike the other ORM, Prisma comes with a tone of other added features. Prisma is
Can you break down these paragraphs into smaller ones? One paragraph must talk about one idea.

Also, add necessary reference links. For example, for ORM, MongoDB, AWS Aurora and so on.

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +
Can you add a `Table of contents` and `Prerequisities` sections

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +1. Ensure you have Prisma installed on your computer.
Add steps to install them. Also, add reference link

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +This guide also runs Prisma using Docker. Ensure you have [Docker](https://www.docker.com/products/docker-desktop) installed on your computer and have some basic knowledge of running and using Docker
You can move these to the pre-requisities section

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +- Prisma migrate
```suggestion
#### Prisma migrate
```

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +- Prisma migrate
Do the same for the remaining 2 sub-topics

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +```bash
Isn't it `dockerfile`?

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +```bash
Isn't it `dockerfile`?

2022-02-24 12:39 UTC, srishilesh commented on content/articles/dockerized-prisma-postgres-api/index.md
> +
Can you add a GitHub URL containing your source code?

Also, add a `Further reading` section that contains reference links

2022-02-24 13:56 UTC, Faithdroid commented
Hello, check this @srishilesh

2022-02-25 14:07 UTC, srishilesh commented
Hey @Faithdroid ,

Thanks for making the changes.

Let me start my tech review. Will keep you posted about it.

Thanks.

2022-02-28 13:22 UTC, srishilesh commented
I'll complete my final review by tomorrow.

2022-03-02 14:15 UTC, srishilesh commented
Starting my final review

2022-03-02 16:34 UTC, srishilesh commented
I've reviewed almost 40% of the article. It is longer than usual, so it's taking time.

I'll make sure to complete it by tomorrow.

2022-03-03 08:40 UTC, srishilesh approved these changes
Hey @Faithdroid ,

Great article.

Make sure to go through the changes I've made.

Moving for the final review.

Thanks.

2022-03-09 17:42 UTC, hectorkambow commented
jumping on this one

2022-03-09 18:46 UTC, merged