tutorial completed for flutter speech recognition using alan voice
section-engineering-education/engineering-education pull request #6628
Opened 2022-02-13 17:48 UTC by Eze4Manuel

This resolves issue #5933

2022-02-16 09:02 UTC, ahmadmardeni1 commented
Why did you delete the template? I've edited your initial comment. Please check what matches your article. @Eze4Manuel

2022-02-17 14:57 UTC, Eze4Manuel commented
@ahmadmardeni1  
I have checked all that matches my article. Thnaks

2022-02-23 00:54 UTC, Eze4Manuel commented
Hello Ahmad,
I have checked and updated the matches as you requested. Please check and
let me know of any changes or updates needed to my tutorial.

Thank you.


On Wed, Feb 16, 2022 at 10:02 AM Ahmad Mardeni ***@***.***>
wrote:

> Why did you delete the template? I've edited your initial comment. Please
> check what matches your article. @Eze4Manuel
> <https://github.com/Eze4Manuel>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/6628#issuecomment-1041263125>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALU74VOP5HK5PP6S7G6JQ5DU3NR2NANCNFSM5OJMRVRQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/6628/c1041263125
> @github.com>
>

2022-02-28 08:18 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-03-05 03:35 UTC, Jethro-magaji requested changes
Hi! @Eze4Manuel 
Well done for such an amazing article. However, there are some corrections you need to make.
Please, run your article on tools like Grammarly and ProWritingAid for better editing. This would save the review time to review your work.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-03-05 03:35 UTC, Jethro-magaji commented on content/articles/flutter_speech_recognition_using_alan_voice/index.md
> +![set-up-application](/flutter_speech_recognition_using_alan_voice/application.png)
Please format all your image path like this ! [starting] (/engineering-education/create-a-registration-form-using-react.js-and-connecting-it-with-firebase/start.PNG)

2022-03-05 03:35 UTC, Jethro-magaji commented on content/articles/flutter_speech_recognition_using_alan_voice/index.md
> +### Prerequisite
Please put all your prerequisite in an unordered list format, also include other prerequisites necessary for the reader to follow along such as a preferable IDE, Flutter SDK version, Alan SDK etc.

2022-03-05 03:35 UTC, Jethro-magaji commented on content/articles/flutter_speech_recognition_using_alan_voice/index.md
> +```dart
Please properly explain all your code below each block and add an in-line comment if necessary.

2022-03-05 03:35 UTC, Jethro-magaji commented on content/articles/flutter_speech_recognition_using_alan_voice/index.md
> +
Add a link to the complete code on GitHub.

2022-03-06 20:16 UTC, Eze4Manuel commented
Hello Jethro, I have made all the updates and adjustments you highlighted.

2022-03-09 22:20 UTC, hectorkambow commented
> Hello Jethro, I have made all the updates and adjustments you highlighted.

@Eze4Manuel have you gone through the entire article to check for other mistakes? Our peer reviewers are not expected to POINT OUT everything. 👍

2022-03-14 04:51 UTC, Jethro-magaji approved these changes
Hi! @Eze4Manuel 
Well done for coming up with such an amazing article. Please take note of these corrections to minimize revision next time.
Thanks

2022-03-15 10:46 UTC, WanjaMIKE commented
Merged #6628 into master

2022-03-15 10:47 UTC, merged