Collapsing action tool bar with android material design in Kotlin
section-engineering-education/engineering-education pull request #6629
Opened 2022-02-13 18:14 UTC by dvoredave

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5333 `

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-28 08:19 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-03-05 03:56 UTC, Jethro-magaji requested changes
Hi! @auxesis 
Well done for such an amazing article. However, there are some corrections you need to make.
Please, run your article on tools like Grammarly and ProWritingAid for better editing. This would save the review time to review your work.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. If you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-03-05 03:56 UTC, Jethro-magaji commented on content/authors/author/index.md
> +
Please edit your author bio in the proper Markdown format. Here's an [example](https://raw.githubusercontent.com/section-engineering-education/engineering-education/master/content/authors/adith-bharadwaj/index.md)

2022-03-05 03:56 UTC, Jethro-magaji commented on content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/index.md
> +
Add a Prerequisites' section here, to provide the audience with any prerequisites that may be required to follow your tutorial. For example: Need basic HTML and CSS knowledge for an article on how to use the CSS pre-processor, Sass.

2022-03-05 03:56 UTC, Jethro-magaji commented on content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/index.md
> +![Title background](engineering-education/collapsing-action-tool-bar-with-android-material-design-in-kotlin/title-bg.png)
Like this `/engineering-education/` not this `engineering-education/`

2022-03-05 03:56 UTC, Jethro-magaji commented on content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/index.md
> +We need an emulator(virtual device) installed in the computer or an actual physical device such as a mobile phone or a phone tablet.
`Emulator (virtual device)` should be listed in the prerequisites section.

2022-03-05 10:19 UTC, dvoredave commented
Hello @Jethro-magaji, I made the changes as requested. Thank you.

2022-03-09 22:21 UTC, hectorkambow commented
@dvoredave 
have you gone through the entire article to check for other mistakes? Our peer reviewers are not expected to POINT OUT everything. 👍

2022-03-15 02:58 UTC, Jethro-magaji commented
Hello @dvoredave 
Seems like you have 2 accounts on Section EngEd, and it's causing a merge conflict.
Please upload a high resolution free stock hero image 600x400px.

2022-03-15 22:49 UTC, Jethro-magaji approved these changes
Hi! @dvoredave 
Well done for coming up with such an amazing article. Please take note of these corrections to minimize revision next time.
Thanks.

2022-03-21 20:21 UTC, hectorkambow commented
jumping on this one

2022-03-21 21:00 UTC, hectorkambow commented
@dvoredave 

Can you please DM via Slack asap

2022-03-21 21:00 UTC, hectorkambow commented
@davidginmaina

2022-03-21 21:01 UTC, hectorkambow commented
Why do you both have the same name again?

2022-03-21 21:07 UTC, merged