Getting Started With Debugging In Android Using Chucker
section-engineering-education/engineering-education pull request #6673
Opened 2022-02-15 14:16 UTC by Hepatrique

### Article checklist

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5579

2022-02-17 09:46 UTC, Kayere commented
Hello @Hepatrique,

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Getting Started With Debugging In Android Using Chucker #6673 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8087487/Getting.Started.With.Debugging.In.Android.Using.Chucker.6673.Copyleaks.Report.pdf)

2022-02-18 06:53 UTC, Dawe-7 commented
@Kayere, can we run another plagiarism check, thanks.

2022-02-25 09:41 UTC, Hepatrique commented
Hello @WanjaMIKE, and @Dawe-7  I think the flags are raised on the code which I cannot change then it is also below 10% as per the rule.

2022-02-26 05:21 UTC, Dawe-7 commented
> Hello @WanjaMIKE, and @Dawe-7 I think the flags are raised on the code which I cannot change then it is also below 10% as per the rule.

@WanjaMIKE, is this article ready for review or do we need to run another plagiarism check?

2022-03-01 22:52 UTC, WanjaMIKE commented
@Hepatrique could you correct the few sentences showing some plagiarism. I shared the report. You can leave the boilerplate code. Thanks

2022-03-02 07:57 UTC, Hepatrique commented
Hello @WanjaMIKE , and @Dawe-7 , I have done the changes as suggested and I now hope the article is ready for review.

2022-03-02 08:02 UTC, WanjaMIKE commented
I think, they are enough. You can proceed with the review. Thanks

2022-03-11 09:36 UTC, Dawe-7 requested changes
Nice article @Hepatrique . Make the suggestions below. Also, ensure your images are of required size 600x400 pixels. Make sure you resize your hero image along with other images used in the article.

Make the changes so we can move on to tech review.

2022-03-11 09:36 UTC, Dawe-7 commented on content/articles/debugging-with-chucker/index.md
> +Also, ensure Java 8 support is enabled by ensuring that the code below is present in your app-level `build.gradle` file inside the `android` block.
Which code are you referring to?

2022-03-11 09:36 UTC, Dawe-7 commented on content/articles/debugging-with-chucker/index.md
> +In the dependencies, we have added the OkHttp library because Chucker works with its interceptor. The coroutines library is added because OkHttp involves network calls.
Does the OkHttp `involves` network calls or `invokes`?

2022-03-11 19:27 UTC, Hepatrique commented
Hello @Dawe-7 , I have done the correction, it was a typo error and it ought to be `invokes`.

2022-03-12 08:04 UTC, Dawe-7 commented
> Hello @Dawe-7 , I have done the correction, it was a typo error and it ought to be `invokes`.

@Hepatrique 

> Hello @Dawe-7 , I have done the correction, it was a typo error and it ought to be `invokes`.

@Hepatrique, kindly ensure you effect all the changes requested.

2022-03-12 21:10 UTC, Hepatrique commented
@Dawe-7 , I have done the suggested changes

2022-03-15 05:30 UTC, Hepatrique commented
@Dawe-7, kindly proceed to the final review. I have tried resizing the images as suggested. Thank you!!!

2022-03-16 17:53 UTC, Dawe-7 approved these changes
Nice article @Hepatrique. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles.

2022-03-16 20:52 UTC, hectorkambow commented
@Hepatrique 

@Dawe-7 

![image](https://user-images.githubusercontent.com/60800358/158688914-0082d394-d0fe-43fe-b625-7fa767bd30ae.png)

2022-03-18 05:55 UTC, closed without merging