Using Big Data analytics to fight cybersecurity threats
section-engineering-education/engineering-education pull request #6695
Opened 2022-02-16 21:40 UTC by Petekavinsky

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #6575

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-02-18 07:53 UTC, jerimkaura commented
Hello @Petekavinsky 

Thanks for submitting your article for review. You must have removed the pre-submission checks. I am adding them for you so that you do the checks before we begin the review.

2022-02-18 08:21 UTC, Petekavinsky commented
@jerimkaura, Thank you I have checked the boxes

2022-02-20 12:04 UTC, jerimkaura requested changes
Hello @Petekavinsky 

Thanks for submitting your article for review. You have a wonderful article but considering the major readability issues identified, consider re-reading the article to eliminate the mistakes and polish it well.

We highly encourage our author to only create PRs for publish-ready articles.

2022-02-20 12:04 UTC, jerimkaura commented on content/articles/using-big-data-analytics-to-fight-cyber-threats/index.md
> +1. In Fraud Detection, Big Data Analytics is Used. Statistical approaches and artificial intelligence techniques are the two main fraud detection tools.
At least introduce the reader to what you are talking about in this context.

2022-02-20 12:04 UTC, jerimkaura commented on content/articles/using-big-data-analytics-to-fight-cyber-threats/index.md
> +### Anamoly-Based Intrusion Detected Using Big Data Analytics
This heading seems unclear.

2022-02-20 12:04 UTC, jerimkaura commented on content/articles/using-big-data-analytics-to-fight-cyber-threats/index.md
> +They can speed up the process of forensic data correlation and create proactive security responses.
What can assist in the gathering of ......?

2022-02-20 12:04 UTC, jerimkaura commented on content/articles/using-big-data-analytics-to-fight-cyber-threats/index.md
> +### Challenges
Use descriptive heading for easy understanding and effective SEO

2022-02-20 23:37 UTC, Petekavinsky commented
@jerimkaura,I've completed all of the necessary changes.

2022-02-22 14:45 UTC, Adespscientist commented
@jerimkaura, What is the update on my PR please

2022-02-23 17:33 UTC, WanjaMIKE commented
Hi @Petekavinsky 

Your article appears to have many sentences that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/). We're really looking for unique/original content.

[New Scan 5_20 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8126507/New.Scan.5_20.PM.Copyleaks.Report.pdf)

2022-02-23 17:33 UTC, closed without merging