Integrating MongoDB with java
section-engineering-education/engineering-education pull request #6743
Opened 2022-02-18 21:20 UTC by muthoni2-lucy

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #4206

2022-02-25 13:57 UTC, srishilesh requested changes
Hey @muthoni2-lucy ,

Congratulations on submitting your first PR!

On a quick glance at your PR, I noticed that we might need several changes. I've suggested a few of them like:
- Your article must be inside `content/articles`.
- The article directory name must be lowercase separated by `-`, not `Integrating MongoDB with Java/index.md`
- The markdown formatting is not followed. Refer guidelines.
- `content/authors/Christine-irungu/Avatar.jpg` Every directory/file name must be in lowercase
- Perform a grammar check
- The code snippets are not enclosed within the markdown quotes
- The image paths are incorrect.

I would highly recommend you to take a step back, go through the contribution guidelines very carefully. You may also read merged PRs/published articles to see how other authors have formatted and structured the flow of the article.

Since your PR requires some major revisions, we will be closing this PR. However, you may work on the changes locally, create a new PR and ping me when you're done.

Visit the EngEd new contributor's docs [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md).

Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) of one of my articles which has little or no revisions to be made, to guide you on formatting.

Let me know if you have any questions.

Thanks.

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +MongoDB is a no SQL database where records get stored in documents. It uses Jason syntax a JavaScript Object Notation to store data. When integrating MongoDB with java it uses a different syntax.
`no SQL database`

It's NoSQL

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +MongoDB is a no SQL database where records get stored in documents. It uses Jason syntax a JavaScript Object Notation to store data. When integrating MongoDB with java it uses a different syntax.
`Jason syntax`???

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +MongoDB is a no SQL database where records get stored in documents. It uses Jason syntax a JavaScript Object Notation to store data. When integrating MongoDB with java it uses a different syntax.
`java` -> `Java`

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +In this article, you'll learn how to connect MongoDB with java using eclipse and learn crud (create, read, update and delete)  operations using Java and MongoDB Java Driver. MongoDB is based on a doc
`crud` -> `CRUD`

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +**Table of content**
Use `###` markdown headers. Read the guidelines

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +- [Conclusion](#Conclusion)
Remove extra new lines

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +Eclipse versus Intellij Idea in MongoDB integration with java
Write full sentences. And, make them bulleted points.

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +5. Java JDK
Why do we have 2 prerequisite sections?

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +6. RDBMS is slower than MongoDB.
You have just stated facts. Explanation is needed

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +After running, you can show how many databases are currently available within your MongoDB
Use ` `` ` for keywords, variables or single line code snippets.

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +             import com.mongodb.client.model.Updates;
Use markdown for code snippets

2022-02-25 13:57 UTC, srishilesh commented on Integrating MongoDB with Java/index.md
> +![cmd 3](image5.png)
Image path is incorrect. Refer guidelines

2022-02-25 13:58 UTC, closed without merging

2022-02-27 08:51 UTC, muthoni2-lucy commented
Hey @srishilesh I pinged you at my new pr #6844