Micro Frontends Using Module Federation In Solid.js
section-engineering-education/engineering-education pull request #6751
Opened 2022-02-19 12:53 UTC by oyedeletemitope

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
>

`This closes #6547 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-01 04:47 UTC, jumamiller commented on content/articles/microfrontend-using-module-federation-in-solid.js/index.md
> +Micro frontend originated from the concept of microservice. When we’re talking about micro frontends, think of it as a website composed of different web pages. These pages consist of features created
Let's ensure that a paragraph is as short and precise. This looks too wordy. Update where applicable!

2022-03-01 04:47 UTC, jumamiller commented on content/articles/microfrontend-using-module-federation-in-solid.js/index.md
> +
Do away with these spaces throughout your article!

2022-03-01 04:48 UTC, jumamiller commented on content/articles/microfrontend-using-module-federation-in-solid.js/index.md
> +#### By Functionality
Follow the English rules. No uppercase in the middle of the sentence? Update where applicable!

2022-03-01 04:49 UTC, jumamiller requested changes
What are the requisites to follow along with this tutorial? if not available, why YARN and not the popular NPM?

2022-03-01 04:50 UTC, jumamiller commented
ALso ensure your code snippets are well explained!

2022-03-01 09:05 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-03-01 09:47 UTC, oyedeletemitope commented
> 
I'm using yarn because npm has been giving some errors unlike yarn plus it's what I'm comfortable with.

2022-03-04 09:35 UTC, oyedeletemitope commented
> What are the requisites to follow along with this tutorial? if not available, why YARN and not the popular NPM?

I'm using yarn because npm has been giving some errors unlike yarn plus it's what I'm comfortable with.

2022-03-04 09:35 UTC, oyedeletemitope commented
> ALso ensure your code snippets are well explained!

changes made. please let me know if there's anything else

2022-03-06 13:42 UTC, jumamiller commented
> > What are the requisites to follow along with this tutorial? if not available, why YARN and not the popular NPM?
> 
> I'm using yarn because npm has been giving some errors unlike yarn plus it's what I'm comfortable with.

Remember an article is for all readers interested in your topic and should be as general as possible! Just give alternative commands in NPM.

2022-03-07 10:06 UTC, oyedeletemitope commented
> > > What are the requisites to follow along with this tutorial? if not available, why YARN and not the popular NPM?
> > 
> > 
> > I'm using yarn because npm has been giving some errors unlike yarn plus it's what I'm comfortable with.
> 
> Remember an article is for all readers interested in your topic and should be as general as possible! Just give alternative commands in NPM.

I have added the npm commands as requested

2022-03-09 06:38 UTC, jumamiller commented
Hi, could you also work on the repetitions? For instance, you're using one word a couple of times in a sentence,`In this tutorial, we'll be discussing micro frontends. We'll also set up micro frontends using module federation in Solid.js. `

In this case, `micro frontends` has been used twice. This is not the only case in your article, others such as `that` among others are very repetitive. Kindly be precise and and avoid repeating yourself.

2022-03-09 06:40 UTC, jumamiller commented
> Hi, could you also work on the repetitions? For instance, you're using one word a couple of times in a sentence,`In this tutorial, we'll be discussing micro frontends. We'll also set up micro frontends using module federation in Solid.js. `
> 
> In this case, `micro frontends` has been used twice. This is not the only case in your article, others such as `that` among others are very repetitive. Kindly be precise to avoid repeating yourself.

Ensure images extensions are also in lowercase, let's just maintain the standards put in place!, I. e `image.png` and not `image.PNG`.

2022-03-09 08:24 UTC, oyedeletemitope commented
> > Hi, could you also work on the repetitions? For instance, you're using one word a couple of times in a sentence,`In this tutorial, we'll be discussing micro frontends. We'll also set up micro frontends using module federation in Solid.js. `
> > In this case, `micro frontends` has been used twice. This is not the only case in your article, others such as `that` among others are very repetitive. Kindly be precise to avoid repeating yourself.
> 
> Ensure images extensions are also in lowercase, let's just maintain the standards put in place!, I. e `image.png` and not `image.PNG`.

HI @jumamiller Changes made as requested

2022-03-14 11:28 UTC, jumamiller approved these changes
Hi, @oyedeletemitope Kindly review if your details are well captured and that your article is well-edited to deliver the concept as you expected. Thank you!

2022-03-14 13:09 UTC, oyedeletemitope commented
Thanks @jumamiller . I've gone through it. Your edits and suggestions were invaluable. Thank you so much

2022-03-22 18:46 UTC, LinusMuema commented
Hi @oyedeletemitope 

Good job on the article. Please check my commit for the changes.

cc: @jumamiller

2022-03-22 18:47 UTC, merged