Understanding shared memory programming with Pthreads and OpenMP
section-engineering-education/engineering-education pull request #6770
Opened 2022-02-20 22:00 UTC by carteblanchemunene

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6135

2022-03-03 07:57 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-03-08 09:45 UTC, jerimkaura requested changes
Hello @carteblanchemunene, Great article here.

While most of your snippets run smoothly, the grammar is a bit off. You have elements of incomplete sentences, hanging phrases and non-related clauses.

Ensure that your content is clear and flows accurately. Each paragraph should have a meaning composed of related sentences.

I only highlighted a single instance but there are several. Work on that so that we move to the next round of review.

Thanks.

2022-03-08 09:45 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +This specifies a parallel chunk of code (omp pragma). Whenever a parallel segment is reached, slave threads are established. The parallel code may run on another thread. Threads finish and join the m
There seem to be some incomplete statements here. Would you please check it out?

2022-03-10 14:07 UTC, jerimkaura requested changes
Hello @carteblanchemunene 

You have a great article but it sounds incomplete. I feel that you have covered the topic very narrowly. Please revise the topic, add more content and ensure proper flow of content.

Thanks.

2022-03-10 14:07 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +Shared memory is used to speed up data flow between programs. Depending on the circumstance, programs may operate on one or more processors. As a result, a process may have several threads. Threads a
It would really be helpful if we help the reader understand why we call Threads 'light-weight-processes'.

2022-03-10 14:07 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +In the shared memory paradigm, data is not assigned. Changes made to one thread in the shared memory paradigm affect all the other threads.
What is the other paradigm?

2022-03-10 19:54 UTC, carteblanchemunene commented
@jerimkaura, am done adding content please check.

2022-03-12 15:54 UTC, jerimkaura requested changes

2022-03-12 15:54 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +Shared memory is used to speed up data flow between programs. Depending on the circumstance, programs may operate on one or more processors. As a result, a process may have several threads. Threads a
So which between threads and processes share addresses?

2022-03-12 15:54 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +Parallelism is achieved by threading a process. Parallelism is a state where many processes are carried out simultaneously. Browser tabs, for example, are threads. Likewise, MS Word uses threads to f
A reader maybe confused here, in one instance you talk of threads, in another, you talk of processes being threaded.

2022-03-12 15:54 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +System architecture may use single-core or multicore processors. A single-core processor operates one thread, while a multicore processor runs several threads at a time.
What is a system architecture?

2022-03-12 15:54 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +To delete a segment, supply `IPC RMID` as the second parameter and NULL as the third argument. Segment removal occurs after all processes that were previously connected have been deleted. To prevent
Would you please show how these commands are used and example use cases?

2022-03-12 15:54 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +Assuming everything goes well, a thread will end by executing `pthread_exit` or returning from its thread function. A thread may, however, request that another thread be terminated. This is referred
This is a very long sentence. Consider breaking it into smaller sentences with independent meanings.

2022-03-12 15:54 UTC, jerimkaura commented on content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
> +An asynchronously cancelable thread may be stopped at any time. On the other hand, asynchronously cancelable threads may be canceled only at certain points. These are cancellation spots where the thr
Break this paragraph.

2022-03-12 15:58 UTC, jerimkaura commented
Hey @carteblanchemunene 

Please work on the article well to achieve maximum reliability. Check with already published content here to help you gauge the quality of articles that are published.

Reviewers are not allowed to perform many edits of articles and your article seems a bit below the threshold. 

Your article is great! Just take time to polish it so that by the time it gets to the queue again, it is publish-ready.

Thanks.

2022-03-12 15:58 UTC, closed without merging