Cookies and Sessions in ASP dot NET
section-engineering-education/engineering-education pull request #6807
Opened 2022-02-23 09:17 UTC by swambui1

### Article checklist
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #5879

2022-03-03 14:46 UTC, tesswambui commented
@WanjaMIKE  can you have a look at this PR, will appreciate. has been over a week and no one has been assigned this PR.

2022-03-07 08:04 UTC, swambui1 commented
@hectorkambow  @ahmadmardeni1 , this pr has been here over a week and has not been assigned for review, kindly help.

2022-03-15 15:04 UTC, LinusMuema commented
plagiarism check done ✅

2022-03-16 12:09 UTC, Jethro-magaji requested changes
Hi! @swambui1 
Well done for such an amazing article. However, there are some corrections you need to make.
 Run your article on tools like Grammarly and ProWritingAid for better editing. This would save the time to review your work.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-03-16 12:09 UTC, Jethro-magaji commented on content/articles/cookies-and-sessions-in-asp-dot-net/index.md
> +Session gets initiated when a user hits an application for the first time.
A session gets ........

2022-03-16 13:29 UTC, swambui1 commented on content/articles/cookies-and-sessions-in-asp-dot-net/index.md
> +Session gets initiated when a user hits an application for the first time.
@Jethro-magaji on it right away

2022-03-16 15:30 UTC, swambui1 commented
@Jethro-magaji  am done with the requested changes, you can proceed with the review thank you.

2022-03-16 20:35 UTC, hectorkambow commented
@swambui1 
Please be sure to proofread the entire article as Peer Reviewers do not provide revisions services (and may not point out all pending issues).
If any other edits are required @Jethro-magaji we can close the PR to allow the student the proper time to make the edits.

2022-03-21 20:17 UTC, swambui1 commented
@hectorkambow, my reviewer is currently working on this pr

2022-03-21 20:18 UTC, hectorkambow commented
cc @Jethro-magaji

2022-03-21 20:29 UTC, Jethro-magaji commented
> cc @Jethro-magaji 

Am currently working on the PR.

2022-03-22 16:48 UTC, Jethro-magaji approved these changes
Hi! @swambui1 
Well done for coming up with such an amazing article. Please take note of these corrections to minimize revision next time.
Thanks.

2022-03-30 10:38 UTC, WanjaMIKE commented
Merged #6807 into master

2022-03-30 10:39 UTC, merged