Implementing Android Jetpack Preferences
section-engineering-education/engineering-education pull request #6819
Opened 2022-02-23 20:30 UTC by mercie-nyakio

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3909

2022-03-03 07:57 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-03-07 20:38 UTC, BrianaNzivu requested changes
Hey @mercie-nyakio   👋 .

First of all, welcome to Section - EngEd. 🎉
We are happy to have you here.

My name is Briana, I'll be reviewing your article for publishing. I will make this review as fast and as swift as possible, with your help of course 😄 .

Good job on the article. It is a very interesting read. 

Just a few changes I need you to make as we continue with the preliminary revisions:
- Please structure your article according to this [sample](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md). I need you to clearly highlight and explain your steps. Where you can add more detail please do so.
- Please upload your author info. You can find the instructions [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md).
- Refer to the other comments I have made.

In case of any question or help needed please do not hesitate to ping me here or on Slack.
Also, notify me when you are done both here and on Slack.

Regards.

2022-03-07 20:38 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +- Select *` Empty activity`* as your project template. Click *` next`* to proceed to the next steps.
Have this in paragraph form.

2022-03-07 20:38 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +#### Adding a menu to the main activity
Highlight the steps probably i.e Step one: Adding a menu to the MainActivity

2022-03-07 20:38 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +```Kotlin
This is xml

2022-03-07 20:38 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +```Kotlin
This is also xml

2022-03-08 22:42 UTC, mercie-nyakio commented
hello @BrianaNzivu  I have done the requested changes.

2022-03-16 20:26 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +These are just a few options our app needs. A customizable app setting is also a superb strategy to enhance the Android app user experience. The Android Preference Library manages user preferences. U
I think this introduction can be better and a little bit more detailed.

2022-03-16 20:41 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +- To add a menu resource, click the project folder on the left side of the `IDE` or simply `alt+1` -> app -> res folder.
Have this as a paragraph

2022-03-18 12:38 UTC, mercie-nyakio commented
hello @BrianaNzivu, am done with the requested change.

2022-03-21 20:07 UTC, BrianaNzivu commented on content/articles/implementing-android-jetpack-preferences/index.md
> +You can run the application to a virtual device(emulator) or a physical device with an `SDK` version upper than the set one during app configuration.
You can link a Github repo here with the code for this project.

2022-03-21 20:07 UTC, BrianaNzivu commented
Proceeding with tech review 👍

2022-03-21 20:48 UTC, BrianaNzivu commented
Tech review done 👍 

Waiting for the minor addition I have requested for a final review to be done.

2022-03-22 19:28 UTC, mercie-nyakio commented
hello @BrianaNzivu, I have added link to the Github repo. Please check

2022-03-22 20:36 UTC, BrianaNzivu approved these changes
Hey @mercie-nyakio 👋 .

Very good job on the article.  

- Please check out the resources page for tools which can help increase the quality of your writing. 
- Please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

2022-04-01 12:11 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +Currently, we have preference windows in almost every software we use, enabling users to tailor their settings to their specifications.
I don't really understand this sentence.

2022-04-01 12:12 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +For example, apps like YouTube enable users to choose between dark and bright modes, pick the download quality, control notifications, and other parameters with a single click, which is an excellent
A whole paragraph is a single sentence. This cannot be. Break it down.

2022-04-01 12:13 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +In this article, we will create a simple setip screen using the Android Preference Library.
setup rather than `setip`

2022-04-01 12:15 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +We will achieve that by adding a click listener to each item(s). To add a menu resource, he following steps should be followed;
`the` rather than `he`

2022-04-01 12:17 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +In this step we will add another activity to our main project. Double-click `app file -> java file -> application package name(com._.androidprefernces)`. Right-click the file -> new -> `activity` ->
In this step, (comma)

2022-04-01 12:17 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +In this step we will add another activity to our main project. Double-click `app file -> java file -> application package name(com._.androidprefernces)`. Right-click the file -> new -> `activity` ->
new `A`ndroid activity ...

2022-04-01 12:19 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +>Note: The new settings activity comes with files in it. Such files include:
Is it the activity or folder/dir?

2022-04-01 12:20 UTC, WanjaMIKE commented on content/articles/implementing-android-jetpack-preferences/index.md
> +
Can the above be normal paragraphs

2022-04-01 12:23 UTC, WanjaMIKE commented
Seems like there is still some work to do @mercie-nyakio

2022-04-01 14:18 UTC, mercie-nyakio commented
Hello @WanjaMIKE, I have done the requested edits please check. Thank you
cc: @BrianaNzivu

2022-04-04 20:16 UTC, BrianaNzivu commented
Hey @WanjaMIKE 👋 
Kindly check if the article is good to go.

Regards.

cc @mercie-nyakio

2022-04-04 20:17 UTC, BrianaNzivu commented
> Hello @WanjaMIKE, I have done the requested edits please check. Thank you cc: @BrianaNzivu

Pinging the moderator on Slack as well 👍

2022-04-07 06:26 UTC, mercie-nyakio commented
Hello @WanjaMIKE, Please do a final review on the article.
cc: @ahmadmardeni1, @hectorkambow

2022-04-12 11:08 UTC, WanjaMIKE commented
Merged #6819 into master

2022-04-12 11:08 UTC, merged