Getting started with anity CMS
section-engineering-education/engineering-education pull request #6825
Opened 2022-02-24 13:58 UTC by abimbolataofeek

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-02 08:52 UTC, abimbolataofeek commented
Hi good morning @ahmadmardeni1, please my article is yet to be assigned for a while now please can you help me look into it.

2022-03-03 10:05 UTC, abimbolataofeek commented
Hi good morning @hectorkambow , please my article is yet to be assigned for a while now please can you help me look into it.

2022-03-06 19:30 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Getting started with Sanity CMS #6825](https://github.com/section-engineering-education/engineering-education/files/8193350/New.Scan.7_26.PM.Copyleaks.Report.pdf)

2022-03-07 14:18 UTC, abimbolataofeek commented
plagiarism checked

2022-03-10 07:24 UTC, abimbolataofeek commented
Good morning @ahmadmardeni1  please can you look into my pr

2022-03-10 16:15 UTC, lalith1403 commented
PFA the plagiarism report. It is higher than what we accept. Please make the changes accordingly. Thank you.
[New Scan 4_11 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8225133/New.Scan.4_11.PM.Copyleaks.Report.pdf)

2022-03-12 07:11 UTC, abimbolataofeek commented
Plagiarism issue fixed @lalith1403

2022-03-15 09:06 UTC, abimbolataofeek commented
Good morning @lalith1403  please can you look into my PR.

2022-03-16 12:31 UTC, Jethro-magaji requested changes
Hi! @abimbolataofeek 
Well done for such an amazing article. However, there are some corrections you need to make.
Run your article on tools like Grammarly and ProWritingAid for better editing, this would save the time to review your work.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-03-16 12:31 UTC, Jethro-magaji commented on content/articles/getting-started-with-sanity-cms/index.md
> +- Run `sanity start` in your terminal.
All commands should be in "Bash" backticks

2022-03-16 12:31 UTC, Jethro-magaji commented on content/articles/getting-started-with-sanity-cms/index.md
> +- `npm install -g @sanity/cli`
This should be in "Bash"

2022-03-16 20:21 UTC, abimbolataofeek commented
@Jethro-magaji  all correction has been fixed

2022-03-16 20:36 UTC, hectorkambow commented
Please be sure to proofread the entire article as Peer Reviewers do not provide revisions services (and may not point out all pending issues).
If any other edits are required @Jethro-magaji we can close the PR to allow the student the proper time to make the edits.

2022-03-16 20:36 UTC, hectorkambow commented
@abimbolataofeek

2022-03-21 18:05 UTC, hectorkambow commented
any update on this PR are any other edits being made? @abimbolataofeek 

cc @Jethro-magaji

2022-03-22 10:22 UTC, abimbolataofeek commented
@hectorkambow all corrections has been made, waiting for review

2022-03-22 17:47 UTC, Jethro-magaji approved these changes
Hi! @abimbolataofeek 
Well done for coming up with such an amazing article. Please take note of these corrections to minimize revision next time.
Thanks.

2022-03-22 20:33 UTC, abimbolataofeek commented
@Jethro-magaji, thank you for reviewing my PR; I've learned from the mistakes you've pointed out.

2022-03-28 16:10 UTC, abimbolataofeek commented
Hello, nothing is happening with my PR.

2022-03-28 22:41 UTC, hectorkambow commented
Our team is going through the queue in the order of oldest to latest 🚀  

We will be sure to review asap

2022-03-31 18:39 UTC, merged