Creating A Shopping Cart API  with Java
section-engineering-education/engineering-education pull request #6859
Opened 2022-02-28 01:03 UTC by kingsleynwafor54

This tutorial contains content on how you can create a shopping cart API and also perform integration testing coupled with the use of postman to also test the API.

2022-02-28 01:04 UTC, kingsleynwafor54 commented
@john-amiscaray

2022-02-28 22:32 UTC, john-amiscaray commented
@kingsleynwafor54 I noticed you have reverted one or two of the changes I made in my last commit. I understand this may have been an accident but if you take issue with any particular changes I've made or don't understand them then let me know.

2022-02-28 23:13 UTC, john-amiscaray commented
@kingsleynwafor54 The instructions you wrote for using postman don't seem to make sense in that you say to click on certain buttons in places in the UI and they don't seem to exist on my postman. I was wondering then which postman version you are using?

2022-02-28 23:18 UTC, john-amiscaray commented on content/articles/creating-a-shopping-cart-api/index.md
> +        customerDao.refresh();
There is no refresh method in the CustomerDao interface

2022-03-01 21:00 UTC, kingsleynwafor54 commented
@john-amiscaray I pulled from this remote repository and then made the changes you asked for, I didn't know it reverted when I committed. Thanks for you understanding

2022-03-02 14:25 UTC, john-amiscaray requested changes
Here are a couple of more changes I forgot to request. At a second glance, I believe it is appropriate for me to once again close this pull request while you implement these changes. Do feel free to message me via the Engineering Education program's slack if you need assistance.

2022-03-02 14:25 UTC, john-amiscaray commented on content/articles/creating-a-shopping-cart-api/index.md
> +In the end, we've seen how to code to an interface, how to write a unit test, how to create an endpoint, and how to use postman to view our endpoint. Also, we discussed how we used field dependency i
This talks about how you discussed field dependency injection vs constructor dependency injection yet you have never talked about it earlier. Please either remove the sentence: 

> Also, we discussed how we used field dependency injection and not constructor dependency injection which will still suffice.

Or add a brief section talking about field dependency injection vs constructor dependency injection earlier in the article.

2022-03-02 14:25 UTC, john-amiscaray commented on content/articles/creating-a-shopping-cart-api/index.md
> +N/B `@PostMapping` is for saving objects, `@GetMapping` is for retrieving data from the database, `@PatchMapping` and `@PutMapping` is for updating data, and `@DeleteMapping` is for deleting. Also, n
I don't believe you made it clear to a reader which endpoints each of the methods map to and how you are doing it. I would add a comment of brief explanation about how you map each of these methods to a particular URL using the `@Postmapping`, `@GetMapping`, `@PatchMapping`, `@PutMapping`, and `@DeleteMapping` annotations.

2022-03-02 14:26 UTC, closed without merging