A REST API built with Golang without any frameworks, only using the native modules
section-engineering-education/engineering-education pull request #6860
Opened 2022-02-28 10:06 UTC by Joakim-gakure

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #6666

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-04 07:08 UTC, ahmadmardeni1 commented
Plagiarism check done ✅

2022-03-16 21:43 UTC, jerimkaura requested changes
Hello @Joakim-gakure 

Kindly consider re-reading the entire article to eliminate the mistakes. I only identified a few. I did not go over the entire article.

Thanks.

2022-03-16 21:43 UTC, jerimkaura commented on content/articles/rest-api-with-golang-without-any-frameworks-only-using-native-modules/index.md
> +However, due to the many libraries that the Go ecosystem has, you can still choose native libraries that you don't have to download and build your APIs. In this guide, we will build a complete and fu
These three paragraphs are somewhat confusing. The meaning doesn't come out clearly.

2022-03-16 21:43 UTC, jerimkaura commented on content/articles/rest-api-with-golang-without-any-frameworks-only-using-native-modules/index.md
> +To start a Go project, you need to first initialize Go within your project. In this case, create a project folder where you want your app to live. Open a command line that points to the newly created
Do you initialize go in the go project?  Isn't that repetitive?

2022-03-16 21:43 UTC, jerimkaura commented on content/articles/rest-api-with-golang-without-any-frameworks-only-using-native-modules/index.md
> +This will initialize a Go project by creating a `go.mod` file. Any go package that you install, its dependencies are saved here. The `go.mod` file has a `native-go-api` module name that helps you cre
You already mentioned what this command does.

2022-03-16 21:43 UTC, jerimkaura commented on content/articles/rest-api-with-golang-without-any-frameworks-only-using-native-modules/index.md
> +This will initialize a Go project by creating a `go.mod` file. Any go package that you install, its dependencies are saved here. The `go.mod` file has a `native-go-api` module name that helps you cre
Use short clear sentences that are easy to understand.

2022-03-16 21:43 UTC, jerimkaura commented on content/articles/rest-api-with-golang-without-any-frameworks-only-using-native-modules/index.md
> +Let's dive in and create a Golang REST API using native modules. This tutorial will use a movie use case. First, model the movie data you want your API to interact with. To do this, create a `models`
Describe the project you are building clearly. Saying the project is a "Movie use case" is not enough.

2022-03-16 21:44 UTC, jerimkaura commented
Consider opening a new PR when you are done with the changes.

2022-03-16 21:44 UTC, closed without merging