Build Calendar in React Using React-Calendar Library
section-engineering-education/engineering-education pull request #6868
Opened 2022-03-01 00:28 UTC by codeInn001

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #5832`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-01 04:45 UTC, jumamiller commented
A great article, looking forward to interacting with you as soon as possible!

Regards,

2022-03-01 04:51 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +![hero](/engineering-education/build-react-calendar-library/hero.jpg)
Kindly follow the article formats, I can see you have published quite a number, kindly check on the intro part!

2022-03-01 04:51 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +
Are some paragraphs incomplete?

2022-03-01 04:52 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +### Prerequisite
plurals?

2022-03-01 04:52 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +```jsx
is it supported by markdown?

2022-03-01 04:52 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +![react-application-structure](react-calendar-default.png)
Update these image links!

2022-03-01 04:53 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +```jsx
Once again, doesn't seem to be supported! Have a look

2022-03-01 04:53 UTC, jumamiller commented on content/articles/build-react-calendar-library/index.md
> +We covered how to integrate react-calendar app, customize, set a date range and add a booking feature into our react app.
Add more content on this section!

2022-03-01 04:54 UTC, jumamiller requested changes
Work on the few suggestions above!

2022-03-01 23:41 UTC, codeInn001 commented on content/articles/build-react-calendar-library/index.md
> +
Please, can you be more explicit?

2022-03-02 00:18 UTC, codeInn001 commented
@jumamiller Thanks, corrections made.

2022-03-04 07:10 UTC, ahmadmardeni1 commented
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


[[Build Calendar in React Using React-Calendar Library](https://github.com/section-engineeringeducation/engineering-education/pull/6868#)
#6868](https://github.com/section-engineering-education/engineering-education/files/8183737/New.Scan.7_05.AM.Copyleaks.Report.pdf)

2022-03-08 01:16 UTC, codeInn001 commented
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [Build Calendar in React Using React-Calendar Library#6868](https://github.com/section-engineering-education/engineering-education/files/8183737/New.Scan.7_05.AM.Copyleaks.Report.pdf)

2022-03-08 01:29 UTC, codeInn001 commented
> > Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> > [Build Calendar in React Using React-Calendar Library#6868](https://github.com/section-engineering-education/engineering-education/files/8183737/New.Scan.7_05.AM.Copyleaks.Report.pdf)

@ahmadmardeni1 Plagiarism corrected. Please, kindly note, Most of the words flagged 
for plagiarism are words common in technical articles.

Here is my report for you to go through. Thanks. 

[3931063-d2a2f89252457139f721-1646699607520.pdf](https://github.com/section-engineering-education/engineering-education/files/8201928/3931063-d2a2f89252457139f721-1646699607520.pdf)

2022-03-08 01:31 UTC, codeInn001 commented
@jumamiller corrections made.
Thanks

2022-03-09 07:34 UTC, jumamiller approved these changes

2022-03-09 07:37 UTC, jumamiller approved these changes

2022-03-16 07:52 UTC, ahmadmardeni1 commented
Hey @jumamiller Please whenever an author revisits his/her article, you need to add the "need plagiarism check" label again. This article is ready now, but this is for your future reviews.

2022-03-16 08:11 UTC, ahmadmardeni1 commented
Great work team!! @codeInn001 @jumamiller

2022-03-16 08:11 UTC, merged