Optimizing ml models with optuna
section-engineering-education/engineering-education pull request #6949
Opened 2022-03-04 10:23 UTC by NdoloBonface

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-04 10:34 UTC, NdoloBonface commented
@srishilesh 
Duplicate of #6816

2022-03-04 14:37 UTC, srishilesh requested changes
Hey @NdoloBonface ,

You have not addressed my suggestions. Please go through them carefully.

I'm sure you wouldn't have gone through other published articles to see how other authors have done it.

Fyi, this is your 1st duplicate PR, if all the requested changes are not done in the new PR, we might have to close this topic. By closing the topic, you might have to suggest a new one.

Ensure that your next PR must be revisions free.

As a few guideline:
- Explain all the terminologies. Add reference links for it
- State the "why" and "how" of everything you do.
- Explain code snippets
- Don't just put your thoughts into words. Instead, think from the reader's perspective and write them.

Take help from other contributors if needed to fine tune your article.

Ping me in the new PR.

Thanks.

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +Software framework Optuna is used to automate optimization processes. It uses a variety of samplers, including grid search, random, bayesian, and evolutionary algorithms, to find the best values for
`samplers`?

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +Software framework Optuna is used to automate optimization processes. It uses a variety of samplers, including grid search, random, bayesian, and evolutionary algorithms, to find the best values for
Keep the introduction simple. Avoid these terminolgies.

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +### Reasons for using Optuna
What are you trying to optimize? State the problem before jumping into solution

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +- Pruning is a technique that the algorithm uses to eliminate poor-quality samples quickly.
How is pruning related to optuna?

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +The Optuna software framework automates the hyperparameter optimization process. **Tree-structured Parzen Estimator** is the name of the `Bayesian` optimization algorithm it uses. According to Bayesi
`Tree-structured Parzen Estimator`

Add reference link

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +1. **Loading the dataset**
Use `#####` instead of numbers

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +X = standardSc.fit_transform(X)
You have not explaind the code as I had requested previously

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +X_train, X_test, y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 12)
You have not explaind the code as I had requested previously

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +print(ourScores)
You have not explaind the code as I had requested previously

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +We can see how much better our model is after fine-tuning the parameters by testing the model. We will use the `cross_val_score()` method to evaluate a score and xboost for gradient boosting algorith
Which model are you testing?

2022-03-04 14:37 UTC, srishilesh commented on content/articles/optimizing-ml-models-with-optuna/index.md
> +```
Explain

2022-03-04 14:37 UTC, closed without merging

2022-03-05 06:43 UTC, NdoloBonface commented
@srishilesh ill work on it and ping you. For now I am held up with exams.

2022-03-05 06:46 UTC, srishilesh commented
> @srishilesh ill work on it and ping you. For now I am held up with exams.
> 

@NdoloBonface 
Sure. No problem. Take your time.

Let me know if you need any help.

2022-03-05 06:49 UTC, NdoloBonface commented
> Reference in new issue
> 
> ### Reference in new issue
> Repository
> engineering-education 
> Title

I will ping you via slack
Thanks