[Duplicate #6567] How to build snake game in javaScript
section-engineering-education/engineering-education pull request #6958
Opened 2022-03-05 05:20 UTC by Kamau-ke

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #6567 ` 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-05 05:35 UTC, Kamau-ke commented
@jumamiller  I have made some changes. You may have a look.

2022-03-11 16:45 UTC, srishilesh commented
Hey @jumamiller ,

Just checking if I can pick up this PR, if you're occupied with other PRs in your backlog.

2022-03-15 14:20 UTC, jumamiller commented on content/articles/how-to-build-a-snake-game-in-javascript/index.md
> +In this article, I’ll show you step-by-step how to create this Snake Game using JavaScript and HTML.
Wordy, repetitive! Be precise and keep it simple.

2022-03-15 14:20 UTC, jumamiller commented on content/articles/how-to-build-a-snake-game-in-javascript/index.md
> +- Basic javaScript knowledge
Missing punctuations and necessary capitalizations and spacings?

2022-03-15 14:21 UTC, jumamiller commented on content/articles/how-to-build-a-snake-game-in-javascript/index.md
> +### Display the Canvas
Capitalization mistakes, fix this throughout your article.

2022-03-15 14:25 UTC, jumamiller commented on content/articles/how-to-build-a-snake-game-in-javascript/index.md
> +To do that, we need to insert `<style>` and `</style>` tags after the `</title>` tag. Then Copy and paste the following block of code.
`To do that`, ( I would ask to do what?) Use the correct phrases! Do not `drop` words, re-read the article.

2022-03-15 14:26 UTC, jumamiller commented on content/articles/how-to-build-a-snake-game-in-javascript/index.md
> +Now, we will create an index.js file that will contain the logic. For the file to be effective on our HTML main file, we need to link the js file to the HTML file. This is done by adding the followin
All non-English words such as file names should be distinguishable! Use, for example, backticks. Update this throughout your article!

2022-03-15 14:29 UTC, jumamiller requested changes
Hi, @Kamau-ke I really love this topic, but I feel you have VERY obvious mistakes which you of course had in the previous submission (Nothing changed).

I have suggested a few, kindly re-read this article and make changes where possible. Keep it simple.

> Any further revisions will lead to this article closure!

2022-03-16 20:37 UTC, hectorkambow commented
@Kamau-ke Noticing this is a duplicate

 Any duplicate that requires more edits show be closed asap @jumamiller

2022-03-16 20:37 UTC, closed without merging