App layout design programmatically using Matlab
section-engineering-education/engineering-education pull request #6970
Opened 2022-03-05 19:46 UTC by vitalisodhis

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #6406 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-10 14:18 UTC, jerimkaura requested changes
Great article @vitalisodhis 

However, consider working on the changes mentioned.

2022-03-10 14:18 UTC, jerimkaura commented on content/articles/app-layout-programmatically-using-matlab/index.md
> +Matlab provides an interactive environment for developing uifigure based apps layouts programmatically using Matlab functions.
Explain what UIfigure is to the reader.

2022-03-10 14:18 UTC, jerimkaura commented on content/articles/app-layout-programmatically-using-matlab/index.md
> +### Containers
Use level 4 heading for sub headings.

2022-03-10 14:18 UTC, jerimkaura commented on content/articles/app-layout-programmatically-using-matlab/index.md
> +The below codes demonstrate creating of a default container. The title will be specified as 'Broadsheet 1'.
Use 'Code' or 'code snippet'. I don't think there's is 'codes'

2022-03-10 14:18 UTC, jerimkaura commented on content/articles/app-layout-programmatically-using-matlab/index.md
> +### Panel container
Use level 4 heading to sub-headings for instance `####`

2022-03-10 14:18 UTC, jerimkaura commented on content/articles/app-layout-programmatically-using-matlab/index.md
> +The below codes shows the creation of a figure containing two panels and a button. The main panel is labelled 'panel 1', the sub-panel is labelled 'panel 2', and the button is labelled 'Start'.
Code.

2022-03-10 14:18 UTC, jerimkaura commented on content/articles/app-layout-programmatically-using-matlab/index.md
> +App layout design is used in making apps or designing websites. In addition, apps are useful in communications, data storage, or entertainment. As demonstrated in the article, Matlab provides an inte
Make this statement  clear.

2022-03-13 17:21 UTC, vitalisodhis commented
@jerimkaura  Changes made.

2022-03-16 07:29 UTC, jerimkaura reviewed
Hey @vitalisodhis 

Make sure to be going through your article before submission. I had to make major changes over:

- Punctuation
- Grammar mistakes
- Spelling
- Sentence structure

Check on the changes I made.

2022-03-16 22:17 UTC, jerimkaura approved these changes
Moving to the final review.

2022-04-11 16:40 UTC, merged