Building a Multiclass image classification model using MobileNet-V2 and TensorFlow
section-engineering-education/engineering-education pull request #6973
Opened 2022-03-06 09:11 UTC by kelivinnganga

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #6758

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-10 16:32 UTC, srishilesh requested changes
Hey @kelivinnganga ,

The tutorial looks great. It's easy to follow.

I've requested for some minor changes. Please let me know when you're done, we can then move to my final review.

Thanks.

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +Image preprocessing will convert the beans image dataset into a format the neural network can use. It involves various stages. Lets create a function that will perform [image scaling](https://en.wiki
`It involves various stages`

Explain a little about it. And, add any reference links

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +Image normalization converts the output pixel value between 0 by 1. The `preprocessing` function performs `normalization` by dividing the `image` by 255. The function uses ` tf.image.resize` to resiz
Use ` `` ` for keywords, variables, functions or anything that you want to be highlighted.

And, remove any additional spaces

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +The function also encodes the classes using `tf.one_hot(label, 3)`. It converts the classes (`Angular Leaf Spot`, `Bean Rust`, `healthy`), into numerical values (0, 1, 2)
Why are we encoding the values? State the reason.

Add reference links at Section.

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +These layers are already trained. To ensure that TensorFlow does not retrain them, use this code:
So, we are just using the pre-trained models to make predictions? If so, state that here. It's so not implicitly understandable.

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +It is the output layer. The `Dense` layer has 3 neurons because the dataset has three predefined classes. We have also set `softmax` as the activation function because the dataset has three pre-defin
Make these bulleted points

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +It will convert the image dataset into an array.
Make them as bulleted points.

2022-03-10 16:32 UTC, srishilesh commented on content/articles/building-a-multiclass-image-classification-model-using-mobilenet-v2-and-tensorflow/index.md
> +It checks the deep neural network's performance. It also calculates the accuracy score. `acc` will get the accuracy score using the train and the test set.
Use bulleted points.

2022-03-11 09:30 UTC, kelivinnganga commented
Hello @srishilesh, I hade gone through all the suggestions and made the changes.

2022-03-13 07:18 UTC, srishilesh commented
Let me check and get back to you by tomorrow.

2022-03-15 16:48 UTC, srishilesh commented
I'll complete my final review by tomorrow.

2022-03-18 18:14 UTC, srishilesh approved these changes
Hey @kelivinnganga ,

Great article. The flow was good. You have covered all the topics.

Have a look at the changes I've made.

Moving for the final review.

Thanks.

2022-04-07 14:41 UTC, merged