Understanding Cloud-Based Data Architectures
section-engineering-education/engineering-education pull request #7008
Opened 2022-03-08 15:24 UTC by verah-tech

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #6349

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-09 05:21 UTC, mbaabuones requested changes
@verah-tech Thank you for submitting your article. Your article is informative and easy to understand. After running your article through Grammarly.com, I have found some minor grammatical errors. Run it through Grammarly.com to identify and fix these errors. Please work on the minor suggested changes and ping me when you are done. Remember to proofread your article after doing the revision.

2022-03-09 05:21 UTC, mbaabuones commented on content/articles/understanding-cloud-based-data-architectures/index.md
> +Below are the benefits of cloud data architectures over the classic architectures:
You can create a new section 'Benefits of cloud data architectures'. Here, explain the specific benefits in-depth.

2022-03-09 05:21 UTC, mbaabuones commented on content/articles/understanding-cloud-based-data-architectures/index.md
> +Most cloud computing architecture consists of two main components: frontend and backend. The [frontend architecture](https://www.oreilly.com/library/view/frontend-architecture-for/9781491926772/ch01.
Here you can be innovative by creating a list of the two components and explaining them one by one. eg.
- **Front end architecture:** This contains every component.......
- **Back end architecture:** This handles data storage, ....

2022-03-09 05:21 UTC, mbaabuones commented on content/articles/understanding-cloud-based-data-architectures/index.md
> +For an organization to migrate to a cloud computing solution, it must be connected to the network. There are different ways an organization can migrate its data to the cloud, as stated below:
This information does not directly correspond to the title of the section. Here, you can create a new section called 'Migrating data to the cloud'.

2022-03-09 05:21 UTC, mbaabuones commented on content/articles/understanding-cloud-based-data-architectures/index.md
> +#### Understanding the cloud architecture
The cloud model

2022-03-09 05:21 UTC, mbaabuones commented on content/articles/understanding-cloud-based-data-architectures/index.md
> +#### Understand different cloud storage options
Cloud storage options

2022-03-09 11:05 UTC, verah-tech commented
Hi @mbaabuones, am grateful for taking the time to review my article. The changes requested have been made and noted. Kindly proceed with the review.
Thank you.

2022-03-10 16:20 UTC, lalith1403 commented
plagiarism check done ✔️

2022-03-11 14:50 UTC, mbaabuones approved these changes

2022-04-11 18:09 UTC, hectorkambow commented
jumping on this one

2022-04-11 18:40 UTC, merged