Implementing Offline Caching In Room For Data Fetched From Firebase Using Kotlin
section-engineering-education/engineering-education pull request #7026
Opened 2022-03-09 13:44 UTC by Sephens

### Article checklist

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5107

2022-03-10 16:24 UTC, lalith1403 commented
plagiarism check done ✔️

2022-03-18 09:47 UTC, Dawe-7 requested changes
Hello @Sephens  , welcome to Section's EngEd and congratulations on submitting your first article. The article is a nice read but i noticed you haven't completely finished and a few things need to be corrected.

Make the following changes/adjustments:
- Ensure your hero image is of the size 600x400 pixels and is not blurred. Some of your images are too large, check on them and resize them.
- Check your article for readability and ensure you code runs. Kindly add the missing code in the article because i've seen a few missing ones.
- If any of your images are cited, kindly add image sources for them.

Feel free to ping me in case you get stuck, i'll be happy to help!

Kindly go through our [docs](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md#create-author-bio-folder-structure) to get familiar with the process. Revisit your article once more and check on your grammar to make the review process smooth.

2022-03-18 09:47 UTC, Dawe-7 commented on content/authors/stephen-odhiambo/index.md
> +---
```suggestion
title: Stephen Odhiambo
type: authors
github: https://github.com/Sephens
images:
  - url: /engineering-education/authors/stephen-odhiambo/avatar.jpeg
skills: ["Kotlin" etc.]
---

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +```kotlin
Add the missing code here

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +@Database(
Add backticks and use the proper language/code identifier. Ensure all your code runs perfectly.

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +This class has a single method that returns the object of our DAO.
```suggestion
This class has a single method that returns the object of our DAO. We create the database class using the code below:

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +```kotlin
Add the missing code here

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +This class will have the business logic for fetching the data and caching it for offline access. In the `repository` package, create a repository class and name it `ItemsRepository`.
```suggestion
This class will have the business logic for fetching the data and caching it for offline access. In the `repository` package, create a repository class and name it `ItemsRepository`. Use the code below to achieve this:
```

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +![demo](/engineering-education/firebase-offline-caching/demo.jpeg)
```suggestion
![Demo](/engineering-education/firebase-offline-caching/demo.jpeg)
```

2022-03-18 09:47 UTC, Dawe-7 commented on content/articles/firebase-offline-caching/index.md
> +We will define our `DAO` and `Database` classes in the `data` package.
Add more content here.

2022-03-21 18:06 UTC, hectorkambow commented
closing this PR to take out of the queue while edits are being made

2022-03-21 18:06 UTC, closed without merging