Create a Python App that Extracts images, Scan For text Info, Transcribe and save to a .txt file
section-engineering-education/engineering-education pull request #7073
Opened 2022-03-11 10:26 UTC by Wachira48

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-11 16:53 UTC, srishilesh requested changes
Hey @Wachira48 ,

I believe this is your 4th article at Section EngEd.

Before you start with this article, did you go through the reviews of the 3 articles that you had published before?

I find many instances where the suggestions/revisions were not applied:
- Image path is incorrect
- No explanation of code snippets
- Many missing topics.
- And, a few more.

We highly recommend you to create PRs that are fully publishable/no revisions required. If there are any glancing errors, we will be closing the PR.

Hence closing this PR.

Thanks.

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +Python is a huge and popular language that many developers enjoy working with. Its human-readable syntax makes it a popular language and an easy to learn path. As a developer, you might need to extra
Break down this intro. Check other articles

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +
Table of contents & prerequisities

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +### Set up tesseract OCR
Add topic on Tesseract

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +![tesseract](tesseract.jpg)
Incorrect path

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +```
Code explanation - state objectives of this code.

Put them as bulleted points

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +```
Modularize the code and explain each method

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +    print(Fore.GREEN + "[!] File Writted" + Fore.RESET)
Break it down

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +
This is an abrupt ending

2022-03-11 16:53 UTC, srishilesh commented on content/articles/python-app-that-extracts-images-scan-text-transcribe-save-to-txt-file/index.md
> +![elevation-error](elevation-error.jpg)
No conclusion or further reading section.

2022-03-23 03:58 UTC, srishilesh commented
Hey @Wachira48 ,

Just checking if we have got any updates on this PR.

Let me know if you need any help.

2022-04-02 12:33 UTC, Wachira48 commented
Yes, @srishilesh. I have them ready

2022-04-15 11:01 UTC, srishilesh commented
@Wachira48 You can push your changes now

2022-04-15 15:07 UTC, Wachira48 commented
I have added the changes @srishilesh

2022-04-15 16:43 UTC, srishilesh approved these changes
Hey @Wachira48 ,

Thanks for making the changes.

Moving for the final review.

Thanks.

2022-04-18 16:32 UTC, Kayere commented
Great work gentlemen 🚀.

2022-04-18 16:32 UTC, merged