Building an animated vertical timeline chart with HTML, CSS and JavaScript.
section-engineering-education/engineering-education pull request #7125
Opened 2022-03-14 15:44 UTC by shegz101

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-16 21:59 UTC, shegz101 commented
@BrianaNzivu please has anyone started the plagiarism check on this content, so you can proceed with the review. I just hope this reviewing process will be fast.

2022-03-19 09:22 UTC, BrianaNzivu commented
> @BrianaNzivu please has anyone started the plagiarism check on this content, so you can proceed with the review. I just hope this reviewing process will be fast.

@section-engineering-education/content-moderator-team .

Hey @shegz101. A check will be done ASAP.

Regards.

2022-03-21 10:28 UTC, louisefindlay23 commented
Plagiarism check complete. Please fix the extra line breaks in between your HTML code snippets.

2022-03-21 18:10 UTC, hectorkambow commented
@BrianaNzivu Lets be sure to glance at the content before we dive into our review to see if any glaring issue exist.

2022-03-23 20:07 UTC, BrianaNzivu requested changes
Hey @shegz101 👋 
Good job on the article.
Just a few things I would love to point out before we proceed with the preliminary revisions:
- Your article has quite a lot of mistakes. I suggest you use [Grammarly](https://app.grammarly.com/) to make these corrections. 
- Please structure your article as required by Section. You can check out a tutorial's structures [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md).
- Refer to the comments made below.


Ping me when done.

Kind Regards.

2022-03-23 20:07 UTC, BrianaNzivu commented on content/articles/building-an-animated-vertical-timeline-chart-with-html-css-and-javascript/index.md
> +…
Indent your code well.

2022-03-23 20:07 UTC, BrianaNzivu commented on content/articles/building-an-animated-vertical-timeline-chart-with-html-css-and-javascript/index.md
> +…
Remove this...for all code snippets

2022-03-23 20:11 UTC, BrianaNzivu commented
@section-engineering-education/peer-reviewers 👋 
I am noticing this article is using Vanilla Js which I am not proficient in. 

Someone who is good at it please feel free to take it up.

2022-03-23 22:05 UTC, shegz101 commented
@BrianaNzivu I have made all the corrections. And I have already linked this PR to an issue initially.
Thanks.

2022-03-25 04:37 UTC, shegz101 commented
@BrianaNzivu please are you still reviewing the article, I have done all you said I should do.

2022-03-25 18:56 UTC, shegz101 commented
> @section-engineering-education/peer-reviewers 👋 I need someone to help review this article, its' been 11 days since I opened this PR.

2022-03-26 14:41 UTC, louisefindlay23 commented
@shegz101, have correctly linked your PR to your topic suggestion for you. Please remember in the future to follow the instructions in the Article Checklist under Topic Suggestion This Closes.

2022-03-26 15:20 UTC, shegz101 commented
> @shegz101, have correctly linked your PR to your topic suggestion for you. Please remember in the future to follow the instructions in the Article Checklist under Topic Suggestion This Closes.

Thank you, I will properly link it next time. Don't know if you can help review this article.

2022-03-27 09:16 UTC, BrianaNzivu commented
Hey @shegz101 👋
Since no one has taken up the article. I will review it but I am requesting if we can work closely on Slack for any clarifications and questions that I might have especially on the Java script end.

Please DM me ASAP. 
Regards.

2022-03-27 11:23 UTC, shegz101 commented
@BrianaNzivu  please what's your name on slack.

2022-03-27 17:30 UTC, shegz101 commented
@BrianaNzivu please what's your name on slack.

2022-03-27 17:31 UTC, BrianaNzivu commented
Briana Nzivu

2022-03-27 17:35 UTC, shegz101 commented
OK let me try again, because I wasn't getting your name before.

2022-03-27 17:38 UTC, shegz101 commented
@BrianaNzivu just sent you a message on slack

2022-03-28 20:39 UTC, BrianaNzivu commented
Proceeding to tech review 👍 

@shegz101 please check your DM.

2022-03-30 16:23 UTC, shegz101 commented
@BrianaNzivu please what's the latest update concerning the tech review.

2022-03-30 19:45 UTC, BrianaNzivu commented
Tech review is done and code functioning well 👍

2022-03-30 19:48 UTC, shegz101 commented
> Tech review is done and code functioning well 👍

Thanks, please what's next.

2022-03-30 19:50 UTC, BrianaNzivu approved these changes
Hey @shegz101👋 .

Very good job on the article. It is a very interesting read👏 .

Just a few things I'd like to point out:
- I suggest that you check out the [structure](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) for the various articles accepted by Section.
- You check out our resources page which has links to various resourceful tools for writing just to minimize the changes being made by the reviewer.
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Once again good job! 👍 

Kind Regards

2022-03-30 19:53 UTC, shegz101 commented
> Hey @shegz101👋 .
> 
> Very good job on the article. It is a very interesting read👏 .
> 
> Just a few things I'd like to point out:
> 
> * I suggest that you check out the [structure](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) for the various articles accepted by Section.
> * You check out our resources page which has links to various resourceful tools for writing just to minimize the changes being made by the reviewer.
> * Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.
> 
> That's it! 😄
> 
> A final review will be done now by a content moderator. Otherwise, congratulations on publishing your article🍾.
> 
> In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email ([briananzivu@gmail.com](mailto:briananzivu@gmail.com)). I am **ALWAYS** here to help.
> 
> It has been a pleasure reading and reviewing this article.
> 
> Looking forward to seeing you contribute more to EngEd. 🚀
> 
> Once again good job! 👍
> 
> Kind Regards

Thanks Briana I would definitely reach out.

2022-04-15 18:10 UTC, hectorkambow commented
> Hey @shegz101 👋 Good job on the article. Just a few things I would love to point out before we proceed with the preliminary revisions:
> 
> * Your article has quite a lot of mistakes. I suggest you use [Grammarly](https://app.grammarly.com/) to make these corrections.
> * Please structure your article as required by Section. You can check out a tutorial's structures [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md).
> * Refer to the comments made below.
> * Please link the issue this PR fixes.
> 
> Ping me when done.
> 
> Kind Regards.

@BrianaNzivu 

The article should have been closed at this stage 💯

2022-04-15 18:10 UTC, hectorkambow commented
jumping on this one for final review

2022-04-15 18:36 UTC, hectorkambow commented
Was not able to preview (render on local host)

2022-04-15 18:38 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team Is anyone able to test to see if they can preview on their end? 
Final review was complete

2022-04-17 12:48 UTC, shegz101 commented
@srishilesh please can you help with this article, it is not rendering.

2022-04-17 16:43 UTC, BrianaNzivu commented
> @section-engineering-education/content-moderator-team Is anyone able to test to see if they can preview on their end? 
> Final review was complete

Cc @section-engineering-education/content-moderator-team

2022-04-19 08:18 UTC, shegz101 commented
@BrianaNzivu please try to render and let me see the error. Thanks

2022-04-19 08:20 UTC, shegz101 commented
@srishilesh please help me check out the issue with this PR, it's not rendering on local host (Hugo).

2022-04-19 17:30 UTC, srishilesh commented
> @srishilesh please help me check out the issue with this PR, it's not rendering on local host (Hugo).

Hey @shegz101 ,

Thanks for reaching out.

I have been having some issues with my laptop for the past 2 days. I'll get to this issue in a day or two.

Meanwhile, I suggest you to take a look [at this guide](https://github.com/section-engineering-education/engineering-education/blob/master/content-moderators/how-to-preview-hugo.md) and try it out in your system. Let me know if some error comes up.

Thanks.

2022-04-21 11:06 UTC, BrianaNzivu commented
> @BrianaNzivu please try to render and let me see the error. Thanks

Hey @shegz101 👋🏾.
You can try creating a new PR on your latest forked repo kmake sure it's up to date with our master) . It might be merge issues.
I will close this to allow you to open another PR. Once you open the PR please ping me or request a review for me so that we see whether we will fix this issue.

Regards.
Cc @hectorkambow
@srishilesh

2022-04-21 11:08 UTC, closed without merging