The asp net core 6 web api a three tier architecture
section-engineering-education/engineering-education pull request #7147
Opened 2022-03-15 18:37 UTC by njorosirmie

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

`This closes #6728

2022-03-23 10:16 UTC, njorosirmie commented
@hectorkambow kindly assign this article for review. Thanks!

2022-04-02 08:32 UTC, njorosirmie commented
@hectorkambow kindly assign this. Thanks.

2022-04-07 07:09 UTC, fely545 commented
@hectorkambow If allowed I would like to review this article has been in the queue for a long time
Cc @louisefindlay23 @ahmadmardeni1

2022-04-07 21:48 UTC, ahmadmardeni1 commented
Hey! @fely545 Are you a peer reviewer?

2022-04-08 09:01 UTC, WanjaMIKE commented
Plagiarism check done

2022-04-11 22:11 UTC, hectorkambow commented
@section-engineering-education/content-moderator-team  

Lets be sure not to overlook this PR.

2022-04-15 01:35 UTC, Jethro-magaji requested changes
Hi! @njorosirmie 
Well done for such an amazing article. However, there are some corrections you need to make.
Run your article on tools like Grammarly and ProWritingAid for better editing, this would save the time to review your work.
Please, replace all the images you have with good quality/clear images and use a high-resolution free stock image for your hero image. 
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-04-15 01:35 UTC, Jethro-magaji commented on content/authors/samson-njoroge/index.md
> +title: Samson Njoroge
This section isn't arranged in the proper Markdown format. Check out this [example](https://github.com/section-engineering-education/engineering-education/blob/master/content/authors/ahmad-mardeni/index.md) to fix it.

2022-04-15 01:35 UTC, Jethro-magaji commented on content/articles/the-asp-net-core-6-web-api-a-three-tier-architecture/index.md
> +### Prerequisites
This section should come after the "Table of contents" section.

2022-04-19 19:00 UTC, hectorkambow commented
Closing this PR due to it not being ready to be published 👍

2022-04-19 19:00 UTC, closed without merging