Why data storage is shifting to the blockchain
section-engineering-education/engineering-education pull request #7164
Opened 2022-03-16 17:03 UTC by Snzovi

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-21 09:47 UTC, louisefindlay23 commented
Plagiarism check complete

2022-03-21 21:56 UTC, mercymeave requested changes
Great area to shed some light on @Snzovi 

However I noticed some mistakes from your article that needs to be addressed.

1. Avoid too many cliches. They make the article become shallow in meaning.
2.  Go over the article keenly to eliminate the common grammar mistakes that exist in the article. 
3.  I didn't go over the entire article once I NOTICED  THE MISTAKES WERE MANY.
> You might have used Grammarly but there are mistakes that are still visible. Correct them then we get to the review.

Thanks

2022-03-21 21:56 UTC, mercymeave commented on content/articles/why-data-storage-is-shifting-to-the-blockchain/index.md
> +Some years ago, the most embraced form of data storage was the traditional in-house data centers. But it was not too long before cloud storage started to replace them. Cloud storage came with the pro
The most embraced form of data storage was the traditional in-house data centers in the recent past. However, cloud storage started to replace it. Cloud storage came with the promise of greater efficiency and more data storage capacity that attracted many businesses.
```suggestion
The most embraced form of data storage was the traditional in-house data centers in the recent past. However, cloud storage started to replace it. Cloud storage came with the promise of greater efficiency and more data storage capacity that attracted many businesses.
```

2022-03-21 21:56 UTC, mercymeave commented on content/articles/why-data-storage-is-shifting-to-the-blockchain/index.md
> +In the same way, cloud storage is now facing competition from blockchain technology. Blockchain comes with the promise to solve data security challenges - an issue that cloud storage has found challe
```suggestion
In the same way, cloud storage is now facing competition from blockchain technology. Blockchain promises to solve data security challenges - an issue that is a great threat to cloud storage. 

With blockchain data storage, companies and individuals will enjoy the desired data transparency. Thus, many companies are opting for this new technology with the hope of revolutionizing data storage.
```

2022-03-21 21:56 UTC, mercymeave commented on content/articles/why-data-storage-is-shifting-to-the-blockchain/index.md
> +This article discusses blockchain as a more secure, cost-friendly alternative data storage system. It also gets leaders prepared of what to expect of blockchain as a data storage solution.
```suggestion
This article discusses blockchain as a more secure, cost-friendly alternative data storage system. It also gets the reader to prepare for what to expect of blockchain as a data storage solution.
```

2022-03-21 21:56 UTC, mercymeave commented on content/articles/why-data-storage-is-shifting-to-the-blockchain/index.md
> +Besides, data in the cloud can exist as either public or private. However, in blockchain, data is always public. Blockchain embraces transparency, meaning that an entity cannot hide data from other u
Hey, the best way to compare two technologies is using one characteristic and looking into it on both sides. For instance, if you take the mode of access, how does it occur in cloud storage and how different is it is from the blockchain.

Taking that approach makes your article smooth and add flow to your content.

2022-03-21 21:56 UTC, mercymeave commented on content/articles/why-data-storage-is-shifting-to-the-blockchain/index.md
> +Unsurprising, such a storage technology that threatens to 'overthrow' cloud storage and offer a highly secure system has its share of financial challenges. In the last few years, the costs for implem
This paragraph sounds a bit off. Consider re-writing and splitting into two to convert a single idea per paragraph.

2022-03-21 21:56 UTC, mercymeave commented on content/articles/why-data-storage-is-shifting-to-the-blockchain/index.md
> +There are specific factors that keep the blockchain functioning normally. In the case of bitcoin, the nodes and miners are responsible. For Ethereum, Gas is the fuel that maintains its routine runnin
How can you verify that the minors are responsible? 

`For Ethereum` ....... `and in the case of Ethereum`. Avoid unnecessary repetition.

How have the mentioned points contributed to the normal functioning of the blockchain?

2022-03-23 20:11 UTC, mercymeave commented
Hello @Snzovi 

I will be closing this PR to allow you make the required revisions. We recommend our students to make revisions in their own forked repos to clear up the queue.

2022-03-23 20:11 UTC, closed without merging