How To Implement Drag and Drop File Upload In Next.js.
section-engineering-education/engineering-education pull request #7217
Opened 2022-03-19 07:52 UTC by gisioraelvis

### Article checklist
#### Pre-submission checks
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #6723

2022-03-21 10:06 UTC, louisefindlay23 commented
Plagiarism check complete

2022-03-31 18:27 UTC, Dawe-7 requested changes
Nice article @gisioraelvis, kindly take a look at the suggestions below and implement them to make the article ready to go. 

Ping me when done with the changes.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +It also imports the `filePreview` component to display the images that have been uploaded. This component uses the `DropZone.module.css` file to style the component.
```suggestion
It also imports the `filePreview` component to display the images that have been uploaded. The `filePreview` component uses the `DropZone.module.css` file to style the component. 
```

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +The `useReducer` hook takes in a reducer function and the initial state and returns the current state and a dispatch function. The dispatch function will be used to update the state.
You've used the word `and` several times in one sentence making it hard to read. Kindly rephrase this sentence

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +Update the `index.js` file.
Is the code below used to update the file?,  if so then state what it does.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +The fourth is the `dragleave` event. This event is fired when the user drags a file over the dropzone region.
```suggestion
The following are the HTML5 drag and drop events:
1.  `dragenter` event - This event is fired when the user drags a file over the dropzone region. 
2. `dragover` event - This event is also fired when the user drags a file over the dropzone region. 
3.  `drop` event - This event is fired when the user drops a file onto the dropzone region. 
 4. `dragleave` event - This event is fired when the user drags a file over the dropzone region.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +`onDrop` will set the `inDropZone` to get the fileList from the event on the dataTransfer object as an array, iterate over existing files, check if the file already exists, if so, don't add to fileLi
The first sentence here is too long, kindly break it down into constructive sentences. Also, the second sentence doesn't flow well.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +To handle file selection, add the following code to the `DropZone.js` component and onchange event listener to the `input` element.
This sentence is hard to read, kindly explain it in a more understandable way. The part starting from "and" is hard to understand.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +Use the `onChange` event on the `input` element. This event is fired when the user selects a file or files.
What is the  `onChange` event's function?

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +The `handleFileSelect` function will be used to get the files from the event on the input element as an array, iterate over existing files, check if the file already exists, if so, don't add to fileL
Break down the first sentence here into smaller constructive sentences.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +The upload button will be shown only if there are files in the fileList. The `uploadFiles` function will be used to get the files from the fileList as an array, initialize formData object, loop over
Kindly break down this paragraph into shorter paragraphs.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +File upload is a common and essential requirement for web applications. In this tutorial, you have implemented a drag and drop file upload component in Next.js that makes use of the HTML5 drag and dr
The second sentence here is also too long, kindly break it down.

2022-03-31 18:27 UTC, Dawe-7 commented on content/articles/nextjs-dnd-file-upload/index.md
> +...
What is the function of this ?

2022-04-02 06:21 UTC, gisioraelvis commented
Hello @Dawe-7 
I am one with the requested changes.

2022-04-03 14:57 UTC, Dawe-7 approved these changes
Nice article @gisioraelvis. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles.

2022-04-03 15:11 UTC, gisioraelvis commented
Thanks @Dawe-7 
I have taken note of the changes.

2022-04-19 03:28 UTC, Dawe-7 commented
@Kayere, can we have a final review of this PR, thanks.

2022-04-22 12:29 UTC, merged