Getting started with neural network in PyTorch
section-engineering-education/engineering-education pull request #7225
Opened 2022-03-19 20:04 UTC by ivymugo

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #6905

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-21 09:59 UTC, louisefindlay23 commented
Plagiarism check complete

2022-03-23 20:52 UTC, mercymeave requested changes
Hello, thanks for submitting your first article to Section.io.

However, your article has a lot of mistakes, grammatical errors, repetition and improper sentences.

I noticed I would take quite a long time doing the edits. I, therefore, recommend that you work on the changes to perfect the article.

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +Neural networks are an algorithmic set of rules for discovering patterns in data. Using a neural network model will help us understand how our brains process information in the same way. The networks
When you talk of the same, way what way ; mentioned before;  are you referring to?

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +- Output nodes - These nodes are the ones that are responsible for the final output. They are the ones that are responsible for the final decision.
Consider using simple sentences, something like "The input node transmit data from the external world into the hidden nodes."

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +Pytorch is a [Python](https://pytorch.org/) library that allows us to create neural networks. It is a high-level library that enables us to build neural networks straightforwardly. It is also a preva
There is repetition here. You already talked of pytorch  in the introduction.

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +To install Pytorch, we need to install the [Python](https://www.python.org/) library. We can do this by using the command:
Here you say we install python but the command below it install, PyTorch, won't this confuse the reader?

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +Let's begin by creating a neural network!
Don't mix up words. Explain every module clearly. Besides, use complete sentences 
.

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +This line imports the `torch` library. It is a high-level library that allows us to create neural networks. It is also a popular library for deep learning.
Repetition .

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +This module has the `F` function used to create the activation functions.
What is an activation function? How is it used in the neural networks? Explain these clearly and do it for every other module. Don't just do the brief explanation.

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +This module contains all the transformations we can use to preprocess our data.
What are `transformations` and why do we need them?

2022-03-23 20:52 UTC, mercymeave commented on content/articles/getting-started-with-neural-network-in-pytorch/index.md
> +
I am wondering where the image came from. Every step should be linked to another for maximum value.

2022-03-23 20:53 UTC, mercymeave commented
I will give you more time to work on this. Create a new PR and ping me once you are done.

2022-03-23 20:53 UTC, closed without merging