Getting Started with Boruta Algorithm in Machine Learning
section-engineering-education/engineering-education pull request #7243
Opened 2022-03-21 20:30 UTC by nelsonnrl

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #5946

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-03-23 16:20 UTC, louisefindlay23 commented
Plagiarism check complete. Remember to spell-check and grammar check your article before submission, @nelsonnrl as I noticed some typos.

2022-03-28 00:42 UTC, Jethro-magaji requested changes
Hi! @nelsonnrl 
Well done for such an amazing article. However, there are some corrections you need to make.
Please, run your article on tools like Grammarly and ProWritingAid for better editing. This would save the review time to review your work.

The hero image should be a high resolution free stock image 600x400px.

Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. If you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-03-28 00:42 UTC, Jethro-magaji commented on content/articles/boruta-algorithm/index.md
> +
Please, add a "Table of contents" section here, linking it to each subheading.

2022-03-28 00:42 UTC, Jethro-magaji commented on content/articles/boruta-algorithm/index.md
> +![image](boruta.png)
Fix all image paths, like this 
`! [Title background] (/engineering-education/collapsing-action-tool-bar-with-android-material-design-in-kotlin/title-bg.png )`

2022-03-28 00:42 UTC, Jethro-magaji commented on content/articles/boruta-algorithm/index.md
> +
Can you please include a link to the complete code?

2022-03-28 00:42 UTC, Jethro-magaji commented on content/articles/boruta-algorithm/index.md
> +1. High computaional cost
Put this in an unordered list.

2022-03-28 00:42 UTC, Jethro-magaji commented on content/articles/boruta-algorithm/index.md
> +1. Filter methods
Put all this list in one line, separated by a comma.

2022-04-11 21:57 UTC, hectorkambow commented
@Jethro-magaji  

can we get a status update on this PR - its been sitting for 12 days now. 

If any more edits are needed we will be closing this PR.

2022-04-14 22:47 UTC, hectorkambow commented
Closing due to the fact the peer reviewer made changes after author.

2022-04-14 23:36 UTC, Jethro-magaji commented
> Closing due to the fact the peer reviewer made changes after author.



> Closing due to the fact the peer reviewer made changes after author.

I made some minor changes to the PR.

2022-04-16 07:57 UTC, nelsonnrl commented
@Jethro-magaji 
I did all the changes you requested and now I see the PR is closed. What should I do about this?

2022-04-16 08:16 UTC, nelsonnrl commented
Hello @hectorkambow, I went through the changes the peer reviewer did after the revision and actually they are minor, just like reducing the number of words in a line and general alignments, which has nothing to do with the change of the content, they are so inferior and I don't think they are worth this PR to be closed. Kindly, would you tell me what to do next?

2022-04-16 22:20 UTC, hectorkambow commented
👀  
Noted. 

If any other edits are needed during a final review we will be closing again (for a final time).

2022-04-16 22:20 UTC, hectorkambow commented
@Jethro-magaji What labels does this PR need?

2022-04-16 22:59 UTC, Jethro-magaji approved these changes
Hi! @nelsonnrl 
Well done for coming up with such an amazing article. Please take note of these corrections for the sake of next time.
Thanks.

2022-04-16 23:00 UTC, Jethro-magaji commented
> @Jethro-magaji What labels does this PR need?

Ready for final review

2022-04-19 22:43 UTC, hectorkambow commented
Noted: just going through the queue in order - we will get to this one asap.!

2022-05-13 16:06 UTC, hectorkambow commented
jumping on this one

2022-05-13 16:52 UTC, hectorkambow commented
@nelsonnrl 

@Jethro-magaji 

made some edits - some of the files were not in the proper folder>

Please be sure to review any edits made to improve future articles 🚀

2022-05-13 16:52 UTC, merged