Improving conversation with the perspective api
section-engineering-education/engineering-education pull request #7277
Opened 2022-03-23 18:45 UTC by Fidelmwangi

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #6664

2022-04-14 22:58 UTC, hectorkambow commented
@section-engineering-education/peer-reviewers  

Team is anyone available to do a review on this PR - it has been idle for about 20 days.

2022-04-15 03:50 UTC, Jethro-magaji requested changes
Hi! @Fidelmwangi 
Well done for such an amazing article. However, there are some corrections you need to make.
Run your article on tools like Grammarly and ProWritingAid for better editing, this would save the time to review your work.
Please, add all the images needed and use a high-resolution free stock image for your hero image.

Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or need help, you can reach out to me on the EngEd Slack channel.
Thanks.

2022-04-15 03:50 UTC, Jethro-magaji commented on content/authors/fidel-mwangi/index.md
> +type: authors
Please change your current avatar to a bit more professional image.

2022-04-15 03:50 UTC, Jethro-magaji commented on content/articles/improving-conversation-with-the-perspective-api/index.md
> +![Image-1](Image-1)
Please change all image path to this format 
`![Allcar] (/engineering-education/introduction-to-unity-engine /allcar.png)`

2022-04-15 03:50 UTC, Jethro-magaji commented on content/articles/improving-conversation-with-the-perspective-api/index.md
> +### Prerequisites
This section should come after the "Table of content" section

2022-04-19 16:56 UTC, lalith1403 commented
plagiarism check done ✔️

2022-04-19 19:12 UTC, hectorkambow commented
@Fidelmwangi 

Any update on this PR ?

2022-04-19 19:17 UTC, Fidelmwangi commented
@hectorkambow Hello sir, this PR will be ready by tomorrow im working on it

2022-04-20 12:08 UTC, Fidelmwangi commented
@Jethro-magaji Hi, this article is good to go

2022-04-20 18:16 UTC, hectorkambow commented
👀  

@Fidelmwangi 

Upon a glance this content looks too similar to [this article](https://css-tricks.com/improving-conversations-using-perspective-api/). 

Either way it seems this topic is well covered in other blog sites as shown above - we prefer to publish original and unique content.  👍

2022-04-20 18:16 UTC, closed without merging