Getting started with Unit Testing with Spring Boot
section-engineering-education/engineering-education pull request #7350
Opened 2022-03-28 14:35 UTC by mussooo

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6997

2022-03-29 07:29 UTC, Kayere commented
Plagiarism check done ✅

2022-03-29 16:54 UTC, john-amiscaray commented
@mussooo Looking good. The only comment I have is that I would suggest making your file names follow [kebab case](https://www.theserverside.com/definition/Kebab-case) but we should be good to move on to the technical review.

2022-03-30 15:55 UTC, john-amiscaray requested changes
Here are some issues/concerns I found in the technical review. Please address them before we can move on to the final review.

2022-03-30 15:55 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +In `/src/main/java` create a new package named `Controller`. Proceed to create a Java class named `HelloContoller.java` in  `/src/main/java/Controller`. Within that file, add the code below:
package names should be lower case, i.e. the package should be named *controller* rather than *Controller*

2022-03-30 15:55 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +    }
The test fails:

![Capture](https://user-images.githubusercontent.com/63324129/160873407-937f9de2-ec3b-45c1-8cf5-df9ee27f7d69.PNG)

2022-03-30 15:55 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +> Note: If we use that structure to run the test, it will fail. Spring Boot will look for `@SpringBootConfiguration` at the package `/test/controller`, and it will not find it. To avoid this, let us
You don't want to put your tests and applications in the same package. I.e., the application should be in `/src/main/java/com.example.demo/DemoApplication.java` while the tests should be in `/src/main/test/java/com.example.demo`.

2022-03-30 15:55 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +> Note: If we use that structure to run the test, it will fail. Spring Boot will look for `@SpringBootConfiguration` at the package `/test/controller`, and it will not find it. To avoid this, let us
I don't understand what the issue is here that you are talking about. I was able to get it working with a structure like this:

![Capture](https://user-images.githubusercontent.com/63324129/160875150-5d3495c9-b078-4b85-893b-691f29863990.PNG)

2022-03-30 15:55 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +Click next to proceed. Type *web* to search the required dependencies in the search bar. Select *Spring Web*, *Spring Reactive Web*, *Spring Web Services*, and click *finish* to download the initiali
We only need the *Spring Web* dependency here. Having *Spring Reactive Web* and *Spring Web Services* is excessive.

2022-03-30 15:56 UTC, john-amiscaray commented
Because the suggested changes aren't massive I'll keep the pull request while you work on fixing them. Just be diligent to make these changes to not take up room in the queue.

2022-04-02 14:25 UTC, mussooo commented
@john-amiscaray, please have a look at my last two commits. Thank you.

2022-04-03 23:43 UTC, john-amiscaray requested changes
Looks fine. It's just the file locations and package names I'm mostly concerned about. Additionally, I left another small piece of feedback I missed regarding the project setup instructions you gave. Please work on these.

2022-04-03 23:43 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +Let us now look at how to test controllers in Spring Boot. To accomplish this, you will need to import some dependencies using the `Spring Initializer` and `IntelliJ IDEA`. In, `IntelliJ IDEA` lets u
I would add a disclaimer here that to do this you need IntelliJ IDEA ultimate, otherwise, you'll need to go to https://start.spring.io

2022-04-03 23:43 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +> Note: I have renamed my Package name to `UnitTesting`.
As I mentioned before, package names should be all lower case

2022-04-03 23:43 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
>  ```
As I mentioned previously, packages containing your tests should be in `/src/test/java`

2022-04-03 23:43 UTC, john-amiscaray commented on content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
> +Repeat the same procedure to generate another test. Name the second test class `HelloControllerIntTest.java`. In `/src/main/test/java/controller/HelloControllerIntTest.java`, modify the code as shown
As I mentioned in another review comment, packages with tests in them should be in `src/test/java` not `src/main/java`

2022-04-06 17:08 UTC, john-amiscaray approved these changes

2022-04-06 17:09 UTC, john-amiscaray approved these changes

2022-05-03 09:03 UTC, WanjaMIKE commented
Merged #7350 into master

2022-05-03 09:04 UTC, merged