A sbert based flask web app for automatic text summarization
section-engineering-education/engineering-education pull request #7523
Opened 2022-04-08 10:16 UTC by FranciscaNg

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-04-11 07:57 UTC, FranciscaNg commented
@BrianaNzivu

2022-04-19 17:31 UTC, lalith1403 commented
plagiarism check done ✔️

2022-04-19 18:28 UTC, srishilesh requested changes
Hey @FranciscaNg ,

Good work!

Please have a careful look at the suggestions I've made.

Your article doesn't dive deep into the technical concepts, instead gives a quick summary of how it can be implemented. Moreover, the code snippets were not very explanatory and had many typo errors. Also, the image paths were incorrect.

Ping me when you're done with the changes.

Thanks.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +There are a variety of ways to use SentenceTransformers in Python projects. Our preliminary work is described in this paper [Sentence-BERT:](https://arxiv.org/abs/1908.10084) Sentence Embeddings Usin
The intro could have been better. It's not very beginner friendly.

The reader might not be familiar with these terms. Take a look at other articles to see how they've done.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +```
Add markdown code snippet type

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +```
```suggestion
```bash

```

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +After executing the above command you will notice that the `summarizerApp` is within brackets.
What do you mean?

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +In the `index.html` file, copy the following html code. The codde consists of a home page code that displays a text field where the user can submit a significant chunk of content that will be summari
Avoid saying "Copy this code". Instead explain what you've done.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +
Add an image that displays the output of the above code.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +
Add image here too

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +### Builing the Flask web app
Before we get started with the implementation, add a separate section that talks about BERT or Text summarization in-detail.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +After importing libraries we create create a SBERT model. We'll use our SBERT model to summarize the required content in our next session.
Talk about SBERT too, after the `Prerequisities`

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +```
It's good that you've added comments. But, looks like the it's not very readable.

Hence, I suggest you to write the explanations below the code snippet as bulleted points using `-`.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +model = SBertSummarizer('paraphrase-MiniLM-L6-v2')# Useful for assignments since it converts phrases and paragraphs into a 384-dimensional dense vector space.
Can you explain more about this `paraphrase-MiniLM-L6-v2`?

Is it some pre-trained file?

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +In your project folder there should exit the following:
Typo again

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +![Terminal](/section-engineering/a-sbert-based-flask-web-app-for-automatic-text-summarization/terminal.png )
Incorrect image path. Please check your previous review.

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +![After summarization](/section-engineering/a-sbert-based-flask-web-app-for-automatic-text-summarization/summarized.png )
Incorrect paths

2022-04-19 18:28 UTC, srishilesh commented on content/articles/a-sbert-based-flask-web-app-for-automatic-text-summarization/index.md
> +In this blog, we demonstrated how to effectively construct a Flask web application that utilizes SBERT to summarize a given piece of material. We constructed a virtual environment, installed packages
Add a GitHub URL that contains the source code.

2022-04-19 18:31 UTC, FranciscaNg commented
Closing now 
I'll take some time before I push some more commits

2022-04-19 18:33 UTC, FranciscaNg commented
Thanks @srishilesh

2022-04-20 18:21 UTC, hectorkambow commented
> Your article doesn't dive deep into the technical concepts, instead gives a quick summary of how it can be implemented. Moreover, the code snippets were not very explanatory and had many typo errors. Also, the image paths were incorrect.
> 
> Ping me when you're done with the changes.
> 
> Thanks.

@srishilesh - this seems like it should have been closed at that point. (not sure how extensive the required improvements were). 

But IF any more edits are needed (be it grammatical or code) we will be closing the PR 👍

2022-04-21 18:36 UTC, srishilesh approved these changes
Hey @FranciscaNg ,

Thanks for making the changes.

Make sure to go through the changes I've made.

Moving for the final review.

Thanks.

2022-04-21 18:37 UTC, FranciscaNg commented
> Hey @FranciscaNg ,
> 
> Thanks for making the changes.
> 
> Make sure to go through the changes I've made.
> 
> Moving for the final review.
> 
> Thanks.

I will. Thanks

2022-04-29 11:06 UTC, merged