[DUPLICATE] Page Transitions in React using Framer Motion
section-engineering-education/engineering-education pull request #7593
Opened 2022-04-19 08:04 UTC by oyedeletemitope

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #7321 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-04-19 19:05 UTC, hectorkambow commented
#7519

2022-04-19 19:06 UTC, hectorkambow commented
![image](https://user-images.githubusercontent.com/60800358/164077314-b6f26bd5-bcad-48ce-8e79-fa581de14366.png)

2022-04-19 19:32 UTC, oyedeletemitope commented
Hello @hectorkambow is there anything I did wrong while submitting?

2022-04-19 20:08 UTC, hectorkambow commented
Possibly the repo was not forked properly - be sure to refer to our docs for more details. 👍

2022-04-20 16:55 UTC, oyedeletemitope commented
Hello @hectorkambow  I tried making some changes if the error still persists then I think I’ll have clone the repo again and close this pr

2022-05-02 17:53 UTC, srishilesh requested changes
Hey @oyedeletemitope ,

I've suggested some minor changes. Please go through them carefully, and ping me when you're done.

Thanks.

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +For some, transitioning from page to page has often seemed difficult. We can archive that using a library called framer motion.
What is the objective of this tutorial? State what is going to be covered here

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +Framer Motion is an animation library that makes it so simple to create animations. Its simplified API allows us to extract the complexities of animations. Thus creating animations with ease. An open
Add link to Framer motion

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +Framer Motion is an animation library that makes it so simple to create animations. Its simplified API allows us to extract the complexities of animations. Thus creating animations with ease. An open
Add any example website that uses framer motion

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +## What is framer motion?
Start the markdown header from `###`

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +
What are we going to build? State the objective of the code project.

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +
Add explanation of the above code as bulleted points.

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +Here, we imported our `Routes`, `Route`, and `useLocation` from react-router-dom. `Routes` are a significant improvement over the `Switch` element in v5. The route will allow us to go to each of the
Make this as bulleted points.

2022-05-02 17:53 UTC, srishilesh commented on content/articles/page-transitions-in-react-using-framer-motion/index.md
> +Our main discussion was about framer motion as a tool for making page transitions in React. We also were able to make page transitions by making use of it in our project. Would you please share if th
Add any reference links that might help the reader

2022-05-04 01:08 UTC, oyedeletemitope commented
@srishilesh changes made as requested

2022-05-11 19:38 UTC, srishilesh approved these changes
Hey @oyedeletemitope ,

Make sure to go through the changes I've made.

Moving for the final review.

Thanks.

2022-05-12 04:07 UTC, oyedeletemitope commented
Thanks @srishilesh i’ll go through them

2022-06-15 17:06 UTC, hectorkambow commented
@oyedeletemitope 

well done - I'd recommend you add a skill section to your author profile. 

This will go a long way for future potential employers.

2022-06-15 17:06 UTC, merged

2022-06-15 17:08 UTC, oyedeletemitope commented
Thank you @hectorkambow i’ll be sure to do that next time

2022-06-15 17:18 UTC, hectorkambow commented
👍  

Fantastic - once the article is live (to help it gain more traction) be sure to share it on LinkedIn & Twitter (and tag us if you could). 

This will give your freshly published article a nice boost of engagement. 

Also note you can see the # of page view your articles get via the EngEd site.