Visualizing data generated for a random walk using Python
section-engineering-education/engineering-education pull request #7606
Opened 2022-04-21 09:50 UTC by duncandegwa

### Article checklist

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

This closes #7247

2022-04-23 13:24 UTC, louisefindlay23 commented
Plagiarism check complete

2022-04-25 16:57 UTC, srishilesh commented
Hey @BrianaNzivu ,

I have completed all the reviews in my backlog, and I'm waiting for the CM's final review. Just checking if I can take up this PR for review, since you have many in your backlog already.

Let me know.

Thanks.

2022-04-25 17:44 UTC, BrianaNzivu commented
Hey @srishilesh .
Sure.

2022-04-26 13:26 UTC, srishilesh commented
Hey @BrianaNzivu ,

Thank you.

2022-04-26 13:42 UTC, srishilesh requested changes
Hey @duncandegwa ,

Great work.

I have suggested some minor changes. Please ping me when you are done.

Thanks.

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> +
Before we get started with the implementation, can you add a sub-topic that discusses where we would use this? Any application of it? How it is used?

Some readers might be new to this.

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> +To design a random walk, we'll construct an `RWalk` class that generates random choices on the basis the trek should go in. Three characteristics are required for the class: a single variable to reco
`Three characteristics are required for the class:`

Make the 3 characteristics as a numbered list.

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> +To design a random walk, we'll construct an `RWalk` class that generates random choices on the basis the trek should go in. Three characteristics are required for the class: a single variable to reco
I find only 2 characteristics. Did you miss any?

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> + rwalk = RWalk()
Fix the indentation

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> + rwalk = RWalk()
Fix the indentation

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> +
Add a GitHub repo URL containing the source code

2022-04-26 13:42 UTC, srishilesh commented on content/articles/generating-data-for-a-random-walk-using-python/index.md
> +Happy coding!
Add a `Further reading` section that contains additional references that the reader can learn from.

2022-04-29 20:44 UTC, duncandegwa commented
Hey @srishilesh  
I have made the minor changes mentioned above
Thanks

2022-06-14 17:22 UTC, hectorkambow commented
👏  

Nicely done!
@duncandegwa 

Also I'd recommend (if you have not already) to add a skill section to your author profile - that will go a long way with future potential employers.

2022-06-14 17:22 UTC, merged