Next.js basics with payroll system
section-engineering-education/engineering-education pull request #7617
Opened 2022-04-23 07:37 UTC by unholydisaster

### Article checklist
[Topic approved](https://github.com/section-engineering-education/engineering-education/issues/7549)

2022-04-23 16:01 UTC, srishilesh commented
@unholydisaster 

Can you please link the issue and your previous PR here?

Will start my tech review soon

2022-04-23 18:27 UTC, unholydisaster commented
[Link issue](https://github.com/section-engineering-education/engineering-education/issues/7549)
[Previous PR](https://github.com/section-engineering-education/engineering-education/pull/7531#event-6450192575)

2022-04-24 14:51 UTC, louisefindlay23 commented
Plagiarism check complete

2022-04-30 16:55 UTC, srishilesh commented
Hey @unholydisaster ,

Just checking if i can reopen this PR and start the review?

2022-05-07 14:35 UTC, unholydisaster commented
You can reopen

2022-05-09 13:07 UTC, srishilesh requested changes
Hey @unholydisaster ,

I've requested for a few changes. Please make sure to go through them carefully.

Ping me when you are done.

Thanks.

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +We will be creating an amazing basic payroll system in Next.js.
A more briefer intro about the project would be good.

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +This tutorial will equip you with the basic arithmetic operators in Next.js and how to effectively use them in functions, for calculations needed in software programming.
You can move this to the intro

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +Npm run dev
```suggestion
npm run dev
```

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +<h4>Net pay=Gross pay - Income tax - Health insurance</h4>
Remove these html tags. Replace them with ` `` `

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +export async function getServerSideProps(context){
Can you please explain more about this function below?

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +
Add a GitHub URL that contains the full source code

2022-05-09 13:07 UTC, srishilesh commented on content/articles/next.js-basics-with-payroll-system/index.md
> +
Add a `Further reading` section that contains reference materials

2022-05-09 15:00 UTC, hectorkambow commented
> You can reopen

Why was the PR closed? 

cc @srishilesh  

If many revisions are needed - we should be closing this PR 👍

2022-05-10 22:48 UTC, unholydisaster commented
Hey, I have already finished the suggestions but I have a problem with my local repository, I need a backup of the .git/config file of the engineering-education repo.

2022-05-11 03:10 UTC, srishilesh commented
> Hey, I have already finished the suggestions but I have a problem with my local repository, I need a backup of the .git/config file of the engineering-education repo.

@unholydisaster 

Are you not able to push the changes? What issue are you facing exactly?

2022-05-11 03:37 UTC, unholydisaster commented
I am not able to push the changes

On Wed, 11 May 2022, 06:10 Srishilesh P S, ***@***.***> wrote:

> Hey, I have already finished the suggestions but I have a problem with my
> local repository, I need a backup of the .git/config file of the
> engineering-education repo.
>
> @unholydisaster <https://github.com/unholydisaster>
>
> Are you not able to push the changes? What issue are you facing exactly?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7617#issuecomment-1123132651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYFABH6DRTY4ETGB37LVJMQKVANCNFSM5UEKN5YQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/7617/c1123132651
> @github.com>
>

2022-05-11 03:49 UTC, srishilesh commented
@unholydisaster 

Can you share a screenshot of the error?

Or you can try opening a new PR.

2022-05-11 20:56 UTC, unholydisaster commented
Hey, I have created the new PR.

2022-05-11 21:00 UTC, unholydisaster commented
Next.js basics with payroll system #7653

2022-05-11 21:26 UTC, closed without merging

2022-05-11 21:32 UTC, unholydisaster commented
Please notify the reviewer of the new PR

On Thu, 12 May 2022, 00:26 hectorkambow, ***@***.***> wrote:

> Closed #7617
> <https://github.com/section-engineering-education/engineering-education/pull/7617>
> .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7617#event-6593738339>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYAG6POXSH3MMCXB3H3VJQQZFANCNFSM5UEKN5YQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/7617/issue_event/6593738339
> @github.com>
>

2022-10-11 08:24 UTC, unholydisaster commented
I don't know how but my systems app data got erased. Am going to make a new
PR with the changes and notify you.

On Wed, 11 May 2022, 06:49 Srishilesh P S, ***@***.***> wrote:

> @unholydisaster <https://github.com/unholydisaster>
>
> Can you share a screenshot of the error?
>
> Or you can try opening a new PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7617#issuecomment-1123151678>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYGCM5LZNLCDAAUES7TVJMU3PANCNFSM5UEKN5YQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/7617/c1123151678
> @github.com>
>