Next.js basics with payroll system
section-engineering-education/engineering-education pull request #7653
Opened 2022-05-11 20:54 UTC by unholydisaster

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-05-12 21:28 UTC, unholydisaster commented
Am I still on the right track, I drafted the PR according to your instruction.

2022-05-13 04:30 UTC, srishilesh commented
I'll do a tech review ASAP. Will let you know if there are any more suggestions.

2022-05-23 14:09 UTC, unholydisaster commented
Yoh, what's up with the review

2022-05-24 11:57 UTC, srishilesh commented
Hey,

Will review it asap.

2022-06-04 06:24 UTC, unholydisaster commented
Hey, is something wrong with the article ?

2022-06-06 08:53 UTC, srishilesh commented
Hey,

I'll review it soon. I have been busy for the past few weeks.

2022-06-11 01:01 UTC, srishilesh commented
The review will be done by this weekend.

2022-06-11 08:33 UTC, unholydisaster commented
Thanks 👍

On Sat, 11 Jun 2022, 04:02 Srishilesh P S, ***@***.***> wrote:

> The review will be done by this weekend.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1152822801>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYF7EKNCRVXT74QEC2LVOPQQVANCNFSM5VWFLYVQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <section-engineering-education/engineering-education/pull/7653/c1152822801
> @github.com>
>

2022-06-13 14:17 UTC, srishilesh commented
Review is in-progress

2022-06-13 17:36 UTC, srishilesh requested changes
Hey @unholydisaster ,

Apologies for the delay in review.

On going through your tutorial, I find that we might need to work on some major improvements. I've added a few suggestions. I would also advise you to take a look at other published articles to see how the authors have structured the flow of the article.

Don't just state the code snippets, instead explain them.

Make sure to do all the changes and ping me when you are done.

Thanks.

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +In this tutorial, we learn basics of Next.js and how we can use them effectively to build a payroll system.
Can you add an intro about NextJS? Where we use it? How it is better than React? What is it?

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +In this tutorial, we will use Node.js will be needed for the javascript runtime needed.
Why are we using NodeJS? Please mention the reason

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +npx create-next-app@latest
Shouldn't you specify the name of the app here?

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +We need timesheet data but in our case, we are going to create it locally and store it in our file system.
Please use ` `` ` for keywords, file names, variables and so on

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +In order for this to work as planned, we will have to create an API route for data fetching. Navigate to the Pages folder and open the API folder that contains a hello.js file, edit the file by erasi
What methods are we building? What do they do?

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +We are going to use a .map() function to iterate our data and create a list from this data.
You can state them above the code snippets

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +                <Link href={`/${Data._Fullname}`} passHref>
Code needs formatting

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +    const employed=await data.json()
Explain

2022-06-13 17:36 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +```
Explain the above code as bulleted points

2022-06-15 11:46 UTC, unholydisaster commented
Hey, finished all changes requested 👍

2022-06-17 06:43 UTC, WanjaMIKE commented
Plagiarism check is done

2022-06-20 06:15 UTC, unholydisaster commented
Hey, all suggestions done ✅

2022-06-20 13:28 UTC, srishilesh requested changes
Hey @unholydisaster ,

On going through the tutorial, I found that it is a little short on content. We have other tutorials that introduces the reader to NextJS. I would suggest you to improve the existing article by adding more content that are valuable or build a full working application (do not break down this implementation into the next tutorial).

Also, perform a grammar check. Feel free to go through my articles to see how I have formatted them.

Thanks.

2022-06-20 13:28 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +The installation will begin and you will be asked to name the application, let's call it payroll.
```suggestion
The installation will begin and you will be asked to name the application, let's call it `payroll`.
```

2022-06-20 13:28 UTC, srishilesh commented on content/articles/building-a-payroll-system-with-nextjs/index.md
> +A payroll system is a process of calculating employees' pay for work performed during a specific period. In search a system, a timekeeping system is required to approve the hours worked, Overtime and
Is a process?

2022-07-01 21:36 UTC, hectorkambow commented
Our team has been working diligently to clear the backlog and we should be getting this pull request ready to be published next week 🚀

2022-07-02 11:02 UTC, srishilesh commented
Hey @unholydisaster ,

I don't see any latest commits. Did you forget to push them ?

2022-07-02 11:05 UTC, unholydisaster commented
I will push them today.

On Sat, Jul 2, 2022 at 2:02 PM Srishilesh P S ***@***.***>
wrote:

> Hey @unholydisaster <https://github.com/unholydisaster> ,
>
> I don't see any latest commits. Did you forget to push them ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1172879641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYDWGYP2AU56YWG37UTVSAOT5ANCNFSM5VWFLYVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/7653/c1172879641
> @github.com>
>

2022-07-04 10:35 UTC, unholydisaster commented
Hey, suggestions done ✅

On Sat, 2 Jul 2022, 14:05 Casaneli, ***@***.***> wrote:

> I will push them today.
>
> On Sat, Jul 2, 2022 at 2:02 PM Srishilesh P S ***@***.***>
> wrote:
>
>> Hey @unholydisaster <https://github.com/unholydisaster> ,
>>
>> I don't see any latest commits. Did you forget to push them ?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1172879641>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOQNVYDWGYP2AU56YWG37UTVSAOT5ANCNFSM5VWFLYVQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> <section-engineering-education/engineering-education/pull/7653/c1172879641
>> @github.com>
>>
>

2022-07-13 19:51 UTC, hectorkambow commented
@unholydisaster 

Hello Eli - and thank you for submitting your 1st article to be published. 

Please keep in mind that we ask students only to submit polished and ready-to-be-published articles. 

Articles should be proof-read and the code should be already reviewed to increase the review process. 

EngEd Peer Reviewers are here to help make sure there are not any GLARING errors and to close the pull request if needed. 

These articles are public-facing and students should keep in mind that it will reflect how the larger DEV community will view your work/projects/skills. - and can impact your software career journey 🚀 .

2022-07-13 20:21 UTC, unholydisaster commented
Thanks alot 👍

2022-07-29 20:02 UTC, merged

2022-07-29 20:17 UTC, hectorkambow commented
@unholydisaster 

Eli please be sure to review and go over any and all edits suggested by your peer reviewer or made by myself - to improve future articles/blog posts. 

You'll be able to see your live published article on the site (in about 30 mins or so).

To give your article a boost in page engagement - be sure to share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction/exposure as well!

I believe this is your 1st EngEd article that was published - you may have forgot to add/create an author page to go alongside your articles (as instructed in the EngEd docs).

NOTE: Also, take into consideration that you can add any other past projects of yours: videos, talks, tutorials, articles (on ANY other site) - you can add them to your EngEd profile.

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.

Think of the EngEd profile as your one-stop shop for everything you do in DEV - making it easier for you to share all your accomplishments when you go out for an interview or employment opp.

It can be from any blog site (or site in general).

Let me know if you have any questions moving forward.

**_Also important NOTE: We wanted to mention that we're going to take a focus on content centered around Kubernetes (K8s) for the month of August._**

The best five (5) K8s related articles that come in this month will be eligible to receive a complimentary virtual pass to [KubeCon USA](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/) ($75.00 value) in Oct.

We're looking for content that enriches developers' understanding of K8s, best practices, and its many use cases.
Please be sure to go over the already [published content the EngEd community has created on Kubernetes](https://www.section.io/engineering-education/search/?q=kubernetes) to see where we can build upon or further explore. 🚀

2022-07-29 20:44 UTC, unholydisaster commented
Thanks alot Hector

On Fri, 29 Jul 2022, 23:17 hectorkambow, ***@***.***> wrote:

> @unholydisaster <https://github.com/unholydisaster>
>
> Eli please be sure to review and go over any and all edits suggested by
> your peer reviewer or made by myself - to improve future articles/blog
> posts.
>
> You'll be able to see your live published article on the site (in about 30
> mins or so).
>
> To give your article a boost in page engagement - be sure to share it
> across your social site (LinkedIn/Twitter) and tag the EngEd program so we
> can also share it and give it some traction/exposure as well!
>
> I believe this is your 1st EngEd article that was published - you may have
> forgot to add/create an author page to go alongside your articles (as
> instructed in the EngEd docs).
>
> NOTE: Also, take into consideration that you can add any other past
> projects of yours: videos, talks, tutorials, articles (on ANY other site) -
> you can add them to your EngEd profile.
>
> If you have not done so already - consider adding a skill section to your
> author page. This will go a long way for potential future employers.
>
> Think of the EngEd profile as your one-stop shop for everything you do in
> DEV - making it easier for you to share all your accomplishments when you
> go out for an interview or employment opp.
>
> It can be from any blog site (or site in general).
>
> Let me know if you have any questions moving forward.
>
> *Also important NOTE: We wanted to mention that we're going to take a
> focus on content centered around Kubernetes (K8s) for the month of August.*
>
> The best five (5) K8s related articles that come in this month will be
> eligible to receive a complimentary virtual pass to KubeCon USA
> <https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/>
> ($75.00 value) in Oct.
>
> We're looking for content that enriches developers' understanding of K8s,
> best practices, and its many use cases.
> Please be sure to go over the already published content the EngEd
> community has created on Kubernetes
> <https://www.section.io/engineering-education/search/?q=kubernetes> to
> see where we can build upon or further explore. 🚀
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1199914721>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYBJWLYSQMJ73RQTQELVWQ37BANCNFSM5VWFLYVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/7653/c1199914721
> @github.com>
>

2022-07-29 20:50 UTC, unholydisaster commented
It's my rightful duty to follow all suggestions.

On Fri, 29 Jul 2022, 23:43 Casaneli, ***@***.***> wrote:

> Thanks alot Hector
>
> On Fri, 29 Jul 2022, 23:17 hectorkambow, ***@***.***> wrote:
>
>> @unholydisaster <https://github.com/unholydisaster>
>>
>> Eli please be sure to review and go over any and all edits suggested by
>> your peer reviewer or made by myself - to improve future articles/blog
>> posts.
>>
>> You'll be able to see your live published article on the site (in about
>> 30 mins or so).
>>
>> To give your article a boost in page engagement - be sure to share it
>> across your social site (LinkedIn/Twitter) and tag the EngEd program so we
>> can also share it and give it some traction/exposure as well!
>>
>> I believe this is your 1st EngEd article that was published - you may
>> have forgot to add/create an author page to go alongside your articles (as
>> instructed in the EngEd docs).
>>
>> NOTE: Also, take into consideration that you can add any other past
>> projects of yours: videos, talks, tutorials, articles (on ANY other site) -
>> you can add them to your EngEd profile.
>>
>> If you have not done so already - consider adding a skill section to your
>> author page. This will go a long way for potential future employers.
>>
>> Think of the EngEd profile as your one-stop shop for everything you do in
>> DEV - making it easier for you to share all your accomplishments when you
>> go out for an interview or employment opp.
>>
>> It can be from any blog site (or site in general).
>>
>> Let me know if you have any questions moving forward.
>>
>> *Also important NOTE: We wanted to mention that we're going to take a
>> focus on content centered around Kubernetes (K8s) for the month of August.*
>>
>> The best five (5) K8s related articles that come in this month will be
>> eligible to receive a complimentary virtual pass to KubeCon USA
>> <https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/>
>> ($75.00 value) in Oct.
>>
>> We're looking for content that enriches developers' understanding of K8s,
>> best practices, and its many use cases.
>> Please be sure to go over the already published content the EngEd
>> community has created on Kubernetes
>> <https://www.section.io/engineering-education/search/?q=kubernetes> to
>> see where we can build upon or further explore. 🚀
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1199914721>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOQNVYBJWLYSQMJ73RQTQELVWQ37BANCNFSM5VWFLYVQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> <section-engineering-education/engineering-education/pull/7653/c1199914721
>> @github.com>
>>
>

2022-07-29 20:57 UTC, unholydisaster commented
Is there a way, that I can add an author's page to the article.

On Fri, 29 Jul 2022, 23:50 Casaneli, ***@***.***> wrote:

> It's my rightful duty to follow all suggestions.
>
> On Fri, 29 Jul 2022, 23:43 Casaneli, ***@***.***> wrote:
>
>> Thanks alot Hector
>>
>> On Fri, 29 Jul 2022, 23:17 hectorkambow, ***@***.***>
>> wrote:
>>
>>> @unholydisaster <https://github.com/unholydisaster>
>>>
>>> Eli please be sure to review and go over any and all edits suggested by
>>> your peer reviewer or made by myself - to improve future articles/blog
>>> posts.
>>>
>>> You'll be able to see your live published article on the site (in about
>>> 30 mins or so).
>>>
>>> To give your article a boost in page engagement - be sure to share it
>>> across your social site (LinkedIn/Twitter) and tag the EngEd program so we
>>> can also share it and give it some traction/exposure as well!
>>>
>>> I believe this is your 1st EngEd article that was published - you may
>>> have forgot to add/create an author page to go alongside your articles (as
>>> instructed in the EngEd docs).
>>>
>>> NOTE: Also, take into consideration that you can add any other past
>>> projects of yours: videos, talks, tutorials, articles (on ANY other site) -
>>> you can add them to your EngEd profile.
>>>
>>> If you have not done so already - consider adding a skill section to
>>> your author page. This will go a long way for potential future employers.
>>>
>>> Think of the EngEd profile as your one-stop shop for everything you do
>>> in DEV - making it easier for you to share all your accomplishments when
>>> you go out for an interview or employment opp.
>>>
>>> It can be from any blog site (or site in general).
>>>
>>> Let me know if you have any questions moving forward.
>>>
>>> *Also important NOTE: We wanted to mention that we're going to take a
>>> focus on content centered around Kubernetes (K8s) for the month of August.*
>>>
>>> The best five (5) K8s related articles that come in this month will be
>>> eligible to receive a complimentary virtual pass to KubeCon USA
>>> <https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/>
>>> ($75.00 value) in Oct.
>>>
>>> We're looking for content that enriches developers' understanding of
>>> K8s, best practices, and its many use cases.
>>> Please be sure to go over the already published content the EngEd
>>> community has created on Kubernetes
>>> <https://www.section.io/engineering-education/search/?q=kubernetes> to
>>> see where we can build upon or further explore. 🚀
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1199914721>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AOQNVYBJWLYSQMJ73RQTQELVWQ37BANCNFSM5VWFLYVQ>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> <section-engineering-education/engineering-education/pull/7653/c1199914721
>>> @github.com>
>>>
>>

2022-07-29 20:58 UTC, hectorkambow commented
That was my mistake - I did not see the author file. 

I've went ahead and added it for you.  & also created a skill section for you (feel free to add any skills you see fit)

2022-07-29 21:08 UTC, unholydisaster commented
Thanks 👍, God bless you.

On Fri, 29 Jul 2022, 23:59 hectorkambow, ***@***.***> wrote:

> That was my mistake - I did not see the author file.
>
> I've went ahead and added it for you. & also created a skill section for
> you (feel free to add any skills you see fit)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/section-engineering-education/engineering-education/pull/7653#issuecomment-1199940972>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQNVYH2ABQNYFTBH4VXG73VWRAZRANCNFSM5VWFLYVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <section-engineering-education/engineering-education/pull/7653/c1199940972
> @github.com>
>