Working with bash arrays
section-engineering-education/engineering-education pull request #7696
Opened 2022-06-15 10:22 UTC by Anitaachu

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-07-01 21:36 UTC, hectorkambow commented
Our team has been working diligently to clear the backlog and we should be getting this pull request ready to be published next week 🚀

2022-07-08 11:26 UTC, WanjaMIKE commented
Plagiarism check is done

2022-07-08 18:18 UTC, WanjaMIKE commented
Sure, he can take it over @

2022-07-10 04:26 UTC, hectorkambow commented
👍  Thank you @WanjaMIKE  
@Youngshark3  

Be sure to reach out if you have any questions along the way - be sure to use the comment feature via GitHub to leave notes.

2022-07-10 22:12 UTC, Youngshark3 commented
> 

okay thanks @hectorkambow on it

2022-07-13 10:47 UTC, Youngshark3 requested changes

2022-07-13 10:47 UTC, Youngshark3 commented on content/articles/working-with-bash-arrays/index.md
> +Bash scripting, just like with other programming languages and scripting tools allows you to create variables, run for loops, apply conditional logic, and more importantly, you can work with arrays w
i find this sentence too long break it down to increase readability

2022-07-13 10:47 UTC, Youngshark3 commented on content/articles/working-with-bash-arrays/index.md
> +
these codes are not inorder kindly edit them

2022-07-16 14:11 UTC, Youngshark3 commented
@Anitaachu okay checking

2022-07-18 12:26 UTC, Youngshark3 commented
cc @WanjaMIKE @hectorkambow done its okay for the next step

2022-07-18 16:57 UTC, hectorkambow commented
Did you complete the prelim review - or the tech review portion?? @Youngshark3

2022-07-18 16:57 UTC, hectorkambow commented
If both are complete - we can add the "ready for final review" 👍

2022-07-18 22:46 UTC, Youngshark3 commented
@hectorkambow  yeah everything is fine. Done both prelim and tech review

2022-07-19 19:44 UTC, hectorkambow commented
🚀  

Fantastic !!! We will be sure to give this a final review and assess the PR 👏  

Nicely done.

2022-07-20 15:33 UTC, hectorkambow commented
👏  

Nicely done @Anitaachu  & @Youngshark3 

🚀  

Please be sure to go over any edits made to the PR to improve future blog posts and reviews. 


@Anitaachu 
You'll be able to see your live published article on the site (in about 30 mins or so).

To give your article a boost in page engagement - _**be sure to share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction/exposure as well!**_

**If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.**

>NOTE: Also, take into consideration that you can add any other past projects of yours: videos, talks, tutorials, articles (on ANY >other site) - you can add them to your EngEd profile.
>
>Think of the EngEd profile as your one-stop shop for everything you do in DEV - making it easier for you to share all your >accomplishments when you go out for an interview or employment opp.
>
>It can be from any blog site (or site in general).

Let me know if you have any questions moving forward.

2022-07-20 15:37 UTC, Youngshark3 commented
Thanks @hectorkambow and congratulations 🎉@Anitaachu

2022-07-20 17:13 UTC, merged

2022-07-29 21:09 UTC, hectorkambow commented
@Anitaachu 
Hello hello! 

We wanted to announce that we're going to take a focus on content centered around Kubernetes (K8s) for the month of August.

We have enjoyed reading all amazing content that has been created the last few months - and with so much to explore with K8s we wanted to invite the community to approach it.

**Wit_h that said, the best five (5) K8s related articles that come in this month will be eligible to receive a complimentary virtual pass to [KubeCon USA](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/) ($75.00 value) in Oct.
We're looking for content that enriches developers' understanding of K8s, best practices, and its many use cases.**_

Please be sure to go over the already [published content the EngEd community has created on Kubernetes](https://www.section.io/engineering-education/search/?q=kubernetes) to see where we can build upon or further explore.

While we're not restricting content solely to K8s-related articles over the next month, we will prioritize acceptance and review of K8s content over other topics.

Please be sure to complete the [topic suggestion form](https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=) when you're ready to dive in.

Happy coding!