Custom Decorators in Django
section-engineering-education/engineering-education pull request #7726
Opened 2022-07-01 17:31 UTC by BOVAGE

### Article checklist

## Attention
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

#### Pre-submission checks
> Please ensure that you have only one open topic suggestion (issue) + in-review article (linked pull request) at a time. This will ensure that we complete the review process in a timely manner from inception to publishing

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
> Remove the backticks and add the issue number below to link and close your Topic Suggestion (issue) when your article has been published (PR has been merged). See this [video](https://youtu.be/TKJ4RdhyB5Y?t=278) for more details.

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

2022-07-01 17:47 UTC, hectorkambow commented
🚀

2022-07-01 17:47 UTC, hectorkambow commented
@BOVAGE 

Question, does this pull request have a corresponding topic suggestion form?

2022-07-01 18:06 UTC, hectorkambow commented
👍  

Thank you - just needed to make sure they were linked (see image) that way once the article is published (merged) it auto-closes the topic form as well. 

![image](https://user-images.githubusercontent.com/60800358/176947661-000d383d-53d3-46bf-b1e4-6af7b37235c3.png)

2022-07-01 18:12 UTC, BOVAGE commented
> 👍
> 
> Thank you - just needed to make sure they were linked (see image) that way once the article is published (merged) it auto-closes the topic form as well.
> 
> ![image](https://user-images.githubusercontent.com/60800358/176947661-000d383d-53d3-46bf-b1e4-6af7b37235c3.png)

Okay sir. Got it

2022-07-05 16:58 UTC, hectorkambow commented
@BOVAGE just noticed that you have not included any author details (to create your author profile).

This is how your articles will be listed under your profile.

In order to publish the article we would need your author details - please see the new contributor folder for more info on how to submit.

2022-07-05 20:21 UTC, BOVAGE commented
> @BOVAGE just noticed that you have not included any author details (to create your author profile).
> 
> This is how your articles will be listed under your profile.
> 
> In order to publish the article we would need your author details - please see the new contributor folder for more info on how to submit.

I added the author details now sir.

2022-07-08 11:23 UTC, WanjaMIKE commented
Plagiarism check is done

2022-07-13 09:24 UTC, WanjaMIKE commented
Hello @BOVAGE  I will get started on this technical review as soon as possible. Sorry for the delay. Thanks

2022-07-13 18:17 UTC, hectorkambow commented
@Collince-Okeyo would like to do a test review on this PR 

@WanjaMIKE  if you have not started yet. 

👍

2022-07-13 20:54 UTC, WanjaMIKE commented
Sure, @Collince-Okeyo you can take up the PR. Thanks

2022-07-13 20:55 UTC, hectorkambow commented
🚀  

Thank you Mike 

@Collince-Okeyo  

@WanjaMIKE is a veteran in the program - he is always a reliable resource if you have any questions as well. 💯

2022-07-14 08:24 UTC, Collince-Okeyo commented
> Sure, @Collince-Okeyo you can take up the PR. Thanks

Thank you @hectorkambow and @WanjaMIKE for this opportunity

2022-07-18 18:32 UTC, Collince-Okeyo requested changes
@BOVAGE ,
Please correct the suggested corrections then let me know to proceed with the review. Thank you...

2022-07-18 18:32 UTC, Collince-Okeyo commented on content/articles/custom-decorators-in-django/index.md
> +
Remove space

2022-07-18 18:32 UTC, Collince-Okeyo commented on content/articles/custom-decorators-in-django/index.md
> +> The default authentication backend does not return a user object for in active users. So if a user who created an account using the register.html won't be able to login unless the admin makes the u
Replace with...
The default authentication backend does not return a user object for inactive users. So a user who created an account using the 'register.html' won't be able to login unless the admin makes the user active.

2022-07-18 18:32 UTC, Collince-Okeyo commented on content/articles/custom-decorators-in-django/index.md
> +Inside posts/views.py
Replace with...
Now to implement the 'xhr_request_only' decorator created earlier, add the following code inside 'posts/views.py.'

2022-07-18 18:32 UTC, Collince-Okeyo commented on content/articles/custom-decorators-in-django/index.md
> +- The built-in require_POST decorator has been used on the post_vote_view to ensure  that it only accepts the POST request method.
Replace with...
The built-in require_POST decorator has been used on the 'post_vote_view' to ensure that it only accepts the 'POST' request method.

2022-07-19 06:18 UTC, BOVAGE commented
@Collince-Okeyo, I have made the suggested changes. Thank you.

2022-07-19 09:07 UTC, Collince-Okeyo approved these changes

2022-07-19 18:40 UTC, hectorkambow commented
@Collince-Okeyo 

It looks like this PR is ready for a "ready for final review" label? 

Assuming both prelim & tech review have been completed?

2022-07-21 07:51 UTC, Collince-Okeyo commented
> @Collince-Okeyo
> 
> It looks like this PR is ready for a "ready for final review" label?
> 
> Assuming both prelim & tech review have been completed?

@hectorkambow , thank you for following up,...

The PR is ready for a "ready for final review" label since all the reviews are completed.

2022-07-23 15:49 UTC, Collince-Okeyo commented
Hello @hectorkambow ,

Please add the 'ready for final review' tag to this PR

2022-07-28 12:22 UTC, BOVAGE commented
Hello @hectorkambow.

@Collince-Okeyo is done with the review.

2022-07-28 19:12 UTC, hectorkambow commented
Thank you for the ping @BOVAGE  

I lose many notification in my inbox.

2022-07-28 20:34 UTC, hectorkambow commented
@BOVAGE 
Well done ! 

Please review any edits made by your peer reviewer (or myself) to improve future blog post.

You'll be able to see your live published article on the site (in about 30 mins or so).

To give your article a boost in page engagement - be sure to share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction/exposure as well!

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.

NOTE: Also, take into consideration that you can add any other past projects of yours: videos, talks, tutorials, articles (on ANY other site) - you can add them to your EngEd profile.

Think of the EngEd profile as your one-stop shop for everything you do in DEV - making it easier for you to share all your accomplishments when you go out for an interview or employment opp.

It can be from any blog site (or site in general).

Let me know if you have any questions moving forward.

Also important NOTE: We wanted to mention that we're going to take a focus on content centered around Kubernetes (K8s) for the month of August.

The best five (5) K8s related articles that come in this month will be eligible to receive a complimentary virtual pass to [KubeCon USA](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/) ($75.00 value) in Oct.

We're looking for content that enriches developers' understanding of K8s, best practices, and its many use cases.
Please be sure to go over the already [published content the EngEd community has created on Kubernetes](https://www.section.io/engineering-education/search/?q=kubernetes) to see where we can build upon or further explore. 🚀

2022-07-28 20:34 UTC, merged